### ISSUE TITLE
[QUESTION] Streaming attempt failed 0x5200000e

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1003]
Streaming attempt failed 0x5200000e and want to know why
[osc_streaming_failed_12042020.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5671874/osc_streaming_failed_12042020.log)

Error list
20045:12-04 08:00:43.775: [ 479][I]2020-12-04 13:00:42 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
20046:12-04 08:00:44.021: [ 479][I]2020-12-04 13:00:42 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
20051:12-04 08:00:44.122: [ 479][I]2020-12-04 13:00:42 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
20052:12-04 08:00:44.172: [ 479][I]2020-12-04 13:00:42 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
20053:12-04 08:00:44.319: [ 479][I]2020-12-04 13:00:42 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
20054:12-04 08:00:44.319: [ 479][I]2020-12-04 13:00:42 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
20055:12-04 08:00:44.319: [ 479][I]2020-12-04 13:00:42 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
20056:12-04 08:00:44.319: [ 479][I]2020-12-04 13:00:42 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
20057:12-04 08:00:44.319: [ 479][I]2020-12-04 13:00:42 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
38648:12-04 09:53:44.547: [ 479][I]2020-12-04 14:53:42 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
38650:12-04 09:53:44.786: [ 479][I]2020-12-04 14:53:43 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
38651:12-04 09:53:44.786: [ 479][I]2020-12-04 14:53:43 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
38652:12-04 09:53:45.330: [ 479][I]2020-12-04 14:53:43 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
38653:12-04 09:53:45.380: [ 479][I]2020-12-04 14:53:43 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
38654:12-04 09:53:45.493: [ 479][I]2020-12-04 14:53:43 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
38655:12-04 09:53:45.493: [ 479][I]2020-12-04 14:53:43 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
39141:12-04 09:54:42.894: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
39142:12-04 09:54:42.894: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
39143:12-04 09:54:42.894: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
39162:12-04 09:54:42.946: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
39163:12-04 09:54:42.946: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
39164:12-04 09:54:42.946: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
39165:12-04 09:54:42.947: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
39166:12-04 09:54:42.947: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
39167:12-04 09:54:42.948: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
39168:12-04 09:54:42.948: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
39172:12-04 09:54:42.949: [4844][I]2020-12-04 14:54:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
39182:12-04 09:54:42.952: [4844][I]2020-12-04 14:54:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
41565:12-04 10:20:34.316: [ 479][I]2020-12-04 15:20:34 ERROR   connectSignalingChannelLws(): operation returned status code: 0x0000000f
45209:12-04 11:00:04.725: [ 479][I]2020-12-04 16:00:04 ERROR   blockingCurlCall(): Curl perform failed for url https://c2dl21inrrhxl7.credentials.iot.us-west-2.amazonaws.com/role-aliases/KvsCameraIoTRoleAlias1/credentials with result Timeout was reached : Operation timed out after 3002 milliseconds with 0 out of 0 bytes received
52781:12-04 11:42:15.253: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
52782:12-04 11:42:15.254: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
52798:12-04 11:42:15.254: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
52799:12-04 11:42:15.255: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
52800:12-04 11:42:15.255: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
52801:12-04 11:42:15.255: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
52802:12-04 11:42:15.255: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
52803:12-04 11:42:15.255: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
52804:12-04 11:42:15.255: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
52805:12-04 11:42:15.255: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
52806:12-04 11:42:15.255: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
52807:12-04 11:42:15.255: [ 478][I]2020-12-04 16:42:14 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
52823:12-04 11:42:16.105: [ 478][I]2020-12-04 16:42:15 ERROR   turnConnectionSendData(): operation returned status code: 0x5a000027
52824:12-04 11:42:16.105: [ 478][I]2020-12-04 16:42:15 ERROR   iceUtilsSendData(): operation returned status code: 0x5a000027
52825:12-04 11:42:16.105: [ 478][I]2020-12-04 16:42:15 ERROR   iceUtilsSendStunPacket(): operation returned status code: 0x5a000027
52827:12-04 11:42:16.105: [ 478][I]2020-12-04 16:42:15 ERROR   turnConnectionSendData(): operation returned status code: 0x5a000027
52828:12-04 11:42:16.105: [ 478][I]2020-12-04 16:42:15 ERROR   iceUtilsSendData(): operation returned status code: 0x5a000027
52829:12-04 11:42:16.105: [ 478][I]2020-12-04 16:42:15 ERROR   iceUtilsSendStunPacket(): operation returned status code: 0x5a000027
52845:12-04 11:42:16.157: [ 478][I]2020-12-04 16:42:15 ERROR   turnConnectionSendData(): operation returned status code: 0x5a000027
52846:12-04 11:42:16.157: [ 478][I]2020-12-04 16:42:15 ERROR   iceUtilsSendData(): operation returned status code: 0x5a000027
52847:12-04 11:42:16.157: [ 478][I]2020-12-04 16:42:15 ERROR   iceUtilsSendStunPacket(): operation returned status code: 0x5a000027
52849:12-04 11:42:16.157: [ 478][I]2020-12-04 16:42:15 ERROR   turnConnectionSendData(): operation returned status code: 0x5a000027
52850:12-04 11:42:16.157: [ 478][I]2020-12-04 16:42:15 ERROR   iceUtilsSendData(): operation returned status code: 0x5a000027
52851:12-04 11:42:16.158: [ 478][I]2020-12-04 16:42:15 ERROR   iceUtilsSendStunPacket(): operation returned status code: 0x5a000027
72748:12-04 14:48:14.485: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
72749:12-04 14:48:14.485: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
72752:12-04 14:48:14.486: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
72753:12-04 14:48:14.486: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
72754:12-04 14:48:14.486: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
72760:12-04 14:48:14.533: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
72761:12-04 14:48:14.533: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
72763:12-04 14:48:14.534: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
72768:12-04 14:48:14.535: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
72769:12-04 14:48:14.535: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
72770:12-04 14:48:14.535: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
72771:12-04 14:48:14.535: [ 480][I]2020-12-04 19:48:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
73441:12-04 14:57:56.062: [ 480][I]2020-12-04 19:57:55 ERROR   signalingGetIceConfigInfoCout(): operation returned status code: 0x5200000e
73453:12-04 14:57:56.065: [ 480][I]2020-12-04 19:57:55 ERROR   closePeerConnection(): operation returned status code: 0x00000001
73454:12-04 14:57:56.066: [ 480][I]2020-12-04 19:57:55 ERROR   freeSampleStreamingSession(): operation returned status code: 0x00000001
73455:12-04 14:57:56.066: [ 480][I]2020-12-04 19:57:55 ERROR   signalingMessageReceived(): operation returned status code: 0x5200000e
73456:12-04 14:57:56.066: [ 480][I]2020-12-04 19:57:55 ERROR   receiveLwsMessageWrapper(): operation returned status code: 0x5200000e
73645:12-04 15:00:18.463: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
73646:12-04 15:00:18.464: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
73648:12-04 15:00:18.465: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
73649:12-04 15:00:18.465: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
73650:12-04 15:00:18.465: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
73651:12-04 15:00:18.466: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
73652:12-04 15:00:18.513: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
73653:12-04 15:00:18.514: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
73654:12-04 15:00:18.515: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
73655:12-04 15:00:18.515: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
73656:12-04 15:00:18.516: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
73657:12-04 15:00:18.516: [ 480][I]2020-12-04 20:00:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005

sdk commit: baefcb52d

**Comment by MushMal** [comment]
Status code 0x5200000e is defined here: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/state/include/com/amazonaws/kinesis/video/state/Include.h#L26

and you can get some info in the KVS docs as well https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-errors.html

The logs clearly show that your client failed to connect

```
41565:12-04 10:20:34.316: [ 479][I]2020-12-04 15:20:34 ERROR connectSignalingChannelLws(): operation returned status code: 0x0000000f
45209:12-04 11:00:04.725: [ 479][I]2020-12-04 16:00:04 ERROR blockingCurlCall(): Curl perform failed for url https://c2dl21inrrhxl7.credentials.iot.us-west-2.amazonaws.com/role-aliases/KvsCameraIoTRoleAlias1/credentials with result Timeout was reached : Operation timed out after 3002 milliseconds with 0 out of 0 bytes received

```

after which the application attempts to call an API that


`73441:12-04 14:57:56.062: [ 480][I]2020-12-04 19:57:55 ERROR signalingGetIceConfigInfoCout(): operation returned status code: 0x5200000e`





I didn't spend time looking through the logs. Please check your logs and see if there is anything else you need. 

You also didn't mention whether you are using stock samples or you are using your own application when you get this ?

**Comment by MushMal** [comment]
Please resolve this issue if you have no further questions regarding the invalid streaming state error. If you need help with other related issues then cut a new issue

**Comment by henryChmn** [comment]
This fail are using our own application, and for this situation not sure how to deal with it in application code, do you have any suggest for such error?

**Comment by MushMal** [comment]
We can't debug your application. Try to follow the samples.

If the explicit calls are failing then you need to react to this in your application. For example, if creating a signaling client fails then you can't continue and use it to connect or send messages. You need to add some logic to it. For example - progressive back-off retry where your application could attempt to retry in 10 seconds or something. You might also want to have some sort of alarms to trigger when there is no networking. 

I am not exposed to your application or your scenario so I can only give generic directions.

Closing this as the original question has been answered.

**Comment by henryChmn** [comment]
Our application code are totally follow sample code, just not using sample stream files to put frames to KVS.
For the issue report from our customer, it had to create signal channel ready and fail with 0x5200000e error code aslo had check the error reference table and the header file .

12-04 14:53:26.259: connection_state: 9 still connect but 12-04 14:57:56.062 error happen.
and it worked in subsequent attempts
for such things, how can we make it more better?

0x5200000e
12-04 13:18:12.453: [KVS Master] 2. Created signaling channel b0c5ca3f0bcc
![image](https://user-images.githubusercontent.com/58592084/101772581-7f91f500-3b26-11eb-93b1-b798376a9509.png)
![image](https://user-images.githubusercontent.com/58592084/101772770-c7188100-3b26-11eb-8c20-7e78921735a3.png)
![image](https://user-images.githubusercontent.com/58592084/101772865-ec0cf400-3b26-11eb-806b-28ce51b986c1.png)
12-04 13:18:17.009: connection_state: 9
![image](https://user-images.githubusercontent.com/58592084/101773227-73f2fe00-3b27-11eb-9d47-c9a15fa82198.png)
12-04 14:53:26.259: connection_state: 9
![image](https://user-images.githubusercontent.com/58592084/101773361-a3096f80-3b27-11eb-9154-22615f64b8bc.png)
12-04 14:57:56.062: [ 480][I]2020-12-04 19:57:55 ERROR   signalingGetIceConfigInfoCout(): operation returned status code: 0x5200000e

**Comment by MushMal** [comment]
It's not immediately clear to me but it's likely happening while the refresh ICE configuration is in progress. Is there a way we can reproduce this locally?

Who's calling signalingGetIceConfigCount? The sample has a startup code and then it handles errors by re-creating the signaling. This is the case when there are errors after retry,

NOTE: We are moving away from automatic refreshing of ICE.
