### ISSUE TITLE
[QUESTION] bandwidthEstimation behavior

### ISSUE THREAD

**Issue by Yannholo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1004]
I am trying to implement dynamic bitrate into a 1 to n (mostly 2) streaming.

My software is based on the gstreamer master sample.

I would like to have some information on the inner working of the bandwidth estimation as I have observed some disconcerting behaviors.

1. My first attempt was to update the gstreamer pipeline bitrate each time the bandwidthEstimation callback is called :
    - The recommended maximum bitrate goes down rapidly to 5000 and the stream is quite terrible
2. My second attempt was to update the pipeline bitrate in steps :
    - I thought that the quite fast bitrate updating could be the culprit
    - Each time the recommended maximum bitrate goes under a step, the actual bitrate is set to the next lower step
    - The steps : 1280000, 640000, 320000, 160000
    - The recommended maximum bitrate still end up lower than the lowest step
3. My third attempt was to start from the lowest bitrate : 
    - It never goes up

The issue for me is that the recommended maximum bitrate is always under the actual bitrate, even with a static bitrate.
- 5120000 static -> recommended maximum bitrate 2040272
- 1280000 static -> recommended maximum bitrate 950048

The dynamic bitrate is needed to handle networks with slow internet connection and keep good quality with fast internet connections. All the attempts where made using excellent connections that handle flawlessly high static bitrates. So the network don't seams to be the culprit. 

I suppose that I should not use the recommended maximum bitrate as it. 
My attempt to decipher the sdk source code and the rfc3550 didn't help me much.

Let me know if I can give you more information.

**Comment by MushMal** [comment]
Can you please include a lot more details on your setup, including the assets you are using, their commit hash and how you get the data.

**Comment by Yannholo** [comment]
We use the sdk version `1.4.0`.

Our code is based on `samples/kvsWebRTCClientMasterGstreamerSample.c`.
The modifications are mostly removing unnecessary code as we only stream one way video (to many).

The pipeline looks like that : 
```
v4l2src do-timestamp=TRUE device=/dev/video0 !
queue !
videoconvert ! 
video/x-raw,width=640,height=480,framerate=30/1 ! 
omxh264enc control-rate=1 target-bitrate=1280000 periodicity-idr=45 inline-header=FALSE ! 
h264parse config-interval=-1 ! 
video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! 
appsink sync=TRUE emit-signals=TRUE name=appsink-video 
```

The value we update is the `target-bitrate`.

The viewer is based on the samples of the javascript sdk.

What more could help ?

**Comment by Yannholo** [comment]
I made some more tests with the `1.4.0` sample and the KVS WebRTC Test Page.

It seams that the `omxh264enc` is not helping as the `target-bitrate` is not constant event if the `control-rate` is set to constant. 
Nload was used to have a network load for comparison.

I had more chances with the gstSample `video-only testsrc` as I got more logical results.

Still I would like to know how the bandwidthEstimation works ?

It seams to be based on some sort of floating average.

Where can I find documentation or source code on the subject ?

**Comment by disa6302** [comment]
@Yannholo , 

At the moment, we only parse the REMB packet to get receiver bandwidth estimation. The exponent and the mantissa in the packet is used to compute the bandwidth. The reference code can be found [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0417c5b1ab09f6de827ea545f013404de08230a2/src/source/Rtcp/RtcpPacket.c#L109).

**Comment by disa6302** [comment]
Closing assuming question is answered. Feel free to reach if you have any more questions.
