### ISSUE TITLE
[QUESTION] Is the priority of remote candidate always zero?

### ISSUE THREAD

**Issue by yuma-m** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1011]
It looks the priority of remote candidates is always 0 because it is not calculated in `iceAgentAddRemoteCandidate` function. 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/04c86e0c115b57631b1ff49900a61d12eeea0f3f/src/source/Ice/IceAgent.c#L349-L350

On the other hand, the priority of remote candidates is used in `computeCandidatePairPriority` function.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/04c86e0c115b57631b1ff49900a61d12eeea0f3f/src/source/Ice/IceAgent.c#L2647-L2648

I think the priority is defined in RFC 8445 (originally RFC 5245?), is this behavior correct? If the priority of the remote candidate is actually calculated in another part, please let me know.

Thank you.

**Comment by suggestedfixes** [comment]
I'm a fellow user, this is not an official PR, pending approval.

**Comment by hassanctech** [comment]
I've merged the PR, closing this issue.
