### ISSUE TITLE
[QUESTION gstreamer rtsp] gstreamer audio and video through rtsp protocol

### ISSUE THREAD

**Issue by micmet** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1014]
I am trying to modify the gstreamer example [kvsWebRTCClientMasterGstreamerSample.c](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c) in order to be able to  stream audio and video of an ip camera through rtsp.

I am able to stream video only, but I have not been able to build the pipeline that works for both audio and video.

Please help me.

Thank you

**Comment by hassanctech** [comment]
Can you please share which modifications you've made, and specifically what errors you are seeing?  For GStreamer it may be helpful to `export GST_DEBUG=5` to get debug level logs.

**Comment by micmet** [comment]
@hassanctech, 
I changed pipeline definition in the sendGstreamerAudioVideo function. For video only I used 

"rtspsrc location=rtsp://XXX.XXX.XXX/... protocols=\"tcp\" short-header=TRUE "
"! rtph264depay ! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video"

and in the signaling channels console i see the video stream. 

For audio and video i used

"rtspsrc location=rtsp://XXX.XXX.XXX/... protocols=\"tcp\" short-header=TRUE name=source "
"! queue ! rtph264depay ! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video source. "
"! queue ! rtpopusdepay ! opusenc ! audio/x-opus,rate=48000,channels=2 ! appsink sync=TRUE emit-signals=TRUE name=appsink-audio"

but doesn't work. I don't know if the pipeline for audio and video is correct, i need help to define it. 
Attached log file for audio and video test.
[gst_av.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5725207/gst_av.log)

Thank you.

**Comment by disa6302** [comment]
@micmet , 

From the logs, it looks like there is something wrong with `rtpopusdepay` element. Please reach out to GStreamer forums to see how rtsp pipeline can be constructed. We cannot provide much support in constructing a pipeline for your camera device.

**Comment by gmiraval** [comment]
> @hassanctech,
> I changed pipeline definition in the sendGstreamerAudioVideo function. For video only I used
> 
> "rtspsrc location=rtsp://XXX.XXX.XXX/... protocols="tcp" short-header=TRUE "
> "! rtph264depay ! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video"
> 
> and in the signaling channels console i see the video stream.
> 
> For audio and video i used
> 
> "rtspsrc location=rtsp://XXX.XXX.XXX/... protocols="tcp" short-header=TRUE name=source "
> "! queue ! rtph264depay ! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video source. "
> "! queue ! rtpopusdepay ! opusenc ! audio/x-opus,rate=48000,channels=2 ! appsink sync=TRUE emit-signals=TRUE name=appsink-audio"
> 
> but doesn't work. I don't know if the pipeline for audio and video is correct, i need help to define it.
> Attached log file for audio and video test.
> [gst_av.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5725207/gst_av.log)
> 
> Thank you.

This worked for me (my audio was pcm alaw 8000 mono):
Samples.h

typedef struct {
    volatile ATOMIC_BOOL appTerminateFlag;
    volatile ATOMIC_BOOL interrupted;
    volatile ATOMIC_BOOL mediaThreadStarted;
    volatile ATOMIC_BOOL recreateSignalingClient;
    volatile ATOMIC_BOOL connected;
    BOOL useTestSrc;
    PCHAR RtspUrl;
...
} SampleConfiguration, *PSampleConfiguration;

kvsWebRTCClientMasterGstreamerSample.c

                strcpy(pipelineStr, "rtspsrc location=");
                strcat(pipelineStr, pSampleConfiguration->RtspUrl);
                strcat(pipelineStr, " short-header=TRUE name=source ");
                
                strcat(pipelineStr, "source. ! queue ! rtph264depay ! ");
                strcat(pipelineStr, "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! ");
                strcat(pipelineStr, "appsink sync=TRUE emit-signals=TRUE name=appsink-video");
                
                strcat(pipelineStr, " ");
                
                strcat(pipelineStr, "source. ! queue ! rtppcmadepay ! alawdec ! ");
                strcat(pipelineStr, "audioconvert ! audioresample ! opusenc ! audio/x-opus,rate=48000,channels=2 ! ");
                strcat(pipelineStr, "appsink sync=TRUE emit-signals=TRUE name=appsink-audio");
