### ISSUE TITLE
[QUESTION] How to make logger file role over every hour?

### ISSUE THREAD

**Issue by HimanshuVerma18111989** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1018]
Hi,

How to make logger file role over every hour and also is there a way to append DateTime in the name of logger file instead of index?

**Comment by MushMal** [comment]
Default logger file is not rolling based on time but on the size. The parameters are configurable - check out the file logger sources in PIC utils and in c producer common library. 

You might need to override the functionality to get what you need. If your implementation is generic enough then please send a PR so we can merge it with the master branch

**Comment by disa6302** [comment]
@HimanshuVerma18111989 , 

As mentioned by @MushMal , there is not a direct way to rotate based on time. For the filename, unfortunately, the log file name is set to `kvsFileLog` by default. The reference implementation can be found [here](https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/FileLogger.c). What you can do is, use have your implementation of `fileLoggerLogPrintFn` and pass it as:

`createFileLogger(......, yourLogFn)`.  `yourLogFn` can avoid using `stringBufferLen` altogether and use a global rotate period instead to execute `flushLogToFile()` periodically.

If you are okay with the default log file name and all you would like to deal with is rotate period, the easiest way (not the most accurate way) to do this would be to set the `maxStringBufferLen` to a value large enough to gather 'rotate period' worth of logs.

**Comment by disa6302** [comment]
Closing assuming question is answered.
