### ISSUE TITLE
AWS Kinesis Video Streams Webrtc SDK C for Yocto Project

### ISSUE THREAD

**Issue by vijayrakesh13** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1020]
Hi,

I couldn't find any SDK for the Yocto Project, so I decided to download all source files, but I couldn't find com/amazonaws/kinesis/video/common/Include.h file. Kindly, please help me with this regard. Also, please do share the link if any AWS KVS SDK C available for the Yocto Project.

Thanks & Regards,
VR

**Comment by disa6302** [comment]
The Include.h file is available in `src directory`. We do not have anything for the Yocto project. Closing
