### ISSUE TITLE
[QUESTION] How to detect from master side if there are stale sessions

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1023]
After running the sample app for a long time. We noticed there are sessions left in the session list that are stale. From experimentation, seems like turn connections can automatically detect a disconnection. It might have been stun connections that tend to get disconnected without detection. We have already implemented browser-side callbacks for teardowns, this allows most disconnections to be clean. However, in rare cases when the user closes the browser, the teardown signal isn't always sent and we are left with zombie sessions occupying a seat in a list of available sessions.

We wonder what would be the best way to clean up those sessions.
- One idea is to grab stats from somewhere and figure out when the last successful frame is sent.
- Similarly, if it is too difficult to grab the stats, put a custom timestamp variable in the sessions struct that keeps the last successful RTP frame sent.
- Is there a method to register a callback for an event of interest?

**Comment by MushMal** [comment]
It’s not clear what the questions are. The webrtc sdk codebase has a set of callbacks for various events. It also has a set of metrics and stats you can extract. The sample code will automatically cleanup the sessions which have been stale or not properly closed - it takes time for them to trigger the timeout

**Comment by suggestedfixes** [comment]
I've been observing from the background and seeing leftover sessions. I will try to correlate with front end events. I think the sample automatically tears down for TURN. But for stun, the frontend needs to send a peer close signal first, I believe. So closing a browser window might not initiate a callback event, to be verified.

**Comment by hassanctech** [comment]
Resolving due to inactivity.  You can re-open if you still need help.
