### ISSUE TITLE
[QUESTION] How does 1-hour limit affect video?

### ISSUE THREAD

**Issue by atyshka** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1028]
We are considering using this SDK to enable video streaming from a linux device to the internet.

** Logging ** 
N/A

** Any design considerations/constraints **
We would like to perform streaming from our devices to a browser for monitoring. Ideally this could be running for multiple hours a time or possibly 24/7. 

When browsing the usage limits, I noticed that there is a hard limit of 1 hour on connections. However, browsing some issues here it seems like many users successfully have used this for hours at a time. My question is how does this limit affect performance? Will the sdk auto-reconnect? Will there be drop-outs in video and how large? We would like to know how this works before committing to using this product as it's an important reliability consideration.

**Comment by MushMal** [comment]
You are talking about webrtc correct? Once the streaming is connected and is streaming the dtls token refresh happens automatically. Please provide more details and if you have no more questions please close this issue

**Comment by atyshka** [comment]
Yes, I am talking about webrtc. Does the token refresh interrupt video and if so how long?

**Comment by MushMal** [comment]
Refresh is happening in a background and shouldn’t interrupt streaming

**Comment by MushMal** [comment]
Give it a try

**Comment by atyshka** [comment]
Ok thanks! Closing for now
