### ISSUE TITLE
[QUESTION] sessionCleanupWait

### ISSUE THREAD

**Issue by juanea** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1029]
What is sessionCleanupWait doing in the /kvsWebRTCClientMasterGstreamerSample.c?
In your latest master it is removed from kvsWebRTCClientMaster.c, Why?

The moment you call sessionCleanupWait in an application similar to kvsWebRTCClientMasterGstreamerSample.c
it does not get out of it.

**Comment by disa6302** [comment]
@juanea , 

I am not sure what you mean? `sessionCleanupWait()` does exist in `kvsWebRTCClientMaster.c`. Check https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/a0916241494a9e075ebd880a9f276064855eac77/samples/kvsWebRTCClientMaster.c#L97

As seen in this [function](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/a0916241494a9e075ebd880a9f276064855eac77/samples/Common.c#L933), what it does is terminate streaming sessions and set up signaling client connection if signaling moves to ready state after terminating sessions. 

Have you tried the stock master sample? Does it get stuck in the stock master application? Do you have any changes in your application? 

Please include more details.

**Comment by hassanctech** [comment]
Assuming the question was answered, resolving.  If you still need help please re-open.
