### ISSUE TITLE
[QUESTION] frame.presentationTs usage

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1035]
Reported by my team member:

I’m checking sample code in “amazon-kinesis-video-streams-webrtc-sdk-c\samples\kvsWebRTCClientMaster.c”. In function “sendVideoPackets”, there’s the code.
 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/94c28731054d5eea7bb2ffa24a49d4f8f4bebf5b/samples/kvsWebRTCClientMaster.c#L234

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/94c28731054d5eea7bb2ffa24a49d4f8f4bebf5b/samples/kvsWebRTCClientMaster.c#L256
 
The code is trying to send sample video frames every 40 milliseconds (here FPS is 25). Also, it increases 40 milliseconds to frame.presentationTs each time it sends a frame. So we have a 40-millisecond frame interval here.
 
So how frame.presentationTs will affect video live FPS in KVS WebRTC Test Page?
 
Because if I keep the “THREAD_SLEEP” code line unchanged (i.e. keeping send video frames interval unchanged), then I only change “frame.presentationTs” to be for instance,
 
a)      frame.presentationTs += SAMPLE_VIDEO_FRAME_DURATION*10;
Or
b)     frame.presentationTs += SAMPLE_VIDEO_FRAME_DURATION/10;
 
I didn’t see any change in KVS WebRTC Test Page. The video live FPS seems unchanged (still 25 FPS).
 
The reason I care about this question is, I want to know, if I can’t retrieve real FPS from a real video live source, can I just use this default FPS value 25? Cause it seems an inaccurate video frame duration that’s used by frame.presentationTs doesn’t have effect on the playback FPS in KVR WebRTC Test Page.
 
Please let me know if something here is unclear.

**Comment by MushMal** [comment]
In webrtc the frame timestamps are not used as the underlying stream is an elementary stream

**Comment by suggestedfixes** [comment]
Thanks!

**Comment by suggestedfixes** [comment]
However, we've encountered cases where non-monotonically increasing timestamps will throw off decoders. So which stamp gets converted to RTP timestamps?

**Comment by disa6302** [comment]
@suggestedfixes , 

Presentation timestamp is the one that gets converted to RTP timestamp. Check this [line](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/f5b89d4b6e6116a06f0bd2580967142e98ce6f70/src/source/PeerConnection/Rtp.c#L235) out.
