### ISSUE TITLE
[QUESTION] Limitations or considerations for multiple camera configurations

### ISSUE THREAD

**Issue by t1-kawasaki** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1036]
Two USB cameras (same manufacturer) are connected to one Raspberry pi4. (There are devices in / dev / video0 and / dev / video2)
Are there any restrictions or considerations when running the Master program at the same time?

**Comment by MushMal** [comment]
Sample master program streams pre canned frames so it will have no difference. For the GStreamer sample you just need to make sure you select the right device.

**Comment by disa6302** [comment]
Closing assuming question is answered.

**Comment by t1-kawasaki** [comment]
Thank you. I copied the sample program (kvsWebRTCClientMasterGstreamerSample.c) and modified it to specify two camera devices. (For video0 device: "v4l2src device = / dev / video0! Queue! videoconvert! video / x-raw, width = 640, height = 480, framerate = 30/1!")
I checked the video on the KVS Web RTC Test Page, but only the video from the first camera is displayed. The video was not displayed on the second unit. Is there anything else I need to fix?
When I ran only one of each, there was no problem.

**Comment by t1-kawasaki** [comment]
It seemed like a resource issue on the raspberry pi4. When the frame size was 640x480 and the frame rate was 1/30, the CPU usage was about 50%. Therefore, it seems that the image from the second camera could not be displayed.
When the frame size was 320x240 and the frame rate was 1/15, the images from the two cameras could be displayed at the same time without any problem. The CPU usage of each was about 20%.
It turns out that it uses very little memory and uses a lot of CPU.
Thank you very much.
