### ISSUE TITLE
[QUESTION]: What Should i do if same peer-ID comes to re-connect  in API "signalingMessageReceived" from common.c

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1047]
In common.c file API "signalingMessageReceived" having a case : "SIGNALING_MESSAGE_TYPE_OFFER" . In this case we are increasing "streamingSessionCount" even if same peerID received at line 1080
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L1080.

In common.c we already found same peerID at line : 1059
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L1059

If same peerID found without closing previous one. How Master should behave?

In my code i modified to check only at which position peerID found. See my below code attachment in case "SIGNALING_MESSAGE_TYPE_OFFER":-
[code.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5830574/code.txt)

But I didn't clear previous peerID context. Is it required to do So? if yes, then where it is required to do?

[Issue] at line number : 1072 from file common.c 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L1072

calculating wrong max stream count:
condition should be : 

if (pSampleConfiguration->streamingSessionCount == SIZEOF(pSampleConfiguration->sampleStreamingSessionList)/sizeof(PSampleStreamingSession)) 
{
    DLOGW("Max simultaneous streaming session count reached.");
    CHK(FALSE, retStatus);
}

**Comment by MushMal** [comment]
There is a bug in LN 1072. We will provide a fix ASAP.

The sample application doesn't really expect the same client id. We will have to add a fix for that too.

**Comment by MushMal** [comment]
One thing to mention is that under the normal circumstances, the peer would terminate properly which would trigger a cleanup on the master. If not, it would take inactivity timeout to clean up the session.

**Comment by shiv50084** [comment]
@MushMal 

Where session inactivity timeout mentioned?
Which macro I need to see for session inactivity timeout?

**Comment by MushMal** [comment]
Any one of the following peer connection state changes will trigger a session cleanup:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L50-L57

If the peer "misbehaves" and doesn't cleanup then the ICE agent timeout is the likely cause to cleanup the session.

The ICE agent is triggering disconnect in the ICE state machine on inactivity after 2 seconds defined here

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.h#L30


The state transition happens in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgentStateMachine.c#L104

The ICE agent has a grace period of 15 seconds defined here https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.h#L31 for which it can still try to recover from disconnected state. However, if it still doesn't recover, the ICE agent state machine moves to failed state.

The sample application has a simplistic handling model where every disconnect will trigger a session cleanup.

So, to be precise, after 2 seconds of inactivity so it seems.

**Comment by MushMal** [comment]
Resolving as the changes have been pushed. Please cut a new issue if you have any further question

**Comment by shiv50084** [comment]
> Any one of the following peer connection state changes will trigger a session cleanup:
> 
> https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L50-L57
> 
> If the peer "misbehaves" and doesn't cleanup then the ICE agent timeout is the likely cause to cleanup the session.
> 
> The ICE agent is triggering disconnect in the ICE state machine on inactivity after 2 seconds defined here
> 
> https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.h#L30
> 
> The state transition happens in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgentStateMachine.c#L104
> 
> The ICE agent has a grace period of 15 seconds defined here https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.h#L31 for which it can still try to recover from disconnected state. However, if it still doesn't recover, the ICE agent state machine moves to failed state.
> 
> The sample application has a simplistic handling model where every disconnect will trigger a session cleanup.
> 
> So, to be precise, after 2 seconds of inactivity so it seems.

@MushMal 

The ICE agent is triggering disconnect in the ICE state machine on inactivity after 2 seconds defined here

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.h#L30

Here you mentioned its trigger disconnect after 2 seconds of disconnecting buts its 30 sec here.
#define KVS_ICE_ENTER_STATE_DISCONNECTION_GRACE_PERIOD (2 * KVS_ICE_SEND_KEEP_ALIVE_INTERVAL)
#define KVS_ICE_SEND_KEEP_ALIVE_INTERVAL                       (15 * HUNDREDS_OF_NANOS_IN_A_SECOND)

Can you please help?
