### ISSUE TITLE
DL frame index not valid for callback 

### ISSUE THREAD

**Issue by zhangxiaobo0715** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1054]
In src/source/PeerConnection/PeerConnection.c : onFrameReadyFunc 
the **frame.index** have not set a value before pTransceiver->onFrame is called.
Then the onFrame can't get index.

**Comment by MushMal** [comment]
Will set it - in webrtc it's not actively used by the SDK but applications might get some use of it.

**Comment by MushMal** [comment]
Fixing this along other issues in #1053

**Comment by disa6302** [comment]
Closing. Issue fixed.
