### ISSUE TITLE
Does KVS-WEBRTC-SDK-c  Support Adaptive bitrate.

### ISSUE THREAD

**Issue by mukesh-2538** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1062]
I have a master which produces h.264 encoded video frames of 3 different resolutions

      -  480p
      -  720p 
      -  1080p
I am using the KVSWEBRTCclientmaster.c sample code. 
I want to achieve Adaptive bitrate live streaming. I want to feed the viewer a video of resolution(480p, 720p, 1080p) corresponding to bandwidth availability of the user.

**Question**

-  Is there an api to know the viewer's bandwidth?
-  Does the viewer need to update the SDP to achieve this?

**I want to achieve**
-  Based on the bandwidth i can feed the client with corresponding 480p/ 720p/ 1080p feed using the Writeframe() api.

**Comment by mukesh-2538** [comment]
Why does it require a new SDP exchange? Can we use payload specific parameters?
[https://tools.ietf.org/id/draft-nandakumar-payload-sdp-max-video-resolution-00.html](url)

**Sample SDP exchange:**
  m=video 62537 RTP/SAVPF 96
  a=rtpmap:96 VP8/90000
  **a=fmtp:96 max-fr=30;max-recv-width=720;max-recv-height=576**
  a=sendrecv

Cant we just mention maximum resolution in the viewer's offer/answer? For example if the viewer specifies 1080p in the Initial SDP exchanges, the same can be used with for sending 480p and 720p,  which would eliminate the need for further SDP exchanges.

**Question**:
-  Do we require a new SDP exchange ? ( provided the viewer specific the max height and width in the initial exchange)

**Comment by hassanctech** [comment]
As @disa6302 mentioned we do not support active bitrate.  Also today we do not parse values such as `max-recv-width` and `max-recv-height`.  We of course welcome contributions!

**Comment by zhuker** [comment]
@mukesh-2538 if you feed h264 IDR slice with PPS/SPS to `writeFrame` function a good h264 decoder (chrome should do it) should switch to the new resolution
ie: i think the library already can support your case
like @disa6302 mentioned you can use the onBandwidthEstimation callback to control your encoders bitrate and even resolution settings

read more about adaptive bitrate [here](https://github.com/zhuker/webrtc-for-the-curious/blob/zhuker-bandwidth/content/docs/05-media-communication.md#adaptive-bitrate-and-bandwidth-estimation)

**Comment by hassanctech** [comment]
Closing this issue as the original question was answered.  If you have a new question please open a new issue.
