### ISSUE TITLE
[QUESTION] Can I use the WebRTC SDK to stream video from my laptop's webcam to an AWS Kinesis video stream?

### ISSUE THREAD

**Issue by anish2591** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1068]
Can I use the WebRTC SDK to stream video from my laptop's webcam to an AWS Kinesis video stream?

** Logging ** 
Add relevent SDK logging. IMPORTANT NOTE: Please make sure to NOT share AWS access credentials under any circumstance! Please make sure they are not in the logs.

** Any design considerations/constraints **
I would like to use the WebRTC SDK to stream live video into a kinesis video stream. Once the video is in the stream I would like to retrieve it using `GetMedia` and then store it in my S3 bucket. 

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by disa6302** [comment]
@anish2591 ,

Yes. You can stream from your laptop. The Gstreamer sample runs with auto video/audio source. You can get started with the GStreamer master sample

**Comment by anish2591** [comment]
@disa6302 Where do I find this sample?

**Comment by disa6302** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c

**Comment by anish2591** [comment]
Thanks! Is there something similar in Javascript?

**Comment by disa6302** [comment]
There is a link to a test page in the JS SDK repository. Please check the test page and the examples folder for samples.
