### ISSUE TITLE
[Question]: After taking latest changes timer creattion stuck in handleoffer API

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1071]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L217
stuck at line 217

**Describe the bug** when master received an offer and sent that offer to handleoffer API during timer creation its stuck in that API

**SDK version number** using commit id: cdc31f63346b4e4dd5242355826b551c94993774

**Open source building**
compiled on MIPS32 based arch

**Comment by MushMal** [comment]
Please provide a stack dump for all of the threads with symbols to be actionable. Please include debug logs as well.

As is there is nothing that points to an issue and I am not sure what “stuck” is. Can you include details on how to repro?

I assume you have no changes and running the stock sample.

**Comment by disa6302** [comment]
@shiv50084 , 

Do you have an update? 

Can you add the following information to the ticket:

1. Changes you made to the sample
2. Logs
3. Complete stack trace

Thanks!

**Comment by disa6302** [comment]
Closing due to no response. Feel free to re-open or create a new issue once you have details.
