### ISSUE TITLE
[QUESTION]In the webrtc-sdk-c, how the opus samples audio files are generated?

### ISSUE THREAD

**Issue by wingengineer** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1072]
I can find the GStreamer command to generate the H264 sample files, but how the opus audio files are created?

Thanks
Wing

**Comment by hassanctech** [comment]
I can look into how they were created, but here is a way to do it if you're just interested in generating some test data:  https://gstreamer.freedesktop.org/documentation/opus/opusenc.html?gi-language=c

**Comment by hassanctech** [comment]
Ok so it looks like they were generated using GStreamer.  How exactly I'm not sure, but the link I shared above should help you generate some if that's what you're after.  I'm closing this issue, if you have a new question please open a new issue.
