### ISSUE TITLE
[QUESTION] How to delete Signaling Channel?

### ISSUE THREAD

**Issue by nguyenduynghia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1073]
Is there any way to delete all Signaling Channels created.
I used function signalingClientDeleteSync but they are still available in Amazon Console.

**Comment by MushMal** [comment]
If it returns STATUS_SUCCESS then the channel would be deleted. Double check your steps

**Comment by nguyenduynghia** [comment]
Yes, It return SUCCESS but stream was not deleted.
Here are log message:
[2021-02-18 11:34:47]-INFO-signalingClientDeleteSync(): Signaling Client Delete Sync
[2021-02-18 11:34:48]-DEBUG-stepStateMachine(): State Machine - Current state: 0x0000000000000400, Next state: 0x0000000000000800
[2021-02-18 11:34:49]-INFO-freeSignalingClient(): Freeing Signaling Client

**Comment by MushMal** [comment]
From the snippet of logs it shows that the state machine has transitioned from DELETE to DELETED state so I assume it was successful. The channel delete operation is inherently ASYNC in the backend. Even if the SDK synchronously issues a delete API it will be eventually consistent. Normally, it takes less than a few seconds for the channel to actually get deleted and get delisted from the view.

Here is the API test for the client level API: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/tst/SignalingApiTest.cpp#L120

All of our unit tests clear/delete the channel after their run (though, they use the internal non-public API but it's called directly).

Please check:

* The region is selected correctly in the console view.
* After deletion, refresh the channel list. Give a few seconds.
* Ensure you use the correct account
* Make sure you are not running ANY other SDK clients - the client when created, will transition from Describe state to Create state automatically when the channel is not present.

**Comment by disa6302** [comment]
Closing based on tag. Feel free to re-open if you have any questions.

**Comment by nguyenduynghia** [comment]
I tried on kvsWebRTCClientMaster example.
call function
 retStatus = signalingClientDeleteSync(pSampleConfiguration->signalingClientHandle);
And put some break point and debug.
It jumps in function fromDeleteSignalingState but never jump into function executeDeleteSignalingState.
I don't debug into function stepStateMachine due to no source code.

**Comment by MushMal** [comment]
signalingClientDeleteSync steps state machinery by calling stepStateMachine which then exercises the state machine to delete. You might want to put some debug breakpoints.

Try to use the unit test which executes the delete API and ensure it works OK. From then on, try to model your application or create a repro so we can look into.
