### ISSUE TITLE
[QUESTION] Try recording WebRTC streaming with AWS KVS

### ISSUE THREAD

**Issue by nilesflow** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1076]
Try recording WebRTC streaming with AWS KVS

We also hope to record WebRTC streams from camera devices and browsing clients on KVS.
We try running client on EC2 (or ECS, Farget, etc.).

Seeing #11, #60, and #550, #191 confirmed an implementation that reads video streaming data from an h.264 file and sends it to KVS and WebRTC at the same time.

If this client joins in Viewer, it will not be possible to record both streams as each device will be Master and Viewer. In order to store both WebRTC streams in KVS, you need to join in Master and transfer the streaming data of all Viewers.
This client replaces the streaming data that it sends to AWS KVS in #191 from the h.264 file to WebRTC streams.
Pre-create as many Streams in AWS KVS as there are Viewers.

Could us tell if there are any mistakes in this design.

We hope this feature to be implemented early in the AWS KVS standard.

**Comment by disa6302** [comment]
@nilesflow , 

There is nothing that does not permit you to do this. However, keep in mind that when you have, say, x viewers and you pre-create x streams, the master application would be streaming x*2 streams and 1 master. If you have a strong network bandwidth, it should be okay.

**Comment by nilesflow** [comment]
@disa6302 thank you for your answer.
We will try to implement to this design.
Please let us know if you have a plan to support it as standard.
