### ISSUE TITLE
Streaming PCM A law data 

### ISSUE THREAD

**Issue by kpatil001** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1078]
With the current implementation of c sdk in this repo, it support streaming of uncontainerized opus data. I want to streaming PCM A law data from kvsWebRTCClientMaster, to accomplish this I changed RTC_CODEC_OPUS to RTC_CODEC_ALAW at 
[this line ](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/cdc31f63346b4e4dd5242355826b551c94993774/samples/Common.c#L472
) and [this line](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/cdc31f63346b4e4dd5242355826b551c94993774/samples/Common.c#L486) .  Our frontend is developed using amazon-kinesis-video-streams-webrtc-sdk-js . With opus data everything is fine but with PCM A LAW data I am not getting any audio in frontend, also there is no error in c sdk logs. 

So is there any other configuration changes which I need to do in c sdk to accomplish streaming of PCM A LAW data?

**Comment by hassanctech** [comment]
Can you please share the offer and answer SDP?  Thanks.

**Comment by hassanctech** [comment]
I suspect your offer does not include support for a-law hence it is not getting selected and that track is being muted.  If that is the case you will need to make sure on the JS side in the offer you advertise support for a-law.  Seeing your offer/answer SDP will make clear if this is the case or something else.

**Comment by hassanctech** [comment]
@kpatil001 We are waiting on offer/answer SDP to further debug.

**Comment by kpatil001** [comment]
sorry for the delay @hassanctech I will share the sdp offer and answer shortly

**Comment by kpatil001** [comment]
SDP OFFER from viewer to Master : :
{"type":"offer","sdp":"v=0\r\no=- 1180247525 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2\r\na=msid-semantic: WMS myKvsVideoStream\r\nm=audio 9 UDP/TLS/RTP/SAVPF 8\r\nc=IN IP4 127.0.0.1\r\na=candidate:3 1 udp 16777215 52.91.108.231 60574 typ relay raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=candidate:2 1 udp 16777215 52.91.108.231 60960 typ relay raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=candidate:1 1 udp 1694498815 3.239.200.108 53468 typ srflx raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=candidate:0 1 udp 2130706431 172.31.12.47 33789 typ host raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=msid:testvideoAIF myAudioTrack\r\na=ssrc:559480802 cname:uCBdqS01gJNtOGuk\r\na=ssrc:559480802 msid:testvideoAIF myAudioTrack\r\na=ssrc:559480802 mslabel:testvideoAIF\r\na=ssrc:559480802 label:myAudioTrack\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:leHO\r\na=ice-pwd:CEJMC5v1LokYsxGY9dIk7yZe\r\na=ice-options:trickle\r\na=fingerprint:sha-256 5B:9D:A5:1C:06:42:0E:91:23:80:A4:F9:31:76:11:AF:F3:2B:24:23:E6:68:FE:98:92:B3:45:F7:3E:36:F1:B4\r\na=setup:actpass\r\na=mid:0\r\na=sendrecv\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:8 PCMA/8000\r\na=rtcp-fb:8 nack\r\nm=video 9 UDP/TLS/RTP/SAVPF 125\r\nc=IN IP4 127.0.0.1\r\na=candidate:3 1 udp 16777215 52.91.108.231 60574 typ relay raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=candidate:2 1 udp 16777215 52.91.108.231 60960 typ relay raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=candidate:1 1 udp 1694498815 3.239.200.108 53468 typ srflx raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=candidate:0 1 udp 2130706431 172.31.12.47 33789 typ host raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=msid:testvideoAIF myVideoTrack\r\na=ssrc:2073841468 cname:uCBdqS01gJNtOGuk\r\na=ssrc:2073841468 msid:testvideoAIF myVideoTrack\r\na=ssrc:2073841468 mslabel:testvideoAIF\r\na=ssrc:2073841468 label:myVideoTrack\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:leHO\r\na=ice-pwd:CEJMC5v1LokYsxGY9dIk7yZe\r\na=ice-options:trickle\r\na=fingerprint:sha-256 5B:9D:A5:1C:06:42:0E:91:23:80:A4:F9:31:76:11:AF:F3:2B:24:23:E6:68:FE:98:92:B3:45:F7:3E:36:F1:B4\r\na=setup:actpass\r\na=mid:1\r\na=sendrecv\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:125 H264/90000\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtcp-fb:125 nack\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 127.0.0.1\r\na=candidate:3 1 udp 16777215 52.91.108.231 60574 typ relay raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=candidate:2 1 udp 16777215 52.91.108.231 60960 typ relay raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=candidate:1 1 udp 1694498815 3.239.200.108 53468 typ srflx raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=candidate:0 1 udp 2130706431 172.31.12.47 33789 typ host raddr 0.0.0.0 rport 0 generation 0 network-cost 999\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:leHO\r\na=ice-pwd:CEJMC5v1LokYsxGY9dIk7yZe\r\na=fingerprint:sha-256 5B:9D:A5:1C:06:42:0E:91:23:80:A4:F9:31:76:11:AF:F3:2B:24:23:E6:68:FE:98:92:B3:45:F7:3E:36:F1:B4\r\na=setup:actpass\r\na=mid:2\r\na=sctp-port:5000\r\n"}

SDP answer from master to viewer : : 
{"type":"answer","sdp":"v=0\r\no=- 1199190477748092561 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2\r\na=msid-semantic: WMS GGdSTHlSV0JsrB7mbTK11VdtCN5HMJvSma29\r\nm=audio 9 UDP/TLS/RTP/SAVPF 8\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:KGU/\r\na=ice-pwd:Df3xgAGAjOiytMqwWlOtoAUa\r\na=ice-options:trickle\r\na=fingerprint:sha-256 AC:56:A6:44:1F:5C:59:9D:E3:23:9B:73:A9:98:79:F5:EA:C1:B2:5A:45:1D:D9:81:CD:F7:5C:2F:F7:0C:AD:EB\r\na=setup:active\r\na=mid:0\r\na=sendrecv\r\na=msid:GGdSTHlSV0JsrB7mbTK11VdtCN5HMJvSma29 fae6aef5-0188-4ad4-b17c-a801b6167a6e\r\na=rtcp-mux\r\na=rtpmap:8 PCMA/8000\r\na=ssrc:1572884547 cname:F619eC5XTHFaMA+K\r\nm=video 9 UDP/TLS/RTP/SAVPF 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:KGU/\r\na=ice-pwd:Df3xgAGAjOiytMqwWlOtoAUa\r\na=ice-options:trickle\r\na=fingerprint:sha-256 AC:56:A6:44:1F:5C:59:9D:E3:23:9B:73:A9:98:79:F5:EA:C1:B2:5A:45:1D:D9:81:CD:F7:5C:2F:F7:0C:AD:EB\r\na=setup:active\r\na=mid:1\r\na=sendrecv\r\na=msid:GGdSTHlSV0JsrB7mbTK11VdtCN5HMJvSma29 1632026c-b019-45ab-9e93-46679926d9aa\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 nack\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=ssrc:2772614007 cname:F619eC5XTHFaMA+K\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:KGU/\r\na=ice-pwd:Df3xgAGAjOiytMqwWlOtoAUa\r\na=ice-options:trickle\r\na=fingerprint:sha-256 AC:56:A6:44:1F:5C:59:9D:E3:23:9B:73:A9:98:79:F5:EA:C1:B2:5A:45:1D:D9:81:CD:F7:5C:2F:F7:0C:AD:EB\r\na=setup:active\r\na=mid:2\r\na=sctp-port:5000\r\n"}

**Comment by hassanctech** [comment]
Every thing looks ok there, are you sure the master side is actually producing / sending audio?  How are you verifying that the receiver side is actually not receiving them, if you're using Chrome/Firefox can you check the webrtc internals and see if there's any data flowing?

Also can you try with our test page:  https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html

To see if you get audio there?  I do not see anything wrong with the SDP exchange so the problem must be somewhere else.

**Comment by kpatil001** [comment]
We tried using your test page, we didn't receive any audio in frontend. If this helps I am sharing logs from Test page::

```
[2021-03-01T14:18:21.136Z] [INFO] [MASTER] Starting master connection
[2021-03-01T14:18:43.672Z] [INFO] [MASTER] Connected to signaling service
[2021-03-01T14:18:43.801Z] [INFO] [MASTER] Received SDP offer from client: ConsumerViewer_1595148768
[2021-03-01T14:18:43.946Z] [INFO] [MASTER] Received remote track from client: ConsumerViewer_1595148768
[2021-03-01T14:18:43.946Z] [INFO] [MASTER] Received remote track from client: ConsumerViewer_1595148768
[2021-03-01T14:18:43.946Z] [INFO] [MASTER] Creating SDP answer for client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.019Z] [INFO] [MASTER] Sending SDP answer to client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.020Z] [INFO] [MASTER] Generating ICE candidates for client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.027Z] [INFO] [MASTER] Generated ICE candidate for client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.028Z] [INFO] [MASTER] Sending ICE candidate to client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.133Z] [INFO] [MASTER] Generated ICE candidate for client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.133Z] [INFO] [MASTER] Sending ICE candidate to client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.311Z] [INFO] [MASTER] Generated ICE candidate for client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.311Z] [INFO] [MASTER] Sending ICE candidate to client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.521Z] [INFO] [MASTER] Generated ICE candidate for client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.521Z] [INFO] [MASTER] Sending ICE candidate to client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.662Z] [INFO] [MASTER] Generated ICE candidate for client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.662Z] [INFO] [MASTER] Sending ICE candidate to client: ConsumerViewer_1595148768
[2021-03-01T14:18:44.727Z] [INFO] [MASTER] All ICE candidates have been generated for client: ConsumerViewer_1595148768
[2021-03-01T14:25:59.386Z] [INFO] [MASTER] Stopping master connection
[2021-03-01T14:25:59.611Z] [INFO] [MASTER] Disconnected from signaling channel
```

We have also tried sending opus data, mentioning opus as audio format at [this line](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/cdc31f63346b4e4dd5242355826b551c94993774/samples/Common.c#L472). When doing this, we received audio in frontend. Hence data is flowing between master and viewer.  

For your reference we are adding pcm alaw files which we are sending from viewer to master.
[pcm-alaw (1).zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6062626/pcm-alaw.1.zip). It will be helpful, if you try to stream these files from your end and let us know the results.

**Comment by Nomidia** [comment]
I am also using the pcma on my device, there is no such issue. Be sure you send the correct audio data from master or viewer. The pcm-alaw shows that the data is invalid 0xff. 
![image](https://user-images.githubusercontent.com/20633988/111725277-c15ad600-88a1-11eb-8615-efc32253fa7c.png)

**Comment by disa6302** [comment]
@kpatil001 , 

Can you try the AWS console as well? I tried Alaw with a GStreamer pipeline instead of files and it works fine. Ensure your file content is valid.

**Comment by disa6302** [comment]
Closing due to no response. @kpatil001 , 

Ensure your file content is valid.
