### ISSUE TITLE
[QUESTION] Does sdk support proxy?

### ISSUE THREAD

**Issue by lhuijae** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1079]
Does sdk support proxy?

embedded device <--> proxy  <--> internet  <--> mobile device

Thanks.

**Comment by MushMal** [comment]
The question is not clear but you should look at TURN server communication where both entities are using the Turn server as a proxy.

I am resolving this issue as not specific

**Comment by lhuijae** [comment]
Thanks @MushMal,

This is our network for WebRTC.
I wonder if mobile and Embedded devices can communicate with WebRTC in this design.
I'm sorry for the lack of explanation.

![2021-02-22 161652](https://user-images.githubusercontent.com/13791042/108674971-76130900-7529-11eb-959d-9111d3165c74.png)

**Comment by MushMal** [comment]
I assume KVS WebRTC in the diagram in the AWS box are the TURN servers? As long as both entities have access to the TURN, there will be at least TURN communication. In this diagram I think there won't be possible to create P2P but I might be wrong. Try to run discoverNatBehavior tool which is part of the package.

**Comment by lhuijae** [comment]
Thanks @MushMal,

I know that KVS WebRTC Box is Signaling Server, STUN, and TURN Server.
The problem is that the only way for Embedded devices to go to IGW is by EC2 HTTP proxy.
In fact, I can't run discoverNatBehavior in this environment.
That's why I'm asking if this kind of communication is possible.

All packets must be via HTTP proxy, and the device's WebRTC SDK is:

1)Can sdk connect to the Signaling Server?
2)Can sdk gather ICE candidates?
3)Can sdk send and receive Opus audio packets by RTP?

Because this is not a network that I designed,
If WebRTC communication is not possible, I will ask him to change the design.

**Comment by MushMal** [comment]
I see. Yeah, this might not work as is. Without modifying the topology there would need to be some sort of a proxy but we don’t have it
