### ISSUE TITLE
[QUESTION] About Outbound hostname and port requirements

### ISSUE THREAD

**Issue by lhuijae** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1083]
I'd like to know the role of each endpoint below.
Or where can I get information about these?

- KVS endpoint : TCP 443 (ex: kinesisvideo.us-west-2.amazonaws.com)
- HTTPS channel endpoint : TCP 443 (ex: r-2c136a55.kinesisvideo.us-west-2.amazonaws.com)
- WSS channel endpoint : TCP 443 (ex: m-26d02974.kinesisvideo.us-west-2.amazonaws.com)
- STUN endpoint : UDP 443 (ex: stun.kinesisvideo.us-west-2.amazonaws.com)
- TURN endpoint : UDP/TCP 443 (ex: 34-219-91-62.t-1cd92f6b.kinesisvideo.us-west-2.amazonaws.com:443)

Thanks.

**Comment by MushMal** [comment]
1) Control plane plane uri. Main APIs are called against those - DescribeChannel
2) not entirely sure which one this is but it’s he data plane API endpoint. Need more info on this to tell for sure
3) WebSocket connection endpoint. Used for signaling 
4) STUN server endpoint
5) TURN server endpoint


I would recommend reading up about WebRtc to get more info about stun and turn.

**Comment by lhuijae** [comment]
Thanks.
