### ISSUE TITLE
[BUG] JitterBuffer.c incorrect handling of late packet from previous frame

### ISSUE THREAD

**Issue by wreuven** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1085]
Line 2 and 3 in the following if statement makes no sense (e.g. comparing timestamp to sequence number) and potentially causes trouble.

```
 if (!pJitterBuffer->started ||
        (pJitterBuffer->lastPopTimestamp == pRtpPacket->header.sequenceNumber &&
         pJitterBuffer->lastRemovedSequenceNumber >= pRtpPacket->header.sequenceNumber)) {
        // Set to started and initialize the sequence number
        pJitterBuffer->started = TRUE;
        pJitterBuffer->lastRemovedSequenceNumber = UINT16_DEC(pRtpPacket->header.sequenceNumber);
    }
```

I think the intention is perhaps that a late packet arriving after the previous frame has already been popped which has a greater sequence number than the last removed sequence number should become the last removed sequence number. In which case the expression should read (see 2 changes):

```
 if (!pJitterBuffer->started ||
        (pJitterBuffer->lastPopTimestamp == pRtpPacket->header.timestamp &&
         pJitterBuffer->lastRemovedSequenceNumber < pRtpPacket->header.sequenceNumber)) {
        // Set to started and initialize the sequence number
        pJitterBuffer->started = TRUE;
        pJitterBuffer->lastRemovedSequenceNumber = UINT16_DEC(pRtpPacket->header.sequenceNumber);
    }
```

**Comment by hassanctech** [comment]
Yikes! Looks like a bug, taking a look...

**Comment by hassanctech** [comment]
I put up a PR for the timestamp comparison.  I'm not yet convinced of the second change, I need to figure out what the intention there was as well, @wreuven feel free to comment on the PR.

**Comment by wreuven** [comment]
By the way, there seems to be other problems with this module.
Seems to assume that timestamps always start at zero and that is not the case by RTP standard.
Seems to assume that timestamps always increase when in fact they wrap around. 
There are a couple scary sounding TODO comments in the module.

**Comment by hassanctech** [comment]
Fixed: https://github.com/awslabs/amazon-kinesis-video-streams-pic/pull/84/files#diff-d181ddf3c70af1265b8b311f3249b35e9e535d4441aa83d019c4bf2d433fd08cR619
