### ISSUE TITLE
[QUESTION] How to use coturn server in SDK?

### ISSUE THREAD

**Issue by lhuijae** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1089]
Can SDK connect to an external STUN/TURN server other than KVS?
I'd like to use the coturn.
What should I do if it's possible?

**Comment by hassanctech** [comment]
This should answer your question:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/769

Let me know if anything remains?

**Comment by lhuijae** [comment]
My question is similar to #769.

This is our network topology.
![2021-03-05 092055](https://user-images.githubusercontent.com/13791042/110049162-a44be080-7d94-11eb-89b4-f66093987526.png)

We want to have WebRTC communication with the camera and mobile, but there is some restrictions camera network. It cannot access the Internet directly. So we thought we could use a proxy and designed it. Is this possible to communicate with WebRTC?

The concept is that signalling is via HTTP proxy and STUN/TURN is via coturn.

According to the test, HTTP proxy works by setting the http_proxy environment variable on Linux.

But I don't know where and how to set up the address of the coturn server.
Also, Does the mobile need to be able to connect the coturn?

Please let me know if my explanation is insufficient.

**Comment by hassanctech** [comment]
From the other issue as mentioned by @MushMal:

> Conceptually, the signaling DAG (object graph) is separate from the WebRTC DAG (rooted with PeerConnection object). You could supply your own TURN info (URI + credentials) to the PeerConnection. This is exactly what the sample application does - it fetches the list of TURN server infos from the signaling and passes it to the PeerConnection object. You could replace those by your own TURN servers, provided they act the same way as the KVS TURN


I'm afraid there is really nothing more I can say there about your first issue.

If coturn were to work, both peers would need to be able to connect to it.

**Comment by disa6302** [comment]
@lhuijae , 

Ideally, you should be able to add server config details using this [structure](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/8b8b2bdf064f6cb2b6495339d31efc3518b12eb9/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1059). You can get inspiration from [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/8b8b2bdf064f6cb2b6495339d31efc3518b12eb9/samples/Common.c#L347) code section. If you are using your own CoTURN server, you would need to make sure your peers can communicate using the server.

**Comment by lhuijae** [comment]
@disa6302 

Thanks, 
I'll try it,  and close the issue.

**Comment by vbhasin2** [comment]
@lhuijae , were you able to work out through this use case? I was trying to experiment a similar use-case and wanted to know if this is possible, using an external STUN/TURN server with Kinesis WebRTC SDK.
Thanks
