### ISSUE TITLE
[FEATURE] Receiver Support for NACKs/Retransmits

### ISSUE THREAD

**Issue by wreuven** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1101]
The current code and sample Viewer seem to support NACKS/retransmits for the sender but not the receiver.
Any chance of this feature being added anytime soon? Intermittent packet loss happens a lot.

**Comment by disa6302** [comment]
@wreuven , 

If I understand correctly, you are asking about the case where the SDK is the receiver of media and the SDK transmits NACK/retransmit packets to the sender. There is no ETA on the implementation of this at the moment.

**Comment by wreuven** [comment]
Right. When the SDK implements the receiver and incoming RTP/UDP packets get lost (which happens), the SDK does not NACK the lost packets so the sender will not retransmit them.

**Comment by wreuven** [comment]
@juno52wendy  I have to agree. Even on a great connection there is packet loss and packet loss means picture corruption without NACKs.

**Comment by juno52wendy** [comment]
@wreuven   In fact, this is not difficult to implement by yourself, but the early implementation of the kvs code requires you to be familiar with the code logic or add a set of additional logic yourself. You can look at the implementation of janus. The principle is very simple. It is cached every time it is sent. A buffer contains seq, and then the rtcp packet that takes over recv parses the corresponding seq to find the corresponding buffer packet data and fetch it, and then resend it immediately.

**Comment by wreuven** [comment]
@juno52wendy -- You are describing the sender side of Nacks which you are correct is not so complicated and I believe is actually is implemented in the code, The missing code is the receiver side. This is less simple as it requires to recognize for each packet when it should have arrived (or when it's last retransmit request should have arrived) to send the NACK as early and accurately as possible. The original Gstreamer implementation for this was extremely inefficient and it is a bit tricky to implement efficiently,

**Comment by juno52wendy** [comment]
@wreuven  Understanding your needs, you can assemble the nack attribute of RTCP and send it to the other end, and then have the other end retransmit the missing data. The general idea is that you need to process the received RR attribute to calculate the RTT in order to calculate the time to send the NACK. The CC in the received RTP external protocol gets the NUMS in order to calculate the NACK attribute to send. There is more RTT calculation in the phase than data transmission. Hope it's helpful to you.

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.
