### ISSUE TITLE
[QUESTION] Data channel can be created only before signaling?

### ISSUE THREAD

**Issue by atyshka** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1102]
The api docs for createDataChannel state that a data channel can be created only before signaling, what does that mean? An rtcpeerconnection is required to create a data channel, and simply creating an rtcpeerconnection requires some level of signaling to take place.

**Comment by disa6302** [comment]
@atyshka , 

`createDataChannel` requires an `RtcPeerConnection` object. This will be set up once the master receives an offer from the other peer. The exchange of offer/answer happens over signaling.

**Comment by atyshka** [comment]
Exactly. So the API docs are either poorly worded or plain wrong. createDataChannel can only be done after signaling sets up an RTCPeerConnection, not before.

**Comment by disa6302** [comment]
@atyshka , 
Can you point to the doc you are referring to?

**Comment by disa6302** [comment]
Change merged in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1103. Thanks for reporting again!

**Comment by atyshka** [comment]
No problem, thanks for the quick fix!
