### ISSUE TITLE
[QUESTION] The video appears delayed after a few minutes of preview

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1105]
After a few minutes of previewing, the video is delayed for about 4 seconds. The delay is cumulative, but it will not continue to increase thereafter. If we control the camera's pt, the position is inaccurate because of the delay. But if we preview again or open a new viewer, the time is accurate at first. The same streaming data is distributed to each peers at the same time.

[Figure1]
![image](https://user-images.githubusercontent.com/20633988/111721573-252dd080-889b-11eb-8b11-0281e0a674df.png)

[Figure2]
![image](https://user-images.githubusercontent.com/20633988/111721603-3aa2fa80-889b-11eb-8893-bcf75040595d.png)

**Comment by disa6302** [comment]
@Nomidia , 

Is this something you observed recently? Which version of the SDK are you using? 
Do you see any errors in the logs?

**Comment by Nomidia** [comment]
It is the latest version and I didn't see any errors.

**Comment by disa6302** [comment]
Hmm. Not sure what could be happening. Did anything change after updating the version? Did you notice this in the previous version you are using?

Without details, it would be difficult to understand what could be causing this.

**Comment by Nomidia** [comment]
We did not notice this issue before, I'm not sure if anyone else has also encountered this problem. I will confirm whether the previous version also has this problem.

**Comment by Nomidia** [comment]
Oh, it is caused by the timestamp. At first, we use the real-time timestamp produced by the device, but the frame interval is uneven, the sound from the viewer is fluctuant. As aws team suggested, then we use the relative time which is accumulated with frame duration, It must be not precise enough.
I will adjust the timestamp next.

**Comment by Ryan45758** [comment]
Hi, did you solve this problem? how did you solve it

**Comment by vc60er** [comment]
+1
