### ISSUE TITLE
Streaming stability issues

### ISSUE THREAD

**Issue by maneeshj** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1107]
Hi, These are some of the different errors I get:
2021-03-03 17:24:44 ERROR iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-03-04 19:07:18 ERROR iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
2021-03-04 19:07:19 ERROR turnConnectionSendData(): operation returned status code: 0x5a000027
2021-03-05 02:23:52 ERROR executeFailedIceAgentState(): IceAgent failed with 0x5a00000d
2021-03-05 02:23:52 ERROR executeFailedIceAgentState(): IceAgent failed with 0x5a00000d
2021-03-05 21:28:27 ERROR iceUtilsSendData(): operation returned status code: 0x58000022
2021-03-05 21:28:27 ERROR iceUtilsSendStunPacket(): operation returned status code: 0x58000022

I was able to get their meaning from https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-c. But I want to understand if these errors being thrown are of a CONCERN or if they are normal while making a peer to peer connection between master and viewer ? Could you please let me know. Thanks!

_Originally posted by @maneeshj in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1098#issuecomment-805416354_

**Comment by disa6302** [comment]
@maneeshj ,

It looks like the ICE candidate string is missing in the SDP you receive. A couple of questions/thoughts:

1. What is your set up like? 
2. Do you see SDP exchanges succeeding? 
3. Can you investigate the SDPs that are being exchanged? You can do this by running: `export DEBUG_LOG_SDP=TRUE`
4. Have you made any changes to the code and what version of the SDK are you using? 

Also, please attach a file with the complete logs and the SDPs.

**Comment by disa6302** [comment]
@maneeshj , 

Any updates?

**Comment by maneeshj** [comment]
Hello Divya,
The previous error logs were from 1.4SDK. I am currently experimenting with 1.5SDK and will let you know how that turns out. I havent gotten a chance to run export DEBUG_LOG_SDP=TRUE yet.

**Comment by maneeshj** [comment]
The number of errors seem to have reduced. But Occasionally streaming goes OFF with the following logs:
```
2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 DEBUG stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000020

**2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 DEBUG executeDisconnectedIceAgentState(): Ice agent detected disconnection. current state ICE_AGENT_STATE_READY. Last data received time 1616788473 s**

2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 INFO onConnectionStateChange(): Channel BETA-GATE1-CHECK_OUT-1-FRONT-1-LO, New connection state 4

2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 DEBUG stepStateMachine(): State Machine - Current state: 0x0000000000000020, Next state: 0x0000000000000010

2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 VERBOSE sessionCleanupWait(): [sessionCleanupWait] BETA-GATE1-CHECK_OUT-1-FRONT-1-LO, Number of open streaming sessions: 1

2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 DEBUG freeStreamingSession(): Freeing streaming session with peer id: 0sxe9nryrpd8rqf1iueiah

2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 INFO onConnectionStateChange(): Channel BETA-GATE1-CHECK_OUT-1-FRONT-1-LO, New connection state 6

2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 DEBUG socketConnectionClosed(): Close socket 15

2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 DEBUG socketConnectionClosed(): Close socket 14

2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 DEBUG on_new_sample(): [GStreamerWrapper] on_new_sample() callback is called

2021-03-26T12:55:04.267-07:00    2021-03-26 19:55:04 VERBOSE rtcpReportsCallback(): sender report 1018670238 16431588403563151213 2441300 : 3868 packets 3472651 bytes
```

We have 1 master with multiple viewers setup. I can see the streams in KVS console via signaling channels. After a while the streams stops with bitrate of 0. Do you know whats happening ?

Thanks
Maneesh

**Comment by disa6302** [comment]
As mentioned in the previous ticket, please check your networking. It is possible your network is disconnecting at times and that is causing this.

**Comment by hassanctech** [comment]
Does this happen with only 1 viewer?  Can you test with just 1 viewer and see if this problem happens? Also can you please try the latest commit in this repo we have made a few possibly relevant changes.

Finally can you please include logs more logs from before executeDisconnectedIceAgentState so we can see what was happening before this.

**Comment by maneeshj** [comment]
Yes this happens with 1 viewer. We have single master - multiple viewer setup, but most of the times, there is only one viewer connected.
 Here are more logs before and after.

```

2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:02 VERBOSE on_new_sample(): [writeFrame] Number of open streaming sessions: 1
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:02 VERBOSE rtcpReportsCallback(): sender report 1553966933 16436360191374085846 77659177088854 : 0 packets 0 bytes
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:02 DEBUG on_new_sample(): [GStreamerWrapper] on_new_sample() callback is called
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:02 VERBOSE on_new_sample(): [writeFrame] Number of open streaming sessions: 1
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:02 VERBOSE rtcpReportsCallback(): sender report 2010335182 16436360191454237237 21111944 : 5750 packets 4018614 bytes
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:02 VERBOSE rtcpReportsCallback(): sender report 2010335182 16436360192249440553 21128608 : 5750 packets 4018614 bytes
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:02 DEBUG on_new_sample(): [GStreamerWrapper] on_new_sample() callback is called
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:02 VERBOSE on_new_sample(): [writeFrame] Number of open streaming sessions: 1
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:02 VERBOSE rtcpReportsCallback(): sender report 1553966933 16436360192547224380 77659177101965 : 0 packets 0 bytes
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 VERBOSE rtcpReportsCallback(): sender report 2010335182 16436360193182093131 21148151 : 5752 packets 4018813 bytes
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 DEBUG on_new_sample(): [GStreamerWrapper] on_new_sample() callback is called
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 VERBOSE on_new_sample(): [writeFrame] Number of open streaming sessions: 1
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 VERBOSE rtcpReportsCallback(): sender report 1553966933 16436360193492997224 77659177112535 : 0 packets 0 bytes
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 DEBUG on_new_sample(): [GStreamerWrapper] on_new_sample() callback is called
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 VERBOSE on_new_sample(): [writeFrame] Number of open streaming sessions: 1
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 VERBOSE rtcpReportsCallback(): sender report 2010335182 16436360194063550128 21166622 : 5756 packets 4019593 bytes
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 VERBOSE rtcpReportsCallback(): sender report 1553966933 16436360194631716749 77659177125261 : 0 packets 0 bytes
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 DEBUG on_new_sample(): [GStreamerWrapper] on_new_sample() callback is called
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 VERBOSE on_new_sample(): [writeFrame] Number of open streaming sessions: 1
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 VERBOSE rtcpReportsCallback(): sender report 1553966933 16436360195091874821 77659177130404 : 0 packets 0 bytes
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 VERBOSE rtcpReportsCallback(): sender report 2010335182 16436360195249555525 21191474 : 5758 packets 4020260 bytes
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 DEBUG stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000020
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 DEBUG executeDisconnectedIceAgentState(): Ice agent detected disconnection. current state ICE_AGENT_STATE_READY. Last data received time 1617899493 s
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 INFO onConnectionStateChange(): Channel TEB6-GATE1-CHECK_IN-1-FRONT-1-LO, New connection state 4
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 VERBOSE sessionCleanupWait(): [sessionCleanupWait] TEB6-GATE1-CHECK_IN-1-FRONT-1-LO, Number of open streaming sessions: 1
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 DEBUG freeStreamingSession(): Freeing streaming session with peer id: df1a8100-652f-4a98-984b-adec00cdac4a
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 DEBUG onSampleStreamingSessionShutdown(): [GStreamerWrapper] onSampleStreamingSessionShutDown callback
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 DEBUG onSampleStreamingSessionShutdown(): Sending EOS signal
  | 2021-04-08T09:32:03.644-07:00 | 2021-04-08 16:32:03 DEBUG stepStateMachine(): State Machine - Current state: 0x0000000000000020, Next state: 0x0000000000000010
  | 2021-04-08T09:32:03.645-07:00 | 2021-04-08 16:32:03 INFO onConnectionStateChange(): Channel TEB6-GATE1-CHECK_IN-1-FRONT-1-LO, New connection state 6
```

**Comment by hassanctech** [comment]
`VERBOSE` logs have a lot in them, can you please 1. Put the logs a file and link the file here and 2. Start the log collection from the start of the connection (when SDP exchange is happening) this logging only spans 2 seconds.

**Comment by maneeshj** [comment]
Hi Hassan, Please check the full set of logs from beginning to when the error occurs. Please not that we have single master, with 4 cameras connected and we create a 2 GStreamer processes for each camera, one for high-res and one for low-res. So the logs would contain everything together. But the logs should give you an idea on how the SDP message look like. 

[docker-kvs-logs-prod.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6281942/docker-kvs-logs-prod.txt)

**Comment by maneeshj** [comment]
[kvs-webrtc-logs.pdf](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6339640/kvs-webrtc-logs.pdf)

Here is a full log file attached with just one camera and 1 GSTREAMER process. The log file contains everything from beginning a stream till when it fails with **executeDisconnectedIceAgentState**() error

**Comment by disa6302** [comment]
Closing since we are having offline discussions.
