### ISSUE TITLE
[QUESTION] is there a way to test the device running webrtc master with multiple-video-tracks using the KVS webrtc test page ?

### ISSUE THREAD

**Issue by ajjiang48** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1109]
Hi, Sir,

We're building a web cam with multiple cameras (2 or 3) and run a webrtc master on it (currently, 1 video track is working and tested); we're planning to put multiple video tracks (1 video track for 1 camera video) into a single webrtc streaming session. My question is, I see only 1 "from master" video screen in the KVS webrtc test page UI, is it possible to test our webrtc master (with multiple video tracks) using the KVS webrtc test page ?? if not, do you have suggestion for the testing for this application??

**Comment by hassanctech** [comment]
It is possible but you'll have to made modifications to the test page to add multiple video tracks.

**Comment by disa6302** [comment]
Closing issue assuming question is answered.
