### ISSUE TITLE
[QUESTION] build on Raspberry pi fails

### ISSUE THREAD

**Issue by StefCeyssens** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1110]
When running the make command, it fails with message "error adding symbols: file format not recognized"

System info:

> Raspberry Pi 3 Model B Plus Rev 1.3
> Linux raspberrypi 5.10.17-v7+
> armv7l
> PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Steps I took:

1. install libs (sudo apt-get install libssl-dev libcurl4-openssl-dev liblog4cplus-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools)
2. Run cmake ..
3. Run make

Result:

> [ 12%] Linking C shared library libkvsWebrtcSignalingClient.so
> /usr/bin/ld: /home/pi/Downloads/kinesis-video-stream-from-rtsp/open-source/lib/libkvsCommonLws.a: error adding symbols: file format not recognized
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/kvsWebrtcSignalingClient.dir/build.make:161: libkvsWebrtcSignalingClient.so] Error 1
> make[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/kvsWebrtcSignalingClient.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2

When I run: 
cmake .. -DBUILD_STATIC_LIBS=TRUE
It goes further than 12% and gives the following result:

> [ 85%] Linking C executable kvsWebrtcClientMaster
> /usr/bin/ld: /home/pi/Downloads/kinesis-video-stream-from-rtsp/open-source/lib/libkvspicUtils.a: error adding symbols: file format not recognized
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/kvsWebrtcClientMaster.dir/build.make:105: kvsWebrtcClientMaster] Error 1
> make[1]: *** [CMakeFiles/Makefile2:114: CMakeFiles/kvsWebrtcClientMaster.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2

I assume that this library should be able to run on a Raspberry pi? Any idea on how to resolve this issue?

**Comment by SirMomster** [comment]
For future readers having this error, we (Colleagues) noticed that we had old files in our <ProjectRoot>/open-source folder (which is created when running CMake). This folder contains compiled files. However, our files were compiled for Ubuntu X64 instead of the platform we were now trying to build on (armv7l). 

After clearing the open-source folder and running CMake followed by a make everything worked fine.

**Comment by StefCeyssens** [comment]
Thx @SirMomster :) 
I indeed tried out this library first on Ubuntu and made some changes to the sample. During the copy of the files to the raspberry, I apparently also copied some ubuntu specific files.
