### ISSUE TITLE
KVSWEBRTC LIVE STREAMING IS NOT WORKING IN FIREFOX BROWSER

### ISSUE THREAD

**Issue by rajnada** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1112]
when I try to play video in firefox. I will get an answer and then received "event" in which I got the "stream: restricted" attribute,
while the same video works perfectly on google chrome and I also got a media stream object

**Error in Firefox:- 
DOMException: Answer tried to set recv when an offer did not set send**

**Logs of Mozilla Firefox:-**

this is a screenshot of the Mozilla Firefox log for reference:-
https://prnt.sc/112azpx

**Logs of Google chrome:-**

this is a screenshot of the google chrome log for reference:-
https://prnt.sc/112ay7m

**answer which I received:-**

**answer =>** {type: "answer", sdp: "v=0
↵o=- 461485223 2 IN IP4 127.0.0.1
↵s=-
↵t=0 0
…x/90000
↵a=fmtp:118 apt=123
↵a=rtcp-fb:123 nack
↵"}sdp: "v=0
↵o=- 461485223 2 IN IP4 127.0.0.1
↵s=-
↵t=0 0
↵a=group:BUNDLE 0 1
↵a=msid-semantic: WMS myKvsVideoStream
↵m=audio 9 UDP/TLS/RTP/SAVPF 0
↵c=IN IP4 127.0.0.1
↵a=msid:myKvsVideoStream myAudioTrack
↵a=ssrc:534900171 cname:u+sFyw1MPSrSqi6F
↵a=ssrc:534900171 msid:myKvsVideoStream myAudioTrack
↵a=ssrc:534900171 mslabel:myKvsVideoStream
↵a=ssrc:534900171 label:myAudioTrack
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=ice-ufrag:Mz3o
↵a=ice-pwd:QVRV2NtgRaAQvNahNU2OSQQy
↵a=ice-options:trickle
↵a=fingerprint:sha-256 FD:CA:06:7D:2C:6F:DF:9B:DB:2C:C8:DA:88:96:25:C8:6D:1F:B6:C4:FB:B2:5D:9E:35:34:A4:0F:F5:42:80:B5
↵a=setup:active
↵a=mid:0
↵a=sendrecv
↵a=rtcp-mux
↵a=rtcp-rsize
↵a=rtpmap:0 PCMU/8000
↵a=rtcp-fb:0 nack
↵m=video 9 UDP/TLS/RTP/SAVPF 123 118
↵c=IN IP4 127.0.0.1
↵a=msid:myKvsVideoStream myVideoTrackRTX
↵a=ssrc-group:FID 2062660401 318622851
↵a=ssrc:2062660401 cname:u+sFyw1MPSrSqi6F
↵a=ssrc:2062660401 msid:myKvsVideoStream myVideoTrack
↵a=ssrc:2062660401 mslabel:myKvsVideoStream
↵a=ssrc:2062660401 label:myVideoTrack
↵a=ssrc:318622851 cname:u+sFyw1MPSrSqi6F
↵a=ssrc:318622851 msid:myKvsVideoStream myVideoTrackRTX
↵a=ssrc:318622851 mslabel:myKvsVideoStreamRTX
↵a=ssrc:318622851 label:myVideoTrackRTX
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=ice-ufrag:Mz3o
↵a=ice-pwd:QVRV2NtgRaAQvNahNU2OSQQy
↵a=ice-options:trickle
↵a=fingerprint:sha-256 FD:CA:06:7D:2C:6F:DF:9B:DB:2C:C8:DA:88:96:25:C8:6D:1F:B6:C4:FB:B2:5D:9E:35:34:A4:0F:F5:42:80:B5
↵a=setup:active
↵a=mid:1
↵a=sendrecv
↵a=rtcp-mux
↵a=rtcp-rsize
↵a=rtpmap:123 H264/90000
↵a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
↵a=rtpmap:118 rtx/90000
↵a=fmtp:118 apt=123
↵a=rtcp-fb:123 nack
↵"type: "answer"proto: Object

Can anyone help me with this situation
thank you in advance :)

**Comment by disa6302** [comment]
@rajnada , 

Are you running the master sample as is? Can you describe your scenario a little and also attach logs from the master with the SDPs? 
Run: 
`export DEBUG_LOG_SDP=TRUE`

**Comment by disa6302** [comment]
@rajnada , 
Any updates?

**Comment by rajnada** [comment]
@disa6302 
Actually we are getting data(streaming) from IOT based device(cameras) using **"amazon-kinesis-video-streams-webrtc"** package 
so we connect(Role) as a VIEWER.

So, MASTER is not in our hand 
or if possible then could you tell me "how to get logs of master?"

Thanks in advance for the support

**Comment by disa6302** [comment]
You should be able to access your IOT camera device side logs.

**Comment by disa6302** [comment]
Closing since issue has gone stale.
