### ISSUE TITLE
Trouble with High resolution frame 

### ISSUE THREAD

**Issue by wolfviking0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1114]
Hi, I am using kinesis webrtc from few months and it’s really work fine.
I am currently using Cisco for the h264 encoding. It’s work fine when I use lower resolution but when I start using 4K I have some black output but no error.
I am also able to use nvenc to create h264 and it’s working great too but when I try 2048, I am having a similar issue.
Sometime I can see the first frame coming but then it’s like hanging same if I call the writeFrame function.

Any idea why I am having this issue ? Is it possible the size of the data h264 could be a problem.
It seems my h264 from nvenc is bigger than the Cisco one.

**Comment by disa6302** [comment]
@wolfviking0 , 

We might need VERBOSE logs to look into it. Can you attach some logs please?

**Comment by wolfviking0** [comment]
Hi @disa6302,
The issue seems to be on the size of the h264.
My h264 from nvenc is much bigger than Cisco one, reducing the size help me to make it work.
I was able to stream my 4K data.

**Comment by disa6302** [comment]
That is great! I will close the issue in that case.
