### ISSUE TITLE
Easy get ICE_AGENT_STATE_DISCONNECTED when streaming over internet

### ISSUE THREAD

**Issue by nguyenduynghia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1115]
It is fine when I connect on local network.
But when I tried to connect over internet, I got this state after a short time.
Log file only show that:
```
[2021-04-05 15:23:59]-DEBUG-stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000020
[2021-04-05 15:23:59]-DEBUG-executeDisconnectedIceAgentState(): Ice agent detected disconnection. current state ICE_AGENT_STATE_READY. Last data received time 1617611008 s
```

Is there any way to find out what cause this state?

**Comment by disa6302** [comment]
@nguyenduynghia , 

Please include more details: 

1. What is your set up? 
2. Does the viewer disconnect anytime? Or network drops? 
3. Please attach complete logs. 2 log lines do not give any information.

**Comment by zhuker** [comment]
I started seeing this recently as well in certain setups, trying to narrow
it down

**Comment by nguyenduynghia** [comment]
I want to view video of 4 IP cameras. So I create one WebRTC Channel and use 4 peer connections.
It works fine on LAN. When I view via internet, it display video for a short time and  then disconnect.
Here is log file.
[kvs.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6277457/kvs.log)

**Comment by zhuker** [comment]
@nguyenduynghia 
do you use `peerConnectionOnSenderBandwidthEstimation` API?
if so try applying this patch and let me know if you see any difference
```
diff --git a/src/source/PeerConnection/Rtcp.c b/src/source/PeerConnection/Rtcp.c
index de35f8e08..d20f68786 100644
--- a/src/source/PeerConnection/Rtcp.c
+++ b/src/source/PeerConnection/Rtcp.c
@@ -319,6 +319,8 @@ STATUS onRtcpTwccPacket(PRtcpPacket pRtcpPacket, PKvsPeerConnection pKvsPeerConn
     }
 
     if (duration > 0) {
+        MUTEX_UNLOCK(pKvsPeerConnection->twccLock);
+        locked = FALSE;
         pKvsPeerConnection->onSenderBandwidthEstimation(pKvsPeerConnection->onSenderBandwidthEstimationCustomData, sentBytes, receivedBytes,
                                                         sentPackets, receivedPackets, duration);
     }
```

**Comment by nguyenduynghia** [comment]
> @nguyenduynghia
> do you use `peerConnectionOnSenderBandwidthEstimation` API?
> if so try applying this patch and let me know if you see any difference
> 
> ```
> diff --git a/src/source/PeerConnection/Rtcp.c b/src/source/PeerConnection/Rtcp.c
> index de35f8e08..d20f68786 100644
> --- a/src/source/PeerConnection/Rtcp.c
> +++ b/src/source/PeerConnection/Rtcp.c
> @@ -319,6 +319,8 @@ STATUS onRtcpTwccPacket(PRtcpPacket pRtcpPacket, PKvsPeerConnection pKvsPeerConn
>      }
>  
>      if (duration > 0) {
> +        MUTEX_UNLOCK(pKvsPeerConnection->twccLock);
> +        locked = FALSE;
>          pKvsPeerConnection->onSenderBandwidthEstimation(pKvsPeerConnection->onSenderBandwidthEstimationCustomData, sentBytes, receivedBytes,
>                                                          sentPackets, receivedPackets, duration);
>      }
> ```

Hi zhuker,
I couldn't fine these code on Release 1.5.0.
Do you mean the latest source code?
Is it ok if I use the latest code instead of release version?

**Comment by zhuker** [comment]
Yes this patch is against the latest master
If you are not using the peerConnectionOnSenderBandwidth api this won't
affect you
As a matter of fact the patch was already merged into master - use that and
report back

**Comment by nguyenduynghia** [comment]
I found one strange thing while streaming over internet.
Master app is still uploading video, while web client couldn't receive any data.
Do you know the reason?

**Comment by disa6302** [comment]
Master would keep sending out the bytes until the viewer is closed and it sends the DTLS alert. Is that what is happening?

**Comment by nguyenduynghia** [comment]
> Master would keep sending out the bytes until the viewer is closed and it sends the DTLS alert. Is that what is happening?

Yes, It is working like this.

**Comment by disa6302** [comment]
Do you see a DTLS close alert from the viewer?

**Comment by nguyenduynghia** [comment]
There is no close alert. Master is still uploading video but web client couldn't receive.

**Comment by disa6302** [comment]
Ok. 
I suspect a connection loss. Something is causing ICE keep alive messages to not reach the master. Keep alive should be received every 15 seconds.

**Comment by disa6302** [comment]
Closing due to no response. Feel free to reopen if you are still facing an issue.
