### ISSUE TITLE
[QUESTION] AEC(Acoustic Echo Cancellation) function

### ISSUE THREAD

**Issue by JacobLeeYootaek** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1116]
Hi, I'm making voice communication function with WebRTC. As I know, WebRTC supports AEC function but I can't find it in this SDK.
Does it support AEC? If it is, is there any sample about that? Thank you.

**Comment by disa6302** [comment]
@JacobLeeYootaek , 

We do not have AEC in our SDK currently. I am going to add an enhancement tag to look into it.

**Comment by JacobLeeYootaek** [comment]
Will you add AEC in this SDK?

**Comment by disa6302** [comment]
@JacobLeeYootaek , 

We need to evaluate this. Will update the ticket once I get a chance to look into this.

**Comment by hassanctech** [comment]
@JacobLeeYootaek Also, we welcome contributions from the community! If you have an implementation you'd like to share feel free to open a PR!

**Comment by juno52wendy** [comment]
This is a gateway protocol project. Will it support such a function for a while?

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.
