### ISSUE TITLE
[FEATURE] Support of H265

### ISSUE THREAD

**Issue by wolfviking0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1124]
Hi,

I am using the SDK with nvenc, and I have the possibility to use h265 output from nvenc.

Some browser can support h265 with webrtc : https://webrtcbydralex.com/index.php/2020/04/28/how-to-enable-hevc-h265-and-av1-in-webrtc-in-your-browser/

I would like to know if h265 could be use with the sdk?

what kind of change will be required in order to add this support ?

Thanks

**Comment by zhuker** [comment]
You would need to
1. create 265 payloader like this one `src/source/Rtp/Codecs/RtpH264Payloader.c`
2. support SDP negotiation for the codec
3. @disa6302 what else?

**Comment by disa6302** [comment]
@wolfviking0 , 

We do not currently include this, but the changes @zhuker mentioned should do it pretty much. 
Assigning myself to this issue. Will add an update once the support is added.

**Comment by zhuker** [comment]
@disa6302 have you thought of supporting h264 profiles other than baseline we have today? Main and high profiles provide very good video quality and it doesn't look like too much work. 
Just saying...

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.

**Comment by WWWshan** [comment]
I see the file name ""RtpH265Payloader.c" ， so Is H265 supported now?  Looking forward to your reply @zhuker
