### ISSUE TITLE
[QUESTION]How to use data channel to send large data over 4k?

### ISSUE THREAD

**Issue by lory17** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1126]
Hi :
I want to send some data from kvs to remote app through data channel. but I met a problem when use data channel to send data. this is my test code. I only modified Common.c
```cpp
VOID onDataChannelMessage(UINT64 customData, PRtcDataChannel pDataChannel, BOOL isBinary, PBYTE pMessage, UINT32 pMessageLen)
{
    UNUSED_PARAM(customData);
    UNUSED_PARAM(pDataChannel);
    if (isBinary)
    {
        DLOGI("DataChannel Binary Message");
    }
    else
    {
        DLOGI("DataChannel String Message: %.*s", pMessageLen, pMessage);
    }

    dataChannelSend(pDataChannel, isBinary, pMessage, pMessageLen);
}
```
I did two tests：
1. I'll send it back when I get the message.  In my test case, I can't receive data which data size is 4096(or more) from android App. but  App can't received any data if data size is above 1140.   

2. I send data from android  App1 to android  App2 data size is 4096(or more), App2 can receive the data, which data lenth is 4096.

From these two tests, I think it is not App‘s issue.  There must be something wrong with the way I use data channel? 
Please give me some advices.  Thank you very much!

**Comment by lory17** [comment]
I do another test:
use dataChannelSend() api to send 1024-2048 length data. I can only send 1350 length data.  If  the length > 1350 usrsctp_sendv will return error.

**Comment by disa6302** [comment]
@lory17 , 

If I am not wrong, there is a limit on the number of bytes that can be transferred with `usrsctp_sendv`. I need to look into it. Can you attach the logs please?

**Comment by lory17** [comment]
@disa6302 
Thanks for your reply, here is my test log: 
[kvs_usrsctp_sendv.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6321948/kvs_usrsctp_sendv.txt)

I have create a data channel then send data to remote device, this is my test code:
```cpp
PVOID sendVideoStreamingThread(PVOID args)
{
    PRtcDataChannel pDataChannel = (PRtcDataChannel)args;

    char pMessage[2048] = { 0 };
    unsigned int snd_Size = 0, pMessageLen = SIZEOF(pMessage);

    THREAD_SLEEP(10 * HUNDREDS_OF_NANOS_IN_A_SECOND);

    for (int i = 0; i < 1000; i++) {
        snd_Size = dataChannelSend(pDataChannel, TRUE, pMessage, pMessageLen / 2 + i);
        if (snd_Size != STATUS_SUCCESS) {
            DLOGI("DataChannel Binary Message send error");
            break;
        }
    }
}
```

**Comment by disa6302** [comment]
@lory17 , 

Have you tried sending data of smaller sizes?

**Comment by disa6302** [comment]
Closing since issue has gone stale. Feel free to reopen if you face any issues
