### ISSUE TITLE
[QUESTION] How do I start as VIEWER using Gstreamer Sample code?

### ISSUE THREAD

**Issue by Lingling77** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1131]
Hi there,

I am pretty new to this and still learning. The kvsWebRTCClientMasterGstreamerSample.c works very well, I used that code for Viewer by changing the Role to SIGNALING_CHANNEL_ROLE_TYPE_VIEWER on [this line](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L349), but it's not working. Did anyone know how to do it? Many thanks!

**Comment by disa6302** [comment]
@Lingling77 , 

There is a specific viewer sample app. You need to add Gstreamer code into it for your use case.
