### ISSUE TITLE
[QUESTION]Does it really have End-to-end Encryption?

### ISSUE THREAD

**Issue by RW0624** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1134]
Hi, end-to-end encryption is mandatory for WebRTC using DTLS-SRTP. However, I found KVS Signaling channel's media playback can actually view my media. In my principle, the end-to-end encryption media should only be visualized by two endpoints. For example, IP Camera as Master and mobile application as viewer. AWS should not be able to watch my media. In my use case, I really do not want any party to watch my content including AWS. If I want to achieve this, should I do one more encryption on top of the media stream. It is feasible?

**Comment by MushMal** [comment]
I assume what you are referring to is the console player. It's running under the local web browser and acts as your peer. In essence, the DTLS transport protects the communication between your master device and your viewer which is the browser. And, yes, your browser is running JS-based WebRTC.

Please feel free to resolve if you have no further questions

**Comment by disa6302** [comment]
Closing assuming question is answered.
