### ISSUE TITLE
[FEATURE] support AV1

### ISSUE THREAD

**Issue by flying1314** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1135]
do you have plan to support AV1?

**Comment by juno52wendy** [comment]
It is not difficult to support this function. The main ones are 1. Increase SDP and describe accordingly, 2. Increase RTP-related AV1 data packaging, 3. Current browsers do not support this piece very well.

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.

**Comment by heyakyra** [comment]
Any updates?
