### ISSUE TITLE
[Question] crosscompile to aarch64-linux-android?

### ISSUE THREAD

**Issue by mechavarriahipcam** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1137]
Hi, 
I can see on the docu:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c
how can cross compile to a aarch64-linux-android architecture using Android ndk?

**Comment by disa6302** [comment]
@mechavarriahipcam , 

We have not tested or done that. If you are looking for using webrtc on android, you can probably look at https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android. Closing this issue for now. Feel free to reach out if you have any other questions.

**Comment by mehmetcy84** [comment]
@disa6302 
I know there is a separate Kinesis Android SDK, but I need to build the Kinesis embedded C SDK to use the built libraries in an Android project.

In cross-compilation section of the sdk overview page, certain environment variables are mentioned to be set.

Is it possible to build the Kinesis C SDK along with its all dependencies contained in the repository, to produce libraries that can be added to Android Studio for Android app development?
What would be the selection of accepted parameters for these variables, and specifically for Android?

> If you wish to cross-compile CC and CXX are respected when building the library and all its dependencies. You will also need to set BUILD_OPENSSL_PLATFORM, BUILD_LIBSRTP_HOST_PLATFORM and BUILD_LIBSRTP_DESTINATION_PLATFORM. See our codecov.io for an example of this. Every commit is cross compiled to ensure that it continues to work.
