### ISSUE TITLE
[QUESTION] KinesisVideoWebRTCClient to  aarch64-linux-android 

### ISSUE THREAD

**Issue by mechavarriahipcam** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1138]
We are working on proprietary hardware that can run Android but since we were informed that the project they are maintaining is the C language project and not Java, we see the need to implement webRTC with the C version. Now we are trying to cross compile of the KinesisVideoWebRTCClient project for  aarch64-linux-android but we do not understand well what would be the steps to follow to do it using the Android ndk.

**Comment by disa6302** [comment]
@mechavarriahipcam , 

As mentioned in your previous issue, we have unfortunately not tried cross compiling this SDK using `aarch64-linux-android`. The first things you will need to do is check how you can cross compile the [dependencies](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/master/CMake/Dependencies) for the platform. [This](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/3af48f92b45d989b553ff17305a99f8e3dc40f7e/.travis.yml#L165) could be a useful reference for cross compiling .

This is 1 more pointer you might find useful.
https://developer.android.com/ndk/guides/other_build_systems

I am closing this issue assuming question is answered. However, feel free to re-open if you have any other questions. Thank you for reaching out.
