### ISSUE TITLE
[CONTRIBUTION] Fix doxygen comments on certain struct members

### ISSUE THREAD

**Issue by kev-the-dev** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1139]
Certain struct members have doxygen comments formatted incorrectly, causing their description to be missing in the generated doxygen HTML, or actually appear in a different struct member, creating confusion for developers:

- [RtcDataChanne.id](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-c/struct____RtcDataChannel.html)
- [RtcConfiguration.certificates](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-c/group__StatusCodes.html#ga73ae9949af12346cc594538b711280e7)

(I'm working on a PR to fix these issues and will submit shortly)

**Comment by disa6302** [comment]
Merged your PR. Thanks again!
