### ISSUE TITLE
[QUESTION] is there any typical cpu and memory requirement?

### ISSUE THREAD

**Issue by cyenux** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1143]
we are working for some embedded devices, and i notice 15M memory requirement on aws docs.
But is there any more detail data? for typical cpu and memory requirement
Such as raspberry pi or nvidia jetson linux target, requirement for one-way or two-way webrtc av stream.
Thanks a lot

**Comment by disa6302** [comment]
@cyenux ,

I do not believe we have any specific platform data out there
