### ISSUE TITLE
[BUG] Streaming session is not terminated correctly

### ISSUE THREAD

**Issue by tuncalie** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1144]
Occasionally, when the sample is running as master and a remote client stops streaming, freeSampleStreamingSession() function in samples/Common.c does not return after calling timerQueueCancelTimer(). 

I placed line-by-line logs and timerQueueCancelTimer is the last call. timerQueueCancelTimer doesn't seem to return.

**Comment by zhuker** [comment]
This happens to me when there's a lock inversion condition. Application
level lock conflicts with the library lock.
Try running your app with tsan.

**Comment by disa6302** [comment]
@tuncalie , 

Are there any app level changes you have made? 
Can you provide a stack trace and logs?

**Comment by disa6302** [comment]
Closing due to no traction. Reopen if you have more info.

**Comment by disa6302** [comment]
Will wait on logs based on offline discussion.

**Comment by disa6302** [comment]
@tuncalie , 

Do you have an update on this?

**Comment by disa6302** [comment]
Closing since it has gone stale.

**Comment by jdelapla** [comment]
We cannot make progress on a bug report without the requested information. This item will remain closed until logs are provided.
