### ISSUE TITLE
how to send viewer statics which appears in kinesis page to our angular dashboard ?

### ISSUE THREAD

**Issue by msfarhann** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1146]
Hello team,

I like to achieve the viewer statics tab which appears in the signalling channel https://ap-south-1.console.aws.amazon.com/kinesisvideo/home?region=ap-south-1#/signalingChannels/signalingChannelName/abc under media playback viewer to appear in our angular frontend dashboard.

it will help us determine whether the video has stopped playing and some other benefits.

image shown below of viewer statics
![image](https://user-images.githubusercontent.com/68335060/118772235-21212d80-b8a1-11eb-8b80-5c16ba3a7058.png)

**Comment by disa6302** [comment]
@msfarhann , 

Not sure if that is possible. You can pull viewer stats on your own by using the JS APIs and tie it with your angular dashboard. https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats. You can use the [JS SDK](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js) to view the video as well.

**Comment by disa6302** [comment]
Closing assuming answered.
