### ISSUE TITLE
[BUG] when using mbedtls, iot core credential crashed

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1147]
When using this sdk with mbedtls, iot core credential crashed. I created one pr on libwebsockets to fix this problem. Just mention it here, in case that someone encounters the same problem.
https://github.com/warmcat/libwebsockets/pull/2304

**Comment by disa6302** [comment]
@ycyang1229 , 

This SDK uses v3.2.3 of the libwebsocket library and the files are very different. Does the problem persist in v3.2.3 of libwebsocket as well?

**Comment by ycyang1229** [comment]
Yes, it is one common bug.
