### ISSUE TITLE
[BUG] PCMA / PCMU does not work from master (using C SDK) to client (using JS or Android or IOS SDK)

### ISSUE THREAD

**Issue by sylvain-fano** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1149]
**Logging**
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

**Describe the bug**
we are implementing C SDK into an IoT camera. 
video is running perfectly, but audio is garbage. 
we use h264 for video and pcma or pcmu for audio (we tried both, same result) . camera is acting as master, and webpage or android app are acting as viewer. 
as said above, video is smooth, but audio does not work. sometimes no sound at all, but sometimes, it seems like some noise is trying to output on viewers ... 

please note that audio from viewers to master is OK (pcma too) ! 

in order to debug, we tried to record audio stream on a dedicated file on sdcard from camera just before sending frames to aws lib. When playing this audio record with external tool like Audacity, we can successfully play audio. 

we cannot try with OPUS since we dont have enough room to fit opus lib inside camera. we need to use either PCMa or PCMu

**SDK version number**
using latest master branch sources from 2021/05/21

Please find debugs from chrome://webrtc attached

[webrtc_internals_dump.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6520926/webrtc_internals_dump.txt)

**Comment by disa6302** [comment]
@sylvain-fano ,

Can you attach the SDK logs please? Also, what are the changes you make in the sample to accommodate PCMA/PCMU?

**Comment by sylvain-fano** [comment]
@disa6302 ,

thanks for your answer, 

Please find SDK log and and screenshot of the changes we made on sample attached :

![screenshotalaw](https://user-images.githubusercontent.com/31700396/119465121-b01bc300-bd43-11eb-8845-1e65f7839f3a.png)

[alaw.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6537709/alaw.log)

**Comment by sylvain-fano** [comment]
Hey all, 

we finally made it work !

we fixed the problem by sending correct timestamps to aws lib :

**timestamps sent were values in milliseconds instead of hundreds of nanoseconds** 

(i still don't understand why video was working since the beginning whereas we did the exact same mistake ... ) 

i think this part could be more detailed in sample IMHO

Anyway, thanks for your help
