### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by Sean-Der** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#115]
We need IPv6 support, we should allow the user to opt in/out. In some cases you have IPv6, but all packets are discarded so just causes spam in the logs.

**Comment by lherman-cs** [comment]
Status:
* Added host candidates support: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/382
* Added reflexive candidates support: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/417

**Comment by lherman-cs** [comment]
I'm closing this issue we have added essential IPv6 support.
