### ISSUE TITLE
[FEATURE] the mbedtls support for srtp

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1159]
I added the mbedtls support for srtp(https://github.com/cisco/libsrtp/pull/512), it is merged, and it speeds up the encryption of packets. Hope this can help people use mbedtls with this sdk. thanks.

**Comment by disa6302** [comment]
@ycyang1229 , I have combined the two into a single ticket. Closing this in favour of that.
