### ISSUE TITLE
[BUG]iceAgentAddRemoteCandidate can't parse IPv6 address string

### ISSUE THREAD

**Issue by YOSI-yoshidayuji** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1165]
In my environment kvsWebrtcClientMasterGstSample always outputs the following log.
"ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000003"

I investigated the cause. This error is occurring here.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.c#L368

When I output the contents of ipBuf, it was "dxxxxx0-axxa-4xxe-9xxb-dxxxxxxxxxx3.local". (I hid some letters)
I use AWS media playback viewer for the client.

**Comment by disa6302** [comment]
@YOSI-yoshidayuji , 

We do not support IPv6 candidates currently. Closing this now. Feel free to reach out if you have any questions.
