### ISSUE TITLE
SENDING BIG FILES OVER DATACHANNEL

### ISSUE THREAD

**Issue by mukesh-2538** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1169]
I am trying to send a big file over datachannel, size of the file being ~740KB (740156 bytes). I am chunking it into smaller chunks of 16KB each which ends up into 46 smaller chunks( each of 16KB).
**OBSERVATION**

- The  datatransfer over dataChannel  failed with "0x0000000c" code.
-  Adding a delay of 20ms after every chunks leads to a successful data transfer, but adds to the latency of sending data.

**Question**

- Is this due to the network buffer size used by the sdk? Can it be increased?

**Comment by suggestedfixes** [comment]
One piece of information I know: for data transfer over TURN, there is a bandwidth limit of 5Mbps.
https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-limits.html

**Comment by hassanctech** [comment]
I suspect you're hitting this:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Sctp/Sctp.c#L193

The error code you posted corresponds to `STATUS_INTERNAL_ERROR`

I'm not sure here need to investigate but maybe `libusrsctp` has a max buffer that's less than 740KB, I will look into this but wanted to post this here to give you some possible leads.

**Comment by hassanctech** [comment]
Yeah I think the limit is 256kB by default.  Try sending chunks of 256kB to get your data out faster does that work for you and/or is that an acceptable solution?  I will look to see if there's a way to increase this default limit.

**Comment by hassanctech** [comment]
I see this:

"usrsctp_sysctl_set_sctp_sendspace()
The space of the available send buffer can be changed from its default value of 262,144 bytes to a value between 0 and 2^32 - 1 bytes."

Here:  https://github.com/Kurento/libusrsctp/blob/master/Manual.md#usrsctp_sysctl_set_sctp_sendspace

Can you try setting this to (1MB):

`usrsctp_sysctl_set_sctp_sendspace(1024 * 1024)`

Immediate before this line:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Sctp/Sctp.c#L193

Let me know if that works for you?

**Comment by mukesh-2538** [comment]
@hassanctech. It failed even after setting it to 1 MB

**Comment by disa6302** [comment]
@mukesh-2538 ,

We do not control the size of the buffer sent to sctp. Perhaps, this would be a better question in the SCTP forum. As per their documentation, using `usrsctp_sysctl_set_sctp_sendspace()` should work, unless, there is some OS level control for buffering. Looking at the `usrsctp` documentation, this is the only way to set the buffer size.
