### ISSUE TITLE
[BUG] Invalid SDP generated if different number of trancievers.

### ISSUE THREAD

**Issue by kev-the-dev** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1171]
**Describe the bug**
If you attempt to generate an SDP answer or a peer connection that has more transceivers than the offer SDP, it will generate
an SDP with a blank line `a=`. It appear to be looking past the valid portion of the list due to how transceiver reordering is done in SessionDescription.c. But even if the below defensive programming strategy is employed, the SDP comes out invalid because "m lines are out of order" (according to chrome). Presumably in such cases an error status should be returned, or a valid SDP should be produced with the extra transceivers unused.

I can try to create a code sample to repro, but putting here early for cross referencing from an internal issue

```
diff --git src/source/PeerConnection/SessionDescription.c src/source/PeerConnection/SessionDescription.c
index 8789e24d6..cb30c2660 100644
--- src/source/PeerConnection/SessionDescription.c
+++ src/source/PeerConnection/SessionDescription.c
@@ -545,6 +545,11 @@ STATUS populateSingleMediaSection(PKvsPeerConnection pKvsPeerConnection, PKvsRtp
                 directionFound = TRUE;
             }
         }
+
+        if (!directionFound) {
+            DLOGW("Incorrect/no transceiver direction set...this attribute will be set to inactive");
+            STRCPY(pSdpMediaDescription->sdpAttributes[attributeCount].attributeName, "inactive");
+        }
     }

     attributeCount++;
```

**Comment by hassanctech** [comment]
Yes this is a known issue we will not create extra transceivers to match extra m-lines in the offer, the master (answerer) side needs to have created those transceivers. The idea is the answer side (master) should have transceivers added for greater than or equal to the number of m-lines it expects to receive from the offer.  The answerer (master side) WILL correctly drop transceivers (i.e not generate m-lines) that have no corresponding m-line in the offer.  

We have an existing bug open to address this:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/803

**Comment by disa6302** [comment]
Closing due to no response. Feel free to reopen when you have more updates.
