### ISSUE TITLE
Issue with kvs with webRTC 2 way Audio on Raspberry Pi 

### ISSUE THREAD

**Issue by Austinj12** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1173]
I’m trying to achieve 2-Way Audio with a raspberry pi running the Rasperry Pi OS 32-bit.

I have successfully used the Amazon Kinesis Video Streams C WebRTC SDK on my raspberry pi to send video and audio to a signalling channel with the kvsWebrtcClientMasterGstSample. The only change that I had to make to that sample was to change the G-streamer string to

"autovideosrc ! queue ! videoconvert ! video/x-raw,width=1280,height=720,framerate=[30/1,10000000/333333] ! "
                                     "x264enc bframes=0 speed-preset=veryfast bitrate=512 byte-stream=TRUE tune=zerolatency ! "
                                     "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE "
                                     "name=appsink-video alsasrc device=plughw:Stream,0 ! "

                                     "queue leaky=2 max-size-buffers=400 ! audioconvert ! audioresample ! opusenc ! "
                                     "audio/x-opus,rate=48000,channels=2 ! appsink sync=TRUE emit-signals=TRUE name=appsink-audio"

because, for some reason the default audio source was not working. 

Now I am trying to use kvsWebRTCClientViewer on my raspberry pi to consume audio that I am sending to a signaling channel from the javascript test page. I confirmed that audio was being sent in the AWS console. Unfortunately, nothing is playing on my raspberry pi when I run that sample code. I was told by the AWS team that that sample is supposed to support audio out of the box. I’d really appreciate some guidance as to what to try next.

Thanks!

**Comment by hassanctech** [comment]
Can you please confirm which version/release of the SDK you're using?

What happens when you test with the test page:  https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html

Do you see the audio/video there when you run the `kvsWebrtcClientMasterGstSample` ?

What have you tried to debug the audio source do you know for sure it's successfully producing audio?  What happens if you just run the stock sample without changes and use the test page linked above, does that work?  I just want to understand if the samples provided work as is and specifically what changes you've made to them.

**Comment by disa6302** [comment]
Also, please update the title to clearly highlight the issue.

**Comment by Austinj12** [comment]
@hassanctech Yes I do see audio and video when I run the kvsWebrtcClientMasterGstSample. There is no problem getting audio from my raspberry pi. The problem is getting audio to the raspberry pi. I'm using the test page to send audio to the signalling channel successfully ( I checked in the AWS console). But when I run the viewer sample (unedited) nothing plays on the raspberry pi.

**Comment by hassanctech** [comment]
Perhaps the rpi doesn't have support for the audio codec, did you see the offer/answer exchange.  It would be nice to see what audio codec support was advertised by rpi in the offer it sent and what was picked by the master answer.

Also can you please specify which commit/release version of the SDK you are using?

**Comment by Austinj12** [comment]
Where do I find the specific version?

**Comment by hassanctech** [comment]
To clarify, in the viewer sample we add some transceivers which specify support for certain audio codecs.  It could be you need to modify these if what is added by default are actually not supported by rpi in which case it would be claiming support for it but it actually cannot decode it hence why it can't play it.

**Comment by hassanctech** [comment]
`git log` should tell you the commit hash.

**Comment by Austinj12** [comment]
commit e90913ed4902dc6e4b492af5424fe40261ee34f4 was the top commit that got returned from git log

**Comment by Austinj12** [comment]
e90913ed4902dc6e4b492af5424fe40261ee34f4

**Comment by Austinj12** [comment]
github seems to be chopping off my response for some reason: 'e90913ed4902dc6e4b492af5424fe40261ee34f4' I had to surround with quotes to give the full value

**Comment by hassanctech** [comment]
Ok that is fairly recent, thanks.

Here is where the audio transceiver is set up:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L479-L485

The offer will include this as an option in the m=audio section of the offer.  If you can print out your SDP attribute dump for both the offer and answer we should be able to figure it out.

**Comment by hassanctech** [comment]
Yeah I don't need the full one the one that's there actually is a link to the actual commit so it's more helpful :)

**Comment by Austinj12** [comment]
Haha oh I see. That makes sense

**Comment by Austinj12** [comment]
> Ok that is fairly recent, thanks.
> 
> Here is where the audio transceiver is set up:
> 
> https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L479-L485
> 
> The offer will include this as an option in the m=audio section of the offer. If you can print out your SDP attribute dump for both the offer and answer we should be able to figure it out.

Sorry, I'm not exactly sure what you are asking me to do here

**Comment by hassanctech** [comment]
Ok I think the easiest way to do this is as follows:

On the side where the master sample is running, before you start the program run the following command in your shell:
`export DEBUG_LOG_SDP=TRUE`

This will cause the offer/answer to be printed to the console.  You'll see two sections one that has the local session description and one that has the remote session description, please include both of those and attach here (better if you attach it as a file it's harder to read if you just copy/paste the contents in the comment).

**Comment by Austinj12** [comment]
I was using the sample page as the master. Do I need to download the sdk on another device to run it instead?

**Comment by hassanctech** [comment]
That's even easier, what browser are you using?  If you're using Chrome then open up:  `chrome://webrtc-internals/` in a new tab.  If you're using FF then open up `about:webrtc` in another tab.  Now you can start and stop the streaming session (from when you start the master to when the viewer sends its offer.  By that time the browser will have received and logged both remote/local SDP from the offer/answer.  Just save that into the text file.

**Comment by disa6302** [comment]
Closing since the issue has gone stale. Feel free to reopen if you have any more questions.
