### ISSUE TITLE
[BUG]  iceAgentLogNewCandidate() unable to decipher protocol from remote SDP

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1174]
**Logging**
5 2021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 172.218.223.215:57470. Type: srflx. Protocol: UNKNOWN.
142021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 172.218.223.215:57466. Type: srflx. Protocol: UNKNOWN.
:2021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 34.215.44.31:49312. Type: relay. Protocol: NA.
292021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 172.218.223.215:57468. Type: srflx. Protocol: UNKNOWN.
:03:192021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 34.215.44.31:64620. Type: relay. Protocol: NA.
22021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 34.222.141.63:58049. Type: relay. Protocol: NA.
7]2021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 34.215.44.31:61676. Type: relay. Protocol: NA.
 I:2021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 34.222.141.63:58736. Type: relay. Protocol: NA.
 2021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 34.222.141.63:58209. Type: relay. Protocol: NA.
lw2021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 34.215.44.31:61179. Type: relay. Protocol: NA.
s_2021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 34.215.44.31:60508. Type: relay. Protocol: NA.
i2021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 34.215.44.31:51884. Type: relay. Protocol: NA.
ss2021-06-15 21:29:03 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: fZ+4XiMkI. Ip: 34.222.141.63:49651. Type: relay. Protocol: NA.

**Describe the bug**
When Logging Remote Candidate, Protocol is either UNKNOWN or NA. However, when inspecting at the incoming candidate SDP, we are able see udp/tcp

**SDK version number**
3e638736df68d0e3d3a7ff93cc8f97fac3d6c024

**Additional context**

**Comment by suggestedfixes** [comment]
The problem is, the parser CAN pick up the protocol from Remote SDP here:
STATUS iceAgentAddRemoteCandidate(PIceAgent pIceAgent, PCHAR pIceCandidateString);

Also, look into test cases for add remote candidate, the protocol is part of SDP for incoming candidates.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/tst/IceFunctionalityTest.cpp#L325

**Comment by disa6302** [comment]
@suggestedfixes ,

I am unsure why we do not record the protocol while logging. The code still needs to be modified a little to ensure we log the protocol irrespective of `pTurnConnection` being set.

**Comment by disa6302** [comment]
Fix merged into the develop branch. Resolving.
