### ISSUE TITLE
[QUESTION] How to use embedded c sdk samples to listen to viewer audio input.

### ISSUE THREAD

**Issue by subham9777** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1175]
I have started kvsWebrtcClientMasterGstSample on my jetson and i can see and listen to the audio and video on the aws console in media playback. Now joining from another computer using the test page as a viewer how can i listen to the audio that the viewer is streaming. I can't see the video due to no screen but can i configure the sample in a way to listen to the audio?

**Comment by disa6302** [comment]
@subham9777 , 

Check [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/08e4d294a7466f42033a7aaeacf2521f519749f7/samples/kvsWebRTCClientMasterGstreamerSample.c#L257). You might have to modify the callback to suit your needs.  

Feel free to reach out if you have any other questions.

**Comment by subham9777** [comment]
@disa6302 Can you please help me out on how to use this function to get the audio output when i run the kvsWebrtcClientMasterGstSample application?

**Comment by disa6302** [comment]
@subham9777 ,

You will have to look at how you can modify your gstreamer pipeline to listen on incoming audio. Please take a look at this line: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/08e4d294a7466f42033a7aaeacf2521f519749f7/samples/kvsWebRTCClientMasterGstreamerSample.c#L274

**Comment by subham9777** [comment]
Hey @disa6302 i was able to modify the mentioned function and get it to work by modifying the audio_description line for gstreamer pipeline. Thanks for the help
