### ISSUE TITLE
KINESIS Signalling channel.

### ISSUE THREAD

**Issue by mukesh-2538** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1185]
Is there a way to see no. of clients and their respective peerIDs currently connected to a signalling channel on cloud watch?

**Comment by juno52wendy** [comment]
You only need to bind the peerid to your business. The signaling channel on Cloud Watch does not need to be concerned. Of course, you can modify the code yourself to bring out the channel id.

**Comment by disa6302** [comment]
@mukesh-2538 , 

I do not think there is a way to see that on Cloudwatch.
