### ISSUE TITLE
[BUG]code error  0x52000084

### ISSUE THREAD

**Issue by wangziheng437** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1186]
This error code will appear after stopping the streaming of kvs, and it will cause the loss of video data，
this is log [ERROR]: [05/07-05:35:00.181][KVS_APP][kvs_module.c::742][KVS] putFrame video failed with 0x52000084

**Comment by juno52wendy** [comment]
Stop kvs, the data stream is discarded is not normal? Releasing cleanup resources

**Comment by disa6302** [comment]
This issue seems to have been opened in an incorrect repository? 

I am closing this now due to lack of details. Please open the issue in the correct repository with more details.
