### ISSUE TITLE
Suggestions for everyone to realize the interaction between Webrtc and Web and Echoshow

### ISSUE THREAD

**Issue by juno52wendy** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1189]
********The previous research used the KVS_Webrtc project. After continuous research and testing, some boundary problems of P2P were not handled properly. The signaling service often timed out or took a very long time. The success rate of hole punching was affected. Secondly, the signaling and webrtc were coupled. The performance is too high, the code is bloated; and the implementation of NACK, REMB, TransportCC,and Jitterbuffer is not perfect. Finally, you need to modify the function yourself. The pr code or modification suggestions cannot be responded quickly, and the provided interface is not flexible enough. . In summary, the consideration cannot be commercialized;

********So I spent 4 months rolling up my sleeves and doing it myself:
1. The current implementation of webrtc supports web and echoshow interaction,
2. Technology stack: libnice, libsrtp, libsctp, RTP/RTCP, stun/turn/ice (coturn), DTLS (openssl)
3. Realization of functions: P2P/Relay, NACK, REMB, TransportCC, PLI, FIR, SR, RR, receiving and sending of all functions,
4. Advantages: you can customize the functions yourself, the interface encapsulation is more lightweight, the function coupling is low, and you can deploy your own signaling server and coturn P2P server.
5. Regardless of whether webrtc is connected to alexa with the lambda service or connected to the web, the delay is very low, and a theoretical 100% success rate can be achieved.
6. Disadvantages: Relying on the glib third-party library, the support for some embedded devices is not complete, and the glib dependency will be stripped later, and the support for embedded devices will be more complete.

***********Of course, in summary, it is not recommended that you do not use KVS_Webrtc. But If you or your team have the strength, if you do not meet the current status of KVS_Webrtc
, For the above-mentioned implementation method I provided to give you a reference idea, realize it when you are familiar with the implementation of webrtc, and it is not a problem to connect to the Web, Alexa, Android, and ios that have completed the standard implementation of Google’s standard Webrtc. It will be more helpful to your understanding of Webrtc.

**Comment by juno52wendy** [comment]
Of course, you can leave a message if you have specific questions, and we will reply as soon as possible！ TKS。

**Comment by sharadrj** [comment]
Hi @juno52wendy, 
We welcome contributions from the community to improve this project. Feel free to open PRs if you have enhancements for the SDK!

I am closing this issue as I don't see any specific technical question or bug reports that we can work on. Feel free to open new issues if you have specific issues to report.
