### ISSUE TITLE
[BUG] THREAD_JOIN inside freeSampleStreamingSession() method freezing

### ISSUE THREAD

**Issue by alexandrecolombobr** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1191]
**Logging**
File log-verbose-mode-kvsWebrtcClientMasterGstSample attached to this issue.

**Describe the bug**
After ending a streaming session, whether it is ended by the web viewer or by the sample that generates the content (**kvsWebrtcClientMasterGstSample**), the application is locked in a **THREAD_JOIN** call within the **freeSampleStreamingSession()** method, present in line 501 of the SDK's Common.c file.
The problem only occurs when running on our device (in x86 architecture it does not occur).
In the file attached to this issue, there is a log of the sample execution with the **AWS_KVS_LOG_LEVEL** option enabled in **LOG_LEVEL_VERBOSE** mode. The error occurs right after a print I entered with the message **"=========== RIGHT BEFORE THREAD_JOIN pSampleStreamingSession->receiveAudioVideoSenderTid"**. 

**SDK version number**
Commit: f3a34c21ab6018074607fc3cb3ac3701314bee67

**To Reproduce**
1. Start the **kvsWebrtcClientMasterGstSample** application with the channel-name, video-only and testsrc arguments
2. Start the viewer present on the AWS Kinesis Video Streams control panel and confirm receiving stream packets
3. End transmission, either stopping the web viewer or ending the application with a system signal (detected in the **sigintHandler()** method in the Common.c file).

**Expected behavior**
Application should terminate correctly.

**Embedded device**
 - ARM Linux 5.4.97 device with 1GB RAM and Freescale i.MX6 Dual Lite CPU

**Comment by disa6302** [comment]
@alexandrecolombobr , 

Did you miss attaching the `log-verbose-mode-kvsWebrtcClientMasterGstSample` file? I ran the sample application on release 1.5.0 but I am unable to reproducer the issue.

**Comment by alexandrecolombobr** [comment]
Sorry for that, it's now attached in this issue.
[log-verbose-mode-kvsWebrtcClientMasterGstSample.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6887982/log-verbose-mode-kvsWebrtcClientMasterGstSample.txt)

**Comment by alexandrecolombobr** [comment]
" @alexandrecolombobr alexandrecolombobr closed this 39 seconds ago"

Sorry about that.

**Comment by disa6302** [comment]
@alexandrecolombobr , 

Looking at the log, I do not see anything that stands out. Since it is not reproducible on x86, it might be difficult to debug this without a stack trace. Can you generate a stack trace for this scenario so that we can look at what the issue is?

**Comment by alexandrecolombobr** [comment]
@disa6302 

Attached are the backtrace output generated by the GDB application and libraries dependency information. 

[backtrace.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6901203/backtrace.txt)
[sharedlibrary.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6901204/sharedlibrary.txt)

**Comment by alexandrecolombobr** [comment]
@disa6302 Any insights regarding the issue we are facing? Is there any other debug file I should provide in order to help identify the problem?

Thank you.

**Comment by disa6302** [comment]
@alexandrecolombobr ,


Apologies for the delay, but can you upgrade your SDK? You are using a really old commit and there were a few sample fixes that went in after Feb 2. That might fix your issue.

Looking at the stack trace, it is possible `THREAD_JOIN` freezes because `receiveGstreamerAudioVideo` is still running somehow and gstreamer pipeline is not terminated causing blocking on `THREAD_JOIN`. But, would still be better if you upgraded the SDK to see if solves your issue.
