### ISSUE TITLE
[QUESTION] Does C sdk support creating SignalingClient by requestSigner like js sdk?

### ISSUE THREAD

**Issue by hokichaio** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1195]
Hi, sorry I am not familiar with C but does this sdk support creating SignalingClient by a signed url, instead of using AWS access key? It's doable in the js sdk but I can't find related information here.

Related document of requestSigner can be found here in the js sdk's document
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#constructor-new-signalingclientconfig

**Comment by disa6302** [comment]
@hokichaio ,

We do not support signed URLs. You need to use AWS Access Key.

**Comment by mehmetcy84** [comment]
@disa6302 Has there been a change in this? We need to support signed URLs with our client that utilizes Kinesis C SDK.

By any chance, can "IOT_CORE_ENABLE_CREDENTIALS" be used with signedURLs?

**Comment by sirknightj** [comment]
Unfortunately, this still isn't supported.

The iot credentials lets us obtain ephemeral credentials (Access Key, Secret Access Key, and Session Token) using STS. You can read more about that [here](https://docs.aws.amazon.com/iot/latest/developerguide/authorizing-direct-aws.html).

**Comment by sirknightj** [comment]
Created #1722
