### ISSUE TITLE
The interface srtp_unprotect returns the value srtp_err_status_ok after decryption, but the decrypted data is all 0xFF

### ISSUE THREAD

**Issue by remainfox** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1196]
Operating environment:
Ubuntu 16.04
gcc: version 5.4.0 20160609
openssl: version 1.1.1k
srtp: version2.2

The interface srtp_unprotect returns the value srtp_err_status_ok after decryption, but the decrypted data is all 0xFF, and there is no log printing. What could be the cause?

**Comment by disa6302** [comment]
@remainfox ,

Can you be more clear? What is the data being sent?
`srtp_err_status_ok` is an indication of no error while receiving. It does not validate the contents.

**Comment by remainfox** [comment]
It's my fault. I'm sorry
