### ISSUE TITLE
[BUG]   The pcmu data sent by echoshow, the decrypted data are all 0xFF, there is no problem with opus

### ISSUE THREAD

**Issue by LiuAriel** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1202]
Hmm, although echoshow/alexa says it supports pcmu/a, g711,  The data in this format given by Alexa has problems. All 0xFF can’t be played normally, but the past pcmu can be played when sent to Alexa. And the data I received from the web is pcmu/a, g711 is no problem, and the opus data that alexa is currently speaking is no problem, it should be a bug, and the official preference is also opus. I don't know what you think?

**Comment by disa6302** [comment]
@LiuAriel , 

I do not think I understand your set up. Can you briefly explain what it is that your. trying to do? What is the master and viewer? What version of the SDK are you using?

**Comment by LiuAriel** [comment]
@disa6302  Hi， I pulled the latest SDK code, ubuntu16.04, gcc5.4, alexa. I don’t know where to see the version. The application scenario is voice two-way intercom. The data pcmu encrypted packet sent by alexa is 102 bytes. , After decryption, it is 80 bytes, the data secondary system display is 0xff, and then sdp sets opus, the opus data encryption packet given by Alexa is 192 bytes when the packet is captured, and the decryption is 170 bytes, there is no problem.
