### ISSUE TITLE
Mbedtls Support?

### ISSUE THREAD

**Issue by fire** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#121]
Support using mbedtls? Also see https://github.com/ARMmbed/mbedtls/pull/1813.

**Comment by MushMal** [comment]
I don't see any technical reason why this can't be done. The API is compatible so it should be doable. Perhaps we can come up with a small sample at some stage?

**Comment by MushMal** [comment]
C Producer SDK has been enhanced to use mbedTLS already. We should adapt it for webrtc too
