### ISSUE TITLE
[QUESTION] Cross-compile cmake fails

### ISSUE THREAD

**Issue by tencho0221** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1211]
I'm using the latest committed version
Please tell me the workaround

Cmake Command：
cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-unknown-linux-uclibcgnueabi

Cmake log：
CMake Error at CMakeLists.txt:245 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

**Comment by hassanctech** [comment]
Please follow the steps here:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/.travis.yml#L170-L187

We CI that runs an ARM cross compile with each commit, I've verified that it is passing.  Also tried locally on a Ubuntu box with an arm toolchain and it was working fine.

**Comment by tencho0221** [comment]
I followed the procedure but it fails
failing with libsrtp

-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Found OpenSSL: /home/admin/sdk/20210730/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libssl.so;/home/admin/sdk/20210730/amazon-kinesis-video-streams-ebrtc-sdk-c/open-source/lib/libcrypto.so (found version "1.1.1g")
CMake Error at CMakeLists.txt:245 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


-- Configuring incomplete, errors occurred!
See also "/home/admin/sdk/20210730/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libsrtp/build/src/project_libsrtp-build/CMakeFiles/CMakeOutput.log".
See also "/home/admin/sdk/20210730/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libsrtp/build/src/project_libsrtp-build/CMakeFiles/CMakeError.log".
gmake[2]: *** [build/src/project_libsrtp-stamp/project_libsrtp-configure] error1
gmake[1]: *** [CMakeFiles/project_libsrtp.dir/all] error 2
gmake: *** [all] error 2
CMake Error at CMake/Utilities.cmake:72 (message):
  CMake step for libsrtp failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:131 (build_dependency)

**Comment by tencho0221** [comment]
sorry.
I upgraded the cmake version and it succeeded.
v3.6.3 -> v3.20
