### ISSUE TITLE
Cross compilation to integrate with builtroot

### ISSUE THREAD

**Issue by bilalmalik76** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1214]
Hi,

How can I cross-compile SDK? Actually, I want to integrate it with buildroot as a new package.

**Comment by hassanctech** [comment]
Here is an example of an arm cross compile in our CI:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/.travis.yml#L171-L187

I recommend looking at buildroot documentation for support with that.

If you have a specific issue or error you encounter while attempting to cross compile please open a new ticket with more specifics.
