### ISSUE TITLE
Cross Compliation Issue

### ISSUE THREAD

**Issue by bilalmalik76** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1218]
I am trying to cross-compile with this command: 
`cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-unknown-linux-uclibcgnueabi`

Getting this error:

` arm-linux-gnueabi-gcc.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/bilal/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libsrtp/build/src/project_libsrtp-build/CMakeFiles/CMakeOutput.log".
CMakeFiles/project_libsrtp.dir/build.make:106: recipe for target 'build/src/project_libsrtp-stamp/project_libsrtp-configure' failed
make[2]: *** [build/src/project_libsrtp-stamp/project_libsrtp-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/project_libsrtp.dir/all' failed
make[1]: *** [CMakeFiles/project_libsrtp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:72 (message):
  CMake step for libsrtp failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:131 (build_dependency)

-- Configuring incomplete, errors occurred!
See also "/home/bilal/amazon-kinesis-video-streams-webrtc-sdk-c/build/CMakeFiles/CMakeOutput.log".
`

**Comment by bilalmalik76** [comment]
I am able to resolve compiler not set issue, but now I am getting this error:

```
-- Found OpenSSL: /home/bilal/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libcrypto.so (found version "1.1.1g") 
CMake Error at CMakeLists.txt:245 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


-- Configuring incomplete, errors occurred!
See also "/home/bilal/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libsrtp/build/src/project_libsrtp-build/CMakeFiles/CMakeOutput.log".
See also "/home/bilal/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libsrtp/build/src/project_libsrtp-build/CMakeFiles/CMakeError.log".
CMakeFiles/project_libsrtp.dir/build.make:106: recipe for target 'build/src/project_libsrtp-stamp/project_libsrtp-configure' failed
make[2]: *** [build/src/project_libsrtp-stamp/project_libsrtp-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/project_libsrtp.dir/all' failed
make[1]: *** [CMakeFiles/project_libsrtp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:72 (message):
  CMake step for libsrtp failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:131 (build_dependency)
```

**Comment by hassanctech** [comment]
Please update your CMAKE to 3.6.3 or newer.

**Comment by bilalmalik76** [comment]
Earlier I was using 3.10.2 and after I upgraded to 3.20.2. It succeeded.  do I have to do something to cross-compile make command also?

**Comment by jdelapla** [comment]
@bilalmalik76 You've said the issue is resolved, but have a cross-compile question, is there another issue still present?

**Comment by bilalmalik76** [comment]
@jdelapla 

The issue which I am facing is that after cross-compilation when I run the make command, the sample binary files are still for x86 architecture when I check with the file file_name command.

**Comment by bilalmalik76** [comment]
Please see this: 

```
bilal@ubuntu:~/amazon-kinesis-video-streams-webrtc-sdk-c/build/samples$ cmake .. -DBUILD_TEST=TRUE -DBUILD_OPENSSL=TRUE -DBUILD_STATIC_LIBS=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DOPENSSL_EXTRA="no-async;no-asm" -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-linux
-- Kinesis Video WebRTC Client path is /home/bilal/amazon-kinesis-video-streams-webrtc-sdk-c
-- dependencies install path is /home/bilal/amazon-kinesis-video-streams-webrtc-sdk-c/open-source
-- Begin building dependencies.
-- openssl already built
-- websockets already built
-- srtp already built
-- usrsctp already built
-- gtest already built
-- kvsCommonLws already built
-- Finished building dependencies.
OPEN_SRC_INSTALL_PREFIX=/home/bilal/amazon-kinesis-video-streams-webrtc-sdk-c/open-source
gstreamer found. Will build gstreamer samples
CMake Deprecation Warning at tst/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/bilal/amazon-kinesis-video-streams-webrtc-sdk-c/build
bilal@ubuntu:~/amazon-kinesis-video-streams-webrtc-sdk-c/build/samples$ make
Consolidate compiler generated dependencies of target kvsWebrtcClient
[ 67%] Built target kvsWebrtcClient
Consolidate compiler generated dependencies of target kvsWebrtcSignalingClient
[ 80%] Built target kvsWebrtcSignalingClient
Consolidate compiler generated dependencies of target kvsWebrtcClientViewer
[ 85%] Built target kvsWebrtcClientViewer
Consolidate compiler generated dependencies of target kvsWebrtcClientMaster
[ 90%] Built target kvsWebrtcClientMaster
Consolidate compiler generated dependencies of target discoverNatBehavior
[ 94%] Built target discoverNatBehavior
Consolidate compiler generated dependencies of target kvsWebrtcClientMasterGstSample
[100%] Built target kvsWebrtcClientMasterGstSample
bilal@ubuntu:~/amazon-kinesis-video-streams-webrtc-sdk-c/build/samples$ file kvsWebrtcClientMaster
kvsWebrtcClientMaster: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=1fe8dabc5e2f96f88c60970ea3ac8c50a01ac521, with debug_info, not stripped
bilal@ubuntu:~/amazon-kinesis-video-streams-webrtc-sdk-c/build/samples$ 
```

**Comment by hassanctech** [comment]
These are our cross compile steps:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/.travis.yml#L170-L187

In particular look at 

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/.travis.yml#L184, did you do this step?

**Comment by bilalmalik76** [comment]
I followed these steps: 
```
export CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++
cmake .. -DBUILD_STATIC_LIBS=TRUE -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-unknown-linux-uclibcgnueabi
```


but I am getting this error on make even I am building on dependencies statically:
![image](https://user-images.githubusercontent.com/9848328/128976906-30885618-bb1f-40f6-91f2-54eb2721bff1.png)

**Comment by disa6302** [comment]
@bilalmalik76 ,
It is possible your libraries are not properly configured. This could be a good resource to start with: https://stackoverflow.com/questions/28942991/which-missing-library-results-in-the-message-usr-bin-ld-cannot-find-lglib-2

As such, we will not be able to help here since this seems to be local toolchain set up issue. Feel free to re-open/create a new issue once your toolchain set up and linking is fixed.

**Comment by bilalmalik76** [comment]
@disa6302 

Hi,  I am able to resolve the linking linbraries issue. But now I am getting this error: 
![image](https://user-images.githubusercontent.com/9848328/129184097-4ba3a902-2f52-4967-8633-342c202251d7.png)

**Comment by hassanctech** [comment]
@bilalmalik76 can you make sure you're using release 1.6.0.  This issue we had at an intermediate commit before our release.  Please do not use master for production use cases, there is no guarantee for it to be stable.  We recommend you use our tagged releases.

**Comment by bilalmalik76** [comment]
@hassanctech Yes, I am using release 1.6.0. To make sure I tried with the fresh download and still getting the same error.
