### ISSUE TITLE
[FEATURE] Datachannel support from C++

### ISSUE THREAD

**Issue by cyuste** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1220]
**Description**
I am using this library in a ROS2 (C++) node, i.e. an object. This node establishes a webrtc connection with a data channel and I would like to be able to process the messages received in it. For this purpose, I need to use a member (non-static) callback function when I configure `pSampleConfiguration->onDataChannel = onDataChannel` (example from kvsWebRTCClientMaster sample)

**Describe the solution you'd like**
My experience in C/C++ is very poor (sorry if this ticket does not make sense at all), but based on [what I have seen in SO ](https://stackoverflow.com/a/6544303) a possible solution would be to change the datachannel callback signature and include a pointer to the object that is using the library

**Describe alternatives you've considered**
Static function is not an option here as I need member properties to process the messages received.
I have solved it the hard way, creating a global pointer to my object and a global function and using them in the callback. It works _but_

**Other links I've found**
https://isocpp.org/wiki/faq/pointers-to-members
https://blog.mbedded.ninja/programming/languages/c-plus-plus/callbacks
https://stackoverflow.com/questions/1000663/using-a-c-class-member-function-as-a-c-callback-function

**Comment by MushMal** [comment]
Any callback takes not only a pointer to a function but also a UINT64 which is a custom data. In case you have a member function, you should define a static function that has the same signature as the callback. When specifying the private data, you pass a pointer to your object. The SDK will return that pointer as a UINT64 back when calling the callback, Within the static callback (defined by you) you cast the UINT64 back to your object type and call the member function.

This pattern is used extensively in KVS cpp producer SDK you can look at.

**Comment by cyuste** [comment]
Thank you very much @MushMal for your help, as I said, I'm quite noob using C libraries and such

Just for clarification, the `customData` pointer received in `onDataChannel` callback is for a `PSampleStreamingSession` struct, that contains `pSampleConfiguration` and finally the customData set by me in the initialisation

**Comment by ycyang1229** [comment]
> Any callback takes not only a pointer to a function but also a UINT64 which is a custom data. In case you have a member function, you should define a static function that has the same signature as the callback. When specifying the private data, you pass a pointer to your object. The SDK will return that pointer as a UINT64 back when calling the callback, Within the static callback (defined by you) you cast the UINT64 back to your object type and call the member function.
> 
> This pattern is used extensively in KVS cpp producer SDK you can look at.

@MushMal  Sorry for my ignorance. May I know why the custom data is UINT64, not PVOID? I think using PVOID will be better if users use 32bit CPU, but I am not sure about the UINT64 design here. Could you explain it to me?

**Comment by MushMal** [comment]
Custom data might not necessarily be a pointer hence the usage of UINT64. If you are using 32 bit, you can still pass a 32 bit PVOID in UINT64 - make sure you initialize the endianness, though, library entry points do initialize it anyway.
