### ISSUE TITLE
[QUESTION]Android SDK sample doesn't display data channel messages from C SDK. How can I display them? 

### ISSUE THREAD

**Issue by agrexgh** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1221]
### Brief

I'd like to use both [C SDK](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c) and [Android SDK](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android), 
but this combination has a problem with data channel communication.
As the title says, Android sample doesn't display data channel messages from C SDK sample.
How can I display them?

### The version of code

* amazon-kinesis-video-streams-webrtc-sdk-android
`4d1b0ed8dac338c0a8dddfda923a0b176cc50fb8`

* amazon-kinesis-video-streams-webrtc-sdk-c
`08e4d294a7466f42033a7aaeacf2521f519749f7` applied the patch below.
This patch makes C SDK sample to echo back the received data channel messages and show result of sending them.

```diff
diff --git a/samples/Common.c b/samples/Common.c
index f1c9f961a..368bd88cb 100644
--- a/samples/Common.c
+++ b/samples/Common.c
@@ -21,6 +21,9 @@ VOID onDataChannelMessage(UINT64 customData, PRtcDataChannel pDataChannel, BOOL
     } else {
         DLOGI("DataChannel String Message: %.*s\n", pMessageLen, pMessage);
     }
+
+    STATUS ret = dataChannelSend(pDataChannel, isBinary, pMessage, pMessageLen);
+    DLOGW("ret = %d", ret);
 }

 VOID onDataChannel(UINT64 customData, PRtcDataChannel pRtcDataChannel)
```

### How to reproduce this issue

1. Launch both sdk samples and connect them to same channel.
2. From Android sample, send a data channel message.

### Expected behavior

At 2, Android sample display the data channel message just like the one Android sample sent on the heads-up notification.

### Actual behavior

At 2, Android app *DOESNOT* display them.

### Supplement

* I can't tell which SDK sample has the problem.
* With Android SDK sample and [JS SDK](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js) sample, there is no problem.
Android sample shows the data channel messages from JS SDK sample on the heads-up notification.

**Comment by agrexgh** [comment]
This issue is equal to 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/issues/69#issue-961388394

**Comment by hassanctech** [comment]
We're currently working on enhancing the existing sample to send data channel messages, as you noted currently it does not send them.  We have verified on our setup that it in fact does work on the JS side, we should have this out in the near term, I don't have an exact date though.

**Comment by disa6302** [comment]
Closing since this issue is on the Android SDK side. As mentioned by @hassanctech , the C SDK sample now has a data channel creation integrated. We do not have a sample on the Android SDK side to demonstrate data channel message reception and reaction to it either. We will add it at some point, but no ETA yet.

**Comment by agrexgh** [comment]
@hassanctech @disa6302 
Thank you very much for replying.
Which branch or commit you're working on about this issue?
I'd like to get a little of hint about this.

**Comment by disa6302** [comment]
The C SDK master already has the data channel piece: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1203 which has been merged. We do not have anything for Android at the moment.

**Comment by agrexgh** [comment]
Thanks a lot!
I'll try it soon!

**Comment by agrexgh** [comment]
I couldn't try it because of an compile error (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1187#issuecomment-900000115).

**Comment by agrexgh** [comment]
I tried again C SDK sample (`0be097904010bb53cca44fd6453c2da953ead4d9`)
and Android SDK sample (`4d1b0ed8dac338c0a8dddfda923a0b176cc50fb8`), 
but unfortunately Android SDK sample seems not to receive data from C SDK sample.

I stop discussing this problem,
and I'll keep on investigating this at https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/issues/69.
