### ISSUE TITLE
[BUG] "Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer."

### ISSUE THREAD

**Issue by HiconKong** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1224]
**Logging**
{"sdp": "v=0
o=- 1240912386791850476 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:PsbQ
a=ice-pwd:80GwiiwBVdcwZ/Bb9xigfbIr
a=ice-options:trickle renomination
a=fingerprint:sha-256 F2:8E:26:21:D0:47:64:D6:57:A0:33:50:7E:4A:BD:28:20:B4:4D:A3:72:E0:C2:F4:52:66:E2:7E:F8:B3:53:A9
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 124 100 101 127 123 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:PsbQ
a=ice-pwd:80GwiiwBVdcwZ/Bb9xigfbIr
a=ice-options:trickle renomination
a=fingerprint:sha-256 F2:8E:26:21:D0:47:64:D6:57:A0:33:50:7E:4A:BD:28:20:B4:4D:A3:72:E0:C2:F4:52:66:E2:7E:F8:B3:53:A9
a=setup:actpass
a=mid:video
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:124 H264/90000
a=rtcp-fb:124 goog-remb
a=rtcp-fb:124 transport-cc
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack
a=rtcp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 red/90000
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=127
a=rtpmap:125 ulpfec/90000
", "type": "offer"}

{"sdp": "v=0
o=- 2139874864 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS myKvsVideoStream
m=audio 9 UDP/TLS/RTP/SAVPF 8
c=IN IP4 127.0.0.1
a=candidate:3 1 udp 16777215 0000:0000:0000:0000:0000:0000:0000:0000 0 typ relay raddr ::/0 rport 0 generation 0 network-cost 999
a=candidate:2 1 udp 16777215 0000:0000:0000:0000:0000:0000:0000:0000 0 typ relay raddr ::/0 rport 0 generation 0 network-cost 999
a=candidate:1 1 udp 1694498815 172.16.21.222 51062 typ srflx raddr 0.0.0.0 rport 0 generation 0 network-cost 999
a=candidate:0 1 udp 2130706431 172.16.21.222 52896 typ host raddr 0.0.0.0 rport 0 generation 0 network-cost 999
a=msid:myKvsVideoStream myAudioTrack
a=ssrc:1678116601 cname:o377k0vWfwcNuLRU
a=ssrc:1678116601 msid:myKvsVideoStream myAudioTrack
a=ssrc:1678116601 mslabel:myKvsVideoStream
a=ssrc:1678116601 label:myAudioTrack
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Lgvo
a=ice-pwd:of16k+l3bqvfH3HUBQuUiKiV
a=ice-options:trickle
a=fingerprint:sha-256 8F:CA:3B:88:0B:C4:62:45:F7:D6:67:CF:2B:90:C0:44:33:A3:09:A7:56:F4:EF:FA:49:DA:7F:1A:E5:DF:7D:D3
a=setup:active
a=mid:0
a=sendonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:8 PCMA/8000
a=rtcp-fb:8 nack
a=rtcp-fb:8 goog-remb
a=rtcp-fb:8 transport-cc
m=video 9 UDP/TLS/RTP/SAVPF 100
c=IN IP4 127.0.0.1
a=candidate:3 1 udp 16777215 0000:0000:0000:0000:0000:0000:0000:0000 0 typ relay raddr ::/0 rport 0 generation 0 network-cost 999
a=candidate:2 1 udp 16777215 0000:0000:0000:0000:0000:0000:0000:0000 0 typ relay raddr ::/0 rport 0 generation 0 network-cost 999
a=candidate:1 1 udp 1694498815 172.16.21.222 51062 typ srflx raddr 0.0.0.0 rport 0 generation 0 network-cost 999
a=candidate:0 1 udp 2130706431 172.16.21.222 52896 typ host raddr 0.0.0.0 rport 0 generation 0 network-cost 999
a=msid:myKvsVideoStream myVideoTrack
a=ssrc:593981998 cname:o377k0vWfwcNuLRU
a=ssrc:593981998 msid:myKvsVideoStream myVideoTrack
a=ssrc:593981998 mslabel:myKvsVideoStream
a=ssrc:593981998 label:myVideoTrack
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Lgvo
a=ice-pwd:of16k+l3bqvfH3HUBQuUiKiV
a=ice-options:trickle
a=fingerprint:sha-256 8F:CA:3B:88:0B:C4:62:45:F7:D6:67:CF:2B:90:C0:44:33:A3:09:A7:56:F4:EF:FA:49:DA:7F:1A:E5:DF:7D:D3
a=setup:active
a=mid:1
a=sendonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:100 H264/90000
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:100 nack
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
", "type": "answer"}

**Describe the bug**
we use android reactnative(kvs with webrtc js sdk) as viewer, pc (kvs with webrtc c sdk) as master,and found that sdp info mismatch,i had change SessionDescription.c as below:

a=group:BUNDLE 0 1 => a=group:BUNDLE audio video
a=mid:0 => a=mid:audio
a=mid:1 => a=mid:video

and it work. so i guess the bug due to c-sdk's media sdp 

**SDK version number**
last pull in 2021.06.29 from master branch

**Comment by hassanctech** [comment]
Can you please use release 1.6.0, we do not recommend using a random commit from master. 

That being said I do not think it will fix your issue.  It looks like there is a mismatch so I suppose on the viewer side if you also changed:

I see the issue here:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/SessionDescription.c#L824

We just write the number, I didn't check if we actually store the string from the remote description.  If you have a patch already please feel free to submit a PR!  Otherwise we look into this I do not have an ETA right now for when this will be fixed.

**Comment by HiconKong** [comment]
yeap. i had modify code where you point out.like following code.
id ==0?“audio”：“video”
it works.but I think it poor compatibility. if you have any good ideas?

Hassan Sahibzada ***@***.***>于2021年8月13日 周五22:44写道：

**Comment by niyatim23** [comment]
Can you please share which browser you are using for the viewer?

**Comment by HiconKong** [comment]
we didn't used browser as viewer. we use android which developed in ReactNative, and it use kvs with webrtc js sdk.

**Comment by niyatim23** [comment]
The PR to fix this bug has been merged hence closing this issue

**Comment by sandeepg1220** [comment]
@niyatim23 Still we are facing this issue. Could you please help on this.

`Possible Unhandled Promise Rejection (id: 0):
Object {
  "message": "Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.",
  "name": "SetRemoteDescriptionFailed",
}
`

Platform Information

React Native Version: 0.67.1
Plugin Version: 106.0.3
OS: iOS - iPhone 14 Pro
OS Version: - iOS 16.1

**Comment by niyatim23** [comment]
Hi @sandeepg1220, this fix is not merged into master so we do not have it as a part of a release yet. It is only available in the `develop` branch of this repository. This will be available in the next release
