### ISSUE TITLE
[FEATURE] Allow usage of system's kvsCommonLws

### ISSUE THREAD

**Issue by ericriff** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1235]
This is a build system feature request.

I'm working on packaging this library with Conan and, according to its guidelines, each library should be packaged independently.

I'm wondering if it could be possible to provide the option of using a prebuilt version of `kvsCommonLws`, just like it is possible for all other dependencies.

The current behavior seems to built it from sources if `BUILD_DEPENDENCIES=TRUE`. Otherwise this library is not available to the build system since it is not being looked for on the system. So I'd expect the build to fail in this case. 

`amazon-kinesis-video-streams-producer-c` (which provides `kvsCommonLws`) recently implemented this for its dependency on `kvspic`. See https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/commit/74d6e8c11d58556276f7027c1fa3b80131f612df

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.
