### ISSUE TITLE
Most of Time Streaming not Start when i start streaming from 4G internet from phone

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1247]
Hi All,

My camera on master mode connected through wifi having enough bandwidth speed and i am start streaming from phone which on 4G internet through SIM module.

Most of time on camera whenever in failure condition when streaming not happen. 
Its showing error log in verbose 

stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_FAILED.
[Uploading kvsFileLog.txt…]()

Please see attached files for same also.
AWS SDK log i save in file

Can we have proper root cause or what is happening in background which cause this issue?

NOTE: Camera always on WIFI network . while we are trying to stream from mobile from $G network.

**Comment by disa6302** [comment]
@shiv50084 , 

We are unable to download the file you attached. 

To clarify: Is your phone camera acting as the master? Or, is your phone the viewer and a camera module the master?

**Comment by shiv50084** [comment]
Ok I will upload it again.

MY camera act as a master while phone act as a viewer
