### ISSUE TITLE
[BUG] Sample is hang when calling signalingClientDeleteSync

### ISSUE THREAD

**Issue by nguyenduynghia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1248]
In sample code of 1.6.0 SDK, I call signalingClientDeleteSync before calling freeSignalingClient and it is hang.
![hang](https://user-images.githubusercontent.com/33972440/131117995-eea6cb17-df9f-4331-916f-a6cc61cf588e.jpg)

Here is my code:
```
retStatus = signalingClientDeleteSync(pSampleConfiguration->signalingClientHandle);
        if (retStatus != STATUS_SUCCESS) {
            printf("[KVS Master] signalingClientDeleteSync(): operation returned status code: 0x%08x", retStatus);
        }

        retStatus = freeSignalingClient(&pSampleConfiguration->signalingClientHandle);
        if (retStatus != STATUS_SUCCESS) {
            printf("[KVS Master] freeSignalingClient(): operation returned status code: 0x%08x", retStatus);
        }
```

**Comment by nguyenduynghia** [comment]
I streamed videos successfully.
After all streaming sessions was disconnected, I delete this channel.
Maybe your unit test is passed. But when integrating to application, it has trouble.

**Comment by MushMal** [comment]
@nguyenduynghia you might want to debug your application further. 

* Does this happen with stock unmodified samples?
* Does this happen on the commodity platforms? (Ex: PC with Linux or Mac)

The tests are designed to simulate a real-life application usage. It is possible that there is a bug but more information is needed to debug

**Comment by nguyenduynghia** [comment]
In sample code, there is no signalingClientDeleteSync function.
What I added are:
- Check if all streaming session are disconnected.
- Signal exit event.
- cal signalingClientDeleteSync before calling freeSignalingClient.
In SDK 1.5.0, I didn't met this issue.
All code are built with Visual Studio in window.

**Comment by nguyenduynghia** [comment]
I found one request that took over 10 minutes.
That cause  listener thread hang.
![longtime](https://user-images.githubusercontent.com/33972440/131502321-2ae85563-9988-469e-b80d-141b105301ec.png)

**Comment by MushMal** [comment]
This is strange. @disa6302 is this a known issue? Can someone please quickly confirm by adding the delete call in the cleanup clause of the master sample and have a trigger to gracefully quick the master (or use ctrl+c).

**Comment by disa6302** [comment]
It is not a known issue. I will look into adding. delete option in the samples and test it out.

**Comment by jdelapla** [comment]
@nguyenduynghia would you mind including the entirety of your changes to the 1.6 sample so that we can attempt to reproduce your issue? It would allow us to debug it ourselves as well.

**Comment by jdelapla** [comment]
I've added the code you mentioned in your initial report to the same sample, and am not experiecing a hang.
`retStatus = signalingClientDeleteSync(pSampleConfiguration->signalingClientHandle);
        if (retStatus != STATUS_SUCCESS) {
            printf("[KVS Master] signalingClientDeleteSync(): operation returned status code: 0x%08x", retStatus);
        }`
If you're still experiencing the issue please re-open the ticket with the entire list of changes made to the sample.
