### ISSUE TITLE
[QUESTION] Is SDP renegiotiation supported

### ISSUE THREAD

**Issue by ela34** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1252]
Looking at the code it seems SDP renegotiation (aka receiving another SDP_OFFER on an already negotiated connection) is not supported. Can you confirm.
If not supported is there any plan to support it ?
Thanks.

**Comment by disa6302** [comment]
@ela34 , 

You are correct. We do not have the support to renegotiate at the moment. We do not have a plan to support it for now. I will mark this with enhancement tag for future enhancement purposes.

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.

**Comment by cwoodhayes** [comment]
This is a dealbreaker for my use-case--is there any status update on being able to renegotiate?
