### ISSUE TITLE
[BUG]Each webRtc-reconnection results in 3 fd leaks，please help confirm，Thanks

### ISSUE THREAD

**Issue by August88618** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1263]
Each webRtc-reconnection results in 3 fd leaks：
Function sessionCleanupWait calls createSignalingClientSync
please help confirm，Thanks
![Call function](https://user-images.githubusercontent.com/88138291/132483143-6df88ac4-69f7-47e3-aef5-1c24d7076224.png)
[Leak comparison.docx](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7127648/Leak.comparison.docx)
[reconnect-log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7127649/reconnect-log.txt)

**Comment by codingspirit** [comment]
This issue might related to lws:

```c
pLwsContext = lws_create_context(&creationInfo);
lws_context_destroy(pLwsContext);
```
User can observe leaked pipe:

before `pLwsContext = lws_create_context(&creationInfo);`:
```bash
ls -l /proc/${PID}/fd
total 0
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 0 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 1 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 2 -> /dev/pts/3
```

after `pLwsContext = lws_create_context(&creationInfo);`:
```bash
ls -l /proc/${PID}/fd
total 0
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 0 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 1 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 2 -> /dev/pts/3
lr-x------ 1 xxxx domain^users 64 Sep  8 06:50 3 -> /dev/urandom
lr-x------ 1 xxxx domain^users 64 Sep  8 06:50 4 -> 'pipe:[2529153]'
l-wx------ 1 xxxx domain^users 64 Sep  8 06:50 5 -> 'pipe:[2529153]'
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 6 -> 'socket:[2529154]'
```

after `lws_context_destroy(pLwsContext);`:
```bash
ls -l /proc/${PID}/fd
total 0
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 0 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 1 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 2 -> /dev/pts/3
l-wx------ 1 xxxx domain^users 64 Sep  8 06:50 5 -> 'pipe:[2529153]'
```

This ` 'pipe:[2529153]'` will persist until we terminated the process.

**Comment by codingspirit** [comment]
Confirmed this issue is related to libwebsockets: https://github.com/warmcat/libwebsockets/issues/2407.
Will rise a PR to fix it.

**Comment by codingspirit** [comment]
Created PR: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1264

**Comment by disa6302** [comment]
Thank you for the PR! Closing this issue.
