### ISSUE TITLE
[QUESTION] Is there a way to have WebRTC SDK C program generate SSLKEYLOGFILE?

### ISSUE THREAD

**Issue by yamasy** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1265]
I need TLS pre master secret key log file that kvsWebrtcClientMasterGstSample generates so that I could decrypt signaling messages over TLS on Wireshark. But even if SSLKEYLOGFILE environment variable is set, this sample program does not generate the log file.
Notes:
- The sample program is working normally and the video from this program is shown by a remote viewer.
- The program was built/ran on a Raspberry Pi by following README.md (cmake .. / make with no option)
- Therefor, the dependent libssl was built internally.

**Comment by disa6302** [comment]
@yamasy ,

We do not have any provision to generate an SSL log file. We will require this callback to achieve that: openssl.org/docs/man1.1.1/man3/SSL_CTX_get_keylog_callback.html

Can you briefly explain what is your use case here? Or, why you would like this functionality?

**Comment by yamasy** [comment]
disa6302, sorry for the late reply.
I understood that there is no functionality for SSL log, so I close this question. 
I am studying feasibility of a system with IoT devices that include WebRTC SDK. I wish I could decrypt TLS messages between the device and Amazon cloud. in order to verify that the SDK interacts with the cloud following WebRTC specification and no unexpected communication is made. And I think it may be helpful if a problem occurs by analyzing communication between the device and the cloud using tcpdump/Wireshark.
