### ISSUE TITLE
Do it fall back to use turn server automatically ?

### ISSUE THREAD

**Issue by ek9852** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#127]
We notice that STATUS createSampleConfiguration(PCHAR channelName, SIGNALING_CHANNEL_ROLE_TYPE roleType, BOOL trickleIce, BOOL useTurn, PSampleConfiguration* ppSampleConfiguration)
It needs to specify useTURN or not. 

Doesn't the sdk SHOULD fall back to use TURN server automatically when p2p between device cannot be reached ? If so, why there is a setting or that .

**Comment by Sean-Der** [comment]
if `useTurn` is true it still tries to do P2P, but then falls back to TURN if P2P fails after a set amount of time. The `useTurn` variable just means we copy the KVS TURN servers into the RtcConfiguration, in some cases users may way want P2P only, so they would set `useTurn` to false.

You can force TURN by setting `iceTransportPolicy` to `ICE_TRANSPORT_POLICY_RELAY` though!

----

Closing for now, but if I missed something please re-open! Thanks @ek9852
