### ISSUE TITLE
[QUESTION] Send message to dataChannel for all pSampleStreamingSession async of received messages.

### ISSUE THREAD

**Issue by ilyaikik** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1275]
I'm trying to achieve the next scenario:
- send the same message to all opened dataChannels from master using `dataChannelSend` async of received messages.

The `SampleConfiguration` structure contains list of active `PSampleStreamingSession`. But I cannot see the way to get to opened `PRtcDataChannel` for `PSampleStreamingSession` from this list.

I open dataChannel for each session.

I could for example use `dataChannelOnOpen` callback to create my own list of `PRtcDataChannel`. But how can I be sure that this pointers still good?
If I open dataChannel for all sessions, would it be ok to create my own map of `PSampleStreamingSession`->`PRtcDataChannel` to use it for sending messages and delete pair from this map when session closing?

Please help me to achieve this functionality!
Thank you!

**Comment by disa6302** [comment]
@ilyaikik , 

You can make any sample changes you want to achieve this. Not sure what you mean by using  `dataChannelOnOpen` to create a list of data channels, but you can create your own mapping of peer connection <-> data channel objects in the sample. 

Do note: we do maintain an internal map of data channels per peer connection object. 

Resolving. Please feel free to reopen or open a new issue if you have any more specific questions.

**Comment by ilyaikik** [comment]
@disa6302 ,

so you say:
> Do note: we do maintain an internal map of data channels per peer connection object.

How can I achieve this map from `SampleConfiguration` struct or somewhere else?

**Comment by ilyaikik** [comment]
So is there a way to achieve all opened dataChannels from `SampleConfiguration` struct?
`SampleConfiguration` holds list of `PSampleStreamingSession` structs.
`PSampleStreamingSession` has `PRtcPeerConnection` struct.
But `PRtcPeerConnection` is just
```
typedef struct {
    UINT32 version; //!< Version of peer connection structure
} RtcPeerConnection, *PRtcPeerConnection;
```
So how to go deep from <RtcPeerConnection> to the dataChannel?

**Comment by ilyaikik** [comment]
ok
I Could do this:
`PKvsPeerConnection pKvsPeerConnection = (PKvsPeerConnection) pRtcPeerConnection;`
and now `PKvsPeerConnection` struct has `PHashTable pDataChannels;` field.
I'm going deeper =)

**Comment by ilyaikik** [comment]
Next
To get `PRtcDataChannel` from `PHashTable pDataChannels` :

```
PKvsDataChannel pKvsDataChannel = NULL;
UINT64 hashValue = 0;
PKvsPeerConnection pKvsPeerConnection = (PKvsPeerConnection) pRtcPeerConnection;
CHK(pRtcPeerConnection != NULL && pRtcDataChannelStats != NULL, STATUS_NULL_ARG);
CHK_STATUS(hashTableGet(pKvsPeerConnection->pDataChannels, pRtcDataChannelStats->dataChannelIdentifier, &hashValue));
pKvsDataChannel = (PKvsDataChannel) hashValue;

PRtcDataChannel* ppRtcDataChannel = NULL;
*ppRtcDataChannel = (PRtcDataChannel) pKvsDataChannel;
```

And now I can use `*ppRtcDataChannel ` for 
`STATUS dataChannelSend(PRtcDataChannel pRtcDataChannel, BOOL isBinary, PBYTE pMessage, UINT32 pMessageLen)`
function to send my message.

But i need to find `pRtcDataChannelStats->dataChannelIdentifier` somewhere.

Still looking...
