### ISSUE TITLE
(BUG) CHK_WARN CHK_ERR should not be inside MUTEX_LOCK

### ISSUE THREAD

**Issue by ek9852** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#128]
There are many case  where CHK_WARN or CHK_ERR or CKH_STATUS are inside a MUTEX_LOCK block, which would skip the mutex unlock when error occurs.

Such as :  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L109 AND  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L114

The CHK_WARN, CHK_ERR just use a goto cleanup when error occurs, and will not unlock the mutex. 

Pls make some test cases and polish the code.

**Comment by chertov** [comment]
but mutex will unlock here https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L70

**Comment by ek9852** [comment]
Not in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L109 AND https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L114

**Comment by Sean-Der** [comment]
Fixed with d633a918a2dd125bb1e0f4d0196056a0e15dac0d
