### ISSUE TITLE
[QUESTION] Can't connect kvsWebrtcClientMasterGstSample 

### ISSUE THREAD

**Issue by NSBSS** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1281]
When I executed ./kvsWebrtcClientMasterGstSample in build/sample/, an error occurred, and I don’t know how to use kvsWebrtcClientMasterGstSample
![image](https://user-images.githubusercontent.com/26132181/135384919-6f300496-a8c4-494a-a37a-bb6ee1b85c70.png)

I don't know how the above error occurred, My purpose is to pass the rtsp stream of the ip camera into kvsWebrtcClientMasterGstSample

**Comment by disa6302** [comment]
What is your viewer equivalent. The sequence is: start master and then start viewer with the same channel name (you can use the JS test page to do this).

**Comment by NSBSS** [comment]
![image](https://user-images.githubusercontent.com/26132181/135578198-5447ef56-83c6-4978-9992-8708739a14ae.png)
the media player viewer，I think this should be the same as the effect of the js page.
thank you for your reply.

**Comment by disa6302** [comment]
@NSBSS ,

the AWS console is another option, yes

Closing this ticket. Please feel free to reopen if you fave any issues
