### ISSUE TITLE
[BUG] Memory leak problem

### ISSUE THREAD

**Issue by shijialin0518** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1282]
My SOC is qualcomm 9531,  toolchain is mips-openwrt-linux-uclibc- . After cross compiling, I put the library generated by SDK into the development board and run the compiled webrtc program to transmit audio and video streams, there will be a memory leak. It is found that the leak occurred when calling the "writeframe( )" function. This function is the interface function provided in the SDK. the webrtc SDK version is 1.5, this problem also occurs on the 1.3 SDK. how do I find the memory leak in the source code

**Comment by disa6302** [comment]
@shijialin0518 ,

There are a lot of tools out there that can help you with this -  valgrind, memwatch, mtrace to name a few.

**Comment by disa6302** [comment]
Closing assuming answered
