### ISSUE TITLE
Audio issues when viewer is using Firefox

### ISSUE THREAD

**Issue by tuncalie** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1287]
We have a device (Jetson Nano) running our streaming solution based on C SDK GstreamerClientMaster sample. We have 1-way video (device to viewer) and 2-way audio communications (OPUS). I repeatedly connected to the stream on same device back to back with Firefox 92.0.1 (64 bit) and Chrome 94.0.4606.71 (x86_64), randomly changing between Chrome and Firefox. In all of my Chrome connections, audio on the device was clear and in all of my Firefox connections, the audio output on the device (audio from viewer to master) was distorted. The audio on the other direction (master to viewer) was clear.

The differences I can see in the logs are (1) Firefox keeps sending bitrate suggestions and Chrome doesn't, (2) Firefox SDP offer has "Found H264 payload type 126 with score 3" but Chrome SDP offer has "Found H264 payload type 102 with score 2" and "Found H264 payload type 125 with score 3".

I am attaching the logs on master side for both connections.

[Okay_chrome_conection.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7281352/Okay_chrome_conection.txt)
[Problematic_firefox_connection.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7281354/Problematic_firefox_connection.txt)

**Comment by tuncalie** [comment]
Another set of logs from similar times. In these logs, the problem seems to be different. Logs keep saying resent of packet succeeded but it seems to keep resending the same packets even though it says "succeeded.".
I can raise this as a different issue if you think that this is independent from the audio issue.

[Stream_problem_resend_packets.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7281491/Stream_problem_resend_packets.txt)

**Comment by tuncalie** [comment]
Before the bot closes this issue, yes this is still happening.

**Comment by disa6302** [comment]
@tuncalie , is this still happening? Are there any other data points the team could use to help with this issue?

**Comment by disa6302** [comment]
Closing due to no response.
