### ISSUE TITLE
[QUESTION] Got build errors "LNK2019: unresolved external symbol" on Windows10 and VS2019

### ISSUE THREAD

**Issue by nshinya** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1288]
I could not build this SDK on Windows10 due to the error described below.

I think this error is related not to KVS C SDK but libwebsockets and pthreads. But I could not find any crew to solve this error from issues of both KVS C SDK/libwebsockets repositories.
How can I solve the error? What prerequisite is short?

I prepared environments referring to README of this SDK and https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-windows.md .

I got pthreads modules from http://mirrors.kernel.org/sourceware/pthreads-win32/, chose pthreads-w32-2-9-1-release.zip .

I'm using Visual Studio 2019 Community. I'm running build commands in X64 Native Tools Command Prompt for VS 2019.

build commands I tried are as below (both had same errors):
`cmake .. -DLWS_HAVE_PTHREAD_H=1 -DLWS_EXT_PTHREAD_INCLUDE_DIR="C:\Program Files (x86)\pthreads\include" -DLWS_EXT_PTHREAD_LIBRARIES="C:\Program Files (x86)\pthreads\lib\x64\libpthreadGC2.a" -DLWS_WITH_MINIMAL_EXAMPLES=1`

`cmake -G "NMake Makefiles" .. -DLWS_HAVE_PTHREAD_H=1 -DLWS_EXT_PTHREAD_INCLUDE_DIR="C:\Program Files (x86)\pthreads\include" -DLWS_EXT_PTHREAD_LIBRARIES="C:\Program Files (x86)\pthreads\lib\x64\libpthreadGC2.a" -DLWS_WITH_MINIMAL_EXAMPLES=1`

** Logging ** 

I got an error as below.

```
Creating library websockets.lib and object websockets.exp
close.c.obj : error LNK2019: unresolved external symbol lws_threadpool_wsi_closing referenced in function __lws_close_free_wsi
ops-pipe.c.obj : error LNK2019: unresolved external symbol lws_threadpool_tsi_context referenced in function rops_handle_POLLIN_pipe
..\bin\websockets.dll : fatal error LNK1120: 2 unresolved externals
```

** Any design considerations/constraints **

I know who wants to use this SDK on Windows10, so I tried to build this SDK on Windows10.

**Comment by yuma-m** [comment]
It looks build for Windows is tested on CI process, but it marked "This job is allowed to fail".
https://app.travis-ci.com/github/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/jobs/537324170

KVS team, Do you expect fail in Windows build? Is Windows not supported on this SDK?

**Comment by pablocordova** [comment]
@nshinya @TristynTorriani did you solve it, I'm trying to build it in windows too and I have the  same error:

```
close.obj : error LNK2019: unresolved external symbol lws_threadpool_wsi_closing referenced in function __lws_close_free_wsi
```

**Comment by vulkan101** [comment]
I also see this same problem on 1.7.2

**Comment by mehmetcy84** [comment]
Has there been any change regarding this issue? I am seeing the same build error with my kinesis SDK configuration on Win64 VS2017 setup. Modified my bat file as:

`call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
mkdir build
cd build
cmd.exe /c cmake -G "NMake Makefiles" ..
cmake -G "NMake Makefiles" -DBUILD_TEST=TRUE -DOPENSSL_ROOT_DIR="E:/vcpkg/installed/x64-windows" -DLWS_HAVE_PTHREAD_H=1 -DLWS_EXT_PTHREAD_INCLUDE_DIR="C:\pthread\include" -DLWS_EXT_PTHREAD_LIBRARIES="C:\pthread\lib\x64\pthreadVC2.lib" -DLWS_WITH_MINIMAL_EXAMPLES=1 ..
nmake`

and receiving the errors:
close.c.obj : error LNK2019: unresolved external symbol lws_threadpool_wsi_closing referenced in function __lws_close_free_wsi
ops-pipe.c.obj : error LNK2019: unresolved external symbol lws_threadpool_tsi_context referenced in function rops_handle_POLLIN_pipe
..\bin\websockets.dll : fatal error LNK1120: 2 unresolved externals

**Comment by mehmetcy84** [comment]
Setting -DLWS_WITH_THREADPOOL=0 (changed from 1 to 0) in 
.\amazon-kinesis-video-streams-webrtc-sdk-c\CMake\Dependencies\libwebsockets-CMakeLists.txt 
and attempting again, the build succeeded. 
Though I am not sure at what cost I managed to build the SDK by disabling the threadpool.

**Comment by mehmetcy84** [comment]
Are there any news regarding this issue?

**Comment by niyatim23** [comment]
Hi, this build has been fixed in the CI. You may have to install gstreamer and strawberryperl to use it. You can refer to the steps for a clean build in the `develop`'s ci.yml
