### ISSUE TITLE
[QUESTION] Use data channel with Master

### ISSUE THREAD

**Issue by wolfviking0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1289]
Hello,

I am using the webrtc sdk for few years now, but I never need to use the data channel, but recently I wanted to do some experiment and I am facing some issue, but I think its a misunderstanding on my side.

I have my code using the master branch (up to date), for my webrtc server. I am using the JS WebRTC page but when I try to enable Open DataChannel I am not able to received the stream anymore with this error from the log:
```
viewer.js:150 Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.
OperationError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate
[2021-10-05T17:33:46.113Z] [ERROR] OperationError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate
```

If I uncheck the data channel checkbox everything goes fine, I have a feeling maybe something doing wrong on the master side.

Do you have any idea suggestion I could try ?

Thanks

**Comment by niyatim23** [comment]
Hi, thank you for your question. The error you are seeing is caused if the `dataChannel` is `NULL`. It seems like you are trying to send a message even before the `dataChannel` is set. I tested our sample Master with the WebRTC JS page and saw no issues while sending messages via the `dataChannel`. I would suggest you to run the Master first and then the Viewer, make sure that a connection between the two is established before sending `dataChannel` messages. Please let us know if the issue persists.

**Comment by wolfviking0** [comment]
Hi, thanks for you response, the trouble was some kind of mismatch with the cmake flag to enable the DATA_CHANNEL.

I am able now to have my Javascript page sending message to my master, for some reason the message from the master are not received from the client, but could be another mistake on my side .

Thanks.
