### ISSUE TITLE
[FEATURE]  How to send FIR/PLI packets to the remote

### ISSUE THREAD

**Issue by conklinsys** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1292]
The docs say there's congestion control support, and there are calls for the callback and to set the callback for picture loss packets (RtcOnPictureLoss) , but is there a matching call to send a PLI to the remote?  Specifically to request a new iframe.

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally
