### ISSUE TITLE
[QUESTION]Why does the system will be stuck for 1 minute when calls method “createSignalingClientSync”

### ISSUE THREAD

**Issue by August88618** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1294]
We're implementing Kinesis webRTC on our camera, but we have found an issue on the connection, when device offline then webRTC will try to reconnect all the time,but after trying for 3 hours and each reconnect will call the method "createSignalingClientSync" and when call the method will stuck in the method for 1 minute, why our call will be stuck in 
the method,has there any logic on Kinesis service to handle the retry cause the stuck? Please help to check, thanks!

[log(API Timeout).txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7319330/log.API.Timeout.txt)
.

**Comment by hassanctech** [comment]
It looks like your network is bad and we're stuck inside libwebsockets for 1 minute it's blocking dns lookup.
