### ISSUE TITLE
[FEATURE] Require few example implementations for Gstreamer webrtc

### ISSUE THREAD

**Issue by sanskar-singh-rajput** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1299]
Currently, all implementations available to use the SDK are here https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-gstreamer-plugin.html#examples-gstreamer-plugin-launch. Unfortunately I was unable to find any implementations to launch the gstreamer in webrtc mode for kinesis video streams. 
Will need a few example implementations to do the same. 

I presume this to be of relevance in this case scenario, https://gstreamer.freedesktop.org/documentation/webrtc/index.html?gi-language=c

**Comment by MushMal** [comment]
Minor suggestion: I was hoping that the demo repository would publish a dual (streaming/WebRTC) sample

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.
