### ISSUE TITLE
[QUESTION]Can i get clientid when i get a message on the datachannel?If can, how to get it?

### ISSUE THREAD

**Issue by yy-arya** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1305]
When master receive a `SIGNALING_MESSAGE_TYPE_OFFER` type of message, It can receive `pReceivedSignalingMessage->signalingMessage.peerClientId`. Soon afterwards， we receive a message on the `onDataChannelMessage` ,  how do we tell which clientid sent the message at this time?

**Comment by niyatim23** [comment]
Hi, thank you for your question. You can typecast the `customData` argument from `onDataChannelMessage` to `PSampleStreamingSession` and access the client ID.
