### ISSUE TITLE
[QUESTION] How to send a message from master to client (dataChannel)

### ISSUE THREAD

**Issue by wolfviking0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1310]
Hi,

I am facing an issue regarding the usage of the data channel, I am able to have a communication between the Viewer and the Master but only in one way.

When the Viewer (Client in javascript) send a message, I am able to received it in my Master (C++), but when I try to send from my Master (C++) a message to my Viewer, I am not receiving anything.

I added my function and I received the log info
```
>> MyStreamer::sendMessage(): COMPLETED - 0x7ff7cc2b0440
```
 so the function its called and I do not received an error message.

```
void MyStreamer::sendMessage(const std::string& message)
{
    Logging::info("MyStreamer::sendMessage(): %s - %p", message.c_str(), _pSampleConfiguration->pRtcDataChannel);
    // Send a response to the message sent by the viewer
    STATUS retStatus = STATUS_SUCCESS;
    if (_pSampleConfiguration->pRtcDataChannel) {
        retStatus = dataChannelSend(_pSampleConfiguration->pRtcDataChannel, FALSE, (PBYTE)message.c_str(), message.size());
        if (retStatus != STATUS_SUCCESS) {
            Logging::error("MyStreamer::sendMessage(): operation returned status code: 0x%08x \n", retStatus);
        }
    }
}
```

Any suggestion or idea of what I am doing wrong ?

Thanks

**Comment by disa6302** [comment]
Closing due to no response.

**Comment by wolfviking0** [comment]
Sorry I did not see there was a comment, just to indicate the issue was in the js page the event in order to receive the channel message from the master was bot set properly.
Thanks

**Comment by wolfviking0** [comment]
Sorry, this is a really old issue, in between since I updated both backend and frontend side and so far the channel communication work smoothly on this side.

**Comment by chenhudl** [comment]
Can you explain which method are you using to allow bidirectional communication?
In-band negotiation (default) or Out-of-band negotiation?
 or do you create two one-way data channels, one from the producer and one from the viewer?
