### ISSUE TITLE
[QUESTION] freePeerConnection is Thread safe ?

### ISSUE THREAD

**Issue by ty-forgit** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1312]
Looking at the source code of the SDK, I was worried about one point.
The comment for freePeerConnection () says * NOT thread-safe.
Is freePeerConnection () a thread-unsafe function?

/*
 * NOT thread-safe
 */
STATUS freePeerConnection(PRtcPeerConnection* ppPeerConnection)
{
    ENTERS();
    STATUS retStatus = STATUS_SUCCESS;
    PKvsPeerConnection pKvsPeerConnection;
    PDoubleListNode pCurNode = NULL;
    UINT64 item = 0;

**Comment by disa6302** [comment]
@ty-forgit ,

`freePeerConnection()` is not thread safe. At the moment, you will have to have a client level lock if multiple threads are going to access the same peer connection object.
