### ISSUE TITLE
[QUESTION] is it possible/doable to port the webrtc C SDK libraries/samples to Windows x86/x64 platform (DLL /EXE) ?

### ISSUE THREAD

**Issue by ajjiang48** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1313]
Hi, Sir,
This is just a quick question; we need to adopt AWS webrtc master or viewer into our Windows application (e.g. the AWS webrtc libraries as DLLs and could be called by our Windows application)  and I'm not sure it's better using C SDK or JS SDK because it looks the JS SDK is only for browser-embedded application, or is there other solution for our requirement ??

Thanks,

**Comment by disa6302** [comment]
This SDK builds for Windows and libraries can also be generated in Windows. You should be able to use the SDK directly. Based on SDK version, you will have to build pthread library separately though following the instructions in the README.
