### ISSUE TITLE
signalingClientSendMessageSync  fails

### ISSUE THREAD

**Issue by obackup** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1322]
1 createSignalingClientSync

2 signalingClientConnectSync

3 signalingClientSendMessageSync

4 signalingClientDisconnectSync

Continue to cycle from step 2 to step 4. After about 5 minutes, signalingclientsendmessagesync fails. At this time, the return value of signalingclientgetcurrentstate is SIGNALING_CLIENT_STATE_CONNECTED, how to solve this problem？

![image](https://user-images.githubusercontent.com/2230621/140911577-2aa360b9-ae30-4124-9e62-6934da33f5f1.png)

**Comment by disa6302** [comment]
Is this an issue you are noticing consistently?
