### ISSUE TITLE
[QUESTION] Documentation or examples about how to stream with WebRTC C SDK

### ISSUE THREAD

**Issue by rafaelRinconFo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1324]
Currently, I've been able to run the `./samples/kvsWebrtcClientMaster myChannel` and see the example in the Amazon console. However, I have not seen any documentation about how to stream a camera with the Web RTC SDK.

From other issues, I have come to understand that it must be done with GStreamer, I am not sure however if this must be done with `kvsWebrtcClientMasterGstSample` or something like that.

I apologize if I have obviated something or ignored some documentation or previously created an issue.

**Comment by disa6302** [comment]
@rafaelRinconFo , 

You are right. You need to use `kvsWebrtcClientMasterGstSample` to stream from camera directly.

**Comment by MushMal** [comment]
KVS SDKs are designed to be generic and independent of the media source. In WebRTC SDK, there are two master samples - the default one that streams pre-packaged frames and the GStreamer based which would use GStreamer pipeline with default camera/encoder. Depending on your device, you could use your own custom media pipeline upstream and feed in the frames into the SDK.

**Comment by rafaelRinconFo** [comment]
Thank you @MushMal , after checking the code in detail I found out the line to set my pipeline. The idea (so far) is to stream my laptop camera or a USB camera but I think I'm missing something because I keep getting the following errors:

`2021-11-11 23:05:59 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
2021-11-11 23:05:59 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
`

I'm taking as an example the line `$ gst-launch-1.0 v4l2src do-timestamp=TRUE device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc  bframes=0 key-int-max=45 bitrate=500 ! video/x-h264,stream-format=avc,alignment=au,profile=baseline ! kvssink stream-name="YourStreamName" storage-size=512 access-key="YourAccessKey" secret-key="YourSecretKey" aws-region="YourAWSRegion"`  included in the [Video streams developer guide](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-gstreamer-plugin.html).

**Comment by MushMal** [comment]
The error you are referencing might be a transient error as the ICE negotiations happen. You should look into the complete log to understand what's going on. There is no information about what's failing and how.

Regarding the kvssink - that's a separate product which is orthogonal to WebRTC. You should attempt to modify the source code for the GStreamer master sample to adapt to your laptop but I would assume it should work as is.

**Comment by rafaelRinconFo** [comment]
Thank you, I just included the kvssink part in order to put the entire line that I'm taking as an example, however, I'm removing everything related to it when creating the pipeline.

Now, this is the entire set of logs, the Errors only start to happen when I access the streaming via the KVS WebRTC Test Page : 

`[KVS GStreamer Master] Using trickleICE by default
[KVS GStreamer Master] Created signaling channel myChannel
[KVS Gstreamer Master] Finished initializing GStreamer
[KVS Gstreamer Master] Streaming video only
[KVS GStreamer Master] streaming type video-only[KVS GStreamer Master] KVS WebRTC initialization completed successfully
[2021/11/11 18:23:55:0033] N: LWS: 4.2.1-v4.2.1, loglevel 7
[2021/11/11 18:23:55:0034] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2021/11/11 18:23:55:0034] N:  ++ [wsi|0|pipe] (1)
[2021/11/11 18:23:55:0034] N:  ++ [vh|0|netlink] (1)
[2021/11/11 18:23:55:0035] N:  ++ [vh|1|default||-1] (2)
[2021/11/11 18:23:55:0039] N:  ++ [wsicli|0|POST/h1/r-0595b96f.kinesisvideo.us-west-2.amazonaws.] (1)
[2021/11/11 18:23:55:9468] N:  -- [wsicli|0|POST/h1/r-0595b96f.kinesisvideo.us-west-2.amazonaws.] (0) 942.878ms
[KVS GStreamer Master] Signaling client created successfully
[2021/11/11 18:23:55:9474] N:  ++ [wsicli|1|WS/h1/m-45f49450.kinesisvideo.us-west-2.amazonaws.co] (1)
[KVS GStreamer Master] Signaling client connection to socket established
[KVS Gstreamer Master] Beginning streaming...check the stream over channel myChannel
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:41 WARN    socketConnectionIsConnected(): socket connection check failed with errno Operation already in progress
2021-11-11 23:24:41 WARN    socketConnectionIsConnected(): socket connection check failed with errno Operation already in progress
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:41 WARN    socketConnectionIsConnected(): socket connection check failed with errno Operation already in progress
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:41 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:43 ERROR   handleRemoteCandidate(): operation returned status code: 0x5a000012
2021-11-11 23:24:43 ERROR   signalingMessageReceived(): operation returned status code: 0x5a000012
2021-11-11 23:24:43 ERROR   receiveLwsMessageWrapper(): operation returned status code: 0x5a000012
2021-11-11 23:24:48 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:48 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:48 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:49 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2021-11-11 23:24:49 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005`

**Comment by MushMal** [comment]
Looks unrelated to GStreamer. Can you build and run the master app? It seems that it's unable to establish the connection for some reason. 

* Try to build the master sample as is with no modification on a commodity platform
* Try to build the GStreamer sample without any modification and run on your laptop
* If any of the above fail, try to get it to run with verbose logging to get more information
* Search in the issues to find a solution that was previously answered by the community

Only after stably running the samples you should proceed with your modifications

**Comment by rafaelRinconFo** [comment]
Hi @MushMal , I have done as you say and this is what happens:

- After rebuilding, the master sample works as expected as you can see in this sample of the `KVS WebRTC Test Page`
![Screenshot 2021-11-12 at 09-53-58 KVS WebRTC Test Page](https://user-images.githubusercontent.com/68308406/141486601-59fd6744-206f-489b-94c4-ae9a49f2205e.png)

- However, the execution of the  `./samples/kvsWebrtcClientMasterGstSample` command gives me the following logs when I try to access the stream: [error_logs_aws_gstream.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7528444/error_logs_aws_gstream.txt)

Just to clarify, I'm trying to access the GStream sample channel from the `KVS WebRTC Test Page` in the same way I do with the `KVS WebRTC Test Page` as I do with the Master sample. I would expect to see in the visualization window the bouncing ball example in the same way I did with the master sample according to the documentation.

**Comment by MushMal** [comment]
This is really odd. From the perspective of WebRTC, there shouldn't be any difference between the master samples. The main difference is the source media pipeline.

Looking at the error log, I can see that the ICE is unable to negotiate the connection which is really bizarre. @disa6302 can you see if you can spot something in the log?

Here is the relevant line in the long I could find:
`2021-11-12 14:50:19 ERROR   handleRemoteCandidate(): operation returned status code: 0x5a000012`

This error is defined as `STATUS_ICE_CANDIDATE_MISSING_CANDIDATE` in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L191


Actually, looking deeper, I see the following:

```
2021-11-12 14:50:17 WARN    turnConnectionAddPeer(): Add peer failed. Max peer count reached
2021-11-12 14:50:17 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x0000000d

```

This is the line https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/c4a13309b6559d19529ca8049a50d4e2b241564f/src/source/Ice/TurnConnection.c#L627

What happens I think is that all of the local and reflexive candidates fail and the only possible connection should be through TURN server which in this case gets dropped.

I am still unsure why this could be the issue if the other master sample works fine. Perhaps a different setup?

Recommend:

* Attempt to run a single viewer session for the test (click on the viewer once)
* Increase the value of DEFAULT_TURN_MAX_PEER_COUNT in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/e90913ed4902dc6e4b492af5424fe40261ee34f4/src/source/Ice/TurnConnection.h#L38 to something larger
* Or, reduce the number of network interfaces on the device

Sorry couldn't be of more help

**Comment by rafaelRinconFo** [comment]
Thank you very much for your support in this thread @MushMal . I must say that after performing the changes you suggested, I obtained no difference sadly, after changing the value of `DEFAULT_TURN_MAX_PEER_COUNT`, there was no difference. 

However, I managed to have some changes. I changed the value in [this line](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/4127014aff98bef86962be5f0c4acf4ba9024de1/samples/kvsWebRTCClientMasterGstreamerSample.c#L377) from False to True in order to see the Test source. I got the following in the WebRTC test page.
![Screenshot from 2021-11-12 15-58-21](https://user-images.githubusercontent.com/68308406/141533668-ef3c8d43-ca07-4b09-b091-70825848c11a.png)


These are the logs obtained in debug mode. Please correct me if I'm wrong, but I don't see any error log [logs_aws_webrtc.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7530383/logs_aws_webrtc.txt)

**Comment by MushMal** [comment]
I think I understand what's going on. It seems that the default GStreamer pipeline that's being created in the GStreamer sample is failing on your platform and the sample itself doesn't somehow release the connection which then ends up with the max connection reached error. 

I hope that @disa6302 or someone from KVS could help with the pipeline but could you set the GStreamers verbose logging to see the output?

Also, I am surprised that things are not getting properly cleaned in the sample.

**Comment by disa6302** [comment]
Hmm. That does not make sense. CleanUp is not GStreamer pipeline specific. It is strange that the test pipeline works but not the default pipeline that reads from the camera. It is also not reproducible. @rafaelRinconFo , what platform are you using to run the sample?

**Comment by rafaelRinconFo** [comment]
@disa6302 I'm running the code on a Ubuntu 18.04 Laptop.

**Comment by rafaelRinconFo** [comment]
Hi @disa6302  and @MushMal . I migrated from Ubuntu 18.04 to Ubuntu 20.04. Still having the same behavior. I don't know if you have any leads on this issue.

**Comment by disa6302** [comment]
On another note: I see IPv6 addresses in your logs. Can you try disabling IPv6 to see if it works?
One way to do this would be: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/4127014aff98bef86962be5f0c4acf4ba9024de1/.travis.yml#L80

**Comment by rafaelRinconFo** [comment]
After attempting with disabling IPv6 with the line you mention, it all happened again. I would like to add that I've tried to replicate this in another Ubuntu PC and it happens exactly the same. 

Just to be sure that there is nothing wrong, I'm making the steps in a similar way to the one indicated in [here](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-c.html), I'm not making any Cross-Compilation or anything similar, as far as I understand, it isn't necessary for executing the examples. 



In addition, these are the logs I've obtained after stepping to Ubuntu 20.04.

1. [The ones obtained with ./samples/kvsWebrtcClientMaster myChannel
](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7557871/logs_master_aws.txt)


2. [The ones obtained with ./samples/kvsWebrtcClientMasterGstSample myChannel
](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7557871/logs_master_aws.txt)

Finally, when I repeat the following as stated before, I'm obtaining the same results:

> However, I managed to have some changes. I changed the value in [this line](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/4127014aff98bef86962be5f0c4acf4ba9024de1/samples/kvsWebRTCClientMasterGstreamerSample.c#L377) from False to True in order to see the Test source. I got the following in the WebRTC test page.
![Screenshot from 2021-11-12 15-58-21](https://user-images.githubusercontent.com/68308406/141533668-ef3c8d43-ca07-4b09-b091-70825848c11a.png)

**Comment by disa6302** [comment]
A question: 
Is your Ubuntu 18.04 an EC2 instance? Do you have a camera source connected to get frames out?

**Comment by rafaelRinconFo** [comment]
Is a physical laptop with several cameras connected. 

I can say now that it finally worked. After attempting several of your suggested solutions, I found curious the fact that the Test pipeline worked and the streaming one didn't. 

I executed a `gst-device-monitor-1.0` and realized that the default Gstreamer pipeline that is set in the code:

```
                    "autovideosrc ! queue ! videoconvert ! video/x-raw,width=1280,height=720,framerate=[30/1,10000000/333333] ! "
                    "x264enc bframes=0 speed-preset=veryfast bitrate=512 byte-stream=TRUE tune=zerolatency ! "
                    "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video"
```
Has very specific configurations i.e: Resolution and framerate. And not every camera supports such specs. My default webcamera for example only supports as follows:

`video/x-raw, format=(string)YUY2, width=(int)160, height=(int)120, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)10/1`

It was never going to work with the default pipeline.


The only camera (at least from the cameras I have) that is able to operate with those specs,  was a RealSense camera with the following GStreamer pipeline:

                   
                   v4l2src device=/dev/video10 ! queue ! videoconvert ! video/x-raw,width=1280,height=720,framerate=[30/1,10000000/333333]!

                    x264enc bframes=0 speed-preset=veryfast bitrate=512 byte-stream=TRUE tune=zerolatency ! 

                    video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video 


I would suggest to include such considerations in the documentation for future cases.

Thank you so much for your help and multiple ideas.

**Comment by disa6302** [comment]
@rafaelRinconFo , 

We have a work item to have documentation on sample GStreamer pipelines. Thank you. Closing now.
