### ISSUE TITLE
[QUESTION] If dataChannelSend () continues to fail, MemFree will continue to decrease.

### ISSUE THREAD

**Issue by pipsnh02** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1327]
If dataChannelSend () continues to fail, MemFree continues to decrease.
Do you have any idea about the phenomenon that MemFree keeps decreasing?
Also, the API response is "0x0000000C",
Is it possible to analyze the causes of these errors?

The environment in which this phenomenon has been confirmed is as follows.

・ P2P communication environment
Local network

・ Communication volume
2Mbps

・ Transmission amount per transmission
25byte ～ 1462byte

**Comment by disa6302** [comment]
@pipsnh02 , 

What do you mean by MEMFREE() continues to decrease?  `0x0000000c` indicates `STATUS_INTERNAL_ERROR`. It is possible you are trying to invoke `createDataChannel()` before signaling is established? There are not a lot of details to work with in this issue. Can you include the following information:

1.  SDK version being used
2. Sample being used
3. Code modifications you might have made for your use case
4. Logs

Additionally, ensure `ENABLE_DATA_CHANNEL` is `ON` [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/4127014aff98bef86962be5f0c4acf4ba9024de1/CMakeLists.txt#L19). It is `ON` by default, but want to make sure you have not disabled the flag.

**Comment by pipsnh02** [comment]
Thank you.
Sorry, I didn't explain MemFree well enough.
MemFree is the value of Free in the Linux system.

The call to createDataChannel() is made in a PC browser (Viewer).
Our device (Master) waits for the data channel to be opened with onDataChannel() and executes dataChannelSend() after the P2P connection is completed.

My scenario is as follows
1. After the P2P connection is completed, the device continues to deliver a stream of about 2Mbps on the DataChannel
   -> At this point, dataChannelSend will succeed. So I believe that the communication is working.
2. After 1 hour, dataChannelSend() fails with STATUS_INTERNAL_ERROR 3. The device does not check for a response to dataChannelSend(), so it continues to deliver the stream

After the STATUS_INTERNAL_ERROR of dataChannelSend() has started, we have confirmed with the Free command that the remaining memory of the system keeps decreasing.

I think dataChannelSend() will return STATUS_INTERNAL_ERROR if usrsctp_sendv() fails.
(But, I cannot determine the failure factor of usrsctp_sendv().)

This leads me to suspect that the usrsctp library may be consuming memory.
For example, is usrsctp_sendv() allocating memory in case of send failure?

My information is
1. SDK version being used
　 -> I am using V1.5.0
2. Sample being used
   -> My program is based on kvsWebRTCClientMaster.c 3. Code modifications you might have made for your use case
   -> The call to dataChannelSend() is not executed at the timing of the call to onDataChannelMessage().
      My program, creates a send thread and calls dataChannelSend() .
4. Logs
   -> Logging is not available, We will try to reproduce this.

**Comment by pipsnh02** [comment]
@disa6302  

Do you know anything from this information?

I'm trying to get the log, but the phenomenon doesn't reappear easily. I will continue to try to reproduce it.

**Comment by hassanctech** [comment]
@pipsnh02 Please try with the latest release 1.6.0.  We updated the versions of libwebsockets, libusrsctp, libsrtp so if the issue was in there it may have already been fixed.  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/releases/tag/v1.6.0

Please update here once you have tried with that version if you continue to see this issue.

**Comment by disa6302** [comment]
No response. Closing. Feel free to reopen if you have more updates.
