### ISSUE TITLE
[QUESTION] recipe for target 'cmTC_f5dc6' failed

### ISSUE THREAD

**Issue by Mlleters** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1332]
I have encountered some problems when I cross-compile this library to my device.

OS: Ubuntu 16.04
cmake version is 3.5.1
arm-linux-gnueabihf-gcc 5.4.0
amazon-kinesis-video-streams-webrtc-sdk-c-1.3.0

**My Command:** 
export CC=arm-linux-gnueabihf-gcc  export CXX=arm-linux-gnueabihf-g++ 
mkdir build && build 
cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32  -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-linux-gnueabihf 

**Getting this error:** 
-- Finished building dependencies.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found OpenSSL: /home/user/webrtc/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libssl.so;/home/user/webrtc/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libcrypto.so (found version "1.1.1g") 
-- Checking for module 'libwebsockets'
--   Found libwebsockets, version 3.2.3
-- Checking for module 'gstreamer-1.0'
--   No package 'gstreamer-1.0' found
gstreamer not found. Will not build gstreamer samples
CMake Error at CMakeLists.txt:233 (list):
  list does not recognize sub-command FILTER

-- Configuring incomplete, errors occurred!
See also "/home/user/webrtc/amazon-kinesis-video-streams-webrtc-sdk-c/build/CMakeFiles/CMakeOutput.log".
See also "/home/user/webrtc/amazon-kinesis-video-streams-webrtc-sdk-c/build/CMakeFiles/CMakeError.log".

[CMakeError.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7607522/CMakeError.log)
[CMakeOutput.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7607523/CMakeOutput.log)

**Comment by hassanctech** [comment]
Can yo please try with CMake 3.6.3?  

We have an arm build that runs with every commit in our CI and it's passing right now, here are the steps:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/.travis.yml#L170-L187

Looks identical except for 1. We're not using the hardfloat and 2. We're using the uclibc destination platform in the libsrtp option.

I checked and our CI is using CMake version 3.12.4.  Might want to try that as well if the above doesn't work.

**Comment by Mlleters** [comment]
yes,I used cmake3.19.2 to compile successfully,thanks
