### ISSUE TITLE
[QUESTION] cv::Mat or IplImage to PBYTE conversion efficiently

### ISSUE THREAD

**Issue by madhu-korada** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1334]
I am using OpenCV-based image data and am able to stream using this library. To convert my IplImage to .h264 I am using avcodec and swscale libraries. I am writing my IplImage to a .h264 formatted file and reading it again using the `readFrameFromDisk` function for every frame I am streaming. This conversion seems expensive on my board which has very little compute. How can I efficiently convert my OpenCV Mat to PBYTE of `readFrameFromDisk` without much difficulty? 
I do not see any questions related to OpenCV in the issues as well. Any help would be appreciated.

**Comment by disa6302** [comment]
@madhu-korada , 

This is beyond the scope of the SDK. I would suggest looking into GStreamer based pipelines for conversion.
