### ISSUE TITLE
[QUESTION] kvsWebRTCMasterGstreamerSample Questions

### ISSUE THREAD

**Issue by RobGries** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1336]
Hello All,

I have a couple of questions regarding the kvsWebRTCMasterGstreamerSample application:

1. What is the lifecycle for the pipeline started in sendGstreamerAudioVideo? 
Is the sendGstreamerAudioVideo pipeline supposed to be started once and stay in the GST_STATE_PLAYING state throughout the application's lifecycle? Should additional pipelines be started after a new session is desired?

2. Should I see the pipeline EOS event occur when stopping the viewer from the [test page](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html)? Currently, I'm only seeing the program enter the onSampleStreamingSessionShutdown when the viewer is stopped but it seems like the pipeline never receives the EOS message. When the EOS message is missed, it seems like I cannot restart the video connection until I forcefully quit the receiveGstreamerAudioVideo application using the `kill <pid_of_kvsWebRTCMasterGstreamerSample>` and restart it.

3. Is it normal for the sample application to not respond to SIGINT when stopping the application via CTRL+C from the terminal?

4. Is the sample application supposed to terminate after the viewer terminates the session from the [test page](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html)? The version I'm using does not do this, but I cannot start another session after stopping the viewer from the [test page](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html).

5. Is the sample application meant to only support the starting of only one session from the [test page](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html)?

6. Can you point me to the most stable and recommended version of the SDK to use when starting a new project that incorporates KVS WebRTC features?

**Comment by disa6302** [comment]
1. What is the lifecycle for the pipeline started in sendGstreamerAudioVideo?
Is the sendGstreamerAudioVideo pipeline supposed to be started once and stay in the GST_STATE_PLAYING state throughout the application's lifecycle? Should additional pipelines be started after a new session is desired?

> The lifecycle of the pipeline is that of the application. And yes, `sendGstreamerAudioVideo` is started once and is expected to be playing for the duration of the application's cycle unless there is something that goes wrong in the media source that might cause the pipeline to fail.

Should I see the pipeline EOS event occur when stopping the viewer from the test page? Currently, I'm only seeing the program enter the onSampleStreamingSessionShutdown when the viewer is stopped but it seems like the pipeline never receives the EOS message. When the EOS message is missed, it seems like I cannot restart the video connection until I forcefully quit the receiveGstreamerAudioVideo application using the kill <pid_of_kvsWebRTCMasterGstreamerSample> and restart it.

> You are correct, it does not look like we hook the EOS signal when viewer shuts down. @hassanctech , can you confirm my understanding is correct?

Is it normal for the sample application to not respond to SIGINT when stopping the application via CTRL+C from the terminal?

> It is not normal for the sample application to not respond to SIGINT. We have not noticed it on our end. But if this is happening, please open a new issue with details - logs, changes in sample application, SDK release being used, etc.

Is the sample application supposed to terminate after the viewer terminates the session from the test page? The version I'm using does not do this, but I cannot start another session after stopping the viewer from the test page.

> The sample application does not terminate on closing the viewer. You can model your application to start a new connection when this happens. Right now, the sample application exits only when SIGINT is received: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/4127014aff98bef86962be5f0c4acf4ba9024de1/samples/Common.c#L1132. You can modify this to exit when the viewer is terminated. When viewer terminates, this is the state that is set: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/4127014aff98bef86962be5f0c4acf4ba9024de1/samples/Common.c#L58. 

Is the sample application meant to only support the starting of only one session from the test page?

> You can have multiple viewers started and every viewer will receive the media from master.

Can you point me to the most stable and recommended version of the SDK to use when starting a new project that incorporates KVS WebRTC features?

> Always use the most recent release version. You can find this under "Releases" in this repository.

**Comment by RobGries** [comment]
Hello @disa6302 

Thank you for your detailed reply, it was quite helpful.

> 
> Is it normal for the sample application to not respond to SIGINT when stopping the application via CTRL+C from the terminal?
> 
> It is not normal for the sample application to not respond to SIGINT. We have not noticed it on our end. But if this is happening, please open a new issue with details - logs, changes in sample application, SDK release being used, etc
I have captured logs and will open a new issue with the requested details.

> Can you point me to the most stable and recommended version of the SDK to use when starting a new project that incorporates KVS WebRTC features?
> 
> Always use the most recent release version. You can find this under "Releases" in this repository.
> 
Thanks for verifying that, I am using the most recent 1.6.0 version from the releases section of this repository.
