### ISSUE TITLE
[QUESTION] Any ideas to feed the video frames to SageMaker endpoint

### ISSUE THREAD

**Issue by cwrx777** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1340]
Due to the lower latency of KVS with WebRTC as compared to KVS, we would like to use KVS WebRTC to stream from an embedded device and at the consumer side, grab video frame (image) and feed into SageMaker endpoint. 
Any SDK available to achieve this?

**Comment by disa6302** [comment]
@cwrx777 , 

WebRTC is a peer to peer comunication. You can have frames being transferred between the peers and then have your custom SageMaker integration to support your usecase.

**Comment by cwrx777** [comment]
@disa6302 
Hi can KVS WebRTC SDK be used to stream raw data /non-video data?

**Comment by disa6302** [comment]
Yes. Data channel can be used for the purpose

**Comment by cwrx777** [comment]
Hi @disa6302 

I tested sending data over data channel from the KVS WebRTC Test page and found out that the max data length is only 64KB per message. Is that limitation of KVS Web RTC service or the SDK? is it possible to increase it? 

Could you give a hint on how to modify the kvsWebRTCClientMaster to send the image frame as raw data using the data channel?
