### ISSUE TITLE
[QUESTION] dns response for turn server  sometimes very slow

### ISSUE THREAD

**Issue by YOSI-yoshidayuji** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1350]
I'm currently having trouble with connection time issues.
Sometimes I found the very big value in the log "time taken to create peer connection x ms".
By tcpdump, DNS response is very slow, sometimes it over 10 second. 

Below is a sample.
No.	Time	Source	Destination	Protocol	Length	Info
186	2021-12-09 11:42:20.831695	192.168.19.104	192.168.19.1	DNS	127	Standard query 0x000d A 54-238-157-139.t-6618366e.kinesisvideo.ap-northeast-1.amazonaws.com
197	2021-12-09 11:42:25.844894	192.168.19.104	192.168.19.1	DNS	127	Standard query 0x000e A 54-238-157-139.t-6618366e.kinesisvideo.ap-northeast-1.amazonaws.com
204	2021-12-09 11:42:30.864628	192.168.19.104	192.168.19.1	DNS	127	Standard query 0x000f A 54-238-157-139.t-6618366e.kinesisvideo.ap-northeast-1.amazonaws.com
205	2021-12-09 11:42:30.919008	192.168.19.1	192.168.19.104	DNS	143	Standard query response 0x000f A 54-238-157-139.t-6618366e.kinesisvideo.ap-northeast-1.amazonaws.com A 54.238.157.139
206	2021-12-09 11:42:30.921605	192.168.19.104	192.168.19.1	DNS	127	Standard query 0x0010 A 54-238-157-139.t-6618366e.kinesisvideo.ap-northeast-1.amazonaws.com
207	2021-12-09 11:42:31.008335	192.168.19.1	192.168.19.104	DNS	143	Standard query response 0x0010 A 54-238-157-139.t-6618366e.kinesisvideo.ap-northeast-1.amazonaws.com A 54.238.157.139
208	2021-12-09 11:42:31.011288	192.168.19.104	192.168.19.1	DNS	127	Standard query 0x0011 A 54-238-157-139.t-6618366e.kinesisvideo.ap-northeast-1.amazonaws.com
209	2021-12-09 11:42:31.055996	192.168.19.1	192.168.19.104	DNS	143	Standard query response 0x0011 A 54-238-157-139.t-6618366e.kinesisvideo.ap-northeast-1.amazonaws.com A 54.238.157.139

If server name start with "111-222-333-444", IP address of server is "111.222.333.444" isn't it ?

If that's the truth, I think you can omit the DNS reference. There may be a problem with IPv6 support.
But, if that's the truth, I want to patch for my local SDK.

**Comment by disa6302** [comment]
@YOSI-yoshidayuji , 

It is the IP address. We do not support IPv6. Ensure to disable IPv6 in your set up. Another way to go about this is to use the network interface filter function to gather candidates from specific interfaces only. You can check this for reference: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/4127014aff98bef86962be5f0c4acf4ba9024de1/samples/Common.c#L282

**Comment by YOSI-yoshidayuji** [comment]
Thanks, I will write a patch for my project.
