### ISSUE TITLE
[QUESTION]  How to fetch live stream from particular sdk

### ISSUE THREAD

**Issue by yogii786** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1353]
currently  I want to use webrtc sdk -c for live streaming from raspberry pi how can I be able to fetch live streaming ?

also getting error 
2021-12-09 11:42:40 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005

**Comment by disa6302** [comment]
@yogii786 , 

Not sure what you mean. WebRTC is a peer a peer to communication methodology. There is a master and a viewer. Each of the peer can listen in on the packets send by the other. If you would like to see what the master sends, you can use the AWS console or the test page: https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html. 

If you would like custom integrations, you can have a viewer run on another device/platform that would listen on the packets (something similar to https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/4127014aff98bef86962be5f0c4acf4ba9024de1/samples/kvsWebRTCClientMaster.c#L346) and have your custom integration to view the media. 

About the error, please attach logs and other details such as set up, version of SDK being used and potential changes in the sample made. You have not provided any information for the team to work with.

**Comment by yogii786** [comment]
how will I be able to use this live stream for computer vision prediction application which is deployed in AWS. or simply how can i get this endpoint URL of live streaming video so that I can use that for my video processing application. or I have to use other platform . can you suggest me as soon as possible ?

**Comment by disa6302** [comment]
@yogii786 , 

WebRTC will not help you with this. As mentioned it is a P2P communication protocol. I believe you are looking for something like https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetHLSStreamingSessionURL.html. You will have to look into our producer SDKs (https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp) to serve your purpose. The streams can then be retrieved using our parser library: https://github.com/aws/amazon-kinesis-video-streams-parser-library. 

Closing assuming question is answered. Feel free to reopen or create a new issue if you have any more questions.

**Comment by yogii786** [comment]
Yes agreed but is there any way so we can check or retrieved the stored frames same as viewer does
