### ISSUE TITLE
[BUG] kvsWebrtcClientMasterGstSample stops responding and blocks upon SIGINT (CTRL+C) on SDK v1.6.0

### ISSUE THREAD

**Issue by RobGries** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1355]
As per @disa6302's request, I am opening a new ticket to track a potential bug that I have found in the kvsWebrtcClientMasterGstSample SDK sample application that appears to block a clean exit of the application upon SIGINT (CTRL+C).

I am using v1.6.0 of the amazon-kinesis-video-streams-webrtc C SDK and have made the following modifications to the sample program:
- Rewrote GStreamer pipeline to encode audio and video from our platform.
```
pipeline = gst_parse_launch("rtspsrc location=rtsp://127.0.0.1:8554/stream01 short-header=TRUE latency=0 ! rtph264depay ! "
"video/x-h264, stream-format=byte-stream, alignment=au, profile=high ! appsink sync=TRUE emit-signals=TRUE wait-on-eos=FALSE drop=TRUE name=appsink-video "
"pulsesrc ! audio/x-raw, format=S16LE, channels=2, rate=48000 ! queue ! opusenc ! "
"audio/x-opus,rate=48000,channels=2 ! appsink sync=TRUE emit-signals=TRUE wait-on-eos=FALSE drop=TRUE name=appsink-audio",
&error);
```
- Hard code `pSampleConfiguration->mediaType = SAMPLE_STREAMING_AUDIO_VIDEO`, so I don't need to specify this option on the command line.
`pSampleConfiguration->mediaType = SAMPLE_STREAMING_AUDIO_VIDEO;`

I have logs available from a test run in a github gist: https://gist.github.com/RobGries/2c347a64c23ccc6af2fe1639d94c51c6

One thing that I saw that helps the application exit without stalling is to comment out the following line of code in kvsWebrtcClientMasterGstSample.c within the `CleanUp` label of the main function:
`THREAD_JOIN(pSampleConfiguration->mediaSenderTid, NULL);`

Perhaps one of the threads that should be terminated at that point is blocking the clean exit of the program? I don't believe that just removing the `THREAD_JOIN` line is a proper fix since there is a chance that whatever is spinning on that method wouldn't be cleaned up properly by just not joining the mediaSender thread?

**Comment by RobGries** [comment]
@disa6302 Was your team able to reproduce the issue? Are there any updates to share about it?
If you or your team needs any further information, please feel free to reach out.

**Comment by disa6302** [comment]
Have you had any success with v1.7.0?
