### ISSUE TITLE
[QUESTION] Is there a limit on the amount of data in datachannel at webrtc? 

### ISSUE THREAD

**Issue by LastHe** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1357]
I want to transmit audio and video inside datachennel, 20 frames per second, and the size of each frame is between 100-10000kb, but there will always be disconnection. Is there a limit on the amount of data in datachannel? Is it disconnected for another reason

**Comment by disa6302** [comment]
@LastHe ,

IIRC, the limit is 256kb. This limit comes from the usrsctp library our SDK depends on. However, it is configurable (We do not have the provision to set it from the application). We would still need verbose logs to investigate what could be going on
