### ISSUE TITLE
Unable to change framerate in Gstreamer Pipeline

### ISSUE THREAD

**Issue by utsavrai** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1358]
**Logging**
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

**Describe the bug**
Unable to stream video when adding framerate argument to gst pipeline, for instance-
This works fine
```
pipeline = gst_parse_launch(
                    "v4l2src device=/dev/video4 ! queue ! videoconvert ! video/x-raw,width=2560,height=720 ! "
                        "x264enc bframes=0 speed-preset=veryfast bitrate=3000 byte-stream=TRUE tune=zerolatency ! "
                        "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video",
                    &error); 
```
but when the framerate argument is added to the pipeline, the master is unable to stream the video
**The below pipeline doesn't work**
```
pipeline = gst_parse_launch(
                    "v4l2src device=/dev/video4 ! queue ! videoconvert ! video/x-raw,width=2560,height=720,framerate=30/1 ! "
                        "x264enc bframes=0 speed-preset=veryfast bitrate=3000 byte-stream=TRUE tune=zerolatency ! "
                        "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video",
                    &error);
```
I get following error for adding framerate to pipeline

./samples/kvsWebrtcClientMasterGstSample mychannel video-only testsrc
[KVS GStreamer Master] Using trickleICE by default
[KVS GStreamer Master] Created signaling channel mychannel
[KVS Gstreamer Master] Finished initializing GStreamer
[KVS Gstreamer Master] Streaming video only
[KVS GStreamer Master] Using test source in GStreamer
[KVS GStreamer Master] streaming type video-only
[KVS GStreamer Master] KVS WebRTC initialization completed successfully
[2021/12/19 16:39:14:7424] N: LWS: 4.2.1-v4.2.1, loglevel 7
[2021/12/19 16:39:14:7424] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2021/12/19 16:39:14:7424] N:  ++ [wsi|0|pipe] (1)
[2021/12/19 16:39:14:7425] N:  ++ [vh|0|netlink] (1)
[2021/12/19 16:39:14:7425] N:  ++ [vh|1|default||-1] (2)
[2021/12/19 16:39:14:7429] N:  ++ [wsicli|0|POST/h1/r-2168f5b4.kinesisvideo.ap-south-1.amazonaws] (1)
[2021/12/19 16:39:15:0130] N:  -- [wsicli|0|POST/h1/r-2168f5b4.kinesisvideo.ap-south-1.amazonaws] (0) 270.151ms
[KVS GStreamer Master] Signaling client created successfully
[2021/12/19 16:39:15:0136] N:  ++ [wsicli|1|WS/h1/m-3bffc0cd.kinesisvideo.ap-south-1.amazonaws.c] (1)
[KVS GStreamer Master] Signaling client connection to socket established
[KVS Gstreamer Master] Beginning streaming...check the stream over channel mychannel
2021-12-19 11:09:21 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000003
2021-12-19 11:09:21 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000003

**Comment by niyatim23** [comment]
Have you tried if the WebRTC Gstreamer sample [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L145-L182) works for you?

**Comment by hassanctech** [comment]
The error code `0x5a000003` means `STATUS_ICE_CANDIDATE_STRING_MISSING_IP`

During the ice candidate gathering stage there may be many ice candidates that get rejected but only 1 is needed to make it work.  In any case we are in the processing of putting together a new release, can you please try with this one:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/release_1_7_0

And us know if it works better?

**Comment by hassanctech** [comment]
@utsavrai any updates?

**Comment by utsavrai** [comment]
Yes, I tried the same pipeline with a different camera (Intel Realsense D415) and it worked perfectly. I was able to change the framerate which I confirmed by checking logs from chrome:webrtc-internals. However, for a particular camera like ZED mini, I was unable to set the framerate below the maximum allowed framerate for any resolution. I am checking with the developer team of ZED for the same. I would like to thank you for your responses. I am closing this issue and stating it as resolved.

**Comment by utsavrai** [comment]
> Have you tried if the WebRTC Gstreamer sample [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L145-L182) works for you?

Yes, it is working for a different camera, I was trying with ZED mini camera which has Nvidia driver dependency due to which I was unable to set its framerate to my desired value (my guess). I am checking with ZED developer team and gstreamer as well.
