### ISSUE TITLE
Getting error while publishing the image with error code 0x5c000003 [version 1.6.0]

### ISSUE THREAD

**Issue by madhu-korada** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1361]
I am trying to convert my OpenCV Mat to GstBuffer and then use the buffer to write the frame, But I am facing issues while trying to publish the image. 
```
2021-12-31 13:36:25 ERROR   writeFrame(): operation returned status code: 0x5c000003
```

The way I am converting my CV Mat to GstBuffer is the following, `cvFrame` is my cv Mat and `cvPtr` is my pointer of `cvFrame`
```c++
cv::Mat cvFrame; // This contains data
cv::Mat *cvPtr = &cvFrame;
GstBuffer *buffer = gst_buffer_new_wrapped_full( (GstMemoryFlags)0,
    		(gpointer)(cvFrame.data), size, 0, size, cvPtr,(GDestroyNotify) buffer_destroy);
```
I was able to convert the Mat to GstBuffer* without any issues, I verified it by writing it into a local file. 

```
Mat matLeft(cv::Size(width, height), CV_8UC3, (char*)info.data, cv::Mat::AUTO_STEP);
imwrite("./op.jpg",matLeft);
```
From `kvsWebRTCClientMasterGstreamerSample.c` file I used the `gst_buffer_map` to convert the GstBuffer to PBYTE, 

```
if (!(gst_buffer_map(buffer, &info, GST_MAP_READ))) {
    printf("[KVS GStreamer Master] on_new_sample(): Gst buffer mapping failed\n");
    goto CleanUp;
}

frame.size = (UINT32) info.size;
frame.frameData = (PBYTE) info.data;
frame.presentationTs += SAMPLE_VIDEO_FRAME_DURATION; //for timestamp
```
I am using the same code from `kvsWebRTCClientMasterGstreamerSample.c` to publish my images. 
```
status = writeFrame(pRtcRtpTransceiver, &frame);
```
This func is failing with the above error.

**Comment by madhu-korada** [comment]
With `kvsWebRTCClientMasterGstreamerSample.c` file I printed the `frame.size` which is approximately 2000 and it changes every frame, but with my current GstBuffer, it is fixed `1228800` for all frames.  Why does the frame size changes when the  `kvsWebRTCClientMasterGstreamerSample` is capturing the camera image? In my case, I am using a video, so I am guessing it should be constant?

**Comment by madhu-korada** [comment]
As said in issue #669, my data might not be Annex B. But How do I verify if my data is Annex B? If my data is not Annex B what can I do to make it Annex B?

**Comment by disa6302** [comment]
What is the format of your frames? Our SDK allows only H.264 and VP8 video codec and Opus, A-Law and u-law audio codecs.
