### ISSUE TITLE
[QUESTION] Code pointer to KvsRetryStrategyCallbacks

### ISSUE THREAD

**Issue by KittyLiou** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1363]
I noticed that `KvsRetryStrategyCallbacks` was introduced into `src/source/Signaling/Signaling.h` and `src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h` recently but I couldn't find its definition anywhere.
Could someone give me some code pointers? Thanks.

**Comment by niyatim23** [comment]
Hi, thank you for your question. The definition for this is in the KVS PIC Repository which is one of the dependencies for the KVS WebRTC SDK. It can be found [here](https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/9f0e8c1bf16525dd3628642f1de2695d8f07ec01/src/utils/include/com/amazonaws/kinesis/video/utils/Include.h#L1537). Please let us know in case of any further questions.
