### ISSUE TITLE
How to convert status result code to string?

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1366]
Is there a way to convert the status values to strings? E.g. the `kinesis/video/CommonDefs.h` contains some of the `#define STATUS_*` and it would be great to be able to convert those to a readable representation.

**Comment by disa6302** [comment]
THe SDK has a python script to do this: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/scripts/parse_status.py

There is not a way to convert status codes to strings in the  log messages itself.

Closing assuming answered. Feel free to reopen if you have further questions.

**Comment by roxlu** [comment]
Thanks @disa6302!
