### ISSUE TITLE
[QUESTION] trackId and streamId not used? 

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1368]
Are the `strreamId` and `trackId` that are passed into `addTransceiver()` (via the `RtcMediaStreamTrack.{streamId, trackId}`) not used? 

I see that in [Common.c](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L488) both values are set which makes me think I'm missing something or maybe they are indeed not used. 

If they're not used/set what is their purpose?

**Comment by niyatim23** [comment]
Hi, thank you for your question. The `streamId` and `trackId` are used to set msid, mslabel, and label in SDP. You can see the SDPs in terminal with `export DEBUG_LOG_SDP=TRUE`

**Comment by disa6302** [comment]
Closing assuming question answered. Feel free to reopen if you have more questions.
