### ISSUE TITLE
[QUESTION] Reopening issue 

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1371]
Hi @disa6302, you asked me to reopen this issue if I had more questions https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1369 but I can't reopen it. I think I need to get the correct permissions to reopen an issue. I've posted my follow-up question in issue #1369

**Comment by disa6302** [comment]
Closing since I reopened the original issue. Let me know if you have further questions.
