### ISSUE TITLE
Camera video (H264 - High profile) not working(frames dropped) with Chrome (Ffmpeg decoder)

### ISSUE THREAD

**Issue by kirubhas** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1373]
I'm trying to stream H264 video captured from camera using kvsWebrtcClientMaster sample application.
Sample application works fine with sample frames provided. But there lots of frame drops when I stream my camera frames. 
Only difference I see is the camera frames are encoded in "High" profile and sample h264 frames are Baseline profile.

What could be wrong in this case? I don't see any errors on both Master side logs as well as chrome browser end(webrtc-internals). Frames are just silently dropped by the browser.

Note: video from the same camera is working fine with another webrtc application using PION is streaming without any frame loss.

I tried comparing the packetization implementation between PION and kinesis-video-streams-webrtc-sdk-c and they both looks similar.

Can someone suggest what else I can check to find the root cause of this problem?

1. **Sample frames** 
Chrome(With HW acceleration enabled) - Working
Chrome(With SW decoder - Ffmpeg) - Working

2. **Camera frames**
Chrome(With HW acceleration enabled) - Working  - frame drops at equal intervals
Chrome(With SW decoder - Ffmpeg) - Not Working - all the frames are dropped

** Logging ** 
Add relevent SDK logging. IMPORTANT NOTE: Please make sure to NOT share AWS access credentials under any circumstance! Please make sure they are not in the logs.
1.
![ExternalDecoder](https://user-images.githubusercontent.com/49689274/150102486-9a22c490-797a-4a4a-9171-817037d56ed3.PNG)
2.
![image](https://user-images.githubusercontent.com/49689274/150102388-ae3742b6-4a86-491b-8ce2-0d6954d03518.png)

**Comment by disa6302** [comment]
@kirubhas , 

We are only supporting baseline profile today (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1373). We do not support high or main profiles.

**Comment by kirubhas** [comment]
@disa6302 , Can you please give more details? 
I'm using kinesis signalling channel to stream video from my camera to remote network. Camera sends h264(high) encoded video and the remote end(chrome browser) receives and decodes the video.
With HW acceleration setting enabled in the browser system settings, video is decoded but with lots of frame drops.
The Ffmpeg decoder in the chrome browser doesn't decode the video.

What do you mean high or main profiles are not supported? Do you mean amazon-kinesis-video-streams-webrtc-sdk-c does n't support streaming these profiles? Apologies if my query is not clear enough.

**Comment by disa6302** [comment]
Yes. When I say high or main profiles are not supported, I mean our SDK does not have support for these profiles. We only support baseline at the moment. So that is probably why you see a lot of frame drops. 

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/22c9e3d7932365f0d04181b339f17e4870036f5c/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L726.

**Comment by kirubhas** [comment]
@disa6302 , 
I've configured my camera to stream Baseline profile and the result is same as I mentioned in my first comment (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1373#issue-1107866981)

Would you please suggest how can I debug the reason for frame drops in browser end?  
Thanks.

**Comment by disa6302** [comment]
@kirubhas , 

Can you add VERBOSE SDK logs? Thanks.

**Comment by kirubhas** [comment]
[kvsmaster.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/7907783/kvsmaster.txt)

Please find the sdk logs with VERBOSE. Pls note, I've added few logs in createPayloadFromNalu() for my understanding.
Yes. I've tested with PION with same frames.

**Comment by disa6302** [comment]
Hmm. Not sure what could be happening. From your logs, I see 2 instances of frame drops and that should not impact your video quality. It could happen due to occasional network drops. How is your video quality?

**Comment by kirubhas** [comment]
@disa6302, I don't see any video in the chrome browser, if HW acceleration is disabled. With HW acceleration enabled, video freezing for a moment every 4seconds.

**Comment by disa6302** [comment]
@kirubhas ,

Can you check for any network issues? Another suggestion would be to compare the contents/format of our sample H.264 frames and the ones you are generating.

**Comment by kirubhas** [comment]
@disa6302 , There are no network issues. But I compared the contents/format of SDK H264 frame samples with my generated frames and found there are differences. I would study the differences and let you know.

**Comment by disa6302** [comment]
I am closing this @kirubhas. Do feel free to reach out when you have some more information.
