### ISSUE TITLE
[QUESTION] Why isn't the GStreamer example using `GstBuffer::duration` but a #define value for PTS/DTS?

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1375]
Why don't we use `buffer->duration` to increment the audio and video frame pts/dts values? 

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L78

**Comment by niyatim23** [comment]
Hi, thank you for your question. We cannot use a "duration" instead of a "timestamp". As per the [KVS documentation](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-data.html), these are timestamps that are frame specific elements. 

Closing assuming answered, feel free to reopen in case of any further questions

**Comment by roxlu** [comment]
Thanks for your reply, @niyatim23.  In the linked code you are already accumulating a duration:

`pSampleStreamingSession->videoTimestamp += SAMPLE_VIDEO_FRAME_DURATION;`

My question was why use a hardcoded `#define` and not the value which is provided by GStreamer? 

Can you explain how I can reopen an issue? Do you mean I should create a new issue as I don't have permissions to reopen an issue that was closed by someone else.

**Comment by niyatim23** [comment]
Hi @roxlu, you can use `GstBuffe::duration` if you like, there is no specific reason for using `SAMPLE_VIDEO_FRAME_DURATION` except to depict a 30 fps frame rate which we use across all our samples in our SDKs. 

Reopening the issue for you, let us know in case of any further questions

**Comment by rayrapetyan** [comment]
Btw,
```
#define DEFAULT_FPS_VALUE                        25
```
not 30. A minor mistake in comment here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/22c9e3d7932365f0d04181b339f17e4870036f5c/samples/kvsWebRTCClientMasterGstreamerSample.c#L78

**Comment by roxlu** [comment]
Hi @niyatim23 thanks for your reply. I wasn't sure if there maybe was some other reason I wasn't aware off.
