### ISSUE TITLE
[FEATURE] Add dataChannelOnClose

### ISSUE THREAD

**Issue by kev-the-dev** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1376]
**Is your feature request related to a problem? Please describe.**
In my application, I'd like to quickly discover if the remote peer has closed the connection. Waiting for the 30 second timeout is too slow for my application. I have found a approach to this in webrtc is to create a data channel "keepalive" (or use one already created for the connection), and register the "on close" event. The code on both sides agree that if this data channel is closed, the entire connection is considered closed and should immediately attempt to re-connect (for example, following a server restart).

**Describe the solution you'd like**
Implement a callback to be registered `dataChannelOnClose` as part of the [webrtc spec data channel close event](https://www.w3.org/TR/webrtc/#dom-rtcdatachannel-onclose). When the Sctp fin message arrives (or however data channel closure is indiciated), call this user-registered callback

**Describe alternatives you've considered**
* Continuously send messages on a data channel. If it returns an error, we know the data channel is closed. This could work, but the discovery period is limited to the rate you send messages, requires this manual polling, and uses unnecessary data

**Additional context**

dataChannelOnError would be cool too!

If I could get a bit of coaching for where to look, I'd be happy to work on implementing this myself

**Comment by niyatim23** [comment]
Hi, thank you for bringing this to our notice. Closing this request here since it is already being tracked internally as a part of this ticket: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/823. Feel free to reopen in case of any further questions/issues
