### ISSUE TITLE
[QUESTION] Why are using pointers using uint64_t instead of void*?

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1384]
I noticed that the sdk uses uint64_t instead of void*. 

Almost all other libraries I've used with use `void*` and I'm curious why this SDK uses `uint64_t` instead? 

Thanks!

**Comment by MushMal** [comment]
If I were to guess, you must be referring to the custom data parameters in the callbacks. Using void* is not the best option in this case as the custom data might not necessarily be a pointer and void* has variable size on 32 and 64 bit platforms.

**Comment by roxlu** [comment]
Rereading my question ... I could have explained better what I meant .  But you are exactly right @MushMal, I was referring to user pointers for callbacks. 

When using uint64_t instead of a void* it means that I can pass other values then a pointer. I'm curious why this is so uncommon? I see why using a uint64_t might be usefull. But then you would most likely use the uint64_t as an index which means you need a global to retrieve the pointer and in those situations a void* would be better regardless if it's 32 or 64 bit, no?

Thanks!
