### ISSUE TITLE
[QUESTION] How a peer will know its offer has been rejected

### ISSUE THREAD

**Issue by H-Tomoki** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1386]
In my system, I want the master to check the `clientId` of viewers and reject all offers except those from the viewer with a specific `clientId`. Is there any way for the viewer to detect that the offer has been rejected by the master?
 
For example, in the sample below, there is a process to ignore the offer if a master session with the same `clientId` is already in progress.
 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/22c9e3d7932365f0d04181b339f17e4870036f5c/samples/Common.c#L1253
 
However, the peer that sent the offer will not be able to detect that it has been ignored, so it will have to wait for the process to time out.
Can the peer that receives an offer explicitly reject it and the peer that sent the offer detect it?

I considered using  `SIGNALING_MESSAGE_TYPE_GO_AWAY` for signaling messages, but it appears to be disabled by the SDK.

**Comment by disa6302** [comment]
@H-Tomoki , 

This is more WebRTC specific than KVS specific, but, there are a couple of ways the viewer can be notified, have not tried these methods:
1. Try not adding the transceiver in the answer SDP. The viewer can then be modelled to handle the case where a transceiver is not set in the answer. If using browser, the answer is rejected in itself if the m lines in the SDP does not match the offer SDP with an error similar to..."m lines are not matching ...".
2. You can set an appropriate timeout on the viewer end within which it needs to receive the answer and if it does receive it in the time, it can be assumed the offer was rejected. The drawback in this case is, if there are any network issues, it would be difficult to pin point the issue.

About `SIGNALING_MESSAGE_TYPE_GO_AWAY`:  we do not support sending this message type. We only support receiving this at the moment.

**Comment by H-Tomoki** [comment]
@disa6302 

Thank you for your reply.
I'm sorry for my lack of explanation, but in my use case, I will only use data channels.
Therefore, I cannot use the method of not adding a transceiver.
Also, in my system, both the master and viewer use the KVS WebRTC SDK embedded.

According to [RFC3264](https://datatracker.ietf.org/doc/html/rfc3264#section-6), the following method should be used to reject an offer.

> "To reject an offered stream, the port number in the corresponding stream in the answer MUST be set to zero."

So, in my interpretation, offers are rejected by setting the m line as follows.
`m=application 0 UDP/DTLS/SCTP webrtc-datachannel`

However, I did not find an option to create such an answer using the SDK.
Also, when I rewrote the SDP by myself without using the SDK and sent it to the peer, the peer connection was established.
Is the above method not supported by the SDK for both offerers and answerers?
Do you have any other ideas for in my use case?

**Comment by H-Tomoki** [comment]
@disa6302 
Thank you for adding the enhancement tag.
I'm hoping that this enhancement will be implemented.
