### ISSUE TITLE
[QUESTION] When trying to open many connections WebSocket connection fails.

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1387]
I'm trying to stress test the KVS WebRtc SDK implementation I've created but when opening and closing many  (~40) connections quikcly the WebSocket server connection fails. 

```
WebSocket connection to 'wss://[REMOVED].kinesisvideo.eu-west-1.amazonaws.com/?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-ChannelARN=[REMOVED]&X-Amz-ClientId=[REMOVED]&X-Amz-Credential=[REOMVED]&X-Amz-Date=20220203T153403Z&X-Amz-Expires=299&X-Amz-Signature=[REMOVED]&X-Amz-SignedHeaders=host' 

failed: 
(anonymous) @ SignalingClient.ts:140
step @ tslib.es6.js:100
(anonymous) @ tslib.es6.js:81
fulfilled @ tslib.es6.js:71
```

I'm not getting an error message, just that the connectioned failed.

Any thoughts why I can't create many connections?
Is the signaling server crashing maybe?

**Comment by disa6302** [comment]
@roxlu ,

Can you attach logs? The ticket does not have any information to go with. How are you modeling this test? How often are the connections getting created - is it all done at once?

**Comment by disa6302** [comment]
@roxlu ,

We do have a soft limit of 10 on the maximum number of viewer connections. Check this: https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-limits.html

**Comment by disa6302** [comment]
Closing assuming question answered. Feel free to reach out if you have any more questions.

**Comment by roxlu** [comment]
Thanks @disa6302, that must have been the issue.
