### ISSUE TITLE
Is there support for the ontrack even in the c++ sdk?

### ISSUE THREAD

**Issue by olegomano** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1388]
Hello, I am running the c++ webrtc sdk on an embedded device and would like to receive video from a web browser. The web browser can dynamically add video tracks. In the javascript webrtc api there is an `ontrack` event that notifies you when a new video track is added by the remote peer. Does a similar callback exist in the c++ sdk? I have so far only found `peerConnectionOnDataChannel`, is there a `peerConnectionOnTrack` ?

**Comment by disa6302** [comment]
@olegomano ,

We do not support onTrack() handler.

**Comment by olegomano** [comment]
If I needed to implement the functionality, would the right approach be parsing the SDP offer/reply the web browser sends, and using it to create transceivers?

**Comment by disa6302** [comment]
So the entire process of parsing the SDP and creating transceivers is something we already do within the SDK. What it is that you are trying to achieve?

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/22c9e3d7932365f0d04181b339f17e4870036f5c/src/source/PeerConnection/SessionDescription.c#L731

**Comment by olegomano** [comment]
So a web browser will dynamically add/remove video tracks based on some user interaction with the UI. I would like to read the h264 frames coming from these tracks on the embedded device. I guess my question is how do I get access to the transceivers that the remote peer adds in the c sdk. In the javascript sdk this is done with the ontrack handler.

**Comment by olegomano** [comment]
@disa6302 I read the code you linked, and it doesn't seem to create any transceivers. It seems to iterate over the already existing transceivers and populate them with the required info based on the SDP. Right now when the web browser adds the new video track on its end, I get a lot of 
`2022-02-08 01:21:23 WARN    sendPacketToRtpReceiver(): No transceiver to handle inbound ssrc 3184874503
`
happening on the embedded device side

**Comment by olegomano** [comment]
So I am able to get rid of that warning if I manually add a transceiver before setting the remote description that the web browser sends me. The problem is I need to know that the transceiver will exist. It would be ideal if there was a way to dynamically figure that out.

**Comment by disa6302** [comment]
Ok. I see what it is you are attempting. In our code, we do use a list of transceivers that get added to a list. What you can do is (as you mentioned), you can create transceivers and add them to the list like in the sample after parsing the sdp. SDK cannot handle the dynamic nature of add/remove video tracks automatically at this point.

**Comment by oleg-skydio** [comment]
Thank you, this answers my question

**Comment by disa6302** [comment]
Closing as question is answered. Feel free to reach out if you have any more questions. Thank you!
