### ISSUE TITLE
[QUESTION] How to Configure the SDK to adapt to Chrome 98?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1389]
We are having issues with the SDK with the recent deprecation of SDES on chrome 98. Do we wonder what would be the steps to disable SDES? We understand this could be a chrome-specific config, js config, or c config. Our version is based off of v1.3.0.
https://developer.chrome.com/blog/deps-rems-98/

Edit:
As determined by hassantech. The root cause was Chrome 98 had exceeded the max allowed lines of SDP configured by the SDK.

**Comment by disa6302** [comment]
AFAIK, we do not use SDES for security implementation in the SDK. We use `DTLS-SRTP`. Can you highlight what the issues you are facing are and include SDK logs?

FYI: You are using a very old version of the SDK. Please upgrade to `v1.7.0`.

**Comment by suggestedfixes** [comment]
Here is an example of other people reporting on the js sdk https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/160

**Comment by disa6302** [comment]
It is possible the offer from the borwser side has changed. In previous version, `sdes` parameter is a part of the `extmap` sdp attribute. While we try to reproduce this, can you also attach SDK logs with `export DEBUG_LOG_SDP=TRUE`? It would be super helpful for us. Thanks!

**Comment by suggestedfixes** [comment]
Good find, my log confirms this as well!
![image](https://user-images.githubusercontent.com/61390265/152883918-e1492600-d890-4750-88d1-116b440e9864.png)

**Comment by suggestedfixes** [comment]
```
#define STATUS_WEBRTC_BASE 0x55000000
#define STATUS_SDP_BASE                         STATUS_WEBRTC_BASE + 0x01000000
#define STATUS_SDP_ATTRIBUTE_MAX_EXCEEDED       STATUS_SDP_BASE + 0x0000000F
```
Those 3 sum up to 0x56.....F

**Comment by hassanctech** [comment]
It does not also these are static with size determined at compile time.  These SDKs are targeted to C89.

**Comment by hassanctech** [comment]
@suggestedfixes can you confirm that this change resolved your issue?

**Comment by hassanctech** [comment]
@suggestedfixes Also perhaps we should change the title of the question, as per your logs there is zero indication of a SDES related issue.

**Comment by suggestedfixes** [comment]
https://github.com/awslabs/aws-c-common/blob/main/include/aws/common/array_list.h

This one might be something as close as a vector<> I can think of.

**Comment by suggestedfixes** [comment]
Great! Thank you very much for identifying the issue and solving it! We really appreciate the great support and effort!

**Comment by disa6302** [comment]
@sugg,

Here is the new release with the fix: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/releases/tag/v1.7.1


As mentioned before, you are using a pretty old version of the SDK, recommend jumping onto this release.
