### ISSUE TITLE
Kvs reports STATUS_SDP_ATTRIBUTE_MAX_EXCEEDED when using the newest version of google chrome

### ISSUE THREAD

**Issue by david511** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1396]
I just updated my chrome to version 98.0.4758.82 and my kvs webrtc stream fails to connect however when I try using it in Firefox everything works fine.

Kvs are logging these errors:
[error] 2022-02-11 17:21:51.669058 kvs: handleOffer(): operation returned status code: 0x5600000f
[error] 2022-02-11 17:21:51.669095 kvs: signalingMessageReceived(): operation returned status code: 0x5600000f[error] 2022-02-11 17:21:51.669141 kvs: receiveLwsMessageWrapper(): operation returned status code: 0x5600000f

It appears this error gets logged in parseMediaAttributes() from /src/source/Sdp/Deserialize.c. This is the line:     CHK(currentMediaAttributesCount < MAX_SDP_ATTRIBUTES_COUNT, STATUS_SDP_ATTRIBUTE_MAX_EXCEEDED);

Is this a known issue with the newest version of chrome? Does anyone have any advise on how to resolve this?

**Comment by disa6302** [comment]
We have released a new version to fix this. Please check v1.7.1.
Closing
