### ISSUE TITLE
Get a feedback error 0x5a00000d when app

### ISSUE THREAD

**Issue by yy-arya** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1408]

**Comment by yy-arya** [comment]
<img width="881" alt="connect" src="https://user-images.githubusercontent.com/89886877/154633738-b5d9814c-d327-45a6-9be5-b59d005320d1.png">

**Comment by yy-arya** [comment]
I would like to know the reason for the failure is there any related configuration that can be optimized?

**Comment by disa6302** [comment]
@yy-arya ,

`0x5a00000d` means that the ICE agent could not find a connected pair within the timeout. Wondering if there is something going on with your network, maybe a firewall that might be preventing the connections? 

Also, can you include the complete logs?

**Comment by yy-arya** [comment]
![224f1db8e8eb4c5c3f23e54983207a3](https://user-images.githubusercontent.com/89886877/154790681-047a988e-8ca3-4980-86d5-de182e81dfdd.png)

This is log from recieved connect request to failed.  I connot ensure if there is something going on with network.  This error sometimes only occurs under different wifi conditions, and sometimes only under 4G networks.

**Comment by disa6302** [comment]
@yy-arya ,

It could be something with your 4G network which has some settings that could be preventing from ICE candidates pairs to connect successfully. Please debug your network settings to understand what could be going on.

**Comment by yy-arya** [comment]
I'll check network related to see if it affects pairing. But under the same network, I am connected to the device of other server. I would like to know if the issue is related to the configuration on the client or server side.

**Comment by ycyang1229** [comment]
Hey, there is one parameter maybe you want to give it a try.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.h#L25.
Change it from 50ms to 150ms or 500ms.

**Comment by yy-arya** [comment]
@ycyang1229  I will try， Thank you!

**Comment by disa6302** [comment]
Closing assuming question answered
