### ISSUE TITLE
Use non-blocking socket

### ISSUE THREAD

**Issue by ek9852** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#141]
If I read the code correcly. FIONBIO (non-blocking socket) was not used.
So during writeFrame in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c#L192
And the underlying layer simply called send.
If only one client network connection was blocked, it will blocked all other clients, since the sample use a simple for-loop calling writeFrame to all connected clients and the underlying layer does not use non-blocking socket.

It will makes all clients have videos degraded if only one client had bad network connection.

**Comment by Sean-Der** [comment]
Yes we need to do something better long-term, but we have the following things I haven't thought through fully yet.

* Do we buffer? If we do how much? Do we let users determine what to throw away? 
* In most cases we are doing UDP, so I don't believe it will be blocking. In the cases we do TURN via TCP it will be a problem though.

There might be other issues, but haven't really tackled this fully yet.

**Comment by ek9852** [comment]
Yep, for UDP, that might not be a problem unless the send rate is reaching the network max. speed.
With TCP, it could be an issue.  We  can control the socket send buffer size via SO_SNDBUF , so no ned for another buffer in user space. Then might be throw away the packet once the  socket buffer is full, i.e. EAGAIN or EWOULDBLOCK return in send.  

The size of the socket send buffer size should be adjust according to the data type, a 1080p video streaming vs a voice only streaming need a different size. Possible buffer 100ms of data at most to ensure latency is minimum.

**Comment by Sean-Der** [comment]
That sounds like a good idea to me!  We can probably just allow `SO_SNDBUF` to be set via the Public API. The less code the better :)

In the future if we have to allow custom 'leak' behavior like GStreamer's queue (upstream vs downstream) we can always revisit.
