### ISSUE TITLE
[QUESTION] C sdk doesn't issue offer with RTX/9000

### ISSUE THREAD

**Issue by olegomano** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1412]
I am using the kinesis c api to transmit h264 video from a embedded device to a browser client. The embedded device is the one that sends the sdp offer. I notice that this offer is missing the rtx/9000 attribute. My understanding is that this attribute is required to enable re transmits in case of packet loss. Is there any way to get it to add the rtx/9000 or to enable re transmits?

The sdp offer that the c api generates

```
o=- 310942175 2 IN IP4 127.0.0.1
    s=-
    t=0 0
    a=group:BUNDLE 0 1
    a=msid-semantic: WMS myKvsVideoStream
    m=video 9 UDP/TLS/RTP/SAVPF 125
    c=IN IP4 127.0.0.1
    a=candidate:2 1 udp 2130706431 100.75.65.109 35863 typ host raddr 0.0.0.0 rport 0 generation 0 network-cost 999
    a=candidate:1 1 udp 2130706431 2600:1010:101C:87C2:3509:A293:140D:15D4 50839 typ host raddr ::/0 rport 0 generation 0 network-cost 999
    a=candidate:0 1 udp 2130706431 2600:1010:B026:3A0C:751D:5F1D:D8A9:9823 36340 typ host raddr ::/0 rport 0 generation 0 network-cost 999
    a=msid:myKvsVideoStream myVideoTrack
    a=ssrc:1170592819 cname:SvzlgVW7FSC3Qfij
    a=ssrc:1170592819 msid:myKvsVideoStream myVideoTrack
    a=ssrc:1170592819 mslabel:myKvsVideoStream
    a=ssrc:1170592819 label:myVideoTrack
    a=rtcp:9 IN IP4 0.0.0.0
    a=ice-ufrag:JmYm
    a=ice-pwd:Tmy4p+TfJyN/qT36L1hqPnAO
    a=ice-options:trickle
    a=fingerprint:sha-256 12:54:A8:D6:7C:A2:92:4F:BA:B9:AF:56:45:36:64:AA:81:9D:3D:EB:87:87:81:54:06:44:CA:7D:94:01:15:93
    a=setup:actp

```

**Comment by disa6302** [comment]
Based on my understanding, you are setting up the SDK as a viewer? In this case, the master is something else and is the sender of media (maybe another embedded device or a web browser), the viewer does not include rtx/9000. The SDK does not support adding RTX/9000 as a viewer (receiver of media) at the moment. The SDK however reacts to an offer containing rtx/9000. This will require some investigation on how we can support this. Tagging this as an enhancement. Will update when there are more details to enclose.

**Comment by disa6302** [comment]
Tracking internally. Closing.
