### ISSUE TITLE
[BUG] CI build fails due to missing secrets

### ISSUE THREAD

**Issue by thinkski** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1415]
`sample-check` CI workflow is failing -- secrets are unavailable to CI:
```
Error: Input required and not supplied: aws-region
```

**Comment by disa6302** [comment]
@thinkski ,

It is not a bug but the nature of GHA CI that does not allow using secrets on forked branches. We will look into it.

**Comment by thinkski** [comment]
Thank you. It's showing up on PR CI builds.

**Comment by niyatim23** [comment]
Hi @thinkski, thank you for bringing this up. I have an update to fix this in the `develop` branch. Can you please rebase from `develop` to see if it works for you?

**Comment by disa6302** [comment]
@thinkski ,
Can you please rebase your PR to pick the changes? Thank you!

**Comment by disa6302** [comment]
Closing due to no response. 
@thinkski , please rebase your PR to include the change. We will reopen if the test still fails

**Comment by thinkski** [comment]
@disa6302 Sorry, didn't see this earlier. I rebased on the Feb 25 commit `b4f4516`. Unfortunately, still encounter same issue.

**Comment by disa6302** [comment]
We will look into this then. Thank you for confirming!

**Comment by sirknightj** [comment]
Should be fixed as of #1631 and #1634
