### ISSUE TITLE
[QUESTION] What is the unit of the duration in RtcOnSenderBandwidthEstimation?

### ISSUE THREAD

**Issue by KittyLiou** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1418]
I read the comment of `RtcOnSenderBandwidthEstimation`, and it says that the parameter `duration` is the time window for txBytes, rxBytes, txPackets, rxPackets. I wonder what time unit it is.

**Comment by niyatim23** [comment]
Hi @KittyLiou, it should be milliseconds as per [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L624). 

Closing assuming answered, feel free to reopen in case of any further questions
