### ISSUE TITLE
[BUG] I could't download project_libwebsockets.

### ISSUE THREAD

**Issue by yy-arya** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1421]
-- Build files have been written to: /home/arya/gitpro/webrtc/amazon-kinesis-video-streams-webrtc-sdk-c-1.7.2/open-source/libwebsockets
Scanning dependencies of target project_libwebsockets
[ 11%] Creating directories for 'project_libwebsockets'
[ 22%] Performing download step (git clone) for 'project_libwebsockets'
Cloning into 'project_libwebsockets'...
fatal: unable to access 'https://github.com/warmcat/libwebsockets.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
Cloning into 'project_libwebsockets'...
^C

I could not download project_libwebsockets, could you give me a node to download this library？ The version of webrtc lib is 1.7.2.

**Comment by disa6302** [comment]
The repo should build as is. What platform are you running this on? Was the SDK building fine with previous versions? I would suggest clean building the repo.

**Comment by yy-arya** [comment]
@disa6302  I need build mips architecture lib，My platform is Ubuntu20. I first built it.

**Comment by yy-arya** [comment]
@disa6302 I want to download it directly, But I'm not sure which node is the fit.
