### ISSUE TITLE
[QUESTION] Sometimes too long delay in SignalingClientFetchSync function

### ISSUE THREAD

**Issue by EunseongBoo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1423]
When I use my custom app with small changes to KVS Master example, sometimes lws (lib web sockets) takes too long time (5.230s in below test log) in `SignalingClientFetchSync` function. 

The test device is a embedded device and use WiFi. 

My questions is why the delay is occur sometimes. It's just wireless network problem? 
Could I reduce the delay or stabilize it? or Can't I control it? 

The test log is below. 

> [2022-03-07 13:16:04.619] [KVS Master] Created signaling channel cam
> [2022-03-07 13:16:04.659] [KVS Master] KVS WebRTC initialization completed successfully
> [2022-03-07 13:16:04.663] [2022/03/07 13:16:04:0507] N: lws_create_context: LWS: 4.3.0-linux-4.19-gen-rkr1-411-ga439fb32, NET CLI SRV H1 H2 WS ConMon IPV6-on
> [2022-03-07 13:16:04.663] [2022/03/07 13:16:04:0518] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
> [2022-03-07 13:16:04.663] [2022/03/07 13:16:04:0522] N: __lws_lc_tag:  ++ [vh|0|netlink] (1)
> [2022-03-07 13:16:04.663] [2022/03/07 13:16:04:0529] N: __lws_lc_tag:  ++ [vh|1|default||-1] (2)
> [2022-03-07 13:16:04.665] [KVS Master] Signaling client created successfully
> [2022-03-07 13:16:04.665] [2022/03/07 13:16:04:0566] N: __lws_lc_tag:  ++ [wsicli|0|POST/h1/default/kinesisvideo.ap-northeast-2.amazonaw] (1)
> [2022-03-07 13:16:04.721] [2022/03/07 13:16:04:1108] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:04.976] [2022/03/07 13:16:04:3689] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:05.097] [2022/03/07 13:16:04:4849] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:05.097] [2022/03/07 13:16:04:4850] N: __lws_lc_untag:  -- [wsicli|0|POST/h1/default/kinesisvideo.ap-northeast-2.amazonaw] (0) 428.425ms
> [2022-03-07 13:16:05.097] [2022/03/07 13:16:04:4865] N: __lws_lc_tag:  ++ [wsicli|1|POST/h1/default/kinesisvideo.ap-northeast-2.amazonaw] (1)
> [2022-03-07 13:16:05.162] [2022/03/07 13:16:04:5532] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:05.222] [2022/03/07 13:16:04:6126] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:05.243] [2022/03/07 13:16:04:6292] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:05.243] [2022/03/07 13:16:04:6293] N: __lws_lc_untag:  -- [wsicli|1|POST/h1/default/kinesisvideo.ap-northeast-2.amazonaw] (0) 142.845ms
> [2022-03-07 13:16:05.243] [2022/03/07 13:16:04:6311] N: __lws_lc_tag:  ++ [wsicli|2|POST/h1/default/r-424ef825.kinesisvideo.ap-northeast] (1)
> [2022-03-07 13:16:10.329] [2022/03/07 13:16:09:7217] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:10.360] [2022/03/07 13:16:09:7535] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:10.471] [2022/03/07 13:16:09:8611] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:10.471] [2022/03/07 13:16:09:8613] N: __lws_lc_untag:  -- [wsicli|2|POST/h1/default/r-424ef825.kinesisvideo.ap-northeast] (0) [5.230s](url)
> [2022-03-07 13:16:10.471] [KVS Master] SignalingClientFetchSync done
> [2022-03-07 13:16:10.471] [2022/03/07 13:16:09:8637] N: __lws_lc_tag:  ++ [wsicli|3|WS/h1/default/m-8f1d6e17.kinesisvideo.ap-northeast-2] (1)
> [2022-03-07 13:16:10.522] [2022/03/07 13:16:09:9151] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:10.557] [2022/03/07 13:16:09:9490] N: lws_gate_accepts: on = 0
> [2022-03-07 13:16:10.662] [KVS Master] Signaling client connection to socket established
> [2022-03-07 13:16:10.662] [KVS Master] Channel cam set up done 
>

**Comment by niyatim23** [comment]
Hi @EunseongBoo, from a cursory look at the logs, I do not see any errors or issues with the SDK, this could be a network issue. How frequently are you able to reproduce this? Can you please share verbose logs from the SDK so that we are sure? Also, can you please share the version of the SDK you are using?
