### ISSUE TITLE
[QUESTION] How to deal with symmetric NATs for viewers?

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1425]
I've got an WebRtc app where viewers watch a camera stream. The viewers only ingest media from the server and don't send any media. We noticed that when a viewer uses 4G they are often behind a symmetric NAT which triggers the use of a TURN server. The server uses a port/address restricted cone NAT that we can configure.

I'm pretty sure that we need TURN, but I'm wondering if there might be a solution to setup a peer-2-peer connection. My understanding is that the viewer who uses e.g. Chrome binds an UDP socket on a particular port and uses `recvfrom()` to read the media packets from the server that's sending the packets.  Because no NAT entry can be used from the symmetric NAT of the viewer, we need an intermediate TURN/relay.

**Comment by hassanctech** [comment]
If your viewers are behind a symmetric NAT (which you do not control) the *only* way it would be possible to achieve peer-to-peer is if your server (which I'm not sure what level of control you have) were behind either a full cone NAT or an address restricted NAT.  As soon as the server becomes port restricted, peer to peer is not possible.

**Comment by disa6302** [comment]
Closing assuming answered.
