### ISSUE TITLE
[QUESTION]OpenSSL inlude dir and OpenSSL libraries

### ISSUE THREAD

**Issue by yy-arya** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1426]
I try to compile the webrtc library. I would like to use my own open-source, but I can't think of a way to modify the path.
![1646787714(1)](https://user-images.githubusercontent.com/89886877/157352083-e11b9fce-bce3-4d77-ae2d-a353d33c9d9e.png)

**Comment by disa6302** [comment]
@yy-arya , 

There are no details in the issue  you opened or the screenshot attached for the team to guide you. Based on what I understand out of your question, if you are looking to have the libraries installed in your custom directory, you can pass `-DOPEN_SRC_INSTALL_PREFIX=<the-directory-you-want>` with `cmake` and that should help.

Like this: `cmake .. -DOPEN_SRC_INSTALL_PREFIX=<the-directory-you-want>`

Closing assuming answered, please feel free to reach out if you have any more questions.
