### ISSUE TITLE
[FEATURE] support AV1 schedule 

### ISSUE THREAD

**Issue by PolunHuang** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1427]
Have any schedule about support AV1 format?
Or had any sample code I can reference to add AV1 format myself.  
if I add the format to kvsWebrtcClientMaster , can I playback it on kvs web site.
https://us-east-1.console.aws.amazon.com/kinesisvideo/home?region=us-east-1#/

**Comment by disa6302** [comment]
This is a duplicate of https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1135. We do not have an update on when this will be looked into yet.
