### ISSUE TITLE
[QUESTION]Data channel connection when the UDP port on the master side is blocked

### ISSUE THREAD

**Issue by H-Tomoki** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1428]
In my use case, I am developing an application that uses only data channels.
I assumed my use case and tested a case where the UDP port on the PC running the master is blocked.
I expected a peer connection to be established via the TURN server, but in fact the connection failed.

Additionally, I have found that a connection is established in the following three cases.

```
 (1) The master's UDP port is not blocked
 (2) Swap the master and viewer (block the UDP port on the viewer side)
 (3) Media streams for video and audio are added to SDP in addition to data channels 
```

(1) is as expected, but (2) and (3) seem strange to me. Is this correct behavior?

---
### Environment
The actual test performed was as follows. I placed the master and viewer on public subnets with different VPCs and ran the sample app. 

EC2 instance region: ap-northeast-1
Instance type: t2.micro
Machine image: Ubuntu Server 18.04 LTS
Signaling channel region: ap-northeast-1
Signaling channel message TTL: 5
SDK version: v1.7.2

![ec2](https://user-images.githubusercontent.com/52448947/157865266-0bfadcad-c1a3-4ada-b13f-8ffe052d0568.png)

<br>

The security groups for the master and viewer EC2 instances were set as follows, and all UDP ports were denied outbound only on the master side. I used the default network ACLs and allowed all traffic.

**Master**

- Inbound

| Source                                | Protocol | Port range | 
| ------------------------------------- | -------- | ---------- | 
| Public IP address range of my network | TCP      | 22         | 

- OutBound

| Source    | Protocol | Port range | 
| --------- | -------- | ---------- | 
| 0.0.0.0/0 | TCP      | 0 - 65535  | 

**Viewer**
- Inbound

| Source                                | Protocol | Port range | 
| ------------------------------------- | -------- | ---------- | 
| Public IP address range of my network | TCP      | 22         | 

- OutBound

| Source    | Protocol | Port range | 
| --------- | -------- | ---------- | 
| 0.0.0.0/0 | ALL      | ALL  | 

To use only the data channel, I modified the sample to not add video and audio transceivers.
In detail, the following sections were commented out in the master and viewer.
The version of the SDK used is v1.7.2.

<br>

**amazon-kinesis-video-streams-webrtc-sdk-c/samples/Common.c : Lines 484-511**
```
    // // Declare that we support H264,Profile=42E01F,level-asymmetry-allowed=1,packetization-mode=1 and Opus
    // CHK_STATUS(addSupportedCodec(pSampleStreamingSession->pPeerConnection, RTC_CODEC_H264_PROFILE_42E01F_LEVEL_ASYMMETRY_ALLOWED_PACKETIZATION_MODE));
    // CHK_STATUS(addSupportedCodec(pSampleStreamingSession->pPeerConnection, RTC_CODEC_OPUS));
    // // Add a SendRecv Transceiver of type video
    // videoTrack.kind = MEDIA_STREAM_TRACK_KIND_VIDEO;
    // videoTrack.codec = RTC_CODEC_H264_PROFILE_42E01F_LEVEL_ASYMMETRY_ALLOWED_PACKETIZATION_MODE;
    // videoRtpTransceiverInit.direction = RTC_RTP_TRANSCEIVER_DIRECTION_SENDRECV;
    // STRCPY(videoTrack.streamId, "myKvsVideoStream");
    // STRCPY(videoTrack.trackId, "myVideoTrack");
    // CHK_STATUS(addTransceiver(pSampleStreamingSession->pPeerConnection, &videoTrack, &videoRtpTransceiverInit,
    //                           &pSampleStreamingSession->pVideoRtcRtpTransceiver));
    // CHK_STATUS(transceiverOnBandwidthEstimation(pSampleStreamingSession->pVideoRtcRtpTransceiver, (UINT64) pSampleStreamingSession,
    //                                             sampleBandwidthEstimationHandler));
    // // Add a SendRecv Transceiver of type audio
    // audioTrack.kind = MEDIA_STREAM_TRACK_KIND_AUDIO;
    // audioTrack.codec = RTC_CODEC_OPUS;
    // audioRtpTransceiverInit.direction = RTC_RTP_TRANSCEIVER_DIRECTION_SENDRECV;
    // STRCPY(audioTrack.streamId, "myKvsVideoStream");
    // STRCPY(audioTrack.trackId, "myAudioTrack");
    // CHK_STATUS(addTransceiver(pSampleStreamingSession->pPeerConnection, &audioTrack, &audioRtpTransceiverInit,
    //                           &pSampleStreamingSession->pAudioRtcRtpTransceiver));
    // CHK_STATUS(transceiverOnBandwidthEstimation(pSampleStreamingSession->pAudioRtcRtpTransceiver, (UINT64) pSampleStreamingSession,
    //                                             sampleBandwidthEstimationHandler));
    // // twcc bandwidth estimation
    // CHK_STATUS(peerConnectionOnSenderBandwidthEstimation(pSampleStreamingSession->pPeerConnection, (UINT64) pSampleStreamingSession,
    //                                                      sampleSenderBandwidthEstimationHandler));
    // pSampleStreamingSession->firstFrame = TRUE;
    // pSampleStreamingSession->startUpLatency = 0;
```

<br>

**amazon-kinesis-video-streams-webrtc-sdk-c/samples/kvsWebRTCClientMaster.c : Lines 48-51**
```
    // // Set the audio and video handlers
    // pSampleConfiguration->audioSource = sendAudioPackets;
    // pSampleConfiguration->videoSource = sendVideoPackets;
    // pSampleConfiguration->receiveAudioVideoSource = sampleReceiveVideoFrame;
```

<br>

**amazon-kinesis-video-streams-webrtc-sdk-c/samples/kvsWebRTCClientViewer.c : Lines 138-142**
```
    // retStatus = transceiverOnFrame(pSampleStreamingSession->pAudioRtcRtpTransceiver, (UINT64) pSampleStreamingSession, sampleFrameHandler);
    // if (retStatus != STATUS_SUCCESS) {
    //     printf("[KVS Viewer] transceiverOnFrame(): operation returned status code: 0x%08x \n", retStatus);
    //     goto CleanUp;
    // }
```

### Logging

**Master**
> [KVS Master] Using trickleICE by default
> [KVS Master] Created signaling channel 1
> [KVS Master] Finished setting audio and video handlers
> [KVS Master] Checked sample video frame availability....available
> [KVS Master] Checked sample audio frame availability....available
> 2022-03-11 10:22:04 INFO    initKvsWebRtc(): SDK version: 2dff44fea83a79336fda676ba2801d0d77417cd1
> [KVS Master] KVS WebRTC initialization completed successfully
> [KVS Master] Signaling client created successfully
> 2022-03-11 10:22:05 DEBUG   lwsHttpCallbackRoutine(): Client append handshake header
> 2022-03-11 10:22:05 DEBUG   lwsHttpCallbackRoutine(): Sending the body {
>     "ChannelARN": "my channel ARN",
>     "ClientId": "ProducerMaster",
>     "Service": "TURN"
> }, size 144
> 2022-03-11 10:22:05 DEBUG   lwsHttpCallbackRoutine(): Connected with server response: 200
> 2022-03-11 10:22:05 DEBUG   lwsHttpCallbackRoutine(): Received client http
> 2022-03-11 10:22:05 DEBUG   lwsHttpCallbackRoutine(): Received client http read: 983 bytes
> 2022-03-11 10:22:05 DEBUG   lwsHttpCallbackRoutine(): Http client completed
> 2022-03-11 10:22:05 DEBUG   lwsHttpCallbackRoutine(): Client http closed
> 2022-03-11 10:22:05 DEBUG   lwsWssCallbackRoutine(): Connection established
> [KVS Master] Signaling client connection to socket established
> [KVS Master] Channel 1 set up done 
> 2022-03-11 10:22:06 DEBUG   receiveLwsMessage(): Client received message of type: SDP_OFFER
> 2022-03-11 10:22:06 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:06 DEBUG   refreshIceConfiguration(): Refreshing the ICE Server Configuration
> 2022-03-11 10:22:06 DEBUG   refreshIceConfiguration(): Refreshing the ICE Server Configuration
> 2022-03-11 10:22:06 DEBUG   iceAgentValidateKvsRtcConfig(): 
>     iceLocalCandidateGatheringTimeout: 10000 ms
>     iceConnectionCheckTimeout: 10000 ms
>     iceCandidateNominationTimeout: 10000 ms
>     iceConnectionCheckPollingInterval: 50 ms
> 2022-03-11 10:22:06 DEBUG   initializePeerConnection(): time taken to create peer connection 6 ms
> 2022-03-11 10:22:06 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: PjkfNNidq. Ip: 10.0.0.19:46125. Type: host. Protocol: udp.
> 2022-03-11 10:22:06 DEBUG   receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
> 2022-03-11 10:22:06 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:06 DEBUG   createSocket(): setsockopt() NO_SIGNAL failed with errno Protocol not available
> 2022-03-11 10:22:06 DEBUG   createSocket(): setsockopt() NO_SIGNAL failed with errno Protocol not available
> 2022-03-11 10:22:06 DEBUG   createSocket(): setsockopt() NO_SIGNAL failed with errno Protocol not available
> 2022-03-11 10:22:06 DEBUG   createSocket(): setsockopt() NO_SIGNAL failed with errno Protocol not available
> 2022-03-11 10:22:06 DEBUG   iceAgentCheckConnectionStateSetup(): ice candidate pair count 1
> 2022-03-11 10:22:06 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_NONE to ICE_AGENT_STATE_CHECK_CONNECTION.
> 2022-03-11 10:22:06 INFO    onConnectionStateChange(): New connection state 2
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_NEW to TURN_STATE_CHECK_SOCKET_CONNECTION
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_NEW to TURN_STATE_CHECK_SOCKET_CONNECTION
> 2022-03-11 10:22:06 DEBUG   iceAgentLogNewCandidate(): New local ice candidate discovered. Id: L/u9kBYit. Ip: 10.0.0.167:51773. Type: host. Protocol: udp.
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CHECK_SOCKET_CONNECTION to TURN_STATE_GET_CREDENTIALS
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CHECK_SOCKET_CONNECTION to TURN_STATE_GET_CREDENTIALS
> 2022-03-11 10:22:06 DEBUG   receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
> 2022-03-11 10:22:06 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:06 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: Pmnc6fmYD. Ip: **.**.**.**:35545. Type: srflx. Protocol: udp.
> 2022-03-11 10:22:06 DEBUG   socketConnectionTlsSessionOnStateChange(): TLS handshake done. Time taken 99 ms
> 2022-03-11 10:22:07 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_GET_CREDENTIALS to TURN_STATE_ALLOCATION
> 2022-03-11 10:22:07 DEBUG   turnConnectionHandleStun(): TURN Allocation succeeded. Life time: 600 seconds. Allocation expiration epoch 164699472705489
> 2022-03-11 10:22:07 DEBUG   receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
> 2022-03-11 10:22:07 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:07 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: tisbF2MjK. Ip: **.**.**.**:52281. Type: relay. Protocol: udp.
> 2022-03-11 10:22:07 DEBUG   receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
> 2022-03-11 10:22:07 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:07 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: 48CXVQUMt. Ip: **.**.**.**:56431. Type: relay. Protocol: udp.
> 2022-03-11 10:22:07 DEBUG   turnConnectionStepState(): Relay address received: **.**.**.**, port: 52131
> 2022-03-11 10:22:07 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_ALLOCATION to TURN_STATE_CREATE_PERMISSION
> 2022-03-11 10:22:07 DEBUG   iceAgentLogNewCandidate(): New local ice candidate discovered. Id: LZZ9uY21G. Ip: **.**.**.**:52131. Type: relay. Protocol: tcp.
> 2022-03-11 10:22:07 DEBUG   turnConnectionHandleStun(): TURN Allocation succeeded. Life time: 600 seconds. Allocation expiration epoch 164699472710471
> 2022-03-11 10:22:07 WARN    turnConnectionHandleStunError(): Received STUN error response. Error type: 0x00, Error Code: 403. attribute len 16, Error detail: Forbidden IP.
> 2022-03-11 10:22:07 DEBUG   turnConnectionHandleStun(): create permission succeeded for peer **.**.**.**
> 2022-03-11 10:22:07 DEBUG   turnConnectionHandleStun(): create permission succeeded for peer **.**.**.**
> 2022-03-11 10:22:07 DEBUG   turnConnectionHandleStun(): create permission succeeded for peer **.**.**.**
> 2022-03-11 10:22:07 ERROR   turnConnectionSendData(): operation returned status code: 0x5a000027
> 2022-03-11 10:22:07 ERROR   iceUtilsSendData(): operation returned status code: 0x5a000027
> 2022-03-11 10:22:07 ERROR   iceUtilsSendStunPacket(): operation returned status code: 0x5a000027
> 2022-03-11 10:22:07 WARN    iceAgentSendStunPacket(): iceUtilsSendStunPacket failed with 0x5a000027
> 2022-03-11 10:22:07 DEBUG   iceAgentSendStunPacket(): mark candidate pair LZZ9uY21G_PjkfNNidq as failed
> 2022-03-11 10:22:07 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer **.**.**.**, port: 35545, channel number 16386
> 2022-03-11 10:22:07 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer **.**.**.**, port: 52281, channel number 16387
> 2022-03-11 10:22:07 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer **.**.**.**, port: 56431, channel number 16388
> 2022-03-11 10:22:09 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CREATE_PERMISSION to TURN_STATE_BIND_CHANNEL
> 2022-03-11 10:22:11 ERROR   turnConnectionStepState(): operation returned status code: 0x5a000020
> 2022-03-11 10:22:11 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_GET_CREDENTIALS to TURN_STATE_FAILED
> 2022-03-11 10:22:11 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x5a000020. Aborting TurnConnection
> 2022-03-11 10:22:11 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_FAILED to TURN_STATE_CLEAN_UP
> 2022-03-11 10:22:11 DEBUG   socketConnectionClosed(): Close socket 10
> 2022-03-11 10:22:11 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_FAILED
> 2022-03-11 10:22:12 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x5a000020. Aborting TurnConnection
> 2022-03-11 10:22:12 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_BIND_CHANNEL to TURN_STATE_READY
> 2022-03-11 10:22:15 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:16 ERROR   executeFailedIceAgentState(): IceAgent failed with 0x5a00000d
> 2022-03-11 10:22:16 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_FAILED.
> 2022-03-11 10:22:16 INFO    onConnectionStateChange(): New connection state 5
> 2022-03-11 10:22:16 DEBUG   freeSampleStreamingSession(): Freeing streaming session with peer id: ConsumerViewer_671953219 
> 2022-03-11 10:22:16 DEBUG   iceAgentGatherCandidateTimerCallback(): Candidate gathering completed.
> 2022-03-11 10:22:16 DEBUG   onIceCandidateHandler(): ice candidate gathering finished
> 2022-03-11 10:22:16 DEBUG   sendLwsMessage(): Sending data over web socket: Message type: SDP_ANSWER, RecepientId: ConsumerViewer_671953219
> 2022-03-11 10:22:16 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:16 DEBUG   onIceCandidateHandler(): time taken to send answer 10025 ms
> 2022-03-11 10:22:16 DEBUG   socketConnectionClosed(): Close socket 9
> 2022-03-11 10:22:16 DEBUG   socketConnectionClosed(): Close socket 8
> 2022-03-11 10:22:16 DEBUG   handleStunPacket(): Received STUN binding indication
> 2022-03-11 10:22:17 DEBUG   handleStunPacket(): received candidate with USE_CANDIDATE flag, local candidate type relay.
> 2022-03-11 10:22:17 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_READY to TURN_STATE_CLEAN_UP
> 2022-03-11 10:22:17 WARN    iceAgentShutdown(): TurnConnection shutdown did not complete within 1 seconds
> 2022-03-11 10:22:17 DEBUG   socketConnectionClosed(): Close socket 11
> 2022-03-11 10:22:25 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:35 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:45 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:55 DEBUG   lwsWssCallbackRoutine(): Client is writable

<br>

**Viewer**

> [KVS Master] Using trickleICE by default
> [KVS Viewer] Created signaling channel 1
> [KVS Viewer] KVS WebRTC initialization completed successfully
> [KVS Viewer] Signaling client created successfully
> 2022-03-11 10:22:06 DEBUG   lwsHttpCallbackRoutine(): Client append handshake header
> 2022-03-11 10:22:06 DEBUG   lwsHttpCallbackRoutine(): Sending the body {
>     "ChannelARN": "my channel ARN",
>     "ClientId": "ConsumerViewer_671953219",
>     "Service": "TURN"
> }, size 154
> 2022-03-11 10:22:06 DEBUG   lwsHttpCallbackRoutine(): Connected with server response: 200
> 2022-03-11 10:22:06 DEBUG   lwsHttpCallbackRoutine(): Received client http
> 2022-03-11 10:22:06 DEBUG   lwsHttpCallbackRoutine(): Received client http read: 986 bytes
> 2022-03-11 10:22:06 DEBUG   lwsHttpCallbackRoutine(): Http client completed
> 2022-03-11 10:22:06 DEBUG   lwsHttpCallbackRoutine(): Client http closed
> 2022-03-11 10:22:06 DEBUG   lwsWssCallbackRoutine(): Connection established
> [KVS Viewer] Signaling client connection to socket established
> 2022-03-11 10:22:06 DEBUG   refreshIceConfiguration(): Refreshing the ICE Server Configuration
> 2022-03-11 10:22:06 DEBUG   refreshIceConfiguration(): Refreshing the ICE Server Configuration
> 2022-03-11 10:22:06 DEBUG   iceAgentValidateKvsRtcConfig(): 
>     iceLocalCandidateGatheringTimeout: 10000 ms
>     iceConnectionCheckTimeout: 10000 ms
>     iceCandidateNominationTimeout: 10000 ms
>     iceConnectionCheckPollingInterval: 50 ms
> 2022-03-11 10:22:06 DEBUG   initializePeerConnection(): time taken to create peer connection 4 ms
> [KVS Viewer] Creating streaming session...completed
> 2022-03-11 10:22:06 DEBUG   createSocket(): setsockopt() NO_SIGNAL failed with errno Protocol not available
> 2022-03-11 10:22:06 DEBUG   createSocket(): setsockopt() NO_SIGNAL failed with errno Protocol not available
> 2022-03-11 10:22:06 DEBUG   createSocket(): setsockopt() NO_SIGNAL failed with errno Protocol not available
> 2022-03-11 10:22:06 DEBUG   createSocket(): setsockopt() NO_SIGNAL failed with errno Protocol not available
> [KVS Viewer] Completed setting local description
> [KVS Viewer] Offer creation successful
> [KVS Viewer] Generating JSON of session description....Completed
> 2022-03-11 10:22:06 DEBUG   sendLwsMessage(): Sending data over web socket: Message type: SDP_OFFER, RecepientId: ProducerMaster
> 2022-03-11 10:22:06 DEBUG   lwsWssCallbackRoutine(): Client is writable
> [KVS Viewer] Creating data channel...completed
> [KVS Viewer] Data Channel open now...
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_NEW to TURN_STATE_CHECK_SOCKET_CONNECTION
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_NEW to TURN_STATE_CHECK_SOCKET_CONNECTION
> 2022-03-11 10:22:06 DEBUG   iceAgentLogNewCandidate(): New local ice candidate discovered. Id: QpW+Berur. Ip: 10.0.0.19:46125. Type: host. Protocol: udp.
> 2022-03-11 10:22:06 DEBUG   sendLwsMessage(): Sending data over web socket: Message type: ICE_CANDIDATE, RecepientId: ConsumerViewer
> 2022-03-11 10:22:06 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CHECK_SOCKET_CONNECTION to TURN_STATE_GET_CREDENTIALS
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CHECK_SOCKET_CONNECTION to TURN_STATE_GET_CREDENTIALS
> 2022-03-11 10:22:06 DEBUG   iceAgentLogNewCandidate(): New local ice candidate discovered. Id: egTBy+9Od. Ip: **.**.**.**:35545. Type: srflx. Protocol: udp.
> 2022-03-11 10:22:06 DEBUG   sendLwsMessage(): Sending data over web socket: Message type: ICE_CANDIDATE, RecepientId: ConsumerViewer
> 2022-03-11 10:22:06 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_GET_CREDENTIALS to TURN_STATE_ALLOCATION
> 2022-03-11 10:22:06 DEBUG   socketConnectionTlsSessionOnStateChange(): TLS handshake done. Time taken 100 ms
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_GET_CREDENTIALS to TURN_STATE_ALLOCATION
> 2022-03-11 10:22:06 DEBUG   turnConnectionHandleStun(): TURN Allocation succeeded. Life time: 600 seconds. Allocation expiration epoch 164699472693127
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): Relay address received: **.**.**.**, port: 52281
> 2022-03-11 10:22:06 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_ALLOCATION to TURN_STATE_CREATE_PERMISSION
> 2022-03-11 10:22:06 DEBUG   iceAgentLogNewCandidate(): New local ice candidate discovered. Id: fc1XKpvyL. Ip: **.**.**.**:52281. Type: relay. Protocol: udp.
> 2022-03-11 10:22:06 DEBUG   sendLwsMessage(): Sending data over web socket: Message type: ICE_CANDIDATE, RecepientId: ConsumerViewer
> 2022-03-11 10:22:06 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:06 DEBUG   turnConnectionHandleStun(): TURN Allocation succeeded. Life time: 600 seconds. Allocation expiration epoch 164699472698115
> 2022-03-11 10:22:06 DEBUG   turnConnectionHandleStun(): TURN Allocation succeeded. Life time: 600 seconds. Allocation expiration epoch 164699472698160
> 2022-03-11 10:22:07 DEBUG   turnConnectionStepState(): Relay address received: **.**.**.**, port: 56431
> 2022-03-11 10:22:07 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_ALLOCATION to TURN_STATE_CREATE_PERMISSION
> 2022-03-11 10:22:07 DEBUG   iceAgentLogNewCandidate(): New local ice candidate discovered. Id: OmM3AAa9L. Ip: **.**.**.**:56431. Type: relay. Protocol: tcp.
> 2022-03-11 10:22:07 DEBUG   sendLwsMessage(): Sending data over web socket: Message type: ICE_CANDIDATE, RecepientId: ConsumerViewer
> 2022-03-11 10:22:07 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:07 DEBUG   turnConnectionHandleStun(): TURN Allocation succeeded. Life time: 600 seconds. Allocation expiration epoch 164699472703137
> 2022-03-11 10:22:07 DEBUG   iceAgentGatherCandidateTimerCallback(): Candidate gathering completed.
> 2022-03-11 10:22:07 DEBUG   onIceCandidateHandler(): ice candidate gathering finished
> 2022-03-11 10:22:16 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:16 DEBUG   receiveLwsMessage(): Client received message of type: SDP_ANSWER
> 2022-03-11 10:22:16 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:16 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: ljCN2NhnW. Ip: **.**.**.**:52131. Type: relay. Protocol: udp.
> 2022-03-11 10:22:16 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: z2FOHHF4I. Ip: 10.0.0.167:51773. Type: host. Protocol: udp.
> 2022-03-11 10:22:16 DEBUG   iceAgentCheckConnectionStateSetup(): ice candidate pair count 8
> 2022-03-11 10:22:16 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_NONE to ICE_AGENT_STATE_CHECK_CONNECTION.
> 2022-03-11 10:22:16 INFO    onConnectionStateChange(): New connection state 2
> 2022-03-11 10:22:16 DEBUG   handleStunPacket(): Ice candidate pair egTBy+9Od_ljCN2NhnW is connected. Round trip time: 0ms
> 2022-03-11 10:22:16 DEBUG   turnConnectionHandleStun(): create permission succeeded for peer **.**.**.**
> 2022-03-11 10:22:16 DEBUG   turnConnectionHandleStun(): create permission succeeded for peer **.**.**.**
> 2022-03-11 10:22:16 WARN    turnConnectionHandleStunError(): Received STUN error response. Error type: 0x00, Error Code: 403. attribute len 16, Error detail: Forbidden IP.
> 2022-03-11 10:22:16 WARN    turnConnectionHandleStunError(): Received STUN error response. Error type: 0x00, Error Code: 403. attribute len 16, Error detail: Forbidden IP.
> 2022-03-11 10:22:16 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_CONNECTED.
> 2022-03-11 10:22:17 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer **.**.**.**, port: 52131, channel number 16385
> 2022-03-11 10:22:17 DEBUG   turnConnectionHandleStun(): Channel bind succeeded with peer **.**.**.**, port: 52131, channel number 16385
> 2022-03-11 10:22:17 DEBUG   iceAgentNominateCandidatePair(): Nominating candidate pair
> 2022-03-11 10:22:17 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CONNECTED to ICE_AGENT_STATE_NOMINATING.
> 2022-03-11 10:22:17 DEBUG   iceAgentReadyStateSetup(): Selected pair egTBy+9Od_ljCN2NhnW, local candidate type: srflx. Round trip time 0 ms. Local candidate priority: 1694498815, ice candidate pair priority: 72057593131958270
> 2022-03-11 10:22:17 DEBUG   iceAgentReadyStateSetup(): Freeing Turn allocations that are not selected. Total turn allocation count 2
> 2022-03-11 10:22:17 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_NOMINATING to ICE_AGENT_STATE_READY.
> 2022-03-11 10:22:17 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CREATE_PERMISSION to TURN_STATE_CLEAN_UP
> 2022-03-11 10:22:17 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CREATE_PERMISSION to TURN_STATE_CLEAN_UP
> 2022-03-11 10:22:17 DEBUG   turnConnectionHandleStun(): TURN Allocation freed.
> 2022-03-11 10:22:17 DEBUG   turnConnectionHandleStun(): TURN Allocation freed.
> 2022-03-11 10:22:17 DEBUG   socketConnectionClosed(): Close socket 10
> 2022-03-11 10:22:17 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_NEW
> 2022-03-11 10:22:17 DEBUG   socketConnectionClosed(): Close socket 11
> 2022-03-11 10:22:17 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_NEW
> 2022-03-11 10:22:26 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:36 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:46 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-03-11 10:22:47 DEBUG   executeDisconnectedIceAgentState(): Ice agent detected disconnection. current state ICE_AGENT_STATE_READY. Last data received time 1646994137 s
> 2022-03-11 10:22:47 INFO    onConnectionStateChange(): New connection state 4
> [KVS Viewer] Cleaning up....

---

### (1) The master's UDP port is not blocked
When the security group of the EC2 instance running the master was changed as shown below and UDP was allowed, a peer connection was established.

**Master**
- Inbound

| Source                                | Protocol | Port range | 
| ------------------------------------- | -------- | ---------- | 
| Public IP address range of my network | TCP      | 22         | 

- OutBound

| Source    | Protocol | Port range | 
| --------- | -------- | ---------- | 
| 0.0.0.0/0 | ALL      | ALL  | 

<br>

**Connection metrics**
> 2022-03-11 10:25:33 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate type: srflx
> 2022-03-11 10:25:33 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate port: 33282
> 2022-03-11 10:25:33 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate transport protocol: udp
> 2022-03-11 10:25:33 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate relay protocol: N/A
> 2022-03-11 10:25:33 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate type: srflx
> 2022-03-11 10:25:33 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate port: 43803
> 2022-03-11 10:25:33 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate transport protocol: udp

### (2) Swap the master and viewer (block the UDP port on the viewer side)
By swapping the instances running the master and viewer, a peer connection was established even though the UDP port on the viewer side was blocked.

**Connection metrics**

> 2022-03-11 10:24:17 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate type: srflx
> 2022-03-11 10:24:17 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate port: 36092
> 2022-03-11 10:24:17 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate transport protocol: udp
> 2022-03-11 10:24:17 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate relay protocol: N/A
> 2022-03-11 10:24:17 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate type: relay
> 2022-03-11 10:24:17 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate port: 52611
> 2022-03-11 10:24:17 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate transport protocol: 

### (3) Media streams for video and audio are added to SDP in addition to data channels
When I ran the original sample with all comment-outs removed, a peer connection was established using the TURN server even though the UDP port was denied.

**Connection metrics**

> 2022-03-11 10:29:19 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate type: relay
> 2022-03-11 10:29:19 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate port: 56046
> 2022-03-11 10:29:19 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate transport protocol: tcp
> 2022-03-11 10:29:19 DEBUG   logSelectedIceCandidatesInformation(): Local Candidate relay protocol: tcp
> 2022-03-11 10:29:19 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate type: srflx
> 2022-03-11 10:29:19 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate port: 57926
> 2022-03-11 10:29:19 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate transport protocol: udp

**Comment by disa6302** [comment]
@H-Tomoki ,

Apologies for the delayed response. But if UDP is blocked TCP is used. So you would see it working in the 3 scenarios.
