### ISSUE TITLE
memory leak in sample

### ISSUE THREAD

**Issue by ek9852** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#143]
pSampleConfiguration->cvar = CVAR_CREATE(); in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L496
without corresponding CVAR_FREE called.

**Comment by MushMal** [comment]
Fixed as part of https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/151
