### ISSUE TITLE
kvs webrtc error happening on Ec2 instance. socketConnectionSendData(): Warning: Failed to send data. Socket closed already

### ISSUE THREAD

**Issue by david511** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1436]
Currently I am running the kvs webrtc binary on a linux Ec2 instance. I have been able to connect to the signaling channel fine for the past week now however I just started experiencing the error below and I am unable to connect to the signaling channel. The network connection on the Ec2 instance is working normally and I am only using IPv4 . Unfortunately, I didn't have the verbose log statements on so these are the only logs I have.

Master logs:
[debug] 2022-03-17 19:16:38.068429 kvs: receiveLwsMessage(): Client received message of type: SDP_OFFER
[debug] 2022-03-17 19:16:38.068502 kvs: lwsWssCallbackRoutine(): Client is writable
[debug] 2022-03-17 19:16:38.086200 kvs: receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
[debug] 2022-03-17 19:16:38.086281 kvs: lwsWssCallbackRoutine(): Client is writable
[debug] 2022-03-17 19:16:38.102421 kvs: receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
[debug] 2022-03-17 19:16:38.102490 kvs: lwsWssCallbackRoutine(): Client is writable
[debug] 2022-03-17 19:16:38.136548 kvs: receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
[debug] 2022-03-17 19:16:38.136646 kvs: lwsWssCallbackRoutine(): Client is writable
[debug] 2022-03-17 19:16:38.144022 kvs: receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
[debug] 2022-03-17 19:16:38.144092 kvs: lwsWssCallbackRoutine(): Client is writable
[debug] 2022-03-17 19:18:48.639109 kvs: turnConnectionRefreshAllocation(): Refresh turn allocation
[debug] 2022-03-17 19:18:48.640961 kvs: turnConnectionHandleStunError(): Updating stale nonce
[debug] 2022-03-17 19:18:48.689184 kvs: turnConnectionRefreshAllocation(): Refresh turn allocation
[debug] 2022-03-17 19:18:48.689823 kvs: socketConnectionClosed(): Close socket 84
[debug] 2022-03-17 19:18:48.689836 kvs: connectionListenerReceiveDataRoutine(): recvfrom() failed with errno Connection reset by peer for socket 84
[debug] 2022-03-17 19:18:48.880841 kvs: lwsWssCallbackRoutine(): Client is writable
[debug] 2022-03-17 19:18:49.640541 kvs: turnConnectionRefreshAllocation(): Refresh turn allocation
[debug] 2022-03-17 19:18:49.690606 kvs: turnConnectionRefreshAllocation(): Refresh turn allocation
[debug] 2022-03-17 19:18:49.690633 kvs: socketConnectionSendData(): Warning: Failed to send data. Socket closed already
[error] 2022-03-17 19:18:49.690638 kvs: iceUtilsSendData(): operation returned status code: 0x58000022
[error] 2022-03-17 19:18:49.690641 kvs: iceUtilsSendStunPacket(): operation returned status code: 0x58000022
[error] 2022-03-17 19:18:49.690645 kvs: turnConnectionRefreshAllocation(): operation returned status code: 0x58000022
[error] 2022-03-17 19:18:49.690649 kvs: turnConnectionTimerCallback(): operation returned status code: 0x58000022
[error] 2022-03-17 19:18:49.690653 kvs: timerQueueExecutor(): operation returned status code: 0x58000022
[debug] 2022-03-17 19:18:49.740680 kvs: turnConnectionRefreshAllocation(): Refresh turn allocation
[debug] 2022-03-17 19:18:49.740705 kvs: socketConnectionSendData(): Warning: Failed to send data. Socket closed already
[error] 2022-03-17 19:18:49.740710 kvs: iceUtilsSendData(): operation returned status code: 0x58000022
[error] 2022-03-17 19:18:49.740713 kvs: iceUtilsSendStunPacket(): operation returned status code: 0x58000022

The error code 0x58000022 is indicating STATUS_SOCKET_CONNECTION_CLOSED_ALREADY.

The viewer reported this error as well: "Timed out after 10sec waiting for track"

The only way I managed to fix this was by resetting the binary containing the kvs webrtc code. I am unfamiliar with this error and not sure what would have caused it. I wondering if anyone could provide a further description about the error or how it might have gotten thrown.

**Comment by david511** [comment]
Also, is there any error callback function I could use that would report an error like this has occurred (besides having to look in the logs)?

**Comment by david511** [comment]
[debug] 2022-03-25 20:06:12.253084 kvs: sendLwsMessage(): Sending data over web socket: Message type: ICE_CANDIDATE, RecepientId: 3f75dd59-f1ff-4fb3-aad8-4e07c2510083
[debug] 2022-03-25 20:06:12.253124 kvs: lwsWssCallbackRoutine(): Client is writable
[debug] 2022-03-25 20:06:12.301033 kvs: turnConnectionStepState(): Relay address received: 54.234.237.191, port: 54671
[debug] 2022-03-25 20:06:12.301054 kvs: turnConnectionStepState(): TurnConnection state changed from TURN_STATE_ALLOCATION to TURN_STATE_CREATE_PERMISSION
[debug] 2022-03-25 20:06:12.301786 kvs: turnConnectionHandleStun(): TURN Allocation succeeded. Life time: 600 seconds. Allocation expiration epoch 164823937230177
[debug] 2022-03-25 20:06:12.303113 kvs: iceAgentGatherCandidateTimerCallback(): Candidate gathering completed.
[debug] 2022-03-25 20:06:12.303126 kvs: onIceCandidateHandler(): ice candidate gathering finished
[debug] 2022-03-25 20:06:12.423962 kvs: receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
[debug] 2022-03-25 20:06:12.424032 kvs: lwsWssCallbackRoutine(): Client is writable
[debug] 2022-03-25 20:06:12.436158 kvs: receiveLwsMessage(): Client received message of type: ICE_CANDIDATE
[debug] 2022-03-25 20:06:12.436192 kvs: lwsWssCallbackRoutine(): Client is writable
[debug] 2022-03-25 20:06:22.019335 kvs: stepStateMachine(): State Machine - Current state: 0x0000000000000002, Next state: 0x0000000000000040
[error] 2022-03-25 20:06:22.019348 kvs: executeFailedIceAgentState(): IceAgent failed with 0x5a00000d
[debug] 2022-03-25 20:06:22.019352 kvs: stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_FAILED.        2022-03-25 20:06:22.019358 kvs: onConnectionStateChange(): New connection state 5


I tried running on a new instance with the same binary however the same errors from my first post appear plus the errors I am adding in this comment. It looks like the master and viewer are trying to connect through a turn server but fail.

"IceAgent failed with 0x5a00000d" does this mean the master and viewer failed to connect to any of the ice candidates exchanged between each other?

Any help would be greatly appreciated.

**Comment by david511** [comment]
@disa6302 is there anymore information I can provide to help figure out how to resolve this issue?

**Comment by disa6302** [comment]
@david511 ,

Apologies for the delay. The error code is set when no data is received on the socket or the recv call fails for some reason. Can you attach complete logs? Do you see any other error codes?
We have a peer connection error callback that you can use to act upon a failure: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/samples/Common.c#L38

**Comment by niyatim23** [comment]
Closing due to no response, feel free to reopen / open a new issue in case of further questions
