### ISSUE TITLE
A confusing key searching logic in JitterBuffer.c

### ISSUE THREAD

**Issue by northteam** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1437]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/src/source/PeerConnection/JitterBuffer.c#L223-L230
if `retStatus` is `STATUS_HASH_KEY_NOT_PRESENT`, then `hashValue` will be untouched, which is `0`. And `pCurPacket` will be `NULL` and cannot be dereferenced. So why treat `STATUS_HASH_KEY_NOT_PRESENT` as a success?

**Comment by jdelapla** [comment]
Hello! 
The reason for this odd looking if statement is that we only want line 228 to exit on a truly critical internal error, like the hashtable doesn't exist. There is also an important check on line 216:
`216         CHK_STATUS(hashTableContains(pJitterBuffer->pPkgBufferHashTable, index, &hasEntry));`
This **should** make STATUS_HASH_KEY_NOT_PRESENT an unreachable error, unless we're dealing with some very obscure bug. 

As for the `NULL` outcome, you're correct that would be the case if this was the very first packet we've iterated through. I'll add a check for this scenario. In all other cases we would send a duplicate packet- also not ideal, I think the correct error handling would be to call `continue;` and go to the next index. I'll send a PR shortly.
