### ISSUE TITLE
Incorrect default value for RtcDataChannelInit.ordered

### ISSUE THREAD

**Issue by hector-chou** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1438]
**Describe the bug**
The assignment doesn't match its comment.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/src/source/PeerConnection/DataChannel.c#L32-L33

**SDK version number**
v1.7.2

**Comment by disa6302** [comment]
It is not a bug, but an issue with the comment. Will fix. :)
Thanks for reporting.

**Comment by hector-chou** [comment]
> It is not a bug, but an issue with the comment. Will fix. :) Thanks for reporting.

But the default value should be TRUE, right?
https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/ordered
