### ISSUE TITLE
Gst example comment error? 

### ISSUE THREAD

**Issue by EunseongBoo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1445]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/samples/kvsWebRTCClientMasterGstreamerSample.c#L78

In the above example, the comment shows that the example assume that video fps is 30. However, Sample.h uses **DEFAULT_FPS_VALUE** as 25 like below. 

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/samples/Samples.h#L17

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/samples/Samples.h#L26

The DEFAULT_FPS_VALUE is normal for 30 fps? Or is the comment wrong?

**Comment by niyatim23** [comment]
Hi @EunseongBoo, the most common value for FPS is 30, however, it can be anything you want it to be. So, either of the two values should work.

Closing assuming answered, fell free to reopen incase of further questions

**Comment by EunseongBoo** [comment]
Yeah I agreed the fps can be set what user want. But that's not my point. 
While the gstreamer code comments specify that the FPS is 30, it is actually referring to an FPS value of 25.
Comments or reference values ​​need to be fixed to clear up misunderstandings
