### ISSUE TITLE
[BUG]Incorrect define value for TWCC_ESTIMATOR_TIME_WINDOW

### ISSUE THREAD

**Issue by jinexplorer** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1447]
**Describe the bug**
I notice that it was defined 1s。but the commet describes its value is 2s
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/src/source/PeerConnection/Rtcp.h#L23

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/src/source/PeerConnection/PeerConnection.c#L1435-L1447
**SDK version number**
1.7.2

**Comment by disa6302** [comment]
@jinexplorer , 
It is a comment fix. So removing the bug tag and closing the ticket. The value defined is what needs to be followed.
