### ISSUE TITLE
Packet dropped by kernel silently

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#145]
Hi, I encountered packet drop issue on my Ubuntu 18.04 machine, which turned out be network config problem, my solution was `sysctl -w net.core.rmem_default=262144` to increase the socket buffer size. In real life, the I frame could be pretty big, I am thinking maybe the software should check and increase the kernel socket buffer size, to avoid weird and unnecessary packet drops, please comment.

**Comment by Sean-Der** [comment]
Hey @staowyze are you acting as a `receiveonly` or `sendrecv` peer? 

I wasn't aware of that setting before, but we can totally make that configurable via public API! What client are you sending from?

thanks

**Comment by staowyze** [comment]
The issue happened at receiver side. I customized the sending client a bit according to my own  scenario, but basically the same as the test example, read the h264 frame from the bistream files, packet drop happened on some big I frames.

**Comment by MushMal** [comment]
This is a hard one - it is very dependent on the actual platform and the application and won't be easy to handle things like these in the SDK layer. Another issue is the permissions - the SDK itself will not have any permission. I think the right approach here is to document this properly and if there is a way to check it at platform bring-up time then flag it.

**Comment by staowyze** [comment]
how about raising warning log if the buffer size is too tiny, we don't need permission to read the buffer size.

**Comment by MushMal** [comment]
Yeah, that was the idea on checking. Currently, we are handling just a small number of OS-es. Will need to think on how to make this generic and platform independent way

**Comment by MushMal** [comment]
Resolving this issue. We have added send buffer size. Might not be respected in all OS-es.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L921
