### ISSUE TITLE
[BUG] Memory Leak starting with 1.7.0

### ISSUE THREAD

**Issue by tross-skybell** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1450]
There seems to be a memory leak starting with 1.7.0. I cannot reproduce with 1.6.0. The leak only seems to happen when a viewer is connected. Just running the ClientMaster and stopping it doesn't show the issue.

This is with a clean build running the sample kvsWebrtcClientMaster. The only changes I have made is to add an outer loop to help track down the leak:

```
diff --git a/samples/kvsWebRTCClientMaster.c b/samples/kvsWebRTCClientMaster.c
index dcaaa7c..4f86304 100644
--- a/samples/kvsWebRTCClientMaster.c
+++ b/samples/kvsWebRTCClientMaster.c
@@ -4,7 +4,7 @@ extern PSampleConfiguration gSampleConfiguration;
 
 // #define VERBOSE
 
-INT32 main(INT32 argc, CHAR* argv[])
+INT32 main_internal(INT32 argc, CHAR* argv[])
 {
     STATUS retStatus = STATUS_SUCCESS;
     UINT32 frameSize;
@@ -157,6 +157,15 @@ CleanUp:
     return STATUS_FAILED(retStatus) ? EXIT_FAILURE : EXIT_SUCCESS;
 }
 
+INT32 main(INT32 argc, CHAR* argv[])
+{
+    while(1)
+    {
+      main_internal(argc, argv);
+      THREAD_SLEEP(30* HUNDREDS_OF_NANOS_IN_A_SECOND);
+    }
+}
+
 STATUS readFrameFromDisk(PBYTE pFrame, PUINT32 pSize, PCHAR frameFilePath)
 {
     STATUS retStatus = STATUS_SUCCESS;
```

To Reproduce
1. Verify no leak without viewer
- Run kvsWebRTCClientMaster
- Do not connect a viewer
- Ctrl-C to exit back to my new outer sleep loop
- Check memory (I am using 'pmap <pid> | grep total')
- Wait 30 seconds for the master to start back up
- Ctrl-C to exit back to my new outer sleep loop
- Check memory and verify no leak
- NOTE: you will need to repeat this a view times to get into a "steady state"

2. Verify leak with viewer
- In sleep loop check memory
- Wait 30 seconds for master to start back up
- Connect viewer
- Disconnect viewer
- Ctrl-C
- Check memory and see the leak
- NOTE: At first there will be very large leaks but that may just be the process allocating space. Repeat these steps over and over to see the consistent leak.

This is on a Ubuntu 16.0.4.
The viewer is usually the Amazon Media Playback Viewer but also tested with KVS WebRTC Test Page

For the standalone sample this isn't much of an issue. The process exits when done and memory is freed. But for an embedded system where it is started and stopped repeatedly this is causing me to run out of memory.

Final note: This could easily just be that I am using this sample code incorrectly and it was never meant to fully clean up. If so any help would be appreciated if finding a command to run to clean up anything allocated during a viewing.

**Comment by sharadrj** [comment]
@tross-skybell : thanks for reporting this issue. We will prioritise the investigation and get back once we have some findings.

**Comment by jdelapla** [comment]
Hey @tross-skybell , investigating the issue right now, thank you for elaborate ticket. While reproducing your issue, I noticed the line numbers in your main_internal function didn't match exactly what is in the tagged release (1.7.0, 1.7.1, or 1.7.2). 

`     UINT32 frameSize;
@@ -157,6 +157,15 @@ CleanUp:
     return STATUS_FAILED(retStatus) ? EXIT_FAILURE : EXIT_SUCCESS;
 }`
 
 The return statement for main is on line 177. Have you made any other changes to the sample? Perhaps in earlier commits (as the commit hashes in your diff are also not the tagged commits).
 I just want my reproduction of the issue to mirror yours as closely as possible.

**Comment by tross-skybell** [comment]
I have been bouncing between different commits trying to track it down. That was probably from 4127014 (just before the large 1.7.0 commit). If I recall, I could NOT reproduce with that commit.

Here is the patch from 1.7.2

```
diff --git a/samples/kvsWebRTCClientMaster.c b/samples/kvsWebRTCClientMaster.c
index d7e29e1..6ec9cb6 100644
--- a/samples/kvsWebRTCClientMaster.c
+++ b/samples/kvsWebRTCClientMaster.c
@@ -4,7 +4,7 @@ extern PSampleConfiguration gSampleConfiguration;
 
 // #define VERBOSE
 
-INT32 main(INT32 argc, CHAR* argv[])
+INT32 main_internal(INT32 argc, CHAR* argv[])
 {
     STATUS retStatus = STATUS_SUCCESS;
     UINT32 frameSize;
@@ -177,6 +177,15 @@ CleanUp:
     return STATUS_FAILED(retStatus) ? EXIT_FAILURE : EXIT_SUCCESS;
 }
 
+INT32 main(INT32 argc, CHAR* argv[])
+{
+    while(1)
+    {
+      main_internal(argc, argv);
+      THREAD_SLEEP(30* HUNDREDS_OF_NANOS_IN_A_SECOND);
+    }
+}
+
 STATUS readFrameFromDisk(PBYTE pFrame, PUINT32 pSize, PCHAR frameFilePath)
 {
     STATUS retStatus = STATUS_SUCCESS;

```

**Comment by Ryan45758** [comment]
Hi, I also seem to have found this problem, I don't know if it is a memory leak, when I execute the sample program on my embedded demo board, sometimes the program can be executed, sometimes it can't be executed, it will be stuck, I found the stuck place is in the createPeerConnection(); line.
