### ISSUE TITLE
Hi3518EV200 createDataChannel error with STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by Ryan45758** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1454]
I try to use this [example](https://www.cnblogs.com/Johness/p/implement-webrtc-in-embedded-system-sec-2.html) on my Hi3518EV200 demoboard, and here is the sample code [download link](https://drive.google.com/file/d/1okg--VUswwyRncQZG8IGAX-pd_TSqwFe/view?usp=sharing),main code path: ./kvs20201106/cv500_new/main.cc, everything goes well, but error code 12 is returned in createDataChannel, I can know that `pKvsPeerConnection->pSctpSession` is null, and dataChannelOnMessage returns error code 1, I can know that the problem lies in this line `CHK(pKvsDataChannel != NULL && rtcOnMessage != NULL, STATUS_NULL_ARG);`, before this I also encountered `1970-01-01 00:04:55 ERROR dtlsSessionProcessPacket(): operation returned status code: 0x59000004`and`1970-01-01 00:38:18 ERROR   executeFailedIceAgentState(): IceAgent failed with 0x5a00002`, I also changed the time , the problem is still there, I don't know if it is a dtls problem, how to solve it? Below is my log output

LOG OUTPUT: [webrtc_rtcdc.log](https://drive.google.com/file/d/1hWUCFPyKF7l_2SrtCt-TkxYP22O4hj03/view?usp=sharing)

And when I used wireshark to capture packets, I found that STUN would keep looping and running repeatedly, like
STUN -> UDP -> UDP -> STUN -> UDP -> UDP -> STUN, is this normal?
![image](https://i.imgur.com/rGFtYsJ_d.webp?maxwidth=1520&fidelity=grand)

**Comment by hassanctech** [comment]
It looks like in the error code print out a zero was missed, or maybe @Ryan45758 modified it by accident, perhaps this is the one it should have been: `0x5a000002` is this one:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/22c9e3d7932365f0d04181b339f17e4870036f5c/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L176

`STATUS_ICE_CANDIDATE_STRING_MISSING_PORT`

The other error code mentioned is this:  `0x59000004` which is `STATUS_SSL_PACKET_BEFORE_DTLS_READY`

**Comment by Ryan45758** [comment]
@disa6302  I used the latest version of the official SDK and recompiled it. The error message of `0x5a000002` is like what @hassanctech  said. I suspect it is a DTLS problem. Could it be caused by openssl? There are other ways besides using viewer Can it be debugged? @hassanctech error code print out a zero just because I print it directly, it returns success, so it is zero, I want to ask why STATUS_ICE_CANDIDATE_STRING_MISSING_PORT and STATUS_SSL_PACKET_BEFORE_DTLS_READY happen? How to solve it will be better, I No idea, stuck for days
