### ISSUE TITLE
[QUESTION] Hi3518EV200 program sometimes executes this function createPeerConnection() for a long time, and then fails to run

### ISSUE THREAD

**Issue by Ryan45758** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1456]
Hello, I use this sdk 1.7.2 to build my webrtc application, the program runs successfully in ubuntu, but when I port it to my embedded device, the program sometimes runs, sometimes it doesn't, no errors at all  information, the program will not be terminated because of this.  

I found that when the program can't run, it is stuck in createPeerConnection().
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/src/source/PeerConnection/PeerConnection.c#L669
 Here I attach a photo of using the top command to see the resource usage of the program. 

When the program can run, I find that %vsz is about 178.  When I can't run, it's around 140, I don't know if it's caused by a memory leak, how do i fix it? I tried using 1.6.0 and the problem is still the same.

Program can be executed success
![1650555745627.jpg](https://user-images.githubusercontent.com/22660919/164501441-d0bcda56-7d64-428c-b852-b36261421e50.jpg)

Program can't be executed success
![1650555788144.jpg](https://user-images.githubusercontent.com/22660919/164501411-5ce2f4b9-6abc-49eb-8cb1-169d8c3ea789.jpg)

**Comment by disa6302** [comment]
@Ryan45758 , 

Thank you for the screenshots. However, this does not provide any information on the source of the issue. We would require stack traces. I do not think there is anything in `createPeerConnection()` that could cause any sort of hang.

**Comment by Ryan45758** [comment]
I traced the stack, and a program created 5 stacks, each stack occupies 8188kb.
![1650888535420.jpg](https://user-images.githubusercontent.com/22660919/165088242-2f8be37c-330d-4880-820d-ed4558f1639f.jpg)
![1650888537611.jpg](https://user-images.githubusercontent.com/22660919/165088253-67c8a3c0-d215-41ac-8641-df5e9c8ea48a.jpg)

At the same time I also discovered when the program can be executed, the candidate does not seem to get srflx, only host, Is this because the stun connection is abnormal? 

I can successfully get srflx on ubuntu using the same program, but not normal on the embedded side, during testing, the network is all from the same source, I have also switched to a different network source, and he type of my NAT is symmetric.

ubuntu:
![1650794682559.jpg](https://user-images.githubusercontent.com/22660919/165089699-439231e5-f647-44f9-8f2f-6373dd8204d8.jpg)


embedded:
![1650794684152.jpg](https://user-images.githubusercontent.com/22660919/165089786-28c2a8da-9448-4cbb-8a02-d68ed1050b2e.jpg)

I have an idea now, could it be because the dhcp name of my device is unknown?
![1650855576729.jpg](https://user-images.githubusercontent.com/22660919/165089251-ef2d01eb-af49-4b99-baf7-7c52ba1a9908.jpg)
