### ISSUE TITLE
[BUG] Typo

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1461]
**Logging**
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

**Describe the bug**
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/ChannelInfo.c#L159
Copy the wrong member.

**SDK version number**
Include the SDK version you are running. If it is a specific commit on master branch, include that

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by niyatim23** [comment]
Hi @ycyang1229, thank you for pointing this out, do you want to submit a PR for this change?

**Comment by MushMal** [comment]
Wow. I am wondering whether this has been in place or had been introduced later. At any rate, I am surprised why there is no unit test coverage for this.

**Comment by ycyang1229** [comment]
@niyatim23 Please fix it and add the unit test. Thanks.

**Comment by disa6302** [comment]
Resolved in develop branch. Closing.
