### ISSUE TITLE
Failling to stream via Webrtc

### ISSUE THREAD

**Issue by ricamano** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1462]
I am able to start streaming yet nothing shows on the viewer or if it shows is just a white ball going around like it's loading. I'm streaming as a Master from a Raspberry Pi, and want to view it in the future in an android app, yet as of now, I'm using the AWS website and their web example to connect to the channels as a view.

`kvsWebrtcClientMaster` or `kvsWebrtcClientMasterGstSample` are both commands that I can run to start the stream, and they do work but as I said either the viewer can't connect or the stream shows a white ball like its a loading screen.

![failwebrtc1](https://user-images.githubusercontent.com/92892941/166934244-3ee23a82-4339-4558-970b-5477df626d0f.PNG)
In the first image, I ran `kvsWebrtcClientMasterGstSample` and the command line would be stuck in that last line, while the viewer couldn't connect to the channel/stream.

![failwebrtc2](https://user-images.githubusercontent.com/92892941/166935057-307afa11-2ebf-45ae-a8d2-cd2671c8b492.PNG)
On the second image, I would use `kvsWebrtcClientMaster`   and besides those error messages I would get:
handleStunPacket(): Cannot find candidate pair with local candidate xxx.xxx.x.xx and remote candidate xxx.xxx.x.xx. Dropping STUN binding success response
Note: Those xxx.xxx.x.xx were IPs, I'm assuming from the master and the viewer but not sure.

I can't find a solution so I'm hoping that someone here can help me out.

**Comment by niyatim23** [comment]
Hi @ricamano, if you see the white ball rolling around with a timer at the corner, then your sample is working fine. The error codes mean `0x5a000003 (STATUS_ICE_CANDIDATE_STRING_MISSING_IP)` and `0x5a000005 (STATUS_ICE_CANDIDATE_STRING_IS_TCP)`. You can safely ignore the stun packet messages as well.

Closing assuming answered, feel free to reopen in case of further questions
