### ISSUE TITLE
[QUESTION]Could KVS WebRTC SDK C support ICE-Lite mode

### ISSUE THREAD

**Issue by remainfox** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1466]
#### Could KVS WebRTC SDK C support ICE-Lite mode

if support, ` how to setup`,   thanks

**Comment by disa6302** [comment]
@remainfox , 

We do not support ICE-Lite and we do not have plans of supporting it at the moment. We will track this internally for future purposes and update this ticket when we have an update.
