### ISSUE TITLE
[BUG]kvsWebRTCClientMasterGstreamerSample dose't call gst_object_unref.

### ISSUE THREAD

**Issue by YOSI-yoshidayuji** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1470]
**Describe the bug**
In lines (190,191,291) of kvsWebRTCClientMasterGstreamerSample.c in the sample source, gst_object_unref is not called for the element obtained by gst_bin_get_by_name. Shouldn't it be called?

**SDK version number**
1.7.2

**Comment by disa6302** [comment]
We go to CleanUp if either are NULL. So no unref happens.
