### ISSUE TITLE
[BUG] Video is not streamed from master if viewer does not stream video back

### ISSUE THREAD

**Issue by idonahum1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1475]
Hi,

Use case:
Streaming video from IP camera using Webrtc C sdk as master to a web browser using Webrtc JS as viewer.

**Logging**
[logs.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/8754936/logs.txt)

**Describe the bug**
Video is not streamed from master if viewer does not stream video back.

**SDK version number**
Latest : v1.7.3

**To Reproduce**
- Use viewer JS example and set sendvideo=False flag in viewer.js
- Use master c example or gstmaster example to stream video into a browser.
- Check if video from master is working.

**Expected behavior**
When setting sendvideo= False in js viewer I expect that I only receive video from master (C sdk). But once I set this flag to false, or disabling the viewer camera, I cant get any video from master.

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chrome
 - Version 101.0.4951.41 (Official Build) (64-bit)

**Additional context**
Additionaly I tried to modify RTC_RTP_TRANSCEVER direction to SENDONLY in [PeerConnection.C](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/PeerConnection.c#:~:text=RTC_RTP_TRANSCEIVER_DIRECTION%20direction%20%3D%20RTC_RTP_TRANSCEIVER_DIRECTION_SENDRECV%3B), as well videoRtpTranseiver direction in [Common.C](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#:~:text=videoRtpTransceiverInit.direction%20%3D%20RTC_RTP_TRANSCEIVER_DIRECTION_SENDRECV%3B), nothing seem have effect.

Tried to modify [viewer.js](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/examples/viewer.js#:~:text=to%20be%20enabled.-,if%20(formValues.sendVideo%20%7C%7C%20formValues.sendAudio)%20%7B,)%3B,-//%20When%20trickle%20ICE)  based on this [PR](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/pull/50), doesnt seem to have effect either

I tried to follow other issues:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/81
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/148

On this issue -
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/468
I can understand that the modification I did are not needed, but still, if I set sendvideo = False on the viewer side, I still dont get any video at all.
Tried to debug myself but I couldnt figure if it is something with the C Sdk, JS Sdk, or it is just the browser itself.

Any ideas? 

Thanks.

**Comment by disa6302** [comment]
I see the error "0x5600000f" which suggests that the SDP size received exceeds  256 attributes as allowed by the SDK. Have you tried other browsers?

**Comment by idonahum1** [comment]
Hey, Thanks.
so after changing the viewer code based on this https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/pull/50
+ changing the brower to firefox everything seems to work fine. But I wonder why it wouldnt work with chrome? any ideas how to fix this?
Thanks.

**Comment by disa6302** [comment]
@idonahum1 , 

To confirm, does the JS SDK change make it work with Chrome as well?
It looks like the SDP generated by Chrome is large causing it to fail with the SDK. As a short term fix, you can modify [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47/src/source/Sdp/Sdp.h#L78) value to increase number of attributes the SDK can handle. 
However, we are still not sure why the size of the SDP is large or what the SDP contains. Can you increase the value and see if it gets through?
It would be useful to also run `export DEBUG_LOG_SDP=TRUE` when it works so that we can see what is causing the large SDP from Chrome.

**Comment by idonahum1** [comment]
@disa6302 

No, the JS change doesnt make it work with chrome.

It seems like the the value that was define in my SDK was 128 somehow, I change it to 256, and now with the JS change it also works with Chrome. 

Thank you!
