### ISSUE TITLE
[BUG] Mismatch of direction if audio and video have different directions

### ISSUE THREAD

**Issue by zzhang9999** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1479]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47/src/source/PeerConnection/SessionDescription.c#L537

The code goes through the remote media attribute and find the first if it matches one of the keyword "sendrecv" or "recvonly" or "sendonly".
When it receives an SDP offer which requires audio to be "sendrecv" and video to be "sendonly", it will send an SDP answer with both audio and video attribute to be sendonly.

**Comment by zzhang9999** [comment]
[sdp_offer_answer_failed.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/8766795/sdp_offer_answer_failed.txt)

**Comment by niyatim23** [comment]
Hi @zzhang9999, can you please share `VERBOSE` logs for us to understand the issue better?

**Comment by zzhang9999** [comment]
> Hi @zzhang9999, can you please share `VERBOSE` logs for us to understand the issue better?

Hi, I can not get the log from KvsWebrtcMasterClient side. Could you try to send the sdp offer list in the txt? It's very easy to reproduce.

**Comment by disa6302** [comment]
@zzhang9999 , 

Please send us the logs. We are unable to replicate the issue. VERBOSE logs would help the team in understanding the issue.

**Comment by zzhang9999** [comment]
I just tested the SDP in the latest code, it is already fixed. Thanks for response.
