### ISSUE TITLE
Properly create `disabled` and `sendonly` transceivers 

### ISSUE THREAD

**Issue by Sean-Der** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#148]
Currently we create all transceviers as `sendrecv` this breaks FireFox.

We should take the remote direction into account, and properly set. If we can't do that we may have to make a Javascript change.

**Comment by disa6302** [comment]
@Sean-Der , FYI, these are the SDPs I noticed while running WebRTC application in Firefox and Chrome. I observed these through the WebRTC internals.

[CHROME_SDP.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4183291/CHROME_SDP.txt)
[FIREFOX_SDP.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4183292/FIREFOX_SDP.txt)

**Comment by chehefen** [comment]
can be reproduced by running js sample in firefox 68.4.1esr. Doesnt work with master sample when only video is checked. works when audio video are both checked.

**Comment by disa6302** [comment]
Issue tracked in #468
