### ISSUE TITLE
[QUESTION] how to streaming live video and recorded video meanwhile

### ISSUE THREAD

**Issue by tim0755** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1485]
on my IP Camera device (whith video record to SD card support)
there is no problem for streaming live video,  two or more client to view the live video  work fine.(refer to kvsWebRTCClientMaster.c)

another case, one viewer requeset live video, but another viewer request one recorded video (belongs to yesterday for example), so the video source if deferent for two viewer.

how can I stream this two source video for two different viewer fairily?
only by one ClientMaster, or use two ClientMaster(use different channel name)?

thanks!

**Comment by disa6302** [comment]
1. WebRTC is a P2P communication methodology. This means our SDK does not support recording.
2. Our SDK supports a single master only config only

**Comment by tim0755** [comment]
> 1. WebRTC is a P2P communication methodology. This means our SDK does not support recording.
> 2. Our SDK supports a single master only config only

Thanks for you reply @disa6302 

sorry, the question is not clearness.
there is no need the SDK to record video.

for example, there are two video source on the IPCamera, one is live video from camera, and the other is the video recorded on the local SD card(like the 'h264SampleFrames' in the SDK).

can i streaming this two video meanwhile by the SDK?
(one master, two client, one viewer look the live video, the other viewer look the recorded video)
