### ISSUE TITLE
It was played half a year ago.　0x5600000f

### ISSUE THREAD

**Issue by hiroshifractal** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1486]
I ran the kvsWebrtcClientMasterGstSample.
It was played half a year ago.
It does not play even in the viewer in the AWS management console.
Return 0x5600000f
May I get suggestions on what might be wrong?
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/8833153/log.txt)

**Comment by disa6302** [comment]
Please update to SDK to 1.7.3 and your issue will be resolved

**Comment by hiroshifractal** [comment]
Thank you.
I try it.

**Comment by hiroshifractal** [comment]
I try update. But I get the following error
[log2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/8836827/log2.txt)

**Comment by disa6302** [comment]
The get endpoint call seems to be failing. Make sure your network is working and you run the sample as is to see if it works before you make changes

**Comment by hiroshifractal** [comment]
I'm using wwan0 on RaspberryPi, and it's connected to the internet.
Do I need to change the sample program when using wwan0?
