### ISSUE TITLE
Do I need to change the sample program when using wwan0?

### ISSUE THREAD

**Issue by hiroshifractal** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1488]
I updated the SDK with the following ISSUE, but I got the attached error.
I'm using wwan0 on RaspberryPi, and it's connected to the internet.
Do I need to change the sample program when using wwan0?

_Originally posted by @hiroshifractal in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1486#issuecomment-1146712277_

**Comment by hiroshifractal** [comment]
[log2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/8849052/log2.txt)

**Comment by jdelapla** [comment]
I'm not sure what you mean by "change", but the error we're seeing 0x5d000015
`#define STATUS_SIGNALING_LWS_CLIENT_CONNECT_FAILED                 STATUS_SIGNALING_BASE + 0x00000015`
means LWS couldn't connect. Most likely a networking issue, please make sure you're connected to the network.

**Comment by hiroshifractal** [comment]
@jdelapla 
Thank you for your answer.  
What is the network?  Other aws services are connecting without any problems.
