### ISSUE TITLE
[QUESTION] Viewer continue start/stop serval time will enter "Current local state retry state" forever

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1491]
We try to let viewer continue start/stop serval times and master will enter "Current local state retry state" forever , restart program will fix it until program happen again.
Please help to let us know the reason and how to fix it, thanks.

**SDK version: v1.7.2**

**Platform: MIPS**
Board: IPCAM RTS3904 CPU: 500M :rx5281 prid=0xdc02
force spi nor mode
DRAM:  128 MiB @ 1066 MHz
Image Name:   linux_4.9.145

**Logging** 
[aws_client1.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/8875452/aws_client1.log)

**Comment by niyatim23** [comment]
Hi @henryChmn, can you try using SDK v1.7.3 and let us know if the issue persists?

**Comment by disa6302** [comment]
Closing due to no response.
