### ISSUE TITLE
Reliability Testing : Master does not connect to viewer after a day or two.

### ISSUE THREAD

**Issue by sauravkumar-volt** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1493]
Hello,
I am streaming 50 cameras to KVS webrtc from a Server Rack. Initially, for 18- 24 hours, the streaming works fine. But over time, eventually master does not connect to the viewer. I have to restart the webrtc binaries to fix the issue.
Is there a way to test the reliability of the webrtc with a higher number of cameras?

**Comment by jdelapla** [comment]
What version are you running? I'm going to recommend updating to 1.7.3 if you're not on it yet.
