### ISSUE TITLE
[QUESTION] config the time of audio data

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1494]
Currently, we are using A-law audio format, and master receive audio frames from viewer that 160 bytes length, and it is 20ms of audio data.
Can we config the time of audio data that audio come from viewer and is possible to config it to 64ms of audio data?
If we can, how should we config it? 
Thanks.

**Comment by jdelapla** [comment]
webrtc-sdk-c/samples Samples.h   
` 24 #define SAMPLE_AUDIO_FRAME_DURATION (20 * HUNDREDS_OF_NANOS_IN_A_MILLISECOND)`

**Comment by henryChmn** [comment]
Hi @jdelapla,

Thanks for your reply,
Does SAMPLE_AUDIO_FRAME_DURATION  need apply both master and viewer?
Currently, I have one IPCAM supported 60ms of audio data and another one supported 64ms of audio data,
how can I config viewer time of audio data for these two IPCAM with different time of audio data?
