### ISSUE TITLE
[QUESTION] kvs stream sometimes freezes and gets choppy after a few days of running and bitrate spikes to 100Mbps.

### ISSUE THREAD

**Issue by david511** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1499]
When I have the kvs stream running for a day or two (sometimes longer) the stream will occasionally start to freeze and get choppy. The only weird thing that I have noticed that is different after a few days is the bitrate spikes and sits at around 50-100 Mbps.

When the stream is working fine the bitrate sits around 1-6 Mbps. I have my h264 video encoder configured to 2 Mbps. I also have the encoder set to the baseline profile as well as in the sdp message "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f".

I tried adding in the max bandwidth attribute (b=AS:2000) to my SDP message which gets created in the kvs c library but that didn't do anything.

Does anyone have any ideas on why the stream output might randomly start to freeze and get choppy?
Is there anyway to cap the webrtc bandwidth in the kvs library or in the SDP message to help prevent this bitrate spike?

Happy to provide addition information if needed.

Version: kvs webrtc c sdk v1.6.0.

**Comment by david511** [comment]
You can see here the outgoing bitrate is 80 Mpbs:
[debug] 2022-06-15 21:41:11.768022 kvs: getIceCandidatePairStatsCallback(): Selected remote candidate ID: AO2xlAGEk
[debug] 2022-06-15 21:41:11.768025 kvs: getIceCandidatePairStatsCallback(): Ice Candidate Pair state: 3
[debug] 2022-06-15 21:41:11.768028 kvs: getIceCandidatePairStatsCallback(): Nomination state: nominated
[debug] 2022-06-15 21:41:11.768031 kvs: getIceCandidatePairStatsCallback(): Packet send rate: 8343.022727 pkts/sec
[debug] 2022-06-15 21:41:11.768034 kvs: getIceCandidatePairStatsCallback(): Packet receive rate: 42.886364 pkts/sec
[debug] 2022-06-15 21:41:11.768038 kvs: getIceCandidatePairStatsCallback(): Outgoing bit rate: 79894673.818182 bps
[debug] 2022-06-15 21:41:11.768041 kvs: getIceCandidatePairStatsCallback(): Incoming bit rate: 88003.818182 bps
[debug] 2022-06-15 21:41:11.768044 kvs: getIceCandidatePairStatsCallback(): Packet discard rate: 0.000000 pkts/sec
[debug] 2022-06-15 21:41:11.768048 kvs: getIceCandidatePairStatsCallback(): Current STUN request round trip time: 0.033413 sec
[debug] 2022-06-15 21:41:11.768050 kvs: getIceCandidatePairStatsCallback(): Number of STUN responses received: 1

Also to note, when the stream starts getting choppy and the bitrate spikes there is a lot of packet loss and almost no frames get decoded.

**Comment by niyatim23** [comment]
Hi @david511, not sure what could be causing the freeze. I would suggest you to move to v1.7.3 as a number of bug fixes and improvements have gone in since v1.6.0. Please try it out and let us know if the issue persists

**Comment by david511** [comment]
Thanks for the reply back. I will try and upgrade the library however I did have a few follow up questions:

1) Is it normal for a webrtc stream to consume a lot of bandwidth for the first 5-60 seconds when starting to stream the video after a peer-to-peer connection has been established? For example: say my video encoder was configured for 2 Mbps with a baseline h264 profile, sometimes on start up for the first 10-60 seconds the bitrate goes up to 20-60 Mbps (and the video is sometimes choppy). Then the bitrate will drop down to 1-5 Mbps (video appears normal again) . Is this somewhat typical?

You can see in this picture the bitrate starts at 40 Mbps then drops to around 5 Mbps:
![normal-bitrate](https://user-images.githubusercontent.com/55361568/174395157-39ec4d3e-844f-4f6d-9c66-2c8a0a76c58b.PNG)

However there are some cases where the stream starts at 5Mbps then drops down to 2 Mbps:
![bitrate-started-5mpbs](https://user-images.githubusercontent.com/55361568/174396698-5ede73cc-4607-47bb-b6e9-0f95d8bf83d1.PNG)

2) I had a case where I started a stream and the bitrate was sitting at 30-40 Mpbs on average and the bitrate never dropped down to 1-5 Mpbs like it normally does. Is there anyway to regulate the bandwidth so on start up it doesn't spike to 30-40 Mpbs or is there a way to set the average bandwidth for a stream?

Refer to this picture to see the behavior I was experiencing:
![freeze-issue-high-bitrate](https://user-images.githubusercontent.com/55361568/174396612-6325ae7c-a9f4-457b-ae1a-f6fa0abb5703.PNG)

**Comment by disa6302** [comment]
Hmm. Nothing I can think of within the SDK that could cause this. Unless there are major network fluctuations.

**Comment by niyatim23** [comment]
Closing since the issue has gone stale. Feel free to reopen in case of further questions / issues
