### ISSUE TITLE
[QUESTION] Having issue with Starting stream through my Laptop camera

### ISSUE THREAD

**Issue by faisalapp1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1500]
Currently i am working on WebRTC sdk for C to live stream from my Laptop camera to Kinesis but issue what i am facing is,I am not able to start stream from my Camera. By reading out the Documentation only samples are being streamed to my Kinesis Channel. Though I have achieved this through C++ Producer but I am going to use WebRTC for now.

**Comment by niyatim23** [comment]
Hi @faisalapp1, what is your master and your viewer? Does your viewer have permissions to access the microphone and camera of your laptop?

**Comment by niyatim23** [comment]
Can you please help me with the answers to the following:
1. What is the version of your SDK?
2. Have you referred to all the instructions on the readme [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c) to build and make?
3. Are you able to build and make the SDK successfully?
4. Are you using the sample application from the SDK? If yes, which sample application are you using?

**Comment by niyatim23** [comment]
The kvsWebrtcClientMasterGstSample uses camera as a source. You do need to provide permissions to access your camera Not sure what is blocking you. Can you please share verbose logs showing the error? Also, are you using an ec2 instance to run your master? Because in that case, it would not have access to your camera

**Comment by faisalapp1** [comment]
No i am not using any EC2 in between. I just want to send stream from laptop cam to kinesis signaling channel that's it. I am stuck at either i running WebRTC right or not because in documentation it is not written how can we send our on stream to master on kinesis, in docs its only about the samples which present in directory and only those are being streamed till yet.

**Comment by faisalapp1** [comment]
Issue resolved.Did some amendments in kvsWebrtcClientMasterGstSample.c code.

**Comment by Ramnirmal0** [comment]
@faisalapp1 i am also facing same issue. could you please help me by sharing how you have resolved it .
