### ISSUE TITLE
[BUG] Sometimes Viewer cannot receive SDP_ANSWER. Then Master returns timeout for respondWithAnswer() 

### ISSUE THREAD

**Issue by EunseongBoo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1503]
**Logging**
I attached two error logs and a normal log for the master. In the error log, even if the master sends SDP answer to viewer, viewer cannot receive answer. Therefore, the timeout errors are occured in the master node. 

> ERROR   respondWithAnswer(): operation returned status code: 0x0000000f

![image](https://user-images.githubusercontent.com/20852734/175226997-b8d44b70-a48e-4b33-b4ae-d1a9a221c2ec.png)

**Describe the bug**
I have ported the gstreamer master to an rk1126 rockchip embedded board (wifi). When chrome viewer connects to master, sometimes the viewer cannot receive the sdp answer from the master node. There is no response because the viewer did not receive the sdp answer, and a timeout occurs for the sdp_answer response in the master. This error occurs once out of 6, and the connection between the viewer and the master fails. This also happens when the viewer is Android. 

**SDK version number**
Master: kvs-webrtc-c library v1.7.3 (Gstreamer-master example)
Viewer: Chrome kvs-webrtc-js example (https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html)

**Additional context**
The errors are only occur in the our rockchip board. This problem did not occur when I ran the master example in vmware in the same network environment (connected wirelessly to the same AP). 

Is there any solution when I get sdp response timeout error? Is there a mechanism to resend the sdp answer? I attached two error logs and a normal log for the master

[SDP_ANSWER_ERROR_LOG2_v1.7.3.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/8964573/SDP_ANSWER_ERROR_LOG2_v1.7.3.txt)
[SDP_ANSWER_ERROR_LOG_v1.7.3.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/8964574/SDP_ANSWER_ERROR_LOG_v1.7.3.txt)
[SDP_ANSWER_NORMAL_LOG_v1.7.3.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/8964575/SDP_ANSWER_NORMAL_LOG_v1.7.3.txt)

**Comment by EunseongBoo** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47/samples/Common.c#L220

I changed this line like this to resend sdp answer when timeout error occurs:

`        
if(respondWithAnswer(pSampleStreamingSession) != STATUS_SUCCESS) {
          CHK_STATUS(respondWithAnswer(pSampleStreamingSession));};`

Resending the sdp answer after this change solved the problem. However, the fundamental problem is that the viewer does not receive it when transmitting the first sdp answer, and delay until timeout occurs even if retransmission is performed. Why is this happening?

**Comment by disa6302** [comment]
It could be a network drop issue. 
Resending the answer as you mentioned would help.

**Comment by EunseongBoo** [comment]
> It could be a network drop issue. Resending the answer as you mentioned would help.

There are two points that I do not understand as a network drop issue
1. PC Master (wifi) - Viewer, works well in the same network (AP)
2. Android viewer does not receive SDP ANSWER much more frequently than web viewer.

**Comment by disa6302** [comment]
Is your Android device and the web viewer in different network configurations?
