### ISSUE TITLE
[QUESTION] Which ports should be open to allow STUN/TURN or only TURN?

### ISSUE THREAD

**Issue by idonahum1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1506]
Hello,

I have a master application behind a NAT, the viewer connects from a different NAT (the streaming is not local).

I try to white list the outbound ip addresses and ports to allow video streaming in my router firewall, I want the list to be smallest as possible, but I cant find the right "formula" to do it. 

I tried to white list all destination addresses on port 443 (like specified in the documentation). But I cant see any video in the viewer side. I assumed that if I open all addresses on port 443 and block all the other, it will force the connection to use turn, but even then the video does not appear on the viewer side.
 
Some logging: 
when blocking everything but port 443:

```Denied | Source: 192.168.0.120  | Dest: 54.144.228.102 | Protocol: UDP | Source Port: 37142 | Dest Port: 59520```

From AWS Webrtc demo page you can see that the destination ip is the turn server, but surprisingly the port is not 443. 

```    "urls": [
      "turn:54-144-228-102.#.kinesisvideo.us-east-1.amazonaws.com:443?transport=udp",
      "turns:54-144-228-102.#.kinesisvideo.us-east-1.amazonaws.com:443?transport=udp",
      "turns:54-144-228-102.#.kinesisvideo.us-east-1.amazonaws.com:443?transport=tcp"
    ]
```

when I white list every port in range 49152 to 65535 :

```Allowed | Source: 192.168.0.120 | Dest: 18.208.168.84  | Protocol: UDP | Source Port: 56822 | Dest port: 64855```

Maybe I am missing something, but I though that TURN should always use port 443 since its the point in cloud relaying, that you know your endpoint, No?

Thanks in advance.

**Comment by TalKlinger** [comment]
According to the design, the ICE candidates are randomly assigned from the dynamic/private (ephemeral) port range.
So it would be missing the point of the process that searches for open ports within the range, by cherry-picking a port on your side :grin: 

You can try by adding to the allowed list a range of ~100 ports in the ephemeral range (49152–65535) just to verify this.

**Comment by disa6302** [comment]
As @TalKlinger said, local ports are arbitrary. I would suggest running some tests to understand the ports being used locally. TURN uses 443. Your snippet with URLS also suggest the same. Closing this ticket assuming answered.
