### ISSUE TITLE
[QUESTION]: how can master close ongoing viewer connection 

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1507]
I am using latest SDK 1.7.3.

If master want to close the ongoing viewer connection. How master will close forcefully viewer connection. In following scenarios: 
- When viewer connection state on master is connected?
- When viewer connection on master is connecting?
- When on master signaling message received and in between user close an APP and retry again to connect with master. 
   for above scenario my master return from this:
   https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L1268

   and its failed for ongoing process.

Because currently master done basis of callback "onConnectionStateChange" return a state .

**Comment by niyatim23** [comment]
Hi @shiv50084, apologies for the delayed response. Have you tried using the following API: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1673
