### ISSUE TITLE
[QUESTION]: Facing an issue when trying to reconnect again when previous connection is not closed properly from same peer

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1508]
I am using SDK 1.7.3.

In last log file kvsFileLog.6.txt when master get connected to viewer on line number 36 but immediately viewer exit from live streaming. Master didn't received close/ disconnected status immediately when viewer exit from live streaming.

master received disconnected after more than 2 minutes . you can see in log file "remaining device log.txt" at line number 412.

I have also attached APP log file (name CloseIssue.txt) as well.

Can you please help to see this issue ?

[remaining device log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9002393/remaining.device.log.txt)
[CloseIssue.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9002394/CloseIssue.txt)

[kvsFileLog.3.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9002278/kvsFileLog.3.txt)
[kvsFileLog.4.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9002279/kvsFileLog.4.txt)
[kvsFileLog.5.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9002280/kvsFileLog.5.txt)
[kvsFileLog.6.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9002281/kvsFileLog.6.txt)
:
[kvsFileLogIndex.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9002282/kvsFileLogIndex.txt)
 
[kvsFileLog.2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9002283/kvsFileLog.2.txt)

**Comment by kateyanurag** [comment]
Hi @shiv50084 - Is this issue consistently reproducible? If yes, can you share the setup/repro steps?

**Comment by shiv50084** [comment]
@kateyanurag 
in our scenario Master (camera) is always connected and viewer (APP) is start connecting only when user press start live streaming. 
and immediately user exit from live streaming page without proper connection between master and viewer. So, app close all its instance when its coming of out of live streaming. While its previous connection in connecting state. This process always happen. Then master close that connection when its timeout.


and what steps i mentioned above in first chat its occur 1 time out of 10. but process is same as mentioned but right now master in connected state and viewer exit immediately and close all its instance/object.
