### ISSUE TITLE
[QUESTION]: What timeout is there in SDK for ICE agent inactivity?

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1509]
in SDK version 1.7.3.

Take a scenario where viewer coming to master for new connection and in between viewer exit immediately but on master new connection request is came. Master having current state  is connecting.

Then after how much time master will take to cleanup previous viewer request. Which is connecting on master.

As i seen here:  
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1047#issuecomment-762644540

@MushMal written its 2 seconds in above attached link:
"The ICE agent is triggering disconnect in the ICE state machine on inactivity after 2 seconds defined here:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.h#L30"

But its actually 30 seconds:

#define KVS_ICE_SEND_KEEP_ALIVE_INTERVAL                       (15 * HUNDREDS_OF_NANOS_IN_A_SECOND)
#define KVS_ICE_ENTER_STATE_DISCONNECTION_GRACE_PERIOD (2 * KVS_ICE_SEND_KEEP_ALIVE_INTERVAL)

Can you please clarify. What exact timeout should be?

**Comment by jdelapla** [comment]
I think @MushMal was simply mistaken, the definition on line 30 is clearly 30 seconds.
