### ISSUE TITLE
[QUESTION] Stop transmission pipeline

### ISSUE THREAD

**Issue by diegocatalao** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1513]
Hello folks. I would like to stop the kvs pipeline transmission. It's possible?

I tried these functions but they wait for the queue to send everything that is allocated:

- stopKinesisVideoStream
- stopKinesisVideoStreams
- stopKinesisVideoStreamSync

**Comment by MushMal** [comment]
stopKinesisVideoStream kicks off a process of stopping a stream asynchronously. It will call a streamStopped callback on success or the error function. stopKinesisVideoStreams will do that for all of the streams. The Sync is the sync version of the function. All of these will attempt to empty the buffer and get the final persisted ACK before the stop timeout.

If you just need to dump the buffer and stop immediately, you could simply free the stream and re-create. A faster method is to resetKinesisVideoStream.

**Comment by diegocatalao** [comment]
Can I call kinesisVideoStreamResetStream after I have called stopKinesisVideoStreamSync? I did a test here and it didn't stop the stream

**Comment by MushMal** [comment]
The sync call will block so I am not sure how you can call reset. If you really need to dump the stream's buffered content (on the SDK side) then you don't need to call stopKinesisVideoStreamSync. You can simply call kinesisVideoStreamReset. If, however, you need to do a last attempt to send the data but the timeout is too big you have two options.

1) You can use the stopKinesisVideoStreamSync (blocking) and configure the stop stream timeout in the StreamInfo.ClientData (if I remember it correctly).
2) You can use stopKinesisVideoStream (the async version) and if by the time your timeout is hit and the streamStopped callback is not called, you can proceed with resetting the stream.

The 2nd version while async, requires thread coordination which might not be what you need. Just go with the first option if you need to last chance attempt to stream the data.

**Comment by diegocatalao** [comment]
Its works fine! Thanks!

**Comment by MushMal** [comment]
The most basic method is to call the metrics API and get the duration/size: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L2189 and check https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L1271 for example. 

You can configure the timeout here: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L1154

BTW, this issue is cut against the WebRTC repository but it should belong to the KVS SDK repo

**Comment by diegocatalao** [comment]
@MushMal

Thanks for answering. Worked perfectly!

Below is an example of how I got this information:

`
  STATUS retStatus = STATUS_SUCCESS;
  StreamMetrics streamMetrics;

  MEMSET(&streamMetrics, 0x00, SIZEOF(StreamMetrics));
  CHK_STATUS(getKinesisVideoStreamMetrics(streamHandle, &streamMetrics));

  printf("version: %d\n", streamMetrics.version);
  printf("currentViewDuration: %d\n", streamMetrics.currentViewDuration);
  printf("overallViewDuration: %lld\n", streamMetrics.overallViewDuration);
`
