### ISSUE TITLE
[QUESTION] turn ip addresses range

### ISSUE THREAD

**Issue by idonahum1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1518]
Hi,

I have a situation where a costumer has very strict network, which does not allow outbound traffic if the ip_address: port is not static. Its also does not allow white listing traffic by DNS - so the examples provided in the repository (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#outbound-hostname-and-port-requirements) cant be used.
But, the costumer allows a range of static ips:port , so my question is:

Assuming turn is used, and the port is 443, what is the valid range of turn servers ips (in order to white list them) ? Is it a known value for a specific region?
In case the turn server ip is random and differs between session to session, is there a way to make a static ip for the turn server using VPC or something similar?

Thanks.

**Comment by disa6302** [comment]
@idonahum1 , 

Currently, there is no way to provide ip ranges for TURN server and we cannot provide a static IP for TURN server either.
