### ISSUE TITLE
[QUESTION] IceRestart option in SDP offer

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1528]
While the viewer tries to connect to the master, there is an ICE negotiation phase, where the peers choose the best suited ICE servers for communication. Sometimes this negotiation fails and it generates a ICE Connection Failed state.

To fix this, the viewer could send a new offer with the  IceRestart constraint whenever this state is reached.

Question:  Is the IceRestart option supported by the SDK?
If yes, how does it work?
Is the above method the right way of retrying ice connection?

**Comment by jdelapla** [comment]
Certainly the above method can work for restarting a connection. The way to do is as you stated, have the viewer send another SDP offer, which can absolutely be done with the current SDK features.
