### ISSUE TITLE
[QUESTION]where is the inputsource

### ISSUE THREAD

**Issue by xiaoyaodingchunqiu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1529]
mples$ ./kvsWebrtcClientMasterGstSample 0727hytest0-for-webrtc
[KVS GStreamer Master] Using trickleICE by default
[KVS GStreamer Master] Created signaling channel 0727hytest0-for-webrtc
[KVS Gstreamer Master] Finished initializing GStreamer
[KVS Gstreamer Master] Streaming video only
[KVS GStreamer Master] streaming type video-only[KVS GStreamer Master] KVS WebRTC initialization completed successfully
[2022/07/29 14:18:30:9026] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2022/07/29 14:18:30:9026] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2022/07/29 14:18:30:9027] N:  ++ [wsi|0|pipe] (1)
[2022/07/29 14:18:30:9027] N:  ++ [vh|0|netlink] (1)
[2022/07/29 14:18:30:9027] N:  ++ [vh|1|default||-1] (2)
[KVS GStreamer Master] Signaling client created successfully
[2022/07/29 14:18:30:9030] N:  ++ [wsicli|0|POST/h1/r-93960ca9.kinesisvideo.us-west-2.amazonaws.] (1)
[2022/07/29 14:18:32:9573] N:  -- [wsicli|0|POST/h1/r-93960ca9.kinesisvideo.us-west-2.amazonaws.] (0) 2.054s
[2022/07/29 14:18:32:9575] N:  ++ [wsicli|1|WS/h1/m-11e07cd0.kinesisvideo.us-west-2.amazonaws.co] (1)
[KVS GStreamer Master] Signaling client connection to socket established
[KVS Gstreamer Master] Beginning streaming...check the stream over channel 0727hytest0-for-webrtc

![image](https://user-images.githubusercontent.com/92872460/181695870-4ee2a2e4-5aff-42c9-9548-5b2099525ba2.png)

the signaling client connect to socket is established, but i can't see the video in test web
the connect success control panel only show the viewer connect
whether it only means test web's connect success??
how can i get the video?
the camera in my laptop isn't work

**Comment by disa6302** [comment]
You ned frames from your camera. If you are just looking to test working with some sample frames, you can run this app: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c

If you are looking to use GStreamer, then run kvsWebrtcClientMasterGstSample with test source input. You can pass `testsrc` in the command line arguments.

**Comment by xiaoyaodingchunqiu** [comment]
> You ned frames from your camera. If you are just looking to test working with some sample frames, you can run this app: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c
> 
> If you are looking to use GStreamer, then run kvsWebrtcClientMasterGstSample with test source input. You can pass `testsrc` in the command line arguments.
![image](https://user-images.githubusercontent.com/92872460/181915294-cc380058-36d7-4557-bda1-68cddba03689.png)
![image](https://user-images.githubusercontent.com/92872460/181915339-f82f8d86-ecc3-41bc-9ee0-ac69d46eab22.png)

the camera in my laptop still donesn't work
and the test page still have no video stream
i just want to know how to let the app use my laptop's camera, as a input video stream

**Comment by xiaoyaodingchunqiu** [comment]
![image](https://user-images.githubusercontent.com/92872460/181915548-4b26851b-a906-4935-870c-db013877a43a.png)
change the command either did not work

**Comment by xiaoyaodingchunqiu** [comment]
> You ned frames from your camera. If you are just looking to test working with some sample frames, you can run this app: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c
> 
> If you are looking to use GStreamer, then run kvsWebrtcClientMasterGstSample with test source input. You can pass `testsrc` in the command line arguments.

can you reopen it?

**Comment by disa6302** [comment]
@xiaoyaodingchunqiu ,
The question is GStreamer specific and you would have to first ensure your pipeline is working. Please construct a working GStreamer pipeline without using webrtc first to ensure you are getting frames. You can use autovideosink to test out your pipeline before using our sample application.

Also, try to run the sample without any changes to see if it works. autovideosrc takes video from laptop camera as well.

**Comment by xiaoyaodingchunqiu** [comment]
> @xiaoyaodingchunqiu , The question is GStreamer specific and you would have to first ensure your pipeline is working. Please construct a working GStreamer pipeline without using webrtc first to ensure you are getting frames. You can use autovideosink to test out your pipeline before using our sample application.
> 
> Also, try to run the sample without any changes to see if it works. autovideosrc takes video from laptop camera as well.

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp
I can run through this producer code，and see my camera's video stream in console
which means gstream and pipeline is ok
the problem is how to let webRTC use camera video stream

**Comment by xiaoyaodingchunqiu** [comment]
> @xiaoyaodingchunqiu , The question is GStreamer specific and you would have to first ensure your pipeline is working. Please construct a working GStreamer pipeline without using webrtc first to ensure you are getting frames. You can use autovideosink to test out your pipeline before using our sample application.
> 
> Also, try to run the sample without any changes to see if it works. autovideosrc takes video from laptop camera as well.
![image](https://user-images.githubusercontent.com/92872460/182067291-6ee86c05-549e-4eac-8f1e-0a0e084e279c.png)

~/kvs/amazon-kinesis-video-streams-webrtc-sdk-c/build$ ./samples/kvsWebrtcClientMasterGstSample 0801-hytest-webrtc-pipeline video-only testsrc
hi, man
this command line works, and can see this video
but when i use "./samples/kvsWebrtcClientMasterGstSample 0801-hytest-webrtc-pipeline video-only /dev/video0", it dosen't work. what the command should i add?

**Comment by xiaoyaodingchunqiu** [comment]
> > @xiaoyaodingchunqiu , The question is GStreamer specific and you would have to first ensure your pipeline is working. Please construct a working GStreamer pipeline without using webrtc first to ensure you are getting frames. You can use autovideosink to test out your pipeline before using our sample application.
> > Also, try to run the sample without any changes to see if it works. autovideosrc takes video from laptop camera as well.
> > ![image](https://user-images.githubusercontent.com/92872460/182067291-6ee86c05-549e-4eac-8f1e-0a0e084e279c.png)
> 
> ~/kvs/amazon-kinesis-video-streams-webrtc-sdk-c/build$ ./samples/kvsWebrtcClientMasterGstSample 0801-hytest-webrtc-pipeline video-only testsrc hi, man this command line works, and can see this video but when i use "./samples/kvsWebrtcClientMasterGstSample 0801-hytest-webrtc-pipeline video-only /dev/video0", it dosen't work. what the command should i add?
![image](https://user-images.githubusercontent.com/92872460/182113825-b49703e6-21b5-4a0e-b6eb-b36cf9a08236.png)
![image](https://user-images.githubusercontent.com/92872460/182113885-003a5911-8253-4590-88a5-f7266e574d2f.png)

Change it or not, it doesn't work.
This is so torturous

**Comment by disa6302** [comment]
Can you attach WebRTC logs please? Run `export AWS_KVS_LOG_LEVEL=VERBOSE` and `export DEBUG_LOG_SDP=TRUE` before running your application. Also include details on if you are using autovideosrc or something else. Thank you.

**Comment by xiaoyaodingchunqiu** [comment]
> 
![image](https://user-images.githubusercontent.com/92872460/182269038-99066a9c-59e3-4f45-a4e4-73e50908cec4.png)

https://github.com/dusty-nv/jetson-inference/issues/461
it works when i change the width and high, the same problem as in the link above
i think there may need some notes for laptop
by the way, it also work when i change to use autovideosrc
