### ISSUE TITLE
[QUESTION]Where RTCP Packet Sent?

### ISSUE THREAD

**Issue by wangchyz** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1530]
In onRtcpPacket code, I see some rtcp packet type was recieved and handled, like RTCP_PACKET_TYPE_FIR、 RTCP_PACKET_TYPE_GENERIC_RTP_FEEDBACK、RTCP_PACKET_TYPE_PAYLOAD_SPECIFIC_FEEDBACK、RTCP_PACKET_TYPE_SENDER_REPORT、RTCP_PACKET_TYPE_RECEIVER_REPORT、RTCP_PACKET_TYPE_SOURCE_DESCRIPTION

But I only found RTCP_PACKET_TYPE_SENDER_REPORT packet sent in code,  where is other RTCP packet sent code?

**Comment by disa6302** [comment]
We react to RTCP packet types, but do not have the sending capability. Tracking in feature request here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1521
