### ISSUE TITLE
[QUESTION] Compile error

### ISSUE THREAD

**Issue by osharena** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1534]
Hi.

I have problem while compiling sdk itself.

The compile error is occuring in line 20 and 21 of [amazon-kinesis-video-streams-webrtc-sdk-c/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h]

#include <com/amazonaws/kinesis/video/client/Include.h>
#include <com/amazonaws/kinesis/video/common/Include.h>

not being able to find those headers.

Actually, there isn't any directory like [com/amazonaws/kinesis/video/client/] and [com/amazonaws/kinesis/video/common/] under [amazon-kinesis-video-streams-webrtc-sdk-c/src/include/] while there is only a directory [com/amazonaws/kinesis/video/webrtcclient/] in it.

Could you give me a hint how I can resolve the problem?

Thanks.

**Comment by disa6302** [comment]
@osharena ,

How are you compiling the SDK? Are you using this as a dependency or following the README to build it?

**Comment by osharena** [comment]
@disa6302 

I'm trying to build it on our linux build system.
Of course, I've already read README but can't find any part in it which explains the absence of those files.
By any chance, could you teach me which part in README is related to the problem?

There must not be any problem while you build it. But I'm just wonder how your build is ok regardless of the obvious absence of those two files.
