### ISSUE TITLE
Attempting to Run kvsWebrtcClientMasterGstSample using IoT Core Certificate

### ISSUE THREAD

**Issue by antoineaws** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1535]
Team,
I am trying to run this sample using IoT core certificate instead of using AWS AccessKeyId and Secret. When using an access key and secret it works well, all dependencies are installed and stream works well.

The command that I am using is as follows:
`AWS_IOT_CORE_THING_NAME=MyThing AWS_IOT_CORE_CREDENTIAL_ENDPOINT=xxxx-ats.credentials.iot.ca-central-1.amazonaws.com  AWS_DEFAULT_REGION=ca-central-1 AWS_IOT_CORE_CERT=certs/device-certificate.pem.crt AWS_IOT_CORE_PRIVATE_KEY=certs/private.pem.key AWS_IOT_CORE_ROLE_ALIAS=thing-role-alias ./kvsWebrtcClientMasterGstSample SignalingChannel
`

Error being generated from the above log is below. Could it be the role-alias? Any help would be greatly appreciated.

Thank you!

** Logging ** 
Logs from running the above command:
```
[KVS GStreamer Master] createSampleConfiguration(): operation returned status code: 0x15000027 
[KVS GStreamer Master] Terminated with status code 0x15000027[KVS GStreamer Master] Cleaning up....
```

**Comment by antoineaws** [comment]
I figured it out. the AWS_IOT_CORE_CREDENTIAL_ENDPOINT was wrong, to get the AWS_IOT_CORE_CREDENTIAL_ENDPOINT, execute this command first: `aws iot describe-endpoint --endpoint-type iot\:CredentialProvider --output text --profile your_profile_name`.

Full command would be: 
`AWS_IOT_CORE_THING_NAME=MyThing AWS_IOT_CORE_CREDENTIAL_ENDPOINT=xxxx.credentials.iot.ca-central-1.amazonaws.com AWS_DEFAULT_REGION=ca-central-1 AWS_IOT_CORE_CERT=certs/device-certificate.pem.crt AWS_IOT_CORE_PRIVATE_KEY=certs/private.pem.key AWS_IOT_CORE_ROLE_ALIAS=thing-role-alias ./kvsWebrtcClientMasterGstSample SignalingChannel`

However, I found a strange recommendation, why does the channel name has to be the same as the IoT Thing name? Why can't we have them as separate?

**Comment by rmncardoso** [comment]
Thanks! Had exactly same issue yesterday.. It works now, after putting the right AWS_IOT_CORE_CREDENTIAL_ENDPOINT.

About the channel name... having the same name as the IoT Thing can be enforced by IAM policy attached to the role used by the Thing: 

    "Effect": "Allow",
            "Action": [
                "kinesisvideo:DescribeSignalingChannel",
                "kinesisvideo:CreateSignalingChannel",
                "kinesisvideo:GetSignalingChannelEndpoint",
                "kinesisvideo:GetIceServerConfig"
            ],
            "Resource": "arn:aws:kinesisvideo:*:*:channel/${credentials-iot:ThingName}/*"
        }

This assures that different Things cannot stream to the same channel...  Assuming that role is used by  several IoT Things.. 
That's the reason for the recommendation.. I think...  you can have different names for Thing/Channel if that fits your use case

**Comment by antoineaws** [comment]
@disa6302 It does not work. In the C program `kvsWebRTCClientMasterGstreamerSample.c` in samples, line 350, the pchannelName is being set to the IOT_CORE_THING_NAME. We should rather grab it from the args being passed in. Can you please re-open? 

```
#ifdef IOT_CORE_ENABLE_CREDENTIALS
    CHK_ERR((pChannelName = getenv(IOT_CORE_THING_NAME)) != NULL, STATUS_INVALID_OPERATION, "AWS_IOT_CORE_THING_NAME must be set");
#else
    pChannelName = argc > 1 ? argv[1] : SAMPLE_CHANNEL_NAME;
#endif
```

**Comment by disa6302** [comment]
@antoineaws ,

Can you add details on the error you see?

**Comment by antoineaws** [comment]
It doesn't throw an error. When we run this command:
`AWS_IOT_CORE_THING_NAME=AWSRobotPi AWS_IOT_CORE_CREDENTIAL_ENDPOINT=xyz.credentials.iot.ca-central-1.amazonaws.com AWS_DEFAULT_REGION=ca-central-1 AWS_IOT_CORE_CERT=certificate.pem.crt AWS_IOT_CORE_PRIVATE_KEY=private.pem.key AWS_IOT_CORE_ROLE_ALIAS=robot-role-alias ./kvsWebrtcClientMasterGstSample MyRandomChannel` 
Note 2 things, *ThingName* is "AWSRobotPi" and *Channel* is "MyRandomChannel". When the sample runs it ignores "MyRandomChannel" as the name of the channel and uses "AWSRobotPi" as the channel name.

<img width="576" alt="Screen Shot 2022-08-23 at 4 30 39 PM" src="https://user-images.githubusercontent.com/78559652/186259645-f4cccce2-d8bd-41f6-aedd-cd4e89803f00.png">
...
<img width="795" alt="Screen Shot 2022-08-23 at 4 30 16 PM" src="https://user-images.githubusercontent.com/78559652/186259591-3057cebe-4b05-4e22-a555-aed8dc26afdf.png">
 
Please feel free if you need more info or if you want me to open a separate issue for it.

**Comment by disa6302** [comment]
@antoineaws ,

If you would like to use a different name for IoT thing and channel name, you should be able to set it up in the samples with some modifications. 

Closing this issue for now assuming answered. Do reach out to us if setting a different name for channel and iot thing causes any errors and the team would be happy to take a look.
