### ISSUE TITLE
[QUESTION]executeFailedIceAgentState callback for application

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1537]
Does executeFailedIceAgentState return status  have callback or any flag for application?

example for  return STATUS_ICE_FAILED_TO_RECOVER_FROM_DISCONNECTION status, our application want to know this happen and process some handle when this occur,

Thanks.

**Comment by disa6302** [comment]
We do not have a callback to listen in on ICE agent error states at this point. However, when ICE_AGENT fails, we set the ICE_AGENT_STATE_FAILED, which sets the peer connection state to failed and we listen in no PEER CONNECTION state changes here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47/samples/Common.c#L45

We do have an enhancement request to https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/703, but we have not gotten to it yet. Will update this thread when we look into this enhancement request
