### ISSUE TITLE
[QUESTION]Does dataChannelSend() sometimes take a long time to respond?

### ISSUE THREAD

**Issue by yusuke1000** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1538]
Does dataChannelSend() ever fail to return a response for an extended period of time?

If a function takes more than 10 seconds to respond, it is a problem in my use case.
I am embedding the Amazon Kinesis Webrtc C SDK for a security camera. If the function does not return a response for an extended period of time, it appears that the camera is stopped. I need to do something so that the camera does not appear to be stopped.

I have checked the following documentation, but it does not describe what I need to know.
https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-c/group__PublicMemberFunctions.html#ga12ab55171a0f53ec8e248e2d193d6bd0

Thanks.

**Comment by disa6302** [comment]
Hmm. Not sure what could be happening but our SDK relies on usrsctp library: https://github.com/sctplab/usrsctp

Wondering if usrsctp_sendv is not returning for some reason. At what rate is the data being sent? And how many bytes are being sent? My recommendation would be to play around this to understand if it helps your case.

**Comment by yusuke1000** [comment]
I had gotten your kind response but sorry for the delay in replying.
I will take a look at the information you provided and see if there is anything wrong with our software.

Thank you.
