### ISSUE TITLE
[QUESTION] how to add sub video track in kvs webrtc

### ISSUE THREAD

**Issue by remainfox** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1539]
## how to add sub video track in kvs webrtc

I want to use **main stream** (1080P) and **sub stream** (720P) to transmit video data in **KVS WEBRTC**. 

How can I add sub video track，Thanks

**Comment by disa6302** [comment]
@remainfox , 

I think what you are looking for is 2 video tracks to solve the purpose. Did you try adding another video transceiver using the addTransceiver API?

**Comment by remainfox** [comment]
> @remainfox ,
> 
> I think what you are looking for is 2 video tracks to solve the purpose. Did you try adding another video transceiver using the addTransceiver API?

yes, i addTransceiver in  , but it is not usefull

```c
RtcMediaStreamTrack videoTrack, audioTrack, subVideoTrack;
RtcRtpTransceiverInit subVideoRtpTransceiverInit;
subVideoTrack.kind = MEDIA_STREAM_TRACK_KIND_VIDEO;
subVideoTrack.codec = pCodecParam->video_codec_type;
subVideoRtpTransceiverInit.direction = RTC_RTP_TRANSCEIVER_DIRECTION_SENDONLY;
STRCPY(videoTrack.streamId, "myKvsSubVideoStream");
STRCPY(videoTrack.trackId, "mySubVideoTrack");
CHK_STATUS(addTransceiver(pSampleStreamingSession->pPeerConnection, &subVideoTrack, &subVideoRtpTransceiverInit,
                              &pSampleStreamingSession->pSubVideoRtcRtpTransceiver));
CHK_STATUS(transceiverOnBandwidthEstimation(pSampleStreamingSession->pSubVideoRtcRtpTransceiver, 
              (UINT64) pSampleStreamingSession,sampleBandwidthEstimationHandler));
```

**Comment by disa6302** [comment]
@remainfox , 
Can you elaborate? What do you mean by its not useful? Do you not see the video?
