### ISSUE TITLE
Performance issues on EKS Cluster

### ISSUE THREAD

**Issue by wolfviking0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1541]
Hi,

i am using the sdk but I am recently facing some trouble with the initialize time of the webrtc protocol.

I am running the master into a docker image on EKS but the timing is really bad. It took almost 40 sec to start the streaming.

i just starting investigating where the timing is, I was suspecting some certificate but even if the timing is slower than a regular machine it’s only 500ms.

i am using the latest release version and my code is almost 99.9 similar to the sample.

It’s really critical I understand what is happening but the log can be hard to decode.

do you have any suggestion where I should look at ? Or any suggestion where I could modify some part to improve the connection time. Because even when the channel already exists it’s take a long time.

Thanks for your advice.

**Comment by disa6302** [comment]
@wolfviking0 ,

There is really not a lot of information to go with here. But, my suggestions would be to start with understanding the network set up. If the candidate pair selection is taking time, try to understand if the connection is being established via TURN. If that is the case, you can expect some latency. A few other suggestions are available in this comment: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1434#issuecomment-1074268997

Without VERBOSE logs, the team really cannot help much. Please attach logs to the issue for the team to look at.

**Comment by wolfviking0** [comment]
Hi, I just locally test disabling Turn, and it make the connection faster on my local, but I need to test on EKS

**Comment by disa6302** [comment]
@wolfviking0 ,

As I said, the team cannot help without logs. Since it is working fine locally, you need to look into what is happening with the EKS and its network set up.

**Comment by wolfviking0** [comment]
Hi sorry for the delay here more feedback I can provide
 
1 - Master and viewer are in the same region
2 - SDK version is 1.7.3
3 - Options use :
trickle ICE = ON
turn/stun = OFF

I am trying to modify my code to add the saving of the log into a file in verbose mode but I am facing an issue because the file does not seems to be created, so I copy them from the console.

<img width="720" alt="Screen Shot 2022-09-01 at 12 17 02 PM" src="https://user-images.githubusercontent.com/2255249/187994970-f19a8ee7-ce32-487d-ad50-80ec79ad2bab.png">
[logmasternoclient.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9472687/logmasternoclient.txt)
[logmasterwithclient.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9472688/logmasterwithclient.txt)

**Comment by disa6302** [comment]
@wolfviking0 , 

Do you have any modifications within the SDK. I see some logs which is not part our SDKs. Can you please run the sample with the SDK without any of your modifications? Also, please use the most recent release. Looking at the logs, I do not see a candidate pair being selected. A few suggestions I have for debugging is to filter out network interfaces and see if that helps. I am not sure how your EKS is set up, but I would start with invetigating the network topology there.

**Comment by wolfviking0** [comment]
Ok I will try again and upgrade to the latest release to check any improvement.

it’s seems in the EKS ForceTurn we’re required and with the older version I have much less issue.
I will do more test and keep you posted
