### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by haiguifly** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1544]
hello, dear
    When I study the source code in  TurnConnection.c,I find the condition TURN_STATE_CHECK_SOCKET_CONNECTION in  function turnConnectionStepState(PTurnConnection pTurnConnection)  dosen't call break statement,I want to ask that is this missing or is it just defined as that?

**Comment by sirknightj** [comment]
Hi @haiguifly, thanks for the keen observation! 

[That case](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/b820e2ea3d28c670da2fbc789face742cb949ef1/src/source/Ice/TurnConnection.c#L926) missing a `break` is intended. Will add a comment there.

**Comment by niyatim23** [comment]
Closing assuming answered. Feel free to re-open / open new issues
