### ISSUE TITLE
Not receiving audio in raspberry pi 4 from viewer side when run ./kvsWebrtcClientMasterGstSample

### ISSUE THREAD

**Issue by Reena2495** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1548]
Hello Folks,

Recently I have been working on one one project. Where we need to do peer-to-peer calls between pi 4 to android application. On Raspberry Pi side, I am using amazon-kinesis-video-streams-webrtc-sdk-c for the same.
We able to successfully stream both audio and video from Pi (Master) to Android (Viewer). But unable to receive back audio from there end. 
./kvsWebrtcClientMasterGstSample ourChannelName audio-video  : use to run the code.
While checking the code, I found out opus pipe line is being use to receive audio.

For the same to test whether audio(opus file) is being played or not through gstreamer pipeline.
For that, this works for me.
gst-launch-1.0 filesrc location=~/sample4.opus ! oggdemux ! opusparse ! opusdec ! alsasink
I also tried the same pipe line in code as well, if it works for me. But no success.

Am I doing anything wrong, or forget something to add? Any helps means a lot for me.
Thanks,
Reena Patel

**Comment by niyatim23** [comment]
Hi @Reena2495, can you please share VERBOSE master and viewer logs to further investigate into this?

**Comment by disa6302** [comment]
Closing due to no response.
