### ISSUE TITLE
[QUESTION] start viewer not play live stream

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1553]
When I stop two viewer  almost the same time, sample program seems have chance hang at timerQueueCancelTimer function as below.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47/samples/Common.c#L562
start viewer again will no chance to play live stream forever, I need restart sample program then ok.

This problem seems only happen under ARM platform but not fond problem under MIPS platform.

**ARM platform information**
Processor       : FA6 rev 3 (v5l)
BogoMIPS        : 858.52
Features        : swp half 
CPU implementer : 0x66
CPU architecture: 5TE
CPU variant     : 0x0
CPU part        : 0x626
CPU revision    : 3

Hardware        : Grain-Media GM8136 series
Revision        : 0000
Serial          : 0000000000000000

**MIPS platform information**
system type             : Formosa
machine                 : RTS3904N EVB
processor               : 0
cpu model               : Taroko V0.2  FPU V0.1
BogoMIPS                : 497.66
wait instruction        : no
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : no
hardware watchpoint     : no
isa                     : mips1
ASEs implemented        : mips16
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
 
**SDK version**
v1.7.3

**Logging** 
as attached log files

[log_20220915_mips.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9573215/log_20220915_mips.zip)
[log_20220915_arm.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9573216/log_20220915_arm.zip)

**Comment by niyatim23** [comment]
I see the error code `0x5a000025`: `STATUS_ICE_FAILED_TO_RECOVER_FROM_DISCONNECTION` in the ARM logs shared. Is the issue described by you persistent?

**Comment by henryChmn** [comment]
@niyatim23 it's some times happen,
BTW, I test this problem by two viewers with different ISP.
If two viewers in same router not found such problem yet.

**Comment by disa6302** [comment]
@henryChmn , 

The logs you shared do not have stack trace. If there is a hang, the team would require a stack trace to investigate. `STATUS_ICE_FAILED_TO_RECOVER_FROM_DISCONNECTION` happens when the peer stops receiving periodic keep alive from the other peer. It seems so that a disconnect happens and no keep alives are received in the grace period as well. Not sure what is causing the other peer to disconnect. This is something you might need to investigate. Meanwhile, please attach a stack trace for the team to look at. The logs do not suggest any kind of hang.

**Comment by henryChmn** [comment]
@disa6302 for arm platform we don't have stack trace information yet,
So far I only can  probe sample code manually,
How about we workaround by restart program when STATUS_ICE_FAILED_TO_RECOVER_FROM_DISCONNECTION  occur?

**Comment by disa6302** [comment]
@henryChmn ,

Reconnecting would be an option, yes. You can modify the sample to react to `RTC_PEER_CONNECTION_STATE_FAILED` state change.

**Comment by disa6302** [comment]
Closing assuming answered. @henryChmn , whenever you have a stack trace, feel free to open a new issue.
