### ISSUE TITLE
[BUG] deadlock when re-connected WebRTC clients (problem in Common.c of samples)

### ISSUE THREAD

**Issue by RufUsul** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1555]
**Describe the bug**
I found a possible deadlock when re-connected WebRTC clients: freeSampleStreamingSession() may deadlock in interaction with pregenerateCertTimerCallback()

**SDK version number**
1.7.3

**Additional context**
I have an fix and just wanted to post an issue before the PR

**Comment by niyatim23** [comment]
Hi @RufUsul, thank you for your PR. Can you please change the base branch to `develop` from `master` and resolve the associated build issues?

**Comment by RufUsul** [comment]
oh wow, some fixed that >4 months ago!
so my issue is effectively i duplicate of #1448 -> i close my issue and PR now

**Comment by RufUsul** [comment]
but please consider merging and releasing this fix ASAP, thanks in advance!
