### ISSUE TITLE
[BUG] Fix possible dead lock when freeSampleStreamingSession (getIceCandidatePairStatsCallback)

### ISSUE THREAD

**Issue by RufUsul** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1560]
Describe the bug
I found a possible deadlock: freeSampleStreamingSession() may deadlock in interaction with getIceCandidatePairStatsCallback()

SDK version number
1.7.3

Additional context
I have an fix and just wanted to post an issue before the PR. Bug and fix are very similar to #1448

**Comment by disa6302** [comment]
Thank you! PR merged.
