### ISSUE TITLE
[QUESTION]How to disable trickle ice in kvsWebRTCClientMaster？

### ISSUE THREAD

**Issue by Kelephant** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1563]
I use the 1.6.0 version of the sdk.

When my alexa is used as the viewer and the ip camera is used as the master, the stream cannot be pulled.

I learned that alesa can't support trickle ice, so what changes should I make to kvsWebRTCClientMaster, disable trickle ice, and let alexa pull the stream successfully？

**Comment by hassanctech** [comment]
That's correct Alexa cannot support trickle Ice.  Here is how to disable it, see where this API is called:

https://github.com/ycyang1229/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c#L31

See the definition here:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L707

The 3rd parameter is a `BOOL` and is set to `TRUE` for `trickleIce`.  You just need to change this to `FALSE` to disable `trickleIce`
