### ISSUE TITLE
[QUESTION] Change the media source output/input on Android and iOS

### ISSUE THREAD

**Issue by chsunwoo1002** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1566]
Hello

I implemented a video/audio pipeline from the IoT device to the peer with RTSP and WebRTC. The implementation of the pipeline has been done with GStreamer. I like to use Kinesis for P2P communication.

I have the following questions:
1. Can I run SDK C on Android and iOS environments?
2. Is SDK C compatible with Android and iOS SDKs?
3. Is there any example code to change the source media on Android and iOS or any related sample code?

Thanks

**Comment by hassanctech** [comment]
This is a low level SDK so using the correct toolchain you should be able to build it for Android and iOS environments to use as a library.  We do not have any examples of this unfortunately nor have we tried to do this ourselves.
