### ISSUE TITLE
TurnConnection in TURN_STATE_FAILED due to 0x5a000020

### ISSUE THREAD

**Issue by mdonahoe** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#157]
I tried passing `KVS_SOCKET_PROTOCOL_UDP` into `createTurnConnection(...)` instead of TCP, but the turn connection did not succeed.

I got this error `TurnConnection in TURN_STATE_FAILED due to 0x5a000020`.

How do I interpret those error messages?

Here's a longer log snippet:
```
2020-01-24 23:45:42 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_NEW to TURN_STATE_GET_CREDENTIALS
[... skipped 200 lines of ICE stuff ...]
2020-01-24 23:45:47 ERROR   turnConnectionStepState(): operation returned status code: 0x5a000020
2020-01-24 23:45:47 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_GET_CREDENTIALS to TURN_STATE_FAILED
2020-01-24 23:45:47 ERROR   turnConnectionTimerCallback(): operation returned status code: 0x5a000020
2020-01-24 23:45:47 ERROR   timerQueueExecutor(): operation returned status code: 0x5a000020
2020-01-24 23:45:47 DEBUG   fromGatheringIceAgentState(): checking local candidate type srflx, ip 192.168.12.1
2020-01-24 23:45:47 DEBUG   fromGatheringIceAgentState(): checking local candidate type srflx, ip 192.168.14.94
2020-01-24 23:45:47 DEBUG   fromGatheringIceAgentState(): checking local candidate type srflx, ip 192.168.12.1
2020-01-24 23:45:47 DEBUG   fromGatheringIceAgentState(): checking local candidate type srflx, ip 192.168.14.94
2020-01-24 23:45:47 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x5a000020
```

_Originally posted by @mdonahoe in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/146#issuecomment-578357290_

**Comment by Sean-Der** [comment]
Thanks for splitting this off @mdonahoe!

I am going to tackle the TCP issue this week. We were able to reproduce the SRTP issue by running in docker (but host OS was 18.04)

I am going to re-image our TX2 to 16.04 on Monday, and work on reproducing (and then fixing the TCP TURN issue). There is another customer that is in the same boat as you so this is at the top of my priorities since we have multiple people getting bit by this :/

----

For UDP TURN I wouldn't burn too many cycles. The developer tasked with this is coming back Monday, and should be able to tackle this. I will have him drop updates soon!

**Comment by disa6302** [comment]
@mdonahoe , I have a TX2 running Ubuntu 16.04. I tried executing the GstSample and it works perfectly fine. I am unable to reproduce your issue. I also tried forcing TURN to see if I can reproduce the issue. But, I do not see this issue pop up.

**Comment by chehefen** [comment]
Hi @mdonahoe, can you tell us which sample are you running? and did you enable TURN? From the log you provided it looks like that turn server is not responding and cause 0x5a000020 which is turn state transition timeout. can you try to dump the packets and see if any turn allocation response was received? Thanks

**Comment by mdonahoe** [comment]
The gstreamer sample.

I’ll get back to you on my packet dump situation after I read up on how to
do that.

**Comment by Sean-Der** [comment]
Hey @chehefen @mdonahoe 

Sorry missed this, but @mdonahoe is seeing https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/173

If a user has multiple network interfaces they may gather a TURN candidate over one that isn't world routable. When TCP is gathered (and fails to connect) it will block forever.

Another thing that *may* help is https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/113 and short term we can have users discard their non-internet routable interfaces until #173 is done.

**Comment by disa6302** [comment]
Hello @mdonahoe , I pushed a change to for #113 into master. You can use that for now and see if it helps. 
Let me know if you have any questions.

**Comment by mdonahoe** [comment]
I'll check it out ASAP, thanks!

**Comment by mdonahoe** [comment]
The filterFunc option from #113 worked great for TCP TURN. Thanks!

I'm nervous about LTE performance of TCP for my use case, but I will see how it goes.

Let me know when UDP-based TURN is working.

**Comment by chehefen** [comment]
you can switch to UDP turn by setting this https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.h#L53 to KVS_SOCKET_PROTOCOL_UDP. But we don't have dtls enabled yet.

**Comment by mdonahoe** [comment]
Hi @chehefen 

I *think* I tried the equivalent of that already (see top of this issue), but got an error.

What is the expected outcome if dtls is not enabled?

**Comment by chehefen** [comment]
@mdonahoe, can you try increase these two timeouts? https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/TurnConnection.h#L25-L26. Maybe you are in a different region than the turn servers and cause extra delay in turn setup.

**Comment by disa6302** [comment]
Closing this for now. @mdonahoe , feel free to reopen the issue or create a new issue if you face any issues
