### ISSUE TITLE
[QUESTION] Whether there is a common version of WEBRTC and KVS dependent libraries？

### ISSUE THREAD

**Issue by yy-arya** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1570]
I would like to integrate the two functions of KVS and WebRTC in a process. 
Then I found that they have some dependent libraries with inconsistent versions. such as libwebsockets，and libkvspic series.
The version of WebRTC I use is 1.7.3 and KVS is 1.2.0.

Are there any dependent library versions that can be shared?

**Comment by niyatim23** [comment]
Hi @yy-arya, do you mean [this](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c) KVS SDK? Can you please elaborate on your use-case of using the two repositories together?

**Comment by yy-arya** [comment]
The KVS SDK for (https://github.com/awslabs/amazon-kinesis-video-streams-producer-c) .

Run webrtc and kvs on different threads of the same process.

Are there any dependent libraries of the same version？

**Comment by disa6302** [comment]
Hmm. Not sure what you mean by common dependencies. If you are looking for the SDK dependency graph, WebRTC SDK depends on producer C SDK and the producer C SDK depends on the PIC SDK.
