### ISSUE TITLE
[QUESTION] Does SDK support IPV6? IPV6 Ice candidates causes 0x00000002 error in iceAgentAddRemoteCandidate()

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1574]
Does SDK support IPV6? 
IPV6 Ice candidates causes 0x00000002 error in iceAgentAddRemoteCandidate()

**Comment by disa6302** [comment]
SDK does not support IPv6 candidates at the moment.

**Comment by wakuken** [comment]
@disa6302 I need IPv6 candidates support because there is an IPv6 only mobile network.

Why is IPv6 not available, even though IPv6 support was added in #115?
