### ISSUE TITLE
[QUESTION]cmake problem

### ISSUE THREAD

**Issue by xiaoyaodingchunqiu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1579]
2001  git clone https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c.git -b master
 2002  cd amazon-kinesis-video-streams-webrtc-sdk-c/
 2003  ls
 2004  mkdir build
 2005  cd build/
 2006  ls
 2007  cmake ..

then cmake failed

** Logging ** 
rock@Snowbot:~/amazon-kinesis-video-streams-webrtc-sdk-c/build$ cmake ..
-- Kinesis Video WebRTC Client path is /home/rock/amazon-kinesis-video-streams-webrtc-sdk-c
-- dependencies install path is /home/rock/amazon-kinesis-video-streams-webrtc-sdk-c/open-source
-- Begin building dependencies.
-- openssl already built
-- Copying patches for dependency websockets: /home/rock/amazon-kinesis-video-streams-webrtc-sdk-c/./CMake/Dependencies/libwebsockets-leak-pipe-fix.patch;/home/rock/amazon-kinesis-video-streams-webrtc-sdk-c/./CMake/Dependencies/libwebsockets-old-gcc-fix-cast-cmakelists.patch
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindOpenSSL.cmake:447 (find_package_handle_standard_args)
  CMakeLists.txt:16 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/rock/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libwebsockets/CMakeFiles/CMakeOutput.log".
CMake Error at CMake/Utilities.cmake:65 (message):
  CMake step for libwebsockets failed: 1
Call Stack (most recent call first):
  CMakeLists.txt:134 (build_dependency)

-- Configuring incomplete, errors occurred!
See also "/home/rock/amazon-kinesis-video-streams-webrtc-sdk-c/build/CMakeFiles/CMakeOutput.log".
rock@Snowbot:~/amazon-kinesis-video-streams-webrtc-sdk-c/build$

background is: rock pi and ubuntu 22.04

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by disa6302** [comment]
Closing due to no response.
