### ISSUE TITLE
[QUESTION] Getting Error while building and Running SDK in Mac OS 12.5 

### ISSUE THREAD

**Issue by Ramnirmal0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1580]
I tried the SDK on my Linux system first. working perfectly. now I want to replicate the same setup in Mac OS too.

**OS version:** Mac OS 12.5 Monterey

so i install cmake and gstreamer in Mac OS . GStreamer is working fine i tested with following commad
`gst-launch-1.0 autovideosrc ! videoconvert ! autovideosink`

there were some error when i tried cmake ..  as follows

> [ 66%] Performing build step for 'project_libopenssl'
In file included from apps/app_rand.c:10:
In file included from apps/apps.h:13:
In file included from ./e_os.h:16:
In file included from include/openssl/e_os2.h:243:
/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include/inttypes.h:30:15: fatal error: 'inttypes.h' file not found
#include_next <inttypes.h>
              ^~~~~~~~~~~~
1 error generated.
make[4]: *** [apps/app_rand.o] Error 1
make[3]: *** [all] Error 2
make[2]: *** [build/src/project_libopenssl-stamp/project_libopenssl-build] Error 2
make[1]: *** [CMakeFiles/project_libopenssl.dir/all] Error 2
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:61 (message):
  CMake step for libopenssl failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:95 (build_dependency)

getting error initally but when i tried cmake .. commad again build is working. then i tried to run the master with 
`./samples/kvsWebrtcClientMasterGstSample <channel-name> video-only`

then i am getting the error below 

> 2022-11-02 19:48:04 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate type: prflx
> 2022-11-02 19:48:04 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate port: 45481
> 2022-11-02 19:48:04 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate priority: 1845501695
> 2022-11-02 19:48:04 DEBUG   logSelectedIceCandidatesInformation(): Remote Candidate transport protocol: udp
> 0:00:08.094678000 21493 0x7fc05d7090c0 ERROR           GST_PIPELINE gst/parse/grammar.y:851:priv_gst_parse_yyparse: no element "autovideosrc"
> 0:00:08.104690000 21493 0x7fc05d7090c0 ERROR           GST_PIPELINE gst/parse/grammar.y:939:priv_gst_parse_yyparse: link has no source [sink=@0x7fc05e81a1b0]
> 0:00:08.104726000 21493 0x7fc05d7090c0 ERROR           GST_PIPELINE gst/parse/grammar.y:851:priv_gst_parse_yyparse: no element "videoconvert"
> 0:00:08.104744000 21493 0x7fc05d7090c0 ERROR           GST_PIPELINE gst/parse/grammar.y:939:priv_gst_parse_yyparse: link has no sink [source=@0x7fc05e81a1b0]
> 0:00:08.105025000 21493 0x7fc05d7090c0 ERROR           GST_PIPELINE gst/parse/grammar.y:851:priv_gst_parse_yyparse: no element "x264enc"
> 0:00:08.105052000 21493 0x7fc05d7090c0 ERROR           GST_PIPELINE gst/parse/grammar.y:939:priv_gst_parse_yyparse: link has no source [sink=@0x0]
> 0:00:08.105095000 21493 0x7fc05d7090c0 ERROR           GST_PIPELINE gst/parse/grammar.y:851:priv_gst_parse_yyparse: no element "appsink"
> 0:00:08.105114000 21493 0x7fc05d7090c0 ERROR           GST_PIPELINE gst/parse/grammar.y:939:priv_gst_parse_yyparse: link has no source [sink=@0x0]
> 
> (kvsWebrtcClientMasterGstSample:21493): GLib-GObject-WARNING **: 01:18:04.439: invalid cast from 'GstQueue' to 'GstBin'
> 
> (kvsWebrtcClientMasterGstSample:21493): GStreamer-CRITICAL **: 01:18:04.439: gst_bin_get_by_name: assertion 'GST_IS_BIN (bin)' failed
> 
> (kvsWebrtcClientMasterGstSample:21493): GLib-GObject-WARNING **: 01:18:04.439: invalid cast from 'GstQueue' to 'GstBin'
> 
> (kvsWebrtcClientMasterGstSample:21493): GStreamer-CRITICAL **: 01:18:04.439: gst_bin_get_by_name: assertion 'GST_IS_BIN (bin)' failed
> [KVS GStreamer Master] sendGstreamerAudioVideo(): cant find appsink, operation returned status code: 0x0000000c 
> no element "autovideosrc"2022-11-02 19:48:04 DEBUG   socketConnectionClosed(): Close socket 15
> 2022-11-02 19:48:04 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_NEW
> 2022-11-02 19:48:04 DEBUG   socketConnectionClosed(): Close socket 16
> 2022-11-02 19:48:04 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CLEAN_UP to TURN_STATE_NEW
> 2022-11-02 19:48:04 DEBUG   dtlsSessionChangeState(): DTLS init completed. Time taken 308 ms
> 2022-11-02 19:48:06 DEBUG   lwsWssCallbackRoutine(): Client is writable
> 2022-11-02 19:48:16 DEBUG   lwsWssCallbackRoutine(): Client is writable

How to fix this ? is this issue with the pipeline code? please help

**Comment by disa6302** [comment]
@Ramnirmal0 , 

It looks like it is unable to find the library. It is a flakiness with our dependency (Openssl). Re-running cmake when you hit this error usually fixes it. Another thing you can try is to run this:
```
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
```
And then run cmake again.

**Comment by disa6302** [comment]
Hmm. Not sure if your Gstreamer libraries are installed correctly. Try reinstalling gstreamer:
`brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav`

**Comment by hassanctech** [comment]
Hi @Ramnirmal0, not sure if you've been able to get past this issue but this is due to the header files for standard libraries no longer being in standard locations for MacOS 12.5, one way to resolve this is to:

`export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include`

You can add this to your shell configuration so you don't have to do it every time.  This is needed to find the <inttypes.h> header.

Then please make sure you have the plugins installed as @disa6302 mentioned so that the standard plugins like `autovideosrc` can be properly found.

You need to make sure those standard GStreamer plugins can be found, fi you install them via the standard package manager (like brew) they should be set up properly with the GStreamer plugin registry.  If not you'll need to export GST_PLUGIN_PATH variable to point to the GStreamer install where the libraries are.

**Comment by Ramnirmal0** [comment]
thanks for the help @hassanctech  @disa6302 . as there are limitation to gstremer Mac moved to linux based setup. so closing this ticket . will reopen if we are considering to expand to macos. 

thanks for the support.

Regards,
