### ISSUE TITLE
[FEATURE] Reqesting for including installation and build procedures for Mac OS in documentation

### ISSUE THREAD

**Issue by Ramnirmal0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1581]
In the documentation, there is a build and installation procedure for Linux. similarly, it would be very helpful if you can include the installation and build procedures and libs needed for mac OS (which should be working in all versions) to support C SDK.

there are lots of errors happening during the build on Mac. it would be better if you could include some troubleshoot instructions to check and validate that the configuration is correct

**Comment by disa6302** [comment]
@Ramnirmal0 , 

The process is the same on Mac as well. If you could elaborate on the specific issue you are facing, the team would be happy to take a look it.

**Comment by disa6302** [comment]
Assuming the issue you are facing is in her: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1580

So closing this out.
