### ISSUE TITLE
[QUESTION]Is it an Amazon KVS WebRTC service requirement or a limitation of this SDK that UPD443 outbound must be allowed?

### ISSUE THREAD

**Issue by H-Tomoki** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1582]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1578
In response to the above question, I received the answer that UDP443 outbound must be allowed because it is a requirement of the service. At the same time, AWS support responded that when using a TURN server, only the TCP port needs to be open.

Is opening UDP443 a requirement of this SDK rather than a requirement of the Amazon KVS WebRTC service?
If so, is there any chance that the SDK update will make it unnecessary to open UDP ports in the future?

**Comment by disa6302** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#outbound-hostname-and-port-requirements - the SDK does not modify any port requirements and it is all as per the service. If UDP is not open, TCP/TLS will be tried. The SDK supports TURN over TCP and UDP
