### ISSUE TITLE
[QUESTION] PCMA audio (ALAW)  stream using kvsWebRTCClientMaster cannot be played on the KVS WebRTC Test Page

### ISSUE THREAD

**Issue by nidhisha-vvdn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1591]
I am trying to stream  H.264 720p, 25fps and  G.711 PCM A-law 8Khz, Mono stream audio using kvsWebRTCClientMaster sample application. 
I could view the video properly via KVS WebRTC Test Page. But audio is having garbage and lot of noise.

Please find the screenshot of the changes I made on sample attached :
![119465121-b01bc300-bd43-11eb-8845-1e65f7839f3a](https://user-images.githubusercontent.com/46441687/203302422-0efbe72b-eaef-4d70-ac0b-b565e035f455.jpg)

Please let me know any other modification required at Master side to playback ALAW audio format successfully at the client side? 

Thanks
Nidhisha.K

**Comment by nidhisha-vvdn** [comment]
Hi ,
I understood from the preview bugs that, timestamps plays a major role in this.
How to find SAMPLE_AUDIO_FRAME_DURATION for the particular ALAW audio frame?

**Comment by niyatim23** [comment]
Closing assuming resolved

**Comment by niyatim23** [comment]
Hi, I was mistaken. WebRTC supports ALAW

**Comment by nidhisha-vvdn** [comment]
Yes. I could able to stream ALAW after modifying the packet size as 160 bytes

**Comment by hassanctech** [comment]
@nidhisha-vvdn Where did you have to make this change for packet size?
