### ISSUE TITLE
How to use Data channel to send large number of data back to Viewer

### ISSUE THREAD

**Issue by itzzmearungmailcom** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1593]
Using Datachannel I am trying to pass the camera stream data from master to viewer. 
I need some help to sent the data as chunk with size permitted by the network.

**Log**
Issue is from SCTP as it not permit to send large CustomData

**Comment by uianster** [comment]
I use the data channel to transmit H264 stream，it work well

**Comment by itzzmearungmailcom** [comment]
> I use the data channel to transmit H264 stream，it work well

Thank you for the response. Are you sending the data in binary format? Could you share the sample code for Master and Viewer?

**Comment by niyatim23** [comment]
The error code `0x0000000c` is `STATUS_INTERNAL_ERROR`. Can you please share verbose logs for further investigation?

**Comment by disa6302** [comment]
Closing due to no response.
