### ISSUE TITLE
[BUG]If UDP 443 outbound is blocked on the machine running the master, peer connection establishment fails for the data channel.

### ISSUE THREAD

**Issue by H-Tomoki** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1594]
**Describe the bug**
The following occurs when the sample is changed to use only the data channel.
The connection state becomes "RTC_PEER_CONNECTION_STATE_FAILED" after the connection attempt and the peer connection establishment fails, if UDP 443 outbound on the machine running the master is blocked.

**SDK version number**
V1.7.3

**To Reproduce**
1. Patch the sample app as in the following question
#1578
2. Block only UDP443 outbound on the PC running the master
    For example, for EC2, do not allow only UDP443 outbound in the security group
3. Run kvsWebrtcClientMaster
4. Run kvsWebrtcClientViewer

**Expected behavior**
As indicated in the answer to the following question, the connection is successfully established by using TCP.

#1582

> If UDP is not open, TCP/TLS will be tried. The SDK supports TURN over TCP and UDP

**Comment by uianster** [comment]
hi @H-Tomoki  
9131	7.517045	192.168.0.97	13.114.42.29	STUN	62	Binding Request
stun server need UDP443

**Comment by disa6302** [comment]
@H-Tomoki , 

Perhaps I should have been specific in my response to the other issue. For media, UDP/TCP is used based on what works. For data channels, SCTP is used which is implemented on top of UDP. This means, UDP needs to be unblocked for data channel use cases.
