### ISSUE TITLE
[QUESTION] Is there a way to know if a connection is TURN or STUN? 

### ISSUE THREAD

**Issue by EunseongBoo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1595]
When Master and Viewer are connected, is there a way to know if a connection is TURN or STUN?

**Comment by niyatim23** [comment]
There is no direct way but you can try to get it from the URL [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1029). It is a part of the configuration [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47/samples/Common.c#L373)

Closing assuming answered
