### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by prathamsss** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1597]
I was able to construct rtsp gstreammer and was able to stream the USB webcam to server,
But when I used rtsp link of my drones with same Gstreammer pipeline I was not able to see video, but channel got created! 
I have attached following logs and screenshots for the same,

Waiting for your response ,
Thanks,

Best,
Prathamesh.

[webrtc_logs.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/10142660/webrtc_logs.txt)

![webrtc_error](https://user-images.githubusercontent.com/46752706/205338015-c2b4f219-c35e-4d91-9692-a740cd4118db.png)

**Comment by prathamsss** [comment]
Yes I'm able to use that without any issue, actually the thing is that the video from RTSP is in different formate! 
It has some STAP-A kind of packets in between. (You can have reference  in below image). Do you guys support these formate or what is the required video formate for WebRTC streaming. ? 

I think I need to write a video formate converter and then stream the converted video to any of the RTSP link and then this RTSP link to Gstreammer 

![Screenshot 2022-12-12 at 11 34 10 PM](https://user-images.githubusercontent.com/46752706/207120563-b142af66-35c3-4044-b703-b15b360ed336.png)

**Comment by niyatim23** [comment]
We do not support the format you mentioned. You can probably use the gstreamer pipeline itself to convert the video to the correct format. The supported codecs for audio / video in WebRTC can be found [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/master/src/source/Rtp/Codecs).

Closing assuming answered
