### ISSUE TITLE
no sever hello when do dtls handshake

### ISSUE THREAD

**Issue by wishys** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1599]
Log show dtls handshake timeout . then i do a capture with wireshark. 
![image](https://user-images.githubusercontent.com/21350292/205785970-7d97784a-625e-4699-85ab-34260174a1e7.png)
![image](https://user-images.githubusercontent.com/21350292/205786125-dcdf5f1f-04f6-4cc6-99d0-365210fbda02.png)
![image](https://user-images.githubusercontent.com/21350292/205786354-d2ec77b9-7dc2-4be4-817d-c44b25609eb8.png)
Wireshark parse clientHello  message to dtls,not dtlsV1.2 。 
Maybe something wrong with the toolchain(arm-openwrt-muslgnueabi). but i am not sure . 
When i compile with this toolchain(arm-openwrt-muslgnueabi)， it  crash when call  ` MEMSET(entries, 0x00, sizeof(entries)); ` ,in function ` signalingCacheLoadFromFile ` of File ` FileCache.c `.
then i comment this line。it does not crash but can not do dtlshandshake....
When I compile with other toolchain（such as arm-linux-gnueabihf） everything works.

**Comment by disa6302** [comment]
The version of OpenSSL we use uses DTLS1.2 by default. It is likely the toolchain you are using does not support that. I am not very sure about the details of the OpenWRT toolchain, but perhaps you need to check the version of gnutls on your system.
