### ISSUE TITLE
[QUESTION] Do we have a sample with two-way audio/video without using gstreamer

### ISSUE THREAD

**Issue by vikramshitole** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1603]
Want to use the webrtc sdk, do we have sample which does 2 way audio video without having gstreamer, not able to cross compile gstreamer for the hardware.

**Comment by jdelapla** [comment]
Hi, there is a sample in samples/kvsWebrtcClientMaster.c that does not use gstreamer, instead it reads from a file. You can change the code in the following functions of that sample:
`sendAudioPackets()
sendVideoPackets()`
to pull from whatever audio/video source your application provides.
