### ISSUE TITLE
[QUESTION] Choppy audio

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1607]
I'm streaming H264/Opus from an Axis M1135 camera via WebRtc. The audio RTP packets contains 20ms of audio, but the timestamps do not exactly increment by 960 (which from my understanding must be the case) and this results in choppy audio playback.  Sometimes the timestamps increment by a slightly different amount, e.g. 953, 964, etc.  This results in a very high amount of concealed samples and choppy audio. Hardcoding and incrementing each timestamp by 960 results in smooth playback, but introduces issues with video/audio synchronisation.

As this issue might be related to other audiences than KVS (e.g. maybe it's related to the neteq jitter buffer in Chromium) I've written a more in depth explanation of this issue here:
https://github.com/roxlu/webrtc-jitter/blob/main/jitter-issue.md

I haven't found the reason why the audio becomes choppy when the delta timestamps are slightly different from 960. Does someone know why this might happen and how I can solve this?

**Comment by disa6302** [comment]
This is a very interesting observation. As you mentioned, this could be something that is coming from Chrome. Have you tried Firefox? Do you see a similar pattern?

**Comment by roxlu** [comment]
This issue is particular to the jitter buffer code from libwebrtc that is used in Chromium. I'll check out other browsers to see if we can see a difference there. Thanks!

**Comment by disa6302** [comment]
Closing due to no updates. @roxlu , feel free to start a discussion on this repo if you have any more findings.
