### ISSUE TITLE
[BUG] Custom MFC C++ application crashes occasinally at JitterBuffer.c

### ISSUE THREAD

**Issue by mehmetcy84** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1611]
On Windows, using SDK v 1.7.3, I am developing a custom Visual Studio 2017 C++ MFC application which makes use of the sample viewer code.

Although I am aiming to implement a controller which can handle multiple simultaneous Kinesis clients, my initial test makes use of the kvsWebRTCClientViewer.c and Common.c along with the Samples.h using a single client only.

The only relevant change I made to these files:
1) Renamed kvsWebRTCClientViewer.c to kvsWebRTCClientViewer.cpp
2) Renamed Common.c to Common.cpp
3) Restructured the main function in kvsWebRTCClientViewer.cpp as below:
-INT32 main(INT32 argc, CHAR* argv[])
+INT32 main()
4) Hardcoded the necessary credentials in code.
5) Added a dbgPrint/TRACE in Common.c (renamed to Common.cpp) function to confirm frames are recevied:
VOID sampleFrameHandler(UINT64 customData, PFrame pFrame)

My MFC application creates a thread, which calls the main, and sampleFrameHandler function starts printing confirming that the frames are received.

Though, occasionally the application crashes at:
src/source/PeerConnection/JitterBuffer.c at line 356:
`CHK_STATUS(pJitterBuffer->depayPayloadFn(pCurPacket->payload, pCurPacket->payloadLength, pCurPtrInFrame, &partialFrameSize, NULL));`

> Exception thrown at 0x00007FF92B3A122E (vcruntime140d.dll) in MyApp.exe: 0xC0000005: Access violation reading location 0x000001A15B54F000.

with VS output showing:

> e:\MyRepo\kinesis\common.cpp(625) : atlTraceGeneral - sampleFrameHandler
> e:\MyRepo\kinesis\common.cpp(625) : atlTraceGeneral - sampleFrameHandler
> e:\MyRepo\kinesis\common.cpp(625) : atlTraceGeneral - sampleFrameHandler
> e:\MyRepo\kinesis\common.cpp(625) : atlTraceGeneral - sampleFrameHandler
> e:\MyRepo\kinesis\common.cpp(625) : atlTraceGeneral - sampleFrameHandler
> Exception thrown at 0x00007FF92B3A122E (vcruntime140d.dll) in MyApp.exe: 0xC0000005: Access violation reading location 0x000001A15B54F000.

What might be the cause of this? I have built the Kinesis C SDK and added the necessary libs to my project. It can be seen that sampleFrameHandler starts firing before the crash. How may I help you help me with this crash?
Thanks in advance,

EDIT: I tried to use directly with .c files instead of the renamed .cpp versions, and the same crash is observed.

EDIT: By applying the workaround fix I mentioned here, a number of different random crashes including the one in this ticket seems to be resolved. Please refer to:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1613

**Comment by niyatim23** [comment]
Hi @mehmetcy84, can you please use the develop branch to build on Windows now, try running the sample application without any modifications to the SDK and see if this issue still persists?

**Comment by niyatim23** [comment]
Please use `develop` and refer to the `windows-openssl-msvc` CI build for steps to build correctly. Closing this issue due to no response. Feel free to reopen / open a new issue if this persists.
