### ISSUE TITLE
[BUG] Custom VS2017 C++ MFC Application occasionally crashes at RtpH264Payloader.c

### ISSUE THREAD

**Issue by mehmetcy84** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1613]
Using Kinesis SDK 1.7.3, developing a C++ MFC App with VS2017 on Win 10 64-bit PC, having built and added the necessary libs to my application, I can display frames from our camera via Kinesis. However there are a number of random crashes in different places.

One of the crashes happens in RtpH264Playloader.c depayH264FromRtpPayload function.

`STATUS depayH264FromRtpPayload(PBYTE pRawPacket, UINT32 packetLength, PBYTE pNaluData, PUINT32 pNaluLength, PBOOL pIsStart)`

```
case STAP_B_INDICATOR:
            naluLength = 0;
            pCurPtr = pRawPacket + STAP_A_HEADER_SIZE;
            do {
                subNaluSize = getUnalignedInt16BigEndian(pCurPtr);
                pCurPtr += SIZEOF(UINT16);
                MEMCPY(pNaluData, start4ByteCode, SIZEOF(start4ByteCode));
                pNaluData += SIZEOF(start4ByteCode);
                MEMCPY(pNaluData, pCurPtr, subNaluSize);    // <--------------PROBLEM HERE
                pCurPtr += subNaluSize;
                pNaluData += subNaluSize;
                naluLength += SIZEOF(start4ByteCode) + subNaluSize;
            } while (subNaluSize > 0 && pCurPtr < pRawPacket + packetLength);
            DLOGS("STAP_B_INDICATOR starting packet %d len %d", isStartingPacket, naluLength);
            break;
```

Here, I receive an exception:

> Exception thrown at 0x00007FF91981122E (vcruntime140d.dll) in MyApp.exe: 0xC0000005: Access violation reading location 0x0000016E87285000.

When I check the local values, 

> packetLength: 224
> subNaluSize: 59196

hence in this line:
`MEMCPY(pNaluData, pCurPtr, subNaluSize);`
pCurPtr points to the first input argument pointer, which points to a buffer of length 224, and memcpy attempts to read 59196 bytes from it.
The fourth input/output argument pNaluLength has the value of 89572.

So the pNaluLength and subNaluSize calculation seems to be off. Has there been a similar issue/crash reported before?
How can we fix this?

EDIT:
I simply added a size check before the memcpy, but still not sure why the packet size read from the frame is a bigger value than the actual size. I no longer see the crash.

**Comment by niyatim23** [comment]
Hi @mehmetcy84, can you please use the develop branch to build on Windows now, try running the sample application without any modifications to the SDK and see if this issue still persists?
