### ISSUE TITLE
[QUESTION] Built websockets.dll depends on a DEBUG dll. How to build websockets.dll in RELEASE?

### ISSUE THREAD

**Issue by mehmetcy84** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1617]
I built the Kinesis C SDK on Windows 10 64 bit VS2017 environment. The built websockets.dll in open-source folder depends on a DEBUG dll. When I 
`dumpbin /dependents websockets.dll`
I get 
`VCRUNTIME140D.dll`
as a dependency, and this is a debug dll missing on client PC's. How can I ensure the websockets.dll depends on
`VCRUNTIME140.dll`
instead?

In libwebsockets-CMakeLists.txt I tried these to no avail:
`-DCMAKE_BUILD_TYPE=RELEASE`
`-DCMAKE_BUILD_TYPE=Release`
but both cases produce DEBUG dlls.

```
ExternalProject_Add(project_libwebsockets
    GIT_REPOSITORY    https://github.com/warmcat/libwebsockets.git
    GIT_TAG           v4.2.2
    PATCH_COMMAND     ${PATCH_COMMAND}
    PREFIX            ${CMAKE_CURRENT_BINARY_DIR}/build
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${OPEN_SRC_INSTALL_PREFIX}
        -DLWS_WITH_HTTP2=1
        -DLWS_HAVE_HMAC_CTX_new=1
        -DLWS_HAVE_SSL_EXTRA_CHAIN_CERTS=1
        -DLWS_HAVE_OPENSSL_ECDH_H=1
        -DLWS_HAVE_EVP_MD_CTX_free=1
        -DLWS_WITHOUT_SERVER=1
        -DLWS_WITHOUT_TESTAPPS=1
        -DLWS_WITH_THREADPOOL=0                                        // <-------- I changed this
        -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=1
        -DLWS_WITHOUT_TEST_PING=1
        -DLWS_WITHOUT_TEST_CLIENT=1
        -DLWS_WITH_STATIC=${LWS_WITH_STATIC}
        -DLWS_WITH_SHARED=${LWS_WITH_SHARED}
        -DLWS_STATIC_PIC=1
        -DLWS_WITH_ZLIB=0
        -DLWS_HAVE_EVENTFD=0
        -DLWS_WITH_MBEDTLS=${LWS_WITH_MBEDTLS}
# enable for debug output        -DCMAKE_BUILD_TYPE=DEBUG        // <--------- uncommented this line with Release/RELEASE
        -DLWS_OPENSSL_INCLUDE_DIRS=${OPENSSL_INCLUDE_DIR}
        -DLWS_OPENSSL_CRYPTO_LIBRARY=${OPENSSL_CRYPTO_LIBRARY}
        -DLWS_OPENSSL_SSL_LIBRARY=${OPENSSL_SSL_LIBRARY}
        -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
        BUILD_ALWAYS      TRUE
    TEST_COMMAND      ""
) 
```

**Comment by disa6302** [comment]
@mehmetcy84 , 

Did you try to clean build? As per libwebsockets library:
https://github.com/warmcat/libwebsockets/blob/v4.2.2/CMakeLists.txt#L48


What you are passing seems to be right. Perhaps this is something the libwebsockets team can help with.

**Comment by mehmetcy84** [comment]
Every time I delete the entire "build" folder and restart from scratch.

**Comment by mehmetcy84** [comment]
I already posted this on libwebsockets github forum and the team stated this:

> The official cmake way is -DCMAKE_BUILD_TYPE=RELEASE or Release, I don't know which for Windows.
> 
> If something imports the debug thing, there should be tools to examine the dynamlic lib and find out what's bringing it in. It might be a transitive import from some other lib lws pulls in, I cannot debug it for you.

**Comment by disa6302** [comment]
I do not quite understand this line: ` It might be a transitive import from some other lib lws pulls in`, given KVS merely uses libwebsockets as an external project and passes in the flags as per the README. 

It might take us a while to reproduce this issue. Is it possible for you to try building libwebsockets library standalone on your Windows machine to see if it generates the RELEASE build? This will help segregate the issue and understand if there is something KVS is doing to prevent the RELEASE version from being built.

**Comment by mehmetcy84** [comment]
> I do not quite understand this line: ` It might be a transitive import from some other lib lws pulls in`, given KVS merely uses libwebsockets as an external project and passes in the flags as per the README.
> 
> It might take us a while to reproduce this issue. Is it possible for you to try building libwebsockets library standalone on your Windows machine to see if it generates the RELEASE build? This will help segregate the issue and understand if there is something KVS is doing to prevent the RELEASE version from being built.

Sure I will try my best, but with my previous standalone attempts to build libwebsockets had me run into many errors which I then I had to give up. Another thing I am not certain is, as far as I understand after cloning the libwebsockets repo, the Kinesis build applies a patch on top of the libwebsockets. Not sure how I will reproduce it on standalone build, or whether that would make a change in regards to the build type of the dll.

**Comment by disa6302** [comment]
The patch files are not related to the build type at all. So you should be fine. The patch files are related to KVS functioning only and has no effect on the build.

**Comment by mehmetcy84** [comment]
I was deleting the entire build folder but not the open-source folder which actually hosts the built websockets.dll.
After deleting the old websockets.dll from the previous build, I realized on rebuild the dll is not recreated.
Only then I realized I also need to delete the open-source folder too.
Once deleted, and rebuilt, the new websockets.dll turned out to be indeed the release version.
