### ISSUE TITLE
[BUG] Client JitterBuffer starts dropping frames due to integer overflow

### ISSUE THREAD

**Issue by mehmetcy84** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1620]
In src/source/PeerConnection/JitterBuffer.c inside the jitterBufferPush function, incoming frame's header timestamp is compared with the last pushed frame's timestamp. But due to integer overflow, newcoming frame's timestamp can become a small number e.g. 14000 and the last pushed frame's timestamp can be a huge number in comparison e.g. close to MAX_UINT 4.2 billion and change. At this point because of the huge gap due to overflow, all the incoming packets start to get dropped and video stops playing.

Overflow needs to be handled in:

`STATUS jitterBufferPush(PJitterBuffer pJitterBuffer, PRtpPacket pRtpPacket, PBOOL pPacketDiscarded)`

```
    if ((pRtpPacket->header.timestamp < pJitterBuffer->maxLatency && pJitterBuffer->lastPushTimestamp <= pJitterBuffer->maxLatency) ||
        pRtpPacket->header.timestamp >= pJitterBuffer->lastPushTimestamp - pJitterBuffer->maxLatency) {
```

**Comment by jdelapla** [comment]
Thank you for the report, we're working to fix this issue.
