### ISSUE TITLE
[QUESTION]How can I get the `kvssink` with the webrtc example for GStreamer

### ISSUE THREAD

**Issue by xtianus79** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1622]
I'm using the webrtc samples but they don't really explain how to use the kvssink. The `kvssink` doesn't exist as a plugin in the example of the GStreamer example. When I try to install the dependencies via apt-get that doesn't seem to add the plugin. for kvssink and emits an error that the plugin in not available. 

Are there specific instructions for this?

**Comment by hassanctech** [comment]
`kvssink` is a GStreamer element which allows you to send video to our backend and is build on top of our Producer libraries.

WebRTC is for peer to peer communication.

If you would like to get the `kvssink` GStreamer element you need to go here:  

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp

I would recommend you use our latest release (v3.3.1).

Create a `build` directory, then go inside and run:

`cmake .. -DBUILD_GSTREAMER_PLUGIN=ON`

This will build the the plugin in the end you should see a `libgstkvssink.so` file that is the plugin.

If you want to run commands like `gst-inspect-1.0 kvssink`, after you have the `libgstkvssink.so` file, export the `GST_PLUGIN_PATH` environment variable setting it to where the `libgstkvssink.so` file is.  Then you'll be able to see it.

Unfortunately right now the plugin is not available via the standard package manager like apt-get.  

If you continue to have issues with this, please open a new issue in the repository linked above.
