### ISSUE TITLE
[QUESTION]What resolution of video can you pass through webRTC as I can only see 720p using GStreamer

### ISSUE THREAD

**Issue by xtianus79** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1623]
Can you do 4k and 1080p?

If so, what I am assuming it is a setting on GStreamer to achieve this.

**Comment by hassanctech** [comment]
There is no inherent limitation here it really is up to your network and what the two sides (master / viewer) agree up that they support.

If you see 720p then I assume you're sending 720p.  You need to modify the source of your video.  

In our samples specifically we do hardcode 720p, you can easily modify this to whatever you'd like in this section:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L145-L182

Specifically like this:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L149
