### ISSUE TITLE
[BUG] Unable to stream on windows 10 with sample applications

### ISSUE THREAD

**Issue by srinivasbakki** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1624]
I'm trying to run the sample master and gstreamer applications on windows 10. Both of them do not work. The JS works in my network, both master and viewer. I'm using the master branch. Please find the log attached for both mater application and gstreamer. 

[aws_webrtc_log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/10516943/aws_webrtc_log.txt)

**Comment by niyatim23** [comment]
Hi @srinivasbakki, are you running the sample application as is or have you made any changes to it?
I see `2023-01-26 15:47:23 ERROR   signalingCacheLoadFromFile(): operation returned status code: 0x0000000a`, seems like this application does not have permissions to write to the file system.

**Comment by srinivasbakki** [comment]
Hi, i ran the application as is. I didn't change anything. My interest is with Client application to stream H264. Didin't check the gstreamer application with below observation -  I saw in some thread about changes to connectionListenerReceiveDataRoutine :
comment  retval = POLL(rfds, nfds, CONNECTION_LISTENER_SOCKET_WAIT_FOR_DATA_TIMEOUT / HUNDREDS_OF_NANOS_IN_A_MILLISECOND); and simply return success. 
Next, in the same routine comment if (canReadFd(localSocket, rfds, nfds)) {
and just go ahead with the recv loop. Bingo, this works. 
But this is not clean solution
Please help

**Comment by niyatim23** [comment]
Hi @srinivasbakki, can you please use the develop branch to build on Windows now and try running the sample application without any modifications to the SDK?
