### ISSUE TITLE
I want to get video data from PC(remote), how to do ?[QUESTION] 

### ISSUE THREAD

**Issue by cpw640530** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1625]
i see kvsWebRTCClientMaster.c have  sampleReceiveVideoFrame(). this mean that can receive video frame from PC ,i mean how to get ?
I want to show remote video ( send from viewer) and display them on local-end (master).  onFrameReadyFunc()??

**Comment by niyatim23** [comment]
You can run the master on your PC and use [this](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html) as a viewer to receive the stream by running the sample application as master from terminal. You can also use the AWS console as your viewer.
