### ISSUE TITLE
[QUESTION] Unable to stream from mac webcam

### ISSUE THREAD

**Issue by ap-northeast-0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1628]
I am using the "./samples/kvsWebrtcClientMasterGstSample myChannel" command to establish the connection and check it using the KVS Test Page. However, the From Master video is not loading the stream from my webcam.
i am attaching the logs. Hope you guys could help me. Do I need to make changes in the kvsWebRTCClientMasterGstreamerSample.c file?

Thank you in advance.

** Logging ** 
[KVS GStreamer Master] Signaling client connection to socket established
[KVS Gstreamer Master] Beginning streaming...check the stream over channel testChannel
2023-02-02 07:55:11 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000003
2023-02-02 07:55:11 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000003

(kvsWebrtcClientMasterGstSample:94271): GStreamer-CRITICAL **: 16:55:11.224: gst_bin_get_by_name: assertion 'GST_IS_BIN (bin)' failed
[KVS GStreamer Master] gst_bin_get_by_name(): cant find appsrc, operation returned status code: 0x0000000c 

(kvsWebrtcClientMasterGstSample:94271): GLib-GObject-WARNING **: 16:55:11.640: invalid cast from 'GstQueue' to 'GstBin'

(kvsWebrtcClientMasterGstSample:94271): GStreamer-CRITICAL **: 16:55:11.640: gst_bin_get_by_name: assertion 'GST_IS_BIN (bin)' failed

(kvsWebrtcClientMasterGstSample:94271): GLib-GObject-WARNING **: 16:55:11.640: invalid cast from 'GstQueue' to 'GstBin'

(kvsWebrtcClientMasterGstSample:94271): GStreamer-CRITICAL **: 16:55:11.640: gst_bin_get_by_name: assertion 'GST_IS_BIN (bin)' failed
no element "appsrc"[KVS GStreamer Master] sendGstreamerAudioVideo(): cant find appsink, operation returned status code: 0x0000000c

**Comment by niyatim23** [comment]
Hi @ap-northeast-0, the error code `0x5a000003` is `STATUS_ICE_CANDIDATE_STRING_MISSING_IP`. Can you please ensure that you have a working GStreamer setup by running a sample pipeline directly from the terminal before we try to debug this?

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to open a new issue in case of further issues / questions

**Comment by ap-northeast-0** [comment]
Hello, thank you very much for your reply.

To test for gstreamer, I tried running the code below and I was able to run it successfully. 
And I am also trying out kvs-producer-sdk and I was able to stream from there.. so I think my gstreamer setup is ok?

gst-launch-1.0 avfvideosrc device-index=0 ! video/x-raw, framerate=30/1, width=1280, height=720 ! queue ! autovideosink

If you meant this line from gstreamersample.c, then it also ran successfully.

gstreamersample.c
pipeline = gst_parse_launch(
                    "gst-launch-1.0 avfvideosrc device-index=0 ! video/x-raw, framerate=30/1, width=1280, height=720 ! queue ! autovideosink ! "
                    "x264enc bframes=0 speed-preset=veryfast bitrate=512 byte-stream=TRUE tune=zerolatency ! "
                    "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video",
                    &error);
--
Run result:

Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
Redistribute latency...
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:06.260766000
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by disa6302** [comment]
@ap-northeast-0 , 

I see you are testing your pipeline with avfvideosrc from command line, but the logs suggest you are trying to use appsrc? You would have to look into why appsrc is not being detected. It could be that GStreamer libraries are not being detected appropriately and that could be a possibility if the base plugin is not found. My debug suggestion would be to verify if appsrc to fakesink pipeline using gst-launch command on your platform works without throwing errors and then integrate this sdk into it. I am closing this for now. Feel free to reopen if you still face issues after getting appsrc to fakesink working.
