### ISSUE TITLE
[BUG]samples/Common.c sessionCleanupWait() return with mutex locking

### ISSUE THREAD

**Issue by YOSI-yoshidayuji** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1694]
**Describe the bug**
At line 1151 of the sessionCleanupWait function in the source file samples/Common.c, pSampleConfiguration->streamingSessionListReadLock is locked. 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L1151
It is unlocked at line 1165, but since there is a CHK_STATUS macro in between, so it might goto to the CleanUp label. 
As with pSampleConfiguration->sampleConfigurationObjLock, I believe it is necessary to define a flag to indicate that locking. Functions should not return in a locked state.

**SDK version number**
1.7.3

**Comment by sirknightj** [comment]
Thanks for reporting this @YOSI-yoshidayuji!
