### ISSUE TITLE
[BUG]Peer connection failed.

### ISSUE THREAD

**Issue by TE-0000401270** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1695]
**SDK version number**
1.7.3

 
**Open source building**
It is not a build issue.

**To Reproduce**
1. Run master. -> signaling connection is OK.
2. Run viewer. -> peer connection is NG.

If you make a signaling connection from the master and then a peer connection from the viewer,

In master's signalingMessageReceived()
Receiving SIGNALING_MESSAGE_TYPE_OFFER(=0) or SIGNALING_MESSAGE_TYPE_ICE_CANDIDATE(=2),

newState in onConnectionStateChange() of master
RTC_PEER_CONNECTION_STATE_CONNECTING(=2) -> RTC_PEER_CONNECTION_STATE_CONNECTED(=3) is notified,
Where it should transition to peer connection OK,
RTC_PEER_CONNECTION_STATE_CONNECTING(=2) -> Notified as RTC_PEER_CONNECTION_STATE_FAILED(=5) after 10 seconds,
Peer connection fails.

**Expected behavior**
1. Run master. -> signaling connection is OK.
2. Run viewer. -> peer connection is OK.

 **Screenshots**
None.

 **Desktop (please complete the following information):**
master environment
    Linux (none) 4.9.186

- OS: [Linux]
- Browser [None]
- Version [None]
non-proxy environment

 **Smartphone (please complete the following information):**
viewer environment
    Ubuntu SMP Fri Mar 17 16:49:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- Device: [PC]
- OS: [Windows 10 Enterprise]
- Browser [Microsoft Edge]
- Version [112.0.1722.46]
non-proxy environment

**Additional context**
We created a client app by referring to the SDK sample app,
Embed it on an embedded device (Linux) and AWS EC2 (Linux),
I ran the embedded device as master and AWS EC2 as viewer.

Could you tell me the cause of peer connection failure and countermeasures?
Thank you.

**Comment by sirknightj** [comment]
Hi @TE-0000401270,

You mentioned that you are running your own application which is based off of the sample application.

Could you try running the sample application as-is (with no modifications) from the device? And also try using Chrome instead of Microsoft Edge, to see if the issue is replicable?

If so, could you attach some logs for some additional context to help us look into this?
