### ISSUE TITLE
[BUG] Unable to build static libraries

### ISSUE THREAD

**Issue by djangbahevans** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1703]
**Logging**
```
[ 90%] Linking C executable kvsWebrtcClientViewer
/usr/bin/ld: ../../open-source/lib/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
samples/CMakeFiles/kvsWebrtcClientViewer.dir/build.make:126: recipe for target 'samples/kvsWebrtcClientViewer' failed
make[2]: *** [samples/kvsWebrtcClientViewer] Error 1
CMakeFiles/Makefile2:164: recipe for target 'samples/CMakeFiles/kvsWebrtcClientViewer.dir/all' failed
make[1]: *** [samples/CMakeFiles/kvsWebrtcClientViewer.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Describe the bug**
I am not able to build the static libraries after running `cmake -DBUILD_STATIC_LIBS=TRUE ..` and `make` from the build folder. Doing so causes the error above at about 90% progress.

**SDK version number**
commit b820e2ea3d28c670da2fbc789face742cb949ef1

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**
1. mkdir build
2. cd build
3. cmake -DBUILD_STATIC_LIBS=TRUE ..
4. make

**Expected behavior**
That the static libraries will be built

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**

**Comment by niyatim23** [comment]
Hi @djangbahevans, we have static build on Linux systems in our CI which runs without any problems. Please refer to the steps [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/.github/workflows/ci.yml#L205-L225) for the same.

Closing assuming answered
