### ISSUE TITLE
H.265 Support

### ISSUE THREAD

**Issue by gi12345** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1709]
I am working on a project which requires H.265 support.
It seems "master" does not support this. There is a branch "H265". Is this branch working and has it been tested? Is there a plan to merge this branch in "master" to provide flexible H.264/H.2,65 support?

**Comment by niyatim23** [comment]
Hi @gi12345, we do not support H265 for WebRTC through any branches. We do not have a timeline yet. This request is being tracked as a part of https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1124
