### ISSUE TITLE
[QUESTION] Multiple times click start and Stop viewer crashing kvswebrtc in the Gstremer pipeline

### ISSUE THREAD

**Issue by pmuvvagithub** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1713]
I am using Gstreamer  pipeline for server gst-launch-1.0 rtspsrc location="rtsp://<USERNAME>:<PASSWORD>@<IP>:<PORT>/videoMain" ! rtpjitterbuffer ! rtph264depay ! h264parse ! kvswebrtc <KVSWEBRTC_PARS>  and https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html as client.

Using this client, click multiple times(average 6 to 8 clicks) Start Viewer and Stop Viewer then Pipeline is crashing. But in the pipeline log shows" closePeerConnection() ->freePeerConnection() ". I enabled log level as Debug but not able to find the crash call stack.  

Any help would be appreciated !!

**Comment by hassanctech** [comment]
Can you please share where this `kvswebrtc` GStreamer plugin is coming from?

**Comment by pmuvvagithub** [comment]
It is custom plugin on top aws webrtc sdk .  Basically I am getting this crash because of Application is running for 5mts then it stops. I am getting the message  "ICE AGENT CONNECTED PAIR NOT FOUND within Interval " . Once after receiving this message then it will not accepting remoteCandidate and not sending SDP answers for multiple times sending client viewer request from  https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html

**Comment by pmuvvagithub** [comment]
[webrtc_sdk_logs.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/11648954/webrtc_sdk_logs.zip)

**Comment by sirknightj** [comment]
Hey @pmuvvagithub , I'm not seeing anything in the attached logs that would indicate that the KVS WebRTC SDK is erroring out, it looks like those are custom application logs. Do you have logs from the SDK itself?

Using the two of the JS sample page, one as master and one as viewer, I repeatedly connected and disconnected the viewer more than 20 times and the two peers were still able to connect fine.

Note that we also have kvsplugin which you can use as a reference of a working version of a GSteamer and WebRTC: https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/gst/gst-kvs-plugin

Would you be able to replicate the connection issue with any of our sample applications so we can fegus the issue further?

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to reopen if the issue persists
