### ISSUE TITLE
how could i resolve it?

### ISSUE THREAD

**Issue by lokeshreddyo11** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1714]
aws kinesisvideo update-media-storage-configuration \
    --channel-arn "arn:aws:kinesisvideo:us-east-2:827079776022:channel/mychannel175/1684305496820" \
    --media-storage-configuration '{"StreamARN": "arn:aws:kinesisvideo:us-east-2:827079776022:stream/mystream175/1684305556139", "Status": "ENABLED"}' \
    --region us-east-2

An error occurred (AccessDeniedException) when calling the UpdateMediaStorageConfiguration operation: The account id 82a22 is not allowed to access the resources

**Comment by sirknightj** [comment]
It's only available in us-west-2 region.

https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/webrtc-ingestion.html

**Comment by lokeshreddyo11** [comment]
even though im getting the same error?
