### ISSUE TITLE
[BUG] Data Channel send not working with C WebRTC SDK Master and JS viewer

### ISSUE THREAD

**Issue by hassanctech** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1752]
**Describe the bug**
Running the latest release C SDK as master and the JS test page viewer: https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html

If you send a message from the JS viewer, it is received by the C SDK and the C SDK sends a message back to the JS, but it not received.  

If you reverse the setup and run the C SDK viewer with JS test page master, there is a startup message sent from the C SDK to the JS page it is received successfully, but all subsequent messages are not.

**SDK version number**
Latest release: v1.7.3

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**

**Expected behavior**
Messages should go through from C SDK --> JS test page and JS test page --> C SDK both permutations:
* C SDK master and JS test page viewer
* C SDK Viewer and JS test page Master

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sirknightj** [comment]
May or may not be related to https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/issues/69

**Comment by yuma-m** [comment]
@hassanctech 
I recently encountered the same issue.
In case of C SDK master and JS SDK viewer, C SDK will send back a message on the data channel created by JS SDK viewer.
However, JS SDK viewer doesn't have a callback function to the data channel created by itself.
You may need to define a callback function in JS SDK viewer sample application like this: `viewer.dataChannel.onmessage = onRemoteDataMessage;` or create a data channel in C SDK master.

**Comment by niyatim23** [comment]
This was an issue on the JS SDK-side. It was fixed and merged into `develop` in [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/pull/213) PR but since we use master with GitHub pages, it is not available yet. It will be available in the next release

**Comment by hassanctech** [comment]
Thanks I've verified it works for me as well on  the`update-producer-dep` branch.  Closing
