### ISSUE TITLE
Stream MP4 or TS file over Webrtc

### ISSUE THREAD

**Issue by pmuvvagithub** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1760]
Hi,
I am able to stream "rtsp url" over webrtc with Gstreamer pipeline. But I am trying to stream MP4 or TS file over webrtc but I can able to see only black screen.
 rtspsrc pipeline is: 
src--capfilter--depay--filter--parser---webrtc  (It is working fine)

For file source gstreamer pipeline:
src--demux--queue--parser--capfilter---webrtc

I enabled repeat headers for every 15 frames of mp4 file.  How to stream local file over webrtc?

**Comment by disa6302** [comment]
@pmuvvagithub ,

You would need a pipeline to ensure the generated audio frames are Opus frames and generated video frames are H.264/VP8.

**Comment by pmuvvagithub** [comment]
Is it work without Audio frames and has only h264 frames?

**Comment by disa6302** [comment]
It can work with video only, audio only and video-audio. The formats should be the ones I specified earlier.

**Comment by pmuvvagithub** [comment]
gst-launch-1.0 multifilesrc location="burglary_h264_640x480_1000kbps.ts" loop=true ! tsdemux ! queue ! h264parse config-interval=-1 ! kvswebrtc channel-name=fc59c012-dc76-40eb-a550-54b06678c92d access-key=xxxxx  secret-key=xxxxx aws-region=us-east-1 webrtc-connection-mode=0 log-level=2.   
burglary_h264_640x480_1000kbps has only h264 video. When I am trying to run I am able to see two issues:
1. If I will do "export GST_DEBUG=tsdemux:8" then only I am able to see the video on https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html
2. After export GST_DEBUG then the video plays very fast
Any idea why it is behave like that?

**Comment by pmuvvagithub** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/132293141/f8eabcba-cc72-4892-8265-6d5aa2612b83
Attached burglary_h264_640x480_1000kbps.ts file

**Comment by pmuvvagithub** [comment]
any update onthis?

**Comment by hassanctech** [comment]
@pmuvvagithub I do not think this will work.  So webrtc is a real-time communication, in the pipeline you have created you will read the data from disk and shove it through the pipeline. In general disk/file IO is way faster than network IO so you'll be shoving those frames, and attempting to send them via webrtc *much faster* than realtime, eventually you will spike your RAM/CPU depending on how large the file is it.  Moreover you will need to build in some sort of buffering inside your GStreamer sink element to handle this buffering so the video is set at real-time and not faster than realtime.  The receiver is expecting to receive the video in real-time.

**Comment by hassanctech** [comment]
> After export GST_DEBUG then the video plays very fast

That is exactly what I would expect because it's being sent faster than real time.
