### ISSUE TITLE
[BUG]suspected memory leak during webrtc play

### ISSUE THREAD

**Issue by Ajit1702** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1778]
Facing Memory Issues when compiling and running Base Sample from the "Develop" Branch. 
While Play video through WebRTC viewer we see memory keeps on increasing up to around 7 minutes, after that memory increase stagnates. 

Initial Sample Run
=====================
RSS-5708, VSZ-197324

WebRTC Viewer is started
============================
RSS-7130, VSZ-593352

WebRTC Viewer running for around 7 Minutes
================================================
RSS-11624, VSZ-593428

Once WebRTC Video play as above is Stopped. After We stop the video but Sample is not closed then the complete memory is not freed.

Memory Showing after Video Pause
=================================
RSS-9528, VSZ-587439

On Restarting the Video again we see that More memory is taken and memory further keeps increasing. 
This scenario happens every time we pause and start Video again. This may be an indication of a Memory Leak

Video Run Again after Pause
==============================
RSS-12780, VSZ-712448

**Comment by sirknightj** [comment]
Hi @Ajit1702, could you clarify what you mean by "WebRTC play"? Are you running the kvsWebrtcClientViewer sample? What are you using as `master`? Is this reproducible with the sample out-of-the-box, or are there any code changes that were made?

If you can run `valgrind` and attach the memory leak report, that will help us determine if there is a memory leak occurring, and where it is originating from. If you could also give us some more information about the toolchain used to compile, and the architecture/OS of the device you're running the sample, that would help us out.

I attempted to replicate this using the [JS sample](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html) as master, but found nothing:
```
==143463== HEAP SUMMARY:
==143463==  in use at exit: 0 bytes in 0 blocks
==143463==  total heap usage: 16,968 allocs, 16,968 frees, 8,821,008 bytes allocated
==143463== 
==143463== All heap blocks were freed — no leaks are possible
```

**Comment by disa6302** [comment]
Closing due to no response. Feel free to open a new issue if there are more details.
