### ISSUE TITLE
[Question] timeline of stable releases

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#178]
What's the timeline of releasing some stable versions? There are a couple of key features missing, e.g. congestion control, just curious what's plan and more importantly timeline.

**Comment by chehefen** [comment]
Hi @staowyze, can you tell us what other key features are missing for you other than congestions control? Thanks

**Comment by staowyze** [comment]
I care more about stability, I hope we could have a stable release soon.

**Comment by MushMal** [comment]
I am resolving this issue for now. The latest versions are stable. We will be moving to tagging certain commits with release on minor/major functionality additions/
