### ISSUE TITLE
[BUG] Do not bind unused ports

### ISSUE THREAD

**Issue by kiyotsu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1782]
Hello.
When I run this application as root, it binds port 132.
Port 132 is opened by the usrsctp library.
However, I do not believe this port is used by WebRTC and should not be open.

I checked usrsctp and found the following pull request.
It looks like I can change the initialization function to not bind this port.
https://github.com/sctplab/usrsctp/pull/532

After changing the initialization function and checking, the unused port is no longer bound.
https://github.com/kiyotsu/amazon-kinesis-video-streams-webrtc-sdk-c/commit/300e672a45cffeff3da1b727c2e665c343ecee1c

I would like to see the bind of unused ports fixed.

**SDK version number**
[b2b05c8](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/b2b05c8982beed62e4c589d2890621bf98638153)

**Environment**
 - Ubuntu 22.04

**Comment by jdelapla** [comment]
Hello @kiyotsu ,
Would you like to create a pull request to our develop branch so you can receive credit for this fix? If not I can go ahead and make the change myself.
Thank you for your deep dive.

**Comment by niyatim23** [comment]
The PR to fix the issue has been merged. Thanks for your contribution!
