### ISSUE TITLE
How to link external TLS lib?

### ISSUE THREAD

**Issue by overheat** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1793]
How to link external TLS lib, like openssl or mbedtls.

I have openssl and mbedtls, which provided by sillicon vender. 
How to link those TLS lib instead of this sdk internal one?

**Comment by jdelapla** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/README.md#building-with-dependencies-off
