### ISSUE TITLE
[Bug]: libkvsCommonLws does not recognize BUILD_DEPENDENCIES

### ISSUE THREAD

**Issue by thomas-roos** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1797]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [X] I have all the details the issue requires

### Describe the bug

When building and define BUILD_DEPENDENCIES=OFF it still tries to download amazon-kinesis-video-streams-producer-c.git

### Expected Behavior

do not download

### Current Behavior

download

### Reproduction Steps

yocto, meta-aws

-> patch here: 
[disable_build_deps.patch.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/12515002/disable_build_deps.patch.txt)

### WebRTC C SDK version being used

67468849fc7bf0acaedd74714a635155ce1a83e3

### Compiler and Version used

dont care

### Operating System and version

linux

### Platform being used

linux

**Comment by niyatim23** [comment]
Hi @thomas-roos, that is the intended behavior because the KVS dependency cannot be installed as a system package while the others can be

**Comment by hassanctech** [comment]
In addition since we have pinned the producer c sdk to a particular commit hash in this project, if you are using a different one at runtime that could result in some bad behavior as it's possible they're not compatible.  You cannot use any arbitrary version of producer c with webrtc c sdk.

**Comment by thomas-roos** [comment]
ok, got it. Thank you.
