### ISSUE TITLE
[QUESTION]The definition of KVS_USE_SIGNALING_CHANNEL_THREADPOOL is not found in the SDK build.

### ISSUE THREAD

**Issue by YOSI-yoshidayuji** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1803]
README.md says "The threadpool is enabled by default," But I can't found add_definitions(-DKVS_USE_SIGNALING_CHANNEL_THREADPOOL) in CMakeLists.txt

I modified the function 'createSignalingSync' in Signaling.c for verification purposes.
--
#ifdef KVS_USE_SIGNALING_CHANNEL_THREADPOOL
printf( "threadpool create !\n" );
    CHK_STATUS(threadpoolCreate(&pSignalingClient->pThreadpool, pClientInfo->signalingClientInfo.signalingMessagesMinimumThreads,
                                pClientInfo->signalingClientInfo.signalingMessagesMaximumThreads));
#else
printf( "No treadpool \n" );
#endif
--
When I build it normally, "No threadpool" is displayed. When I write add_definitions(-DKVS_USE_SIGNALING_CHANNEL_THREADPOOL), "threadpool create!" is displayed. 
Am I misunderstanding something?

**Comment by disa6302** [comment]
@YOSI-yoshidayuji , 

It does seem we are missing the add definition in the CMake file. Thank you for pointing it out! 
Would you like to open a PR with the flag change?

**Comment by YOSI-yoshidayuji** [comment]
Thank you for your response. 
According to the regulations of my organization, I do not wish to open in PR.

**Comment by disa6302** [comment]
No problem :) 
Keeping this ticket open till we have the cmake fix merged. Thanks for reporting again!

**Comment by niyatim23** [comment]
We have a new CMake flag for this now `ENABLE_KVS_THREADPOOL`. Currently only available in `develop`
