### ISSUE TITLE
[QUESTION]Addition of LOG_LEVEL_PROFILE in Ver1.8.0 and its implications

### ISSUE THREAD

**Issue by YOSI-yoshidayuji** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1804]
LOG_LEVEL_PROFILE has been added in Ver1.8.0.
It is defined as follows:
--
#define LOG_LEVEL_VERBOSE 1
#define LOG_LEVEL_DEBUG   2
#define LOG_LEVEL_INFO    3
#define LOG_LEVEL_WARN    4
#define LOG_LEVEL_ERROR   5
#define LOG_LEVEL_FATAL   6
#define LOG_LEVEL_SILENT  7
#define LOG_LEVEL_PROFILE 8
--

Even if you specify LOG_LEVEL_SILENT, you cannot suppress the logs because LOG_LEVEL_PROFILE is the strongest.
Doesn't this seem strange considering the meaning of LOG_LEVEL_SILENT ?
Personally, I feel that it would be more appropriate to have the strength between LOG_LEVEL_INFO and LOG_LEVEL_WARN.

**Comment by sirknightj** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-pic/pull/234

**Comment by stefankiesz** [comment]
@YOSI-yoshidayuji, thank you for pointing this out, we have addressed it in the above PR.
