### ISSUE TITLE
[Question] Interactive with Alexa

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#181]
Can kinesis interactive with Alexa? Looks like at least not all the error resiliency tools are implemented in kinesis yet.
quote from https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-rtcsessioncontroller.html
```
Your device or platform must be WebRTC compliant or support the suite of protocols by WebRTC and all supported resiliency mechanisms used in WebRTC. Specifically,

Negative acknowledgement (NACK)
Picture loss indication (PLI)
Full intra request (FIR)
Receiver estimated maximum bitrate (REMB)
```

**Comment by Sean-Der** [comment]
Hey @staowyze 

We do support NACK [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/Rtcp.c#L17-L19).

We are going to add REMB and (PLI/FIR) very soon. You will just need to set callbacks on the Transceiver and you will get a callback with suggested bitrate and when a keyframe is requested.

**Comment by Sean-Der** [comment]
But this client does work with Alexa (and we have customers that already do)

In networks with high packet loss or low bandwidth the experience isn’t as good as it can be though. When we add PLI and REMB it will be better.

We also plan on doing things like FEC which will add even more over the things Alexa requires

**Comment by staowyze** [comment]
Great to know, looking forward to seeing the progress.
