### ISSUE TITLE
[Feature request]: Using a channel name different than the IoT thing name when using IoT credentials

### ISSUE THREAD

**Issue by ocihangir** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1818]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing feature requests
- [x] I have all the details the issue requires

### Describe the feature

The sample application automatically sets the channel name to IoT thing name when using IoT credentials. I want to be able to use channel name different than the IoT thing name.

### Use Case

WebRTC master needs to open channels with different names while using a single IoT certificate. 

### Proposed Solution

When calling `createLwsIotCredentialProvider` in Common.c, IoT thing name should be set, instead of `channelName`. pChannelName should still be set as a command line argument.

### Other Information

I can implement this feature.

**Comment by disa6302** [comment]
@ocihangir , 

There is necessarily no change required within the core SDK for this but the change is a sample level change. You can modify the sample to set both IoT thing name and your channel name. Just make sure to modify the policy doc [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/scripts/generate-iot-credential.sh#L53) to ensure you set the appropriate channel name(s) in the resource block.

Happy to accept a PR contribution if you can modify the sample to allow this!

**Comment by disa6302** [comment]
@ocihangir , 

Quick question. Curious. What is your use case and why do you require a channel name different from IoT thing name?

**Comment by disa6302** [comment]
Closing since PR is merged. Thanks again @ocihangir for your contribution!
