### ISSUE TITLE
[QUESTION] What happens if Websocket/signaling client reboots without telling signaling server

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1835]
I have a question on how the websocket ( webrtc signaling) works if signaling client ungracefully reboots.
The client ( camera / webrtc master) creates a websocket connection with kvs webrtc signaling server to exchange signaling SDP packets.
If suddenly camera ungracefully reboots, it doesn't send packet to signaling server notifying the connection should be closed. So the signaling server doesn't know that the connection is gone.  At this time, if the webrtc viewer sends a new offer in its signaling channel, the offer will be forwarded to the camera at the old tcp port ( used before camera reboots).  Because there is no connection at this port after camera reboots, I guess the camera's tcp stack will respond with RST flag, indicating error/no connection exists.
**When signaling server gets the RST tcp reply, will it re-transmit the offer, or consider the offer already sent?**

**Comment by niyatim23** [comment]
Hi @zwei333, if there is an ungraceful reboot and the websocket is still open, the server assumes it is active and sends the offer to it but the master cannot use it since it is not active. The best way to handle this would be to reconnect to the server once you come back online. The viewer would also know about the disconnection since it did not hear back on the offer so have it send the offer back again. It cannot consider that the offer was sent

Closing assuming answered

**Comment by zwei333** [comment]
Thank you for the reply.  The problem we have seen is, after the ungraceful reboot, the offer and a few ICE candidates are delivered to the old port.  Of course, they will be dropped.  When new websocket connection is established between signaling server and master, the offer and the first a few ICE candidates are not re-transmitted by the signaling server.  Master only gets the remaining ICE candidates.  
I wonder what is the expected behavior for the server.  Should it re-transmitted those SDP packets that are not properly Acked?  Or, server will need the viewer to send another offer?

**Comment by niyatim23** [comment]
The server will cache the message for them until message TTL expires. So camera should reconnect and stay alive, and the server will be able to get message on next reconnect

**Comment by disa6302** [comment]
To clarify, the message TTL is configured as part of `createChannel`. The default is set to 60 seconds. The max you can set it to is 120 seconds.

**Comment by zwei333** [comment]
We are using the message cache.  Our viewers sometime send the offer before master is ready. 
But for ungraceful reboot, the first a few messages, including the offer, are gone forever.  It is 100% reproducible with our camera.  The server won't re-transmit them even after new connection is ready.
Using tcpdump, we can see those messages are delivered to the old port.  So we are wondering how the server treats the messages delivered to the old port.  They are not Acked.  tcp stack should only send RST reply.  So they shouldn't be considered successfully sent and should be re-transmitted.

**Comment by niyatim23** [comment]
If the websocket is connected, the server assumes that the message is transmitted. There are no ACKs in this case. When there is an abrupt shutdown, the old websocket is still open and connected so the server assumes it delivered the message. There is no way to handle this on the server-side. Application-level retries are the right way to go here, the application should consider re-sending the offer if the other peer does not send an SDP answer

**Comment by zwei333** [comment]
Thank you!  It helps understand the server behavior.  We will work on the application to re-send the offer
