### ISSUE TITLE
[Bug]: Memory leak in signalingMessageReceived in samples/Common.c file.

### ISSUE THREAD

**Issue by coder0201200** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1841]
### Please confirm you have already done the following

- [ ] I have searched the repository for related/existing bug reports
- [ ] I have all the details the issue requires

### Describe the bug

I am using the kvsWebRTCClientMaster.c in that I had found one memory leak, please find the below observation.
KVS SDK version: v1.8.1

In samples/Common.c when signalingMessageReceived is getting called at that time memory leak occurs from pReceivedSignalingMessageCopy.

In signalingMessageReceived it will go in switch case SIGNALING_MESSAGE_TYPE_ICE_CANDIDATE. In that switch case, memory gets allocated for pReceivedSignalingMessageCopy. after that it is queued and after that NULL is assigned to pReceivedSignalingMessageCopy, before doing SAFE_MEMFREE(pReceivedSignalingMessageCopy).

So when SAFE_MEMFREE(pReceivedSignalingMessageCopy) is getting called at that time pReceivedSignalingMessageCopy is NULL, so memory will not get free.

To verify this leak I added prints in the dequeue side before every free, but the allocated same memory location is not getting free at the dequeue side also.

When we are starting streaming at that time this memory leak is happening 2-3 times.

Please let me know if more information is needed.

### Expected Behavior

Allocated memory for pReceivedSignalingMessageCopy should be gets free.

### Current Behavior

Allocated memory for pReceivedSignalingMessageCopy is not getting free.

### Reproduction Steps

Run the sample app kvsWebRTCClientMaster.c in the device and start streaming using the sample js web page.

### WebRTC C SDK version being used

1.8.1

### Compiler and Version used

linaro-aarch64-2020.09-gcc10.2-linux5.4/bin/aarch64-linux-gnu-gcc

### Operating System and version

Linux OS

### Platform being used

Arm

**Comment by sirknightj** [comment]
Hi @coder0201200, I ran `valgrind` and didn't see any indication of a memory leak. I ran the following using [latest master](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/15e60193456709a3786f7c0f237c49ea7bd9c81f).

Procedure:
1. Start master: `valgrind --leak-check=full   --show-leak-kinds=all   --track-origins=yes   --verbose   --track-fds=yes   --log-file=valgrind-out.txt   ./samples/kvsWebrtcClientMaster demo-channel`
2. Join as viewer using [JS SDK](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html). Checked: Send video, send audio, enable data channel, STUN/TURN, use Trickle Ice.
3. After I see the media on the viewer side, wait 10 seconds.
4. Interrupt the valgrind/master using `ctrl+c`. Look at the `valgrind-out.txt` file.
 
```
==144143== HEAP SUMMARY:
==144143==     in use at exit: 0 bytes in 0 blocks
==144143==   total heap usage: 30,288 allocs, 30,288 frees, 23,422,845 bytes allocated
==144143== 
==144143== All heap blocks were freed -- no leaks are possible
```

Would you be able to attach a `valgrind` output showing the memory leak? Thanks.

**Comment by coder0201200** [comment]
@sirknightj Have you checked with start and stop streaming multiple times(like 15 times) using js sample page?
Because I observed that pReceivedSignalingMessageCopy is not getting assigned every times.

unfortunately i am not able to run valgrind on my device due to memory constrain.

**Comment by jdelapla** [comment]
Hello @coder0201200 ,
This is not a memory leak, this is by design. This pending message queue is an implementation on the sample that stores remote candidate received from a previous session & remote peer. The candidates are retried on the next SDP offer/answer (common is supporting both viewer and master cases) in an attempt to reduce latency.

You're correct that the memory is not freed in the same function, because instead the objects are placed in a queue, and that is also placed in another hash. The next time the same peerClientId is present in a SDP offer/answer signaling message, the switch case state will get access to the queue from the hash, and then pop each item off the queue and submit them to the ice agent.

You can see this functionality in submitPendingIceCandidate().

Thank you for expressing interest in our sample code implementation.
