### ISSUE TITLE
[QUESTION] There is no sound when I play DASH with G711 on Chrome, but there is sound on Safari.

### ISSUE THREAD

**Issue by aqi-wyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1844]
There is no sound when I play DASH with G711 on Chrome, but there is sound on Safari.

I try both G711-a and G711-u, but Dash cannot play with sound on Chrome.
I use Dash.js to play our dash stream.

If I play WebRTC or MP4 file with G711 on Chrome, both of them can play sound.

I am not sure it is a Chrome Browser issue, or AWS KVS Dash file is not compatible with Chrome.

**Comment by hassanctech** [comment]
Have you tried with a DASH file with G711 audio that is not from AWS (some other source) that you know works otherwise.

**Comment by aqi-wyze** [comment]
Yes, and DASH file with G711 audio cannot played on Chrome either from AWS or from other Source. 
So there are two assumption: 1, Chrome doesn't support DASH file with G711 audio, but WebRTC support G711 on Chrome.
2, Our client implementation, dash.js, doesn't support DASH file with G711 audio on Chrome. 

So I wonder that had your team notice this issue before and is there other customer had solved this issue?

**Comment by niyatim23** [comment]
Hi @aqi-wyze, just wanted to check if you're trying to use the media ingestion feature with WebRTC? Are you trying to playback the video ingested via WebRTC? What SDK are you using to upload the media to KVS? What is your video codec?

**Comment by niyatim23** [comment]
When you say KVS with DASH, do you mean the test webpage [here](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html)?

**Comment by sharadrj** [comment]
@aqi-wyze :  can you clarify if this issue is about KVS WebRTC or with KVS Streams/Producer SDKs? We are confused because you have filed this issue in WebRTC Github repo, but MPEG-DASH is a Streams playback feature.

**Comment by aqi-wyze** [comment]
I thought you are same team, but if not, which repository I can ask for help?

**Comment by niyatim23** [comment]
Although KVS owns these SDKs, we expect customers to open issues corresponding to a particular SDK in its own repository. Are you using the Producer SDK or the WebRTC SDK? Please open this issue in https://github.com/awslabs/amazon-kinesis-video-streams-producer-c or https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp or confirm if the issue rightly belong in this repository before we proceed.
