### ISSUE TITLE
Kinesis WebRTC Viewer sample in AWS Lambda environment

### ISSUE THREAD

**Issue by farooq-zaman-82** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1845]
I have compiled Viewer example as a shared library and I am using this library in Python to establish WebRTC connection. Idea is to receive video from master and apply AI on video frames. I am also using data channel for communication between master and viewer. I am running this whole setup in AWS lambda environment.

All works well when there's a single user accessing the service but when multiple users start using the service it goes all wrong and processing is stuck after a while. Appreciate if you could guide me on how to fix this issue. Is it because of global variables in Viewer sample like gSampleConfiguration and pDataChannel that are causing the issue? or it has to do with lambda environment?

**Comment by hassanctech** [comment]
Can you please clarify what issue you are hitting?  Can you attach some logs from the application and please explain your architecture.  Which version of the SDK are you using.  What platform / toolchain are you using.  You mention you're using the viewer, so what is the master side running / how is it setup?

**Comment by farooq-zaman-82** [comment]
Hi @hassanctech , thanks for the response. I have attached the architecture I am using for my solution. I have also included Viewer shared library that I am using.

I intend to use Viewer as an AI agent deployed as a lambda function. Purpose of the AI agent is to participate in the communication between two users silently and process video from master using AI technologies. Due to data channel both master and secondary viewer can receive results in realtime. One potential use case is Telehealth.

Everything seems to be working right. Only problem is that AI agent (Viewer in lambda function) goes haywire when multiple users are using the system and usually it's stuck in the middle of processing video from master. In my understanding, lambda function provides sandbox environment so technically one user shouldn't affect the other user.

I would appreciate a lot if you could guide me on how to resolve these issues.

![AI Bot Architecture](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/59040931/e6a056a5-792f-4133-a310-638bb7fe2d1f)
![AWS Kinesis Architecture](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/59040931/f55d152e-4870-4461-86db-9b96bc4b9261)
[kvsWebRTCClientViewer.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/13461089/kvsWebRTCClientViewer.zip)

**Comment by stefankiesz** [comment]
Hi, can you please provide [verbose](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c?tab=readme-ov-file#sample-kvswebrtcclientmastergstsample:~:text=currently%20available%20are%3A-,LOG_LEVEL_VERBOSE,-%2D%2D%2D%2D%201) level logs from both the master and viewer end demonstrating the issue you are experiencing.
