### ISSUE TITLE
Random ERROR   dtlsSessionProcessPacket(): operation returned status code: 0x59000004

### ISSUE THREAD

**Issue by pof2** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1860]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [X] I have all the details the issue requires

### Describe the bug

I'm using (a slightly modded) kvsWebrtcClientViewer to measure performance of a webrtc device (also using kinesis SDK). Sometimes when I run the viewer I see the following error:

ERROR   dtlsSessionProcessPacket(): operation returned status code: 0x59000004

When I see the error the connection always takes about 1s extra to be established. The connection does not fails.

Attaching complete logs of bad run and a good run:

[client_bad.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/13501676/client_bad.txt)
[client_good.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/13501677/client_good.txt)

### Expected Behavior

no error

### Current Behavior

ERROR   dtlsSessionProcessPacket(): operation returned status code: 0x59000004

### Reproduction Steps

Run kvsWebrtcClientViewer in a loop. About 20% of the runs I see the error

### WebRTC C SDK version being used

0ae9ec6b80deff9df724555927fb6595a23054f1 (tag: v1.9.0, origin/master)

### Compiler and Version used

gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 

### Operating System and version

Ubuntu 22.04

### Platform being used

Linux

**Comment by sirknightj** [comment]
Hi @pof2,
 
 The status code 0x59000004 is: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0ae9ec6b80deff9df724555927fb6595a23054f1/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L191
 
 It's only thrown here:
 
 https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0ae9ec6b80deff9df724555927fb6595a23054f1/src/source/Crypto/Dtls_openssl.c#L449
 
 This would indicate that the DTLS Session has not been set up. The DTLS session is set up when the ICE agent moves to ready state.
 
 https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0ae9ec6b80deff9df724555927fb6595a23054f1/src/source/Crypto/Dtls_openssl.c#L375-L377
 
 https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0ae9ec6b80deff9df724555927fb6595a23054f1/src/source/PeerConnection/PeerConnection.c#L427-L432
 
Your logs indicate that this occurred before the ready state.
 
 ```
 1-29 14:15:31.310 ERROR   dtlsSessionProcessPacket(): operation returned status code: 0x59000004
 1-29 14:15:31.321 INFO    stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_CONNECTED.
 1-29 14:15:31.371 INFO    stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CONNECTED to ICE_AGENT_STATE_NOMINATING.
 1-29 14:15:31.421 INFO    stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_NOMINATING to ICE_AGENT_STATE_READY.
 ```
 
Between the two runs, I did notice that the DTLS initialization for your run labeled "good" is:
 ```
 1-29 14:19:42.757 PROFILE dtlsSessionChangeState(): [DTLS initialization completion] Time taken: 40 ms
 ```
 and the DTLS initialization for your run labeled "bad" is:
 ```
 1-29 14:15:32.339 PROFILE dtlsSessionChangeState(): [DTLS initialization completion] Time taken: 1018 ms
 ```
 
Most likely, your application encountered a DTLS handshake failure and the 1s extra delay is from the retry from openssl. Could you also share some more information about your test setup? Are you starting the viewer before the master or maybe repeatedly connecting the viewer to the same master?

If you'd like, you can also try the develop branch, as some additional log lines might be present to see something. If you could attach the verbose master logs too that might help as well.

**Comment by pof2** [comment]
Hello,

> Hi @pof2,
> 
> The status code 0x59000004 is:
> 
> https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0ae9ec6b80deff9df724555927fb6595a23054f1/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L191
> 
> It's only thrown here:
> 
> https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0ae9ec6b80deff9df724555927fb6595a23054f1/src/source/Crypto/Dtls_openssl.c#L449

I have, as an experiment, already tried commenting out line 449. That makes the problem go away and I have not seen any negative side effects. Ran over 1000 successful connects in a row.
 
> This would indicate that the DTLS Session has not been set up. The DTLS session is set up when the ICE agent moves to ready state.
> 
> https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0ae9ec6b80deff9df724555927fb6595a23054f1/src/source/Crypto/Dtls_openssl.c#L375-L377
> 
> https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0ae9ec6b80deff9df724555927fb6595a23054f1/src/source/PeerConnection/PeerConnection.c#L427-L432
> 
> Your logs indicate that this occurred before the ready state.
> 
> ```
> 1-29 14:15:31.310 ERROR   dtlsSessionProcessPacket(): operation returned status code: 0x59000004
> 1-29 14:15:31.321 INFO    stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_CONNECTED.
> 1-29 14:15:31.371 INFO    stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CONNECTED to ICE_AGENT_STATE_NOMINATING.
> 1-29 14:15:31.421 INFO    stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_NOMINATING to ICE_AGENT_STATE_READY.
> ```
> 
> Between the two runs, I did notice that the DTLS initialization for your run labeled "good" is:
> 
> ```
> 1-29 14:19:42.757 PROFILE dtlsSessionChangeState(): [DTLS initialization completion] Time taken: 40 ms
> ```
> 
> and the DTLS initialization for your run labeled "bad" is:
> 
> ```
> 1-29 14:15:32.339 PROFILE dtlsSessionChangeState(): [DTLS initialization completion] Time taken: 1018 ms
> ```
> 
> Most likely, your application encountered a DTLS handshake failure and the 1s extra delay is from the retry from openssl. Could you also share some more information about your test setup? Are you starting the viewer before the master or maybe repeatedly connecting the viewer to the same master?
> 
> If you'd like, you can also try the develop branch, as some additional log lines might be present to see something. If you could attach the verbose master logs too that might help as well.

Master is indeed doing DTLS retry:

dtlsTransmissionTimerCallback(): DTLS handshake timeout event, retransmit

My setup is this:

* Master is using SDK 1.8.1.
* Master is always on, logged in with it's signalling client.
* Client is repeatedly connecting to same master.

New logs taken at client  and master are attached. Clocks are same to about a second.

Client
2023-12-04 20:40:49.325 ERROR   dtlsSessionProcessPacket(): operation returned status code: 0x59000004

Master
2023-12-04 20:40:50.015 DEBUG   dtlsTransmissionTimerCallback(): DTLS handshake timeout event, retransmit

[dtls-err-client.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/13551334/dtls-err-client.txt)
[dtls-err-master.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/13551346/dtls-err-master.txt)

**Comment by pof2** [comment]
Hi again,

> If you'd like, you can also try the develop branch, as some additional log lines might be present to see something. If you could attach the verbose master logs too that might help as well.

Sure. I was able to reproduce also on develop (824484423a4910e734231ef353919a2976384956).

[dtls-err-develop.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/13551592/dtls-err-develop.txt)

**Comment by disa6302** [comment]
I see the handshake succeeds in this case and is done in 25 ms too. However, in develop, we changed the way we were calculating the DTLS set up time in the sense, we start the time calculation only when we receive the ClientHello message whereas earlier, we started calculating the moment the DTLS initialization began irrespective of receiving the ClientHello message. About the retry, it is likely your DTLS is being started before the pair is actually selected and that is what is causing the timeout. We fixed this in develop to ensure DTLS does not start until a candidate pair is selected for p2p. Hence, you do not see any timeout events on develop.

Overall, the error code is not causing any streaming issues because it seems there is active media exchange. The error code 0x59000004 is an indication that the SDK is receiving the DTLS packet before DTLS is set up here and the other end is retrying sending the ClientHello again because of a timeout event there, which is why despite this code, DTLS initialization succeeds. Hence, this is not a fatal code in this case.

Closing assuming answered. Please feel free to reopen if you face any further issues because of this status code.
