### ISSUE TITLE
Is it possible that Webapp client uses kvs-webrtc-sdk-js while the server side uses kvs-webrtc-sdk-c?

### ISSUE THREAD

**Issue by springboot999** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1866]
Hi all,

I want to build a service in which users stream videos from a webapp running on their mobile devices to AWS. On the client side I plan to use kvs-webrtc-sdk-js. On the server side, I will have an app written in C++ or C running on an EC2 instance to receive the streams and extract their frames for analysis.

Can I use this kvs-webrtc-sdk-c on the server side, or do I have to stick to the kvs-webrtc-sdk-js to be consistent with the client side?

Thanks.

**Comment by sirknightj** [comment]
Yes, you can use this SDK in an EC2. The WebRTC SDK's are designed to be compatible with each other - this SDK [is compatible](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/webrtc-sdks.html) with the JS, Android, and iOS SDK's.

Note that we have the [WebRTC Ingestion](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/webrtc-ingestion.html) feature available, which captures the WebRTC media and uploads it to a Kinesis Video Stream (which you can then use other services Amazon Rekognition or Amazon Sagemaker to analyze).
