### ISSUE TITLE
[QUESTION] kvsWebRTCClientBasicStorageSession  Sample

### ISSUE THREAD

**Issue by Jeremyforwork** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1871]
Hello， is there a sample about kvsWebRTCClientBasicStorageSession that has not been launched yet？

**Comment by Jeremyforwork** [comment]
I didn't see kvsWebRTCClientBasicStorageSession  after I 'make'

**Comment by sirknightj** [comment]
Hi @Jeremyforwork,

The WebRTC ingestion feature has been launched and the samples it's in are "kvsWebRTCClientMaster" and "kvsWebrtcClientMasterGstSample". Wondering if you could provide some more information on where you're seeing "kvsWebRTCClientBasicStorageSession"? Is there a documentation page that is out of date?

See https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/ingest-media.html#ingest-webrtc-sdk or https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#running-the-samples.

For "kvsWebRTCClientMaster", the 2nd argument needs to be "1". 

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0ae9ec6b80deff9df724555927fb6595a23054f1/samples/kvsWebRTCClientMaster.c#L34-L36

And for "kvsWebrtcClientMasterGstSample", the 2rd argument needs to be "audio-video-storage".

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/0ae9ec6b80deff9df724555927fb6595a23054f1/samples/kvsWebrtcClientMasterGstSample.c#L423-L426

**Comment by disa6302** [comment]
@Jeremyforwork ,

Thanks for bringing the doc discrepancy to our attention, we will work on getting it fixed.

I would recommend trying out Storage using our official release 1.9.0. Closing this ticket now and tracking documentation issue internally. Please feel free to reach out if you face issues while running the sample.
