### ISSUE TITLE
[QUESTION] lws_client_handshake: got bad HTTP response '403'

### ISSUE THREAD

**Issue by WeiWei00123** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1875]
When I connect my IP camera to webrtc, I encounter an error "lws_client_handshake: got bad HTTP response '403'". My IP camera uses OpenSSL version 3.1.0 for its system. I suspect this version might be the cause of the error. Is there an SDK version available that supports OpenSSL 3.1.0?

![messageImage_1701914644732](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/143770121/be009e68-37ee-43db-97e4-19b8c73429e1)

**Comment by sirknightj** [comment]
Hi @WeiWei00123, we're working on that in this PR. https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1840

Note that if you build with dependencies off, it will use the openssl installed on your system. Here are the instructions for that. https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#building-with-dependencies-off

Could you share which branch you're running on? If you're on develop, can you try with master?

**Comment by disa6302** [comment]
@WeiWei00123 , 

Which version of the SDK are you using?

**Comment by WeiWei00123** [comment]
@sirknightj @disa6302 thank you for your reply, I will try #1840 later, and my sdk version is v1.8.1

**Comment by niyatim23** [comment]
Hi @WeiWei00123, did using the newer version of the SDK fix the issue for you? (A newer version- 1.9.1 is also available now)

**Comment by WeiWei00123** [comment]
@niyatim23 thank you for your reply, this issue has been resolved
