### ISSUE TITLE
[QUESTION] Unable to setup dependencies in sdk to include in cpp

### ISSUE THREAD

**Issue by shreyas-wt** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1884]
I am setting kvs webRTC C SDK for my cpp program. While I followed the steps in the read me I am unable to load the dependent include files like com/amazonaws/kinesis/video/client/Include.h and com/amazonaws/kinesis/video/common/Include.h

Steps followed
git clone --recursive https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c.git

mkdir -p amazon-kinesis-video-streams-webrtc-sdk-c/build; cd amazon-kinesis-video-streams-webrtc-sdk-c/build; 

cmake ..  -DBUILD_STATIC_LIBS=TRUE

make

(I also tried to manually clone submodules before building : git submodule update --init --recursive)

when I try to include the webrtcclient/include.h in my cpp program I get #include <com/amazonaws/kinesis/video/client/Include.h> not found. 

The sub modules are not loaded.

Please need help setting this up
Thanks

**Comment by YOSI-yoshidayuji** [comment]
I am not a member of the development team, but I can probably answer your question. 
If you are able to build the sample program, you can resolve the issue by adding the include directories for the header files using the 
include_directories command in CMake. You may also need the link_directories  command.

**Comment by shreyas-wt** [comment]
Thanks for the answer. I did something similar. I found a soln in here with a custom CMakeList that I used directly with my program.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/202 has the CmakeList that fetches the code and sets all the directories.

I was running on Mac OS 14 and I was giving me another error inttypes.h not found. Switched to Ubuntu and it worked.
I am still having some issues with SSL but the build worked

Thanks

**Comment by hassanctech** [comment]
Can you try with the latest `develop` branch?  The static build should be set up properly there.  No clone recurse is necessary for this SDK.  This project does not use git submodules.

**Comment by sirknightj** [comment]
I was able to get around it in the current master by doing `brew unlink openssl`.

**Comment by shreyas-wt** [comment]
Thanks @hassanctech and @sirknightj I will try these. I had issue with setting up on Mac OS 14 as I was getting inttypes.h not found. Switched to Ubuntu and used the other CMakeLists and I had got that SSL error "Unable to get local issuer".

I will try again with the steps you suggested and update here.

**Comment by hassanctech** [comment]
@shreyas-wt Regarding the `inttypes.h` not being found this is because you need to include the standard library headers that are already installed on MacOS.  You should be able to set this up properly by exporting the following env var:
```
export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
```

**Comment by hassanctech** [comment]
@shreyas-wt Can you please use the latest `develop`.  There is an issue with the static build in `master` at the moment but it should be fixed in the latest `develop` branch.

```
git clone https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c.git
cd amazon-kinesis-video-streams-webrtc-sdk-c
git checkout develop
mkdir build
cd build
cmake .. -DBUILD_STATIC_LIBS=TRUE
make
```

This should work now, please report back if it does not.

**Comment by sirknightj** [comment]
Regarding the earlier-mentioned SSL error, please make sure that the `.pem` file has been added to your SSL folder (`/etc/ssl/`).

https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producersdk-cpp-rpi-software.html -- step 2

Closing as this should be fixed in https://github.com/awslabs/amazon-kinesis-video-streams-pic/pull/232 and no comments were added in the last 2w.
