### ISSUE TITLE
[QUESTION] maybe  a bug

### ISSUE THREAD

**Issue by waterfoxfox** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1899]
very nice open source project,    i am studying the code,  then found something maybe little bug.   

File:   PeerConnection.c   
Function:  sendPacketToRtpReceiver 
Code:  pTransceiver->inboundStats.received.packetsDiscarded = packetsDiscarded;      
Should be:   pTransceiver->inboundStats.received.packetsDiscarded += packetsDiscarded;

**Comment by disa6302** [comment]
Thank you for the report @waterfoxfox ! Opened a PR for this.
