### ISSUE TITLE
[Bug]: executeFailedIceAgentState(): IceAgent failed with 0x5a00000d

### ISSUE THREAD

**Issue by koratshail** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1905]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [X] I have all the details the issue requires

### Describe the bug

I am using the sample application provided in Webrtc SDK v1.91. The peer connection can't be established with the error "IceAgent failed with 0x5a00000d" Sometimes, even the network between my phone and embedded device are both fine, and the offer/answer SDP and ICE candidates are all correct.

### Expected Behavior

The peer connection should be established and users can play the live streaming if the network are both fine.

### Current Behavior

[notworking_webrtc_log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/13992489/notworking_webrtc_log.txt)

Please find attached detailed log messages. I am not able to understand the exact what's problem of not starting the live stream between an Embedded device and a Phone. 

### Reproduction Steps

Executing [kvsWebrtcClientMasterGstSample.c](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebrtcClientMasterGstSample.c) code with IoT certificate method and I can see live stream between two device in 4/10 ration only. 

### WebRTC C SDK version being used

1.9.1

### Compiler and Version used

gcc-linaro-10.2.1

### Operating System and version

Linux

### Platform being used

Linux

**Comment by disa6302** [comment]
@koratshail , 

Can you provide details on what your set up looks like? 
1. Where do the master and viewer reside - which region?
2. What device is the master and viewer running on

From the logs, it seems the network is quite slow. The time taken to send answer from receiving offer is 6 seconds, which is extremely long, indicating the websocket operation is slow on the device. It also seems TURN is failing to create permission within the expected time. So it is a timeout issue.

**Comment by koratshail** [comment]
@disa6302 ,
Thank you for your reply.

**Where do the master and viewer reside - which region?**

- As a Viewer, I have two options, a Mobile Phone app and a Media player inside the AWS management console. I am using both for my testing. As far as I know, both Viewer and master regions are **us-east-2**

**What device is the master and viewer running on**

- As I have said I have two options for the viewer, Mobile app, and Media player from the AWS management console. For the master device, I am using an Embedded device having Linux running and using KVS Webrtc C SDK.

If you observed time-outs in certain operations link SDP offer/answer TURN connections due to bad network, Can I increase the default time-out period to certain levels? **Could you guide me on what time-outs I should increase to make connections between Master and Viewer?** I do not worry if its take a long time to exchange and make connections.

**Comment by koratshail** [comment]
@disa6302 
Thanks for your suggestion.

As per your initial response, you stated, "_The time taken to send the answer from receiving the offer is 6 seconds._" I would like to verify that the log messages I provided indicate approximately 14 seconds with the entry: "**PROFILE signalingSendMessageSync(): [Offer Received to Answer Sent time] Time taken: 14512 ms.**"

Just wanted to confirm that are you looking at the correct log messages right?

Following are the increased time-outs for ICE agents:
```
#define KVS_ICE_GATHER_REFLEXIVE_AND_RELAYED_CANDIDATE_TIMEOUT (60 * HUNDREDS_OF_NANOS_IN_A_SECOND)
#define KVS_ICE_CONNECTIVITY_CHECK_TIMEOUT                     (60 * HUNDREDS_OF_NANOS_IN_A_SECOND)
#define KVS_ICE_CANDIDATE_NOMINATION_TIMEOUT                   (60 * HUNDREDS_OF_NANOS_IN_A_SECOND)
#define KVS_ICE_SEND_KEEP_ALIVE_INTERVAL                       (15 * HUNDREDS_OF_NANOS_IN_A_SECOND)
#define KVS_ICE_TURN_CONNECTION_SHUTDOWN_TIMEOUT               (20 * HUNDREDS_OF_NANOS_IN_A_SECOND)
#define KVS_ICE_DEFAULT_TIMER_START_DELAY                      (3 * HUNDREDS_OF_NANOS_IN_A_MILLISECOND)
#define KVS_ICE_SHORT_CHECK_DELAY                              (50 * HUNDREDS_OF_NANOS_IN_A_MILLISECOND)

// Ta in https://tools.ietf.org/html/rfc8445
#define KVS_ICE_CONNECTION_CHECK_POLLING_INTERVAL  (100 * HUNDREDS_OF_NANOS_IN_A_MILLISECOND)
#define KVS_ICE_STATE_READY_TIMER_POLLING_INTERVAL (1 * HUNDREDS_OF_NANOS_IN_A_SECOND)
/* Control the calling rate of iceCandidateGatheringTimerTask. Can affect STUN TURN candidate gathering time */
#define KVS_ICE_GATHER_CANDIDATE_TIMER_POLLING_INTERVAL (50 * HUNDREDS_OF_NANOS_IN_A_MILLISECOND)

/* ICE should've received at least one keep alive within this period. Since keep alives are send every 15s */
#define KVS_ICE_ENTESTATE_FAILED_GRACE_PERIOD        (25 * HUNDREDS_OF_NANOS_IN_A_SECOND)R_STATE_DISCONNECTION_GRACE_PERIOD (2 * KVS_ICE_SEND_KEEP_ALIVE_INTERVAL)
#define KVS_ICE_ENTER_STATE_FAILED_GRACE_PERIOD        (25 * HUNDREDS_OF_NANOS_IN_A_SECOND)
```

Modified Turn connections time-outs:

```
#define TURN_PERMISSION_LIFETIME                 (300 * HUNDREDS_OF_NANOS_IN_A_SECOND)
#define DEFAULT_TURN_TIMER_INTERVAL_BEFORE_READY (50 * HUNDREDS_OF_NANOS_IN_A_MILLISECOND)
#define DEFAULT_TURN_TIMER_INTERVAL_AFTER_READY  (1 * HUNDREDS_OF_NANOS_IN_A_SECOND)
#define DEFAULT_TURN_SEND_REFRESH_INVERVAL       (1 * HUNDREDS_OF_NANOS_IN_A_SECOND)

// turn state timeouts
#define DEFAULT_TURN_SOCKET_CONNECT_TIMEOUT    (50 * HUNDREDS_OF_NANOS_IN_A_SECOND) //5
#define DEFAULT_TURN_GET_CREDENTIAL_TIMEOUT    (50 * HUNDREDS_OF_NANOS_IN_A_SECOND) //5
#define DEFAULT_TURN_ALLOCATION_TIMEOUT        (50 * HUNDREDS_OF_NANOS_IN_A_SECOND) //5
#define DEFAULT_TURN_CREATE_PERMISSION_TIMEOUT (20 * HUNDREDS_OF_NANOS_IN_A_SECOND) //2
#define DEFAULT_TURN_BIND_CHANNEL_TIMEOUT      (30 * HUNDREDS_OF_NANOS_IN_A_SECOND) //3
#define DEFAULT_TURN_CLEAN_UP_TIMEOUT          (100 * HUNDREDS_OF_NANOS_IN_A_SECOND) //100
```
Are there any additional adjustments you believe should be made to prevent timeouts when establishing a live stream?

**Comment by disa6302** [comment]
@koratshail , 

I looked at the one with 6 seconds. I see only one log file attached in the description. Either ways, the device seems to be extremely slow and the fields you added are the ones you can adjust if you are not looking to understand why the operations take very long.
