### ISSUE TITLE
[Bug]: No streaming on the Kinesis Page

### ISSUE THREAD

**Issue by Moadib129** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1911]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [X] I have all the details the issue requires

### Describe the bug

I am trying to stream from my virtual box linux machine a video as a master by running kvsWebrtcClientMaster RpiCamera(Signaling channel) and i get these results
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/c1012fa8-155c-48a6-9c67-b84fb63bd2ca)

When i view the stream, it just shows a blank screen a  background music and a ball running 
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/4b92ea6b-4c28-4f68-be3e-cf95c518e7f2)

I dont know how to get the video and audio

### Expected Behavior

It should show the video and audio from the camera

### Current Behavior

It only shows a ball rotating with a blank screen and ball moving on it on kinesis signaling channel

### Reproduction Steps

![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/fa8c3c28-b89d-42fc-aaea-af5704c525e5)

### WebRTC C SDK version being used

Latest

### Compiler and Version used

N/A

### Operating System and version

Oracle Vm box - Debian

### Platform being used

Debian

**Comment by disa6302** [comment]
Please use the `kvsWebrtcClientMasterGstSample` sample and set up your gstreamer pipeline. The sample you are using uses pre-canned frames for demo.

**Comment by Moadib129** [comment]
I tried running that as well but it keeps loading and receives no information. It is just stuck.

I used this command ./samples.kvsWebrtcClientMasterGstSample RpiCamera video-only devicesrc
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/cbba7f36-a026-4120-90da-32291d31c495)

This is on my signaling channel
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/ba8a29b5-7121-437c-8ac7-1cc94e6c2d21)

**Comment by disa6302** [comment]
@Moadib129 ,

You would have to modify the gstreamer pipeline to use the raspberry pi camera. `devicesrc` uses autovideosrc. If you have a camera connected RPi, you would need to find the

**Comment by Moadib129** [comment]
I am using a debian image on Oracle virtual machine on Windows 10 and a usb camera is attached with it

**Comment by Moadib129** [comment]
How can i edit the pipeline,
should i pass argument devicesrc /dev/video0 or devicesrc=/dev/video0

**Comment by hassanctech** [comment]
If you specify `devicesrc` for audio/video you will get the pipeline specified here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebrtcClientMasterGstSample.c#L208

If you have `v4l2src` available (you can check by running `gst-inspect-1.0 v4l2src`), if it's available you can replace `autovideosrc` in the sample code with `v4l2src device=/dev/video0`

Once you have that now you have to see what encoding is the video

**Comment by Moadib129** [comment]
Hi @hassanctech ,
I have already tried that here is the code:
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/e627ac13-813f-467b-9872-729083288a0d)

The command is used was
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/46aace62-59ac-44fb-8a24-b40026599654)


and when i open the Kinesis video stream, these messages are printed
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/58b3a4fe-e0e9-4029-8450-0a5cbfd18a4e)

Here is the screenshot from kinesis page
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/109261728/1e51b72d-e57a-441e-83eb-39fd274c7eb4)

**Comment by hassanctech** [comment]
To make sure your source is working properly, can you try the GStreamer pipeline with a `filesink` and make sure you can stream properly there?

**Comment by Shreshtha2000** [comment]
I am also facing the same issue did you find the fix for it?

**Comment by Moadib129** [comment]
@hassanctech Thanks for the insight I added the "v4l2" command. It turned out I had to use "\" before using double qoutes in "/dev/video0".

@Shreshtha2000 This worked

**Comment by Shreshtha2000** [comment]
just for clarification is the final line like this? "v4l2src "" device=/dev/video0" "! queue !
