### ISSUE TITLE
ICE bug due to stale pBindingRequest

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#193]
`pIceAgent->pBindingRequest` is built and cached before remote description is available, which causes invalid `Username` attribute. `pIceAgent->pBindingRequest` is not updated even the remote description arrives.
As far as I tested, safari and chrome would reject STUN binding due to the invalid `Username` attribute, and caused ICE failure.

**Comment by chehefen** [comment]
Hi @staowyze, was there a bug that you ran into? if so can you tell us the step to reproduce? When the remote description becomes available, iceAgentStartAgent get called and username is updated there: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.c#L431

**Comment by staowyze** [comment]
I didn't test against the latest master code, I think what happened in my case was `pIceAgent->iceAgentState` moves to `ICE_AGENT_STATE_CHECK_CONNECTION` before having the remote description. Then `pBindingRequest` is not updated because `iceAgentCheckConnectionStateSetup` is not called anymore, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.c#L431. Would it still possible with the latest master code?

**Comment by chehefen** [comment]
which sample were you running?

**Comment by staowyze** [comment]
I built my own sample application, I fixed the issue by
```
src/source/Ice/IceAgent.c
@@ -428,6 +428,17 @@ STATUS iceAgentStartAgent(PIceAgent pIceAgent, PCHAR remoteUsername, PCHAR remot
     }
     SNPRINTF(pIceAgent->combinedUserName, ARRAY_SIZE(pIceAgent->combinedUserName), "%s:%s", pIceAgent->remoteUsername, pIceAgent->localUsername);
 
+    if (pIceAgent->pBindingRequest != NULL) {
+        CHK_STATUS(freeStunPacket(&pIceAgent->pBindingRequest));
+    }
+    CHK_STATUS(createStunPacket(STUN_PACKET_TYPE_BINDING_REQUEST, NULL, &pIceAgent->pBindingRequest));
+    CHK_STATUS(appendStunUsernameAttribute(pIceAgent->pBindingRequest, pIceAgent->combinedUserName));
+    CHK_STATUS(appendStunPriorityAttribute(pIceAgent->pBindingRequest, 0));
+    CHK_STATUS(appendStunIceControllAttribute(
+            pIceAgent->pBindingRequest,
+            pIceAgent->isControlling ? STUN_ATTRIBUTE_TYPE_ICE_CONTROLLING : STUN_ATTRIBUTE_TYPE_ICE_CONTROLLED,
+            pIceAgent->tieBreaker));
+
 CleanUp:
 
     if (locked) {
```

**Comment by chehefen** [comment]
I see, I think there should be an extra state for waiting for remote username and password. I will add the fix shortly.

**Comment by chehefen** [comment]
@staowyze can you check if the branch fixes the issue? Thanks

**Comment by staowyze** [comment]
thank you, I cannot try the fix immediately, will get back to you once I do.

**Comment by staowyze** [comment]
pull the new code, the bug doesn't happen, close for now
