### ISSUE TITLE
viewer unable to join stream when use new feature "ingestion and storage media"

### ISSUE THREAD

**Issue by aniket0527** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1930]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [X] I have all the details the issue requires

### Describe the bug

there is raspberry pi which is live streaming video(uni direction) and audio(bi direction) to client app and also I want to store that. so it it possible with kvs webrtc? because i already try it but i cant able to store and there is new release like ingestion and storage media but in that client app (viewer) unable to join and master getting stucked "PROFILE initSignal(): [Signling connect client] 2147ms"

### Expected Behavior

viewer unable to join stream 

### Current Behavior

kvs webrtc new feature "ingestion and storage media" in that peer to peer communication along with storage should happen

### Reproduction Steps

kvs webrtc with storage

1.Create a Signaling Channel(Make note of the channel ARN).
2. Create a stream(Make note of the stream ARN)
(Important WebRTC Ingestion requires an Amazon Kinesis video stream with data retention enabled.)
3.Configure media ingestion and storage
 When you have the ARNs, set the media storage configuration. Type:
$ aws kinesisvideo update-media-storage-configuration \
    --channel-arn your-arn \
    --media-storage-configuration \
        StreamARN="your-stream-arn",Status="ENABLED" \
    --region us-west-2 

 Follow all the steps the WebRTC SDK in C for Embedded Devices procedures to build the sample application.(https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-c.html)
 run:
        ./samples/kvsWebrtcClientMasterGstSample channel-name audio-video-storage devicesrc

### WebRTC C SDK version being used

Release 1.9.1

### Compiler and Version used

13.2

### Operating System and version

ubuntu 18

### Platform being used

laptop

**Comment by sirknightj** [comment]
Hi @aniket0527, thanks for your interest in the WebRTC ingestion feature.

The behavior you are experiencing is by current design. There are two modes a signaling channel can be in. If the channel is in ingestion mode, viewers can no longer join directly. Please refer to the following documentation page: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_UpdateMediaStorageConfiguration.html

We've taken note of the request to support viewer and ingestion on the same channel and will consider it for our roadmap.
