### ISSUE TITLE
[Bug]: How to convert each obtained camera frame to cv:Mat

### ISSUE THREAD

**Issue by setareh-soltanieh** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1954]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [X] I have all the details the issue requires

### Please answer the following prompt

- [X] This issue is replicable using the unmodified sample application

### Describe the bug

I'm currently working on integrating this codebase to stream camera frames from my mobile device into ROS. So far, I've successfully created a ROS package from the project and converted the Viewer's code from C to C++, allowing me to create a ROS node from this codebase.

Now, I'm aiming to publish my camera frames to a ROS topic (sensor_msgs/Image). However, to achieve this, I need to read each image and convert it to the cv::Mat format before publishing it to ROS.

From my understanding pFrame->frameData is pointing to the received image buffer data and we have key frame and non key frame images. I have tried to convert these .h264 data to cv:Mat using ffmpeg (libav commands) but these codes only work for key frames and I have the following errors when I try to convert non key frames

`[h264 @ 0x56487713e500] non-existing PPS 0 referenced
[h264 @ 0x56487713e500] decode_slice_header error
[h264 @ 0x56487713e500] no frame!`

Does anybody know how I can convert my camera frames to cv:Mat? 

### Expected Behavior

I want to be able to receive camera frames in cv:Mat format. 

### Current Behavior

The camera frames are being received in h264 format. 

### Reproduction Steps

`VOID myFrameHandler(UINT64 customData, PFrame pFrame)
{
    av_register_all();
    avcodec_register_all();

    AVCodec* codec = avcodec_find_decoder(AV_CODEC_ID_H264);
    AVCodecContext* codecContext = avcodec_alloc_context3(codec);
    avcodec_open2(codecContext, codec, nullptr);

    AVPacket packet;
    av_init_packet(&packet);
    packet.data = (uint8_t*)pFrame->frameData;
    packet.size = pFrame->size;

    AVFrame* frame = av_frame_alloc();

    static AVFrame* lastKeyFrame = nullptr;
    if (!lastKeyFrame) {
        lastKeyFrame = av_frame_alloc();
    }

    if (frame->pict_type == AV_PICTURE_TYPE_P) {
        av_frame_copy(lastKeyFrame, frame);
        av_frame_unref(frame);
    }
    
    int frameFinished = 0;
    int bytesDecoded = avcodec_decode_video2(codecContext, frame, &frameFinished, &packet);

    // Convert decoded frame to cv::Mat
    cv::Mat decodedFrame;
    if (frameFinished) {

        // Convert AVFrame to BGR format using sws_scale
        struct SwsContext* img_convert_ctx = sws_getContext(
            codecContext->width, codecContext->height, codecContext->pix_fmt,
            codecContext->width, codecContext->height, AV_PIX_FMT_BGR24,
            SWS_FAST_BILINEAR, nullptr, nullptr, nullptr);
        if (img_convert_ctx != nullptr) {
            decodedFrame = cv::Mat(codecContext->height, codecContext->width, CV_8UC3);
            uint8_t* outData[1] = { decodedFrame.data };
            int outLinesize[1] = { decodedFrame.step };
            sws_scale(img_convert_ctx, frame->data, frame->linesize, 0, codecContext->height,
                      outData, outLinesize);
            sws_freeContext(img_convert_ctx);
        }
    }
    printf("frame Id: %u\n", pFrame->index);

    if (!decodedFrame.empty()) {
        cv::imshow("Decoded Frame", decodedFrame);
        cv::waitKey(1);
    }

    av_frame_free(&frame);
    avcodec_close(codecContext);
    avcodec_free_context(&codecContext);
}
`
This is my frame handler function in my viewer.cpp code and I'm using this function with: 

`CHK_STATUS(transceiverOnFrame(pSampleStreamingSession->pVideoRtcRtpTransceiver, (UINT64) pSampleStreamingSession, myFrameHandler));`

### WebRTC C SDK version being used

master

### Compiler and Version used

gcc --version Visual Studio 

### Operating System and version

Ubuntu 20.04

### Platform being used

ROS

**Comment by niyatim23** [comment]
Hi @setareh-soltanieh, the viewer receives raw I, P, and B frames if you're using H264 codec. Out of these, I-frames can be directly converted into images, however, P and B frames need more information as they are not independent by themselves. We don't have any examples using cv:Mat. We have some GStreamer pipelines that consume audio and video buffers as they are received by a transceiver. You can modify this pipeline to generate images instead of write to a file. Please note that this is just an example and still a work in progress and may not work out of the box directly.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/90033dff1b1aa41bc5157d4e3229bb43a963c41c/samples/kvsWebRTCClientViewer.c#L37-L217

Closing this issue as this isn't a bug. Please use the discussion thread we already have for further conversation.
