### ISSUE TITLE
[Feature request]: Need to build the kvsdk package with OpenWrt

### ISSUE THREAD

**Issue by seba-0506** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1980]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing feature requests
- [X] I have all the details the issue requires

### Describe the feature

Need to build the kvsdk package with OpenWrt

### Use Case

Trying to build the kvsdk library with openwrt packages

**Comment by disa6302** [comment]
@seba-0506 ,

Could you clarify what issues you are facing?
