### ISSUE TITLE
[Documentation]: README.md should mention the supported video codecs for WebRTC ingestion

### ISSUE THREAD

**Issue by gotodeneslaszlo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1984]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing documentation issue reports
- [X] I have all the details the issue requires

### Describe the issue

Hello guys!

The documentation says that VP8 is supported, but I tried to set the media type of the created video stream for ingestion, but the incoming offer still uses H264, instead of VP8.

Is it possible to force VP8 video codec in the incoming offer during WebRTC ingestion?

README.md should mention the supported video codecs for WebRTC ingestion, because it is not clear which codecs are supported for ingestion.

### Links

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/README.md

**Comment by sirknightj** [comment]
Related: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/discussions/1983

**Comment by sirknightj** [comment]
Thanks for your patience.

The AWS documentation has been updated with the track requirements for WebRTC Ingestion feature.
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_webrtc_JoinStorageSession.html

![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/assets/14988194/2d5bea40-bfed-4bad-9d3d-6979ba85b7b3)
