### ISSUE TITLE
[Bug]: Seemingly SessionDescription creation bug

### ISSUE THREAD

**Issue by wei-zhang-simplisafe** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#2007]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [X] I have all the details the issue requires

### Please answer the following prompt

- [X] This issue is replicable using the unmodified sample application

### Describe the bug

This line looks wrong:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/SessionDescription.c?plain=1#L659
The SPRTINTF will be overwritten by the next SPRINTF:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/SessionDescription.c?plain=1#L662

nack feature is supported by webrtc SDK, so these lines should be in the SDP:
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli

But because of the above issue, only "a=rtcp-fb:125 nack pli" is in the SDP.
Some peer doesn't know webrtc SDK supports NACK, so won't send NACK RTCP packets.

### Expected Behavior

These lines should be in the SDP:
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli

### Current Behavior

Only a=rtcp-fb:125 nack pli is in the SDP

### Reproduction Steps

Run sample code, and check the SDP text

### WebRTC C SDK version being used

Most recent code base

### If it was working in a previous version, which one?

No

### Compiler and Version used

Any compiler

### Operating System and version

any OS

### Platform being used

any platform

**Comment by disa6302** [comment]
It does look like a bug. Thanks @wei-zhang-simplisafe ! Will get this fixed.

**Comment by hassanctech** [comment]
fix has been merged!
