### ISSUE TITLE
Add easy way to install sdk

### ISSUE THREAD

**Issue by TomyTomm** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#202]
* [ ] Allow user to specify where all headers/shared objects get installed
* [ ] Include a `.pc` for easy use of `pkg-config`
* [ ] Should we also copy all the deps when `BUILD_DEPENDENCIES` is specified.

**Comment by Sean-Der** [comment]
Thanks @TomyTomm! Will update your original issue with everything we need.

**Comment by rossyeager** [comment]
+1 on this request. It seems that there is no package config file nor easy way to integrate these libraries into our build without extracting the sources and dependencies and packaging them up on our own.

Having a `make install` step that respected typical `Cmake` install variables would be ideal.

**Comment by lherman-cs** [comment]
Using our SDK is now easier, following is the only required CMakeLists:

```
cmake_minimum_required(VERSION 3.11)
project(KVSWebRTCCanary LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 11)

include(FetchContent)
FetchContent_Declare(
  webrtc
  GIT_REPOSITORY https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c
  GIT_TAG        35fc3ea5f2132613a8439da41fdfc1b5c052c858
)

FetchContent_GetProperties(webrtc)
if(NOT webrtc_POPULATED)
  FetchContent_Populate(webrtc)
  add_subdirectory(${webrtc_SOURCE_DIR} ${webrtc_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()

include_directories(${webrtc_SOURCE_DIR}/src/include)
include_directories(${webrtc_SOURCE_DIR}/open-source/include)
link_directories(${webrtc_SOURCE_DIR}/open-source/lib)

add_executable(
  kvsWebrtcCanaryWebrtc
  path/to/your/source/code.cpp)
target_link_libraries(
  kvsWebrtcCanaryWebrtc
  kvsWebrtcClient)
```

Since we've improved our build system and reasonably easy to integrate, I'll mark this as resolved.
