### ISSUE TITLE
【Question】Why H265 payloadType changed by DEFAULT_PAYLOAD_H265？

### ISSUE THREAD

**Issue by remainfox** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#2029]
### Please confirm you have already done the following

- [X] I have searched the repository for related/existing bug reports
- [X] I have all the details the issue requires

### Please answer the following prompt

- [X] This issue is replicable using the unmodified sample application

### Describe the bug

1、in populateSingleMediaSection function，`hashTableGet(pKvsPeerConnection->pCodecTable, pRtcMediaStreamTrack->codec, &payloadType)` already calculate h265 payloadType ，but after `pRtcMediaStreamTrack->codec == RTC_CODEC_H265` ，h265 payloadType changed by `payloadType = DEFAULT_PAYLOAD_H265`, Why?

![image](https://github.com/user-attachments/assets/0026308c-c63b-4e3e-8498-a3e9633450e0)

### Expected Behavior

- 

### Current Behavior

- 

### Reproduction Steps

- 

### WebRTC C SDK version being used

Master Branch， Release1.10.2

### Compiler and Version used

gcc 5.4

### Operating System and version

linux

### Platform being used

mips

**Comment by hassanctech** [comment]
Fix has been merged.
