### ISSUE TITLE
easy way to include headers of the library

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#203]
Hi, I am trying to use the pre-built library, but the Include.h header includes other header files, hope to have an easy way to include all the required header files in a single place.

**Comment by MushMal** [comment]
WebRTC project has only a single public include file it's https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h

However, it relies on C SDK library public includes:

#include <com/amazonaws/kinesis/video/client/Include.h>
#include <com/amazonaws/kinesis/video/common/Include.h>

In turn, these will rely on public includes from PIC.

The initial dependency on C SDK common library is the reason why webRTC doesn't directly include PIC header and common definition files.

If you close the repository (with the sub-modules) you won't have any issues with the include files. 

However, in your case, I believe, we need CMake install or similar technique to install the public header files.

Could you please elaborate what you would like to see in this case where multiple dependent repositories are involved.

**Comment by staowyze** [comment]
I think CMake install would solve my problem, I don't want to find all the header dependency manually.
May I know how to `close the repository (with the sub-modules) you won't have any issues with the include files`? Do it support CMake already?

**Comment by MushMal** [comment]
I meant 'clone' the repository. Per readme:

`git clone --recursive https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c.git`

**Comment by MushMal** [comment]
sorry - pressed enter before I had finished my thought.

The current CMakeList that builds the repository also sets the include paths which then are automatically get picked up.

I believe for your application the cmake install should work just fine. Before we implement that though, you might want to take a look at the directory inclusion in the cmake file

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/CMakeLists.txt#L393

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/202 is tracking it

**Comment by staowyze** [comment]
great, closing as duplicated.
