### ISSUE TITLE
[Bug]: unable to stream H265 webrtc on test page

### ISSUE THREAD

**Issue by naseebpanghal** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#2030]
### Please confirm you have already done the following

- [x] I have searched the repository for related/existing bug reports
- [x] I have all the details the issue requires

### Please answer the following prompt

- [x] This issue is replicable using the unmodified sample application

### Describe the bug

I am able to stream H264 but not H265 from same machine, same terminal.
Respective commands used:
./kvsWebrtcClientMaster naseebgetyourown_QA 0 opus h264
./kvsWebrtcClientMaster naseebgetyourown_QA 0 opus h265

It seems connection is made but nothing is shown in the viewer.
webpage: https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html

I verified the video samples and found below result.
[mediainfo_result.txt](https://github.com/user-attachments/files/16309330/mediainfo_result.txt)

### Expected Behavior

dot boll should be seen in the viewer similar to H264

### Current Behavior

Currently connection is made but black screen is visible. Nothing is shown in the viewer window.

### Reproduction Steps

Run steps as provided on the README page.

### WebRTC C SDK version being used

1.10.2

### Compiler and Version used

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### Operating System and version

Ubuntu 22.04

### Platform being used

Intel

**Comment by sirknightj** [comment]
Hi @naseebpanghal, could you share which browser you are using?

Currently, most browsers haven't accepted H265 support for WebRTC yet. Refer to https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1965#issuecomment-2089235566 for the details on available players for it.

**Comment by naseebpanghal** [comment]
Hi @sirknightj, I am using chrome on linux.

**Comment by sirknightj** [comment]
Thanks for confirming.

Chrome currently doesn't support H.265 with WebRTC. Feel free to +1 the feature request here: https://issues.webrtc.org/issues/41480904
