### ISSUE TITLE
Loaded client cert private key message : Not found when using createLwsIotCredentialProvider API

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#206]
Trying to using createLwsIotCredentialProvider API to replace createStaticCredentialProvider,
the kvsWebrtcClientMaster will has error as below after Loaded client cert private key,
{"message":"Not Found","traceId":"c00be6b7-0999-3387-0e9e-5909a1dcebfc"} 
![image](https://user-images.githubusercontent.com/58592084/75009200-0c46c600-54b5-11ea-84c2-7156bce28cc1.png)

We are follow the document in the SDK to create iot credential file and parameter.
 
Need advice.

**Comment by zhiyua-git** [comment]
Hi @henryChmn ,

Your IoT credentials url is incorrect, it should be something in format of blah.**credentials**.iot.us-west-2.amazonaws.com. As mentioned in README, you cannot use the IoT endpoint from AWS Console.

You can use AWS CLI to retrieve the IoT credentials endpoint by calling “aws iot describe-endpoint --endpoint-type iot:CredentialProvider” as mentioned in [here](https://aws.amazon.com/blogs/security/how-to-eliminate-the-need-for-hardcoded-aws-credentials-in-devices-by-using-the-aws-iot-credentials-provider/). Thanks.

**Comment by henryChmn** [comment]
@zhiyua-git 
Yes, we found this and has other error as below: Access Denied
![image](https://user-images.githubusercontent.com/58592084/75021471-6b193900-54cf-11ea-9256-f860a882954a.png)

**Comment by henryChmn** [comment]
It's working now,
Thanks
![image](https://user-images.githubusercontent.com/58592084/75023394-b4b75300-54d2-11ea-9ab8-8b816b48e424.png)

**Comment by zhiyua-git** [comment]
Nice to see it works for you! Can you share some information about what was going wrong?

**Comment by henryChmn** [comment]
@zhiyua-git channelName:kvs_example_camera_stream and roleAlias:KvsCameraIoTRoleAlias are incorrect
