### ISSUE TITLE
SRTP Extension for DTLS Non Conformance

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#208]
https://tools.ietf.org/html/rfc5764#section-5.1.2
"If the value is in between 128 and
   191 (inclusive), then the packet is RTP (or RTCP, if both RTCP and
   RTP are being multiplexed over the same destination port)."

However, the current demux logic is using 127 and 192 inclusive in
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/PeerConnection.c

**Comment by Sean-Der** [comment]
That is awesome, thank you @suggestedfixes! Would you be up for opening a PR (always love when others contribute)

Or do you want me to grab?

**Comment by suggestedfixes** [comment]
Thanks! For now I don't know how tests and CI are executed. So I think it is safer for you to grab.
