### ISSUE TITLE
libwebsocket version causes problems

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#211]
For libwebsocket, this GIT_TAG is used:    v3.2-stable.
It caused problems recently.  Before 1/16, there was no problems
* When running binary on Ubuntu 18.04 ( using system's openssl), peer connection crashes in createCertificateAndKey function.  I found it has a few 509_xx calls.
* When cross-compile for ARM, the build fails with error X509_VERIFY_PARAM_set1_host not defined.
Downgrading libwebsocket to  GIT_TAG =3179323afa81448287a15982755ed0e4a34d80cb solves the problem

**Comment by zwei333** [comment]
When crash on Ubuntu 18.04, the log and backtrace
2020-02-24 05:01:15 INFO    signalingClientGetIceConfigInfoCount(): Signaling Client Get ICE Config Info Count
2020-02-24 05:01:15 INFO    signalingClientGetIceConfigInfo(): Signaling Client Get ICE Config Info
2020-02-24 05:01:15 INFO    signalingClientGetIceConfigInfo(): Signaling Client Get ICE Config Info
Error: signal 11:
./webrtc(_Z15segsegv_handleri+0x2b)[0x55a2c80d32af]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7f29355b0f20]
./libkvsWebrtcClient.so(createCertificateAndKey+0x189)[0x7f2936aff033]
./libkvsWebrtcClient.so(createDtlsSession+0xf2)[0x7f2936aff5df]
./libkvsWebrtcClient.so(createPeerConnection+0x1f6)[0x7f2936b124c2]

**Comment by MushMal** [comment]
@zwei333 Thanks for reporting. We will look into it asap.

@Sean-Der could you please drive this?
