### ISSUE TITLE
freeSignalingClient() gets stuck sometimes

### ISSUE THREAD

**Issue by hsinghaowang** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#216]
I found sometimes `freeSignalingClient()` get stuck, never return.

**Comment by MushMal** [comment]
@hsinghaowang the free client has two potential threads to terminate - the listener and the reconnect if they exist. In the optimistic path, those would be "prompt" - aka - no awaiting. In the pessimistic path, the code triggers the termination and awaits for those to quit as those might be driving the libWebSockets event loop/machinery. In either case, it's configured to timeout in 5 seconds. So, in case it hits the "bad" lws it might await for around 10 seconds.

Are you seeing it to terminate after a while or it simply gets stuck?

If the latter, would you be able to take a dump so we can see what's going on?

**Comment by hsinghaowang** [comment]
It gets stuck forever.
I will try to dump (stack trace?)

**Comment by MushMal** [comment]
That would be really cool. If you are running a debugger, pause all the threads and get the stack traces of the threads like 'thread apply all bt'

**Comment by MushMal** [comment]
One more question. What state is the signaling when you are attempting to free the client? Is it connected?

**Comment by hsinghaowang** [comment]
yes, it is connected. I can start video streaming after that.

**Comment by MushMal** [comment]
Interesting. Could you also tell us what platform you are on?

**Comment by hsinghaowang** [comment]
I am running on arm-linux-3.3 (GM8136) with 128MB RAM

**Comment by hsinghaowang** [comment]
Here is the dump
[freeSignalingClient_stuck.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4254644/freeSignalingClient_stuck.log)

**Comment by hsinghaowang** [comment]
Any idea?

**Comment by MushMal** [comment]
@hsinghaowang Thanks for the logs. Seems something odd is going on the teardown path when we are tearing down the timerqueue while the timerqueue executor thread that's currently happen to execute the state machine which is executing ice refresh code which holds the lock. The strange thing is that the termination sequence should trigger LibWebSockets event loop shutdown but for some reason it doesn't. I need to investigate this a little further. Will update as soon as I get more info.

**Comment by MushMal** [comment]
I believe this is fixed by the latest commit #aa9628d189719e6fe2f709347c5a62d93a3ff98d
