### ISSUE TITLE
CMake: Downloading and building of dependencies only happens once

### ISSUE THREAD

**Issue by InspectorConstructor** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#220]
When CMake is run, dependencies are only downloaded and built once.
While this may simplify things, it causes the following problems:

- If a dependency is tracking a git branch, and the branch is updated, the build will not automatically update and rebuild the dependency.
- If the dependency's definition changes (if we change what commit or branch to download) the new version will not automatically be downloaded or rebuilt.
- If a dependency fails to build, re-invoking make or cmake will not attempt to rebuild the missing package. This means all builds thereafter will fail until the dependency's build directory is erased, or the project build directory is erased.

This is of concern for everyone when a dependency is updated. This is also pertinent to new customers compiling for new architectures, as custom toolchains may cause build issues.

Using cmake's **ExternalProject** to build the dependencies directly could be a better way to go.

**Comment by disa6302** [comment]
@InspectorConstructor , this is a great suggestion!

If you already have some changes you have made to the CMake file to do this, feel free to start a PR with this change and the team could review it. Thank you for your contributions and suggestions. Appreciate it.

**Comment by InspectorConstructor** [comment]
After some research, handling third-party-dependencies elegantly is a common yet cumbersome problem for CMake projects to solve, and ExternalProject may be less-than-ideal. I'm committed to working on other issues for the next few weeks, but I'd be happy to contribute something when I have time!

**Comment by chehefen** [comment]
In majority of our use cases, we only need to build the libraries once. The third point should be fixed by #265. For first and second point, you will have to delete the library files from open-source/local/lib to trigger its build again.

**Comment by MushMal** [comment]
I am closing this issue as I don't see this to be actionable for now. We should revisit perhaps a more elegant way to track dependencies but for now, those should be done manually.
