### ISSUE TITLE
Unable to see sample video on aws media playback viewer

### ISSUE THREAD

**Issue by taufeeq25** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#228]
Hello Team,

I am testing amazon-kinesis-video-streams-webrtc-sdk-c sample examples. when i running kvsWebrtcClientMaster, its throwing warning related socket, SSL send.

This example suppose to play sample file on kinesis video stream -> Media Playback viewer, but i cant see anything on media.

Platform: Ubuntu 16.04

I have attached log details. please check.

[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4273716/log.txt)

**Comment by chehefen** [comment]
from it log it looks like the application got terminated 1 second after it got connected, can you give it a bit more time? thanks.

**Comment by taufeeq25** [comment]
@chehefen,

Thanks for replying. Application is able to live stream from Raspberry pi to Android application. I am running kvsWebrtcClientMasterGstSample. 

Problem is why i can't see video on aws media playback viewer? On android video is streaming fine.
Anyway that is not important because raspberry pi able stream video to android app.

Now i want to make one way communication from raspberry pi to android. I don't need any data from android to raspberry pi. 
Could you suggest me which callback i need de-register to clean all  log for receiving data.

**Comment by chehefen** [comment]
to not receive data, you can just set this: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L302 to NULL. what it does is that it skips setting up transceiverOnFrame callback on the transceiver.

**Comment by taufeeq25** [comment]
@chehefen 

I made changes as you suggested in above comment.
pSampleConfiguration->receiveAudioVideoSource = NULL;

Video streaming is OK but getting lot of error log. Please check attached log file.
[log1.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4279850/log1.txt)

**Comment by Sean-Der** [comment]
Hi @taufeeq25 I have created a new issue for what you reported, and I am going to start working on it now. https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/232

**Comment by taufeeq25** [comment]
hello @Sean-Der, 
Thank you for acknowledging and crating new issue. I will keep following that thread.

**Comment by chehefen** [comment]
It seems that all issues have been fixed. Closing the issue.
