### ISSUE TITLE
bug in onIceConnectionStateChange 

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#231]
Looks like not all the states are well handled https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/PeerConnection.c#L293
e.g. I got following warning logs
`onIceConnectionStateChange(): Unknown ice agent state 4`

**Comment by chehefen** [comment]
it's fixed in this commit: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/bef6c8c0b485de5b108314dab59bfe8f8813f936
