### ISSUE TITLE
[Question]: Is PeerConnection reusable

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#235]
Hi experts,
Is it feasible to reuse PeerConnection for different sessions?
I handle only ONE peer connection each time, however, for each connection request, I need to free the old peer connection and create a new one. It takes a few seconds on my device to free and create peer connection, it would be very valuable to me if I could reuse the existing peer connection, any thoughts? I didn't find a reset API yet.

**Comment by chehefen** [comment]
Hi, freePeerConnection shouldnt take too much time. Can you give us some log to show how long it takes to free peerConnection? For createPeerConnection path, can you check how long it takes to run this function: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Dtls/Dtls.c#L80 when whether it makes up majority of the creation delay.

**Comment by Sean-Der** [comment]
@staowyze WebRTC as an API doesn't allow PeerConnection re-use, this is something dictated by the W3C standard. Here are a couple of the technical reasons why though!

### DTLS handshake only occurs once
When the WebRTC peers connect they do a (D)TLS handshake. If we enabled re-use of a PeerConnection we would need a way to reset all the underlying cryptographic state.

### SCTP Association init
A SCTP association has a bunch of state between two peers and can't be re-used.

**Comment by staowyze** [comment]
`createCertificateAndKey` took most of the time, a few seconds on my platform, reduced the `certificateBits` from 2048 to 1024 helped a lot, however, even 1024 is till too slow to me, about 5 seconds for it.
Not dig the standard much, is it possible to reuse the certificate and key? Or is it possible to make `createCertificateAndKey` faster?

**Comment by chehefen** [comment]
we switched to use ECDSA key generation by default in this commit https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/f24a8d687b1b577cd4b397581a551f78ced197a4. Can you check if it helps with key generation?

**Comment by staowyze** [comment]
I got error with `CHK(EVP_PKEY_assign_EC_KEY(*ppPkey, eccKey) != 0, STATUS_CERTIFICATE_GENERATION_FAILED);`, any ideas what could be wrong?

Would ECDSA signaficantly faster than RSA?

**Comment by staowyze** [comment]
> @staowyze WebRTC as an API doesn't allow PeerConnection re-use, this is something dictated by the W3C standard. Here are a couple of the technical reasons why though!
> 
> ### DTLS handshake only occurs once
> When the WebRTC peers connect they do a (D)TLS handshake. If we enabled re-use of a PeerConnection we would need a way to reset all the underlying cryptographic state.
> 
> ### SCTP Association init
> A SCTP association has a bunch of state between two peers and can't be re-used.

Is it feasible to reuse the DTLS key, say we only generate key once, but use the same key for the rest of handshakes.

**Comment by staowyze** [comment]
Another finding, a mutex would be occupied by `pConnectionListener` up to `SOCKET_WAIT_FOR_DATA_TIMEOUT_SECONDS`, which eventually blocks freePeerConnection.

**Comment by staowyze** [comment]
> > @staowyze WebRTC as an API doesn't allow PeerConnection re-use, this is something dictated by the W3C standard. Here are a couple of the technical reasons why though!
> > ### DTLS handshake only occurs once
> > When the WebRTC peers connect they do a (D)TLS handshake. If we enabled re-use of a PeerConnection we would need a way to reset all the underlying cryptographic state.
> > ### SCTP Association init
> > A SCTP association has a bunch of state between two peers and can't be re-used.
> 
> Is it feasible to reuse the DTLS key, say we only generate key once, but use the same key for the rest of handshakes.

I just tried make the DTLS key and certificate global, and only create them in initKvsWebRtc, works at my side. However, I am not sure if it would introduce security concerns.

**Comment by zhiyua-git** [comment]
Hi @staowyze ,

ECDSA key generation should be much faster than RSA.

If that is still not fast enough for you, you can generate certificate before offer comes and pass it into createPeerConnection as here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/pregen_certs#use-pre-generated-certificates. However, it is recommended to rotate the certificates often - preferably for every peer connection to avoid a compromised client weakening the security of the new connections. Thanks.

**Comment by MushMal** [comment]
To add to the above... Some platforms can generate 256-bit ECDSA key-based crypto a lot faster than 2048-bit RSA and this approach can be used to generate a new cert for each peer connection. The key pair/cert generation is on the "hot" path and can slow down the e2e latency so we are experimenting with pre-generated certificates highlighted by the above post. The main idea is to "offload" the cert generation from the "hot" path. The recommended implementation in the customers application would keep a pre-generated cert and would use that cert for an incoming peer connection only. 

While I can't think of any direct attack vector when re-using a cert, it's recommended to not use the same cert for multiple sessions.

**Comment by staowyze** [comment]
alright, I pulled the latest master and tried out, ECDSA is amazing, way faster!
my problem solved, i can afford key regeneration now, thank you!
