### ISSUE TITLE
How to use on Windows

### ISSUE THREAD

**Issue by DyncEric** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#237]
Hi, i want test this sdk on windows, how to build and use it?

**Comment by suggestedfixes** [comment]
Note I'm not an Amazon Developer. I'm also testing this sdk.

One possible path that might shed some light is to use mingw-w64 compiler, you might encounter many issues along the way. You may have to build some libraries from scratch.

Another possible path is to run it on a Debian docker image. Or spin up a virtual machine with Linux. 

If you are comfortable setting up travis. You can even fork this repo, copy the .travis.yml, run travis, grab the artifacts, download the binaries and run it on a Linux machine.

This repo is mostly intended for running on embedded devices. Modern desktop computers are fast enough without running C most of the time. So you might want to consider for javascript/Java or other higher level language sdk that runs well on Windows.

**Comment by MushMal** [comment]
@DyncEric while we are not officially supporting WIndows with WebRTC SDK, the codebase itself is quite portable. The main issue is to bring Windows-based build scripts - similar to what we do in 

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp

There might be some adaptation need around socket APIs but it shouldn't bee too hard to pinpoint once the build-scripts are done properly.

**Comment by DyncEric** [comment]
Thanks for resp
