### ISSUE TITLE
Travis Build Info Out of Date

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#238]
When we click into the build icon on README page, it shows that the build is passing from
 master "fix sctp lifecycle handling", which is from 3 months ago.
It would be appreciated if clicking that build icon leads to the latest build, or most recent stable build from not too long ago.

**Comment by disa6302** [comment]
Thank you for the suggestion @suggestedfixes . Will work on it.
