### ISSUE TITLE
Please improve socket error handlings / recovery in unreliable wifi network

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#245]
Our wifi network in office is very noisy, and our camera's wifi driver is not the best, so the webrtc is running in a very tough wifi environment.
Although this scenario is rare in the field, it is a very good stress test of kvs software error resilience.
We need help to improve the socket error handling in this extreme condition so that the video is still barely acceptable.
In our office, we see these errors:
1. "socketConnectionSendData(): Failed to send data. Socket closed already."  
status code 0x58000022
Not sure if it is necessary to close socket.  And after socket is closed, maybe we should quickly reconnect.  Current code calls  socketConnectionSendData() many times, getting many of error messages, and video is frozen
2. "socketConnectionSendData(): sendto data failed with errno"  "Resource temporarily unavailable"
status code 0x5800001a
Sending fails and then frames dropped. When the error happens, the error repeats many times, and webrtc drops a lot of frames.  Looks like re-transmission kicks in that causes significant latency, as much as 5 seconds.
Like to see improved strategy of dropping frames and re-transmiting, so that latency won't increase too much in noisy wifi network.

**Comment by chehefen** [comment]
Hi, is your master and viewer running in the same network or are you using turn?
for issue #1, is it happening after the ice got connected and start streaming?
for issue #2, it could be that you are filling the kernel send buffer. you can try give it a larger size here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L667

**Comment by zwei333** [comment]
Thanks!
Issue #1, Streaming was running before the socket error.
Issue #2, I will try it.  It is very helpful.
Again, our wifi in a corner of our office is bad.  So I use this spot to test the robustness of kvs code

**Comment by zwei333** [comment]
Can you resend link for "for issue #2, it could be that you are filling the kernel send buffer. you can try give it a larger size here: "?  Maybe there are new check-ins.  The specified line does not have code to change buffer size

**Comment by chehefen** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L672

**Comment by chehefen** [comment]
Hi @zwei333 , any updates regarding issues you posted? For issue 1, the RtcOnConnectionStateChange should be invoked with either RTC_PEER_CONNECTION_STATE_FAILED or RTC_PEER_CONNECTION_STATE_CLOSED and you should tear down and recreate the peerConnection again.

**Comment by MushMal** [comment]
@zwei333 any update?

**Comment by chehefen** [comment]
@zwei333  #2 should be fixed by #279. can you try it out? Thanks
