### ISSUE TITLE
question about non-trickle ice

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#247]
From the sample application, appears no-trickle ice is supported, however from the implementation, we seems not wait the relay candidate particularly, i.e. if the relay candidate comes too late, we would claim candidate gathering done without waiting, do I understand correctly?

**Comment by staowyze** [comment]
With ICE_TRANSPORT_POLICY_RELAY policy, it would wait till the relay candidate is available, which makes sense.
But for ICE_TRANSPORT_POLICY_ALL, should we wait for the relay candidate too?

**Comment by chehefen** [comment]
yes. this is a bug. we will address this as soon as we can.

**Comment by staowyze** [comment]
would like to check if the bug has been fixed or not, thx

**Comment by chehefen** [comment]
Hi @staowyze, I'm implementing the fix right now. Should be out soon. Thanks.
