### ISSUE TITLE
iceCandidatePair with two relay candidates

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#248]
It's a more ICE technical question, in kinesis webrtc implementation, the `iceCandidatePair` could be two relay candidates, I am wondering does it make sense to have a connection which goes through two TURN addresses? I assume every connection should be bi-directional. Unless both sides don't want to expose their own IPs, otherwise why do we need this kind of `iceCandidatePair`?

**Comment by Sean-Der** [comment]
@staowyze You could have a situation where both clients are behind NATs that don't allow UDP traffic at all. There are also some other really annoying behaviors of NATs like Endpoint-Independent Mappings, so impossible to have multiple P2P sessions. Stuff like that pops up, so `relay <-> relay` is something that can occur!

[RFC 4787](https://tools.ietf.org/html/rfc4787) is a good read! I haven't found an exhaustive list of everything that can go wrong though, just painful bumps I have hit in production :)
