### ISSUE TITLE
[bug] - stuck in checking socket connection

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#249]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/TurnConnection.c#L917
if `socketConnectionIsConnected` failed for some reason, `pTurnConnection->stateTimeoutTime` is not set properly, and the state never times out, which caused the following logs:
```
2020-03-06 19:48:16 WARN    socketConnectionIsConnected(): socket connection check failed with errno Operation already in progress
2020-03-06 19:48:17 WARN    socketConnectionIsConnected(): socket connection check failed with errno Operation already in progress
...
```

**Comment by chehefen** [comment]
turn cant make progress until the tcp connection has been established. "already in progress" means that the non-blocking socket is still in progress of establishing the tcp connection. This seems like a network issue in your environment. Can you tell us what is your expectation?

**Comment by staowyze** [comment]
I would expect it eventually bails out, e.g. time out, then we could try to restart the application or just report errors, does it make sense to you?

**Comment by chehefen** [comment]
if turn cannot be established and there is no p2p connectivity, ice will eventually timeout when checking connection and onConnectionStateChange will report state change to failed. Is that ok with you?

**Comment by staowyze** [comment]
yeah, definitely. However, I believe it was stuck forever in my last time, I didn't test with to very recent code though, is it something new?

**Comment by MushMal** [comment]
@staowyze there has been some modifications to the ICE/TURN state machinery in the recent commits. Would you mind reporting the latest behavior? As @chehefen mentioned, the callback will be called after a timeout.

**Comment by MushMal** [comment]
Closing due to staleness. Please re-open if this issue still stands

**Comment by chehefen** [comment]
will close once state timeout is implemented.
