### ISSUE TITLE
Add more args to sample

### ISSUE THREAD

**Issue by virgilvox** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#250]
Things I'd like since I'm using this on a raspberry pi and the regular kinesis video streamer samples do this so it was nice:

- Make it easier to just flag to build only the gst sample
- Make the sample take args for video resolution, framerate
- Args for passing iot credentials endpoint and paths to cert

Would just be really useful way to demo and test without having to write or modify the example to be the way I need.

**Comment by zhiyua-git** [comment]
Hi @virgilvox ,

We are in a process of better splitting us the simple samples that demonstrate basic API usage and commercial grade samples that provides more args and options to be used directly. Will address this on the new samples. Thanks.

**Comment by MushMal** [comment]
We will consider adding more args to the new in-depth samples that we will be putting in place. However, supporting multitude of permutations of the args will greatly decrease the readability of the samples. We will have to go case-by-case basis. 

I am resolving this issue for now
