### ISSUE TITLE
Unable to stream video/audio when media type is audio-video

### ISSUE THREAD

**Issue by taufeeq25** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#259]
Hello Team,

I am facing problem with audio-video media type on raspberry pi. I am unable to stream video/audio.
It seems error related to ALSA library.

I have not interfaced speaker till now, but i want to input audio through mic so android app can play video with audio. Please let me know if any setup problem with ALSA Library.

Raspberry image: Raspbian Buster Lite
Board: Raspberry 4.

[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4323929/log.txt)

**Comment by MushMal** [comment]
@taufeeq25 perhaps it's a better question for a RPi forums but a google search brought this in the first line:

https://bbs.archlinux.org/viewtopic.php?pid=1446773#p1446773

Perhaps you need to configure your drivers?

**Comment by taufeeq25** [comment]
@MushMal  Thank you so much for response. I will raise issue issue with RPi once it is clear that media type-> audio-video, don't have any issue in SDK.

-> I have enable audio jack (3.5mm) on board for audio. I am hoping earphone should work for input/output audio. If i am wrong? please correct me.

-> I am able to remove most of ALSA error by configuring /boot/config.txt by adding. 
dtparam=audio=on.

But still facing some error:
AL lib: (EE) ALCcaptureAlsa_open: Could not open capture device 'default': No such file or directory

I tried to look for above error but could not find much on google. Detail log are attached, please have a look. 
Any help or suggestion will be appreciated.
[log1.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4328855/log1.txt)



Thank you.

**Comment by MushMal** [comment]
I really can't tell what's causing the audio capture error. In order to eliminate the KVS, would you be able to run the KVS Master application against the console viewer to see whether your device/network topology can make the pre-canned frames go through?

**Comment by taufeeq25** [comment]
@MushMal  I am able to stream audio/video using kvsWebrtcClientMaster executable. It able to stream sample video with audio. Is it possible to make this example work with live streaming using camera and audio with earphone?
-> I am pretty new to alsa, so i will dig more into that to make /kvsWebrtcClientMasterGstSample works with live streaming.(audio/video).

**Comment by MushMal** [comment]
@taufeeq25 as long as the media source works with the GStreamer pipeline it should be possible. 

My recommendations would be to try to remove KVS from the GStreamer pipeline and run your pipeline with gst-launch-1.0 with fakesink. Once that works you could then apply it to KVS. You can ask GStreamer forums for more information about your media pipeline.

I am going to mark this issue as resolved as you are able to stream using the provided samples.
