### ISSUE TITLE
pkgconfig searches default path /usr/lib/pkgconfig not /open-source/local/lib/pkgconfig

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#270]
I did not install gstreamer  under my environment of cross compiling.

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libwebsockets'
--   Found libwebsockets, version 3.2.0
-- Checking for module 'libsrtp2'
--   Found libsrtp2, version 2.2.0
-- Checking for module 'gstreamer-1.0'
--   Found gstreamer-1.0, version 1.14.5
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.56.4
-- Checking for module 'gstreamer-app-1.0'
--   Found gstreamer-app-1.0, version 1.14.5
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.56.4
gstreamer found. Will build gstreamer samples

[100%] Linking C executable kvsWebrtcClientMasterGstSample
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lglib-2.0
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lgstreamer-1.0
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lgobject-2.0
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lglib-2.0
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lgstapp-1.0
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lgstbase-1.0
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lgstreamer-1.0
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lgobject-2.0
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lglib-2.0
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lgobject-2.0
the/path/of/yours/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lglib-2.0
collect2: error: ld returned 1 exit status
CMakeFiles/kvsWebrtcClientMasterGstSample.dir/build.make:127: recipe for target 'kvsWebrtcClientMasterGstSample' failed
make[2]: *** [kvsWebrtcClientMasterGstSample] Error 1
CMakeFiles/Makefile2:229: recipe for target 'CMakeFiles/kvsWebrtcClientMasterGstSample.dir/all' failed
make[1]: *** [CMakeFiles/kvsWebrtcClientMasterGstSample.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ycyang1229** [comment]
I fixed this by the following command.
export PKG_CONFIG_LIBDIR=the/path/of/yours/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/local/lib/pkgconfig

**Comment by MushMal** [comment]
@ycyang1229 thanks for the info. We welcome PRs for this information in the readme. Would you be able to add a line in the readme?

Resolving for now.

**Comment by ycyang1229** [comment]
@MushMal Sorry for missing this message and readme is fine.
