### ISSUE TITLE
Unable to build project because of conflicting OpenSSL libraries

### ISSUE THREAD

**Issue by mm318** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#278]
We have a project that uses both the AWS SDK and this KVS WebRTC SDK.

The AWS SDK happens to be by default linked to the operating system's libcurl, which has a dependency on libssl. This KVS WebRTC SDK's `libkvsWebrtcClient.so` and `libkvsWebrtcSignalingClient.so` also have dependency on libssl.

The problem is that the operating system's libcurl expects to be using the operating system's libssl, but this SDK's `libkvsWebrtcClient.so` brings in its locally built libssl instead, and they're incompatible (libcurl will complain about undefined reference to `SSL_CTX_set_keylog_callback@OPENSSL_1_1_1`). (On the other hand, `libkvsWebrtcSignalingClient.so` for some reason is by default linked to the operating system's libssl, in contrast to `libkvsWebrtcClient.so`.)

I hacked the build system so that `libkvsWebrtcClient.so` uses the operating system's libssl instead, and then the project could be built successfully without linker errors. (See https://github.com/mm318/amazon-kinesis-video-streams-webrtc-sdk-c/commit/c57cef99e730237a8969a8168916bce983cf3fe1 and https://github.com/mm318/amazon-kinesis-video-streams-producer-c/commit/1008202db3f9607258a57e6189d9b23453c496bf.)

Can you please add an option to not build OpenSSL locally?

**Comment by mm318** [comment]
It is probably also better if `libkvsWebrtcClient.so` and `libkvsWebrtcSignalingClient.so` are consistent with which libssl they are linked to.

**Comment by Sean-Der** [comment]
If you set ‘-DBUILD_DEPENDENCIES=FALSE’ it will only use system libraries.

In the .github folder there is a Dockerfile we use for our CI, but might be nice to follow for setting up things. Some of our deps require configure flags so avoid use a package manager.

**Comment by mm318** [comment]
Yeah, I figured we shouldn't be using a package manager to obtain the dependencies, but I wasn't sure how to manually setup all of the required dependencies, which is why I didn't set `-DBUILD_DEPENDENCIES=FALSE`. We would also then have to codify the manual setup of the required dependencies into our project's `CMakeLists.txt`.

However, I think OpenSSL is an exception. There should should be an option in CMake build system to use the OpenSSL from the operating system's package manager, because it is so ubiquitous, chances are there will be a project that will have to use the build of OpenSSL from the package manager and is unable to use multiple builds of the same version of OpenSSL.

**Comment by MushMal** [comment]
I am going to resolve this issue for now. The build can be custom made using CMake.
