### ISSUE TITLE
PCM MULAW/ALAW played by gstreamer doesn't  work

### ISSUE THREAD

**Issue by lingdhox** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#291]
In the gstreamer sample.
`        case RTC_CODEC_MULAW:
        case RTC_CODEC_ALAW:
            audioDescription = "appsrc name=appsrc-audio ! rawaudioparse ! decodebin ! autoaudiosink";
            break;
`
The "autoaudiosink" does  not work.

And it works  by specify the format, like this: 
`        case RTC_CODEC_MULAW:
            audioDescription = "appsrc name=appsrc-audio ! audio/x-mulaw, channels=1, rate=8000 ! pulsesink";
            break;
        case RTC_CODEC_ALAW:
            audioDescription = "appsrc name=appsrc-audio ! audio/x-alaw, channels=1, rate=8000 ! pulsesink";
            break;
`

**Comment by MushMal** [comment]
@lingdhox Thank you for the suggestion. We would love if you could submit a pull request that we can review and merge. We strongly encourage and are very grateful for any contribution to the codebase!

**Comment by chehefen** [comment]
Hi, can you tell us what exactly didnt work when using autoaudiosink? Can you show us the gstreamer error? autoaudiosink is just a wrapper and it should select the right plugin to play audio in each platform.

**Comment by lingdhox** [comment]
> Hi, can you tell us what exactly didnt work when using autoaudiosink? Can you show us the gstreamer error? autoaudiosink is just a wrapper and it should select the right plugin to play audio in each platform.

The autoaudiosink is not a problem.  It seems that rawaudioparse is not working properly.

**Comment by chehefen** [comment]
does it work it if you only have audio/x-mulaw or audio/x-alaw?

**Comment by lingdhox** [comment]
According to GStreamer doc. For audio/x-mulaw, pulsesink is built-in support, while alsasink does not. 
So in the case of pulsesink missing, decodebin may be required.

**Comment by MushMal** [comment]
I am going to resolve this for now. The samples are not designed to work with any pipeline and might require changes to adapt to the particular pipeline. In the future, we might consider a plugin type of support for GStreamer

**Comment by EunseongBoo** [comment]
> I am going to resolve this for now. The samples are not designed to work with any pipeline and might require changes to adapt to the particular pipeline. In the future, we might consider a plugin type of support for GStreamer

The sample code still have this problem. "audioDescription = "appsrc name=appsrc-audio ! rawaudioparse ! decodebin ! autoaudiosink";". This line doesn't work, but "appsrc name=appsrc-audio ! audio/x-mulaw, channels=1, rate=8000 ! pulsesink"; works well 

Any other solutions for mulaw/alaw if pulse sink doesn't work on embedded?
