### ISSUE TITLE
kvsWebRTCClientMasterGstreamerSample.c pipeline for raspberry pi 

### ISSUE THREAD

**Issue by dannymarosi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#296]
Were can I find help modifying the pipeline in kvsWebRTCClientMasterGstreamerSample.c for raspberry pi zero?

I need a pipeline that has 2 sources and 2 sinks.

Audio source (we currently use arecord a LINUX audio recording utility)
Video source (for RASPICAM not a USB webcam)
Video sink to KVS streaming
Video sink to mp4 video file

Thanks

**Comment by chehefen** [comment]
Hi, you can checkout the gstreamer forum for information on what pipeline to use for raspberry pi: http://gstreamer-devel.966125.n4.nabble.com/

**Comment by dannymarosi** [comment]
Thanks
