### ISSUE TITLE
how to specify sysroot for cross compilation?

### ISSUE THREAD

**Issue by rossyeager** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#300]
I am trying get cross compilation working. I have a sysroot with openssl and srtc already built for my architecture. I'd like to specify the sysroot and have that referenced within the build. Is this something you guys support?

**Comment by Sean-Der** [comment]
Hey @rossyeager, thanks for checking out the SDK!

For OpenSSL we use pkg-config, so if you can just set your pkg-config environment variable it should respect it.

For other dependencies you should be able to either set `LIBRARY_PATH` or pass them as a `CFLAG/LDFLAG` we make sure to only append never overwrite what you pass.

thanks!

**Comment by rossyeager** [comment]
Ok, so set the following:
```
set(ENV{PKG_CONFIG_LIBDIR} ${CMAKE_SYSROOT}/lib/pkgconfig)
set(ENV{PKG_CONFIG_PATH} ${sysroot_pkg_path})
set(ENV{PKG_CONFIG_SYSROOT_DIR} ${CMAKE_SYSROOT})
```

**Comment by rossyeager** [comment]
for reference, I'm trying to build `aarch64` on an `x86` machine.

**Comment by rossyeager** [comment]
I am still unable to build using the pkgconfig variables with reference to a buildroot. Pkgconfig will not translate native paths (i.e. `/usr/lib/xxx`) to the cross compiled paths (i.e. `CMAKE_SYSROOT/usr/lib/xxx`). It does not seem like this is something that you support. Does this mean that I'd need to pass in that info some other way?

**Comment by MushMal** [comment]
This ticket seems to be stale. I am going to resolve this for now as the cmake build has undergone some major changes. Please try the latest commits.
