### ISSUE TITLE
Achieved selectedcandidatepairchange callback and getSelectedCandidatePair api

### ISSUE THREAD

**Issue by juno52wendy** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#302]
1. I have modified the code of kvs webrtc. The callback process code is completely encapsulated according to the process style of kvs webrtc. The state value of the hole can be printed out. Register it in the Common.c file function onSelectedCandidatePairType in KVS. Master implements the callback function, and you can get the status value outside the KVS Master
2. The sample callback can get the status. The reason is to use the callback output at the outermost because sessionCleanupWait is a loop.
3, the code modified by webrtc includes the callback status of hole punching and memory modification. Using tool search for modify by juno is the modified code.
4. The modified code is in the attached compressed package: webrtc_code modification_2020.3.26.zip
5. This code has been given to aws technical support staff, and we look forward to the early merger.
[webrtc_code modification_2020.3.26.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4385826/webrtc_code.modification_2020.3.26.zip)

**Comment by chehefen** [comment]
Hello, thanks for your contribution, but unfortunately we cant merge your change because we are trying to stick to the standard WebRTC apis listed here: https://www.w3.org/TR/webrtc/. The ones you need would be the onselectedcandidatepairchange event handler and getSelectedCandidatePair api. We will try to add them as soon as possible. Thank you for your patience.

**Comment by juno52wendy** [comment]
> Hello, thanks for your contribution, but unfortunately we cant merge your change because we are trying to stick to the standard WebRTC apis listed here: https://www.w3.org/TR/webrtc/. The ones you need would be the onselectedcandidatepairchange event handler and getSelectedCandidatePair api. We will try to add them as soon as possible. Thank you for your patience.

thanks for the reply,
1. If you need to comply with the webrtc standard, you can inform the detailed API of https://www.w3.org/TR/webrtc/, and you can refer to the modified implementation.
2. According to the currently provided API, sessionCleanupWait is a loop, so if I need to getSelectedCandidatePair api, I need to set an additional thread to include sessionCleanupWait, which is not very reasonable.
3. The current implementation, except that no 3C implementation standard was found, follows the current code style design and is triggered in real time using callback events.
4. The addition of such a design is also to meet business needs. It is not considered that the business needs to be met later. The desired custom standard can be found in the 3C standard. If there is no correct version, the corresponding product design is an unreasonable requirement. In the end, comprehensive consideration needs to be made to meet the needs of products and users.
5. At present, there are many additional requirements for docking webrtc products, which have been provided to your team's local technical support, and have also feedback to you. Unfortunately, it has not been implemented for almost half a month. Add the code logic that meets the business needs, then we will update the code later, and the maintenance workload will be large.

**Comment by disa6302** [comment]
Closing this since it is being tracked in #282
