### ISSUE TITLE
Websocket disconnected when my device try to send sdp answer

### ISSUE THREAD

**Issue by arthur-zou** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#306]
[webrtc.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4390987/webrtc.txt)

**Comment by MushMal** [comment]
@arthur-zou thanks for the logs. Looking at them, it seems that the exchange starts normally and the connection gets dropped receiving/right after receiving the ICE candidate:

```
[2020-03-27 09:47:50 255179] lwsWssCallbackRoutine(382): Client receive {"messagePayload":"eyJjYW5kaWRhdGUiOiJjYW5kaWRhdGU6MTAwNzkyNDE4NyAxIHVkcCA0MTg4NTY5NSAzNC4yMTUuMTMuMzkgNTQ2NzYgdHlwIHJlbGF5IHJhZGRyIDE4MC4xMTcuMjQyLjE5OCBycG9ydCAxMTc3NiBnZW5lcmF0aW9uIDAgdWZyYWcgRkF3WCBuZXR3b3JrLWlkIDMgbmV0d29yay1jb3N0IDEwIiwic2RwTWlkIjoiMCIsInNkcE1MaW5lSW5kZXgiOjB9","messageType":"ICE_CANDIDATE","senderClientId":"fc8f1ba9-b49f-4dd9-ac51-c2968fff61ae"}
[2020/03/27 09:47:59:7363] I: lws_sul_wsping_cb: req pp on wsi 0x117700
[2020/03/27 09:48:00:8072] I: rops_handle_POLLOUT_ws: issuing ping on wsi 0x117700: ws wss h2: 0
[2020/03/27 09:48:00:8077] I: 
[2020/03/27 09:48:00:8078] I: lws_issue_raw: ssl_capable_write (6) says -1
[2020/03/27 09:48:00:8078] I: __lws_close_free_wsi: 0x117700: caller: close_and_handled
[2020/03/27 09:48:00:8104] I: lws_vhost_unbind_wsi: vh default: count_bound_wsi 0
[2020/03/27 09:48:00:8235] I: lws_vhost_bind_wsi: vh default: count_bound_wsi 1
[2020/03/27 09:48:00:8250] I: lws_client_connect_via_info: role binding to h1
[2020/03/27 09:48:00:8265] I: lws_client_connect_via_info: protocol binding to https
[2020/03/27 09:48:00:8287] I: lws_header_table_attach: wsi 0x138ab0: ah (nil) (tsi 0, count = 0) in
[2020/03/27 09:48:00:8307] I: _lws_create_ah: created ah 0x131b70 (size 4096): pool length 1
[2020/03/27 09:48:00:8323] I: lws_header_table_attach: did attach wsi 0x138ab0: ah 0x131b70: count 1 (on exit)
[2020/03/27 09:48:00:8339] I: lws_client_connect_2: 0x138ab0: address kinesisvideo.us-west-2.amazonaws.com:443
[2020/03/27 09:48:01:0295] I: lws_client_connect_2: 0x138ab0: address kinesisvideo.us-west-2.amazonaws.com:443
[2020/03/27 09:48:01:0364] I: lws_client_connect_3: wsi 0x138ab0: h1 https client created own conn (raw 0)
[2020/03/27 09:48:01:0368] I: client conn using alpn list 'http/1.1'
[2020-03-27 09:48:00 838522] lwsWssCallbackRoutine(256): WSS callback with reason 75
[2020-03-27 09:48:00 838848] lwsWssCallbackRoutine(335): Client WSS closed
[2020-03-27 09:48:00 840677] lwsHttpCallbackRoutine(34): HTTPS callback with reason 30
[2020-03-27 09:48:00 847385] stepStateMachine(166): State Machine - Current state: 0x0000000000000100, Next state: 0x0000000000000002
[2020-03-27 09:48:00 847900] signalingClientStateChanged(108): Signaling client state changed to 2 - 'Get Security Credentials'
```

The message content is `{"candidate":"candidate:1007924187 1 udp 41885695 34.215.13.39 54676 typ relay raddr 180.117.242.198 rport 11776 generation 0 ufrag FAwX network-id 3 network-cost 10","sdpMid":"0","sdpMLineIndex":0}`

The connection gets re-established later on as the state machine handles the reconnect.

It's not immediately clear why the libWebSocket drops the connection - there is nothing that indicates a problem or any reason.

Could you please provide more information whether the master application was modified, whether any changes were done to the WebRTC SDK? Is this reproducible? If so, how can we reproduce this locally? Could you please describe your scenario?

**Comment by arthur-zou** [comment]
> @arthur-zou thanks for the logs. Looking at them, it seems that the exchange starts normally and the connection gets dropped receiving/right after receiving the ICE candidate:
> 
> ```
> [2020-03-27 09:47:50 255179] lwsWssCallbackRoutine(382): Client receive {"messagePayload":"eyJjYW5kaWRhdGUiOiJjYW5kaWRhdGU6MTAwNzkyNDE4NyAxIHVkcCA0MTg4NTY5NSAzNC4yMTUuMTMuMzkgNTQ2NzYgdHlwIHJlbGF5IHJhZGRyIDE4MC4xMTcuMjQyLjE5OCBycG9ydCAxMTc3NiBnZW5lcmF0aW9uIDAgdWZyYWcgRkF3WCBuZXR3b3JrLWlkIDMgbmV0d29yay1jb3N0IDEwIiwic2RwTWlkIjoiMCIsInNkcE1MaW5lSW5kZXgiOjB9","messageType":"ICE_CANDIDATE","senderClientId":"fc8f1ba9-b49f-4dd9-ac51-c2968fff61ae"}
> [2020/03/27 09:47:59:7363] I: lws_sul_wsping_cb: req pp on wsi 0x117700
> [2020/03/27 09:48:00:8072] I: rops_handle_POLLOUT_ws: issuing ping on wsi 0x117700: ws wss h2: 0
> [2020/03/27 09:48:00:8077] I: 
> [2020/03/27 09:48:00:8078] I: lws_issue_raw: ssl_capable_write (6) says -1
> [2020/03/27 09:48:00:8078] I: __lws_close_free_wsi: 0x117700: caller: close_and_handled
> [2020/03/27 09:48:00:8104] I: lws_vhost_unbind_wsi: vh default: count_bound_wsi 0
> [2020/03/27 09:48:00:8235] I: lws_vhost_bind_wsi: vh default: count_bound_wsi 1
> [2020/03/27 09:48:00:8250] I: lws_client_connect_via_info: role binding to h1
> [2020/03/27 09:48:00:8265] I: lws_client_connect_via_info: protocol binding to https
> [2020/03/27 09:48:00:8287] I: lws_header_table_attach: wsi 0x138ab0: ah (nil) (tsi 0, count = 0) in
> [2020/03/27 09:48:00:8307] I: _lws_create_ah: created ah 0x131b70 (size 4096): pool length 1
> [2020/03/27 09:48:00:8323] I: lws_header_table_attach: did attach wsi 0x138ab0: ah 0x131b70: count 1 (on exit)
> [2020/03/27 09:48:00:8339] I: lws_client_connect_2: 0x138ab0: address kinesisvideo.us-west-2.amazonaws.com:443
> [2020/03/27 09:48:01:0295] I: lws_client_connect_2: 0x138ab0: address kinesisvideo.us-west-2.amazonaws.com:443
> [2020/03/27 09:48:01:0364] I: lws_client_connect_3: wsi 0x138ab0: h1 https client created own conn (raw 0)
> [2020/03/27 09:48:01:0368] I: client conn using alpn list 'http/1.1'
> [2020-03-27 09:48:00 838522] lwsWssCallbackRoutine(256): WSS callback with reason 75
> [2020-03-27 09:48:00 838848] lwsWssCallbackRoutine(335): Client WSS closed
> [2020-03-27 09:48:00 840677] lwsHttpCallbackRoutine(34): HTTPS callback with reason 30
> [2020-03-27 09:48:00 847385] stepStateMachine(166): State Machine - Current state: 0x0000000000000100, Next state: 0x0000000000000002
> [2020-03-27 09:48:00 847900] signalingClientStateChanged(108): Signaling client state changed to 2 - 'Get Security Credentials'
> ```
> 
> The message content is `{"candidate":"candidate:1007924187 1 udp 41885695 34.215.13.39 54676 typ relay raddr 180.117.242.198 rport 11776 generation 0 ufrag FAwX network-id 3 network-cost 10","sdpMid":"0","sdpMLineIndex":0}`
> 
> The connection gets re-established later on as the state machine handles the reconnect.
> 
> It's not immediately clear why the libWebSocket drops the connection - there is nothing that indicates a problem or any reason.
> 
> Could you please provide more information whether the master application was modified, whether any changes were done to the WebRTC SDK? Is this reproducible? If so, how can we reproduce this locally? Could you please describe your scenario?

The master application was modified in the function sending video/audio packet and the audio frame received callback.I did not modify anything about signaling.
I can always(100%) reproduce it at home (China Telecom network),but it seldom happens in my company.Felix has tried to debug this issue with me together previously,but we have no idea about why this happens.

**Comment by MushMal** [comment]
Might as well be the networking. You are hitting us-west-2 region. Could you please run this against a region that's closer? Also, could you perhaps build the debug version of the libWebSockets so we can see more spew out of it?

**Comment by arthur-zou** [comment]
1.I can change the region,but i think even though i choose a far region,websocket also should not disconnect.If this is a hard limit of KVS backend,please tell me.
2.I have add the "-DCMAKE_BUILD_TYPE=DEBUG" when i build libwebsocket with cmake,but it seems that only a part of logs before which there is an "I:".Should i add more parameters when i build?Or is there a method to control the output log just like log level?Could you tell me how can i do?
Thank you very much.

**Comment by MushMal** [comment]
There is a limit for the connection duration. However, we also Keep alive the connection and run pong. If the pong retries fail we deem the connection as broken. There is no other way to detect the logical connection is still viable. When the libWebSockets determines the connection is dropped we cycle the state machine to reconnect. In your case it seems that you are already building the debut version of libWebSockets. The latest sample has code that sets the logging verbosity based on the env variable. Please set it to verbose so you can get more info. The region change is primarily for the packet loss and latency.

**Comment by arthur-zou** [comment]
The log level in sample is set to get more log of kvs webrtc sdk,instead of libwebsocket,is it right?I just confirm the log level i set and i think i have got all logs in sdk.Of course,if you need to add some log to a specified location where you want,you can tell me the file and line number.

**Comment by disa6302** [comment]
Hello @arthur-zou , 
Yes. We would like to get kvs webrtc sdk logs as well. Please run `export AWS_KVS_LOG_LEVEL=1` to get VERBOSE logs as well. Thanks!

**Comment by arthur-zou** [comment]
I think the log i attached has contained all of SDK log and libwebsocket log due to i have change the DLOGD/DLOGI/…………………… to our own log saving function.If you find that there are any log that should have been output but it can not be found in my log file,you can tell me the file name and line and i will check again.

**Comment by MushMal** [comment]
@arthur-zou we seem unable to make further progress on this issue as it's not reproducible locally here. Could you please pull down the latest and tun it again with debug built libWebSockets and debug LOG verbosity on the WebRTC SDK. As stated earlier, we are not sure whether it's the network packet loss that causes the disconnection.

**Comment by MushMal** [comment]
Resolving as it seems to be stale
