### ISSUE TITLE
Viewer exits gracefully after 45 min

### ISSUE THREAD

**Issue by disa6302** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#309]
The viewer app exits gracefully every time after a 45 minute run. The logs do not have any critical error code as well.

**Comment by MushMal** [comment]
@disa6302 tracked this to THREAD_SLEEP parameter bitness issue which is tracked in https://github.com/awslabs/amazon-kinesis-video-streams-pic/issues/36

**Comment by disa6302** [comment]
Closing this since the PR in PIC is merged.
