### ISSUE TITLE
cross compiling failed when compiling libopenssl

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#313]
amazon-kinesis-video-streams-webrtc-sdk-c/open-source/local\"" -DENGINESDIR="\"/home/user/_workspace/*******/video-streaming/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/local/lib/engines-1.1\"" -Wall -O3 -pthread -mabi=32 -DBN_DIV3W -mips2 -o fuzz/bignum-test fuzz/bignum.o fuzz/test-corpus.o -L. -lcrypto -ldl -pthread
./libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
./libcrypto.so: undefined reference to `getcontext'
./libcrypto.so: undefined reference to `setcontext'
./libcrypto.so: undefined reference to `makecontext'
collect2: error: ld returned 1 exit status
Makefile.shared:179: recipe for target 'link_app.gnu' failed
make[5]: *** [link_app.gnu] Error 1
Makefile:6347: recipe for target 'fuzz/asn1-test' failed
make[4]: *** [fuzz/asn1-test] Error 2
make[4]: *** Waiting for unfinished jobs....
./libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
./libcrypto.so: undefined reference to `getcontext'
./libcrypto.so: undefined reference to `setcontext'
./libcrypto.so: undefined reference to `makecontext'
collect2: error: ld returned 1 exit status
Makefile.shared:179: recipe for target 'link_app.gnu' failed
make[5]: *** [link_app.gnu] Error 1
Makefile:6372: recipe for target 'fuzz/asn1parse-test' failed
make[4]: *** [fuzz/asn1parse-test] Error 2
./libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
./libcrypto.so: undefined reference to `getcontext'
./libcrypto.so: undefined reference to `setcontext'
./libcrypto.so: undefined reference to `makecontext'
collect2: error: ld returned 1 exit status
Makefile.shared:179: recipe for target 'link_app.gnu' failed
make[5]: *** [link_app.gnu] Error 1
Makefile:6389: recipe for target 'fuzz/bignum-test' failed
make[4]: *** [fuzz/bignum-test] Error 2
LD_LIBRARY_PATH=.: /home/user/_workspace/*******/mips-gcc472-glibc216-32bit/bin/mips-linux-uclibc-gnu-gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DAES_ASM -DOPENSSLDIR="\"/home/user/_workspace/*******/video-streaming/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/local\"" -DENGINESDIR="\"/home/user/_workspace/*******/video-streaming/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/local/lib/engines-1.1\"" -Wall -O3 -pthread -mabi=32 -DBN_DIV3W -mips2 -fPIC -DOPENSSL_USE_NODELETE -Wl,-znodelete -mabi=32 -shared -Wl,-Bsymbolic -Wl,-soname=libssl.so.1.1 -o libssl.so.1.1 -Wl,--whole-archive,--version-script=ssl.map libssl.a -Wl,--no-whole-archive -L. -lcrypto -ldl -pthread
./libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
Makefile:132: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/project_libopenssl.dir/build.make:111: recipe for target 'build/src/project_libopenssl-stamp/project_libopenssl-build' failed
make[2]: *** [build/src/project_libopenssl-stamp/project_libopenssl-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/project_libopenssl.dir/all' failed
make[1]: *** [CMakeFiles/project_libopenssl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:59 (message):
  CMake step for libopenssl failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:83 (build_dependency)

**Comment by ycyang1229** [comment]
It is one issue I met before, and I fixed it by adding no-async.


cmake_minimum_required(VERSION 2.8)

project(libopenssl-download NONE)

find_program(MAKE_EXE NAMES make)

if (BUILD_STATIC)
  SET(OPENSSL_EXTRA ${OPENSSL_EXTRA} no-shared no-dso)
endif()

if (DEFINED BUILD_OPENSSL_PLATFORM AND NOT BUILD_OPENSSL_PLATFORM STREQUAL OFF)
  SET(CONFIGURE_COMMAND ${CMAKE_CURRENT_BINARY_DIR}/build/src/project_libopenssl/Configure ${OPENSSL_EXTRA} **no-async** --prefix=${OPEN_SRC_INSTALL_PREFIX} --openssldir=${OPEN_SRC_INSTALL_PREFIX} ${BUILD_OPENSSL_PLATFORM})
else()
  SET(CONFIGURE_COMMAND ${CMAKE_CURRENT_BINARY_DIR}/build/src/project_libopenssl/config ${OPENSSL_EXTRA} --prefix=${OPEN_SRC_INSTALL_PREFIX} --openssldir=${OPEN_SRC_INSTALL_PREFIX})
endif()

**Comment by ycyang1229** [comment]
[cross-compiling.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4401701/cross-compiling.log)

**Comment by juno52wendy** [comment]
cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-linux

**Comment by Sean-Der** [comment]
@ycyang1229 I think that could make a great addition to the CMakeLists.txt!

Maybe `-DBUILD_OPENSSL_EXTRA_OPTIONS` and we could append them to OPENSSL_EXTRA maybe?

**Comment by ycyang1229** [comment]
@Sean-Der That may be an option.
