### ISSUE TITLE
DeleteSignalingChannel Public API call

### ISSUE THREAD

**Issue by TomyTomm** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#328]
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_DeleteSignalingChannel.html
There's an API call to delete signaling channels, but it would be nice to have that wrapped in a C-style API call.

**Comment by MushMal** [comment]
@TomyTomm could you please describe your scenario? We do have a few backend public APIs that we are not modeling in the SDK as we model the lifecycle of the embedded devices. 

In particular, the DeleteSignalingChannel API is implemented in the SDK but not exposed publicly - we use it in the tests. 

Perhaps, if you have a compelling scenario we could expose it

**Comment by TomyTomm** [comment]
Yeah, so I'm currently working on importing this SDK for use in ROS (Robot Operating System) ecosystem. So I have a TurtleBot3 that connects as Master and creates the signaling channel if it doesn't already exist. For cleanup purposes, I was thinking it would be nice to delete the signaling channel on destruction so resources aren't leaked.

**Comment by MushMal** [comment]
Nice! Thanks. Let's use this issue to track this. Having clear customer scenario makes it easier to expose this publicly.

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/346 got merged. Resolving
