### ISSUE TITLE
Move CHK_LOG_ERR_NV to PIC

### ISSUE THREAD

**Issue by MushMal** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#329]
We need this functionality across other repos. Need to move to PIC

**Comment by chehefen** [comment]
PIC has CHK_LOG_ERR.

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-pic/commit/266f5fc0ca673faf78d783977be4333583012c37

moves the CHK_LOG_ERR_NV to PIC. We will resolve this issue once we re-base the submodule on the latest commit
