### ISSUE TITLE
Saving to file

### ISSUE THREAD

**Issue by dannymarosi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#337]
How can I save the video before and during streaming?
I know how to save to video file while streaming.
But I would like to start saving before the far side is connected.
Then continue saving during the streaming session.
I am using kvsWebRTCClientMasterGstreamerSample.c 

Thanks,
Danny Marosi

**Comment by MushMal** [comment]
Take a look at this enhancement that we didn't merge: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/191

In this case, the sample starts streaming into KVS streams for persistence right away, before any Viewers are connected. Once a Viewer is connected, it will receive the current frames.

The reason why this is not merged is that we don't want to pull the dependency into this repository and will be adding this sample to a new Samples repository soon.

You could use the same as a base and perhaps enhance the GStreamer pipeline to also dump the frames into the file.

**Comment by dannymarosi** [comment]
Hi @MushMal

I am having difficulty cloning out the kvs_persistence branch.
Can you give me direction how to get the kvs_persistence branch running on the raspberry pi?

Thanks, 
Danny Marosi

**Comment by dannymarosi** [comment]
Hi @MushMal
Fail to compile after checking out  'remotes/origin/kvs_persistence' branch

pi@raspberrypi:~/amazon-kinesis-video-streams-webrtc-sdk-c/build $ git branch
* (detached from origin/kvs_persistence)
  master

Can you check?
Thanks,
Danny Marosi

**Comment by dannymarosi** [comment]
See attached 
[CMakeError.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4459642/CMakeError.log)
[CMakeOutput.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4459643/CMakeOutput.log)

**Comment by MushMal** [comment]
@dannymarosi apologies - just getting back to this. It seems that the minimal viable program compilation fails - this is what the cmake compiles to check whether the compiler is supported.. Might be related to older versions of cmake and gcc. Could you please upgrade the cmake and the gcc? Seems that you are using gcc 4.9.2 which in itself should be more than adequate to compile the core projects (perhaps with the exception of the unit tests which require modern C++) but somehow the liner for the min program for cmake fails to load pthread library.

CheckSymbolExists.c:(.text+0x38): undefined reference to `pthread_create'

**Comment by dannymarosi** [comment]
@MushMal
I verified that I have the latest gcc and cmake for my raspbian distribution
 gcc (Raspbian 4.9.2-10) 4.9.2 
cmake version 3.6.2
uname –r  
4.4.50-v7+

I notice 2 things:
1.  “CMake”  folder  in master branch was  replace by “cmake-scripts” in kvs_persitence branch.
2.  Fail compiling libcurl

![kvs_persistenc_vs_master_branch](https://user-images.githubusercontent.com/62627034/79021336-15a4f400-7b30-11ea-942b-9f3f394f61ca.jpg)

![fail_compile_libcurl](https://user-images.githubusercontent.com/62627034/79021378-2f463b80-7b30-11ea-8d5f-c99dd4e8dd29.jpg)

Can you check?

Thanks,
Danny Marosi

**Comment by MushMal** [comment]
@dannymarosi sorry for the delay, I really can't tell what's wrong with this. A couple of questions.. Are you able to get a clean build of the latest master branch? If so, all you need is to look at the sample to understand how the "media loop" is started initially in order to adapt for your case.

**Comment by MushMal** [comment]
@dannymarosi the persistence branch was not intended to be merged with the master - this was a small demo. The reason why we don't want to merge it to master is that it pulls in the C repository to be used in the sample which, in turn, has a dependency on curl. We are working on publishing this as a sample in a new Samples repository soon.

In the meanwhile, you could indeed pull down the webrtc repository and the c producer repository https://github.com/awslabs/amazon-kinesis-video-streams-producer-c

The c producer repository builds libCurl.

I believe the sample is using channel name and stream name to persist as separate parameters.

**Comment by dannymarosi** [comment]
@MushMal
I found the libcurl-CMakeLists.txt in the kvs-persistence branch then recomple.
It looks that libcurl is messing configuration.
See attached file.
[libcurl_fail_log_2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4471021/libcurl_fail_log_2.txt)
Can you help?

**Comment by dannymarosi** [comment]
@MushMal
Thanks You answered my questions.

**Comment by MushMal** [comment]
No problems. Please feel free to cut issues if you have any further questions
