### ISSUE TITLE
Is there any sample code to register customized logprint

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#340]
Function pointer globalCustomLogPrintFn = defaultLogPrint.  defaultLogPrint writes to standard io.
We like to use our logger/logging files to manage the debug print
There is some sample code in open-source/amazon-kinesis-video-streams-producer-c/samples/KvsVideoOnlyStreamingSample.c
But can't find in samples/kvsWebRTCClientMaster.c or samples/Common.c

**Comment by MushMal** [comment]
Related to #325 

The C producer has proper facilities to overwrite the logging and a lot of other functionality. The WebRTC doesn't expose this. We will be providing means to specify callbacks/overwrite some of the platform functionality including logger functionality soon, including some implementation for file based logger.

Meanwhile, you could set your logger function pointer.

**Comment by zwei333** [comment]
Could you please explain a llittle more on "Meanwhile, you could set your logger function pointer."?

**Comment by MushMal** [comment]
In PIC. utils/src/Logger.c

The last line in the file LN84. This sets the logger function pointer. You can export the globalCustomLogPrintFn and set it to your function pointer.

Again, apologies for this customization, we will be addressing this properly.

**Comment by zwei333** [comment]
Got it.  Thanks.  Forgot that globalCustomLogPrintFn is global. 
Please feel free to close this issue if you don't need it.

**Comment by MushMal** [comment]
No problems. We will address this in an easier manner. NOTE: all platform-level integration is done easily at the core via function pointers (for perf reasons).

As we are tracking this issue already, I am going to be resolving this one.
