### ISSUE TITLE
Sending through data channel

### ISSUE THREAD

**Issue by CatsNipYummy** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#343]
Is there an example that sends data through the data channel? I see some tests but is there an example? I would like to send data along with audio and video.

**Comment by Sean-Der** [comment]
Hey @CatsNipYummy sorry for the delay!

In [Common.c](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L15-L29) we accept and print incoming datachannel messages. If you use our JS/Mobile examples you can enter these DataChannel callbacks easily.

Right now in our sample code we don't have anything that sends outbound, but it would be really easy to echo all input back!

[createDataChannel_Disconnected](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/tst/DataChannelFunctionalityTest.cpp#L13) is also a good demo of it E2E. Even though it is a test it is only using public APIs.

**Comment by MushMal** [comment]
@CatsNipYummy I am going to resolve this issue. Please feel free to re-open if you have any further questions.

**Comment by mdonahoe** [comment]
I tried to edit the onDataChannel and onDataChannelMessage functions to get the master to reply to the viewer, but I don't see any replies in the viewer app.
