### ISSUE TITLE
kvs-persistence

### ISSUE THREAD

**Issue by dannymarosi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#345]
I am working on integrating kvs-persistence into my branch (inherit form master on 4/9/2020).
I getting  the following compiler error:
kvsWebRTCClientMasterGstreamerSample.c:(.text+0x1008): undefined reference to `createDefaultDeviceInfo'

The definition for createDefaultDeviceInfo'() can be found at :
 amazon-kinesis-video-streams-webrtc-sdk-c/open-source/amazon-kinesis-video-streams-producer-c/src/include/com/amazonaws/kinesis/video/cproducer/Include.h

The following include is in Sample.h:
#include <com/amazonaws/kinesis/video/cproducer/Include.h>

What need to be done to enable calling functions that reside under amazon-kinesis-video-streams-producer-c  folder?

**Comment by MushMal** [comment]
@dannymarosi if you are simply using the master sample as a base, perhaps you can also submodule the c producer project into your sample and reference the header files from within.

We are in a process of putting together a separate repository for samples but that will take some time.

**Comment by dannymarosi** [comment]
@ MushMal
I was able to build and run the kvs-persistence branch after several modifications.
All works well.
Here are the changes:

//--- disable libcurl build
Modify: /home/pi/amazon-kinesis-video-streams-webrtc-sdk-c/CMakeLists.txt
Was: set(BUILD_COMMON_CURL TRUE CACHE BOOL "Build ProducerC without CURL Support" FORCE)
Is:  set(BUILD_COMMON_CURL FALSE CACHE BOOL "Build ProducerC without CURL Support" FORCE)


//--- comment out extra parameter in createDefaultCallbacksProviderWithAwsCredentials()
Modify: /home/pi/amazon-kinesis-video-streams-webrtc-sdk-c/samples/kvsWebRTCClientMaster.c
        /home/pi/amazon-kinesis-video-streams-webrtc-sdk-c/samples/kvsWebRTCClientMasterGstreamerSample.c

CHK_STATUS(createDefaultCallbacksProviderWithAwsCredentials(pAwsCredentials->accessKeyId,
                            pAwsCredentials->secretKey,
                            pAwsCredentials->sessionToken,
                            MAX_UINT64,
                            pSampleConfiguration->channelInfo.pRegion,
                            pSampleConfiguration->pCaCertPath,
                            NULL,
                            NULL,
        //                  FALSE,
                            &pClientCallbacks));
//--- run cmake
pi@raspberrypi:~/amazon-kinesis-video-streams-webrtc-sdk-c/build $ cmake ..
//--- run make
pi@raspberrypi:~/amazon-kinesis-video-streams-webrtc-sdk-c/build $ make

Thanks,
Danny Marosi

**Comment by MushMal** [comment]
Thanks Danny, the codebase had drifted away since the branching. We will certainly implement this once we port the persistence sample into Samples repository. Appreciate the help!
