### ISSUE TITLE
Implement ICE renomination

### ISSUE THREAD

**Issue by Sean-Der** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#350]
In the current standardized version of ICE you choose one candidate pair, and use it the entire time. This means if you select TURN you will stick with it forever (or STUN if host was possible)

[ICE Renominations](https://tools.ietf.org/html/draft-thatcher-ice-renomination-00) make it possible to switch network routes at a later time. This is only implemented in Chromium, and not standardized.

We should evaluate if this is something we want, and should probably email MMUSIC and see if we can get this standardized.

**Comment by fernandoc1** [comment]
This is a nice feature.
One of the discussions within my organization is that we should reduce the use of TURN as much as possible. We are going to sell camera for surveillance, and people will be looking at it 24h every day. If somehow TURN is the connection chosen, our costs will go out of our expectations and our customers budget will explode, rendering us a huge headache.
So, hearing that this feature is being considered, bring us hope.

**Comment by disa6302** [comment]
This feature is being tracked by the team internally.
