### ISSUE TITLE
[BUG] ICE password not conforming to newer versions of chrome

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#351]
@MushMal @chehefen @disa6302 @Sean-Der 

js-sdk version: 1.0.2
System: Windows 10
Chrome Version: 81.0.4044.92 (Official Build) (64-bit)
Description:
The following exception is thrown with newest version of chrome; however, the javascript sdk still works with older versions of chrome.
```
Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Failed to apply the description for 0: Invalid ICE parameters: ICE pwd must contain only alphanumeric characters, '+', and '/'.
```
Initial investigation shows that Turn passwords are base64, and includes = signs. We understand it is a huge change on the service side. Is it possible to change the alignment base64 passwords of turn servers so that it does not contain =?

**Comment by MushMal** [comment]
Thanks @Sean-Der 

@suggestedfixes could you please give this a try and resolve if fixed

**Comment by suggestedfixes** [comment]
@MushMal tested with a newer build. Have not replicated.
