### ISSUE TITLE
Compiler warnings aren't enabled in travis

### ISSUE THREAD

**Issue by Sean-Der** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#354]
I don't know why/when they got disabled, but we should turn them back on!

This doesn't need to be done at once, someone can move one suite at a time.

- [x] OSX Clang
- [x] OSX GCC
- [ ] Linux GCC

**Comment by disa6302** [comment]
We need to let the warnings on Linux GCC. The current warnings are related to inline functions in PIC. Closing this ticket and will recreate if we need to enable warnings in the future.
