### ISSUE TITLE
kvsWebRTCClientMaster example code test in alaw audio format

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#356]
We want to test audio format in alaw,
and not sure how to configuration it in example code.

attached audio frames with alaw format
[test_alaw_sample_0417.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4492010/test_alaw_sample_0417.zip)

Thanks

**Comment by chehefen** [comment]
you just need to change these two lines to RTC_CODEC_ALAW:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L392
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L410

**Comment by MushMal** [comment]
Re-open if need more info after inspecting the suggested code

**Comment by henryChmn** [comment]
@chehefen Thanks, it's working now.
