### ISSUE TITLE
WebRTC Signaling Protocol Options for Emergency Call Box

### ISSUE THREAD

**Issue by dannymarosi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#360]
What signaling protocol would work best with WebRTC to support the following use case? 

We are interested in a video application where the system containing the camera will place a PSTN phone call into an answering facility. 
Within this answering facility there will be a number of dispatchers (each with a phone and each with their own PC). 
An incoming PSTN call can be answered by any one of the available dispatchers (i.e. not known a priori which dispatcher will answer an incoming call). 
The dispatcher that answers the incoming call will want to see the camera video on their own PC.
 We are planning to use WebRTC for video transport between the camera and the dispatcher’s PC 
(to achieve minimum latency in the video relative to the audio received over the PSTN).

Thanks,
Danny Marosi

**Comment by MushMal** [comment]
@dannymarosi it's not clear what your question is. So, it seems that you would like to use WebRTC solution for Video ONLY. You can try using the camera as a Master and the dispatchers PC application as a viewer. The Master will start immediately with the PSTN call. The viewer will start when the dispatcher takes the call.

You can look at the master/viewer sample applications.

Please refine your question perhaps I am not understanding it.

**Comment by dannymarosi** [comment]
@MushMal
The master (a call box ) will start a PSTN call and at the same time start a persistent video streaming.
How can the viewer (a PC on the dispatcher desk) be alerted for the incoming call?
Can a SIP protocol be used to alert the viewer for an incoming call?

**Comment by MushMal** [comment]
I see. You might want to do some solution architecting for this type of signaling. Generally, we consider it outside of the WebRTC solution we provide (yet).

I wonder if you can swap it around - by doing master the dispatcher (who will be connected always) and then viewer be the caller... This will obviously require some changes to the master/viewer code samples.

**Comment by dannymarosi** [comment]
@MushMal
Can you refer us to any resources that can help us with solution architecture for our use case?

**Comment by garishsood** [comment]
@dannymarosi My name is Girish and I am the product manager for Kinesis Video. Would you mind sending me a note at garisood@amazon.com and we can schedule a call to discuss your usecase and evaluate if KVS WebRTC would be a fit.

**Comment by dannymarosi** [comment]
@MushMal
Thanks for your help
