### ISSUE TITLE
Up to one turn server

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#363]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.c#L94 says only up to one turn server is supported, but we may have a couple of turn servers and would like to pick the best one during probing, could we support multiple turn servers?

The only way to config ice servers is to create a peer connection, which is not very convenient, e.g. we want to create peer connection first, then wait for connection requests, however allocate turn servers is a waste if no connection request comes, more efficient way would be we could add turn servers whenever SDP messages arrive.

**Comment by chehefen** [comment]
@staowyze, we will add support for multiple turn servers soon. Regarding your second issue. Candidate gathering wont start until you call setLocalDescription. In the samples we are calling setLocalDescription when it receives connection requests, which then kicks off turn allocation. Is this solution working for you?

**Comment by staowyze** [comment]
I don't see any API to add turn servers other than creating peer connection, would you mind adding one?

**Comment by chehefen** [comment]
From what I understood, the reason that you want to delay adding turn server is to avoid allocate turn when you create peerConnection is that right? but it would only start allocating when after you call setLocalDescription.

**Comment by chehefen** [comment]
@staowyze multi turn server support is added in this PR: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/365. Can you close this issue? Thanks.

**Comment by chehefen** [comment]
resolving the issue since it multi turn server supported has been added in #365

**Comment by disa6302** [comment]
Closing this issue

**Comment by staowyze** [comment]
> From what I understood, the reason that you want to delay adding turn server is to avoid allocate turn when you create peerConnection is that right? but it would only start allocating when after you call setLocalDescription.

Sorry, was offline in the past a couple of weeks. I don't find any APIs that can add turn servers after creating the peerConnection, in my case, I don't have available turn servers while creating peerConnection, so I would like to have an API e.g. addTurnServers(peerConnection, turnServers).

**Comment by chehefen** [comment]
Hi @staowyze, can you clarify why you cant start allocating turn after your app has received the sdp message (offer/answer) like we did in the sample? Thanks

**Comment by staowyze** [comment]
allocating turn is not after SDP arrives from my understanding
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L360

**Comment by chehefen** [comment]
that's just getting the turn server ips and credential from backend. The actual allocation happens here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L218

**Comment by staowyze** [comment]
i see the gap, "allocation" I meant getting turn server ips, not the allocation in turn's RFC.
The problem is I don't want to get turn server ips in advance, as they may not be used unless SDP arrives, ideally, I would like to get turn server ips only when SDP arrives.

**Comment by MushMal** [comment]
@staowyze, the getIceServerConfig is executed when the signaling client is being created and after that refreshed prior its expiration. This is optimized so we can have fast connection when the offer arrives - i.e. the signaling client always has the "fresh" ICE config when being requested.

Is your main concern the bandwidth utilization during the refresh? Is it the initial signaling client creation time? For the latter, we have a mode that does async getIceServerConfig which is the default in samples.

**Comment by MushMal** [comment]
Also, as this is a separate topic, do you mind furnishing this question in a separate issue so we can track it better?

**Comment by staowyze** [comment]
sounds good, closing the issue
