### ISSUE TITLE
gSampleConfiguration not wired up to local configurations in sigint handler in sample apps

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#370]
Seems like the sigint handler is designed to broadcast for threads to stop and perform some cleanups. But gSampleConfiguration was never wired up to point to local pSampleConfigurations. So it might not work as intended.

**Comment by suggestedfixes** [comment]
Update. Found the assignment in Master samples, but not in the Viewer sample.

**Comment by MushMal** [comment]
Oh, odd... Would you like to push a pull request please?
