### ISSUE TITLE
[Question] Is it safe to enable caching endpoints? Does the code refresh the cache if endpoint connections fail?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#371]
In Common.c, there is a line
pSampleConfiguration->channelInfo.cachingEndpoint = FALSE;

Would it be safe to set it to TRUE. And the would the code refresh cached Endpoint if fetch endpoint failure?

**Comment by MushMal** [comment]
Caching of the front-end APIs is not implemented yet. I created an issue to track it: #372 372

**Comment by MushMal** [comment]
I will resolve this for now as we will track this work in the #372
