### ISSUE TITLE
Implement Front-End API caching policy

### ISSUE THREAD

**Issue by MushMal** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#372]

**Comment by arthur-zou** [comment]
We need the caching enpoints solution.
Our device needs to sleep for power saving.It can not maintain websocket connection when it is sleeping.
So we will disconnect when it is going to sleep and reconenct when it wakes up and it will cost too much time for describe channel/get endpoint. 
Could you help to implement the enpoint caching solution?
Thanks.

**Comment by MushMal** [comment]
@arthur-zou , thanks for the input. Let us prioritize this work.

**Comment by MushMal** [comment]
This is in. Part of this (file persistence caching) is in flight. Resolving
