### ISSUE TITLE
Better build indicators

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#375]
Current build indicators are not helpful when selecting stable commits. If we wanted to build the latest commit, a leap of faith of required. It might be nice to have a process in place to make sure latest code does not break existing tests.

**Comment by MushMal** [comment]
@suggestedfixes could you please elaborate? Every change that gets merged into master branch requires a clean build/pass which executes variety of platforms/unit tests.

We independently run more grueling tests and some manual test scenarios before cutting or tagging a "release" indicating more stable version. For WebRTC SDK we have a single release so far 1.0.0.

**Comment by suggestedfixes** [comment]
Beside each commit, there is a checkmark/cross indicator indicates whether CI passes. There are very few commits with a checkmark.

**Comment by MushMal** [comment]
Not sure what this refers to but every one of our commits undergoes the full CI check before being allowed to merge. We don't even have an easy way to override this for admins.

**Comment by suggestedfixes** [comment]
I'm referring to the Travis status beside each commit.
<img width="663" alt="Screen Shot 2020-04-22 at 3 30 36 PM" src="https://user-images.githubusercontent.com/61390265/80040234-7e845880-84ae-11ea-8b55-f1166b3125f6.png">

**Comment by MushMal** [comment]
Understood. While we are running PRs some of the builds can and might fail. This is normal. These are the builds that are not on the master branch but the PR branches. The master should always be clean.

**Comment by suggestedfixes** [comment]
The current status is error, from readme
<img width="706" alt="Screen Shot 2020-04-22 at 3 45 15 PM" src="https://user-images.githubusercontent.com/61390265/80041085-5a297b80-84b0-11ea-9ea1-8ce7d8ca384b.png">

**Comment by suggestedfixes** [comment]
I think it's possible for Travis to configure flaky tests. I've seen codebase a few magnitudes bigger and have a tolerance of passing them.

**Comment by MushMal** [comment]
Not sure how the badge is configured. Our flakiness sometimes is caused by the minute timing issues as some of our unit tests really are full integ tests that hit the backend and we have fault-injected scenarios.

Trying to shut these tests in favor of a clean badge is not a good trade-off. However, we will continuously invest in making the tests more stable.

Incidentally, I wonder what codebases are you referring to that has the depth and complexity as well as the coverage? We could learn from them

**Comment by MushMal** [comment]
Oh, I get it. This particular case is due to the instrumented allocators merge initially and later multi-turn merged and causing a leak in the test. We will fix this ASAP and we will have clean runs

**Comment by suggestedfixes** [comment]
```
Incidentally, I wonder what codebases are you referring to that has the depth and complexity as well as the coverage? 
```
I was lucky enough to intern at one of those places that has a monolithic code base for all their teams offices across the globe, my internship project has about 98% coverage. But given that you work at Amazon, there could be large teams you can talk to where they have some of those toolings, the problem here is that you probably cannot use them on open source projects.

**Comment by suggestedfixes** [comment]
Closing because duplicate of #428
