### ISSUE TITLE
Can't watch video after update latest version chrome 

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#377]
After update chrome  81.0.4044.122 (Official Build) (64-bit), Test page can't watch video from ipcam.

Ipcam webrtc SDK verbose log: 
[ipcam_debug_verbose_log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4519883/ipcam_debug_verbose_log.txt)

Test page log:
[webrtc2.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4519886/webrtc2.log)

The previous version can watch video:
Version 80.0.3987.162 (Official Build) (64-bit)

Thanks

**Comment by Sean-Der** [comment]
Hey @henryChmn 

Can you update to [1.0.0](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/releases/tag/v1.0.0) 

The exact fix you need is 389703f1f46ce71ab0a77bf9a061feb4a44e9636

thanks!

**Comment by henryChmn** [comment]
Hi @Sean-Der ,

Thanks, we will do it.
