### ISSUE TITLE
Memory keep increasing with P2P

### ISSUE THREAD

**Issue by sharadrj** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#383]
An issue with potential memory leak has been reported - 

I found that memory occupied will keep rising when P2P connection is established. 
Could you please help to check? 

Log location: 
It started after P2P connection is established. 
It seems that defaultMemAlloc is keeping called and when i quit live streaming,sdk will free the streaming session and free large amount of memory. 
But i don't know why sdk needs so much malloc times when watch live streaming. 
Besides, i am not sure if all memory has been freed,it also needs to been verified. 
I think you can reproduce this issue easily,just watch live streaming and cat /proc/<pid>/status. 

[memory_1636[3] copy.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4530346/memory_1636.3.copy.txt)

![1587723018(1) 3 jpg](https://user-images.githubusercontent.com/7018404/80238684-afca6900-8613-11ea-8cb0-cd56bc4c6869.png)

**Comment by MushMal** [comment]
I would like to add some more info on this while we investigate it.

The P2P scenario is likely going through UDP in which case we utilize the jitter buffer to keep the RTP packets. The jitter buffer will serve these packets in case of retry. Currently, every RTP packet is a single allocation with another allocation (header) to keep the track of it. For video,  as the frames are produced, each frame will evaluate into multiple allocations. This might explain the temporal increase in memory. The memory consumption should stabilize after steady streaming and all the memory will be collected at the end.

There is SET_INSTRUMENTED_ALLOCATORS() and RESET_INSTRUMENTED_ALLOCATORS() pair that sets instrumented allocators when compiled with INSTRUMENTED_ALLOCATORS define - we started using this in the unit tests to ensure no memory leaks occur. 

One of the leaks was fixed recently in the jitter buffer so I would like to ask you to update to the latest commit and retry as we will do that internally too.

**Comment by lherman-cs** [comment]
I've run Valgrind a couple of times, and I couldn't find possible memory leaks.

![Screenshot from 2020-04-27 15-57-18](https://user-images.githubusercontent.com/15654932/80415087-04821400-88a0-11ea-9a6d-e207e0b3235a.png).

So, as @MushMal has suggested, I think updating the version to the latest commit will fix the problem. 

To add more context about the jitter buffer fix, following are the original issue and the PR to fix it:
* Issue: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/307
* PR: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/362

**Comment by lherman-cs** [comment]
Following shows that `createRtpPacketFromBytes` called malloc the most:

<img width="691" alt="Screen Shot 2020-04-24 at 6 48 08 PM" src="https://user-images.githubusercontent.com/15654932/80730492-a6d80c80-8ad7-11ea-83a6-9fd553bc31ad.png">

**Comment by MushMal** [comment]
I am going to resolve this for now, we don't really have a memory leak but might benefit from a less frequent allocation/free which is tracked by a separate issue
