### ISSUE TITLE
[Question] Recommended Steps Handling Disconnection/Lost Transceiver?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#387]
We are testing streaming for as long as we can. The current issue we are encountering is that if for some reason when the master side disconnects and went back online, a naive viewer would not have detected it, and the video freezes indefinitely. One thing we can do on the viewer side can be monitoring the video stats through the (https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_Statistics_API), and retry connection if no video for more than n seconds, and possibly send some message through the data channel to tell the master there is no video. The master then can perform a quick diagnostics on recovering some of the threads or decide to reboot itself, then inform the viewer what the master is going to do. Then the viewer performs some more steps depending on the master's choice.

So our question is would this be a good approach? Or are there some APIs we can call, or some parameters/settings we can tweak to solve this problem?

**Comment by chehefen** [comment]
Can you clarify you mean by master "disconnects and went back online" ? If master connection resumes within 15s the RTC_PEER_CONNECTION_STATE  would still remain connected and viewer should also keep receiving. If the disconnection exceeds 15s then the master has to be restarted. In that case The viewer should observe connection state change to disconnected here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L39, and viewer has to be restarted too because the peerConnectionObj for both master and viewer are no longer usable.

**Comment by suggestedfixes** [comment]
Disconnects and went back online might have occurred when Gstreamer sends a spurious eos and ending a video thread, and we have decided to reboot the app or the video thread. Another case might have been a segmentation fault and the supervisor process has detected master might need a reboot.
Our use case is to maintain master alive as long as possible and viewer alive as long as possible. If it means to restart the master or viewer, we probably have to do that.

**Comment by suggestedfixes** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/c2bff6ea67c01771ba0c357a6ba78fde7b849871/src/source/Ice/IceAgent.h#L30

Isn't the KVS_ICE_ENTER_STATE_DISCONNECTION_GRACE_PERIOD too little. Relating to Nyquist Sampling Theorem, shouldn't this be double the KEEP_ALIVE_INTERVAL?

Also if the network has a lot of jitter, wouldn't this probabilistically fail a lot over time?

**Comment by chehefen** [comment]
15s is the time it will wait before raising the disconnection flag if nothing has been received. After that the flag has been raised, it will wait 30 more seconds for disconnect to recover. The 30s is defined in KVS_ICE_ENTER_STATE_FAILED_GRACE_PERIOD.

**Comment by chehefen** [comment]
but yh, you are right, I will change KVS_ICE_ENTER_STATE_DISCONNECTION_GRACE_PERIOD to 30s.

**Comment by suggestedfixes** [comment]
Would it also be possible to recreate signaling client on ice disconnection? Or resend ice candidate pair or reboot ice agent somehow?

**Comment by suggestedfixes** [comment]
Found this:
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/restartIce

**Comment by suggestedfixes** [comment]
Also, we might want to allow new offers coming in if ice is in one of the disconnected/fail/closed state. So the following commit is probably too strict?
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/0099c46bed8074129efc937c2d62226442549a0a

**Comment by chehefen** [comment]
Right now we dont have restartIce(). The work around is to free the PeerConnection once its state is changed to disconnected/fail/closed. In the sample, when we detect that peerConnection state has entered disconnected/fail/closed, we trigger the tear down pSampleStreamingSession which in turn tears down its PeerConnection. Once the teardown is completed, it's ready to receive offer again. But you can start tearing down on fail/closed only.

**Comment by chehefen** [comment]
> isconnects and went back online might have occurred when Gstreamer sends a spurious eos and ending a video thread, and we have decided to reboot the app or the video thread.

you dont need to kill the webrtc app when gstreamer send an eos right? You can just recreate the gstreamer pipeline and start sending again. If you are rebooting the app I dont think iceRestart() will help much because it just reestablish the ice connection and the new process wont have the dtls and srtp session that already negotiated.

**Comment by suggestedfixes** [comment]
I had attempted to recreate the pipeline, the issue was that the recreated pipeline had failed to find plugins somehow. Let me redo this experiment.
