### ISSUE TITLE
Don't use CMAKE_SOURCE_DIR

### ISSUE THREAD

**Issue by enobufs** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#389]
When this project (KinesisVideoWebRTCClient) is included in another project using add_subdirectory(), CMAKE_SOURCE_DIR no longer points to the path originally intended.

`/CMake/Utilities.cmake` is using CMAKE_SOURCE_DIR.

Here's a proposal:
```
diff --git a/CMake/Utilities.cmake b/CMake/Utilities.cmake
index 2cca8f6..6f98b6a 100644
--- a/CMake/Utilities.cmake
+++ b/CMake/Utilities.cmake
@@ -40,7 +40,7 @@ function(build_dependency lib_name)

   # build library
   configure_file(
-    ${CMAKE_SOURCE_DIR}/CMake/Dependencies/lib${lib_name}-CMakeLists.txt
+    ${CMAKE_CURRENT_SOURCE_DIR}/Dependencies/lib${lib_name}-CMakeLists.txt
     ${KINESIS_VIDEO_OPEN_SOURCE_SRC}/lib${lib_name}/CMakeLists.txt COPYONLY)
   execute_process(
     COMMAND ${CMAKE_COMMAND} ${build_args}
```

**Comment by chehefen** [comment]
thanks. feel free to submit a pull request for this.

**Comment by enobufs** [comment]
@chehefen There was one more location using CMAKE_SOURCE_DIR which prevents us including this SDK from a parent CMake project.  PR is incoming. (are you able to reopen this?)
