### ISSUE TITLE
Support setting codecs/tracks on CLI for GStreamer Example

### ISSUE THREAD

**Issue by Sean-Der** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#39]
Users shouldn't need to edit to get the following

* [ ] Using VP8
* [ ] Using PCM
* [ ] Using `videotestsrc` if they don't have a camera available
* [ ] Using `audiotestsrc` if they don't have a camera available

**Comment by disa6302** [comment]
Closing this for now. Moving the issue elsewhere
