### ISSUE TITLE
WebRTC test page as master on new Chrome browser issue:  InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection'

### ISSUE THREAD

**Issue by ajjiang48** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#403]
I recently get Chrome browser upgraded to version 81.0.4044.129, and run WebRTC test page as master and our device running WebRTC C SDK codes as viewer (tested OK many times with older chrome with the same test), and get the below message on the WebRTC test page log:
+++++++++++++++++
[2020-04-27T08:47:58.294Z] [INFO] [MASTER] Starting master connection
[2020-04-27T08:47:58.677Z] [INFO] [MASTER] Connected to signaling service
[2020-04-27T08:48:17.022Z] [INFO] [MASTER] Received SDP offer from client: WebRTCViewer
[2020-04-27T08:48:17.034Z] [ERROR] InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to apply the description for 0: Invalid ICE parameters: ICE pwd must contain only alphanumeric characters, '+', and '/'.
[2020-04-27T08:48:17.456Z] [INFO] [MASTER] Received ICE candidate from client: WebRTCViewer
[2020-04-27T08:48:17.463Z] [INFO] [MASTER] Received ICE candidate from client: WebRTCViewer
[2020-04-27T08:48:17.620Z] [INFO] [MASTER] Received ICE candidate from client: WebRTCViewer
[2020-04-27T08:48:17.974Z] [INFO] [MASTER] Received ICE candidate from client: WebRTCViewer
[2020-04-27T08:48:59.264Z] [INFO] [MASTER] Stopping master connection
++++++++++++++++++
however, I t changed the browser to Firefox (v75.0) and do the same test and no such error occurred.
Please help check if it's the compatibility issue between new Chrome browser and the WebRTC C SDK.

**Comment by Sean-Der** [comment]
Hey

Can you update to [1.0.0](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/releases/tag/v1.0.0) 

The exact fix you need is 389703f1f46ce71ab0a77bf9a061feb4a44e9636

thanks!

**Comment by ajjiang48** [comment]
Thank you for the info; downloaded the 1.0.0 and do the cmake but I got the below error ! the configuration is incomplete. can you help check what's the problem? 
ps: had exported CC and CXX before the following cmake command (I used arm-ca53-linux-gnueabihf-gcc and arm-ca53-linux-gnueabihf-g++)

++++++++++++++++++++++
ajjiang@via-embedded-swb:~$ cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-unknown-linux-uclibcgnueabi
-- Kinesis Video PIC path is /home/ajjiang/WebRTC/amazon-kinesis-video-streams-webrtc-sdk-c-1.0.0/open-source/amazon-kinesis-video-streams-pic/
-- Kinesis Video C Producer path is /home/ajjiang/WebRTC/amazon-kinesis-video-streams-webrtc-sdk-c-1.0.0/open-source/amazon-kinesis-video-streams-producer-c/
-- Kinesis Video WebRTC Client path is /home/ajjiang/WebRTC/amazon-kinesis-video-streams-webrtc-sdk-c-1.0.0
-- dependencies install path is /home/ajjiang/WebRTC/amazon-kinesis-video-streams-webrtc-sdk-c-1.0.0/open-source
-- Begin building dependencies.
-- openssl already built
-- websockets already built
-- srtp already built
-- usrsctp already built
-- jsmn already built
-- Finished building dependencies.
-- Checking for module 'gstreamer-1.0'
--   No package 'gstreamer-1.0' found
gstreamer not found. Will not build gstreamer samples
CMake Error at CMakeLists.txt:236 (add_subdirectory):
  The source directory

    /home/ajjiang/WebRTC/amazon-kinesis-video-streams-webrtc-sdk-c-1.0.0/open-source/amazon-kinesis-video-streams-producer-c

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
+++++++++++++++++++++++

**Comment by disa6302** [comment]
Can you run git submodule update --init outside build directory and then run cmake again?

**Comment by ajjiang48** [comment]
@disa6302 I do run the command before cmake as below, 
+++++++++++++++++++++
ajjiang@via-embedded-swb:~/WebRTC/amazon-kinesis-video-streams-webrtc-sdk-c-1.0.0$ git submodule update --init
ajjiang@via-embedded-swb:~/WebRTC/amazon-kinesis-video-streams-webrtc-sdk-c-1.0.0$
++++++++++++++++++++++
however, the same error above still happens after running cmake as below:

++++++++++++++++++++++
CMake Error at CMakeLists.txt:236 (add_subdirectory):
  The source directory

    /home/ajjiang/WebRTC/amazon-kinesis-video-streams-webrtc-sdk-c-1.0.0/open-source/amazon-kinesis-video-streams-producer-c

  does not contain a CMakeLists.txt file.
+++++++++++++++++++++++++++++

**Comment by disa6302** [comment]
Can you clean the build directory contents and try again? Sometimes, CMakeCache.txt overrides your variables. 

Also, check if the directory `open-source/amazon-kinesis-video-streams-producer-c` has the CMakeLists.txt file.

**Comment by disa6302** [comment]
@ajjiang48 , 

Any updates?

**Comment by ajjiang48** [comment]
@disa6302 I do clean the build directory and do cmake again, the same error still occurred, and the open-source/amazon-kinesis-video-streams-producer-c/ directory is empty (no CMakeLists.txt file there).
btw, I do "git clone --recursive https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c.git" and do the cmake and make; the problem disappeared and all the libraries are built but the last-step webrtc sample binaries build has problem below (screen-shot the console screen):

![image](https://user-images.githubusercontent.com/62043901/80943499-f1c88b80-8e19-11ea-85c9-194e09fc43c8.png)

**Comment by disa6302** [comment]
@ajjiang48 ,  

Considering you are running it on ARM platform (assumption made based on your logs, correct me if I am wrong), you will have to cross compile to use ARM specific library versions. There is an example to cross compile for ARM platform in .travis.yml file that you can follow.

**Comment by ajjiang48** [comment]
@disa6302 yes, I've read travis.yml before and exported CC and CXX before doing cmake and make (actually, I've ARM cross compile successful build in the old C SDK version); don't know why those issues happen building the newer version C SDK.

**Comment by zhiyua-git** [comment]
Hi @ajjiang48 ,

CMake would not clean up the dependency builds, can you remove the directories except "amazon-kinesis-video-streams-pic" and "amazon-kinesis-video-streams-producer-c" under "open-source" directory and call cmake and make again? Thanks.

**Comment by ajjiang48** [comment]
HI, @zhiyua-git,
I removed the "local" under the "open-source" directory and do the cmake (cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-unknown-linux-uclibcgnueabi), it re-builds those open-source libraries but stops with the same issue; I attached the CMakeError.og and CMakeOutput.log for your reference. Thanks.
[CMakeError.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4578622/CMakeError.log)
[CMakeOutput.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4578623/CMakeOutput.log)

**Comment by MushMal** [comment]
Sorry for the troubles. Seems that the reported problem is not the same as the original issue. I recommend closing this one and opening a new one to track the build issues.

Looking at the CMake output it seems that your toolchain has an issue compiling:

CheckSymbolExists.c:(.text+0x1c): undefined reference to `pthread_create'

There could be a number of problems causing this.

* remove build and open-source directories from your enligtment
* do `git clean -dfx`
* do `git pull`
* do `git submodule update`
* check the version of your cmake - update to the latest

Rebuild/

**Comment by ajjiang48** [comment]
@MushMal hi, I git clone the up-to-date amazon-kinesis-video-streams-webrtc-sdk-c.git (the tag is 1.0.0) and do the CMake with the same parameters, there's no error; however, when I make the sample viewer executables; it pops the function reference problem, but I fixed it my own; and I've tested the viewer sample works with the new chrome browser. this issue could be closed; thanks.

**Comment by Sean-Der** [comment]
@ajjiang48 fantastic! Thanks for using KVS :)
