### ISSUE TITLE
Using my own byte buffer (uint8_t*) instead of local files

### ISSUE THREAD

**Issue by CatsNipYummy** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#404]
I am using the Kinesis WebRTC to stream my own byte buffer video frames instead of local files. I have an h264 encoded byte buffer. As a note, the encoding works fine, cause I was able to save this byte buffer to a local file and could stream that file out using the default example shown here https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c.

But when I try to pass the byte buffer to the frame datatype, I get the following error:

    writeFrame() failed with 0x5c000003
    ERROR   getNextNaluLength(): operation returned status code: 0x5c000003

What I'm doing is as follows:

            std::pair<uint8_t*, size_t> tempVal = _h264EncoderDataQueue.front();
            frame.frameData = (PBYTE) tempVal.first;
            frame.size = tempVal.second;
            _h264EncoderDataQueue.pop();

The queue contains the byte array and the size of the byte array. I pass the byte array and the size to frame.frameData and frame.size. 

But the status I get from the below method is the error I mentioned above:
status = writeFrame(pKinesisConfiguration->kinesisStreamingSessionList[i]->pVideoRtcRtpTransceiver, &frame);

I was wondering if the PBYTE cast is working fine. I can see the size is set correctly and its the same size when I try to stream the locally saved h264 file I mentioned before.

**Comment by MushMal** [comment]
The cast should work OK. Who owns the frame buffer itself? Is this collected/ovwerwrittent before you get a chance to push this into the transeiver?

There is no enough information to go with. I would recommend you to dump out the values - you can print the values as they are popped. Run it under the debugger to ensure the size and the frame buffer point to the correct entities.

**Comment by CatsNipYummy** [comment]
@MushMal I'm going to close this issue for now. I see some issues with my code.
