### ISSUE TITLE
[Question] How long do selected candidate pairs persist throughout the session?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#406]
When do candidates get recycled/reused? There might be a case some candidates suddenly got a new IP,  what do the standards specify?

**Comment by chehefen** [comment]
Right now when a candidate pair is selected, it will remain selected throughout the lifetime of current ice session. We havent yet implemented ice renegotiation but we are working on it.

**Comment by chehefen** [comment]
can you elaborate in what cases would a candidate suddenly get a new IP?

**Comment by suggestedfixes** [comment]
Closing because question answered.
