### ISSUE TITLE
Add a FAQ section to provide a way to get a function that allocates memory the most

### ISSUE THREAD

**Issue by lherman-cs** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#408]
I think we should add a FAQ section in our README to include a simple way to know what function that allocates memory the most. Adding this section can help some users to discover memory leaks or, at least, some pointers to memory leaks. 

For example, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/383 issue can have much better context if we can get following information:

<img width="691" alt="Screen Shot 2020-04-24 at 6 48 08 PM" src="https://user-images.githubusercontent.com/15654932/80730085-23b6b680-8ad7-11ea-9d14-c2a4468b9ca9.png">

*The screenshot shows that createRtpPacketFromBytes called malloc the most*

**Comment by disa6302** [comment]
Closing this since we are tracking documentation related work items in #737
