### ISSUE TITLE
Reduce memory allocations in sending media data

### ISSUE THREAD

**Issue by lherman-cs** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#409]
As of now, we make a lot of allocations when we're sending either video or audio packets. I think we should try to preallocate some of the memory and reuse them.

Following is a statistic of how many times `defaultMemAlloc` got called in the master example.

Note: the statistic is taken using lldb with this helper script, https://github.com/lherman-cs/dev/blob/master/helpers/lldb_helper.py#L50-L120.

<img width="441" alt="Screen Shot 2020-04-30 at 12 49 24 PM" src="https://user-images.githubusercontent.com/15654932/80739618-c32e7600-8ae4-11ea-8402-8981375f6188.png">

**Comment by disa6302** [comment]
This feature is being tracked by the team internally.
