### ISSUE TITLE
socketConnectionReadData(): SSL_read failed with error:00000006:lib(0)

### ISSUE THREAD

**Issue by Fak3Tales** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#410]
Using the most recent version of master and running `./kvsWebrtcClientMasterGstSample video-only testsrc`.

After around a minute this error is produced in the log then the session is free'd up and the stream ends

The full error for ref is `socketConnectionReadData(): SSL_read failed with error:00000006:lib(0):func(0):EVP lib. Length of data already written 0`

Going back through the commits this seems to have been introduced with this commit b13d84c

I have reproduced this on MacOS and my Ubuntu 18.04 Server.

**Comment by disa6302** [comment]
@Fak3Tales ,

1. Can you send all the logs? 
2. What version of OpenSSL are you using?

**Comment by Fak3Tales** [comment]
@disa6302 

I am using OpenSSL 1.1.1g

Here is the log file:
[MacOS.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4561344/MacOS.txt)

If i checkout 8a5f22c everything seems to work a little better.

**Comment by chehefen** [comment]
you can avoid this issue right now by pulling in this commit https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/b826a9b2d84062bc3ce273dd9f8fddfbfc9b84af. It configures TURN to use udp by default.

**Comment by disa6302** [comment]
@Fak3Tales , 

Did the commit resolve your issue?

**Comment by Fak3Tales** [comment]
@disa6302 

Yup that commit seems to have resolved the issue. 

Cheers
