### ISSUE TITLE
Send kinesis_video_msgs::KinesisVideoFrame message through webtrc

### ISSUE THREAD

**Issue by huyhoangk50** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#423]
I want to write an example that subscribes in ROS that subscribe a sensor_msgs/Image topic then sending it through webrtc instead of reading from local files like the example in kvsWebRTCClientMaster.c. How can I do that? I tried to encode the topic to  a kinesis_video_msgs::KinesisVideoFrame topic, using https://github.com/aws-robotics/kinesisvideo-encoder-ros1 repo, then sending the encoded frames, but it did not work.

**Comment by disa6302** [comment]
@huyhoangk50 , 

It is not clear what does not work. Can you be more specific as to what part is not working? Can you also send some logs? Thanks!

**Comment by MushMal** [comment]
@huyhoangk50 to add to @disa6302 response.

At the low-level WebRTC has an intrinsic knowledge of the underlying stream format. It will be a lot of tinkering to get this working with your own frame format.

In the meanwhile, perhaps you could describe your end-to-end scenario better? Perhaps KVS Producer SDK with KVS Streams might be a better fit for a custom frame format.

**Comment by huyhoangk50** [comment]
I have solved the problem. the code is
```
// kvs_image is assigned by subscribing a kinesis_video_msgs::KinesisVideoFrameConstPtr topic
frameSize = kvs_image.frame_data.size()+kvs_image.codec_private_data.size();
    // Re-alloc if needed
    if (frameSize > pSampleConfiguration->videoBufferSize) {
      pSampleConfiguration->pVideoFrameBuffer = (PBYTE) realloc(pSampleConfiguration->pVideoFrameBuffer, frameSize);
      if(pSampleConfiguration->pVideoFrameBuffer == NULL)
      {
        printf("[KVS Master] Video frame Buffer reallocation failed...%s (code %d)\n", strerror(errno), errno);
        printf("[KVS Master] realloc(): operation returned status code: 0x%08x \n", STATUS_NOT_ENOUGH_MEMORY);
        goto CleanUp;
      }

      pSampleConfiguration->videoBufferSize = frameSize;
    }

    frame.frameData = pSampleConfiguration->pVideoFrameBuffer;
    vector<uint8_t> h264_data = kvs_image.codec_private_data;
    h264_data.insert(h264_data.end(),kvs_image.frame_data.begin(),kvs_image.frame_data.end());
    frame.frameData = reinterpret_cast<PBYTE>((void *)(h264_data.data()));
//    BYTE D = BYTE(10);
//    frame.frameData = &D;
    frame.size = frameSize;
    frame.flags = (FRAME_FLAGS)kvs_image.flags;
    frame.index = kvs_image.index;

//    retStatus = readFrameFromDisk(frame.frameData, &frameSize, filePath);
    if(retStatus != STATUS_SUCCESS) {
      printf("[KVS Master] readFrameFromDisk(): operation returned status code: 0x%08x \n", retStatus);
      goto CleanUp;
    }

//    frame.presentationTs += SAMPLE_VIDEO_FRAME_DURATION;
    frame.duration = kvs_image.duration;
    frame.decodingTs = kvs_image.decoding_ts;
    frame.presentationTs = kvs_image.presentation_ts;

    if (!ATOMIC_LOAD_BOOL(&pSampleConfiguration->updatingSampleStreamingSessionList)) {
      ATOMIC_INCREMENT(&pSampleConfiguration->streamingSessionListReadingThreadCount);
      for (i = 0; i < pSampleConfiguration->streamingSessionCount; ++i) {
        status = writeFrame(pSampleConfiguration->sampleStreamingSessionList[i]->pVideoRtcRtpTransceiver, &frame);
        if (status != STATUS_SUCCESS) {
#ifdef VERBOSE
          printf("writeFrame() failed with 0x%08x", status);
#endif
        }
      }
      ATOMIC_DECREMENT(&pSampleConfiguration->streamingSessionListReadingThreadCount);
    }
    THREAD_SLEEP(SAMPLE_VIDEO_FRAME_DURATION);
  }
```

**Comment by mhaboali** [comment]
Hi @huyhoangk50 

I'm trying to replicate exactly what you've done, but I"m not able to run the roscpp code with this C-sdk. Could you explain more how did you manage to do it? And if it's possible to share that chunk of code that streams the ROS images to the signaling channel, it'll be highly appreciated!

**Comment by atyshka** [comment]
@huyhoangk50 @mhaboali Do either of you have working code available for a ROS integration? I have been able to integrate the library build and linkage into catkin, but I am running into difficulties integrating this into a ros node with regard to threading.

**Comment by yt** [comment]
[huyhoangk50](https://github.com/huyhoangk50) Thank you for the code snippet. I have created the ROS integration of the sdk here: https://github.com/yt/kinesiswebrtc-ros1

**Comment by setareh-soltanieh** [comment]
Hi @huyhoangk50, I also want to publish my camera frames to sensor_msgs/Image and for this task I have first created a ros package from this project and then defined a new cpp file which is completely the same az kvsWebrtcClientViewer.c and I have made this new cpp file into a node. I have the following function which handles every incoming camera frames. 
`VOID myFrameHandler(UINT64 customData, PFrame pFrame)
{
    Frame frame = *pFrame;
    unsigned char* actualFrameData = frame.frameData;
    
    printf("frame size is: %u\n", pFrame->size);
    printf("frame data is: %u\n", frame.frameData);

    for (int i = 0; i < 10; ++i) {
        printf("%d\n", actualFrameData[i]);
    }
}`

What I dont understand is how do you actually convert this pFrame data into sensor_msgs/Image? and also one interesting thing for me is that the pFrame->size is different each time, have you done anything for this?
