### ISSUE TITLE
"signaling reconnection failed" error causes webrtc not functioning until restarted

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#424]
We have seen that Webrtc has to be restarted to accept signaling channel messages, after webrtc has been running for dozens of minute.

I have seen one instance that webrtc reported STATUS_SIGNALING_RECONNECT_FAILED.
While signaling channel was in idle mode, suddenly, libwebsocket sent this event
2020-05-04 14:48:55 DEBUG   lwsWssCallbackRoutine(): Client WSS closed

Then webrtc started to re-connect to signaling channel, but later on failed.  The failure made signaling channel not function any more.

We will add code to restart webrtc to deal with this error case.  However, we still like to find out why the error happens, so we can fix it at the root cause, reducing the need to restart webrtc

We call createLwsIotCredentialProvider for credentialing.  Could it affect signaling re-connection?
webrtc log attached below

[fail-to-connect.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4578990/fail-to-connect.txt)

**Comment by MushMal** [comment]
@zwei333 just to give some background... The signaling client has a public API to connect (and disconnect). This will try to connect and re-try within the allotted time or fail with a timeout as this is a synchronous API. However, once the client is in a "connected" state, it has a monitor that will attempt to re-connect in case of a failure. In this case, it happens in the background and when it fails after it has retried multiple times (TIMEOUT) it will printout this error. The code will also notify the application via the error callback. The application then can handle this case based on the application needs. For example, one of the ways to handle it might be to disconnect and re-connect again. Alternatively, you can teardown the signaling client and re-create it.

**Comment by MushMal** [comment]
Please resolve this issue if you don't have re-connect or error specific questions. Please open a separate issue tracking the networking/re-connect failure - I believe you already opened a separate one here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/427

**Comment by zwei333** [comment]
This issue is quite different from #427.
First, when it happens, kvs prints 
2020-05-04 14:48:55 DEBUG   lwsWssCallbackRoutine(): Client WSS closed
That is not seen in #427 
Second, #427 can easily reconnect, but in this issue reconnection fails
Third, when trying reconnect, #427 goes to state
0x0000000000000100, Next state: 0x0000000000000020
@@@@@ Signaling Client State changed to 6 - Get ICE Server Configuration
but this issue goes to state 
0x0000000000000100, Next state: 0x0000000000000002
@@@@@ Signaling Client State changed to 2 - Get Security Credentials

**Comment by MushMal** [comment]
@zwei333 the state machinery deduces which state to move to based on the error received and some other input. Perhaps you are correct that this is slightly different but looking at your cases those point to bad networking as a root cause which manifest in different ways.

We won't be able to debug your networking so as I suggested, try to run the debug logs with debug libWebSockets to get more insight into what might be wrong with your network.

Just a little further info. The signaling client (after it establishes the connection successfully) attempts to keep the connection alive by ping-ponging. It also monitors the connection and if after certain period it doesn't receive the pongs it deems the connection as dead. Also, the libWebSocket client can return a connection closed based on low-level socket.

**Comment by sharadrj** [comment]
@zwei333, 

As @MushMal said, SDK tries several times to reconnect and if it fails it throws the error. Please get more debug logs in LWS. Instructions for that are here:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/427#issuecomment-624283824

Also, code for recreating the signaling client is here: 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L790-L799

Error detection:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L103-L115

**Comment by MushMal** [comment]
I am going to resolve this issue. Please re-open or cut a new issue if need help

**Comment by zwei333** [comment]
Once "Client WSS closed", SDK automatically starts re-connection.  It is good.
However, please see the following lines, which are copied from the attached log file.
At iceServerConfiguration request, everything looked normal and wifi wa good, but suddenly, STATUS_SIGNALING_RECONNECT_FAILED error was reported.  I like to confirm re-connection logic is correct and the STATUS_SIGNALING_RECONNECT_FAILED was not caused by a SDK bug.

@MushMal  can you reopen this issue.  I can't reopen it because you closed it.

*******************************************************
@@@@@ Signaling Client State changed to 6 - Get ICE Server Configuration
2020-05-04 14:49:13 DEBUG   lwsHttpCallbackRoutine(): Client append handshake header

2020-05-04 14:49:13 DEBUG   lwsHttpCallbackRoutine(): Sending the body {
        "ChannelARN": "arn:aws:kinesisvideo:us-east-1:015020446588:channel/42498ccf651e5f0d5050e20fc0017e5f_3460014/1585854252452",
        "ClientId": "ProducerMaster",
        "Service": "TURN"
}, size 178
2020-05-04 14:49:13 DEBUG   lwsHttpCallbackRoutine(): Connected with server response: 200
2020-05-04 14:49:13 DEBUG   lwsHttpCallbackRoutine(): Received client http
2020-05-04 14:49:13 DEBUG   lwsHttpCallbackRoutine(): Received client http read: 573 bytes
2020-05-04 14:49:13 DEBUG   lwsHttpCallbackRoutine(): Http client completed
2020-05-04 14:49:13 DEBUG   lwsHttpCallbackRoutine(): Client http closed
@@@@@ Signaling Client generated an error 0x5d000030

**Comment by MushMal** [comment]
@zwei333 could you please cut a new issue and include the detailed description of what you are seeing. From the latest, it seems that you are getting 0x5d000030 which is indeed a reconnect failure but the log snippet doesn't show what's going on and why we are refreshing ice server config every 5 seconds.

Please include the debug logs. Also, if this is on the device, it might help to also include spew from debug version of LWS which you might need to rebuild by deleting the libWebSockets.so library from the open-source/lib directory, modify the libWebSockets cmake file in CMake to uncomment the debug build line and rebuild

**Comment by zwei333** [comment]
This issue is about re-connection failure.  Refreshing ice server config every 5 seconds is a different issue.
The issue I worry about is why the re-connection fails.  If it fails because network / lws is still bad, then it is OK.  But if it fails because SDK bug, then we should fix it.  The re-connection is a very nice SDK feature.
The log is pretty hard to get.  I could wait for days to get a WS close event.
So far, I have seen four instances.
Two of them had more network malfunctions, so lwsHttp Connection failed.  This is fine.
Two of them had working lwsHttp connection, and the connection was closed normally. Then STATUS_SIGNALING_RECONNECT_FAILED was reported.  These two I like to investigate more.
I have LWS debug enabled, but only captured one log.  Unfortunately it is the one with persistent network malfunction, not the one I am interested in.
I will continue to monitor the camera until I get a failure log with LWS debug

**Comment by MushMal** [comment]
I understand. It is indeed hard to capture. We do try to simulate various failure modes in the unit tests by fault injecting. Perhaps you could take a look at the fault injection logic. It’s designed to simulate various real failures and helped us to catch some edge cases that are hard to “guess” bales on the SDK reliance on libWrbSocket library, which in turn relies on the platform specific sockets to work with the backend.
