### ISSUE TITLE
Our mobile app has trouble streaming in the first attempt. They usually don't get ice candidates the first time but retry works well

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#425]
We have seen that “Both Android and web applications have trouble streaming in the first attempt. They usually don't get ice candidates the first time but if they retry connecting again then things seem to work. “

I found out when mobile app has ice candidate issue, after this turn state change,
2020-05-04 15:16:02 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_GET_CREDENTIALS to TURN_STATE_ALLOCATION

webrtc run into this error:

2020-05-04 15:16:07 ERROR   turnConnectionStepState(): operation returned status code: 0x5a000020
2020-05-04 15:16:07 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_ALLOCATION to TURN_STATE_FAILED
2020-05-04 15:16:07 ERROR   turnConnectionTimerCallback(): operation returned status code: 0x5a000020
2020-05-04 15:16:07 ERROR   timerQueueExecutor(): operation returned status code: 0x5a000020
2020-05-04 15:16:07 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x5a000020
2020-05-04 15:16:07 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_FAILED to TURN_STATE_CLEAN_UP
2020-05-04 15:16:10 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000002, Next state: 0x0000000000000040
2020-05-04 15:16:10 ERROR   executeFailedIceAgentState(): IceAgent failed with 0x5a00000d
2020-05-04 15:16:10 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_FAILED.

The error will cause the master (camera) side to close the peer connection.  Therefore mobile/web app can’t get the ice candidate to stream at the first attempt.  Retrying connection will make streaming run.

We call createLwsIotCredentialProvider for credentialing.  Not sure if it is related to this bug.
log attached.
[ice-issue.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4579015/ice-issue.txt)

**Comment by chehefen** [comment]
Looking at the log it seems that turn allocation failed during the first attempt and when it succeeds turn is used. Can you tell us which commit you are at? We made quite a few optimizations to turn allocation recently and I would recommend to try the latest master.

**Comment by zwei333** [comment]
When I reported the issue, we used 4/17 version of KVS SDK.  Currently we are using 5/4 verion of SDK.  Does 4/17 version include TURN fixes?  Which version we should use to test the new TURN fixes?

**Comment by chehefen** [comment]
the 5/4 version has TURN fixes.

**Comment by zwei333** [comment]
The problem is still there with release 1.1.0.
It only happens when TURN is needed.  When direct connection is available, every connection attempt is successful

**Comment by zwei333** [comment]
We are using master branch as of 5/22/20.  The issue is still unfixed.
Now I can reproduce the issue reliably.
It only happens when we use IoT credentialing;
When webrtc starts and signaling channel is first time connected, if app sends an offer,camera will response with two ice candidates,  p2p and TURN.  
And subsequent peer connection attempts will have the same result, UNTIL:
signaling channel connection is renewed.  signaling channel connection is renewed roughly every five minutes.  After the renewal, if app sends an offer, camera will only response with ONE ice candidate, p2p only, no TURN.  So app can't connect to camera when p2p is not possible.
Then subsequent peer connection attempts will generate two ice candidates, p2p and TURN, and app can connect to camera, UNTIL:
signaling channel connection is renewed again. 

It can be repeated almost every time.

**Comment by MushMal** [comment]
There are few oddities with what you are reporting. I am just not sure how IoT would have any affect on this at all and also what exactly do you mean by renewing signaling every 5 minutes? Are you referring to the pong? Are you seeing ice server config refresh? Or, indeed your connection does get dropped for some reason? 

Could you attach debug logs to understand what’s going on?

**Comment by zwei333** [comment]
Please see the attached log file.  Notes:
1) it is mixed with SDK log and our application log.  They have different log format and our time stamp is 8 hours ahead of SDK log's timestamp
2) I put comments to help read the log.  Please search for marker "#######"
[first-attempt-fail.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4690776/first-attempt-fail.log)

**Comment by zwei333** [comment]
While being odd, the IoT and key/secret do have different behaviour. In IoT case, 1 TURN (good) or 0 TURN (bad) can be found; in key/secret, 2 TURNs or 1 TURN can be found

**Comment by lherman-cs** [comment]
@zwei333 from your logs, there seems to be no issue. 

Regarding why you saw 1 p2p is because the ice gathering received the p2p candidate earlier than it finished allocating turn. You can observe this from a screenshot of your logs below. It shows that `Ice agent state changed from ICE_AGENT_STATE_NOMINATING to ICE_AGENT_STATE_READY` then later `TURN Allocation succeeded. Life time: 600 seconds. Allocation expiration epoch 159060110081967`.

<img width="1391" alt="Screen Shot 2020-05-28 at 1 35 30 PM" src="https://user-images.githubusercontent.com/15654932/83174293-2e6d6700-a0e8-11ea-9720-84d35755cf4f.png">
 
If you'd like to see all of the candidates, you can turn off trickle ice. But, it's generally not recommended since the ice gathering will take a longer time to finish.

Regarding why it only happened when you used IOT credentials, I think this is a red herring since there shouldn't be any correlation with the issue.

**Comment by zwei333** [comment]
The 1 p2p candidate is not concerned here.
We see one TURN candidate for offer before refreshIceConfiguration and zero TURN candidate for offer after refreshIceConfiguration.
Zero TURN candidate means when p2p is not possbile, app can't connect to camera.  But if app retries, then next offer will get back one TURN candidate.
This issue is consistently reproducible.

**Comment by lherman-cs** [comment]
I'm sorry for my bad wording. What I really meant was about no turn candidate. When ice agent state became ready, what it means is that 1 candidate pair has been nominated and is being used (in this case, p2p is being used). So, at this point, unused turn allocations will be freed up, and the turn candidate WILL NOT be reported since it's still trying to allocate.

Maybe, could you try to turn off trickle ice? It should show all of the candidates.

**Comment by zwei333** [comment]
I used my system to capture the log.  In my system, webrtc was doing p2p.  But other system was using TURN.  
Initially the issue was found by system with TURN.  The ice candidates discovery was exactly the same as the attached log: 1 TURN for connection request before refreshIceConfiguration, 0 TURN for connection request after refreshIceConfiguration, and retry of connection request got 1 TURN.
When there was 0 TURN, app waited for connection, no streaming.
The issue is not random, but has a clear pattern.

**Comment by chehefen** [comment]
Hi @zwei333, I tried to reproduce your issue by switching to iot credential provider, use TURN only NAT mode in js sample, then view sdk master after each signaling refresh. The connection was always successful. Can you check if you can reproduce the issue by running our sample?

**Comment by zwei333** [comment]
It is more complicated than I originally thought.
The result depends on the app layer code.  If I add even one line of code at a certain spot, the TURN discovery will be different.  In good case, 1 TURN Ice is found and in bad case, 0. 
Some compiling/building issue seems affecting the SDK's performance.  In the case of 1 / 0 TURN ice discovered, with the same binary executable, the result will be consistent, always 1 / 0 TURN ice.
The critical spot is completely unrelated to SDK and TURN discovery.
Why in some case zero TURN ice is found?  How could app layer simple code change, (such as adding/removing a std::cout or a return;) could change TURN discovery result?
puzzled.

**Comment by chehefen** [comment]
@zwei333, can you capture the packets for both the good and bad cases and send us the pcap file? thanks.

**Comment by MushMal** [comment]
I am going to resolve this due to staleness. Please cut a new issue and include the details on the issue you are having

**Comment by zwei333** [comment]
Have found the root cause of this issue
kvs sdk expects us to create peerConnection after offer is received. We create peerConnection ahead of time to optimize the connection wait time. This causes the issue.
Every five minutes, kvs sdk refreshes IceServerConfig to get the most recent IceServer urls and turn server credentials. Because we create peerConnection before the IceServerConfig refreshing, and the IceServerConfig can't be changed once peerConnection is created, we lock in old IceServer urls + turn credentials. Using the old urls + turn credentials causes TURN ice candidate searching failure.
If TURN connection is not a must, then the streaming can still start.
If TURN connection is required, the streaming will fail at the first attempt. When trying the second time, a new peerConnection is created, with the most recent urls + turn credentials. Then the streaming will be OK

**Comment by MushMal** [comment]
Indeed, creating a peer connection has two heavy parts - the DTLS initialization (creating self-signed certs) that can evaluate to heavy processing on some platforms and the ICE negotiation. Unfortunately, you can't front-load the ICE negotiation due to the network staleness and ICE configuration. You could, however, offload the cert generation and supply the pre-generated certs.
