### ISSUE TITLE
refreshIceConfiguration too frequent, every a couple seconds

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#427]
Have been running webrtc for about 20 hours.  For most time, the signaling channel is idle, waiting for messages. 
Normally the signaling channel reconnects about every 4.5 mins.  But sometime the reconnection is too frequent, every 2 to 5 seconds.
Log attached.
[frequent-reconnection.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4581509/frequent-reconnection.txt)

**Comment by MushMal** [comment]
@zwei333 the log you've attached indicates that the connection gets dropped frequently and the state machinery re-tries constantly. It's not possible to tell why the connection gets dropped.

Could you try to run the debug LWS by uncommenting this line: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/CMake/Dependencies/libwebsockets-CMakeLists.txt#L37

and set debug logs for the client and include the full logs so we can understand what's causing the connection dropping.

**Comment by sharadrj** [comment]
Closing as stale. 

@zwei333 , please reopen if you still see this issue.

**Comment by zwei333** [comment]
At a closer look, I found that in this issue, Signaling Client reconnection didn't happen.
Only refreshIceConfiguration repeated frequently (1~5 seconds after signaling client state changed to "Connected")
During the time, network was doing well.  Every refreshIceConfiguration request succeeded. 
It seems some logic inside kvs SDK that frequently called refreshIceConfigurationCallback().
It is a different issue from #424 
I changed the issue name to reflect the above finding.

@sharadrj Can you reopen the issue?  Because it was closed by you, I can't reopen it.

**Comment by sharadrj** [comment]
@zwei333, Sorry missed your last comment earlier.

**Comment by MushMal** [comment]
Seems this has gone stale. @zwei333 can you please provide the latest information on this issue with debug logs?

**Comment by zwei333** [comment]
Haven't seen the problem again

**Comment by disa6302** [comment]
Closing this. @zwei333 , feel free to open a new issue if you face any issues.
