### ISSUE TITLE
CI test stability issues

### ISSUE THREAD

**Issue by MushMal** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#428]
Currently, we have some stability issues with peer connection functionality tests and the signaling client functionality tests. These are complex integration tests with fault injection and timeouts. The timing, however loose, still becomes an issue when running in Travis CI. These tests pass in clean on local machines.

All of the PRs are going through clean runs before they can be merged to master branch.

The master branch runs the builds and sets the GitHub badge which if the run fails, it marks as broken which is a mistake.

We need to think through how we can add more stability to the tests and also think about re-trying the failed tests a couple of times perhaps to ensure clean runs.

**Comment by lherman-cs** [comment]
The CI stability has been improved by https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/485. Although, test flakiness is still there, but it's minor. We should create another issue when a new issue related to this occurs.

Before:
<img width="1023" alt="Screen Shot 2020-06-01 at 12 43 59 PM" src="https://user-images.githubusercontent.com/15654932/83431769-de531500-a405-11ea-8b6b-fa9865173a65.png">

After:
<img width="1069" alt="Screen Shot 2020-06-01 at 12 43 43 PM" src="https://user-images.githubusercontent.com/15654932/83431788-e4e18c80-a405-11ea-9cd1-90e70195ca3a.png">
