### ISSUE TITLE
[Enhancement] Make video thread more independent from peer connections

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#446]
We are dealing with extremely unreliable video libraries, so we are experimenting with restarting the video pipeline. One way to do emulate the death of a thread is to send a "killvideo" message to a data channel, and join the video thread. What is interesting is that, our frontend code was able to reconnect initially. But somehow, mysteriously, master is refusing to answer subsequent offers from other peers. As we recall, as we first start the master, the video thread does not start until the first successful handshake, so with the absense of a video thread shouldn't affect peer negotiation process correct?

Here is a code snippet in Common.c to duplicate the problem
```
VOID onDataChannelMessage(UINT64 customData, BOOL isBinary, PBYTE pMessage, UINT32 pMessageLen)                         {

    PSampleStreamingSession pSampleStreamingSession = (PSampleStreamingSession)customData;
    if (isBinary) {
        DLOGI("DataChannel Binary Message");
    } else {
        DLOGI("DataChannel String Message: %.*s\n", pMessageLen, pMessage);
    }
    DLOGD(">>>>>>>>Peer id: %s\n", pSampleStreamingSession->peerId);
    PSampleConfiguration pConfig = pSampleStreamingSession->pSampleConfiguration;
    if (strncmp(pMessage, "killvideo", 9) == 0) {
        DLOGD(">>>>>>>>Thread id is %ud\n", pConfig->videoSenderTid);
        if (IS_VALID_TID_VALUE(pConfig->videoSenderTid)) {
            // Join the threads
            THREAD_JOIN(pConfig->videoSenderTid, NULL);
        }
    }
}
```

**Comment by MushMal** [comment]
@suggestedfixes I believe this one was answered on a separate channel. You can change the offer handling code per your need.

Moreover, the master sample "emulates" a video pipeline by creating a separate thread. Most likely your actual video pipeline has a separate source of liveness (thread) that can "push" frames onto your callback? If not, then you will need the thread like in the master.

Also, make sure that the thread you are joining is not detached. I believe the detached thread can't be joined or something on some platforms.

**Comment by suggestedfixes** [comment]
@MushMal This is a different issue. I think killing the video thread somehow broke IceAgent. So the absence of video frames is coupled to some mechanism I don't understand. And connecting with any other peer id would not work anymore. There are messages being exchanged, but no answer.

**Comment by chehefen** [comment]
Ice isnt coupled to video thread. As shown in this unit test: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/tst/PeerConnectionFunctionalityTest.cpp#L9. There is no video thread and ice connects just fine.

**Comment by suggestedfixes** [comment]
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4623810/log.txt)
This is running the master sample with the mentioned change in Common.c. Then send killvideo to the data channel. I understand by killing the thread, I might have broken something.

**Comment by suggestedfixes** [comment]
I think sessionCleanup might have locked operations that needed sampleConfiguration since mediathread count is most likely one. Testing this.

**Comment by suggestedfixes** [comment]
It turns out as for gstreamer, it is pretty cumbersome to stop the pipeline.

**Comment by suggestedfixes** [comment]
@MushMal @chehefen 
This is still an ongoing experiment with both gstreamer master and file master.

**Comment by MushMal** [comment]
I would suggest closing this issue as it's a generic description. Instead, as you make progress, open a targeted issues

**Comment by suggestedfixes** [comment]
@MushMal 
Let's take file master sample, we need help on try to restart media thread. This means joining and creating the thread.

**Comment by MushMal** [comment]
@suggestedfixes the samples are just that - samples. The thread in the master sample is to simply emulate a media pipeline. Most media pipelines operate on "PUSH" model where a thread in the media pipeline calls a callback to push a frame. You don't need any thread in that case.

In a real commercial application you might need to use the media capabilities and the liveness of the media pipeline at hand which is likely to have it's own thread so you don't need to create a thread to get frames. 

Same is for putting frames into the media pipeline (the consumer side). In this case, you can simply use the thread that you were called with to push the frame into the media pipeline.

**Comment by suggestedfixes** [comment]
In the case of Gstreamer, seems like there is a gstreamer event loop blocking, and we also have a webrtc loop blocking. It seems pretty difficult to merge those two event loops into one event loop without threads.

**Comment by MushMal** [comment]
@suggestedfixes I am not sure what you mean. The samples codebase is minimized so we can have as little code as possible to demo simple interactions. Thus, most of the functionality is concentrated in Common.c which serves both the master samples and the viewer sample.

In order to not duplicate code, we do create a thread when the offer comes in using the function pointer that's specified by the higher-level logic - the actual sample (pSampleConfiguration->videoSource and pSampleConfigudation->audioSource).

In case of the Master sample, the thread that's created is used as a media pipeline thread to actually drive the samples.

In case of the GStreamer Master sample, the thread ONLY sets things up and quits. The GStreamer media thread is the one that pushes samples and calls on_new_sample_video for video samples and on_new_sample_audio for audio samples - we are not actually running our own media thread in this case.

**Comment by MushMal** [comment]
I am going to resolve this issue. Please feel free to cut a new one with more precise details if needed
