### ISSUE TITLE
AWS KVS webrtc could not find webcam issue

### ISSUE THREAD

**Issue by ssalexa** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#449]
Hi,

I want to run a KVS client sample. I followed README file: https://github.com/ssalexa/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/README.md

But I have two questions here:

1. I met this issue when I opened WebRTC SDK Test Page : It shows [2020-05-13T04:46:08.186Z] [ERROR] [MASTER] Could not find webcam

2. I have a Ring camera (Ring stick up cam), but I don't see how to setup camera in README file, how should I setup with KVS?

Error message from WebRTC SDK Test Page:

[2020-05-13T04:46:00.743Z] [INFO] Page loaded
[2020-05-13T04:46:07.833Z] [INFO] [MASTER] Channel ARN:  arn:aws:kinesisvideo:us-west-2:006979377340:channel/myChannel/1589321583991
[2020-05-13T04:46:07.882Z] [INFO] [MASTER] Endpoints:  {
  "WSS": "wss://m-8a150cee.kinesisvideo.us-west-2.amazonaws.com",
  "HTTPS": "https://r-34a7a751.kinesisvideo.us-west-2.amazonaws.com"
}
[2020-05-13T04:46:08.175Z] [INFO] [MASTER] ICE servers:  [
  {
    "urls": "stun:stun.kinesisvideo.us-west-2.amazonaws.com:443"
  },
  {
    "urls": [
      "turn:54-190-105-65.t-4f692171.kinesisvideo.us-west-2.amazonaws.com:443"
    ],
    "username": "********************************************************",
    "credential": "**************************************"
  }
]
[2020-05-13T04:46:08.186Z] [ERROR] [MASTER] Could not find webcam
[2020-05-13T04:46:08.187Z] [INFO] [MASTER] Starting master connection
[2020-05-13T04:46:08.510Z] [INFO] [MASTER] Connected to signaling service
[2020-05-13T04:46:15.408Z] [INFO] [MASTER] Stopping master connection
[2020-05-13T04:46:15.447Z] [INFO] [MASTER] Disconnected from signaling channel

Here is how I setup KVS, I listed all the setup steps here in case I missed anything:

1. cloned code from repo
2. created "build" folder under "amazon-kinesis-video-streams-webrtc-sdk-c"
3. cd build folder and run "cmake .. -DBUILD_STATIC_LIBS=TRUE"
4. run "make" and it works good
5. createD AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
6. set log level = 5 as I need

~/myWorkSpace$ ./kvsWebrtcClientMasterGstSample myChannel
[KVS GStreamer Master] Using trickleICE by default
[KVS GStreamer Master] Created signaling channel myChannel
[KVS Gstreamer Master] Finished initializing GStreamer
[KVS Gstreamer Master] Streaming video only
[KVS GStreamer Master] streaming type video-only[KVS GStreamer Master] KVS WebRTC initialization completed successfully
[KVS GStreamer Master] Signaling client created successfully
[KVS GStreamer Master] Signaling client connection to socket established
[KVS Gstreamer Master] Beginning streaming...check the stream over channel myChannel

**Comment by MushMal** [comment]
The first issue is caused by the browser not detecting the built-in camera as the lid of the laptop is closed. As for the second one, it requires a debug platform that could take a modified firmware.

I am going to resolve this issue - please feel free to re-open if you need more info.
