### ISSUE TITLE
Support a Way to Clear Signaling Channel State

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#454]
We have gotten multiple signaling channels into unrecoverable states during our rigorous testing. The reason that we know we broke them is that, creating a new channel with a new name worked. We also know that deleting a signaling channel does not clear the states completely, because the new channel with the same name will retain most of the channel history.

**Comment by MushMal** [comment]
@suggestedfixes to clarify, you are stating that deleting a channel via console, CLI or using deleteSignalingChannel API succeeds but "some" information leaks through to the new one created with the same name? Can you please provide a little more context on this? This is super important.

* What are the steps you are taking.
* Does the deleteSignalingChannel (if this is the case) return STATUS_SUCCESS?
* What's the state that you've mentioned that leaks to a new channel?

**Comment by suggestedfixes** [comment]
The channel is deleted through clicking a button on the AWS Web Interface. By creating a new signaling channel by clicking buttons, we are able to view the previous signaling channel's history. So some past information is migrated.

**Comment by MushMal** [comment]
Can you please specify what previous history is migrated? Thanks for reporting

**Comment by suggestedfixes** [comment]
The cloudwatch metrics were migrated to the new signaling channel. But what is more relevant should be it might have carried over last signaling's state with the same name.

**Comment by MushMal** [comment]
Let me get back to you regarding the CW metrics. There are no other states really to be carried over for a signaling channel.

**Comment by suggestedfixes** [comment]
I think some limits are carried over to the newly created signaling channel is to prevent API limit abuse. But we can solve that by putting a limit on the number of times creating and deleting signaling channels with the same name.

**Comment by MushMal** [comment]
The TPS or limits are service-wide limits and will be accounted against the account. I think you might see some of the TPS limits for the messages exchanged which might persist but the TPS should be high enough to be "cleared" between delete and new create. We would really appreciate more details if you get a chance.

**Comment by MushMal** [comment]
From my understanding, the CW metrics use the channel name as a dimension - those metrics simply collide as the channel name is the same but the channels themselves are different. There is just no good and easy way to differentiate between the metrics for the old and the new channel by the same name.

**Comment by suggestedfixes** [comment]
When signaling channels have gotten to an unrecoverable state. The master can connect to signaling channel 100% of time. However, no viewer can connect. We have tried to turn off master and deleted the signaling channel for several days and still cannot recover it. We are sure that no viewer was connected to it during this period, because cloudwatch does not have a history of viewers connecting to the channel during this time.

**Comment by suggestedfixes** [comment]
It will be nice to introduce something such as temporarily ban all the viewers.

**Comment by bdhandap** [comment]
> The master can connect to signaling channel 100% of time. However, no viewer can connect.

We are aware of this issue and we are working on a fix.

And like @MushMal explained above, cloudwatch metrics use `SignalingChannelName` as dimension which means even if you delete and re-create the channel, the metrics will co-exist for both instances of same channel.

**Comment by JBerges** [comment]
> I think some limits are carried over to the newly created signaling channel is to prevent API limit abuse. But we can solve that by putting a limit on the number of times creating and deleting signaling channels with the same name.

Limits are applied by account and by combination of account and channel name.

Given that the name is the same, in an scenario where you create, describe, delete, create, describe, delete, two operations of describe will be verified for limits.

In that scenario, [describe and delete will apply a limit of 5TPS](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-limits.html) for that channel while create will apply a limit of 50TPS per account.

**Comment by suggestedfixes** [comment]
@JBerge We have not exceeded the limits and have left the channels inactive for at least 24 hours. Our 5-second interval monitoring of the channel and use of random signaling client ids caused the initial problem. We are in the process of changing our monitoring to use the same client id, and this problem will occur less frequently.

**Comment by suggestedfixes** [comment]
We understand the infrastructure behind each signaling channel. But from a black-box experimentation perspective, it does seem like:
- channel x not usable
- deleting x and recreate x does not fix x
- creating y, given same master viewer pair and other conditions fixed, allows connection
- recreated x does not behave like y

**Comment by suggestedfixes** [comment]
If each channel behaves like an independent unit, then the source of the problem could be (one of the databases of keeping track of metadata channels) / (management components of the infrastructure). In that case, it is a much harder fix.

**Comment by MushMal** [comment]
@suggestedfixes the only issue really is the list of viewers that's connected to the master that's not being purged. This is something that we are actively working on and will be fixed ASAP. This is the only issue you will have with deleting and creating a new channel. CW metrics, however, will still have a channel name as a dimension and metrics from the previous channel with the same name will be reflected.
Unfortunately, we don't have a precise ETA on this fix. I will let @bdhandap to comment on this with more info if he has any and update the issue as soon as the fixes are public.

**Comment by suggestedfixes** [comment]
@MushMal If a master disconnects from signaling channel for a certain period, would it be safe to purge all the viewers? We understand it could get much more complex. But by common sense, the initial design would have avoided too much complexity, correct?

**Comment by JBerges** [comment]
> @JBerges We have not exceeded the limits and have left the channels inactive for at least 24 hours. Our 5-second interval monitoring of the channel and use of random signaling client ids caused the initial problem. We are in the process of changing our monitoring to use the same client id, and this problem will occur less frequently.
> 
> Also, another problem could be that the signaling channel might have overcounted the number of viewers, so there might be stale viewers left unpurged occupying viewer quota.

My answer was related to operations limits (create/describe/delete), but I see now that you are talking about viewers limits, so my comment does not apply to your situation, sorry about that. 

About the viewers limits and not being purged, I will let @bdhandap to comment more on this.

**Comment by bdhandap** [comment]
>  If a master disconnects from signaling channel for a certain period, would it be safe to purge all the viewers? We understand it could get much more complex. 

@suggestedfixes That's not correct. Master and viewers can be independent entities and should not affect each other connection state. Consider this case where the master and viewers are connected to signaling service and viewer sent an offer/ice-candidate but before receiving the offer/ice-candidate master got disconnected due to network issues. When the master comes back online, the pending offer/candidate to master will be delivered and P2P connection can be established. 

If we force the viewers to disconnect whenever the master disconnects then any network issue on the master side will impact the viewer offer/candidates and the viewer needs to reconnect and resend the offers/candidates every single time which is not a good customer experience. 

Currently master and viewer can connect in any order (master first or viewer first) and send offers/answer/candidates. As long as the other end (master/viewer) connects within channel's TTL, pending SDP message will be delivered.

**Comment by bdhandap** [comment]
> Unfortunately, we don't have a precise ETA on this fix. I will let @bdhandap to comment on this with more info if he has any and update the issue as soon as the fixes are public.

ETA for deploying the fix is next week. I will update this thread if something changes.

**Comment by suggestedfixes** [comment]
@bdhandap 
- Thanks for the update! Your explanation makes sense! When a viewer decides to intentionally close the signaling client, does the signaling channel side try to remove the viewer from a list of active clients, or does the signaling channel keeps the record for at least an hour?

**Comment by bdhandap** [comment]
@suggestedfixes The viewer will be removed from the list of active clients as soon as it closes the connection intentionally.

**Comment by suggestedfixes** [comment]
@bdhandap Status on the deployment date?

**Comment by MushMal** [comment]
@suggestedfixes this fix will be in the wave 1 of the deployment. As soon as it lands in IAD region we will update the issue. Shouldn't be long but we simply can't give precise ETAs due to variabilities we need to account for.

**Comment by MushMal** [comment]
Just wanted to give a short update - this is still in progress. Should be in soon :)

**Comment by bdhandap** [comment]
@suggestedfixes Changes are deployed to IAD. Can you try now and let us know?

**Comment by suggestedfixes** [comment]
@bdhandap We have not seen issues yet. I'm curious about the changes?

**Comment by bdhandap** [comment]
Most of the time this issue happens when the websocket connections are not closed properly i.e clients abruptly terminating the underlyingTCP connection without sending close frame. Such stale connections are kicked out after [connection duration limit of 1 hour](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-limits.html#limits-signaling-service).

**Comment by bdhandap** [comment]
Resolving this issue. Feel free to reopen a new one if the issue persists.
