### ISSUE TITLE
example of createLwsIotCredentialProvider

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#455]
Hi, I would like to use iot credentials for signaling channel, may I know how to get the IoT credentials endpoints from the AWS account and how to specify Iot role alias as the following sample code shows?
createLwsIotCredentialProvider(
            "coxxxxxxxx168.credentials.iot.us-west-2.amazonaws.com",  // IoT credentials endpoint
            "/Users/username/Downloads/iot-signaling/certificate.pem",  // path to iot certificate
            "/Users/username/Downloads/iot-signaling/private.pem.key", // path to iot private key
            "/Users/username/Downloads/iot-signaling/cacert.pem", // path to CA cert
            "KinesisVideoSignalingCameraIoTRoleAlias", // IoT role alias
            channelName, // iot thing name, recommended to be same as your channel name
            &pSampleConfiguration->pCredentialProvider));

**Comment by MushMal** [comment]
@staowyze you might want to reference #110

**Comment by MushMal** [comment]
Please re-open if you need more info
