### ISSUE TITLE
Add ICE config when SDP arrives

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#456]
follow up the discussion in #363
```
The only way to config ice servers is to create a peer connection, which is not very convenient, e.g. we want to create peer connection first, then wait for connection requests, however allocate turn servers is a waste if no connection request comes, more efficient way would be we could add turn servers whenever SDP messages arrive.
```
```
@staowyze, the getIceServerConfig is executed when the signaling client is being created and after that refreshed prior its expiration. This is optimized so we can have fast connection when the offer arrives - i.e. the signaling client always has the "fresh" ICE config when being requested.

Is your main concern the bandwidth utilization during the refresh? Is it the initial signaling client creation time? For the latter, we have a mode that does async getIceServerConfig which is the default in samples.
```

**Comment by staowyze** [comment]
Not the bandwidth utilization, I worry about unbalanced load of TURN servers, it would be very hard to determine how many connections a TURN server can handle if most of the connections could be idle (i.e. no real data traffic)

**Comment by MushMal** [comment]
@staowyze the ice config is being refreshed periodically. Normally, there is one or two URLs that are returned each time. Your application can chose any one of those. Note, getIceServerConfig doesn't 'reserve' a turn quota by itself. Your application can call this API many times with no impact (modulo the TPS that the backend imposes).

The proper balancing happens at the backend when the actual TURN allocations start happening
