### ISSUE TITLE
Not streaming audio but no error

### ISSUE THREAD

**Issue by CatsNipYummy** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#460]
I am using libopusenc to create audio chunks and I've saved it to files similar to the sample available. When I stream these files out, I don't get a write error but I don't hear the audio on the receiving end. I tried combining all these opus files into one and it seems to be playing on VLC. Is there a way to find out what's happening? I tried running AWS_KVS_LOG_LEVEL_VERBOSE and I get the following:

`VERBOSE sampleBandwidthEstimationHandler(): received bitrate suggestion: 2582288.000000`

Can you tell me how the opus frames are encoded in the sample? The opusinfo of one of my files looks like this:

```
opusinfo sample-002.opus
Processing file "sample-002.opus"...

New logical stream (#1, serial: 60b7acd9): type opus
Encoded with libopus unknown,  0.2.1-4-g6e0a98c
User comments section follows...
	ARTIST=Someone
	TITLE=Test
Opus stream 1:
	Pre-skip: 312
	Playback gain: 0 dB
	Channels: 1
	Original sample rate: 16000Hz
	Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	Page duration:     40.0ms (max),   40.0ms (avg),   40.0ms (min)
	Total data length: 876 bytes (overhead: 99.3%)
	Playback length: 0m:00.033s
	Average bitrate: 210.4 kb/s, w/o overhead: 1.441 kb/s (hard-CBR)
Logical stream 1 ended
```

The file from the sample (that streams fine) gives me the following:

```
Processing file "/Users/Tests/kinesis/amazon-kinesis-video-streams-webrtc-sdk-c/samples/opusSampleFrames/sample-000.opus"...

WARNING: Hole in data (4 bytes) found at approximate offset 160 bytes. Corrupted Ogg.
WARNING: Hole in data (156 bytes) found at approximate offset 160 bytes. Corrupted Ogg.
ERROR: No Ogg data found in file "/Users/anil/Tests/kinesis/amazon-kinesis-video-streams-webrtc-sdk-c/samples/opusSampleFrames/sample-000.opus".
Input probably not Ogg.
```

Are you using a different encoder to create these files?

**Comment by MushMal** [comment]
It’s hard to tell why there are errors generated - perhaps the GStreamer forums might be a better place to get more info about this plugin/encoder.

**Comment by CatsNipYummy** [comment]
@MushMal Any way to know how these opus files were generated? I can try using the same library to generate them.

[opusSampleFrames](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/master/samples/opusSampleFrames)

**Comment by chehefen** [comment]
they are here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L165-L177

**Comment by CatsNipYummy** [comment]
Is gstreamer producing the opus frames in the opusSampleFrames folder as well? For the kvsWebRTCClientMasterSample?

**Comment by chehefen** [comment]
no, it's wired up directly with the webrtc client.

**Comment by CatsNipYummy** [comment]
got it. so for the kvsWebRTCClientMaster.c sample, its pulling from the opusSampleFrames folder right? Located [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/master/samples/opusSampleFrames)

Can you tell me how those frames are generated? Guessing its outside the codebase?

**Comment by chehefen** [comment]
they are transcoded using gstreamer. This is an example of transcoding them to aac using gstreamer
```
gst-launch-1.0 multifilesrc location="opusSampleFrames/sample-%03d.opus" ! opusparse ! decodebin ! audioconvert ! avenc_aac ! multifilesink location="./sample-%03d.aac"
```

**Comment by MushMal** [comment]
Resolving
