### ISSUE TITLE
WebRTC C SDK - Stuck in lwsWssCallbackRoutine(): Client is writable

### ISSUE THREAD

**Issue by getash** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#462]
Hello there,

1. Installed the webRTC SDK for Embedded devices on my Jetson TX2
2. Execute make command to compile & build the samples
3. Exported the appropriate credentials
4.Ran ./kvsWebrtcClientMasterGstSample testchannel on the Jetson TX2
5. On the mac, opened the https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html & entered the appropriate info with "testchannel" in the channel name
6. Opened the "Start Viewer". Provided access to the webcam. The webcam is visible under "Viewer" while the "From Maser" is blank
7. On Jetson command prompt, it gets stuck in "lwsWssCallbackRoutine(): Client is writable".
8. Opened up AWS Management Console for AWS Kinesis. Opened the channel & tried to view the Media Playback viewer but it came back with the error - "Answer tried to set recv when offer did not send"

I am not attaching log but please message me directly if you need more information. Thanks!

**Comment by MushMal** [comment]
@getash it's not yet clear whether the master sample is "stuck" or is awaiting for the signal.

It would be very helpful if you could try to run the other master sample with the pre-canned frames on the device (to eliminate the GStreamer) and send us the debug logs. You can either attach the log file to this issue or email them at kinesis-video-support@amazon.com

**Comment by getash** [comment]
@MushMal I have attached the log for the GStreamer Master
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4637212/log.txt)

Ran the "./kvsWebrtcClientMaster testchannel" instead of GStreamer with same results. Please the log attached in that as well.
[log_clientmaster.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4637223/log_clientmaster.txt)

**Comment by chehefen** [comment]
Hi @getash, can you do a packet capture `sudo tcpdump -i any udp -w foo.pcap` while running the master and send us the pcap file? thanks

**Comment by getash** [comment]
@chehefen I have emailed the PCAP file to kinesis-video-support@amazon.com.  Please do the needful.

**Comment by mateuszboryn** [comment]
Hi, I also had "Answer tried to set recv when offer did not send".
I read elsewhere this might be specific to Firefox browser (@getash , what browser are you using btw?).
What helped in my case was modifying this file: `src/source/PeerConnection/PeerConnection.c`.
In function `addTransceiver()` I replaced 
`RTC_RTP_TRANSCEIVER_DIRECTION direction = RTC_RTP_TRANSCEIVER_DIRECTION_SENDRECV;`
with 
`RTC_RTP_TRANSCEIVER_DIRECTION direction = RTC_RTP_TRANSCEIVER_DIRECTION_SENDONLY;`
then I made some progress.
However this is not a permanent solution nor it made my usecase working.

**Comment by getash** [comment]
@mateuszboryn Thank you for the information. I shall try it today & let you know.

@chehefen @MushMal Any updates? Thanks!

**Comment by chehefen** [comment]
@getash are you also hosting your TURN server? You may not have set it up correctly. There is a lot of 401s in the pcap. Based on your log you should be able to view the stream. Can you try to use chrome?

**Comment by getash** [comment]
@chehefen I do not think so but let me try it on Chrome. I have tried Safari with the same results. I also tried @mateuszboryn recommendation of changing the PeerConnection with same results.

**Comment by getash** [comment]
@chehefen Chrome works for both AWS Management Console & the testing kvs page. Does this mean that Kinesis WebRTC will not work for any other browser? Thanks!

**Comment by chehefen** [comment]
Firefox's webrtc has different behaviors for different versions. We are trying to address them but right now chrome is the most stable.

**Comment by getash** [comment]
@chehefen Are there any other way to work this around on the viewer end handling those? Any specific media player we can embed? Thanks!

**Comment by chehefen** [comment]
I dont think you can get around that using media players. You can track this instead: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/49

**Comment by MushMal** [comment]
@getash seems that the original issue has been answered. Could you please close this issue and if needed open a new one to track any further issues

**Comment by getash** [comment]
@MushMal I believe the firefox issue is being tracked in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/49. If that is the case could you please confirm & provide an approximate timeline on this? Thanks!

**Comment by MushMal** [comment]
Confirming - this is the enhancement. Unfortunately, we can't give precise ETAs.

I am going to resolve this issue in favor of the enhancement that we are tracking
