### ISSUE TITLE
freePeerConnection() hanging

### ISSUE THREAD

**Issue by TomyTomm** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#466]
When a peer disconnects, I make a call to `freePeerConnection()` but the function call hangs. Is there any reason why?

**Comment by MushMal** [comment]
@TomyTomm could you please provide a little more information about your scenario and the assets you are using (sample app, etc).

Generally speaking freePeerConnection shouldn't hang, although is not a 'prompt' operation as it has to shutdown ICE agent, etc.. This said, it does have certain timeouts after which it gives up trying to gracefully shutdown sub-components.

Please enable the debug logs, run the scenario, attach a debugger when it 'hangs' and get core dumps or local stacks with local variables so we can see where it's at. Include the logs as well.

**Comment by TomyTomm** [comment]
I have changed a few things with the examples/common.c file:
- Removed the audio streaming functionality
- Added `pRtcDataChannel` to SampleStreamingSession struct
- Added a call to 
```
    CHK_STATUS(createDataChannel(pSampleStreamingSession->pPeerConnection,
                                 const_cast<PCHAR>("myDataChannel"),
                                 NULL,
                                 &pSampleStreamingSession->pRtcDataChannel));
```
- Added a call to 
```
    CHK_STATUS(dataChannelOnOpen(pSampleStreamingSession->pRtcDataChannel,
                                 reinterpret_cast<UINT64>(pSampleStreamingSession),
                                 pSampleConfiguration->onDataChannelOpenSend));
```
```
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:04 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:04 DEBUG   lwsWssCallbackRoutine(): Client is writable
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:04 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:07 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000020
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:07 DEBUG   executeDisconnectedIceAgentState(): Ice agent detected disconnection. current state ICE_AGENT_STATE_READY
[kinesis_webrtc_streamer-1] [INFO] [kinesis_webrtc_streamer]: [onConnectionStateChange] New connection state 4
[kinesis_webrtc_streamer-1] [INFO] [kinesis_webrtc_streamer]: [onConnectionStateChange] Ending streaming session for peer 4QP5BIK5STI
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:07 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:07 DEBUG   lwsWssCallbackRoutine(): Client is writable
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:07 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:14 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:14 DEBUG   lwsWssCallbackRoutine(): Client is writable
[kinesis_webrtc_streamer-1] 2020-05-19 04:37:14 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
```

**Comment by MushMal** [comment]
The changes you've made should be OK.

From your response, it's unclear what your scenarios is? Is your application which is based on the sample (assume master sample) "hangs" when terminating? How are you terminating the Master sample? Can you pause it under the debugger to get stack traces with locals?

**Comment by chehefen** [comment]
can you tell us which commit are you using?

**Comment by TomyTomm** [comment]
I am using the commit for release 1.0: f7c97063bdd6f6c8e32b718510aa7de1c8a2e4f6

**Comment by chehefen** [comment]
can you try the latest master? We fix a bunch of things around cleanup since 1.0.

**Comment by MushMal** [comment]
@TomyTomm could you please update this issue with the latest and resolve if this is not an issue for you

**Comment by enobufs** [comment]
I am also seeing freePeerConnection is hanging for about a second.
I am using the commit bbe061a.
I am using a data channel between the two local peers in the same process, sending 10 5-byte messages (loopbacked), then calling freePeerConnection() when the last message was received. freePeerConnection() is called by the app thread, not by any callbacks from the library.

**Comment by MushMal** [comment]
@enobufs it's hard to tell where exactly does the cleanup spend the time - it has to gracefully shutdown so some timeouts are OK.

We do have a set of unit tests that create and free peer connections in isolation of everything else. Can I ask you to run those and check the result? What platform are you using? Can you try on your target device and your desktop on the same network topology and compare the results?

**Comment by chehefen** [comment]
> I am also seeing freePeerConnection is hanging for about a second.
> I am using the commit [bbe061a](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/bbe061a2ce6f63a82b4cc8b02e524859d73ce9f0).
> I am using a data channel between the two local peers in the same process, sending 10 5-byte messages (loopbacked), then calling freePeerConnection() when the last message was received. freePeerConnection() is called by the app thread, not by any callbacks from the library.

could be due to this https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/bbe061a2ce6f63a82b4cc8b02e524859d73ce9f0/src/source/Ice/IceAgent.c#L648-L657. we are trying to free turn allocation during freePeerConnection.

**Comment by sharadrj** [comment]
@TomyTomm , is this issue resolved for you now?

**Comment by disa6302** [comment]
Stale ticket. Closing. Feel free to re-open or create a new issue if you have any questions!
