### ISSUE TITLE
get ice config fail sometimes with samples

### ISSUE THREAD

**Issue by willyting** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#467]
Hi all:
I run the samples with cross compile on my device.
It will get ice config fail, retry some times and stop the program.
It is fine with 64bit build on Ubuntu and cross compile on other two platform inside the same network env.
I cannot figure out what happened from logs.

On the specific device
It sometimes get ice server list fail at first time.
It always get ice config fail when I stop and run program again quickly.
It will get ice config success again after 1 min or more.
It will show some message when get ice config fail

-------------------- log start -----------------
2020-05-18 07:54:35 VERBOSE lwsCompleteSync(): Perform secure synchronous call for URL: https://r-2c136a55.kinesisvideo.ap-northeast-1.amazonaws.com/v1/get-ice-server-config 
2020-05-18 07:54:35 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 85
2020-05-18 07:54:35 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 71
2020-05-18 07:54:35 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 71
2020-05-18 07:54:35 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 1
2020-05-18 07:54:35 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 29
2020-05-18 07:54:35 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 19
2020-05-18 07:54:35 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
2020-05-18 07:54:35 VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 30
-------------------- log end -----------------

**Comment by MushMal** [comment]
@willyting the signaling client retrieves the ICE configuration during the create call and keeps refreshing it just before the credentials in the configs expire. As it handles the refreshing in the background, if it fails retrieving the configs for whatever reason after set number of retries and overall timeout is reached, it will notify the calling application through the error callback. The error callback in the samples case is really minimalistic and real-life applications can chose to react differently than simply tearing things down as the sample does. For example, your real-life application can re-start the master.

Getting back to the failure. From the snippet of log it seems that it's due to network connection. 

Recommend:

* Ensure the network is established on the device (use some online tools, etc).
* Ensure you have the correct credentials provider and your credentials do not expire/get refreshed properly.
* Enable LWS debug logs by compiling with this line uncommented: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/CMake/Dependencies/libwebsockets-CMakeLists.txt#L37
* Ensure you set the debug logging level on the client (for example, in samples set https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L647 env variable to 2)
* Ensure you are using the region closest to your geographic locality.

**Comment by willyting** [comment]
Hi @MushMal :
I am sure the network, credentials and closet region. It usually work fine at first time or wait a while.
I set log level to VERBOSE as follow
export AWS_KVS_LOG_LEVEL=1

I try to enable LWS debug logs by compiling with this line uncommented: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/CMake/Dependencies/libwebsockets-CMakeLists.txt#L37

But I did not get more logs??!!

**Comment by MushMal** [comment]
You are setting the logging level correctly. You will also need to delete the libwebsockets.* from open-source/local/lib directory to kick off the debug build when you run build.

It is rather odd that the connection gets closed. Can you also run some network troubleshooting tools (any) on your device to ensure the connectivity?

**Comment by willyting** [comment]
As a network tools:   "netstat -nlp"

I found sample program always use a port: 132
----------------------
udp        0      0 0.0.0.0:55019           0.0.0.0:*                           1997/kvsWebrtcClien
udp        0      0 :::51579                :::*                                1997/kvsWebrtcClien
raw        0      0 0.0.0.0:132             0.0.0.0:*               132         1997/kvsWebrtcClien
raw        0      0 :::132                  :::*                    132         1997/kvsWebrtcClien
----------------------

But it is only two port used on my Ubuntu:
----------------------
udp        0      0 0.0.0.0:55161           0.0.0.0:*                           18498/kvsWebrtcClie
udp6       0      0 :::49204                :::*                                18498/kvsWebrtcClie
----------------------

**Comment by willyting** [comment]
I compare the log between get ice success and fail.
I found out there are not a reason callback 58.
```
VERBOSE lwsHttpCallbackRoutine(): HTTPS callback with reason 58
```
As the log, the lbs Program start to handshake after the callback.
```
I: lws_openssl_describe_cipher: wsi 0xbdaa0: ECDHE-RSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-GCM-SHA256, 128 bits, TLSv1.2
I: lws_client_socket_service: HANDSHAKE2: 0xbdaa0: sending headers on 0xbdaa0 (wsistate 0x10000012 0x10000012), w sock 11, wsi sock 11
```

**Comment by MushMal** [comment]
Reason 58 is LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION which will be called after the connection is established. In your case, you simply don't seem to have the connection - perhaps your routing is bad or have a firewall or something is interfering.

The open ports should be fine. Try to get the libWebSockets debug version and also try to enable more verbose logs from LWS by replacing lines
to https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/LwsApiCalls.c#L54 and https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/LwsApiCalls.c#L273

with 

`lws_set_log_level(LLL_NOTICE | LLL_INFO | LLL_WARN | LLL_DEBUG | LLL_ERR, NULL);`

**Comment by willyting** [comment]
[first.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4655058/first.txt)

**Comment by willyting** [comment]
[sch-ok-1.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4655722/sch-ok-1.txt)

This log get ice config fail at first.
Success after retry some times.

**Comment by MushMal** [comment]
@willyting thanks for the logs. Looking through them, I still can't tell what exactly is going on.

Could you please disable async get ice config in the sample?

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L676

set it FALSE

**Comment by willyting** [comment]
@MushMal It work!!
It get ice config success always. Thinks.
Maybe it is some resource not enough in this platform. But we do not know.

**Comment by MushMal** [comment]
Perhaps. With the async, we are trying to minimize the overall startup->ready time by parallelizing the higher-level create/connect calls.

I am very glad that it works - one less mystery I guess :).

I am resolving this issue for now. Please feel free to re-open or cut a new one if you need any further assistance
