### ISSUE TITLE
Display human readable error code when Access/Secret key is unset

### ISSUE THREAD

**Issue by devxiaoyi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#47]
hi, How can I run the executable file? such as kvsWebrtcClientMaster and kvsWebrtcClientViewer. when I run that on Mac, I got "main(): operation returned status code: 0x00000002"

**Comment by chehefen** [comment]
Hi, did you export the aws credentials before you run? they should be exported like such
```
export AWS_ACCESS_KEY_ID=access-key
export AWS_SECRET_ACCESS_KEY=secret-key
./kvsWebrtcClientMaster channel-name
```

**Comment by devxiaoyi** [comment]
> Hi, did you export the aws credentials before you run? they should be exported like such
> 
> ```
> export AWS_ACCESS_KEY_ID=access-key
> export AWS_SECRET_ACCESS_KEY=secret-key
> ./kvsWebrtcClientMaster channel-name
> ```
It works for me! thanks!!

**Comment by Sean-Der** [comment]
Thank you so much for opening this ticket @devxiaoyi 

I am going to re-open and close it when we have a better error message so users don't hit this in the future, thanks!
