### ISSUE TITLE
Better Support Reusing the Same Client ID after Leaving and Rejoining the Session

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#475]
If we use the same Client ID on the test page here:
https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html
If we open a session, then followed by closing and opening a new session with the same Client ID, the success rate of connecting to the new session is very low. However, if we were to use a new Random ID, the success rate of closing and opening a new session is very high.

One method to increase this success rate is to removing the check on whether the offer had already been received, but after removing this check, the success rate of reusing the same client id is still very low.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L155

Our use case is not to generate too many random client IDs, because we found doing so will break the signaling channel.

**Comment by suggestedfixes** [comment]
Can we assume that the offer is the first one that always arrives? Are there edges cases where candidates can arrive before the offer?

**Comment by suggestedfixes** [comment]
Cause I'm currently getting a track, but the track does not have video. I think we might have re-init some of the transceivers in handleOffer()

**Comment by chehefen** [comment]
you can check this out: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/481

**Comment by MushMal** [comment]
Using our assets should prevent the case you are describing - you should be getting offer from a viewer and answer and only after that exchange ICE, etc..

**Comment by chehefen** [comment]
@suggestedfixes the PR I linked added the ability to detect TLS close alert and trigger RTConnectionStateChange callback to closed. With that added, the sdk will be able to detect that peer has close the session and clean up the streamingSession promptly. Then you can connect again using the same clientId.

**Comment by suggestedfixes** [comment]
@chehefen I’ve discovered that while opening and closing the viewer using the button worked. But closing the tab while the master is streaming, then opening another tab and opening new connections will block new connections regardless of client ID.

**Comment by sharadrj** [comment]
Got report from customer - "For the single client ID testing. I’ve discovered that while opening and closing the viewer worked. But closing the tab while the master is streaming, then opening another tab and opening new connections will block new connections regardless of client ID. I am going to report it on github as well."

**Comment by lherman-cs** [comment]
@suggestedfixes Do you mind to retry with the JS sample? https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/pull/56 should fix this issue.

**Comment by chehefen** [comment]
issue is fixed by https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/pull/56
