### ISSUE TITLE
Signalling Reconnection Failure

### ISSUE THREAD

**Issue by chehefen** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#48]
Steps to repro
- start kvsWebrtcClientMaster sample, but dont start any viewer
- wait for 5 min. After around 5min, there should be log showing signaling tries to refresh iceServers.
- Start the viewer
     - expected outcome: master receives the offer and starts streaming
     - actual outcome: master doesnt receive anything.

**Comment by MushMal** [comment]
Working on the reconnect - there was a regression. ETA - tomorrow

**Comment by chehefen** [comment]
resolved
