### ISSUE TITLE
Using GStreamer in kvsWebrtcClientViewer

### ISSUE THREAD

**Issue by tesnorindian** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#482]
Hi all,

I tried integrating GStreamer in to the sample kvsWebrtcClientViewer code. I tried sending RTP packets from Chrome browser using WebRTC. I am able to receive the frames in the callback of transceiverOnFrame. But how to distinguish between a audio frame and a video frame in the frame handler callback, so that I can pass it to the corresponding gstreamer pipeline.  

Thanks in advance.

**Comment by suggestedfixes** [comment]
One way is to grab the trackId from the handler
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L540

**Comment by MushMal** [comment]
Generally speaking you have a callback per transceiver so at the high level you can distinguish between the transceivers. In case of multi-track, as @suggestedfixes suggests you can use the trackid differentiator.

I am going to resolve this question. Please feel free to re-open or cut a new one

**Comment by tesnorindian** [comment]
Thanks @MushMal and @suggestedfixes
