### ISSUE TITLE
Caching endpoints

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#489]
Current AWS SDK supports caching endpoints with SIGNALING_API_CALL_CACHE_TYPE_FILE switch. We heard that this feature is experimental.
Will this caching be supported in the future?
What is the pros and cons of it?
How much time can be saved not describe-get-endpoint?

**Comment by MushMal** [comment]
@zwei333 anything in the Master branch is official. Unless there are explicit comments and specific information in the readme you can treat this as the ultimate source of truth (not sure what channels you use).

There are few caching policies defined here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1033

The comments are very explicit about their behavior (please let us know if it's not).

To answer your question. If you have an intermittent viewer application that starts quite often and needs to optimize the speed from the event (triggering viewer) to streaming. In this scenario, the application starts "cold" so there will be cache miss if SIGNALING_API_CALL_CACHE_TYPE_DESCRIBE_GETENDPOINT is used. For this reason, we have a file based cache: SIGNALING_API_CALL_CACHE_TYPE_FILE. However, if the application is a long-running master application then cold start happens at the device boot time some time ago and the cache miss with SIGNALING_API_CALL_CACHE_TYPE_DESCRIBE_GETENDPOINT happens off of the "hot" path.

The drawback with caching as with any other cache is that the cache can go stale and the call to connect or other API might result in an error. However, the SDK signaling client state machine will handle the error and get back to the correct state and issue a backend API call to get endpoint.

Regarding saving on the call... It really depends. The main savings are the latencies associated with the device networking as the APIs are fairly fast and resolve within few milliseconds. However, there are networks with 200+ms latencies so even two calls can evaluate to close to half a second savings.

Please resolve this issue if you have no further questions

**Comment by zwei333** [comment]
Thank you for your detailed response.
For our camera, looks like SIGNALING_API_CALL_CACHE_TYPE_FILE is the way to go.  Our camera is battery powered, shuts down when not active.  When app viewer sends request, camera needs to cold boot and do a lot of things until stream video/audio.  If we can manage to save half a second, that is a lot of time.
However, there is a small problem of SIGNALING_API_CALL_CACHE_TYPE_FILE. It tries to create a file in current directory.  This is not possible for most embedded system.  We ran into crash with this option.  I will test to see if it is caused by the file location.

**Comment by MushMal** [comment]
@zwei333 from what you describe indeed it sounds most suitable. Though, savings are highly dependent on the network in question.

Please capture the crash stack so we can understand whether it's access issue or something else. 

NOTE: On "well behaved" OS we shouldn't get a crash when failing to read/write to the local file. The SDK low-level file I/O is based on C standard file I/O so it should fail gracefully and the SDK should handle the failure gracefully. You might see warnings in file cache operations but it should still proceed without any crash as if it was a fall-through case.

Please resolve this issue and open a new one to track the crash if that's the case

**Comment by zwei333** [comment]
Found out crash is not because of file creation.
It is caused by this line of Signaling.c 
STRCPY(signalingFileCacheEntry.channelName, pSignalingClient->pChannelInfo->pChannelName);

We use a special API, channelInfo.pChannelName = NULL to skip  Signaling Client State "Describe Channel".  But the null pointer causes trouble.

**Comment by MushMal** [comment]
@zwei333 could you please provide further information so we can harden the API against accidental mis-use? At any rate, if you have your question answered, could you please go ahead and resolve this

**Comment by zwei333** [comment]
The special API is for IoT credentialing.  Channel is pre-created so "Describe channel" should be skipped. 
channelInfo.pChannelName = NULL will tell SDK to do so
adding  "if(pSignalingClient->pChannelInfo->pChannelName)" before 
STRCPY(signalingFileCacheEntry.channelName, pSignalingClient->pChannelInfo->pChannelName);
can fix the crash

**Comment by lherman-cs** [comment]
@zwei333 Supporting null channel name seems to be a bit tricky since we use the channel name and region to get the cache back. So, I think it makes more sense to set the channel name to a constant value.

**Comment by MushMal** [comment]
At the higher level validation on ChannelInfo we validate that either channel name or channel ARN is specified. If channel ARN is specified then we skip the describe state all together as the assumption is that the channel had been already pre-created.

While we don't encourage not specifying channel name, we should really fix the code to not crash for sure.

**Comment by zwei333** [comment]
I thought you require channel name == null for the iot case.  now looks like the decision is only made on if ARN == null or not.
Then I can give channel name its value to simplify the SDK code.  Having a special condition means adding a lot of corner cases.  I will try it quickly

**Comment by MushMal** [comment]
Yes, that will help but we will follow-up with a fix for the crash anyway

**Comment by zwei333** [comment]
Thanks.  I tested.  With current SDK, if I give channel name its true value, not NULL, webrtc won't crash.  I am OK with the solution so far, so I will close this issue
