### ISSUE TITLE
SDK outputs too many error messages

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#490]
When bandwidth is limited, SDK could repeat printing error messages, such as "GetNextNalu failure" ( I don't recall the exact wording.  Will update once I see it again)
At that time, video quality suffers but streaming is still running, and webrtc is still doing OK.  What bothers is these high volume of error messages flood our logging file.
We set the log level to "INFO", but these messages level is "ERROR"
Could repeated error messages (those are generated for each video/audio frame) be consolidated or demoted in log level?

**Comment by MushMal** [comment]
@zwei333 I am pretty sure this is the line that prints the error:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Rtp/Codecs/RtpH264Payloader.c#L125

There are really two issues associated with this. 

1) The verbosity of an error that can happen quite often on a proper negative path such as retrying of the packet. This should be fixed and we are welcoming any fixes that customers can send a PR. A proper fix might be to remove CHK_LOG_ERR() with if (STATUS_FAILED(retStatus)) {DLOGD("GetNextNalu failed...");}
2) Understand why this fails in the first place.

For the second, would you please try to capture more information about your stream so we can analyze. Normally, even with the network pressures, this path is responsible for sending the frames in 'writeFrame' API in the transceiver so it shouldn't result in errors. Is your device using some sort of rtsp input itself that could corrupt frames?

**Comment by zwei333** [comment]
Yes, the message is the line.
For understanding how it happens:
Is it possible that the frame is overwritten in noisy network?  
Our camera video encoder uses circular buffer to store video frames, and there is no overwrite prevention. It is user's responsibility to copy video data before it expires (overwritten). 
To minimize delay and memory usage, our app forwards the frame data pointer to KVS SDK without copying the frame data. If SDK can't copy the data quickly enough (I remember the data is valid for 8 seconds, to be confirmed), the data will be corrupted.
I remember I saw it recently.  I simulated low bandwidth by running six streamings at the same time.  I saw a video latency of 12 seconds and I found SDK was printing a lot of messages of this error.
Could network condition slows down SDK sending frames in writeFrame API?
Our app runs a thread per connection, and the timing of forwarding frame data pointer to SDK is not affected by network condition.

**Comment by MushMal** [comment]
@zwei333 you need to debug your application and put some guarantees that your application won't corrupt the frame while it calls writeFrame. Network slow-downs should not affect writeFrame as it operates on the original bits. True, there is interlocking that needs to be dealt with but generally speaking writeFrame is a 'prompt' operation so its fast.

Before we even fix the printout, we should try to understand the root cause of the issue you are seeing as if your media pipeline is stable you won't see these errors in the first place.

Try to put a breakpoint in this location and run with some network pressures. See whether the frame bits are corrupted. Your application should handle the multi-threading

**Comment by zwei333** [comment]
We will investigate why the error happens.
getNextNaluLength error is only one example of this issue.
Generally, if error happens frequently (for example, for each video frame), error messages will be printed many times.  It burdens logging storage.  Can SDK be smart in handling this case, do not flood the logging?

**Comment by MushMal** [comment]
It depends on the situation. Adding more heuristics will make the code cumbersome and will break in some situations. This particular case should be replaced by DLOGW or DLOGV perhaps - it tells you that your frame is bad. You could then filter out those by setting appropriate level. Each case should be considered separately though.

**Comment by zwei333** [comment]
Yes, it seems not practical to have more control on printing this error message
I will suggest that any message repeating quickly be DLOGW or below.

**Comment by MushMal** [comment]
@zwei333 I agree that under the normal circumstances it should be DLOGV. However, we didn't expect this to be that type of issue.

Let me provide a quick fix shortly for this.

**Comment by zwei333** [comment]
Other examples are
"socketConnectionSendData(): Failed to send data. Socket closed already."
"socketConnectionSendData(): sendto data failed with errno" 
When wifi network is marginal, I got a lot of these prints.  While SDK can't improve wifi signal, the high volume error prints are quite a burden for the system

**Comment by zwei333** [comment]
Issue is fixed
