### ISSUE TITLE
Time to transition to RTC_PEER_CONNECTION_STATE_DISCONNECTED > 30seconds

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#491]
When our webapp finishes streaming and closes peer connection and signaling channel, camera(master) does not transition to RTC_PEER_CONNECTION_STATE_DISCONNECTED right away.  It remains CONNECTED for another 30 seconds.
Wonder if this is the expected behaviour.

Webapp's closing is shown in the attached picture
![image](https://user-images.githubusercontent.com/55103241/82841504-58cee280-9ea4-11ea-8e19-e3764aea6a61.png)

**Comment by MushMal** [comment]
Yes, this is the expected behavior for now. For P2P scenario, we are trying to make this more "live" https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/484

**Comment by MushMal** [comment]
One more thing.. The latest codebase already has a state transition when DTLS closes. Could you please check whether you are using P2P and use the latest codebase

**Comment by zwei333** [comment]
I am on P2P: I am streaming from camera in the same wifi network.
I am using release 1.1.0.
I will try the latest codebase

**Comment by zwei333** [comment]
Confirmed. The issue is fixed.
Closing the it
