### ISSUE TITLE
[Question] Signaling Channel Client ID regex

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#500]
What is a valid set of characters that can be used to specify signaling client viewer/master ID?

**Comment by lherman-cs** [comment]
@suggestedfixes It's  `^((?!(?i)AWS_.*)[a-zA-Z0-9_.-]`. For more details, you can find it here, https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-websocket-apis-1.html.
