### ISSUE TITLE
Support for VP9

### ISSUE THREAD

**Issue by tesnorindian** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#502]
Hi All,

It would be nice if AWS WebRTC C SDK supports VP9 payload. As VP9 is widely used now in Mobile and Web and AV1 adoption is still a long way to go.

How can I enable support for VP9. Is it similar as like VP8? Or is there any special needs for VP9. I don't have much idea about RTP payloads and its type. If somebody can guide me it will be of helpful.

**Comment by lherman-cs** [comment]
I think supporting VP9 would be just a matter of serializing and deserializing RTP headers with proper VP9 spec for RTP. I should be similar to VP8.

@Sean-Der any thought?

**Comment by tesnorindian** [comment]
Hi Iherman-cs,

Please find the latest VP9 RTP payload spec for your reference.

https://datatracker.ietf.org/doc/draft-ietf-payload-vp9/

Thanks in advance.

**Comment by MushMal** [comment]
Thanks for the information @tesnorindian . We will try to provide the vp9 support based on the priority. Meanwhile, we are welcoming any contribution to the code base

**Comment by tesnorindian** [comment]
Thanks @MushMal .

**Comment by MushMal** [comment]
I am going to resolve this for now. Will re-open when/if we start working on it. The prioritization will also be based on the browser and other clients support for VP9
