### ISSUE TITLE
Firefox 76 not working with KVSViewer

### ISSUE THREAD

**Issue by tesnorindian** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#505]
Hi all,

KVSViewer is dropping the STUN packets from Firefox 76 running in Win 10. The following log is being printed by the viewer

2020-06-01 10:17:00 WARN    handleStunPacket(): Dropping unrecognized STUN packet. Packet type: 0x111. Packet content:
        011100142112A442A1C590810A03E7171397C5C70009001000000401556E617574686F72697A6564
2020-06-01 10:17:00 WARN    handleStunPacket(): Dropping unrecognized STUN packet. Packet type: 0x111. Packet content:
        011100142112A4423FFFAC356E5CE63CDD683DB60009001000000401556E617574686F72697A6564
2020-06-01 10:17:00 WARN    handleStunPacket(): Dropping unrecognized STUN packet. Packet type: 0x111. Packet content:
        011100142112A442B5665FED07226BDABF46EED80009001000000401556E617574686F72697A6564
2020-06-01 10:17:00 WARN    handleStunPacket(): Dropping unrecognized STUN packet. Packet type: 0x111. Packet content:
        011100142112A44215B2F3ECBF416853F92B32AD0009001000000401556E617574686F72697A6564
2020-06-01 10:17:01 WARN    handleStunPacket(): Dropping unrecognized STUN packet. Packet type: 0x111. Packet content:
        011100142112A442EE25F476578B87AFA1BB51420009001000000401556E617574686F72697A6564
2020-06-01 10:17:01 WARN    handleStunPacket(): Dropping unrecognized STUN packet. Packet type: 0x111. Packet content:
       011100142112A4426EEFE5BB47BE3D8EFFA92B050009001000000401556E617574686F72697A6564
2020-06-01 10:17:01 WARN    handleStunPacket(): Dropping unrecognized STUN packet. Packet type: 0x111. Packet content:

SDP Offer from KVSViewer:

v=0
o=- 1700110352 2 IN IP4 127.0.0.1
s=-
t=0 0
a=sendrecv
a=group:BUNDLE 0 1 2
a=msid-semantic:WMS myKvsVideoStream
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 127.0.0.1
a=candidate:0 1 udp 658881 172.31.27.237 54166 typ host raddr 0.0.0.0 rport 0 generation 0 network-cost 999
a=sendrecv
a=fingerprint:sha-256 42:D8:32:08:9E:63:24:CF:18:F3:96:52:21:A9:4F:66:92:07:1B:EC:CC:8F:26:51:9E:56:3F:D5:AD:C6:7F:04
a=fmtp:111 maxplaybackrate=0;stereo=0;useinbandfec=1
a=ice-pwd:rXLgjDEoABKo6DCSfv09Fiad
a=ice-ufrag:5QJo
a=mid:0
a=msid:myKvsVideoStream myAudioTrack
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:111 nack
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=setup:actpass
a=ssrc:903487670 cname:ynteOX+pX6e8XkLG
a=ssrc:903487670 msid:myKvsVideoStream myAudioTrack
a=ssrc:903487670 mslabel:myKvsVideoStream
a=ssrc:903487670 label:myAudioTrack
m=video 9 UDP/TLS/RTP/SAVPF 125
c=IN IP4 127.0.0.1
a=sendrecv
a=fingerprint:sha-256 42:D8:32:08:9E:63:24:CF:18:F3:96:52:21:A9:4F:66:92:07:1B:EC:CC:8F:26:51:9E:56:3F:D5:AD:C6:7F:04
a=fmtp:125 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=ice-pwd:rXLgjDEoABKo6DCSfv09Fiad
a=ice-ufrag:5QJo
a=mid:1
a=msid:myKvsVideoStream myVideoTrack
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:125 nack
a=rtcp-mux
a=rtpmap:125 H264/90000
a=setup:actpass
a=ssrc:1220104794 cname:ynteOX+pX6e8XkLG
a=ssrc:1220104794 msid:myKvsVideoStream myVideoTrack
a=ssrc:1220104794 mslabel:myKvsVideoStream
a=ssrc:1220104794 label:myVideoTrack
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 127.0.0.1
a=sendrecv
a=fingerprint:sha-256 42:D8:32:08:9E:63:24:CF:18:F3:96:52:21:A9:4F:66:92:07:1B:EC:CC:8F:26:51:9E:56:3F:D5:AD:C6:7F:04
a=ice-pwd:rXLgjDEoABKo6DCSfv09Fiad
a=ice-ufrag:5QJo
a=mid:2
a=rtcp:9 IN IP4 0.0.0.0
a=setup:actpass
a=sctp-port:5000

SDP Answer from FF 76 on Windows 10:

v=0
o=mozilla...THIS_IS_SDPARTA-76.0.1 7594870933370082027 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 9E:27:C3:5B:1A:21:98:83:93:19:E1:1F:54:97:82:CC:22:CF:EE:0F:C9:BB:66:56:49:E7:C8:D1:43:41:72:AB
a=group:BUNDLE 0 1 2
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=sendrecv
a=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=ice-pwd:71242df4cbbd04fa3c490914513fe05a
a=ice-ufrag:1f859e54
a=mid:0
a=msid:{c9f3af9b-86d9-485d-ac00-903a0e04c481} {3ad1a700-ed80-4c54-ba6e-28c85d6c8e9c}
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=setup:active
a=ssrc:3966018485 cname:{7fa795fa-508a-4498-9234-bb2bd2549449}
m=video 9 UDP/TLS/RTP/SAVPF 125
c=IN IP4 0.0.0.0
a=sendrecv
a=fmtp:125 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=ice-pwd:71242df4cbbd04fa3c490914513fe05a
a=ice-ufrag:1f859e54
a=mid:1
a=msid:{c9f3af9b-86d9-485d-ac00-903a0e04c481} {417da8be-7ecf-41e7-b9b8-69b3159a29e5}
a=rtcp-fb:125 nack
a=rtcp-mux
a=rtpmap:125 H264/90000
a=setup:active
a=ssrc:1861262918 cname:{7fa795fa-508a-4498-9234-bb2bd2549449}
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=sendrecv
a=ice-pwd:71242df4cbbd04fa3c490914513fe05a
a=ice-ufrag:1f859e54
a=mid:2
a=setup:active
a=sctp-port:5000
a=max-message-size:1073741823

Can you please help me in fixing this.

Thanks in advance.

**Comment by chehefen** [comment]
@tesnorindian  can you try checkout this PR https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/504? I think it may solve the issue you ran into.

**Comment by tesnorindian** [comment]
@chehefen,  I can confirm that PR #504 fixes this issue and can be closed.
