### ISSUE TITLE
Current AWS_KVS_CACERT_PATH only accepts full path to the pem file

### ISSUE THREAD

**Issue by zhiyua-git** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#51]
Unlike C/C++ producer SDK, we are only accepting full path to pem file in AWS_KVS_CACERT_PATH now. Need to check if we can also detect if given path is a directory and support that if libwebsocket supports it.

**Comment by Sean-Der** [comment]
@disa6302 mind grabbing this? Should be a quick little win and will bring the bug count down :)

I am going to grab some other issues, but feel free to pull me in if anything comes up

**Comment by disa6302** [comment]
Sure thing! I will work on this
