### ISSUE TITLE
SET_LOGGER_LOG_LEVEL/GET_LOGGER_LOG_LEVEL not working issue

### ISSUE THREAD

**Issue by ajjiang48** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#517]
Hi, I used SET_LOGGER_LOG_LEVEL to set a different log level than the AWS_KVS_LOG_LEVEL environment variable, but it looks the real log level always match what the AWS_KVS_LOG_LEVEL set, if there's no AWS_KVS_LOG_LEVEL, it looks the log level is always 7 (LOG_LEVEL_VERBOSE).
The SDK version I used is newer than 1.0.0 (I just git clone the C SDK to check this issue on 6/2).
Please help check it. Thanks, A.J.

**Comment by MushMal** [comment]
Verbose is 1. Please set values between 1-7

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#setup-desired-log-level

**Comment by ajjiang48** [comment]
@MushMal sorry I mis-match the log level wording and the number; I used the defined log words LOG_LEVEL_SILENT in the code (SET_LOGGER_LOG_LEVEL(LOG_LEVEL_SILENT )), but it always prints DEBUG/INFO logs, but if I run the command "export AWS_KVS_LOG_LEVEL=7" before the sample webrtc viewer, the result will be correct (no DEBUG/INFO logs printed). that's why I said the SET_LOGGER_LOG_LEVEL/GET_LOGGER_LOG_LEVEL is not working based on my tests. Please help check it. Thanks, A.J.

**Comment by MushMal** [comment]
@ajjiang48 it's hard to debug this without concrete code. Can you please provide a little more context as to what you are trying to do? Are you trying to set the log level in the sample application? If so, are you setting it before or after the sample application sets the log level from the env variable?

Also, NOTE: The signaling client will re-set the log level to the one that's specified in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1068

Thus, the common file in the samples sets this variable to the same level:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L690

This is done as the signaling client is logically a separate object dag from WebRTC - the former is entirely KVS specific while the latter is driven by W3C specs.

**Comment by chehefen** [comment]
@ajjiang48, it's probably that the environment variable processing happened after your SET_LOGGER_LOG_LEVEL call and override your setting. Any reason you cant use the AWS_KVS_LOG_LEVEL environment variable to set log level?

**Comment by ajjiang48** [comment]
@MushMal @chehefen I just reference the the sample viewer source code and do the log level set ONLY in the createSampleConfiguration function; the codes is very simple as below:
+++++
   // Set the logger log level
    pLogLevel = NULL;
    pLogLevel = getenv(DEBUG_LOG_LEVEL_ENV_VAR);
    if (pLogLevel != NULL) {
    	STRTOUI32(pLogLevel, NULL, 10, &logLevel);
    }    	
    else {
	logLevel = LOG_LEVEL_SILENT;
	printf("[WebRTCViewer] no log level env variable, set log level to LOG_LEVEL_SILENT\n");
    }
	
    SET_LOGGER_LOG_LEVEL(logLevel);
    printf("[WebRTCViewer] log level set to: %d\n", GET_LOGGER_LOG_LEVEL());
++++
the GET_LOGGER_LOG_LEVEL prints whatever I set in the SET_LOGGER_LOG_LEVEL, but it's interesting that the REAL log level just follows what the environment variable set (export AWS_KVS_LOG_LEVEL=X), so I'm curious if there's other codes doing the AWS_KVS_LOG_LEVEL check to override my settings. Thanks, A.J.

**Comment by disa6302** [comment]
@ajjiang48 , 

We do parse the environment variable in createPeerConnection as well. Again, to @chehefen's point, the environment variable is probably being read after you set logger level which is causing the override. Where in code are you calling GET_LOGGER_LEVEL?

Also, is there any specific reason you want to use the getters/setters instead of the environment variable?

**Comment by ajjiang48** [comment]
@disa6302 1. that's what I confused case I just call the SET_LOGGER_LOG_LEVEL/GET_LOGGER_LOG_LEVEL in the createSampleConfiguration function (just as the sample viewer), that's all what I do, and don't know why my settings are overridden. 
2. I want to use SILENT log level if there's no env variable setting (daily-use scenario, if I need to do debugging, then set the log level env variable), but it goes to the DEBUG or INFO log level (I see many INFO/DEBUG log printed) if no env variable setting.

**Comment by MushMal** [comment]
Not sure I am following on what's gong on with the thread.

You can "silence" the KVS WebRTC side logging by setting AWS_KVS_LOG_LEVEL=7 like this

`export AWS_KVS_LOG_LEVEL=7`

Could you try this and report in details what's observed. This is a super simple issue and for some reason it's being iterated over for days with no resolution.

**Comment by MushMal** [comment]
Resolving due to staleness. Please reopen or cut a new issue if need further assistance

**Comment by mdonahoe** [comment]
I too had this problem.

I would prefer not to rely on environment variables, and my initial call to SET_LOGGER_LOG_LEVEL was being overridden with every new PeerConnection.

My solution is to re-set the level after each peer connection is created. Feels a bit dirty, but it works.
