### ISSUE TITLE
[BUG]Memory is not released completely after session disconnecting

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#518]
**Describe the bug**
The memory usage rate is increasing during the connection.

I have customized the following params to reduce the size of the rolling buffers.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/Rtp.h#L11-L12
```
#define DEFAULT_ROLLING_BUFFER_DURATION_IN_SECONDS              1
#define HIGHEST_EXPECTED_BIT_RATE                               (2 * 1024 * 1024)
```
I added the definitions in CMakeLists.txt. And reset the allocators in code.
`	add_definitions(-DINSTRUMENTED_ALLOCATORS)`
`SET_INSTRUMENTED_ALLOCATORS();`
It print the size of allocation regularly as follows:
GetAllocationSize,==-=>size[71926]!

When I connected to the device for a while, the memory usage increased to 2891417. From 71926 to 2829102. After disconnecting the memory usage decreased to 1103593 which was higer than before.

This phenomenon does not happen every time. Usually it occurs when the network is not good enough or the devices and viewers are under different networks. When I use the master and viewer in our office, it is hard to reprodure. However, preview elsewhere easily to reproduce.

Here is the full log.
[master.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4729944/master.log)

**Comment by MushMal** [comment]
@Nomidia thanks for the report. Generally speaking, the RTP buffer is what can reserve most of the memory. On "bad" networks when packets get dropped there will be re-sends and hence more allocation. However, once the peer connection terminates, it should tear down the entire memory usage. Can you please check:

* When you are stopping the session, the peer connection can take some time to fully cleanup. Make sure the peer connection is actually torn down
* When you exit the application, does the memory not get claimed?

You can add SET_INSTRUMENTED_ALLOCATORS() right at the beginning of the application and RESET_INSTRUMENTED_ALLOCATORS() just before exiting. It should tell whether all the memory had been freed.

This will help with the investigation.

**Comment by Nomidia** [comment]
I ran the demo and reproduced the problem. The final occupied memory minus the leaked memory equals to the vaule before connection. 2114006 - 2042016 = 71990
[master2.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4733655/master2.log)

**Comment by MushMal** [comment]
Thanks, it's not immediately clear what causes the leak - seems that some of the negative paths do not free allocations. Can you please confirm that you don't have any changes of your own?

I would love if we can reproduce this locally so we can look into this closer.

**Comment by MushMal** [comment]
Looking at the leaked numbers (2042016 bytes) it seems that the rtp buffer didn't get freed perhaps. Hard to tell. Please try to answer the question about the modifications you've made. Would be nice to have a clear way to reproduce

**Comment by Nomidia** [comment]
Sorry, it was lunch time. I only change the size of rolling buffer cause last week I found it occupied too much memory. The test was normal at the time. But when the network is sometimes not good, the live stream will stop after watching for a while.
```
#define DEFAULT_ROLLING_BUFFER_DURATION_IN_SECONDS              1
#define HIGHEST_EXPECTED_BIT_RATE                               (2 * 1024 * 1024)
``

**Comment by MushMal** [comment]
Got it. Let us do some testing on our side to try to hit this so we can debug. We will also need to look closed at the logs you've produced - perhaps it can give better hints

**Comment by chehefen** [comment]
this is the diff
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 49cfe564..d3d77db4 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -184,7 +184,7 @@ endif()

 # Uncomment below line for very verbose logging
 # add_definitions(-DLOG_STREAMING)
-
+add_definitions(-DINSTRUMENTED_ALLOCATORS)
 file(
   GLOB
   WEBRTC_CLIENT_SOURCE_FILES
diff --git a/samples/kvsWebRTCClientMaster.c b/samples/kvsWebRTCClientMaster.c
index b1b87e02..285260f9 100644
--- a/samples/kvsWebRTCClientMaster.c
+++ b/samples/kvsWebRTCClientMaster.c
@@ -9,6 +9,7 @@ INT32 main(INT32 argc, CHAR *argv[])
     STATUS retStatus = STATUS_SUCCESS;
     UINT32 frameSize;
     PSampleConfiguration pSampleConfiguration = NULL;
+    SET_INSTRUMENTED_ALLOCATORS();

 #ifndef _WIN32
     signal(SIGINT, sigintHandler);
@@ -130,6 +131,7 @@ CleanUp:
             printf("[KVS Master] freeSampleConfiguration(): operation returned status code: 0x%08x", retStatus);
         }
     }
+    CHK_LOG_ERR(RESET_INSTRUMENTED_ALLOCATORS());
     printf("[KVS Master] Cleanup done\n");
     return (INT32) retStatus;
 }
```

RESET_INSTRUMENTED_ALLOCATORS isnt reporting any leak when kvsWebrtcSampleMaster is shut down. If you want to reduce the memory footprint you can try reduce DEFAULT_ROLLING_BUFFER_DURATION_IN_SECONDS and DEFAULT_SEQ_NUM_BUFFER_SIZE in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/Rtp.h

**Comment by Nomidia** [comment]
Yes, I have added these codes. I use the same codes to run on Ubuntu and IoT device. These are debugging information.

1. When the device and Ubuntu are  running under the same network through the wired network. The memory only occurs on device as so far. I connect to the device twice, only the second time there was a memory leak.
[wired.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4739633/wired.log)

2. I switch the device's network to wireless. In this situation the fluency is lower than wired. It's easier to reproduce the issue.
[wireless.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4739664/wireless.log)

So I'm sure it is related to network quality. In addition, the device does not support non-4 byte alignment.

**Comment by chehefen** [comment]
Hi @Nomidia, I tried various things but I still cant reproduce the leak. Can you print a stack backtrace using https://man7.org/linux/man-pages//man3/backtrace_symbols.3.html inside 
- https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/InstrumentedAllocators.c#L177
- https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/InstrumentedAllocators.c#L103
- https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/InstrumentedAllocators.c#L129

I think printing 3 stacks should be enough.

**Comment by MushMal** [comment]
@Nomidia what's the commit you are using? We did fix a mem leak https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/93dbd03699b9eaaa9c173de888da7e0dd2f5daec

I am not sure whether alignment has anything to do with this though.

**Comment by Nomidia** [comment]
@MushMal The point you mentioned has been involved. I will use the latest version and add the stack backtrace to test.

**Comment by Nomidia** [comment]
@chehefen The device doesn't support backtrace. 
```
fatal error: execinfo.h: No such file or directory
```
I test the device and Ubuntu again at the same time. I can't reproduce it except on the device. I even limit the bandwidth of the Ubuntu. I think we should find other ways to analyse it.

platform:
Linux localhost 3.4.43-gk #3 PREEMPT Tue Mar 31 17:48:17 CST 2020 armv6l GNU/Linux

**Comment by MushMal** [comment]
@Nomidia sorry I am drawing blank here. It's puzzling why this would reproduce only on your device - not entirely sure yet. Just to confirm, on your device, are you using any special allocator? Are you using built-in system version of the open-source libraries that might operate differently (in either case I can't understand what could cause the leak).

Could I ask you perhaps to add instrumentation to the allocators to print out some info? If you look at PIC code https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/InstrumentedAllocators.c each of the entries has a DLOGS. DLOGS can be enabled by specifying LOG_STREAMING compile definition https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/common/include/com/amazonaws/kinesis/video/common/PlatformUtils.h#L92

You could either enable super verbose logging by defining LOG_STREAMING or you could modify DLOGSs in the InstrumentedAllocators.c to DLOGIs to get the output. Run the scenario to reproduce and we could see at least what's attempting to leak.

A better yet approach is to trace all of the allocation sites in RTP in WebRTC and add DLOGI before the allocation. You could at least see whether the free APIs are getting called or not,

Sorry if I am not much help but it's hard to debug without being able to reproduce this locally.

**Comment by Nomidia** [comment]
@MushMal Hi, I notice the struct PtpPacket has a member pRawPacket.
```
struct __RtpPacket {
    RtpPacketHeader header;
    PBYTE payload;
    UINT32 payloadLength;
    PBYTE pRawPacket;
    UINT32 rawPacketLength;
};
```
So I add printing here.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/43ede519ebd4fda0b17bc02bf5baab8dd2461da7/src/source/Rtp/RtpPacket.c#L76

```
    if((*ppRtpPacket)->pRawPacket != NULL)
        PRINTF("Possible rtpPacket mem leak (*ppRtpPacket)->pRawPacket = %u\n", (*ppRtpPacket)->rawPacketLength);
    SAFE_MEMFREE(*ppRtpPacket);

```
To reproduce the problem, I decrease the bandwidth . You can see the log like this "Possible rtpPacket mem leak (*ppRtpPacket)->pRawPacket = 1312".
Then I add all the numbers. 
1312 * 172 + 1124 + 267 + 14 + 70 + 14 + 596 + 14 + 741 + 14 +56 + 469 +14 = 229057.
The sum number is exactly the possible memory leak.

_resetInstrumentedAllocators(): Possible memory leak of size 229057_


[ReproduceMaster.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4786275/ReproduceMaster.log)
