### ISSUE TITLE
[QUESTION] gstreamer example not running

### ISSUE THREAD

**Issue by juanea** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#520]
I want to run the ./kvsWebrtcClientMasterGstSample and been able to see the live feed in https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html
with no success.
I am attaching the log file with this two flags:
AWS_KVS_LOG_LEVEL=4
GST_DEBUG=2
[2020-06-04_AWS_Webrtc_sdk_c.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4733135/2020-06-04_AWS_Webrtc_sdk_c.txt)

The sample ./kvsWebrtcClientMaster works with out any problem.

Thank you.

**Comment by disa6302** [comment]
@juanea , 

Can you include the details about where you are running gstreamer sample from? Is gstreamer using the system camera? 
Also, if you could, please attach logs with GST_DEBUG=4.

**Comment by juanea** [comment]
Thank you very much @disa6302,
I am trying to run this sample https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c
With my system camera. 

"Opened device 'Integrated Camera: Integrated C' (/dev/video0) successfully"

Here is the file with GST_DEBUG=4.
[2020-06-05_AWS_Webrtc_sdk_c.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4737481/2020-06-05_AWS_Webrtc_sdk_c.txt)

**Comment by disa6302** [comment]
@juanea , 

The reason it is probably not working is your viewer and gstreamer master sample are accessing the same underlying camera that is causing some resource contention. Try to run the sample with testsrc and run the viewer js to confirm the sample works:

`./kvsWebrtcClientMasterGstSample <channel-name> audio-video testsrc`

Let me know how it goes.

**Comment by juanea** [comment]
Thank you @disa6302 That worked.
![Screenshot from 2020-06-05 10-36-41](https://user-images.githubusercontent.com/9869942/83909667-1320de00-a71e-11ea-818d-eb7c4c8208cd.png)
So If I want to see my laptop camera direclty and see it in the console not the the javascript sample page what should I do?

Thank you.

**Comment by MushMal** [comment]
@juanea there is no single answer as it depends - on your hardware, your OS, your browser and the GStreamer implementation. I doubt that you will find good solution in this forum. Perhaps some GStreamer and your browser specific forums might be a better place.

The gist of the issue is that most hardware resources are not "sharable" at the higher layers in the OS.

**Comment by juanea** [comment]
Thank you @MushMal and @disa6302
