### ISSUE TITLE
[QUESTION] gstreamer through rtsp protocol

### ISSUE THREAD

**Issue by juanea** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#521]
I want to modify the gstreamer example https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c to be able to stream an ip camera throught rtsp.

I am able to see the camera feed with gstremer with this command launching it through terminal.
gst-launch-1.0 rtspsrc location=rtsp://ipaddress latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! videoscale ! video/x-raw,width=640,height=480 ! autovideosink

**Comment by chehefen** [comment]
you can refer to this sample: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c. You just need to modify the upstream plugins to consume from rtsp.

**Comment by juanea** [comment]
@chehefen Thank you for your reply.

Yes, I am modifying the upstream so that it consumes rtsp from that specifi file that you mention.
`pipeline = gst_parse_launch(
                    "rtspsrc location=rtsp://192.168.1.10:554/live1.sdp latency=0 ! rtph264depay ! h264parse ! avdec_h264 !"
                    "appsink sync=TRUE emit-signals=TRUE name=appsink-video audiotestsrc is-live=TRUE ! "
                    "queue leaky=2 max-size-buffers=400 ! audioconvert ! audioresample ! opusenc ! audio/x-opus,rate=48000,channels=2 ! appsink sync=TRUE emit-signals=TRUE name=appsink-audio",
                    &error);`

This pipeline works from me when I launch gstreamer from terminal.
`gst-launch-1.0 rtspsrc location=rtsp://192.168.1.X:554/live1.sdp latency=0 ! rtph264depay ! h264parse ! avdec_h264 ! autovideosink`
But when I try to use it inside the sample it does not stream to the signaling channel.
I am attaching my log.
[rtsp_kinesis_gstreamer.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4739021/rtsp_kinesis_gstreamer.txt)

Thank you

**Comment by suggestedfixes** [comment]
This one worked for us
```
rtspsrc location=url short-header=TRUE ! rtph264depay ! "
                 "video/"
                 "x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! "
                 "appsink sync=TRUE emit-signals=TRUE name=appsink-video";
```

**Comment by juanea** [comment]
Thank you @suggestedfixes I will take a look and see that works for me as well.

**Comment by chehefen** [comment]
you need to omit the avdec_h264, you dont need to decode it. the webrtc client is expecting h264 frames.

**Comment by juanea** [comment]
Thank you @chehefen 
I am still having the same problem. I connected a different camera and what @suggestedfixes suggested works perfectly.
But the camera that I need to use still has problems.
I am attaching the log.
[log_rtsp.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4755199/log_rtsp.txt)
Is there any specific setting that the camera should have?
This are the main errors I am getting.
`gst_rtp_bin_associate unable to sync to provided rtptime`
`gst_rtp_buffer_ext_timestamp Cannot unwrap, any wrapping took place yet. Returning 0 without updating extended timestamp.`
Thank you.

**Comment by MushMal** [comment]
It's hard to tell what might be wrong. Have you tried posting this question to GStreamer forums to get some help with regards to rtp? It really is not related to webrtc

**Comment by suggestedfixes** [comment]
- h264parse after h264depay and before the caps filter might be helpful.
- h264 has multiple profiles, so try one of the baseline profiles if your device supports it.

**Comment by MushMal** [comment]
I am going to resolve this issue. Please feel free to cut a new issue with more targeted details
