### ISSUE TITLE
[QUESTION] The support of curl

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#522]
A one liner description about the use case and what you are trying to achieve
The support of curl
** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 
Will this sdk support curl? 
** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by MushMal** [comment]
We don't have any support for libCurl in the embedded WebRTC. Could you please specify your use case and why the libWebSockets solution will not work for you?

The main difficulty with libCurl is that we will still need to use libWebSockets as the communication requires web sockets.

**Comment by ycyang1229** [comment]
Hey, thanks for @chehefen, and he explained the processes of signaling channel for me. For my experience, some embedded device has the libcurl already, but does not have libwebsocket. So I am seeking the possibility of using libcurl excluding libwebsocket.

So I summarized the information for some people who may need. Please correct me if I am wrong. Thanks.

For these APIs, we can use either https or websocket to create/describe the signaling channel.
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_Operations_Amazon_Kinesis_Video_Streams.html
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_Operations_Amazon_Kinesis_Video_Signaling_Channels.html

For the following connection between server and devices, we need to use websocket.
https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-websocket-apis.html
