### ISSUE TITLE
[QUESTION] the length of pChannelName and pChannelArn @createValidateChannelInfo

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#523]
A one liner description about the use case and what you are trying to achieve
the length of pChannelName and pChannelArn @createValidateChannelInfo

** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 

Does the line#121 need to use strncpy since sdk already truncates the channel name at line#21 by using strnlen? 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/ChannelInfo.c#L121

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/ChannelInfo.c#L21

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by MushMal** [comment]
No, it can actually use 

MEMCPY(pCurPtr, pOrigChannelInfo->pChannelName, nameLen * SIZEOF(CHAR));

This said, there is not going to be any performance gains at all. Especially, since this is not a "hot" path.

Can I ask whether this is perf related or any correctness related?

**Comment by MushMal** [comment]
Oh, one more thing. Just realized that this is actually STRCPY and not STRNCPY which will operate at almost the same speed as MEMCPY

**Comment by ycyang1229** [comment]
They are good! Basically, they are the same thing, so I just want to know which one is the preference in this sdk.
