### ISSUE TITLE
ERROR   turnConnectionStepState(): operation returned status code: 0x5a000020

### ISSUE THREAD

**Issue by mdonahoe** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#526]
I'm using an LTE modem on my master device. I see this error on my master when a client tries to connect using TURN

```
2020-06-06 00:56:58 WARN    iceAgentSendPacket(): No valid ice candidate pair available to send data
2020-06-06 00:56:58 WARN    socketConnectionIsConnected(): socket connection check failed with errno Operation already in progress
[... snip repeats ...]
2020-06-06 00:57:00 WARN    socketConnectionIsConnected(): socket connection check failed with errno Operation already in progress
2020-06-06 00:57:00 ERROR   turnConnectionStepState(): operation returned status code: 0x5a000020
2020-06-06 00:57:00 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CHECK_SOCKET_CONNECTION to TURN_STATE_FAILED
2020-06-06 00:57:00 ERROR   turnConnectionTimerCallback(): operation returned status code: 0x5a000020
2020-06-06 00:57:00 ERROR   timerQueueExecutor(): operation returned status code: 0x5a000020
2020-06-06 00:57:00 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x5a000020
2020-06-06 00:57:00 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_FAILED to TURN_STATE_CLEAN_UP
```

Any ideas for how to investigate this?

Related, has there been any progress made on supported UDP-based TURN?

Thanks!

**Comment by chehefen** [comment]
the latest master uses UDP-based TURN by default. Log shows that you cant make tcp connection for some reason.

**Comment by mdonahoe** [comment]
Ok, I'll try master. I'd prefer UDP anyway.

Weirdly, I am able to create TCP connection for the signaling to work, so I am a little confused why this TCP connection would fail when that one did not.

**Comment by mdonahoe** [comment]
As an update, this is still not working right, despite getting the latest build with UDP TURN support.

I am testing four different setups for my "Master".
1. Ubuntu desktop with wired ethernet
2. Nvidia TX2 with wired ethernet
3. Ubuntu desktop with LTE modem
4. Nvidia TX2 with LTE modem

In all four cases, my WebRTC "Client" is a macbook on wifi using the KVS WebRTC test webpage in Chrome. The client is set to "TURN only" via the checkbox.

Good news: Both computers work great with TURN over **wired internet**
Bad news: Neither computer works well with my **LTE** modem, and they fail differently.

Symptoms:
* On the TX2 with an LTE modem as master, the TURN connection fails due to the 5 second timeout on the GET_CREDENTIALS step. No messages are ever exchanged with the client.
* The Ubuntu desktop with same LTE modem hardware does not timeout and is able to receive datachannel messages from the client, but the client just never gets any messages (video or data) from the desktop.


Any ideas how to debug this? I'm worried packets are being dropped by the LTE modem, but I am perplexed by the different behavior seen by the TX2 vs my desktop. I was thinking I could maybe host my own TURN server and monitor the traffic myself, but I'm not sure how to use a custom turn url with this library.

**Comment by MushMal** [comment]
Seems that the networking is the main issue here. Could you run some network-level troubleshooting using some online tools to guarantee you have proper network with the LTE? There is a case with LTE reported by a customer - perhaps unrelated: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/447

**Comment by mdonahoe** [comment]
Thanks for that case reference. His errors look different than mine, but the notion of "mobile terminated data" is interesting.

Do you have any recommended online-based tools? I feel like that's my best bet at tracking down packet drops that happen on the LTE network.

While using the modem, I am able to:
* ping google.com
* connect to the KVS signaling service
* use ssh
* send and receive UDP packets from a public UDP echo server

Currently I'm trying to use tcpdump to record network packets and then compare the different setups.

But I am concerned I won't be able to see packet drops that happen over LTE if I am just recording local traffic.

Is it possible to change TURN urls? I really want to man-in-the-middle the traffic using an online server. That way I can see what is actually arriving.

**Comment by chehefen** [comment]
> As an update, this is still not working right, despite getting the latest build with UDP TURN support.
> 
> I am testing four different setups for my "Master".
> 
> 1. Ubuntu desktop with wired ethernet
> 2. Nvidia TX2 with wired ethernet
> 3. Ubuntu desktop with LTE modem
> 4. Nvidia TX2 with LTE modem
> 
> In all four cases, my WebRTC "Client" is a macbook on wifi using the KVS WebRTC test webpage in Chrome. The client is set to "TURN only" via the checkbox.
> 
> Good news: Both computers work great with TURN over **wired internet**
> Bad news: Neither computer works well with my **LTE** modem, and they fail differently.
> 
> Symptoms:
> 
> * On the TX2 with an LTE modem as master, the TURN connection fails due to the 5 second timeout on the GET_CREDENTIALS step. No messages are ever exchanged with the client.
> * The Ubuntu desktop with same LTE modem hardware does not timeout and is able to receive datachannel messages from the client, but the client just never gets any messages (video or data) from the desktop.
> 
> Any ideas how to debug this? I'm worried packets are being dropped by the LTE modem, but I am perplexed by the different behavior seen by the TX2 vs my desktop. I was thinking I could maybe host my own TURN server and monitor the traffic myself, but I'm not sure how to use a custom turn url with this library.

on your XT2, run https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/discoverNatBehavior.c and see what says.

On your Ubuntu desktop, check what's the MTU of your network interface. By default we use 1300. you can configure it here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L946

**Comment by mdonahoe** [comment]
I ran the discoverNatBehavior on my desktop, and got the following.

```
build$ ./discoverNatBehavior 
Usage: ./discoverNatBehavior -i network-interface-name -s stun-hostname
Using stun host: stun:stun.sipgate.net:3478, local network interface (null).
2020-06-20 01:49:19 WARN    createSocket(): setsockopt() failed with errno Protocol not available
2020-06-20 01:49:19 DEBUG   discoverNatBehavior(): Start NAT mapping behavior test.
2020-06-20 01:49:19 DEBUG   discoverNatMappingBehavior(): Running mapping behavior test I. Send binding request
2020-06-20 01:49:22 DEBUG   socketConnectionClosed(): Close socket 5
Detected NAT mapping behavior NO_UDP_CONNECTIVITY
Host does not have any UDP connectivity. STUN is not usable. Can only connect using TCP relay
Detected NAT filtering behavior NO_UDP_CONNECTIVITY
Host does not have any UDP connectivity. STUN is not usable. Can only connect using TCP relay
```

`Can only connect using TCP relay` seems suspicious. Does that really mean that UDP TURN won't work?

**Comment by chehefen** [comment]
> I ran the discoverNatBehavior on my desktop, and got the following.
> 
> ```
> build$ ./discoverNatBehavior 
> Usage: ./discoverNatBehavior -i network-interface-name -s stun-hostname
> Using stun host: stun:stun.sipgate.net:3478, local network interface (null).
> 2020-06-20 01:49:19 WARN    createSocket(): setsockopt() failed with errno Protocol not available
> 2020-06-20 01:49:19 DEBUG   discoverNatBehavior(): Start NAT mapping behavior test.
> 2020-06-20 01:49:19 DEBUG   discoverNatMappingBehavior(): Running mapping behavior test I. Send binding request
> 2020-06-20 01:49:22 DEBUG   socketConnectionClosed(): Close socket 5
> Detected NAT mapping behavior NO_UDP_CONNECTIVITY
> Host does not have any UDP connectivity. STUN is not usable. Can only connect using TCP relay
> Detected NAT filtering behavior NO_UDP_CONNECTIVITY
> Host does not have any UDP connectivity. STUN is not usable. Can only connect using TCP relay
> ```
> 
> `Can only connect using TCP relay` seems suspicious. Does that really mean that UDP TURN won't work?

yes, that means your NAT drops UDP packets.

**Comment by chehefen** [comment]
I see that you didnt pass a local interface for the NAT behavior discovery "local network interface (null)". It may have chosen one that has no connectivity. can you pass a interface to it with the -i option?

**Comment by MushMal** [comment]
Updates?

**Comment by disa6302** [comment]
@mdonahoe , 

The issue seems to have gone stale. Feel free to open a new issue or re-open this if needed. Thanks!

**Comment by mdonahoe** [comment]
I updated to latest master, then re-ran discoverNatBehavior on my TX2 with `-i eth0`, and the results seem to be better.

```./discoverNatBehavior -i eth0
Usage: ./discoverNatBehavior -i network-interface-name -s stun-hostname
Using stun host: stun:stun.sipgate.net:3478, local network interface eth0.
2020-07-14 00:37:02 WARN    createSocket(): setsockopt() failed with errno Protocol not available
2020-07-14 00:37:02 DEBUG   discoverNatBehavior(): Start NAT mapping behavior test.
2020-07-14 00:37:02 DEBUG   discoverNatMappingBehavior(): Running mapping behavior test I. Send binding request
2020-07-14 00:37:02 DEBUG   discoverNatMappingBehavior(): Running mapping behavior test II. Send binding request to alternate address but primary port
2020-07-14 00:37:02 DEBUG   socketConnectionClosed(): Close socket 5
2020-07-14 00:37:03 WARN    createSocket(): setsockopt() failed with errno Protocol not available
2020-07-14 00:37:03 DEBUG   discoverNatBehavior(): Start NAT filtering behavior test.
2020-07-14 00:37:03 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test I. Send binding request
2020-07-14 00:37:04 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test II. Send binding request with change ip and change port flag
2020-07-14 00:37:06 DEBUG   discoverNatFilteringBehavior(): Running filtering behavior test III. Send binding request with change port flag
2020-07-14 00:37:08 DEBUG   socketConnectionClosed(): Close socket 5
Detected NAT mapping behavior ENDPOINT_INDEPENDENT
Host's NAT uses same public IP address regardless of destination address. STUN is usable.
Detected NAT filtering behavior PORT_DEPENDENT
Host's NAT allows to receive UDP packet from external address and port that host had previously sent data to. STUN is usable.
```

I also got the kvsWebrtcClientMaster example working by using the `iceSetInterfaceFilterFunc` option.

```
diff --git a/samples/Common.c b/samples/Common.c
index 5f31449..f24abf9 100644
--- a/samples/Common.c
+++ b/samples/Common.c
@@ -3,6 +3,15 @@
 
 PSampleConfiguration gSampleConfiguration = NULL;
 
+BOOL interfaceFilterFunc(UINT64 custom, PCHAR interface) {
+  BOOL result = FALSE;
+  if (strncmp(interface, "eth0", 4) == 0) {
+    result = TRUE;
+  }
+  DLOGI("filtering interface %s = %i\n", interface, result);
+  return result;
+}
+
 VOID sigintHandler(INT32 sigNum)
 {
     UNUSED_PARAM(sigNum);
@@ -328,7 +337,7 @@ STATUS initializePeerConnection(PSampleConfiguration pSampleConfiguration, PRtcP
     MEMSET(&configuration, 0x00, SIZEOF(RtcConfiguration));
 
     // Set this to custom callback to enable filtering of interfaces
-    configuration.kvsRtcConfiguration.iceSetInterfaceFilterFunc = NULL;
+    configuration.kvsRtcConfiguration.iceSetInterfaceFilterFunc = interfaceFilterFunc;
 
     // Set the  STUN server
     SNPRINTF(configuration.iceServers[0].urls, MAX_ICE_CONFIG_URI_LEN, KINESIS_VIDEO_STUN_URL, pSampleConfiguration->channelInfo.pRegion);
```

Thanks!
