### ISSUE TITLE
[Deleting an existing Signaling Channel & rerunning the Sample code on device gives error ]

### ISSUE THREAD

**Issue by getash** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#529]
**Describe the bug**
Deleting an existing signaling channel on the AWS Management Console - Kinesis Video stream & running the modified kvsWebRTCClientMasterGstreamerSample.c (changed in order to accept video source as an input & it compiles/works fine)

**SDK version number**
master Latest

**To Reproduce**
1. Run ./kvsWebRTCClientMasterGstreamerSample test-channel
2. Goto AWS Management Console, Kinesis Signaling Channel &  view the media playback - able to see the live video (or test source depending on the input)
3. Go back to Signaling Channel & delete the "test-channel"
4. Go back to the console on the device - exit out of the ./kvsWebRTCClientMasterGstreamerSample
5. Run the ./kvsWebRTCClientMasterGstreamerSample test-channel 
6. Errors out with - [2020/06/08 10:43:51:1462] W: lws_client_handshake: got bad HTTP response '404'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Ubuntu OS

Edge Device is NVidia Jetson TX2
Viewer on the Mac with the Chrome as the browser

**Comment by MushMal** [comment]
@getash could you please include the debug logs?

The correct behavior of the signaling client is to check if the channel exists (issuing DescribeChannel) call and if it's not then attempt to re-create it. 

It's OK to get 404 - this is the normal negative path.

NOTE: The SDK/Signaling client does return status codes for machining.
NOTE: The DELETE operation is not 'prompt' - it's actually asynchronous on the console and it takes a moment for the channel to actually be fully deleted. There is a chance that the master will fail to "detect" that the channel is deleted and will proceed forward to only fail at the later states. In this case, the state machine would loop back to proper state (likely Describe Channel) and if the channel is deleted then it should be recreated.

**Comment by getash** [comment]
@MushMal I retried this with providing more time before I initiated creation of a new channel. That worked. Thanks for the clarification. I shall close this issue.
