### ISSUE TITLE
release 1.1.1?

### ISSUE THREAD

**Issue by zhuker** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#530]
feels like this commit  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/3a083735266214286f4cc90c6ab5b2b7412e51ee is worth a micro release

**Comment by MushMal** [comment]
Yes indeed. We were going to cut a Revision release but thought to accumulate into a minor release as there has been a bunch of new changes. Please stay tuned

**Comment by zhuker** [comment]
it would also be cool to include `amazon-kinesis-video-streams-pic` and `amazon-kinesis-video-streams-producer-c` with the release vs downloading separately
a little less pain to bazelize the new version
please please

**Comment by MushMal** [comment]
That's the idea indeed

**Comment by zhuker** [comment]
@MushMal can you give me an ETA? i either wait for you guys or use a master commit

**Comment by MushMal** [comment]
It’s hard to come up with an ETA due to few factors. We are targeting this week.

Can you please provide some information about what your intent is. Are you building a device firmware and need to lock down the date? It’s ok to reply to Kinesis-video-support@amazon.com - just will be easier to help and support you.

**Comment by zhuker** [comment]
this week works for me! thanks
> building a device firmware
i am under NDA, sorry :/

**Comment by disa6302** [comment]
@zhuker , 

New release is up. You can check out v1.2.0 now. Thank you for your patience. 

I am closing this ticket now. Feel free to open a new issue if you have any questions.
