### ISSUE TITLE
[FEATURE] gstreamer sink and source component

### ISSUE THREAD

**Issue by mateuszboryn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#532]
Dear developers,

There is an example `kvsWebRTCClientMasterGstreamerSample.c` which sets up a fixed gstreamer pipeline that is created in C code.
However there are no gstreamer components built, that could be used in a custom pipeline out of the box (using shell command gst-launch-1.0).

What I would expect is to have a sink and as source component(s) for gstreamer that could be used in custom pipelines. Something similar to this: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/src/gstreamer/gstkvssink.cpp

The gstreamer component could have:

- input pad for video h264 frames (in case of Master mode, for Viewer mode it should be optional pad)
- input pad for audio frames (in case of Master mode, for Viewer mode it should be optional pad)
- input pad for data channel messages
- output pad for data channel messages
- output pad for video h264 frames (in case of Viewer mode, for Master mode it should be optional pad)
- output pad for audio frames (in case of Viewer mode, for Master mode it should be optional pad)
 

Maybe it is possible to have only one gstreamer component that has a parameter selecting Master or Viewer mode.
Also other parameters regarding IoT authentication are needed, just like in gstkvssink.cpp.

Cheers,

Mateusz

**Comment by MushMal** [comment]
Thanks for opening this feature request. We are looking at this and trying to analyze the customer demand in order to assess the prioritization.

Could you please describe your use case and add some info why a custom built application won’t be able to handle your needs similar to the samples we publish?

Of course, aside from general usefulness of the plugin.

**Comment by mateuszboryn** [comment]
Use case requires a component for well-known and media standardized streaming framework. 

Platform-dependent video encoder is a must (for example in Raspberry PI using h264enc is CPU consuming, while omxh264enc is the recommended way for video encoding).

Tuning codec parameters is needed.

User defined algorithms for media processing should integrate well and easily with webrtc and IoT. Hardcoding a gst pipeline in the application makes it difficult for users to tune codec parameters and bind it to custom algorithms.

I recognize gstreamer as promising framework for such requirements.

**Comment by MushMal** [comment]
Understood. To refine though, if you are building a particular device, you would actually hard-code the pipeline and use a custom application instead of a plugin.

What's the primary cause in your case to request a plugin?

**Comment by MushMal** [comment]
I am going to resolve this for now. GStreamer plugin might be a good idea for platform bringup/quick checking. We will be adding a new "enhancement" issue  if/when we proceed with the plugin
