### ISSUE TITLE
[QUESTION] failure in connectSignalingChannelLws()

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#534]
On one of our platforms, signaling channel client initialization gets stuck in the while loop of this line, and eventually returns error code 0x0000000f.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/acc94940a715ac5dec8f20cf5e51b65607e09e43/src/source/Signaling/LwsApiCalls.c#L1265
The problem doesn't happen every time.  There is 50% chance to see it.  The other 50% chance is OK.
On the other platform we are using, the same code runs always without a glitch.

Question:  What cause the error?

**Comment by MushMal** [comment]
@zwei333 the definition of this particular status code is here: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h#L457

You need to provide debug logs in order to understand why the connect is timing out.

Also, it might help to build debug version of the libWebSockets by uncommenting https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/CMake/Dependencies/libwebsockets-CMakeLists.txt#L36 and deleting libWebSockets library to get it rebuilt.

**Comment by MushMal** [comment]
Resolving as stale. Please reopen or cut a new issue with details and try the suggestions in the body of the issue

**Comment by zwei333** [comment]
Confirmed that the issue is not related to kvs-sdk.  Please see the following notes

Most urls in the process of connecting to the signaling channel have three ip addresses. libwebsockets will pick one of three to create connection (the one picked could be different each time connecting to signalling channel)
So each time libwesockets tries to connect to four servers out of the following list.  ( For the case of using IoT credentialing)

./sock_connect 52.6.219.120
./sock_connect 34.196.121.248
./sock_connect 34.201.197.68
./sock_connect 34.236.195.233
./sock_connect 52.0.79.75
./sock_connect 52.87.83.232
./sock_connect 52.202.150.99
./sock_connect 34.234.255.182
./sock_connect 54.145.78.223
./sock_connect 52.86.93.106
./sock_connect 3.208.126.161
./sock_connect 52.207.97.66
./sock_connect 3.212.157.179

The problem is, at each boot, our battery camera has difficulty in connecting to one or several servers in the list (occasionally, camera could have smooth connections with all servers but the chance is low).

The un-connectable servers are random at each boot, but are consistent before reboot. i.e. if camera is booted, and can’t connect to 52.6.219.120, it always fails to connect to 52.6.219.120, until reboot. Next time booted, connecting to 52.6.219.120 could be OK, but then connecting to 34.196.121.248 could be failing consistently.

If webrtc/KVS-SDK/libwebsockets happens to use the problematic server, then webrtc will times out and quit. If one url has multiple server ips, then each time running webrtc, a server will be picked randomly. So webrtc can eventually connect to signaling channel after multiple retries even without reboot.

From host linux machine I can confirm all of these servers are fine, and I don’t have firewall issue in my local network. The problem is on the camera.

I can run a simple program (with zero webrtc/KVS-SDK/libwebsockets code) to reproduce the issue.

**Comment by MushMal** [comment]
Not sure what you mean by different IPs. What you see is the actual host IPs given out by the load balancers. Those have certain algorithms to distribute but you can assume they are random and they can change without any notice. The load balancers will kick out "bad" hosts out of rotation on health check.

**Comment by zwei333** [comment]
Yes, those three ips are from the load balancers.  There is a problem with our new platform that some ips can't be connected from our board randomly at each boot.  It is the root cause of this issue.  The os team from our partner is taking over the issue.  We are all set here.  Thanks!
