### ISSUE TITLE
CMakeLists.txt references several variables that do not exist anymore

### ISSUE THREAD

**Issue by rossyeager** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#535]
Just a quick glance at the `CMakeLists.txt` file after updating to latest master. I have an install step that I have added in my local copy with older versions of the library that referenced the following variables `KINESIS_VIDEO_PIC_SRC` and `KINESIS_VIDEO_PRODUCER_C_SRC`. These don't seem to be set in the latest `master`. The are referenced here:

`file(GLOB PIC_HEADERS "${KINESIS_VIDEO_PIC_SRC}/src/*/include")`
`include_directories(${KINESIS_VIDEO_PRODUCER_C_SRC}/src/include)`

These are added but reference empty variables now and it seems like now the submodules that they reference no longer exist? Is this correct? If so, these stale variables should be removed.

**Comment by disa6302** [comment]
@rossyeager , 

Thanks for pointing it out, will have a PR out to remove this soon!

**Comment by MushMal** [comment]
@rossyeager you are correct - these should be cleaned up.

We have moved from directly submoduling the related projects to using them as a separate open source project with their own INSTALL command to get the public headers into the installation root.

We would love any contributions though :)

**Comment by disa6302** [comment]
@rossyeager , 

This is fixed.
