### ISSUE TITLE
Missing libsrtp2 pc file [BUG]

### ISSUE THREAD

**Issue by rossyeager** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#538]
**Describe the bug**
Latest master does not create a package config file for libsrtp2 but includes it as a library

**SDK version number**
commit: acc94940a715ac5dec8f20cf5e51b65607e09e43

**Open source building**

I am building the repository and creating a deb package for installation in our build system. When I install the libraries, dependencies, and created pc files, I am missing the srtp2 pc file. When I manually add in the pc file from previous older versions of webrtc, it works fine. This pc file used to be included in older versions of webrtc.

**To Reproduce**
Build the repository, look in `open-source/lib/pkgconfig`. There are config files for all the other created libraries except `libsrtp2`

**Expected behavior**
Need a `libsrtp2.pc` in `open-source/lib/pkgconfig`:

```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libsrtp2
Version: 2.2.0
Description: Library for SRTP (Secure Realtime Transport Protocol)

Libs: -L${libdir} -lsrtp2 -lcrypto -ldl -pthread 
Cflags: -I${includedir}
```

**Comment by disa6302** [comment]
@rossyeager , 

Perhaps @Sean-Der will have some context.

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/549

**Comment by hassanctech** [comment]
We've encountered some failures and it looks like this is going to involve some more work to get right.  No ETA yet.
