### ISSUE TITLE
[BUG] Stucked in createLwsIotCredentialProvider()

### ISSUE THREAD

**Issue by hsinghaowang** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#540]
**Describe the bug**
sometimes it get stucked in createLwsIotCredentialProvider() for a long time (7minutes)

**SDK version number**
git commit: dbf484bae22f8d597edc61e047b46726f4664b46

**To Reproduce**
1. setup Iot Credential variables
2. call createSampleConfiguration(), it will call createLwsIotCredentialProvider()

**Expected behavior**
createLwsIotCredentialProvider() should return in a short time.

**Additional context**
 - OS: [ARM Linux 3.3 with 128MB RAM  600MHz CPU]

**Comment by MushMal** [comment]
@hsinghaowang which asset you are using and whether you have any modifications?

I am not sure what's causing the call to be "stuck" as there are timeouts implemented in place but those should be a lot shorter than 7 mins. Can you run the debug build under the debugger to see where the threads are blocked? What happens after 7 minutes? Does this come back with an error? Do you have verbose logs? Can you build debug libWebSockets?

Generally, issues like livelocks or deadlocks are impossible to debug if we can't reproduce this so we will be asking you for help debugging this.

**Comment by hsinghaowang** [comment]
It happened in our program which using WebRTC C SDK. So it might be our problems. But I put logs before and after createLwsIotCredentialProvider()...
After 7 mins, it continues as usual, works fine.

PS. If we replace createLwsIotCredentialProvider() with createStaticCredentialProvider(), it never stucked (for now)

**Comment by MushMal** [comment]
The logic of the IoT credential provider is rather simple. As the credential provider could be "asked" by the lower-layers to get credentials, we do cache the credentials until it expires minus a certain grace period. If, however, the cache is invalidated, it will actually make the real call. Here, we use the IoT certificate, the endpoint and the private key to make the call using LibWebSockets (for webRTC). It actually has it's own independent LWS loop implementation which is a blocking call with a timeout which is defined as 5 seconds: 

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/source/Common/Lws/LwsCall.c#L33

I really can't understand what could cause a 7 minute blocking and whether it is blocking.

Here is my recommendation:

1) Build debug version of libWebSockets by deleting the libWebSockets.so and uncommenting https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/CMake/Dependencies/libwebsockets-CMakeLists.txt#L36 - same in the WebRTC project to make sure what whichever project builds the libWebSockets, it builds the debug version
2) Add LLL_DEBUG to https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/source/Common/Lws/LwsCall.c#L113 to get LWS debug info
3) Add more instrumentation to your code to understand what's actually blocking. If you do printfs before and after main entry points. 

Also, perhaps I am not understanding but it's the actual creating of the credential provider that gets "stuck" for 7 minutes? How about afterwards? IoT credentials expire in about an hour (most cases) so does the IoT credential provider update the credentials in that case just fine? If so, there might be something wrong with the startup sequence or boot sequence on your device? How's your network stack gets started? Do you have an NTP time? Is the application starting as a daemon? Can you pause the application start until the device is fully booted, the drivers are loaded and the time sync has happened? 

Sorry but I am just adding some brainstorming notes here to help you get more information so we can get some resolution to this,.

**Comment by hsinghaowang** [comment]
Thanks for your ideas and your time.
It looks like about booting sequence. Restart the application later seems fixed it. Need more tests.

**Comment by hsinghaowang** [comment]
Restart the applicaion later doesn't fix the problem.
The problem happens more often with WiFi than cable.
We have make sure NTP is ready and CPU is not busy.

PS. I disabled cache, because the default output filesystem is ready only. Can I specify another place to store the cache?
```
    pSampleConfiguration->channelInfo.cachingPolicy = SIGNALING_API_CALL_CACHE_TYPE_NONE;
    pSampleConfiguration->channelInfo.cachingPeriod = SIGNALING_API_CALL_CACHE_TTL_SENTINEL_VALUE;
```

**Comment by MushMal** [comment]
First thing. You can change the file location by modifying https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/FileCache.h#L15

Regarding the hung. We will need you to debug your code a little and give a little more information including:

* Which asset you are trying to test - assuming master sample with NO modification but using IoT credential provider. If there is custom code involved, we would ask you to try the master sample application with as little modification as possible.
* Run with debug or verbose logs enabled and copy the logs
* Run under the debugger and as you get the "hung" reproduced, please pause the debugger and get the debug stack traces for all of the threads.


Update the issue as you discover this information. As is, this is not actionable

**Comment by hsinghaowang** [comment]
Thanks. It is solved.
The problem has something to do with random number generation in our platform.
