### ISSUE TITLE
[QUESTION] How long can we cache signalling endpoints for?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#545]
We wanted to specify an expire time for signaling endpoints we cached on front end beyond which we know for sure has expired. So how often do HTTPS and WSS endpoints change?
We looked here and couldn't find anything
https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-limits.html
But from docs on kvs stream, it says 45 minutes for GetDataEndpoints, so I assume similar time frame?
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/limits.html

**Comment by MushMal** [comment]
@suggestedfixes the links you've been looking at are irrelevant to this conversation. The second link is the max session time in streams that's enforced by the backend, though, the SDK handles graceful session stitching. This is not relevant to WebRTC.

For WebRTC we do not publish any validity times. This is highly dependent on the system. At times, we take the backend instances out for servicing or deprecate them.

Currently, the default caching period is specified as 10 hours:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/c2b0137d25f260e4f31eef7ad758731a540367a0/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L603

You could, however, specify your own value - for example 24 hours.

The Signaling client when failing the call, will result in the right state transition to re-acquire the fresh values and update the cache.

Please let us know whether you have any further questions. Please resolve this if you when done

**Comment by suggestedfixes** [comment]
Got it I will cache for 10 hours on the front end.
