### ISSUE TITLE
[QUESTION] How to stream video from this client into KVS for analytics

### ISSUE THREAD

**Issue by ajhool** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#550]
We would like to process WebRTC conference calls using AWS KVS (analytics) and are hoping to (1) use AWS KVS WebRTC to act as the signaling server; (2) use this client to receive all of the WebRTC streams; and (3) forward all of those streams to the AWS KVS (analytics) service for doing real-time video/audio processing in AWS Lambda.

** Any design considerations/constraints **
Ideally, this SDK could be deployed in a headless, autoscaling fashion (eg. lambda or fargate). The input would be a webrtc room id (hosted by AWS KVS WebRTC) and this client would connect to the WebRTC room. Then, this client would forward all information into AWS KVS (analytics) .

Note: The distinction between AWS KVS WebRTC and "ordinary" KVS is a little confusing. I understand that the KVS WebRTC service is just an autoscaling signaling server for WebRTC, while "ordinary" KVS or KVS (analytics) is for processing video streams. Ideally, we could use the KVS WebRTC server as a media server that automatically forwards client feeds into KVS (analytics), but that does not seem to be possible. Thus, we would need a this headless webrtc client (or another headless client) to receive audio/video and forward it to KVS (analytics).

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by MushMal** [comment]
Understand the scenario. Currently, we don't support persistence (aka the KVS ingestion) for WebRTC but you noted it right, it's possible to have one of the clients (say a master) to act as a dual-streaming mode. We had an older PR to do this: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/191

In this sample, we have dual stream - one for the master WebRTC peer and the other for KVS.

You can implement something similar to this.

Note: Lambda has time limits for the execution. Perhaps a Fargate instance might be a better option.

**Comment by MushMal** [comment]
Resolving as answered.
