### ISSUE TITLE
[QUESTION] the compile option of libwebsocket

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#554]
A one liner description about the use case and what you are trying to achieve
the compile option of libwebsocket.

** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 

Recently, I am working on porting this sdk on non-linux based RTOS. 
For libwebsocket, I am trying to disable the compile options of libwebsocket as much as I can in order to lessen the effort of porting, since this sdk is the only one uses libwebsocket on this platform right now.
So I have one question, is it all the compile option or all the feature inside libwebsocket necessary for this sdk? In other word, what is necessary feature set of libwebsocket for this sdk? 

For example, I disabled two compile options as below in libwebsocket, and the sample code of master role still worked well.

if (LWS_WITH_ESP32)
option(LWS_WITH_DIR "Directory scanning api support" OFF)
option(LWS_WITH_LEJP_CONF "With LEJP configuration parser as used by lwsws" OFF)
else()
option(LWS_WITH_DIR "Directory scanning api support" ON)
option(LWS_WITH_LEJP_CONF "With LEJP configuration parser as used by lwsws" ON)
endif()

Thanks.

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by MushMal** [comment]
I am not even familiar with these. I would love to see the footprint to be smaller by removing any of the dependencies we are not actually using. My advise is this - if the sample works fine - submit a PR and we will get this pushed in. We will also run the unit/integ tests as part of TravisCI run (needs to run under our own account) to validate this further.

**Comment by ycyang1229** [comment]
Thanks for your reply.
