### ISSUE TITLE
[QUESTION]How can I using iot credential

### ISSUE THREAD

**Issue by lory17** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#555]
I have replace createSampleConfiguration by createLwsIotCredentialProvider like this:
`CHK_STATUS(createLwsIotCredentialProvider(
        "c3hfsep1hhoyce.credentials.iot.ap-northeast-1.amazonaws.com",
        "./certs/iot-cert/certificate.pem",
        "./certs/iot-cert/private.pem.key",
        "./certs/iot-cert/cacert.pem",
        "KvsCameraIoTRoleAlias01",
        channelName,
        &pSampleConfiguration->pCredentialProvider));`
I can get accessKeyId secretAccessKey and sessionToken. but can get ICE Server info. 
I found SSL error in log:
[2020/06/17 15:28:31:2275] E: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=3)
 
This is my log file:
[kvsWebrtcClientMaster_iot.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4791422/kvsWebrtcClientMaster_iot.txt)

Can you give me some advise to solve this problem? Thanks

**Comment by MushMal** [comment]
Looks like the ca cert is not found/not specified. You can specify the ca cert via an env var: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/ae7462f38d71823d87ed284013e2ea976b48011a/samples/Common.c#L589

or use the default path but make sure you point to https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/master/certs

**Comment by lory17** [comment]
Hi @MushMal
Thanks for your advise !
I removed  lookForSslCert step, before call createLwsIotCredentialProvider. that casue the problem!
