### ISSUE TITLE
[QUESTION] Unable to stream video from adroid to Ubuntu 16.04

### ISSUE THREAD

**Issue by taufeeq25** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#558]
Hello,

I am trying to test KVS webrtc sdk on Ubuntu 16.04 and Raspberry pi. 
Raspberry pi=>  

i am able to stream audio and video to Android, but i am unable to stream video from Android to Raspberry pi or Ubuntu.

Sometimes i am able to get audio from android to raspberry pi/ubuntu but its not stable.

i was going through example code(samples/kvsWebRTCClientMasterGstreamerSample.c) but looks like video is not wired up with gstreamer as mentioned in comment. I am really new to Gstreamer and don't know how to wired up video with gstreamer pipeline for playing.

If it is wired up with gstreamer pipeline then what possible reason could cause this problem? If not, let me know how to wired up video with gstreamer.

 ****//TODO: Wire video up with gstreamer pipeline****

    switch (pSampleStreamingSession->pAudioRtcRtpTransceiver->receiver.track.codec) {
        case RTC_CODEC_OPUS:
            audioDescription = "appsrc name=appsrc-audio ! opusparse ! decodebin ! autoaudiosink";
            break;

        case RTC_CODEC_MULAW:
        case RTC_CODEC_ALAW:
            audioDescription = "appsrc name=appsrc-audio ! rawaudioparse ! decodebin ! autoaudiosink";
            break;
        default:
            break;
    }
Thank you.

**Comment by MushMal** [comment]
@taufeeq25 I believe you report a couple of issues if I am not mistaken. I will address the C WebRTC SDK specifics. The sample is indeed not wired up for the audio. We are trying to keep a balance between the readability and feature completeness of the samples. We will be looking at adding a more involved sample at some stage to another repository for samples. But, for now, there are no immediate plans to add this.

**Comment by disa6302** [comment]
@taufeeq25 , 

This issue seems to have gone stale. Closing it. Feel free to open a new issue if you face any problems!
