### ISSUE TITLE
[QUESTION] The support of IPv6

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#561]
A one liner description about the use case and what you are trying to achieve
The support of IPv6

** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 
The readme said the support of ipv6 is todo, but some pull req. said this sdk has the support of ipv6. So I am a little confused. Does this sdk already supports the ipv6? Or some functionalities are on-going? 
thanks,

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/417
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/382

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by MushMal** [comment]
Clients do support IPv6 with these changes. However, our backend TURN and STUN do not. The Readme should be updated perhaps to reflect the latest greatest on this. Resolving. Please feel free to reopen

**Comment by ycyang1229** [comment]
@MushMal  I have one more question about ipv6. I checked the libwebsocket, and there is one compile option for ipv6. But I did not see this sdk enables the option in libwebsocket. 
https://github.com/warmcat/libwebsockets/blob/master/CMakeLists.txt#L93
Is this option necessary for webrtc? 
Btw, just curious, will the backend add the support of ipv6 in the future?
thanks,

**Comment by ycyang1229** [comment]
@MushMal  I can not reopen this issue, so I left it this way. thanks,

**Comment by MushMal** [comment]
Actually, you are correct. We haven't considered this option as most of the communication between the client and the backend is done in IpV4 format due to some backend APIs (like TURN for example) not supporting it. We will need to add support for Ipv6 cmake flag once the backend supports it. I would keep that issue separate though from the P2P IPv6 support that was added.

**Comment by ycyang1229** [comment]
Cool, thanks. Like you said, I think the backend does not support ipv6  should be mentioned somewhere, since this is different  from the capabilities of p2p ipv6. It is easier to confuse users, and make people mistake the support of ipv6.

**Comment by MushMal** [comment]
Indeed, thanks for the input. The reason I would like to take this a little deeper because we need to understand the overall investment and the strategy across our products - including KVS streams and webRtc implementations and make a coherent story for our customers. 
We will follow-up with "Enhancements" issues once we get more information.

**Comment by ycyang1229** [comment]
@MushMal This notification of github did not notify me of the change of this issue if I am not tagged. I assume it will happen to you so I tag you here.

**Comment by ycyang1229** [comment]
Thanks, please let me know if you have one clear story. However, I think backend probably does not support the ipv6 since it is not popular.

**Comment by MushMal** [comment]
Sorry, I didn't want to confuse you. There are technical and product reasons why the backend support for IpV6 is not uniform across the services and APIs. This goes a little beyond a single service (WebRTC in question) and this is the reason why I wouldn't just cut a separate issue just now about work items for support IpV6 across the board.

**Comment by ycyang1229** [comment]
Do not be sorry. It is one discussion about the capability of kvs service and webrtc, and I just try to have one clear view on these stuff. big thanks!
