### ISSUE TITLE
[QUESTION] How to add OpenSSL engines to Kinesis?

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#563]
I'm create an streaming solution for a camera with an SOC that has cryptography hardware support.
So I need to write an engine to take advantage of this hardware. What is the best / recommended way of adding this engine?

**Comment by MushMal** [comment]
@fernandoc1 the KVS SDKs operate with either OpenSSL or MbedTLS. Your custom hardware likely has crypto library that plugs into OpenSSL or MbedTLS that you might need to investigate/get answers from the manufacturer.

Resolving this issue - please feel free to reopen or cut a new issue
