### ISSUE TITLE
cannot clone submodule

### ISSUE THREAD

**Issue by huyhoangk50** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#566]
**Describe the bug**
Cannot clone two submodules in file .gitmodules

**To Reproduce**
git clone --recursive https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c.git

**Expected behavior**
Clone with submodules inside open-source folder

**Desktop (please complete the following information):**
 - OS:ubuntu

**Additional context**
It seems that some one delete the commit of submodules in open-source folder

**Comment by MushMal** [comment]
@huyhoangk50 we removed the submodules intentionally. The related sub-projects are now pulled as other open-source projects. You can git clone with --recursive and it won't break anything. During the build process when CMake is run, it will pull down the appropriate commit from the projects and build libraries from them. Installing the library will also install the header files in your open-source root directory.

I am resolving this issue. Please feel free to re-open

**Comment by huyhoangk50** [comment]
@MushMal No, it does not work  now.

**Comment by MushMal** [comment]
@huyhoangk50 could you please elaborate? Can you get a clean repository by git clone then run the build steps highlighted in readme? Simply create a directory called build, then cd into build and cmake .. and then make 

I am reopening this but please provide the details so we can help

**Comment by huyhoangk50** [comment]
@MushMal It worked now.
