### ISSUE TITLE
[question] can you explain why knowing interface+ip ahead of time is required for turn?

### ISSUE THREAD

**Issue by zhuker** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#568]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/327a1aafd51c040d6d7661f1dc655199117bfe56/src/source/Ice/IceAgent.c#L1643-L1656

i've been thinking of replacing this with a programmatic `ip route get $MY_TURN_SERVER_IP_ADDR` which most of the time is default gateway

**Comment by zhuker** [comment]
@chehefen @lherman-cs ?

**Comment by chehefen** [comment]
yh, it's not necessary to bind to an address for relay candidates.
