### ISSUE TITLE
 ld: library not found for -lkvsCommonLws error when using kvs sdk-c

### ISSUE THREAD

**Issue by ssalexa** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#573]
Hi,

I am going to integrate this library with my project. It works good if I only link to kvsWebrtcClient. However, it shows  ld: library not found for -lkvsCommonLws error when I link kvsWebrtcSignalingClient. Would you help with this? I can provide log later.

I added these lines in CmakeList. 

link_directories("${CMAKE_CURRENT_BINARY_DIR}/amazon-kinesis-video-streams-webrtc-sdk-c")
link_directories("${CMAKE_CURRENT_SOURCE_DIR}/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib")

include_directories("${CMAKE_CURRENT_SOURCE_DIR}/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/include")
include_directories("${CMAKE_CURRENT_SOURCE_DIR}/amazon-kinesis-video-streams-webrtc-sdk-c/src/include")

#target_link_libraries(SampleApp kvsWebrtcClient)
target_link_libraries(SampleApp kvsWebrtcSignalingClient)

**Comment by MushMal** [comment]
@ssalexa can you build the samples? Those link both the webrtc library and the signaling. Each, in turn link the common.

If you are able to build and run the stock samples, you should modify your cmake to have the same pattern. Unfortunately, we don't provide direct support for customers cmake files

**Comment by disa6302** [comment]
@ssalexa , 

Are you still facing issues with this?

**Comment by disa6302** [comment]
@ssalexa , 

This issue seems to have gone stale. Feel free to open a new issue if you face any problems.
