### ISSUE TITLE
[QUESTION] anyone working on RtcPeerConnectionGetMetrics?

### ISSUE THREAD

**Issue by zhuker** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#576]
I couldn't find implementation for https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/74cf636e5694c0687287df308e8c3e2e650e0233/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1838

Is anyone working on it? Am I missing something?

**Comment by lherman-cs** [comment]
I think @disa6302 and @MushMal have more context on this.

**Comment by MushMal** [comment]
This is WIP. For WebRTC metrics, we will be adding some very shortly. For Signaling, we will ad those also soon.

**Comment by zhuker** [comment]
> This is WIP. For WebRTC metrics, we will be adding some very shortly. For Signaling, we will ad those also soon.

Any ETAs? Need help?

**Comment by MushMal** [comment]
@zhuker , while we can't give a precise ETA, it's one of the highest priority items. 

We would LOVE if you could contribute. How about we push the main APIs and we can all incrementally iterate on the support?

**Comment by zhuker** [comment]
> @zhuker , while we can't give a precise ETA, it's one of the highest priority items.
> 
> We would LOVE if you could contribute. How about we push the main APIs and we can all incrementally iterate on the support?

Sounds good

do you guys have a public chat? discord? gitter? slack?

**Comment by MushMal** [comment]
Nothing yet really. We should set something up. In the meanwhile, if you could send us your email to kinesis-video-support@amazon.com, I would follow-up with you and set up a quick sync-up or something

**Comment by disa6302** [comment]
@zhuker ,

Apologies for the delayed response. I am working on it in this branch: 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/set-up-ice-metrics
It is a WIP.

**Comment by zhuker** [comment]
@disa6302 you wanna merge https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/set-up-ice-metrics with https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/579 ?
`Metrics.h` seems to conflict

**Comment by zhuker** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/586

**Comment by disa6302** [comment]
@zhuker ,

The branch isnt ready with the ICE metrics code. But yes, I will rebase it with top of master. Will keep you posted.

**Comment by disa6302** [comment]
@zhuker , 
Closing this since it is being tracke din #578
