### ISSUE TITLE
[BUG] Static and cross-compile builders should assert that artifacts are correct

### ISSUE THREAD

**Issue by Sean-Der** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#582]
**Describe the bug**
Static and cross-compile builders succeed right now. We broke these builds in our CMakeLists, but our testers didn't catch it.

**SDK version number**
b3f40e80c6a8f2075f8f2f8673d1dc2e87fb6862

**Open source building**
None

**To Reproduce**
Run current build and it will succeed incorrectly

**Expected behavior**
Builders should fail

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

**Comment by lherman-cs** [comment]
Static build is now properly checked after https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/837.

**Comment by MushMal** [comment]
@lherman-cs Nice! Do you want to resolve this then?

**Comment by lherman-cs** [comment]
@MushMal I think we should keep this open since we still don't have a good check for cross-compile scenarios.
