### ISSUE TITLE
[BUG] handleStunPacket(): local candidate ip address does not match with xor mapped address in binding response

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#583]
**Describe the bug**
This was observed occasionally throughout the past, the conditions that caused this was unknown. See log
[xor-mapped.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4860916/xor-mapped.txt)

**SDK version number**
59c70fe

**Comment by lherman-cs** [comment]
@suggestedfixes do you mind to share your platform details, e.g. architecture, endianness, OS, etc.?

**Comment by suggestedfixes** [comment]
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Model name:            ARMv7 Processor rev 1 (v7l)
CPU max MHz:           816.0000
CPU min MHz:           96.0000
# uname -r
3.10.104
#

**Comment by lherman-cs** [comment]
@suggestedfixes did this happen intermittently on the same device? Also, your log shows that this device acted as a master. Did your viewer use JS SDK or C SDK? Could you share more details for the viewer also, e.g. browser version, sdk version, logs, device details?

I'm sorry for asking for a lot more details. I'm trying to get as much details as I can so that we can hopefully find the root cause.

**Comment by suggestedfixes** [comment]
This happen intermittently on the same device and difficult to reproduce.
My viewer uses JS SDK 1.0.8.
Browser version: Version 83.0.4103.116 (Official Build) (64-bit).
OS: Windows 10
Device: Thinkpad P52

**Comment by lherman-cs** [comment]
@suggestedfixes I'm not sure how we can debug this. Does this issue still happen? Or do you have more details on this?

**Comment by lherman-cs** [comment]
Since the issue has gone stalled and we don't have enough information to debug this, I'll mark this as resolve. Please feel free to reopen it for further assistance!
