### ISSUE TITLE
[QUESTION] use find_package(OpenSSL REQUIRED) when doing cross-compiling.

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#584]
A one liner description about the use case and what you are trying to achieve
cross-compiling.

** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 
For cross-compiling and find_package(OpenSSL REQUIRED), how about using CMAKE_FIND_ROOT_PATH instead of OPENSSL_ROOT_DIR?
thanks, 

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by lherman-cs** [comment]
@ycyang1229 I'm not really sure about `CMAKE_FIND_ROOT_PATH` and `OPENSSL_ROOT_DIR`. How do they differ? And, how `CMAKE_FIND_ROOT_PATH` can help with cross compiling? Do you mind to explain them in more details?

Also, please feel free to open a PR! We'll be happy to review it.

**Comment by ycyang1229** [comment]
@lherman-cs 
I prefer using the cmakefile of toolchain to cross-compile this sdk, and I use the CMAKE_FIND_ROOT_PATH and "only" mode to constrain the access of includes/lib. 

Here is one example.
https://github.com/warmcat/libwebsockets/blob/master/contrib/cross-esp32.cmake#L59
https://github.com/warmcat/libwebsockets/blob/master/contrib/cross-esp32.cmake#L66

Here is my understanding.
In the original case, find_package() will use OPENSSL_ROOT_DIR to find openssl. After using CMAKE_FIND_ROOT_PATH and only mode, find_package() will not find openssl. 
https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindOpenSSL.cmake#L143

If I want to use my preferred approach to cross-compile this sdk, I have to add the "sdk/open-source" folder path into CMAKE_FIND_ROOT_PATH, and find_package() will find openssl. 

please correct me if I am wrong.
thanks,

**Comment by MushMal** [comment]
Drawing blank here. I am OK with any of the approaches but my only concern is to not regress some other scenarios on other platforms. I will let the experts to chime in on this

**Comment by ycyang1229** [comment]
@MushMal That's why I want to use the cmakefile of toolchain, and keep platform-specific parameter in the platform cmakefie. And the sdk provides the general interface to be controlled by the cmakefile of toolchain. For this case, I hope the path of searching some lib/include and installing bin/lib can be exposed to one or two(maybe more) specific path variables. Btw, I like one recent commit which added the way of installing bin/lib. 
I am not an expert of cmake and I am not sure it is a good or correct way, either. I just gave my idea on this, so if you have any suggestion for cross-compiling, please let me know. 
thanks. :D

**Comment by ycyang1229** [comment]
Closing it. Please re-open it if it is necessary. :D
