### ISSUE TITLE
[FEATURE] Unit test on resendPacketOnNack()

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#588]
We had crashes on resendPacketOnNack() before. Although they had been resolved, it would be nice to mock different Nack scenarios to prevent regression.

**Comment by lherman-cs** [comment]
@suggestedfixes this is a great idea. I'll let the team aware of this request. Thanks!

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.
