### ISSUE TITLE
missing EMA_ACCUMULATOR_GET_NEXT

### ISSUE THREAD

**Issue by minhngvan** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#589]
`// API call latency calculation
#define SIGNALING_API_LATENCY_CALCULATION(pClient, time, isCpApi) \
        MUTEX_LOCK((pClient)->diagnosticsLock); \
        if (isCpApi) { \
            (pClient)->diagnostics.cpApiLatency = EMA_ACCUMULATOR_GET_NEXT((pClient)->diagnostics.cpApiLatency, GETTIME() - (time)); \
        } else { \
            (pClient)->diagnostics.dpApiLatency = EMA_ACCUMULATOR_GET_NEXT((pClient)->diagnostics.dpApiLatency, GETTIME() - (time)); \
        } \
        MUTEX_UNLOCK((pClient)->diagnosticsLock); \`

**Comment by MushMal** [comment]
You need to clean up the repository so it will build the project and install the headers. In this case you can remove the kvs common library

**Comment by lherman-cs** [comment]
@minhngvan Do you have an update on this?

**Comment by MushMal** [comment]
Resolving. Please feel free to reopen if you still have issues with this
