### ISSUE TITLE
How to convert a file into .h264 file for each frame?

### ISSUE THREAD

**Issue by thasin96** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#590]
I am able to run sample code which has been provided. I would like to do the same for my external camera. I can get the stream through RTSP. How to convert my stream into H264 file? Is there anyway I can directly pass RTSP Link to Streamer in WebRTC?

**Comment by lherman-cs** [comment]
@thasin96 our WebRTC SDK doesn't handle media pipelines. We expect that the frames that we receive have been encoded, which later will be packetized in RTP format.

To do what you want, I'd highly recommend to use a software such as GStreamer or ffmpeg. We have an example how you can integrate GStreamer, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c. The example uses files as the source, but you can replace this easily with `rtspsrc` plugin.

For encoding the video stream, please also take a look at the example, specifically these 2 lines, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L153-L154.

**Comment by disa6302** [comment]
@thasin96 , 

Is your question answered? If yes, could you please close the ticket? Thanks!
