### ISSUE TITLE
How to change the source in the Gstpipeline

### ISSUE THREAD

**Issue by ashutoshIITK** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#591]
I want to use kvsWebrtcClientMasterGstSample application but do not want to use /dev/video0 but some other device say /dev/video1.
I made this change in the pipeline:
pipeline = gst_parse_launch(
                    "**v4l2src do-timestamp=TRUE device=/dev/video3** ! queue ! videoconvert ! video/x-raw,width=1280,height=720,framerate=30/1 ! "
                    "x264enc bframes=0 speed-preset=veryfast bitrate=512 byte-stream=TRUE tune=zerolatency ! "
                    "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video",
                     &error);

but on running the program, it still uses the /dev/video0. Could you please let me know why is it so?

**Comment by lherman-cs** [comment]
@ashutoshIITK which mode did you use, video only or audio video? Please make sure that you update the right pipeline. Also, the question is not related to the SDK since we don't handle media pipelines, our SDK only receives encoded frames. I think GStreamer forum is more appropriate for this kind of questions.

**Comment by ashutoshIITK** [comment]
@lherman-cs I used video only.

**Comment by lherman-cs** [comment]
@ashutoshIITK So, I assumed that you changed this pipeline, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMasterGstreamerSample.c#L158-L162? Also, you can always test your pipeline by piping it to `autovideosink`.

**Comment by ashutoshIITK** [comment]
Thank you! Yes, I will check the pipeline and update this thread by tomorrow.

**Comment by ashutoshIITK** [comment]
Okay, I will explain the problem here. This is my pipeline:
```
"v4l2src device=/dev/video3 ! queue ! videoconvert ! video/x-raw,width=1280,height=720! "
                        "x264enc bframes=0 speed-preset=veryfast bitrate=512 byte-stream=TRUE tune=zerolatency ! "
                        "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video"
```
When I use device=/dev/**video0** i.e. the original camera. It works fine but what I wanna do is that instead of using **video0**, I want to use some other source which I have created/duplicated from **video0**. The duplicated sources are **video2** and **video3**. **video2** is used to send data to Kinesis Video Stream (**KVS**) and it _works fine_ but with Kinesis WebRTC I am unable to use **video3**. It just show "_Connecting to signaling channel and master device_" in the AWS Console (viewer) and in the sending device. It keep showing "Client is writable".

Just to let you know that I can play both the sources perfectly locally. I checked using ffplay /dev/video2 and ffplay/dev/video3.

Could you please let me know about it? Thank you in advance.

**Comment by MushMal** [comment]
@ashutoshIITK could you please include the debug logs from KVS WebRTC? From what I understand, your webRTC solution works fine but when you attempt to pipe video source 3 it doesn't work for some reason. It is perhaps GStreamer related and if so, GStreamer forums might provide a better answer. 

You could also try to get more information about GStreamer failure setting GST_DEBUG=5 env variable and re-launching your application to get more spew from GStreamer that might help you debug your application

**Comment by ashutoshIITK** [comment]
@MushMal 
I think you have slightly misunderstood my point. With /dev/video2, I use the normal Kinesis Video Streaming (KVS) [https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp](url) and not the KVS WebRTC.  That works completely fine. With /dev/video3, I am trying to use this WebRTC. I have checked the pipeline several times by just using /dev/video0 and then it works fine but only in the duplicated case i.e. using /dev/video3, it does not work. I cannot understand the reason because the normal KVS streams fine.

I have attached the log here. Could you please have a look?
[log.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4899014/log.log)

**Comment by MushMal** [comment]
The log seem to be truncated or something - the last entry is freeing turn allocations. 

If I understand it correctly, you are using same device and the same encoder in parallel? Depending on the hardware, it might only allow exclusive access (most hardware encoders do). Perhaps, I am not understanding the question. Can you run a few simple experiments with WebRTC and your media source is isolation to eliminate the KVS issues all together?

**Comment by ashutoshIITK** [comment]
Actual exclusive access is not the problem.
I am using same device that has only one physical camera (/dev/video0). Next, I create fake devices using `sudo modprobe v4l2loopback devices=4`, This will create `/dev/video1`, `/dev/video2`,` /dev/video3`, `/dev/video4`. Out of these created devices, I write the output from `/dev/video0` to `/dev/video2` and `/dev/video3`. So basically, they are copy of the `/dev/video0` but it kind of gives me access to two cameras (Because as you mentioned about exclusive access, I can use `/dev/video0` for only one purpose). 

Now, I use /dev/video2 for normal KVS streaming and that works fine. But when I use `/dev/video3` with KVS WebRTC, it does not show the output (video) in Signalling Channel in AWS Console. I have reattached the console for your perusal.
[log_updated.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4899154/log_updated.log)

**Comment by ashutoshIITK** [comment]
@MushMal , The problem is solved. Actually, it took very long time for the video to show. Usually, it is not like that.  (Maybe I was just impatient cause its WebRTC :p) Basically, everything is okay but I have just left my comments if someone encounters same problem in the future.  Thanks for your help. This issue can be closed!

**Comment by MushMal** [comment]
Oh, wow! Very cool indeed!

The latency might be due to the ICE negotiation. I am going to keep this issue open for now until we have more understanding why the connection setup takes long and come up with some suggestions

**Comment by ashutoshIITK** [comment]
Thank you!
I see! Sure!

**Comment by chehefen** [comment]
@ashutoshIITK Hi, do you still see the long delay for video to show? Thanks

**Comment by ashutoshIITK** [comment]
@chehefen 
I have observed an interesting thing here. When my raspberry pi and the viewer (my laptop) are connected to the same network, it takes really long (30 seconds or more) to get the streaming video to appear in the AWS console Media Playback Viewer but when I am connected to a different network, it connects within 5 seconds. Is there some explanation for this? I experimented it today several times.

**Comment by lherman-cs** [comment]
@ashutoshIITK in both networks, were both connected through peer-to-peer or TURN? Also, Did you enable trickle ice?

**Comment by lherman-cs** [comment]
Since this issue has gone stalled, I'll mark this as resolve. Please feel free to reopen it for further assistance!

**Comment by utsavrai** [comment]
I am having the same problem, I am trying to change the video source to a usb connected (Intel realsense d415) camera by changing video0 to video4 but the streaming does not start as it does for video0 (webcam).

**Comment by ashutoshIITK** [comment]
> I am having the same problem, I am trying to change the video source to a usb connected (Intel realsense d415) camera by changing video0 to video4 but the streaming does not start as it does for video0 (webcam).

What do you mean that it does not start? Are you writing frames to video4 or not?

If you are already writing frames to the fake source, then consider streaming on a separate process. Let me know if you face issues.

**Comment by utsavrai** [comment]
> > I am having the same problem, I am trying to change the video source to a usb connected (Intel realsense d415) camera by changing video0 to video4 but the streaming does not start as it does for video0 (webcam).
> 
> What do you mean that it does not start? Are you writing frames to video4 or not?
> 
> If you are already writing frames to the fake source, then consider streaming on a separate process. Let me know if you face issues.

Sorry I should have checked my code first, changing the pipeline to the following worked ( I removed framerate argument from the pipeline command)


```
pipeline = gst_parse_launch(
                    "v4l2src device=/dev/video6 ! queue ! videoconvert ! video/x-raw,format=I420,width=1920,height=1080! "
                        "x264enc bframes=0 speed-preset=veryfast bitrate=50000 byte-stream=TRUE tune=zerolatency ! "
                        "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video",
                    &error);
```

thank you very much for the quick reply
