### ISSUE TITLE
how to decrease the viewer timeout for peer connection failure?

### ISSUE THREAD

**Issue by ajjiang48** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#593]
Hi, Sir,
We're running the webrtc C SDK viewer on our device and do some abnormal user scenario testing.
We got the peer connection failure event (RTC_PEER_CONNECTION_STATE_CLOSED event from 
onConnectionStateChange callback function) after 30 seconds while the webrtc master force-close the 
browser (the webrtc master-side is implemented using webrtc JS SDK).
We want to decrease the 30 second timeout to 15 or 20 seconds for better user experience; is there
an option or source code modification to achieve it ??
Thanks, A.J.

**Comment by lherman-cs** [comment]
@ajjiang48 AFAIK, this is currently not possible. Since the master will force close the connection, this is the same case as reducing idle connection timeout.

@chehefen any thought on this?

**Comment by chehefen** [comment]
@ajjiang48  you can change it here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.h#L30. However ICE sends keep-alive every 15 seconds. By decreasing the timeout you may risk premature disconnection when there is network congestion.

**Comment by ajjiang48** [comment]
@chehefen thank  you for the quick answer; I've tested the 15 seconds and it's working; 
We assume the network congestion or sudden disconnect being recovered within 10 seconds, so, it's reasonable for 15 seconds timeout.
