### ISSUE TITLE
[BUG] Add -lm as a compilation flag for linking libkvsWebrtcClient.so

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#601]
I'm trying to compile Kinesis (v1.2.0) in my platform, and it complains about missing ldexp symbol. It is necessary to add `-lm` in order to compile the whole project.

```
/usr/bin/cmake -E cmake_link_script CMakeFiles/discoverNatBehavior.dir/link.txt --verbose=1
/opt/hisi-linux/x86-arm/arm-hisiv300-linux/target/bin/arm-hisiv300-linux-gcc  -fPIC  -rdynamic CMakeFiles/discoverNatBehavior.dir/samples/discoverNatBehavior.c.o  -o discoverNatBehavior  -L/home/fccoelho/Code/kinesis_arm/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib -Wl,-rpath,/home/fccoelho/Code/kinesis_arm/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib:/home/fccoelho/Code/kinesis_arm/amazon-kinesis-video-streams-webrtc-sdk-c/build libkvsWebrtcClient.so 
/home/fccoelho/Code/kinesis_arm/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libcrypto.so.1.1: warning: gethostbyname is obsolescent, use getnameinfo() instead.
libkvsWebrtcClient.so: undefined reference to `ldexp'
```

**Comment by ycyang1229** [comment]
Hey @chehefen , I have the same problem on my platform,  but I did the static build. Just posted my error log here, and probably the same problem. 

[ 93%] Linking C executable kvsWebrtcClientViewer
../open-source/lib/libcrypto.a(b_sock.o): In function `BIO_gethostbyname':
b_sock.c:(.text+0x54): warning: gethostbyname is obsolescent, use getnameinfo() instead.
/*****/****-linux/x86-arm/arm-********-linux/host_bin/../lib/gcc/arm-linux-uclibceabi/6.3.0/../../../../arm-linux-uclibceabi/bin/ld: libkvsWebrtcClient.a(RtcpPacket.c.o): undefined reference to symbol 'ldexp'
/*****/****-linux/x86-arm/arm-********-linux/host_bin/../target/lib/libm.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/kvsWebrtcClientViewer.dir/build.make:126: recipe for target 'kvsWebrtcClientViewer' failed
make[2]: *** [kvsWebrtcClientViewer] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/kvsWebrtcClientViewer.dir/all' failed
make[1]: *** [CMakeFiles/kvsWebrtcClientViewer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chertov** [comment]
i have this error too! 

It was fixed after add 'm' to target_link_libraries(kvsWebrtcClient ...)
But on my old gcc 6.2 and linux kernel 3.1 i have to add
/CMake/Dependencies/libopenssl-CMakeLists.txt#L13
SET(OPENSSL_EXTRA ${OPENSSL_EXTRA} no-async no-tests)
and
/CMake/Dependencies/libwebsockets-CMakeLists.txt#L27
-DLWS_HAVE_EVENTFD=0

**Comment by fernandoc1** [comment]
I think that this is a common issue when building Kinesis. If they could just add these flags from a external switch, it could make the building process easier.

**Comment by MushMal** [comment]
@fernandoc1 I believe we have gone back and forth on this for a long while. We can't assume that by adding extra flags we won't be breaking other scenarios. As mentioned in numerous other posts, the TravisCI integration we currently run builds clean on those compiler/platform combinations. We wish that it was as trivial to add support for your scenarios but I believe we will need to have a better understanding of the build of these 3p dependencies on the given platforms in order to provide some guarantees.

We will try to spend more cycles on the build flags later. I am going to resolve this issue for now.

**Comment by fernandoc1** [comment]
If you want, I can send you a compiler toolchain for the camera we are developing. It is using GCC (arm-hisiv300-linux-gcc (Hisilicon_v300) 4.8.3 20131202)
You can add a new toolchain to your tests that deliver the same errors as other customers are facing, while giving you some clue about potential issues with your code.
If needed, I can provide my build steps. It is pretty easy.
