### ISSUE TITLE
Include.h documents `freeTransceiver` but it is not implemented.

### ISSUE THREAD

**Issue by gerwin3** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#604]
**Describe the bug**
There's mention of a function `freeTransceiver` in `Include.h` but it isn't implemented (as far as I can see).

**Expected behavior**
I think the function header should be removed.

**Additional context**
I tried to use it but it the linker cannot find an implementation. I looked through the source code and it doesn't seem to have an implementation.

**Comment by MushMal** [comment]
Indeed this is a bug. We will address this shortly.
