### ISSUE TITLE
[BUG] Sometimes the connection fails

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#605]
I have compiled Kinesis for a camera I'm working on, and it sometimes works great, for many hours.
However, there are sometimes that Kinesis stop sending packets and my streaming freezes. Since I'm using a local network, and the camera connection is always available, I don't think that is a connection problem. After this happens, Kinesis stop completing connections and never start sending packets to my remote host, even though it receives the connection request and prints its information on the terminal.
When this happens, my unique solution is to kill Kinesis and start it over again.
I wish to find exactly what is the cause, but I have no idea.
I have attached the complete log in this post. Here, I have initially a successfull connection that lasts for some minutes and latter, no other connection is possible.

[log_kinesis.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4897859/log_kinesis.txt)

**Comment by MushMal** [comment]
I see a spew of 

```
NO FRAME DATA
2020-07-09 13:09:36 ERROR   writeFrame(): operation returned status code: 0x00000001
```

Can you please check your code? This might be irrelevant but I am not sure I understand what's happening in your case? It seems that the last few entries in the log indicate that your master did receive the offer, responded and established P2P connection. 

Can you also include whether the stock master sample works on your device with the pre-canned frames and no modifications?

**Comment by lherman-cs** [comment]
Since this issue has been stalled for a while, I'll mark this as resolve. Please feel free to reopen it for further assistance!
