### ISSUE TITLE
[BUG] kvsWebRTCClientMasterGstreamerSample.c Add peer failed. Max peer count reached on second connection

### ISSUE THREAD

**Issue by arkhipenko** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#608]
**Describe the bug**
A kvsWebRTCClientMasterGstreamerSample.c with the following gst pipeline

 pipeline = gst_parse_launch(
"rpicamsrc keyframe-interval=30 "
"! queue "
"! h264parse "
"! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline "
"! appsink sync=TRUE emit-signals=TRUE name=appsink-video",
 &error);

only allows one connection, and never allows the same client to reconnect or different client to connect (video never shows up on a 2nd viewer or subsequent attempts of the same client) until the program is restarted. 

on second connection:
2020-07-12 21:35:05 DEBUG   iceAgentLogNewCandidate(): New remote ice candidate discovered. Id: CZjN9Eq7A. Ip: 18.219.39.23:64507. Type: host
**2020-07-12 21:35:05 WARN    turnConnectionAddPeer(): Add peer failed. Max peer count reached**
2020-07-12 21:35:05 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x0000000d

**SDK version number**
amazon-kinesis-video-streams-webrtc-sdk-c  release version 1.2.0

**Open source building**
not a build issue - builds ok

**To Reproduce**
1. Go to https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html
2. Click on "start viewer", start streaming. 
3. Click on "stop viewer". 
4. Click on "start viewer", try starting streaming. - the video never starts although there is activity on the kvsWebRTCClientMasterGstreamerSample.c side

**Expected behavior**
Expected to have 10 simultaneous clients streaming or at least after the same client reconnects. 

**Desktop (please complete the following information):**
 - OS: Streaming from RPi under latest Buster. Gstreamer 1.0 installed and functional outside of webrtc environemnt
 - Browser crome
 - Version Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by disa6302** [comment]
@arkhipenko , 

By your description it looks like the Master does not detect when the peer is stopped. I am unable to reproduce the behavior and would like to get some logs to confirm what might be causing this.

**Comment by arkhipenko** [comment]
Thank you for a quick reply. 
Log is attached.   The log is an attempt to connect to signalling channel crane1-1 with client ids "test-page-1", "test-page-2", and "test-page-3".  For test-page-2 I just pushed "stop viewer" and then "start viewer", For "test-page-3" I closed chome completely and started with a new session. Same result - video feed for 2 and 3 never showed up.
Video only shows up if the host app is reloaded. 

Please help! Thanks!

**Comment by arkhipenko** [comment]
UPDATE: 
Using a USB connected camera with this pipeline does not seem to have this issue.

"-v v4l2src device=/dev/video1 ".
"! queue "
"! videoconvert "
"! video/x-raw,width=640,height=480,framerate=30/1 "
"! x264enc  bframes=0 key-int-max=45 bitrate=500 tune=zerolatency "
"! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline "
"! appsink sync=TRUE emit-signals=TRUE name=appsink-video"


same device, same codebase...

**Comment by arkhipenko** [comment]
So it clearly happens only with this pipeline
"-v rpicamsrc bitrate=5000000 annotation-mode=12 preview=false "
"! queue "
"! queue max-size-time=100000000 "
"! h264parse "
"! video/x-h264,profile=constrained-baseline,stream-format=byte-stream,alignment=au "
"! appsink sync=TRUE emit-signals=TRUE name=appsink-video",

which seems to mean it's somehow linked to the rpicamsrc...
Is there anything you can help me with providing information to the author of rpicamsrc to help fix this?
Thank you for your help!!
Verbose log is attached.
[verbose_log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4913170/verbose_log.txt)

**Comment by disa6302** [comment]
> Thank you for a quick reply.
> Log is attached. The log is an attempt to connect to signalling channel crane1-1 with client ids "test-page-1", "test-page-2", and "test-page-3". For test-page-2 I just pushed "stop viewer" and then "start viewer", For "test-page-3" I closed chome completely and started with a new session. Same result - video feed for 2 and 3 never showed up.
> Video only shows up if the host app is reloaded.
> 
> Please help! Thanks!
> [log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4910569/log.txt)

Thank you @arkhipenko  for running different cases! From the logs, it looks like streaming session is getting free'd in all the cases. (test-page-1, test-page-2 and test-page-3)

So, yes, looks like it is something with the rpicamsrc. One thing that will help you debug is to run the sample with `GST_DEBUG=4`. That will give you an understanding of what might be going on with the pipeline.

**Comment by arkhipenko** [comment]
The log that I attached is actually in VERBOSE! Even more than DEBUG.Can you have a look? Is there anything there that can be a pointer for the problem?.On Jul 13, 2020 1:11 PM, Divya Sampath Kumar <notifications@github.com> wrote:

Thank you for a quick reply.
Log is attached. The log is an attempt to connect to signalling channel crane1-1 with client ids "test-page-1", "test-page-2", and "test-page-3". For test-page-2 I just pushed "stop viewer" and then "start viewer", For "test-page-3" I closed chome completely and started with a new session. Same result - video feed for 2 and 3 never showed up.
Video only shows up if the host app is reloaded.
Please help! Thanks!
log.txt

Thank you @arkhipenko  for running different cases! From the logs, it looks like streaming session is getting free'd in all the cases. (test-page-1, test-page-2 and test-page-3)
So, yes, looks like it is something with the rpicamsrc. One thing that will help you debug is to run the sample with GST_DEBUG=4. That will give you an understanding of what might be going on with the pipeline.

**Comment by disa6302** [comment]
@arkhipenko , 

I do not see any obvious issue. One thing you can try is removing `queue max-size-time` and then try this. It is possible that the buffers are getting filled up? This is just a hunch though.

But, you can get more information by running GST_DEBUG=4 to see if there is anything wrong with the pipeline.

**Comment by arkhipenko** [comment]
attaching a log with GST_DEBUG=4
Anything that strikes you as unusual?   I noticed the amount of activity during the second connect is clearly different.

Thank
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4914283/log.txt)
 you again!

**Comment by chehefen** [comment]
`0:00:08.641448784  1506 0x6d3026c0 ERROR           GST_PIPELINE grammar.y:816:priv_gst_parse_yyparse: no element "v"`
you cant pass -v in gst-parse-launch.

**Comment by arkhipenko** [comment]
> `0:00:08.641448784 1506 0x6d3026c0 ERROR GST_PIPELINE grammar.y:816:priv_gst_parse_yyparse: no element "v"`
> you cant pass -v in gst-parse-launch.

Interesting... I don't think this is the cause though as both pipelines work first time:

"-v rpicamsrc keyframe-interval=30 num-buffers=-1 "
"! h264parse "
"! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline "
"! appsink sync=TRUE emit-signals=TRUE name=appsink-video",

and 

"-v v4l2src device=/dev/video1 ".
"! queue "
"! videoconvert "
"! video/x-raw,width=640,height=480,framerate=30/1 "
"! x264enc bframes=0 key-int-max=45 bitrate=500 tune=zerolatency "
"! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline "
"! appsink sync=TRUE emit-signals=TRUE name=appsink-video"

only the latter one allows multiple connections and repeat viewing, but the former does not....

**Comment by arkhipenko** [comment]
tried without "-v" - same behaviour

**Comment by chehefen** [comment]
can you try this?
"rpicamsrc keyframe-interval=30 bitrate=500000 ! queue ! h264parse config-interval=-1 ! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video"

**Comment by arkhipenko** [comment]
> can you try this?

You, sir, are a magician!
What was the trick? "h264parse config-interval=-1"?

**Comment by arkhipenko** [comment]
For posterity and those who come looking for the same solution:
this is the winning pipeline (courtesy of @chehefen )

"rpicamsrc keyframe-interval=30 bitrate=5000000 "
"! queue "
"! h264parse config-interval=-1 "
"! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline "
"! appsink sync=TRUE emit-signals=TRUE name=appsink-video",

**Comment by guimagcm** [comment]
Could any of you please adapt this same pipeline using a mkv or mp4 file as source?
