### ISSUE TITLE
[QUESTION] latency and network performance metrics

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#616]
Does SDK have latency metrics, such as
Time between sending rtp packet and getting ack
percentage of dropped packets
percentage of re-transmitted  packets

I noticed that there is bandwidth measurement.  How should I use the bandwidth info?

**Comment by disa6302** [comment]
@zwei333 ,

Nothing yet. Whatever metrics are being implemented now are what is available in the spec and we will add them in slowly. No ETA yet. It is a WIP. Public interfaces will also be available to pull the information. Thank you for your patience!

**Comment by disa6302** [comment]
@zwei333 , 

Closing this because webrtc metrics is being tracked in #578
