### ISSUE TITLE
[QUESTION] about TURN allocation

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#617]
Who decides which TURN ice candidate to use, viewer app or the TURN server?
How is TURN ice candidate being chosen? based on what information?
Are offer and answer used during choosing the TURN ice candidate?  To be specific, if offer has audio/video receive only, then there is no media data flowing from viewer to master.  I guess the one way data flow can affect the TURN ice candidate choosing process.

Please help me to gain more understanding of the TURN.

**Comment by disa6302** [comment]
@zwei333 , 

Which TURN candidate to use for data exchange is based on which candidate pair is nominated, which in turn is based on which pair passes the connectivity check and is of highest priority. Nomination happens on the controlling side of the peer connection. As per our SDK and in general as well, the one that sends the offer is the controlling side. This means, viewer (if sending the offer) will ultimately nominate the pair based on connectivity checks and priority.

**Comment by suggestedfixes** [comment]
Normally TURN is absolutely the last resort when there's no way STUN can get through due to network topology.
Also, this commit fixes the weight that TURN gets chosen.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/23362651ad78ccdbcc3971e89352289017d1c367

**Comment by lherman-cs** [comment]
Since the question has been answered, I'll mark this as resolve. Please feel to reopen if you need further assistance!
