### ISSUE TITLE
[QUESTION] Sendto() failed with errno Network is unreachable

### ISSUE THREAD

**Issue by Lion-blade** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#618]
In a wireless network. The live view on the AWS console via kvsWebRtcMaster.  After 10 -15 seconds the preview terminates and returns the following exception logs.

Log:
11:45:50  2020-07-15 03:49:10 DEBUG   lwsWssCallbackRoutine(): Client is writable
11:46:00  2020-07-15 03:49:20 DEBUG   lwsWssCallbackRoutine(): Client is writable
11:46:01  2020-07-15 03:49:21 DEBUG   socketSendDataWithRetry(): sendto() failed with errno Network is unreachable
11:46:01  2020-07-15 03:49:21 DEBUG   socketSendDataWithRetry(): Close socket 51
11:46:01  2020-07-15 03:49:21 DEBUG   socketSendDataWithRetry(): Failed to send data. Bytes sent 0. Data len 188. Retry count 0
11:46:01  2020-07-15 03:49:21 ERROR   socketSendDataWithRetry(): operation returned status code: 0x5800001a
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x5800001a
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x5800001a
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    socketConnectionSendData(): Failed to send data. Socket closed already
11:46:01  2020-07-15 03:49:21 ERROR   iceUtilsSendData(): operation returned status code: 0x58000022
11:46:01  2020-07-15 03:49:21 WARN    turnConnectionSendData(): iceUtilsSendData failed with 0x58000022
.............

This is the complete log file.
[wireless.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4923325/wireless.txt)

**Comment by Lion-blade** [comment]
@disa6302 Yes. I've tried several different wireless networks. But they all have this problem.Are there any limitations when the device and the Client are not on the same wireless network?

**Comment by disa6302** [comment]
@Lion-blade , 

That should not matter. The connection establishment would happen via TURN and that is what the logs indicate. Are you running the master sample as it is? Are there any modifications you are making? 

Also, there are 2 errors I see in the log. One is STATUS_SEND_DATA_FAILED (0x5800001a) which is because all the bytes could not be sent out because network is unreachable. The second error occurs because of the first error that leads to closed socket connection. 

One thing you could try is running both the master and viewer (in your case the AWS console) on the same wireless network to see if it works.

**Comment by Nomidia** [comment]
Since the wireless connection is not stable enough, Network is unreachable may occur. We can ignore the errno ENETUNREACH here. After that, it will not affect the subsequent data transmission.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/01f5160431380d8fd52777a45dba41e318b433b7/src/source/Ice/SocketConnection.h#L16-L20

```
#define CLOSE_SOCKET_IF_CANT_RETRY(e, ps)                                                                                                            \
    if ((e) != EAGAIN && (e) != EWOULDBLOCK && (e) != EINTR && (e) != EINPROGRESS && (e) != EPERM && (e) != EALREADY && (e) != ENETUNREACH) {                              \
        DLOGD("Close socket %d", (ps)->localSocket);                                                                                                 \
        ATOMIC_STORE_BOOL(&(ps)->connectionClosed, TRUE);                                                                                            \
    }

```

**Comment by MushMal** [comment]
@Nomidia looks promising! Do you mind pushing a PR with the changes?

**Comment by Nomidia** [comment]
Ok, I will push later.

**Comment by disa6302** [comment]
@Nomidia , 

Thank you for your changes! 

@Lion-blade , do you mind pulling https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/625 and checking if the issue persists?

**Comment by Lion-blade** [comment]
@disa6302 Thanks, While it still returns the error message "WARN turnConnectionSendData(): iceUtilsSendData failed with 0x5800001a", the live view works fine and no other issues have been identified as a result of this changes.

**Comment by disa6302** [comment]
Great @Lion-blade ! Will close this issue then
Do not hesitate to reach out if you face any issues.
