### ISSUE TITLE
Gstreamer not working with Raspivid

### ISSUE THREAD

**Issue by Rpi112** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#619]
Hi,

I am using Raspicam with Raspberry Pi setup to stream video to pipeline as master. When using the GSTreamer sample code (and chrome browser as viewer in another device), i am not getting any video output in viewer.

I could see from log that connection is established but there seems to be some issue with the video stream that is sent. It seems gst_parse_launch uses "autovideosrc" which is not working with raspicam.

Generally I use the below way to start gst pipeline for streaming.
raspivid -t 999999 -h 480 -w 640 -fps 25 -hf -b 500000 -o - | gst-launch-1.0 -v fdsrc ! blah blah 

Any suggestion to solve this issue is appreciated. Error log attached.

[Error Log_Kinesis.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4926401/Error.Log_Kinesis.log)

**Comment by disa6302** [comment]
@Rpi112 ,

GStreamer related questions are best directed to GStreamer forums to get answers. One thing you could try is using gst-rpicamsrc instead of raspivid. Not sure if you have a specific reason for using raspivid.

**Comment by Rpi112** [comment]
@disa6302 : Thanks.. I will try gst-rpicamsrc and check..

**Comment by Rpi112** [comment]
@disa6302 : I could get it working. It seems the problem was not with "autovideosrc" but with "x264enc". After installing gst-plugins-ugly, the problem was resolved.
