### ISSUE TITLE
[QUESTION] Does this library support TURN over UDP/DTLS?

### ISSUE THREAD

**Issue by mdonahoe** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#624]
I thought the answer was yes, but recent code comments make me think otherwise.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/ae7462f38d71823d87ed284013e2ea976b48011a#diff-ac8a6868f6ec8cad1125016a09ecb8c2R362

**Comment by lherman-cs** [comment]
@mdonahoe we currently only support UDP and TLS.

**Comment by mdonahoe** [comment]
Does that mean you support TURN over UDP? How does that work without DTLS?

I'm not an expert here, I'm just looking for a low-latency TURN connection. Thanks!

**Comment by lherman-cs** [comment]
Sorry for the confusion. Let's imagine for the case of sending a data channel message. The overall data would look as follow (this is of course an oversimplification from the actual flow, but it should still describe how packets get encrypted):

```
     Application Data
                 v
              DTLS
                 v
Transport layer (e.g. UDP/DTLS/TCP/TLS)
                 v
      Network sockets
```

From the diagram above, it shows that your application data will first get encrypted with DTLS. Then, the encrypted data will be transported in the transport layer (this is TURN in your case). So, if we use DTLS for the TURN connection, what it really means is that your encrypted data will be **reencrypted** by the DTLS from the transport layer.

So, for a low-latency TURN connection, I would suggest to pick UDP instead.

Note: DTLS can work without access to the underlying sockets, it can operate on data buffers.

**Comment by mdonahoe** [comment]
Oh I see. There is a difference between `turn:` and `turns:`

Thanks for the clarification.
