### ISSUE TITLE
[BUG] View from Master freezes while using GStreamer sample project on Google Chrome

### ISSUE THREAD

**Issue by nichatpratik** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#626]
**Describe the bug**
I am working on using the webRTC stack with a webcam feed. I have set up the Master-Viewer configuration using a GStreamer pipeline, I was successful in transferring webcam feed from the WebRTC JavaScript SDK – Viewer (browser) to the WebRTC C SDK - GStreamer Master and returned the received frames back to the browser using the WebRTC C SDK - Gstreamer Master.
 
But I observed that when we are running the WebRTC JavaScript SDK on Google Chrome  the feed from the WebRTC C SDK - Gstreamer Master was getting frozen after some time (time varies with different runs), while this wasn’t the case on using Firefox. This is an issue in Chrome, since on experiments with Firefox, I did not see the issue anymore. I request and will highly appreciate support to fix this issue. Thank you.

**SDK version number**
v1.2.0 - commit 959d259acff08c8b913faab5a3653f08cf0e409e

**To Reproduce**
1. Build SDK and run kvsWebRTCClientMasterGstreamerSample.c
2. Open up KVS Test Page and start viewer
3. Webcam feed from browser is sent to the C SDK sample project and is returned back using GStreamer pipelines.
4. After some time, the view from Master on the browser gets frozen. (Only happens in Google Chrome)

**Expected behavior**
As seen in Firefox, I can stream the video for more than 30 mins but while on Google Chrome, the view from Master freezes within a minute (differs wrt different runs)

**Desktop (please complete the following information):**
 - OS: Linux (ubuntu)
 - Browser chrome

**Additional context**

**Comment by disa6302** [comment]
@nichatpratik , 

1. Can you please provide the logs for the run? 
2. So the viewer and the master are using the same webcam, right? It is possible there is resource contention because the camera is being accessed by two applications simultaneously. But, we would not know without the logs.

**Comment by lherman-cs** [comment]
@nichatpratik any update?

**Comment by lherman-cs** [comment]
Closing, communicated with the customer offline.
