### ISSUE TITLE
[QUESTION]How to make an offer

### ISSUE THREAD

**Issue by alexareactnative1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#630]
My application is only one peer sends data while the others are listening. I want to make an offer, and then I can make a http call to create an answer. 

I looked into sample code, I add this code in my application, but it doesn't work:

`
 retStatus = createSampleConfiguration(argc > 1 ? argv[1] : SAMPLE_CHANNEL_NAME,
                                          SIGNALING_CHANNEL_ROLE_TYPE_VIEWER,
                                          TRUE,
                                          TRUE,
                                          &pSampleConfiguration);
    if(retStatus != STATUS_SUCCESS) {
        printf("[KVS Viewer] createSampleConfiguration(): operation returned status code: 0x%08x \n", retStatus);
        goto CleanUp;

    // Initalize KVS WebRTC. This must be done before anything else, and must only be done once.
    CHK_STATUS(initKvsWebRtc());

    retStatus = createOffer(pSampleStreamingSession->pPeerConnection, &offerSessionDescriptionInit);
    if (retStatus != STATUS_SUCCESS) {
        printf("[KVS] createOffer(): operation returned status code: 0x%08x \n", retStatus);
        goto CleanUp;
    }
    printf("[KVS] Offer creation successful\n");

    retStatus = setLocalDescription(pSampleStreamingSession->pPeerConnection, &offerSessionDescriptionInit);
    if(retStatus != STATUS_SUCCESS) {
        printf("[KVS] setLocalDescription(): operation returned status code: 0x%08x \n", retStatus);
        goto CleanUp;
    }
    printf("[KVS] Completed setting local description\n");
    }`

**Comment by disa6302** [comment]
What you are describing is a classic single master multi-viewer configuration if I am not mistaken. Can you give more details on who the listeners are? Is your intent to createOffer and answer in the same application?

**Comment by alexareactnative1** [comment]
My questions is answered by @disa6302
