### ISSUE TITLE
[BUG] : facing linking error while compiling statically webrtc sdk

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#636]
**Describe the bug**

**[ 64%] Linking C executable kvsWebrtcClientViewer
/opt/mips-gcc540-glibc222-64bit-r3.3.0/bin/cmake -E cmake_link_script CMakeFiles/kvsWebrtcClientViewer.dir/link.txt --verbose=1
/opt/mips-gcc540-glibc222-64bit-r3.3.0/bin/mips-linux-gnu-gcc -muclibc -lm -fPIC -muclibc  -muclibc -rdynamic CMakeFiles/kvsWebrtcClientViewer.dir/samples/Common.c.o CMakeFiles/kvsWebrtcClientViewer.dir/samples/kvsWebRTCClientViewer.c.o  -o kvsWebrtcClientViewer  -L/home/shiv/project/ingenic/ingenic_main_branch_540/camera/opensource/amazon-webrtc-sdk-c/open-source/lib -Wl,-rpath,/home/shiv/project/ingenic/ingenic_main_branch_540/camera/opensource/amazon-webrtc-sdk-c/open-source/lib: libkvsWebrtcClient.a libkvsWebrtcSignalingClient.a -lkvspicUtils ../open-source/lib/libsrtp2.a ../open-source/lib/libusrsctp.so -lkvspicState -lpthread -lwebsockets ../open-source/lib/libssl.so ../open-source/lib/libcrypto.so -lkvsCommonLws
../open-source/lib/libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
/home/shiv/project/ingenic/ingenic_main_branch_540/camera/opensource/amazon-webrtc-sdk-c/open-source/lib/libkvsCommonLws.a(Version.c.o): In function `getUserAgentString':
Version.c:(.text+0x74): undefined reference to `globalGetOsVersion'
Version.c:(.text+0xb8): undefined reference to `globalGetPlatformName'
Version.c:(.text+0xfc): undefined reference to `globalGetCompilerInfo'**

My compiling process using given cmake command:--

**cmake .. -DADD_MUCLIBC=TRUE -DBUILD_TEST=TRUE -DBUILD_OPENSSL=TRUE -DBUILD_STATIC_LIBS=TRUE  -DBUILD_OPENSSL_PLATFORM=linux-generic32 \
		 -DOPENSSL_EXTRA="no-egd;no-sse2;no-asm;no-threads;no-hw;no-zlib;no-weak-ssl-ciphers;no-static-engine" \
		 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=mips-unknown-linux-uclibcgnu  \
		 -DCMAKE_INSTALL_PREFIX=/opensource/amazon-webrtc-sdk-c/out/**

**SDK version number**
Include the SDK version you are running. If it is a specific commit on master branch, include that

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**
1. Go to '...' ---      mkdir build ; cd build ; "run cmake command that i mentioned above "; make

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lherman-cs** [comment]
@shiv50084 do you mind to check if `libkvsCommonLws.a` is statically compiled properly? You could check this by running `objdump -t libkvsCommonLws.a`. You should see that the symbols that you mentioned above are defined.

**Comment by shiv50084** [comment]
@lherman-cs 
Yes these symbols are defined in  libkvsCommonLws.a


[objdump_libkvsCommonLws.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4958348/objdump_libkvsCommonLws.txt)

**Comment by lherman-cs** [comment]
@shiv50084, sorry I misunderstood how we statically compile our dependencies, we statically link the dependencies at the end not per library. So, I saw that the symbols (globalGetOsVersion, globalGetPlatformName, and globalGetCompilerInfo) are undefined from your log. This is OK, as long as it's statically compiled later with `libkvspicUtils.a`, which contains the three missing symbols.

Could you check if `libkvspicUtils.a` compiled properly by running `objdump -t libkvspicUtils.a`?  It should show the three symbols are defined:

![Screen Shot 2020-07-22 at 9 41 44 AM](https://user-images.githubusercontent.com/15654932/88204034-b8cdd500-cc18-11ea-9a57-1e4bf7829e79.png)

To see more details on what actually happened during linking, could you recompile with `make VERBOSE=1` and share the output here?

**Comment by ycyang1229** [comment]
@lherman-cs built it just now, and did not check it further, will check it tmr if there is no progress.

[ 80%] Building C object CMakeFiles/kvsWebrtcSignalingClient.dir/src/source/Signaling/Signaling.c.o
[ 82%] Building C object CMakeFiles/kvsWebrtcSignalingClient.dir/src/source/Signaling/StateMachine.c.o
[ 84%] Linking C static library libkvsWebrtcSignalingClient.a
[ 84%] Built target kvsWebrtcSignalingClient
Scanning dependencies of target kvsWebrtcClientMaster
[ 86%] Building C object CMakeFiles/kvsWebrtcClientMaster.dir/samples/Common.c.o
[ 88%] Building C object CMakeFiles/kvsWebrtcClientMaster.dir/samples/kvsWebRTCClientMaster.c.o
[ 90%] Linking C executable kvsWebrtcClientMaster
/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libkvsCommonLws.a(Version.c.o): In function `getUserAgentString':
Version.c:(.text+0x77): undefined reference to `globalGetOsVersion'
Version.c:(.text+0xb2): undefined reference to `globalGetPlatformName'
Version.c:(.text+0xed): undefined reference to `globalGetCompilerInfo'
collect2: error: ld returned 1 exit status
CMakeFiles/kvsWebrtcClientMaster.dir/build.make:127: recipe for target 'kvsWebrtcClientMaster' failed
make[2]: *** [kvsWebrtcClientMaster] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/kvsWebrtcClientMaster.dir/all' failed
make[1]: *** [CMakeFiles/kvsWebrtcClientMaster.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$ echo ${CC}

yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$ gcc --version
gcc (Ubuntu 4.8.5-4ubuntu8) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$ ^C
yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$ git diff
diff --git a/CMake/Dependencies/libmbedtls-CMakeLists.txt b/CMake/Dependencies/libmbedtls-CMakeLists.txt
index 34d647fe..a621cee7 100644
--- a/CMake/Dependencies/libmbedtls-CMakeLists.txt
+++ b/CMake/Dependencies/libmbedtls-CMakeLists.txt
@@ -21,7 +21,7 @@ ExternalProject_Add(
   # TODO: needs to replace this with official mbedTLS branch
   #       when they add DTLS-SRTP extension support.
   # Reference: https://github.com/ARMmbed/mbedtls/pull/3235
-  GIT_REPOSITORY  https://github.com/lherman-cs/mbedtls.git
+  GIT_REPOSITORY  https://github.com/ycyang1229/mbedtls.git
   GIT_TAG         pr1813
   PREFIX          ${CMAKE_CURRENT_BINARY_DIR}/build
   CMAKE_ARGS
diff --git a/CMake/Utilities.cmake b/CMake/Utilities.cmake
index 11a3d370..43baa580 100644
--- a/CMake/Utilities.cmake
+++ b/CMake/Utilities.cmake
@@ -38,7 +38,7 @@ function(build_dependency lib_name)
   # library building cmake.
   set(build_args ${ARGN})
 
-  file(REMOVE_RECURSE ${OPEN_SRC_INSTALL_PREFIX}/lib${lib_name})
+  #file(REMOVE_RECURSE ${OPEN_SRC_INSTALL_PREFIX}/lib${lib_name})
 
   # build library
   configure_file(
@@ -61,7 +61,7 @@ function(build_dependency lib_name)
     message(FATAL_ERROR "CMake step for lib${lib_name} failed: ${result}")
   endif()
 
-  file(REMOVE_RECURSE ${OPEN_SRC_INSTALL_PREFIX}/lib${lib_name})
+  #file(REMOVE_RECURSE ${OPEN_SRC_INSTALL_PREFIX}/lib${lib_name})
 endfunction()
 
 function(enableSanitizer SANITIZER)
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7eca0ae5..62bba5ea 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -6,9 +6,9 @@ project(KinesisVideoWebRTCClient LANGUAGES C)
 # User Flags
 option(ADD_MUCLIBC "Add -muclibc c flag" OFF)
 option(BUILD_DEPENDENCIES "Whether or not to build depending libraries from source" ON)
-option(USE_OPENSSL "Use openssl as crypto library" ON)
-option(USE_MBEDTLS "Use mbedtls as crypto library" OFF)
-option(BUILD_STATIC_LIBS "Build all libraries statically. (This includes third-party libraries.)" OFF)
+option(USE_OPENSSL "Use openssl as crypto library" OFF)
+option(USE_MBEDTLS "Use mbedtls as crypto library" ON)
+option(BUILD_STATIC_LIBS "Build all libraries statically. (This includes third-party libraries.)" ON)
 option(BUILD_OPENSSL_PLATFORM "If buildng OpenSSL what is the target platform" OFF)
 option(BUILD_LIBSRTP_HOST_PLATFORM "If buildng LibSRTP what is the current platform" OFF)
 option(BUILD_LIBSRTP_DESTINATION_PLATFORM "If buildng LibSRTP what is the destination platform" OFF)
yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$ 
yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$ 
yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$ 
yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$ make VERBOSE=1
/usr/bin/cmake -H/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c -B/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build/CMakeFiles /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
make -f CMakeFiles/kvsWebrtcClient.dir/build.make CMakeFiles/kvsWebrtcClient.dir/depend
make[2]: Entering directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
cd /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build/CMakeFiles/kvsWebrtcClient.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
make -f CMakeFiles/kvsWebrtcClient.dir/build.make CMakeFiles/kvsWebrtcClient.dir/build
make[2]: Entering directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
make[2]: Nothing to be done for 'CMakeFiles/kvsWebrtcClient.dir/build'.
make[2]: Leaving directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
[ 70%] Built target kvsWebrtcClient
make -f CMakeFiles/kvsWebrtcSignalingClient.dir/build.make CMakeFiles/kvsWebrtcSignalingClient.dir/depend
make[2]: Entering directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
cd /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build/CMakeFiles/kvsWebrtcSignalingClient.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
make -f CMakeFiles/kvsWebrtcSignalingClient.dir/build.make CMakeFiles/kvsWebrtcSignalingClient.dir/build
make[2]: Entering directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
make[2]: Nothing to be done for 'CMakeFiles/kvsWebrtcSignalingClient.dir/build'.
make[2]: Leaving directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
[ 84%] Built target kvsWebrtcSignalingClient
make -f CMakeFiles/kvsWebrtcClientMaster.dir/build.make CMakeFiles/kvsWebrtcClientMaster.dir/depend
make[2]: Entering directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
cd /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build/CMakeFiles/kvsWebrtcClientMaster.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
make -f CMakeFiles/kvsWebrtcClientMaster.dir/build.make CMakeFiles/kvsWebrtcClientMaster.dir/build
make[2]: Entering directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
[ 86%] Linking C executable kvsWebrtcClientMaster
/usr/bin/cmake -E cmake_link_script CMakeFiles/kvsWebrtcClientMaster.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC  -rdynamic CMakeFiles/kvsWebrtcClientMaster.dir/samples/Common.c.o CMakeFiles/kvsWebrtcClientMaster.dir/samples/kvsWebRTCClientMaster.c.o  -o kvsWebrtcClientMaster  -L/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib -Wl,-rpath,/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib: libkvsWebrtcClient.a libkvsWebrtcSignalingClient.a -lkvspicUtils ../open-source/lib/libsrtp2.a ../open-source/lib/libusrsctp.so -lkvspicState -lpthread -lwebsockets ../open-source/lib/libmbedtls.so ../open-source/lib/libmbedx509.so ../open-source/lib/libmbedcrypto.so -lkvsCommonLws 
/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libkvsCommonLws.a(Version.c.o): In function `getUserAgentString':
Version.c:(.text+0x77): undefined reference to `globalGetOsVersion'
Version.c:(.text+0xb2): undefined reference to `globalGetPlatformName'
Version.c:(.text+0xed): undefined reference to `globalGetCompilerInfo'
collect2: error: ld returned 1 exit status
CMakeFiles/kvsWebrtcClientMaster.dir/build.make:127: recipe for target 'kvsWebrtcClientMaster' failed
make[2]: *** [kvsWebrtcClientMaster] Error 1
make[2]: Leaving directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/kvsWebrtcClientMaster.dir/all' failed
make[1]: *** [CMakeFiles/kvsWebrtcClientMaster.dir/all] Error 2
make[1]: Leaving directory '/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$

**Comment by lherman-cs** [comment]
@ycyang1229 edited your comment to format the logs properly.

**Comment by lherman-cs** [comment]
From 
```
/usr/bin/cc  -fPIC  -rdynamic CMakeFiles/kvsWebrtcClientMaster.dir/samples/Common.c.o CMakeFiles/kvsWebrtcClientMaster.dir/samples/kvsWebRTCClientMaster.c.o  -o kvsWebrtcClientMaster  -L/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib -Wl,-rpath,/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib: libkvsWebrtcClient.a libkvsWebrtcSignalingClient.a -lkvspicUtils ../open-source/lib/libsrtp2.a ../open-source/lib/libusrsctp.so -lkvspicState -lpthread -lwebsockets ../open-source/lib/libmbedtls.so ../open-source/lib/libmbedx509.so ../open-source/lib/libmbedcrypto.so -lkvsCommonLws 
```

It shows that it includes kvspicUtils properly into kvsWebrtcClientMaster binary. Could you check if the symbols exist in kvspicUtils?

Also, the linking order might give an issue? Do you mind to do a quick test with running

```
/usr/bin/cc  -fPIC  -rdynamic CMakeFiles/kvsWebrtcClientMaster.dir/samples/Common.c.o CMakeFiles/kvsWebrtcClientMaster.dir/samples/kvsWebRTCClientMaster.c.o  -o kvsWebrtcClientMaster  -L/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib -Wl,-rpath,/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib: libkvsWebrtcClient.a libkvsWebrtcSignalingClient.a ../open-source/lib/libsrtp2.a ../open-source/lib/libusrsctp.so -lkvspicState -lpthread -lwebsockets ../open-source/lib/libmbedtls.so ../open-source/lib/libmbedx509.so ../open-source/lib/libmbedcrypto.so -lkvsCommonLws -lkvspicUtils
```

Unfortunately, I can't reproduce this locally.

**Comment by shiv50084** [comment]
Thanks Lucas for your great help and Support.

I Found issue .I am also using AWS S3 parallelly. Which i compiled with old version of openssl that is creating linking issue.

**Comment by lherman-cs** [comment]
@shiv50084 I'm glad that you found the issue!
