### ISSUE TITLE
How to pass argument to sendGstreamerAudioVideo function in kvsWebRTCClientMasterGstreamerSample.c file?

### ISSUE THREAD

**Issue by thasin96** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#640]
I have modified kvsWebRTCClientMasterGstreamerSample.c sdk code to create my own pipeline. For That I have commented switch block and added my own new gstream pipeline like below. 

```
PVOID sendGstreamerAudioVideo(PVOID args)
{
    ...
     pipeline = gst_parse_launch(
                                 "rtspsrc location=rtsp-url  short-header=TRUE ! rtph264depay !" 
                                 "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video",
                                 &error);
     ...
}
```

After modifying my current code works as I expected. Now, I want to pass rtsp url dynamically. How pass argument (rtsp url) to sendGstreamerAudioVideo function?

**Comment by lherman-cs** [comment]
@thasin96 the easiest way to do that is to add a member to SampleConfiguration, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Samples.h#L42-L76. Later, SampleConfiguration will be passed to the video thread as a custom argument, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L243.

So, at the end, within `sendGstreamerAudioVideo`, you'll be able to access SampleConfiguration by casting `args`.

**Comment by thasin96** [comment]
@lherman-cs - thanks for the response. I would like to pass rtsp-url as a new argument while calling the application. My use case is I am calling kvs Gstreamer from some other services such as shell command, python service. So, I want to pass this parameter as a new argument. I guess, the suggested method will not be for my use case. Is there anyway I can pass rtsp as separate command and access the parameter in `sendGstreamerAudioVideo(PVOID`?

**Comment by lherman-cs** [comment]
@thasin96 yes, you can definitely do that with my approach.

1. Add a member to SampleConfiguration for the url:

```c
typedef struct {
   ...
   CHAR url[1024]; // <--- the new member
} SampleConfiguration, *PSampleConfiguration;
```

2. Get the url from cli args:

```c
INT32 main(INT32 argc, CHAR* argv[])
{
    STATUS retStatus = STATUS_SUCCESS;
    PSampleConfiguration pSampleConfiguration = NULL;

    ...
    retStatus =
        createSampleConfiguration(argc > 1 ? argv[1] : SAMPLE_CHANNEL_NAME, SIGNALING_CHANNEL_ROLE_TYPE_MASTER, TRUE, TRUE, &pSampleConfiguration);
    pSampleConfiguration->videoSource = sendGstreamerAudioVideo;
    pSampleConfiguration->mediaType = SAMPLE_STREAMING_VIDEO_ONLY;
    pSampleConfiguration->receiveAudioVideoSource = receiveGstreamerAudioVideo;
    pSampleConfiguration->onDataChannel = onDataChannel;
    pSampleConfiguration->customData = (UINT64) pSampleConfiguration;
    pSampleConfiguration->useTestSrc = FALSE;
 
    STRCPY(pSampleConfiguration->url, argv[2]); // <-- it's up to you how you get the url from the cli args
    ... 
    return (INT32) retStatus;
}
```

3. Extract the given url

```c
PVOID sendGstreamerAudioVideo(PVOID args)
{
    ...
     PSampleConfiguration pSampleConfiguration = (PSampleConfiguration) args;
     PCHAR url = (PCHAR) pSampleConfiguration->url;

     // create your pipeline with this dynamic url.
     pipeline = gst_parse_launch(
                                 "rtspsrc location=rtsp-url  short-header=TRUE ! rtph264depay !" 
                                 "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video",
                                 &error);
     ...
}
```

**Comment by MushMal** [comment]
I am going to resolve this issue as it's been answered. In general, this issue is not related to the SDK per-say but asks for an advice for the custom application. 

Please feel free to cut a new issue if you need more assistance
