### ISSUE TITLE
[QUESTION] How to add a token session parameter ?

### ISSUE THREAD

**Issue by longos** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#641]
In addition to AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, I have to use Session Token. This is needed for credentals from STS. How call the Session Token parameter in the system variable so that kvs can use it ?

**Comment by lherman-cs** [comment]
@longos you can set `AWS_SESSION_TOKEN` for the session token.

**Comment by lherman-cs** [comment]
Thank you for the report. We're indeed missing this from our README. https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/643 will add this documentation.

**Comment by MushMal** [comment]
The samples take the session token in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L617

I think this is indeed a documentation issue. I just pushed @lherman-cs PR so we have this updated in the readme as well
