### ISSUE TITLE
[QUESTION] Double Free?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#648]
Found in 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/Retransimitter.c

   CHK_LOG_ERR(retStatus);
    if (pRtpPacket != NULL) {
        // free the packet as it is not put back into rolling buffer
        freeRtpPacket(&pRtpPacket);
        pRtpPacket = NULL;
    }
    freeRtpPacket(&pRtpPacket);

**Comment by MushMal** [comment]
@suggestedfixes the freeRtpPacket call is idempotent so it won't do anything.

However, this is really a bizarre code and needs to be cleaned.

From what I understand, instead of the entire

```
if (pRtpPacket != NULL) {
// free the packet as it is not put back into rolling buffer
freeRtpPacket(&pRtpPacket);
pRtpPacket = NULL;
}
freeRtpPacket(&pRtpPacket);
```

We only need` freeRtpPacket(&pRtpPacket);`


@disa6302 would you please take a look at this?

**Comment by ycyang1229** [comment]
Is this bug relating to my second comment in this issue? https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/650
