### ISSUE TITLE
Make ICE timing configurable

### ISSUE THREAD

**Issue by Sean-Der** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#65]
Users may have unique requirements in certain networks, we should make the following configurable per PeerConnection

* ICE timeout intervals (may prefer to fail fast)
* Polling Intervals (May have a very lossy network, or working in a network constrained env)
* Custom configuration for nomination (how soon till we nominate, if we use TURN and don't even attempt host/reflexive candidates)

**Comment by chehefen** [comment]
resolved
