### ISSUE TITLE
[QUESTION] the git of mbedtls

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#651]
Hey, I am using gcc 4.8.5 to compile this sdk, and it did not work.
After adding this commit(https://github.com/ARMmbed/mbedtls/pull/3479/files), it worked. I also checked the gcc4.8.5 manual, and there is no ‘-Wformat-signedness’. 

Would you mind merging this commit back to your git branch? thanks.

yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$ cmake ..
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Kinesis Video WebRTC Client path is /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c
-- dependencies install path is 
-- Begin building dependencies.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libmbedtls
Scanning dependencies of target project_libmbedtls
[ 11%] Creating directories for 'project_libmbedtls'
[ 22%] Performing download step (git clone) for 'project_libmbedtls'
Cloning into 'project_libmbedtls'...
Switched to a new branch 'pr1813'
Branch 'pr1813' set up to track remote branch 'pr1813' from 'origin'.
[ 33%] No patch step for 'project_libmbedtls'
[ 44%] Performing update step for 'project_libmbedtls'
Current branch pr1813 is up to date.
[ 55%] Performing configure step for 'project_libmbedtls'
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Could NOT find Threads (missing: Threads_FOUND) 
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libmbedtls/build/src/project_libmbedtls-build
[ 66%] Performing build step for 'project_libmbedtls'
Scanning dependencies of target mbedcrypto_static
[  1%] Building C object library/CMakeFiles/mbedcrypto_static.dir/aes.c.o
cc: error: unrecognized command line option ‘-Wformat-signedness’
library/CMakeFiles/mbedcrypto_static.dir/build.make:62: recipe for target 'library/CMakeFiles/mbedcrypto_static.dir/aes.c.o' failed
make[5]: *** [library/CMakeFiles/mbedcrypto_static.dir/aes.c.o] Error 1
CMakeFiles/Makefile2:352: recipe for target 'library/CMakeFiles/mbedcrypto_static.dir/all' failed
make[4]: *** [library/CMakeFiles/mbedcrypto_static.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/project_libmbedtls.dir/build.make:111: recipe for target 'build/src/project_libmbedtls-stamp/project_libmbedtls-build' failed
make[2]: *** [build/src/project_libmbedtls-stamp/project_libmbedtls-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/project_libmbedtls.dir/all' failed
make[1]: *** [CMakeFiles/project_libmbedtls.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:61 (message):
  CMake step for libmbedtls failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:77 (build_dependency)

-- Configuring incomplete, errors occurred!
See also "/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build/CMakeFiles/CMakeOutput.log".

**Comment by ycyang1229** [comment]
https://github.com/ARMmbed/mbedtls/issues/3478

**Comment by lherman-cs** [comment]
@ycyang1229 https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/654 should fix thix

**Comment by ycyang1229** [comment]
@lherman-cs it works now. thanks.
