### ISSUE TITLE
[BUG] Invalidate/Flush SignalingCache if the Channel is not found

### ISSUE THREAD

**Issue by bkneff** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#660]
**Describe the bug**
The gstreamer sample applications will automatically create a channel if it doesn't exist.  The application will also cache this information in the Signaling FileCache.  If you delete the channel, the application will still attempt to use the cache'd value in FileCache.

**SDK version number**
acc94940

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**
1. Run the gstreamer sample and specify a channel name
2. Delete the channel via the console
3. Kill the gstreamer application
4. Re-run the gstreamer application
5. The application will error out and not re-create the channel

If you delete the FileCache and re-run it will work.

**Expected behavior**
The application will re-create the channel

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MushMal** [comment]
We should ensure that if the cached operations fail they will have to run the non-cached version after the state machine retries.

**Comment by disa6302** [comment]
Pending implementation.

**Comment by disa6302** [comment]
Closing since this is not an issue in the newer version anymore. Exponential retry covers this case.
