### ISSUE TITLE
[QUESTION] static build failed because of libwebsockets

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#663]
Some error happened when doing static build. Checked the issue on the github of libwebsockets, and it may be the same problem. 
https://github.com/warmcat/libwebsockets/issues/1975
https://libwebsockets.org/git/libwebsockets/commit?id=c8baeccfd76d324c1454cb9b57bf01a95ad5b500

I fixed it by adding -lcap into the amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/pkgconfig/libwebsockets.pc

Name: libwebsockets
Description: Websockets server and client library
Version: 3.2.3

Libs: -L${libdir} -lwebsockets **-lcap**
Cflags: -I${includedir}

Error log:
/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Signaling/FileCache.c:222:22: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 10 has type ‘UINT64’ [-Wformat=]
[ 78%] Building C object CMakeFiles/kvsWebrtcSignalingClient.dir/src/source/Signaling/LwsApiCalls.c.o
[ 80%] Building C object CMakeFiles/kvsWebrtcSignalingClient.dir/src/source/Signaling/Signaling.c.o
[ 82%] Building C object CMakeFiles/kvsWebrtcSignalingClient.dir/src/source/Signaling/StateMachine.c.o
[ 84%] Linking C static library libkvsWebrtcSignalingClient.a
[ 84%] Built target kvsWebrtcSignalingClient
Scanning dependencies of target kvsWebrtcClientMaster
[ 86%] Building C object CMakeFiles/kvsWebrtcClientMaster.dir/samples/Common.c.o
[ 88%] Building C object CMakeFiles/kvsWebrtcClientMaster.dir/samples/kvsWebRTCClientMaster.c.o
[ 90%] Linking C executable kvsWebrtcClientMaster
/home/yc/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libwebsockets.a(unix-caps.c.o): In function `lws_plat_drop_app_privileges':
unix-caps.c:(.text+0x341): undefined reference to `cap_get_proc'
unix-caps.c:(.text+0x35d): undefined reference to `cap_set_flag'
unix-caps.c:(.text+0x365): undefined reference to `cap_set_proc'
unix-caps.c:(.text+0x385): undefined reference to `cap_free'
unix-caps.c:(.text+0x391): undefined reference to `cap_get_proc'
unix-caps.c:(.text+0x3a9): undefined reference to `cap_set_flag'
unix-caps.c:(.text+0x3b1): undefined reference to `cap_set_proc'
unix-caps.c:(.text+0x3d1): undefined reference to `cap_free'
collect2: error: ld returned 1 exit status
CMakeFiles/kvsWebrtcClientMaster.dir/build.make:127: recipe for target 'kvsWebrtcClientMaster' failed
make[2]: *** [kvsWebrtcClientMaster] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/kvsWebrtcClientMaster.dir/all' failed
make[1]: *** [CMakeFiles/kvsWebrtcClientMaster.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
yc@yc-Inspiron-3470:~/_workspace/iot-lab/amazon-kinesis-video-streams-webrtc-sdk-c/build$

**Comment by disa6302** [comment]
@ycyang1229 , 

Can you create a PR to add the -lcap flag?
