### ISSUE TITLE
[QUESTION] static build did not work

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#665]
I did static build of webrtc but kvsWebrtcClientMaster still linked to dynamic libraries. I removed all the lib inside ../open-source and libkvs* inside ../build, and it did not work alone. 

Can kvsWebrtcClientMaster work alone when setting BUILD_STATIC_LIBS as ON?

**Comment by disa6302** [comment]
Looks like this is being handled in #664 . Closing this as duplicate.
