### ISSUE TITLE
[BUG] how can i play pcmulaw and pcmalaw on client 

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#667]
**Describe the bug**

I tried pcmalaw audio stream from encoder at 8K sample rate but I didn't able to listen audio on test page
https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html and android generic APP

How can I test pcm alwa and ulaw audio ?

Is there any specific requirements for pcm alaw and ulaw audio to play with test page or app?

Or we need to test any specific bitrate and sampling rate to encoder to test with test page?
Can you please suggest for this?

We initialize Camera PCMAlaw Audio encoder with following params:-
rate=8000, channels=1, format=S16LE.

And whatever audio frame we are getting from CAM encoder . we writing that frame directly without any changes on API:- "writeFrame"

**SDK version number**
I am using master branch with latest changes. with commit id: -bc0f38daa4438016fbc9b60492856125c3746e84

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shiv50084** [comment]
When i am sending a Audio from JS test page .I am getting a noise with actual audio while I am sending a audio from generc APP i am getting proper voice on Camera device to play.


But While I am sending a Audio from Camera device to APP or JS test page.I am not getting any audio not even Noise .So we can confirm that we are able to send audio from Camera device to client (APP/ JS test page).


Can you please help for this?

**Comment by shiv50084** [comment]
[event_log_latest_20200728_1524_26_16.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4987469/event_log_latest_20200728_1524_26_16.log)
[webrtc_internals_dump.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4987471/webrtc_internals_dump.txt)


PFA  chrome://webrtc-internals/

for audio issue not able to play on webrtc Client send from Camera device;


for this i am using sample "kvsWebRTCClientMaster" and modifed according to us minor change to send audio and video only.

in function "createSampleStreamingSession" i make support for ALAW

    CHK_STATUS(addSupportedCodec(pSampleStreamingSession->pPeerConnection, RTC_CODEC_ALAW));
    audioTrack.codec = RTC_CODEC_ALAW;

after using this i am able to play audio sent from APP or JS testing page on camera device .But i am not able to play audio sedn from cam device to APP or JS page.

**Comment by MushMal** [comment]
We do support rtp codecs for g711 indeed. I am not yet sure what's going on with the device you have - you might want to debug it further as we won't be able to help with that. 

The RTP packetization happens here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Rtp/Codecs/RtpG711Payloader.c

**Comment by shiv50084** [comment]
@MushMal 

I already seen this function to create g711 rtp packet. 

One thing I want to know?
You are sending g711 rtp packet immediately after creating rtp packet or you creating a buffer of fixed size to send it to viewers?
Bcz I am receiving opus frame size exactly same what i am sending. 

But for g711 it's not like that.

**Comment by MushMal** [comment]
Each one of these has its own rules for packing into mtu. The RTP packets get encrypted before they are saved in the jitter buffer and sent in the meanwhile. The jitter buffer is needed for re-transmission.

**Comment by shiv50084** [comment]
@MushMal 
Thanks for your great help and support. 

We fixed this issue its mainly bcz of wrong timestamp.

**Comment by sylvain-fano** [comment]
@shiv50084 
We are experiencing the exact same problem with a camera here. 
h264 video stream is smooth, but pcma audio stream is garbage ... 

audio stream is : 

- pcm alaw
- 8000hz
- 16 bits
- non signed
- 1 channel (mono)

to debug where the issue was, we tried to record audio stream to sdcard instead of sending it to aws kvs lib. Audio is OK. 

I saw you fixed your issue by fixing wrong timestamps... can you detail a little bit more pls ?

**Comment by shiv50084** [comment]
@sylvain-fano 

after calculating encoder sampling time which we set same i set in
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Samples.h#L24


for example at 8KHz in 1ms we received 8 bytes of audio packets. same we received 160 bytes in 20ms. according to you calculate your encoder sampling time and how many bytes you are getting and change according to the audio sampling time for sync issue.

**Comment by sylvain-fano** [comment]
@shiv50084 

ok, got it. 
thank you for the tip, i think this part could be more detailed in documentation for SDK C producer IMHO
