### ISSUE TITLE
[BUG] ERROR   dtlsSessionProcessPacket(): operation returned status code:  STATUS_SSL_PACKET_BEFORE_DTLS_READY (0x59000004)

### ISSUE THREAD

**Issue by vixtor-qm** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#668]
**Describe the bug**
I'm running a simple loopback test with the C SDK. everything works fine when I use AWS test page for WebRTC streaming.
But a kvsWebrtcClientviewer is unable to receive the stream with the error and hangs

**SDK version number**
I use master branch

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 16.04

**Comment by lherman-cs** [comment]
@vixtor-qm do you mind to share the logs from kvsWebrtcClientviewer by rerunning it with `export AWS_KVS_LOG_LEVEL=2`?

**Comment by vixtor-qm** [comment]
Hi @lherman-cs,
Here are the recent logs

[master.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4983084/master.log)
[viewer.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4983085/viewer.log)

**Comment by lherman-cs** [comment]
@vixtor-qm I'm not sure what kind of packets that arrived before the DTLS handshaking is finished. But, this should be OK, when this happens, we simply ignore the packet. From the logs, I saw that there's no issue in master and viewer, both showed that the ICE agent state successfully changed to ICE_AGENT_STATE_READY.

**Comment by vixtor-qm** [comment]
@lherman-cs , thanks for your efforts. The reason I'm asking this question is that I'm not receiving the packet with a payload on my viewer's side as it should. The viewer registers the callback to print out the content but it seems that it is not called. 

`    retStatus = transceiverOnFrame(pSampleStreamingSession->pAudioRtcRtpTransceiver, (UINT64) pSampleStreamingSession, sampleFrameHandler);
`
The callback code:
`
VOID sampleFrameHandler(UINT64 customData, PFrame pFrame)
{
    UNUSED_PARAM(customData);
    DLOGV("Frame received. TrackId: %" PRIu64 ", Size: %u, Flags %u", pFrame->trackId, pFrame->size, pFrame->flags);
}

`

**Comment by lherman-cs** [comment]
@vixtor-qm did you set the log level to verbose, `export AWS_KVS_LOG_LEVEL=1`? `DLOGV` only prints out in verbose level, otherwise it's just a noop.

**Comment by MushMal** [comment]
@vixtor-qm could you please either enable the verbose logs or change the handling code in the callback and update the thread with your findings.

**Comment by vixtor-qm** [comment]
@lherman-cs , @MushMal, I have set the verbose level to 1 and how I see the packets. Thank you for the support
