### ISSUE TITLE
getNextNaluLength(): Warning: Failed to get the next NALu in H264 payload with 0x5c000003

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#669]
**Describe the bug**
We are getting this error when writing H264 frames with SPS+PPS+ (I or P frame). We writing direct encoder frame from Camera to webrtc API writeFrame :- 
**2020-07-27 13:07:56 DEBUG   getNextNaluLength(): Warning: Failed to get the next NALu in H264 payload with 0x5c000003
2020-07-27 13:07:56 ERROR   writeFrame(): operation returned status code: 0x5c000003**

We taken latest changes from git. 

**SDK version number**
I am using master branch with latest changes. with commit id: -bc0f38daa4438016fbc9b60492856125c3746e84

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**
1. Go to '...' we are using direct frame from Camera encoder and writing it to webrtc API.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MushMal** [comment]
This is an indication that your frames are not in proper Annex-B format:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/507dbd130ba534865a757c7157f82720bb2c0175/src/source/Rtp/Codecs/RtpH264Payloader.c#L91

You might want to check the source of the frames and ensure they are Annex-B
