### ISSUE TITLE
[QUESTION] Android receives video with delay

### ISSUE THREAD

**Issue by sochildish** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#682]
Android receives video with delay

**Comment by MushMal** [comment]
@sochildish could you please include a little more information with your question/issue? As is, it's not actionable or we won't be able to help. Please include full details of what you are attempting to do, what's your setup, OS, commit version, etc... If this is regarding Android WebRTC then this is not the right repository for the question and you might redirect it to https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android

**Comment by disa6302** [comment]
Closing this issue since it has gone stale. Feel free to open a new issue with any queries you might have. Thanks!
