### ISSUE TITLE
[BUG]  Uninitialized array of type struct lws_protocols causes memory issue

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#683]
For SignalingClient, pSignalingClient->signalingProtocols (of type struct lws_protocols) is not initialized. This array is used in creating lws client connection.  If the per_session_data_size field of struct lws_protocols happens to be big non-zero number, then libwebsocket will report out of memory.

In file src/source/Signaling/Signaling.c line #76, please add
MEMSET(pSignalingClient->signalingProtocols, 0, sizeof(pSignalingClient→signalingProtocols));

For blockingLwsCall in amazon-kinesis-video-streams-producer-c repo (used for IoT credentialing)
 , lwsProtocols (of type struct lws_protocols) is not initialized.   This array is used in creating lws client connection.  If the per_session_data_size field of struct lws_protocols happens to be big non-zero number, then libwebsocket will report out of memory.  We have seen OOM while calling IoT credentialing

In amazon-kinesis-video-streams-producer-c repo, file src/source/Common/Lws/LwsCall.c, line #23, please add
MEMSET(lwsProtocols, 0, sizeof(lwsProtocols));

My account doesn't have authorization to push and create PR.  So, please help me make the change

**Comment by MushMal** [comment]
For the signaling client, the field is of a fixed size: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/Signaling.h#L253

the entire structure gets calloc-ed which zeroes it out: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/Signaling.c#L25

and gets set to the actual protocols with: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/Signaling.c#L76-L79


However, this code is the culprit: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/source/Common/Lws/LwsCall.c#L18

This needs to be memset to zero. Will provide a fix ASAP

**Comment by zwei333** [comment]
Thanks!

**Comment by lherman-cs** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/684 will include the fix.

**Comment by MushMal** [comment]
Fix is in. Closing
