### ISSUE TITLE
[BUG] sampleStreamingSessionList multi-thread access

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#685]
Is there a race condition while accessing `sampleStreamingSessionList`?

`sampleStreamingSessionList` is cycled around https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L808
and it is accessed while new video sample is available https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c#L239

Assume the following order of executions
1. new sample is available, `updatingSampleStreamingSessionList` is false
2. start to cycle `sampleStreamingSessionList`,  set `updatingSampleStreamingSessionList` true
3. `streamingSessionListReadingThreadCount` is zero as nobody reads it yet
4. `streamingSessionListReadingThreadCount` is incremented in `sendVideoPackets`, and start to push data to each session
5. `sampleStreamingSessionList` is cycled

**Comment by staowyze** [comment]
btw: is `pSampleConfiguration->streamingSessionCount` protected by `pSampleConfiguration->sampleConfigurationObjLock`?
I am trying to optimize `sendVideoPackets` a bit, i.e. don't read file from the disk if no viewers.

**Comment by MushMal** [comment]
There is indeed a race condition here (however small but there is a race) when the lines in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c#L238-L239 intermesh with https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L808-L809

I think we should simply interlock these as providing atomicity across two variable indicators is not possible without higher-order lock.
