### ISSUE TITLE
[FEATURE] Switch from TURN to STUN during run time

### ISSUE THREAD

**Issue by codingspirit** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#694]
**Is your feature request related to a problem? Please describe.**

In some scenarios, STUN might takes much longer time to establish connections while TURN is much faster.
i.e. TURN might takes 1 sec to start tranfering video stream, STUN might takes 6.

To improve user experiences and cost down, developer want to try both TURN and STUN at the same time when creating connection. When TURN is success and video stream already showed to user, they still want to try STUN in background. Once STUN is established, they want to switch from TURN to STUN.

**Describe the solution you'd like**
KVS WebRTC C SDK provides a way to maintain both TURN and STUN at the same time, developer can decide to swich during run time.

**Describe alternatives you've considered**

**Additional context**

**Comment by disa6302** [comment]
@codingspirit , 

The way the WebRTC stack works is it tries STUN first and then TURN if STUN is unsuccessful. What you are requesting seems to be similar to ICE renomination which would allow switching network routes at a later point of time. (#350) 

I will let @chehefen to give more insight into this.

**Comment by hassanctech** [comment]
Will be addressed as part of: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/350
