### ISSUE TITLE
[QUESTION] Too many onRtcpReceiverReport messages

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#699]
I'm receiving a lot of these messages, when running Kinesis on my hardware:
onRtcpReceiverReport(): RTCP_PACKET_TYPE_RECEIVER_REPORT rttPropDelay

What does these messages mean? How can I fix this?

**Comment by disa6302** [comment]
@fernandoc1 , 

Apologies for the log spew. There is a PR that includes this change. But, let me push a new PR to fix this.
