### ISSUE TITLE
How to see kvsWebrtcClientViewer's received frames

### ISSUE THREAD

**Issue by franktseng0718** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#705]
I am a beginner to KVS. I want to try some sample codes in amazon-kinesis-video-streams-webrtc-sdk-c/samples. I've run kvsWebrtcClientMasterGstSample and run another kvsWebrtcClientViewer to receive incoming streaming. I've seen some messages like below on my viewer's terminal.

>  2020-08-14 08:21:43 WARN    onFrameDroppedFunc(): Frame with timestamp 18097200 is dropped!

> 2020-08-14 08:21:33 DEBUG   lwsWssCallbackRoutine(): Client is writable

I think it did received frames successfully.But I wonder how to see the incoming streaming with kvsWebrtcClientViewer. I cannot find where the incoming frames were received and placed in the code.

**Comment by lherman-cs** [comment]
We currently only listen to audio frames. The code is specified here:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/e2fad0b46c5ae8ccfae5fd600c523c97f9cf8b3e/samples/kvsWebRTCClientViewer.c#L105-L109

**Comment by franktseng0718** [comment]
Hey! Is this SDK gonna support listening to video frames and show it on the screen? BTW is WebRTC SDK in Unity gonna be available in the future?

**Comment by franktseng0718** [comment]
`retStatus = transceiverOnFrame(pSampleStreamingSession->pAudioRtcRtpTransceiver, (UINT64) pSampleStreamingSession, sampleFrameHandler); `
If the code here means listen to audio frames, where are the audio frames be placed? 
If I add this line below, can I listen to video frames?
` retStatus = transceiverOnFrame(pSampleStreamingSession->pVideoRtcRtpTransceiver, (UINT64) pSampleStreamingSession, sampleFrameHandler); ` 
But I don't just want to 'listen' to frames, I want to hear the voices and see the video streaming ,how do I achive it?

**Comment by MushMal** [comment]
@franktseng0718 the SDK provides a low-level functionality for sending and retrieving audio/video data in a few supported formats. The transceiverOnFrame API sets a callback function that will be called when a frame/sample is received by the transceiver. It's then up to the layer above it to do something with it. In many higher-level applications such as av/playback engines, the frames get A/V synced, decoded and rasterized on the actual hardware - display (for video) and speakers (for audio). 

In order for your application to "hear" the frames, you will need to

1) Setup the callback to receive the frames from the peer
2) Setup a decoder to decode the frames specific to your codec
3) Understand how your target device/platform/OS processes audio and "render" the audio in your application.


Many platforms provide off-the-shelf support. For example, Android or iOS have an integrated playback stack. Perhaps, you need to look into it.

**Comment by disa6302** [comment]
Closing this. @franktseng0718 , feel free to reopen/open a new issue if you have any questions!
