### ISSUE TITLE
usrsctp_connect return -1

### ISSUE THREAD

**Issue by sochildish** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#706]
It can transmit audio and video normally , but I can't send strings using datachannel

SDK version 1.3.0

**Comment by MushMal** [comment]
Could you please attach debug logs and describe your scenario and the assets you are using?

**Comment by sochildish** [comment]
[logs.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5081719/logs.log)
this is my logs， thanks

**Comment by sochildish** [comment]
Sorry, now, the device can receive messages from the Android side, but the message sent by the device side cannot be received by the Android terminal

The interface I called is < datachannelsend >, and the parameter < prtcdatachannel > is the second input parameter of the function < ondatachannel (Uint64 customdata, prtcdatachannel, prtcdatachannel) > in the common. C file

Do I need to call the function < createdatachannel > to send messages to Android

**Comment by chehefen** [comment]
yes you need to do createdatachannel in order to send.

**Comment by sochildish** [comment]
@chehefen 
 CHK_STATUS(createDataChannel(pSampleStreamingSession->pPeerConnection, (PCHAR) "test", NULL, &pSampleStreamingSession->pRtcDataChannel));

    CHK_STATUS(dataChannelOnOpen(pSampleStreamingSession->pRtcDataChannel, (UINT64) &pSampleStreamingSession->datachannelLocalOpenCount, dataChannelOnOpenCallback));

    dataChannelOnMessage(pSampleStreamingSession->pRtcDataChannel, (UINT64) pSampleStreamingSession, onDataChannelMessage); 

I created and opened a datachannel, but this channel still can't be used to send data, only to receive data. Did I do something wrong?

**Comment by sochildish** [comment]
Thank you. My problem has been solved
