### ISSUE TITLE
[QUESTION] The minimum steps to connect to peer

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#707]
I'm having a lot of trouble connecting Kinesis. There are some times that the application fails with these messages:

<pre>
[KVS Master] Using trickleICE by default
Reading key and certificate
[KVS Master] Created signaling channel L1HEMPNBA9XG5YDF111A
[KVS Master] Finished setting audio and video handlers
[KVS Master] KVS WebRTC initialization completed successfully
[KVS Master] Signaling client created successfully
2020-07-20 16:42:03 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
2020-07-20 16:42:03 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
2020-07-20 16:42:04 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
2020-07-20 16:42:05 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
2020-07-20 16:42:06 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
2020-07-20 16:42:10 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
2020-07-20 16:42:16 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
2020-07-20 16:42:29 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
2020-07-20 16:42:29 ERROR   signalingConnectSync(): operation returned status code: 0x0000000f
[KVS Master] signalingClientConnectSync(): operation returned status code: 0x0000000f 
[KVS Master] Terminated with status code 0x0000000f[KVS Master] Cleaning up....
[KVS Master] Cleanup done
</pre>

I'm having a hard time following the code to find what are the step until the code reaches this failure.
So I would like to ask:
What are the minimum steps to connect to Amazon an start listening to the Websocket for incoming connections?
I need this just to check/debug whether the problem is with my connection (which I doubt that is the case, since I can ping anywhere) or if it is another issue.

**Comment by MushMal** [comment]
There really isn't enough information in the log to debug it. The connectivity issue could be caused by a number of issues:

* Check whether you have the appropriate rights 
* Check whether you have proper network connection - some firewalls will not allow bidirectional communication
* Once the above two have panned out, you might want to enable debug spew from the libWebSockets itself

for that you will need to 

* enable debug logging for KVS embedded SDK
* uncomment the https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/CMake/Dependencies/libwebsockets-CMakeLists.txt#L43 to enable debug build
* delete the existing libWebSockets.so binary and re-build it, this time with the debug mode
* Modify https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/LwsApiCalls.c#L260 to OR with LLL_DEBUG

**Comment by disa6302** [comment]
@fernandoc1 , 

Any updates?

**Comment by fernandoc1** [comment]
I'm just preparing a code to share with about these steps.
I would like to have a clear view of the steps that are being done, until the connection is established and the peers begun to exchange data. It would be nice to have the smallest code possible to just debug when the connection fails.
I'm having a lot of trouble here seeking what are the causes of some connections to fail.
One think that is always happening is that I need to try twice or more, until the streaming starts successfully. Sometimes I just need to kill the master application and restart it again in order to succeed. Sometimes the application just work in the first try.
I have activated some debug, but I can't figure out any problems. I can't agree that I'm having network issues, because the camera is very responsive for every network service I try.

**Comment by MushMal** [comment]
Your issue is not p2p connection - the logs you had attached indicate you have an issue with the signaling. Please try to use the stock master sample and see if what works. If not, attach the debug logs so we can try to help debugging

**Comment by disa6302** [comment]
@fernandoc1 , 

Closing this issue since it is stale. Feel free to open a new issue if you have any questions. Thanks!

**Comment by fernandoc1** [comment]
Hi @disa6302 
I was just looking at the history commits from Kinesis and I found something that is very interesting here:
[Manual signaling](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/8a79ff0760cac72d0d3bed020bbf4edc427e5f35/samples/kvsWebRTCClientMaster.c)
I would be very happy if I could use this code to check P2P connections without the need of the signaling.
I just want to be able to test things separated. It is very common in my camera to have the signaling phase failing and I can't figure out what is happening wrong. If I could just use an alternate signaling channel, it would be nice to check where is the problem.
Many thanks for your attention.

**Comment by MushMal** [comment]
@fernandoc1 the WebRTC spec does not specify the signaling methods. The Signaling service and it's client that's part of the embedded WebRTC SDK is purely AWS concept and thus, it requires the AWS integration. There is also another part that requires AWS integration which is TURN and STUN. If you don't use these then you can simply use the WebRTC pieces directly and specify your TURN and STUN URIs. You could also use some other means for signaling, including a variety of SIP protocols and their implementations. Unfortunately, we won't be able to give any guidance on it.

P.S. Regarding the signaling - you might want to narrow down and file an issue perhaps to track these down.
