### ISSUE TITLE
[BUG] race condition in freeSampleConfiguration

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#709]
see https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L780
before accessing `sampleStreamingSessionList`, should acquire `sampleConfigurationObjLock`?

**Comment by disa6302** [comment]
@staowyze , 

Fixed this in #739. Closing
