### ISSUE TITLE
[QUESTION] Streaming a raw h264 stream

### ISSUE THREAD

**Issue by chertov** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#710]
Streaming a raw h264 stream

Hello! How can i send my custom raw h264 stream from hardware encoder?
In an example we have 1500 files.. Each file contains few NALs (with prefix 0x00_00_00_01), and the first NAL of each file is AUD (Access Unit Delimiter) NAL. Should i put this NAL in every buffer of Frame structure when i call the __writeFrame__ function?
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/96704f1511d6cea8f33b9f538a9e3344ca57c0f0/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1639

Why enum RTC_CODEC has RTC_CODEC_H264_PROFILE_42E01F_LEVEL_ASYMMETRY_ALLOWED_PACKETIZATION_MODE value with profile and level? Can i send a h264 stream with different profile/level?
How should i pack my custom h264 into __struct Frame__ buffer?
I'm trying to send
```
1. writeFrame( Frame(0x00_00_00_01 sps, 0x00_00_00_01 pps, 0x00_00_00_01 idr I) )
2. writeFrame( Frame(0x00_00_00_01 non-idr P) )
3. writeFrame( Frame(0x00_00_00_01 non-idr P) )
.....
25. writeFrame( Frame(0x00_00_00_01 non-idr P) )
26. writeFrame( Frame(0x00_00_00_01 sps, 0x00_00_00_01 pps, 0x00_00_00_01 idr I) )
27. writeFrame( Frame(0x00_00_00_01 non-idr P) )
28. writeFrame( Frame(0x00_00_00_01 non-idr P) )
.....
```
but i can't see the video in chrome..
chrome://webrtc-internals shows only an increasing key frame counter, other counters is zero

I want to find a right way to stream a custom h264 stream.. 
Thanks!

**Comment by MushMal** [comment]
Hi @chertov 

Sorry for the delay. In case of video, the current embedded SDK supports only variants of h264 and vp8. Unfortunately, when it comes to WebRTC/RTP, supporting a particular transceiver type means both the elementary stream and the packaging and it's type. In this case, the the RTC_CODEC_H264_PROFILE_42E01F_LEVEL_ASYMMETRY_ALLOWED_PACKETIZATION_MODE mode has a few implications, including the fact that the NALus should be in Annex-B mode. You don't need to have AUD NALu though.

The handling of the frame assembly from RTP packets (depaying) is done in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Rtp/Codecs/RtpH264Payloader.c#L227 depayH264FromRtpPayload API.

The comments state the RFCs we try to confirm with.


If you have the control of your own peers, you can use any format you want. If you want a generic peer like Chrome, you will need to adhere to the RFCs.

Not sure if I answered your questions but you could post a more targeted questions after you go over the information I just provided

**Comment by disa6302** [comment]
@chertov , 

Closing this assuming your question is answered. Feel free to open a new issue if you have any questions. Thanks!
