### ISSUE TITLE
Viewer cannot view the live video stream

### ISSUE THREAD

**Issue by pai-da-xin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#714]
* After I successfully run the kvsWebrtcClientMaster, I can't start the viewer to receive audio and video frames in the kvs webrtc test page, but I can view the video sent by the kvsWebrtcClientMaster in the kVs console.

* In addition, how can I use amazon-kinesis-video-streams-webrtc-sdk-c to display the real-time images captured by the embedded device camera on Amazon echo show.This is the task that I want to accomplish most at present. There are some ideas, but the specific aspects are not very clear.I hope we can find the answer.

Thanks.

**Comment by MushMal** [comment]
Could you please provide more info on your first question like the logs and what exactly you are actually seeing?

Regarding the second question... You need to actually build the media pipeline path to decode and display the frames. You have not provided any information about your target platform and many platforms have their build-in media pipelines. For a more generic solution you could look into integrating with GStreamer

**Comment by pai-da-xin** [comment]
@MushMal I want to use Amazon echo show to control the third-party camera through the Alexa skill kit and display the real-time picture on the echo show screen,Also need to build media pipeline path.
* In addition,How can I make sure that a third-party camera supports webrtc, just burn amazon-kinesis-video-streams-webrtc-sdk-c to the camera.

**Comment by pai-da-xin** [comment]
@MushMal This is a part of the log that I failed to print when I started viewer in the kvs webrtc test page after I successfully ran the kvswebrtcclientmaster.But I can see the video using the media playback viewer on the kvs console.

> [2020-08-19T06:32:02.670Z] [INFO] [VIEWER] Starting viewer connection
[2020-08-19T06:32:14.338Z] [INFO] [VIEWER] Connected to signaling service
[2020-08-19T06:32:14.346Z] [ERROR] [VIEWER] Could not find webcam

**Comment by MushMal** [comment]
As it explicitly states - it can’t find a webcam in your device. The JS sample requires a web camera. If you are using a notebook then please ensure you have the lid of the notebook open to enable the camera

**Comment by pai-da-xin** [comment]
@MushMal  Thank you very much for your reply.
