### ISSUE TITLE
[QUESTION][BUG?] gst pipeline configuration - RTCP_PACKET_TYPE_RECEIVER_REPORT size 4

### ISSUE THREAD

**Issue by Yannholo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#717]
We plan to use the webrtc-sdk-c to join a webrtc video chat from an embedded device.

### producer-sdk-cpp
First, I followed the producer-sdk-cpp and achieved a video stream with a webcam and gst-launch-1.0.
```
gst-launch-1.0 v4l2src do-timestamp=TRUE device=/dev/video4 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc bframes=0 key-int-max=45 bitrate=500 ! video/x-h264,stream-format=avc,alignment=au,profile=baseline ! kvssink stream-name="XXX" storage-size=512 access-key="XXX" secret-key="XXX" aws-region="XXX"
```
### webrtc-sdk-c
Next, as the producer-sdk-cpp was not really what we needed I looked at webrtc-sdk-c.

The samples with the `testsrc` video and audio works well, I started having trouble when trying to stream a webcam.

The `./kvsWebrtcClientMasterGstSample XXX video-only` don't seams to work on my machine, so I tried to apply the gst-launch-1.0 magic to the sample project.

I have tried multiple combination of gst pipeline but none worked for me : 
```
"v4l2src device=/dev/video4 ! "
"queue ! "
"videoconvert ! "
"video/x-raw,width=1280,height=720,framerate=30/1 ! "
"x264enc bframes=0 speed-preset=veryfast bitrate=512 byte-stream=TRUE tune=zerolatency ! "
"video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! "
"appsink sync=TRUE emit-signals=TRUE name=appsink-video "
```

For my tests I use the [WebRTC SDK Test Page](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html) (on chrome and firefox).

The test video (and audio) works fine.
I also use two webcams because I was worried that they may be some sort of exclusive access.

I noticed a difference between the logs of the test video and the webcam pipeline configuration.
The webcam pipeline never seam to successfully handle `RTCP_PACKET_TYPE_RECEIVER_REPORT` all of them come back as :
```
WARN    onRtcpReceiverReport(): unhandled packet type RTCP_PACKET_TYPE_RECEIVER_REPORT size 4
```
The video sample only has a few `size 4` error and correctly print them most of the time.

[video-only.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5096924/video-only.log)
[webcam.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5096925/webcam.log)

I don't really know if this is a bug or a simple configuration issue on my end.
Let me know if I can give you more insight on my issues.

**Comment by MushMal** [comment]
Not yet sure why the size is 4 for this packet type. The code enforces min 28 bytes per https://tools.ietf.org/html/rfc3550#section-6.4.2

Anyone?

**Comment by disa6302** [comment]
@Yannholo , 

A few questions:

1. What webcam are you using? 
2. Can you run your application with GST_DEBUG=4 to see if anything is wrong with your pipeline? One more thing you can try is run your webrtc pipeline with fakesink in gst-launch-1.0 and see if it works. If it doesnt then you will have to check your pipeline.
3. In case of video-only, is your camera source the machine's webcam? What machine are you using?

**Comment by Yannholo** [comment]
@disa6302 

With the help of fakesink I was able to find the issue :+1: .
It seams that the resolution 1280x720 does not work with the pipeline.

This pipeline works :
```
"v4l2src do-timestamp=TRUE device=/dev/video0 ! "
"queue ! "
"videoconvert ! "
"video/x-raw,width=640,height=480,framerate=30/1 ! "
"x264enc bframes=0 speed-preset=veryfast bitrate=512 byte-stream=true tune=zerolatency ! "
"video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! "
"appsink sync=TRUE emit-signals=TRUE name=appsink-video "
```

1. We have multiple webcams, all of them works with the 480p pipeline but not with the 720p
    - https://www.logitech.fr/fr-fr/product/hd-webcam-c270 (should output 720p)
    - The integrated webcam of my Thinkpad T14s (AMD) (should output 720p)
    - Several shady endoscope style camera (some are rated for 720p)
1. I mostly used fakesink to debug the pipeline (here is the 720p gst-launch-1.0 log)
    ```
    Définition du pipeline à PAUSED...
    Le pipeline est actif et n’a pas besoin de phase PREROLL…
    Passage du pipeline à la phase PLAYING…
    New clock: GstSystemClock
    ERREUR : de l’élément /GstPipeline:pipeline0/GstV4l2Src:v4l2src0 : Internal data stream error.
    Information de débogage supplémentaire :
    gstbasesrc.c(3072): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
    streaming stopped, reason not-negotiated (-4)
    Execution ended after 0:00:00.000621035
    Définition du pipeline à PAUSED...
    Définition du pipeline à READY (prêt)…
    Définition du pipeline à NULL…
    Libération du pipeline…
    ```
1. For the video-only I was using the testsrc option, the source was gstreamer videotestsrc

I guess I can close the issue here as it seams that my problem comes from gstreamer.

Thanks for the help.
