### ISSUE TITLE
How to receive audio back from Viewer

### ISSUE THREAD

**Issue by jvasanthan** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#720]
Hi Team, 
I am running amazon-kinesis-video-streams-webrtc-sdk-c as master(in Device) and Android app as Viewer. I am able to stream sample H.264 video and opus audio frames from master to viewer. How to send audio from viewer(Android) and play it back in the master(device). There is an option to select "Send Audio" in the Android app but that doesn't work. How to test this feature? 

Regards,
James

**Comment by MushMal** [comment]
@jvasanthan the samples are not attempting to play back audio. When you build an application, you have to write code that handles the audio by handling the transceiver on frame callback and then decoding and rendering audio on your device.

**Comment by jvasanthan** [comment]
@MushMal Yes I am aware that sample doesn't playback audio. The issue is I am not receiving the audio frames, does the sample application show the received audio frame in the terminal?

**Comment by MushMal** [comment]
Here is the callback that should be called on a successful audio frame received: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/kvsWebRTCClientMaster.c#L329

**Comment by jvasanthan** [comment]
@MushMal I am trying to test it. I have deleted my previous repo, cloned new one and building again but cmake got stuck at the below step for more than an hour. Tried multiple times, restarted VM(running Ubuntu in VM) & host, Internet connection is also fine. 

[ 11%] Creating directories for 'project_libopenssl'
[ 22%] Performing download step (git clone) for 'project_libopenssl'
Cloning into 'project_libopenssl'...

Any inputs?

**Comment by MushMal** [comment]
This is unfortunate but it does takes a while to compile the ssl project. What’s your platform? Could you u restart the build perhaps? After the first time it builds the binary it will then use it with consecutive builds

**Comment by jvasanthan** [comment]
I am running Ubuntu 16.04 (32 bit edition) in VM. I tried to restart the build several times but no help. is there a way I can clone the dependencies, place them under opensource and stop the cmake from downloading them?

**Comment by jvasanthan** [comment]
@MushMal I built it again and running kvsWebRTCClientMaster in Ubuntu and Viewer in Android. The sampleReceiveAudioFrame is not getting called during the webrtc session(Send Audio box is checked in the App). What am I missing?

**Comment by disa6302** [comment]
@jvasanthan , 

Can you send the logs? Are you getting the offer from the viewer?

**Comment by jvasanthan** [comment]
Here is the log

[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5106927/log.txt)

**Comment by disa6302** [comment]
@jvasanthan ,

The `sampleFrameHandler` displays logs only in VERBOSE level. Can you increase log level to see if you see audio frame logs or change log level from `DLOGV` to `DLOGD` [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/15aae699fa0ba3c7f68caff17ee849870f64f87d/samples/Common.c#L590) ?

**Comment by jvasanthan** [comment]
@disa6302 
After enabling DLOGD sampleFrameHandler displays frame size. are these audio frames? see attached log.

[kvsWebrtcClientMaster_Ubuntu_verbose_2.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5117513/kvsWebrtcClientMaster_Ubuntu_verbose_2.txt)

**Comment by disa6302** [comment]
@jvasanthan , 

Yes. Those are the logs. If you would like the frame data to be displayed, you can add it to the log line [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/15aae699fa0ba3c7f68caff17ee849870f64f87d/samples/Common.c#L587)

**Comment by jvasanthan** [comment]
@disa6302 Thank you

**Comment by ronbarrera** [comment]
@jvasanthan I have the same issue with a raspberry pi, where I don't get any audio from android viewer. Where you able to solve this issue?
