### ISSUE TITLE
Connect Amazon echo show

### ISSUE THREAD

**Issue by pai-da-xin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#724]
* How can I connect kvsWebClientMaster to Amazon echo show.Stuck with this question.Even with kvs webrtc test pages.

**Comment by disa6302** [comment]
@pai-da-xin , 

Can you give more clarity around what your set up is like and what your expectations are?

**Comment by pai-da-xin** [comment]
@disa6302 I expect to run kvsWebClientMaster and call my webcam to transmit the real-time audio and video captured to Amazon echo show and display it on its screen.

**Comment by MushMal** [comment]
@pai-da-xin check out https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_AWSAcuitySignalingService_SendAlexaOfferToMaster.html

SendAlexaOfferToMaster API is not part of the embedded SDK interface.

We use this forum to provide support and answer questions for our open source SDKs. If you need architecture guidance for you end application, please consider reaching out to your AWS account team through your AWS account page.

**Comment by pai-da-xin** [comment]
@MushMal If I have an IP camera embedded in this SDK,Using the method, the real-time audio and video captured by the camera can be transmitted to the echo show.Can it be implemented through the Alexa skill kit.

**Comment by pai-da-xin** [comment]
Thank you very much for your reply. I get it.
