### ISSUE TITLE
signalingConnectSync(): operation returned status code: 0x0000000f

### ISSUE THREAD

**Issue by jvasanthan** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#732]
Hi Team, 
I have compiled (default) webrtc sdk in both ubuntu and cross compiled (static link) for my hardware as well.
1. kvsWebrtcClientMaster (Ubuntu) works fine in Ubuntu and I could stream audio and video to Android Viewer (audio back from viewer to Master is still not working). The connection is stable. 
2. Running kvsWebrtcClientMaster(Device) leads  to some issues. The most frequent issue is signalingConnectSync(): operation returned status code: 0x0000000f (see attached signalingConnectSync)
.txt). When I encounter this timeout issue I try to run kvsWebrtcClientMaster parallelly in my ubuntu machine which makes device to establish connection (not sure how though). The audio & video stream runs in android viewer with frame loss and after sometime crashes with Seg fault(see attached Seg_fault.). The above mentioned happens every time & repeatable. 

Any idea to run it stable in the device?

[signalingConnectSync.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5112633/signalingConnectSync.txt)
[seg_fault.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5112634/seg_fault.txt)

**Comment by disa6302** [comment]
@jvasanthan , 

I am not sure what the issue is. Can you run the app with `AWS_LOG_LEVEL=2` to get SDK debug logs? That might give us a clue. Your log level is set to WARN.

**Comment by MushMal** [comment]
I am still unsure what's going on but seems to be two separate issues

* signalingConnectSync.txt indicates that the libWebSockets is simply unable to establish a connection for the RESTful API calls. Perhaps, the device doesn't have internet connectivity? It retries but fails and times out.
* seg_fault.txt - similar story but in this case the connection gets established but somehow, getting ICE config settings keeps retrying and finally succeeds. The master app then exchanges the SDPs but seems that no viable connection gets selected. The end of the log terminates with the crash output but absolutely no stack trace or anything.


Recommendations:

* List any changes you've made to the stock sample application. If any. Any build flags that are different, etc..
* Attempt to compile without async ICE config: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L724 Set this line to FALSE. Some configurations are incapable of creating two parallel contexts.
* Run under the debugger to get the detailed crash dump of debug bits for all of the threads to understand what's crashing.
* Ensure you have good networking (though, this shouldn't cause a crash)

**Comment by fernandoc1** [comment]
Hi @MushMal,
This issue related to libwebsockets not being able to establish a connection for the RESTful API happens to me and I'm sure that it is not a internet connectivity issue. In our camera, there are a lot of internet services running and our clock rely on internet to update. This always happens to me to have to try twice or more, before the Master application is able to receive connections.

I have tried the FALSE flag for asyncIceServerConfig and it didn't help. The same issue:

<pre>
2020-08-24 12:09:17 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000002, Next state: 0x0000000000000040
2020-08-24 12:09:17 ERROR   executeFailedIceAgentState(): IceAgent failed with 0x5a00000d
2020-08-24 12:09:17 DEBUG   stepIceAgentStateMachine(): Ice agent state changed from ICE_AGENT_STATE_CHECK_CONNECTION to ICE_AGENT_STATE_FAILED.
</pre>

**Comment by MushMal** [comment]
@fernandoc1 seems that you are confusing the signaling client connecting with ICE agent state machinery and overall P2P or TURN connection. The snippet of log you've attached has nothing to do with signaling. In this case, your ICE agent fails to connect to the nominated pair which I can't see fro the logs

**Comment by fernandoc1** [comment]
In my post, the first paragraph is not linked to the second.
There are two issues:
 - (First paragraph) Signaling failures
 - (Second paragraph) P2P connections not being established successfully.

**Comment by jvasanthan** [comment]
@MushMal After setting asyncIceServerConfig to FALSE, the signaling client connection looks stable. I still have frame loss issue & crash, will open a new ticket for that.

**Comment by MushMal** [comment]
@jvasanthan those are unrelated issues indeed. Could you please open separate issues to track each one. For the crash, please make sure to include the debug stack dumps for all threads in the process. The easiest is to run your debug compiled application under a debugger and capture the stack.

Could you please go ahead and resolve this issue as addressed?

**Comment by jvasanthan** [comment]
@MushMal sure will do
