### ISSUE TITLE
[QUESTION] createSignalingClientSync failing with status code 0x0000000f

### ISSUE THREAD

**Issue by Morras** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#733]
I am trying to use the the library as a dependency for a RoS package so I can send a video stream from a robot.

When I run my application, createSignalingClientSync fails with status 0x0000000f.
As far as I can see that is a timeout status, and a common problem people have run into here, but without a clear way to fix it.

I have recompiled libwebsockets with debug enabled and you can find the logs from the execution attached below.

I am using an IoT credential provider, but that seems to get the credentials without any problems.

For the **SignalingClientInfo**, I provide the following values:
```
version = 0
clientIdString = robot_6fd21297-5f0d-450b-b616-edbce74cd607  // The uuid is also the thing name
loggingLevel = LOG_LEVEL_DEBUG
```

For the **ChannelInfo", I provide the following values:
```
        channelInfo.pChannelName = "6fd21297-5f0d-450b-b616-edbce74cd607_front";
        channelInfo.pRegion = "eu-west-1";
        channelInfo.version = 1;
        channelInfo.pChannelArn = NULL;
        channelInfo.pControlPlaneUrl = NULL;
        channelInfo.pCertPath = NULL;
        channelInfo.pUserAgentPostfix = NULL;
        channelInfo.pCustomUserAgent = NULL;
        channelInfo.pKmsKeyId = NULL;
        channelInfo.channelType = SIGNALING_CHANNEL_TYPE_SINGLE_MASTER;
        channelInfo.channelRoleType = SIGNALING_CHANNEL_ROLE_TYPE_MASTER;
        channelInfo.reserved = FALSE;
        channelInfo.cachingPeriod = SIGNALING_API_CALL_CACHE_TTL_SENTINEL_VALUE;
        channelInfo.retry = TRUE;
        channelInfo.reconnect = TRUE;
        channelInfo.messageTtl = 0;
        channelInfo.tagCount = 0;
        channelInfo.pTags = NULL;
        channelInfo.cachingPolicy = SIGNALING_API_CALL_CACHE_TYPE_DESCRIBE_GETENDPOINT;
        channelInfo.asyncIceServerConfig = FALSE;
```

The robot is supposed to connect as the master to the channel.

The other issues that have been opened about this seems to have been resolved due to network issues. To eliminate that, I am running my code in a Cloud9 environment in eu-west-1, so there should not be any coorporate firewalls or policies impacting the network.  
The security group of the Cloud9 instance allows all outbound traffic, but only SSH inbound.

I need some help in how to debug this issue and get it resolved.

Best regards

[webrtc output.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5117619/webrtc.output.txt)

**Comment by MushMal** [comment]
You need to ensure you have the appropriate rights:

2020-08-24 11:07:05 DEBUG   lwsHttpCallbackRoutine(): Connected with server response: 403


What happens is that the signaling client state machine executes the RESTful API just fine but it's getting access denied when attempting to connect as master. It then circles back and attempts to fetch the credentials from the specified credential provider, which according to you is the stock IoT credential provider which has credential caching enabled by default so it returns the same credentials (which is the right thing to do) and the cycle repeats.

It then terminates after the timeout is reached.


Regarding the timeout error code. The synchronous API will return a more targeted error code if it determines that continuing to retry is meaningless. In this case, the 403 error might be possible to retry as the credential provider might refresh the credentials and get connected successfully.

**Comment by Morras** [comment]
Thank you MushMal. 
I had a typo in the channel name in my IAM Role.
I had looked at CloudTrail but Kinesis does publish there it seems.
I can now establish connection to the channel. Thank you.
