### ISSUE TITLE
[QUESTION] How to Use in MacOS Swift Project

### ISSUE THREAD

**Issue by kyledecot** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#734]
What is the recommended way of using this in a MacOS/Swift based application? Are there any examples that can be used as a reference?

**Comment by MushMal** [comment]
Unfortunately, we don't have a sample based on MacOS Swift currently. There is an iOS SDK which is based on Google's implementation of WebRTC and KVS Signaling which is in Swift you might find useful: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios

**Comment by disa6302** [comment]
Closing this since the question is answered. Feel free to reach out if you have any questions!
