### ISSUE TITLE
[BUG] Static build issue

### ISSUE THREAD

**Issue by disa6302** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#736]
**Describe the bug**
While static building the webrtc sdk, at times, the kvsCommonLws gets linked before pic which causes issues like #727 and #636. An active PR was #666 was closed since the changes failed on Mac. The goal of this ticket is to fix the issue across all platforms.

**SDK version number**
1.3.0

**Expected behavior**
Static build should pass

**Comment by ycyang1229** [comment]
NO, I closed it since it has been there about one month. I am glad to see this obvious bug will be corrected.

**Comment by MushMal** [comment]
@ycyang1229 thanks for your contribution. Indeed, this is an issue with the static build that some of the customers are using and some might hit it. The last that was known about this is that it fails to compile on various platforms. I would love to get this resolved ASAP in a portable manner without having custom scripts to address the extensions (pardon my ignorance and knowledge of the issue itself).
