### ISSUE TITLE
[BUG?] REMB for multiple video tracks handling

### ISSUE THREAD

**Issue by zhuker** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#741]
according to REMB spec 
> This feedback message is used to notify a sender of multiple media streams over the same RTP session of the *total* estimated available bit rate on the path to the receiving side of this RTP session.

meaning a single bitrate value is sent for multiple tracks, while we are handling it as if bandwidth hint is per track see `Rtcp.c:199`

**Comment by zhuker** [comment]
@Sean-Der what you say?

**Comment by MushMal** [comment]
Perhaps we should add some handling for this case. Most scenarios are video only so it would be OK. In cases where we have audio and video, the data is a little skewed in this case. True, the audio density is multiple times smaller than video but perhas we should handle it. I am not yet sure how to properly handle this and what the net result should be from the applications perspective.

The SDK currently just passes the information along to the customers application but it can't control the actual ABR or frame thinning.

**Comment by zhuker** [comment]
if you get a REMB like `[2mbps, audio_ssrc, video_ssrc]`
both audio and video track will receive 2mbps bandwidth hint separately so user app will decide that both audio AND video can be encoded at 2mbps for a total of 4mbps which is not what REMB intended to say

**Comment by MushMal** [comment]
Indeed, however, in practice I have not seen any ABR that can apply neatly to audio. So, likely, the applications will simply ignore it for audio.

This said, I would like to tease apart what would be needed to handle this from the SDK perspective. Perhaps, the applications should have the understanding that the reported bandwidth is for all the tracks summarily as the SDK can't subdivide the bandwidth proportionally

**Comment by zhuker** [comment]
i also found a bug in remb handling https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/743

**Comment by MushMal** [comment]
NIIIIIICE! Commented on it.
