### ISSUE TITLE
compile this SDK

### ISSUE THREAD

**Issue by pai-da-xin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#748]
Hi,Sir,
* How can I compile this SDK to conform to mips-linux-gnu-gcc of MIPs platform.Do I need to use cross compilation? What parameters do I need to use when compiling.I need to modify it CMakeLists.txt?

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#cross-compilation

You can also search existing issues - there are some questions that had been asked and answered prior.

**Comment by pai-da-xin** [comment]
@MushMal 
* Thank you for your reply.
* But now I have another problem.After executing cmak, I encountered the following problems when executing make:

> libkvsWebrtcSignalingClient.so：对‘EMA_ACCUMULATOR_GET_NEXT’未定义的引用
libkvsWebrtcClient.so：对‘strnstr’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [kvsWebrtcClientMaster] 错误 1
make[1]: *** [CMakeFiles/kvsWebrtcClientMaster.dir/all] 错误 2
make: *** [all] 错误 2

I didn't change anything. I just ran cmake and make.

**Comment by MushMal** [comment]
Not sure what the text says. Does it complain that it can't find strnstr? This API is ifdef-ed in PIC. If your toolchain provides the implementation we use it and if not, we use the implementation in utils

https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h#L806-L810

util implementation is in https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/String.c#L459

Can you make sure that you are linking PIC util properly?

**Comment by pai-da-xin** [comment]
@MushMal Even if I don't use cross compilation, just normal compilation, it will have this problem.Maybe that's not the reason.

**Comment by pai-da-xin** [comment]
@MushMal Now I execute the command to cross compile, but it has the following problems.

> Linking C shared library libkvsWebrtcClient.so
/usr/local/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: skipping incompatible /home/hyg/work/webrtc_aws/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libkvspicUtils.a when searching for -lkvspicUtils
/usr/local/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lkvspicUtils
/usr/local/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: skipping incompatible /home/hyg/work/webrtc_aws/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libkvspicState.a when searching for -lkvspicState
/usr/local/mips-gcc472-glibc216-32bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/ld: cannot find -lkvspicState
../open-source/lib/libssl.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [libkvsWebrtcClient.so] 错误 1
make[1]: *** [CMakeFiles/kvsWebrtcClient.dir/all] 错误 2
make: *** [all] 错误 2

This is my command to cross compile:
> cmake .. -DCMAKE_C_COMPILER=mips-linux-gnu-gcc -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=mips-linux -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=mips-linux

* What's more, I have the same problem when I execute this command and execute the cmake .. -DCMAKE_C_COMPILER=mips-linux-gnu-gcc command,Whether or not parameters  DBUILD_OPENSSL and DBUILD_OPENSSL_PLATFORM and DBUILD_LIBSRTP_HOST_PLATFORM and DBUILD_LIBSRTP_DESTINATION_PLATFORM are used, There will be no other changes.
Do I need to modify the CmakeList.txt?

**Comment by pai-da-xin** [comment]
* Oh,Nice, it's solved.
