### ISSUE TITLE
Implement createDataChannel (currently we only support accepting incoming)

### ISSUE THREAD

**Issue by enobufs** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#75]
Could you please tell me if you have a plan to support partial reliability options for data channels in the near future?

**Comment by enobufs** [comment]
I just realized that the SDK does not have a method to create a data channel. Would that become available any time soon?

**Comment by Sean-Der** [comment]
Hi @enobufs I am not sure, we are still evaluating the tradeoffs.

For now users are creating DataChannels in Android/iOS/JS, and no users have expressed desire to do `Embedded` <-> `Embedded` solutions. The upside of not supporting it is reduces a lot of code paths/possible error cases on our side. We have to implement code for the creation, and we have to provide callbacks/handle all the states of `Creating -> Opened -> Closed` etc...

I am not against it though! It just hasn't blocked anyone from building things yet.

**Comment by enobufs** [comment]
I see.  It's rather surprising that embedded devices are not on priority...
Thanks for your info @Sean-Der

**Comment by Sean-Der** [comment]
Thanks for making the issue! `Embedded` <-> `iOS/Android/Web` is a priority though.

Things can always change when people find new things they want to build, so totally happy to change direction if this is blocking.

**Comment by enobufs** [comment]
Hmm... "Embedded <-> iOS/Android/Web is a priority”, BUT, "Embedded" still can not create a Data Channel stream. (How do we ensure that one of the endpoints is always a iOS/Android/Web?) Wouldn't it just be a missing feature (in C SDK) rather than the priority issue then? (I am working on a game console app.)

**Comment by MushMal** [comment]
@enobufs could you please provide a little more detail on your application? Is your application embedded <=> embedded? Do you need to create a single channel? As @Sean-Der mentioned, we are in a process of evaluating these and going over feature by feature.

**Comment by enobufs** [comment]
It's a real-time app, which essentially has three types of nodes:

* Producer (generates raw data, a console/embedded device and/or a browser)
* Processor (processes the raw data, spits out a result for Consumer. a distributed service node)
* Consumer (consumes the result, a console/embedded device and/or a browser)

> A node could be a Producer and a Consumer at the same time.

Each node could be located anywhere. The app uses two data channels, a control (reliable) channel, and an (unreliable) data channel where the data tolerates some level of loss and latency-critical - up to 1000 msec).

I am currently using Pion (thanks to Sean). Then I was excited to see this SDK as an open-source particularly because it offers a very small memory footprint - great for resource-constraint devices. But I am aware this is an SDK for Kenisis, and my use case may not align with your goal with this SDK in the first place. Please let me know what you think. Thank you.
