### ISSUE TITLE
kvsWebrtcClientMaster not working on Windows

### ISSUE THREAD

**Issue by Ben8823** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#756]
I'm trying to get the kvsWebrtcClientMaster program to run under windows. It compiles fine, if i run it it creates the signaling channels and prints out the following.
```
[KVS Master] Signaling client connection to socket established
[KVS Master] Channel test set up done
```
Unfortunately no video is showing up on the KVS WebRTC Test Page. If I try the same from ubuntu I can watch the video.
Did anyone get it to run under windows? If yes are there any changes requried?

**Comment by MushMal** [comment]
No changes should be required. Could you provide full debug logs for both the master and the viewer. Include detailed information about the network topology, your application, scenario, etc

**Comment by Ben8823** [comment]
Ok that's strange. I noticed that in the handleOffer function in Common.c the call to setLocalDescription fails.
The callstack looks like this:
```
iceAgenstStartGathering->iceAgentInitRelayCandidates->iceAgentInitRelayCandidate->createSocketConnection->socketConnect
```
the connect in socketConnect returns -1 and only errno is checked which is not set on windows. on windows WSAGetLastError has to be called.
but this would mean that the socket codebase is not ready for windows yet?

I'm testing it on LAN behind NAT, both on the same machine.
Attached you can find the log of master and viewer.

[viewer.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5137742/viewer.log)
[master.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5137743/master.log)

**Comment by disa6302** [comment]
@Ben8823 , 

It does look like we do not support `WSAGetLastError` in our stack. We will look into it. Meanwhile, can you use WSAGetLastError and FormatMessage in [createSocket()](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/a7da1e06166ca2931c626b11e24f4bb2c05d4a0f/src/source/Ice/Network.c#L146) to get the error string so that we can understand what the error is?

**Comment by Ben8823** [comment]
@disa6302 

ok but as far as i know there is not really an alternative to `WSAGetLastError()` if compiling on windows. 
It's not `createSocket()` but the [socketConnect()](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/a7da1e06166ca2931c626b11e24f4bb2c05d4a0f/src/source/Ice/Network.c#L266) that fails.

That's the error i get. It's basically the same as the `EINPROGRESS` which is already handled.
```
A non-blocking socket operation could not be completed immediately.
```
Probably everywhere where `errno` is used `WSAGetLastError()` has to be handled on windows.

**Comment by disa6302** [comment]
@Ben8823 , 

Sorry for the late response. From the logs, I see TURN is being used and no candidate pair is being chosen. Can you disable TURN to see how it works? 

You need to replace [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/9da07ef74f1e0f8a12ed5aa61ebab11dd88cca55/samples/kvsWebRTCClientMaster.c#L22) line with this:

`createSampleConfiguration(argc > 1 ? argv[1] : SAMPLE_CHANNEL_NAME, SIGNALING_CHANNEL_ROLE_TYPE_MASTER, TRUE, FALSE, &pSampleConfiguration);`

Also, we welcome contributions! Would you like to open a PR with the `WSAGetLastError()` in our stack?

**Comment by Ben8823** [comment]
@disa6302 
I've tried it with TURN disabled and using `WSAGetLastError()` in `socketConnect()`.  Unfortunately I'm still not getting video in the browser.
Attached you can find the viewer and master logs.

I think a PR makes no sense at this stage as i only added handling of `WSAGetLastError()` at one place but `errno` is used at a lot of places in the code (Network.c, SocketConnection.c, ConnectionListener.c).
[master.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5224247/master.log)
[viewer.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5224248/viewer.log)

**Comment by MushMal** [comment]
Curious, if there is anything special on your platform that for some reasons fails the socket operations with errno - no error? We had added Windows support not so long ago but have Windows runs in Travis CI and they are working OK. I don't have a stock windows machine handy to give it a try but perhaps someone could verify that Windows build works OK?

**Comment by Ben8823** [comment]
Sure it compiles fine on windows.
The problem is that `errno` never gets set if you call a winapi method like [sendto]( https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-sendto) or [connect](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-connect).
Instead of reading `errno` the `WSAGetLastError()` function has to be called on windows.

**Comment by MushMal** [comment]
I understand. This requires some re-plumbing for these APIs. Is this the entire list BTW?

Ideally, we implement the errno code as an internal API in Network.c which then can be compile-time defined into platform specific error code retrieval and mapping API. 

No ETA for this work for now

**Comment by MushMal** [comment]
P.S. We love if people could contribute to the codebase. Please let us know if you would like to work on it. We have a number of community members contributing by submitting their PRs
