### ISSUE TITLE
kvsWebrtcClientMaster frame loss

### ISSUE THREAD

**Issue by jvasanthan** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#757]
Hi Team, 
Setup:
Running Mater in Device, viewer in Android. Using stock kvsWebrtcClientMaster (kvsWebrtcClientMaster is set to False) and stock viewer in android app. 
Issue:
Frame loss while streaming h264 & opus frames in android viewer. See attached log

[frame_loss.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5136898/frame_loss.txt)

**Comment by MushMal** [comment]
It’s hard to tell what exactly is going on with your network. Have you seen any output from the viewer device? Could you run some experiments like pairing cia forced turn, running master from a browser, etc... this might help you debug your network

**Comment by disa6302** [comment]
@jvasanthan , 

Can you check for any firewall or check if you are running on VPN?

**Comment by jvasanthan** [comment]
@disa6302 
No. Firewall is disabled & there is no VPN. 

The following scenario works well.
Device as Master - js as Viewer
Android as Master - js as Viewer
js as Mater - Android as Viewer
Android as Master - Android as Viewer

The only issue is with Device as Master - Android as Viewer. I added webrtc sdk into my project and feeding live video from camera. The Android Viewer is laggy/frame loss for 2-3 mins and then it plays in realtime (its repeatable) and there is no issue in js viewer. I am attaching the modifications done in the sendVideoPackets function, is there any issue in handling sleep?. 
If I enable THREAD_SLEEP(SAMPLE_VIDEO_FRAME_DURATION); video plays with more than 30 seconds delay and laggy in js viewer as well. 

[modified_sendVideoPackets.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5172700/modified_sendVideoPackets.txt)

**Comment by disa6302** [comment]
@jvasanthan , 

We modified the THREAD_SLEEP logic in the master sample recently. Do you mind pulling the latest and see if it works?

**Comment by jvasanthan** [comment]
@disa6302 I pulled the latest version. No change in behavior. is there any more information I can provide to debug the issue?

**Comment by disa6302** [comment]
@jvasanthan , 

I do not think there is any other information. From the logs, I can see that TURN is being used and that the select() call is timing out. Can you check if the master and viewer are in the same network and if not, try that to see if you do not see frame losses? 
The sample itself is fine.

**Comment by jvasanthan** [comment]
@disa6302 both master and viewer are always in same network. I am attaching android debug logs, EglRenderer: srRemoteViewDuration: 4011 ms. Frames received: is 0 or 1 initially and after sometime it comes back to 25-30 fps. is it because of TURN? can I rule out encoder issue?  
[android_viewer.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5208725/android_viewer.txt)

**Comment by jvasanthan** [comment]
@disa6302 The issue is with only video. Audio is streaming fine

**Comment by disa6302** [comment]
Can you try without TURN enabled? 

Since you are using the sample as it is, the only thing I can think about is network right now, considering the other combinations work.

**Comment by jvasanthan** [comment]
@disa6302 tried without TURN. No change.

**Comment by MushMal** [comment]
I am also drawing a blank here. Recommend trying different network configuration to narrow down the potential bandwidth issue. The main issue is that we are not exposed to the actual Androids webrtc implementation and there really isn't much we can recommend in terms of debugging it.

**Comment by jvasanthan** [comment]
closing the issue for now. I didn't see frame loss in a different network.
