### ISSUE TITLE
[QUESTION] do we have consent freshness checks implemented?

### ISSUE THREAD

**Issue by zhuker** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#759]
as described here https://tools.ietf.org/html/rfc7675

**Comment by zhuker** [comment]
it looks like `currentRoundTripTime` is updated only once 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/7a020880321e76548271ea1c20de093c09833a6c/src/source/Ice/IceAgent.h#L121
am i missing something?
@disa6302

**Comment by disa6302** [comment]
@zhuker , 

Consent freshness checks are not implemented. 

About currentRoundTripTime, I should probably be updating it every time I receive a binding response. Let me get back to you on that.

**Comment by disa6302** [comment]
@zhuker , 

I will work on a fix for `currentRoundTripTime` soon. Sorry its taken this long. Will update this ticket once I add in the fix.

**Comment by disa6302** [comment]
Tracking this in #813
