### ISSUE TITLE
[BUG]Kinesis is failing to send all IP candidates

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#762]
I have done a test with the camera in a network with IPv6/IPv4 and my computer in another network with IPv6/IPv4. Both networks are stable and working all the time.
In my test, I have refreshed the browser viewer multiple times. Sometimes, the received message, doesn't came with all IP possibilities. I think that this might be a bug.
Here is the video of my test: [Kinesis failure test](https://www.youtube.com/watch?v=S3JuJmI1kFo). Note that at the console log, there are sometimes that the IPv6 candidate is not listed and it is when the streaming fails.

I have also attached a log of the terminal output from Kinesis master client:
[kinesis_failure_2020-08-28.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5143991/kinesis_failure_2020-08-28.log)

If you want to check, here is my viewer code: [viewer](https://gist.github.com/fernandoc1/ba3a3d393556a5e00265fc6ecda40eb8)

I think that kinesis should always send all candidates to the viewer.

**Comment by MushMal** [comment]
IPv6 should not be listed for TURN. Our TURN is IPv4 only. Please re-open or cut a new one if you need further assistance
