### ISSUE TITLE
[QUESTION] Session keeps occupied after connection build up fail

### ISSUE THREAD

**Issue by jonescx** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#767]
With the attached log line 8699
<2020-09-01 15:43:43>
....
[ 771][D]doMasterMessageReceived(): Creating new streaming session for peer c8c9ea60987e4eb3a48897f29114d7e8

A new session created and it failed to build up a connection, but it keeps the session count as 1 as following pattern.
[ 771][W]webrtc_master: heartbeat. state:[9], **sesssions:[1]**

Also, please note the onConnectionStateChange log is modified from "New connection state" to "New **Peer** connection state"
[0901_log_server4.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5161792/0901_log_server4.txt)

**SDK version number**
SDK version tag v1.3.0 with the extra logs output. check the patch files for detail.
[0902_extra_log_patch.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5161813/0902_extra_log_patch.txt)

**To Reproduce**
It not easy to reproduce.

**Comment by jonescx** [comment]
@MushMal Could you show me where is the decrement of the peer connection for the 15 seconds in the source code? We want to add some output around there. Thanks.

**Comment by MushMal** [comment]
Not entirely sure I understood the question. Here is the callback that gets set in the samples: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L32

This is where the callback gets called from: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/PeerConnection.c#L268

This, in turn gets called from the ICE connection manager and from the DTLS.

**Comment by MushMal** [comment]
ICE Agent can detect the disconnect here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgentStateMachine.c#L601

The timeout is configured as 15 seconds

**Comment by MushMal** [comment]
BTW. I am going to remove the BUG tag and mark it as answered.

**Comment by jonescx** [comment]
@MushMal No problem. We will collect more data to see if we can reproduce it.

**Comment by disa6302** [comment]
@jonescx , 

Closing based on comment. Feel free to reach out if you have any questions.
