### ISSUE TITLE
[QUESTION]How to use alternative TURN servers in Kinesis?

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#769]
I'm trying to build a solution where my customers can have their own TURN servers. It is a requirement that their video stream do not go to foreign servers. So I will rely on Kinesis signaling and send the streaming to their TURN servers.
I have tried to manually add the TURN server ([Common.c](https://gist.github.com/fernandoc1/364291f7335c83ac5a5d2b807ac3059e#file-common-c-L293)) but it is always sending me 54.190.53.169 TURN server.
Is there any way to disable Amazon TURN servers?

**Comment by MushMal** [comment]
Conceptually, the signaling DAG (object graph) is separate from the WebRTC DAG (rooted with PeerConnection object). You could supply your own TURN info (URI + credentials) to the PeerConnection. This is exactly what the sample application does - it fetches the list of TURN server infos from the signaling and passes it to the PeerConnection object. You could replace those by your own TURN servers, provided they act the same way as the KVS TURN

**Comment by fernandoc1** [comment]
Hi @MushMal, thanks for your attention.
I would like to know if [COTURN](https://github.com/coturn/coturn) is compatible with KVS TURN. Is there any recomendations?

**Comment by MushMal** [comment]
Unfortunately, we can't provide this type of info as we simply don't have the information. It would depend not only to the version of the software in question and the internal spec adherence (which sometimes is a little lose) but also to the network topology, etc..

**Comment by lherman-cs** [comment]
@fernandoc1 as the original question has been answered, I'll mark this issue as resolved. Please feel free to reopen it for further assistance.
