### ISSUE TITLE
[FEATURE] Update the code documentation 

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#771]
I would like to ask for the Kinesis staff update the code documentation that is available at:
[awslabs.github.io](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-c/)
It would be nice if there were call graphs, like this one:
![image](https://user-images.githubusercontent.com/249402/92143887-47bf3700-edec-11ea-90e9-e61b11c6bd48.png)
I'm contributing the doxygen I create for this, if you are interested:
[kinesis_doxygen.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5170065/kinesis_doxygen.txt)

I also would like to ask to update this part of the documentation [use-pre-generated-certificates](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#use-pre-generated-certificates) because it is no longer representing the current state of the code.

**Comment by disa6302** [comment]
@fernandoc1 , 


Thank you for this! 

Our doxygen usually gets updated with every merge commit. Will spend some time to see if any formatting is incorrect in the public header file `Include.h` and also add other public header files to the doc. 

About  [use-pre-generated-certificates](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#use-pre-generated-certificates), will look into it. Thanks!

**Comment by fernandoc1** [comment]
Hi @disa6302 
I would like you to give special attention to documentation around PRtcPeerConnection, because it is initialized as PKvsPeerConnection. I had to expend sometime until I figured it out that is a "kind of Inheritance". It is not explicit in the code.

**Comment by disa6302** [comment]
@fernandoc1 , 

I am not sure I understand. `PKvsPeerConnection` is an internal structure which has `PRtcPeerConnection` as a member. What is available to use publicly is `PRtcPeerConnection`. What kind of documentation are you looking for around that?

**Comment by fernandoc1** [comment]
Because it looks like the PKvsPeerConnection is responsible to create the most important part of the P2P connection and its structure is hidden. By looking at the code, it is not easy to figure out that PRtcPeerConnection is related to PKvsPeerConnection and thus, not being able to quickly understand how the peer connection is actually established.
To be more clear, I have found a commit that just do almost what I'm dreaming for: [Manual signaling](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/8a79ff0760cac72d0d3bed020bbf4edc427e5f35/samples/kvsWebRTCClientMaster.c).
I want to understand exactly how the P2P connection is done within Kinesis, with detailed steps, without the need to rely on Amazon signaling channel.
When we look at the code, RtcPeerConnection is just a "UINT32 version" and there is no reference/clue about how this structure work within the code. So if PRtcPeerConnection structure documentation is improved, understanding the P2P connection part would become more clear.

**Comment by disa6302** [comment]
@fernandoc1 , 

We will add more documentation around how P2P connection works within the SDK. I will add it as an action item to the documentation ticket.

About Manual signaling, it is a good feature to have to test out signaling separately. We will get back on this shortly.

**Comment by disa6302** [comment]
@fernandoc1 , 

The initial documentation issues have been resolved: The doxygen now has call graphs and the documentation for pre-gen certificate int he README.md is fixed. I am going to go ahead and close the issue. 

Feel free to reach out with any questions in the future. Thanks!
