### ISSUE TITLE
[QUESTION] receiveLwsMessageWrapper(): operation returned status code: 0x0000000f

### ISSUE THREAD

**Issue by jonescx** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#778]
@MushMal 
In the line attached log, at line 1016 there is a status code 0x0000000f for something timeout. 
We want to know what functions we can add instrumentation to collect more information to know where the error code comes from. Thank you.

BTW, I found our application stop at closing video at line 851. In normal case, it should go through like from line 311 to 326.
It may be related between the application stuck and the sdk thread timeout.

[receiveLwsMessageWrapper_0x0000000f.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5192949/receiveLwsMessageWrapper_0x0000000f.txt)

**Comment by MushMal** [comment]
It's still not immediately clear as what's going on.

Could you please add some instrumentation to 

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/LwsApiCalls.c#L1432
and 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/LwsApiCalls.c#L1453

Add in a form of 

retStatus = CVAR_WAIT(..);
if (STATUS_FAILED(retStatus)) { DLOGE("Instrumented printout from cvar wait send 0x%08x", retStatus);}
CHK_STATUS(retStatus);

Make sure to output something different for the second occurence.

**Comment by MushMal** [comment]
Any updates on this issue after you've implemented the error callback handler?

**Comment by jonescx** [comment]
@MushMal We patched the openssl library by another way to solve the wait too long issue. It seems hard to reproduce the timeout issue.

**Comment by MushMal** [comment]
These are hard to repro issues indeed. Please run multiple scenarios to ensure you the suggested steps are reducing the connect time by reducing ice agent time. Please resolve this issue once verified

**Comment by disa6302** [comment]
@jonescx , 

Closing this because there isnt any activity on this. Feel free to reach out if you have any more questions.
