### ISSUE TITLE
[QUESTION] Streaming request timed out - answer took to long to send in master

### ISSUE THREAD

**Issue by jonescx** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#780]
@MushMal 
An attempt to stream timed out because the camera took too long to respond with an answer.

These times are in the attached uart logs:
16:28:23.645 - offer received by camera
Camera logs show that the offer was received at 16:28:23 (echoshow195)

Bumps the current session count to 2
16:28:30 - answer was sent, but it was too late
16:28:39 - freeing streaming session with peer id: echoshow195

Session count back to 1
16:28:30 - first log of “writeFrame A”

As of 16:54 it’s still writing frames. There are no clients streaming.

Felix from AWS suggested to only the turn servers that end in TCP. It should help shorten the time to respond with the answer when the client does not support trickle ICE (alexa does not support trickle ice).

In this case, where can we put instrumentation to measure the spending time from receive offer until answering SDP?
Thanks.

[master_answer_sdp_slow.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5193406/master_answer_sdp_slow.txt)

**Comment by modescode** [comment]
tagging @chehefen

**Comment by disa6302** [comment]
@jonescx, 

We do display the time taken to send answer after receiving offer here: 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/9da07ef74f1e0f8a12ed5aa61ebab11dd88cca55/samples/Common.c#L151

Somehow, the log gets cut at "handleOffer(): time taken to sen" in the file you attached.

**Comment by MushMal** [comment]
@jonescx Here is the latest thinking on this..

In your scenario, you are using the NON Trickle ICE due to Alexa. Alexa has a 6 second timeout overall. KVS master sample when receiving an offer needs to kick off ICE agent to collect ALL of the ICE candidates in order to furnish the answer. The main issue is that in non-trickle ICE mode, the ICE agent has to wait for all of them to resolve - either with success or a timeout.

The suggestion is to try to filter out the network interfaces that inherently are not used. For example, if you have virtual loops or a LAN then those can be filtered out. 

@chehefen could you provide a little more info on how to apply the filter and point to a sample/test code?

**Comment by disa6302** [comment]
@jonescx , 

You can refer to this to add network interface filtering: 
[this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/790#issuecomment-692258493) and [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/790#issuecomment-692263868)  and see if it helps.

**Comment by jonescx** [comment]
@disa6302 Thanks. We will check them out.

**Comment by chehefen** [comment]
@jonescx you have at least three network interfaces on your camera:
09-08 16:28:29.620: iceAgentLogNewCandidate(): New local ice candidate discovered. Id: QCkpK0VLK. Ip: 2601:0540:c601:2f50:8fb7:aa44:4d62:00d9:43947. Type: host. Protocol: UDP.
09-08 16:28:29.621: iceAgentLogNewCandidate(): New local ice candidate discovered. Id: W+oiVdGmZ. Ip: 2601:0540:c601:2f50:0000:0000:0000:13b2:40313. Type: host. Protocol: UDP.
09-08 16:28:29.621: iceAgentLogNewCandidate(): New local ice candidate discovered. Id: w1Uf6s61k. Ip: 192.168.1.47:34062. Type: host. Protocol: UDP.

and sdk only found one srflx candidate:
New local ice candidate discovered. Id: f0kfnAORc. Ip: 71.61.16.77:48815. Type: srflx. Protocol: UDP.

likely the sdk is stuck on trying to get the STUN ip for the other two network interfaces. You can use the interface filter that Divya suggested to only use interfaces that works.

**Comment by jonescx** [comment]
@chehefen We will add the network filtering function in our application. Thanks.

**Comment by disa6302** [comment]
@jonescx , 

Closing this. Feel free to open a new issue if network filtering does not solve the issue you are facing.
