### ISSUE TITLE
[QUESTION] signalingConnectSync(): operation returned status code: 0x0000000f

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#781]
A one liner description about the use case and what you are trying to achieve
Sometimes signalingConnectSync fail with timeout
** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 

SDK commit:
a7da1e06166ca2931c626b11e24f4bb2c05d4a0f

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

log:
2020-09-09 10:57:12 WARN    lwsHttpCallbackRoutine(): Client connection failed. Connection error string: closed before established
![image](https://user-images.githubusercontent.com/58592084/92591409-6764cc80-f2d0-11ea-8c6b-0c160612290c.png)

[signalingConnectSync_code_0x0f_.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5194688/signalingConnectSync_code_0x0f_.txt)

**Comment by lherman-cs** [comment]
@chehefen any idea?

**Comment by MushMal** [comment]
The log seems to be OK - it simply drops the connection and times out. You can debug by checking:

* The device has proper network - this is the most likely case as it seems to be an intermittent issue.
* Ensure your credentials have proper access rights
* Ensure your device can handle parallel contexts. Simply set the following to false: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L620

**Comment by MushMal** [comment]
Resolving as it seems to be related to network
