### ISSUE TITLE
[Questions] lwsIotCallbackRoutine(): Client connection failed. Connection error string: lws_ssl_client_connect1 failed

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#789]
Hi experts,

The sample application quit unexpectedly on some devices, with this log
`lwsIotCallbackRoutine(): Client connection failed. Connection error string: lws_ssl_client_connect1 failed`
This seems related to iot credential provider, could someone give some insight on how the credential provide works and why the application quit?

Thank you!

**Comment by MushMal** [comment]
@staowyze the IoT credential provider is one of the types of credential providers. It's defined in the C Producer codebase in Common library.

The idea is to supply a callback that will be called by (in this case) the signaling client whenever it needs the credentials. The IoT credential provider has a caching logic so it won't issue the actual call if the credentials are still valid for a certain period of time calculated based on min durations.

In this case, if the IoT credential provider fails to make the call, the error gets bubbled up to the client (signaling client in this case) which then returns an error to the caller - assuming this is the path of direct API calls like create or connect. If this error happens in a background (refreshing ICE server config or when it attempts to reconnect on disconnect) then the error gets bubbled up via the error callback function.

Now, the question is why the actual call is failing. There is nothing to work on this as I don't see any debug logs from debug LWS. Suggest debugging your connection on a debug built libWebSockets. (more info on how to build the debug lws can be found by searching the issues).

Removing bug label and setting assumed answered question.


Please resolve if you don't have further questions./

**Comment by staowyze** [comment]
thanks for the concrete answer! I tagged bug by accident, and then didn't find a way to remove the bug tag, sorry.

**Comment by MushMal** [comment]
No worries. I am going to resolve this issue. Please feel free to cut a new one or reopen this if you need further assistance with IoT credential provider
