### ISSUE TITLE
[QUESTION] Cost Optimization, Feasibility of Packing multiple Candidates in One message

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#790]
We are doing some signaling cost optimizations.
Just wondering if it is technically possible to pack multiple candidates into one JSON message?

**Comment by suggestedfixes** [comment]
https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-websocket-apis5.html
From this, seems like we just have to delimit the message payload, and make sure there is an upperbound of 10k characters.

**Comment by MushMal** [comment]
Yes, the limit is 10K for the message. This should cover most of the cases, unless your device has numerous interfaces. This is not a soft-limit as of now. Please provide a little more information about your scenario if this really is an issue on a prod device.

**Comment by suggestedfixes** [comment]
The issue is mostly related to cost, currently the price is $2.25/million messages. Currently, it takes around 20-40 messages to establish a connection. However, if we can pack multiple candidates into one message, so it might only take about 4-10 messages to per connection. This is about 5-10 times of saving on signaling messages.

**Comment by MushMal** [comment]
In your real-world prod devices you shouldn't end up with that many messages as you should filter out all of the non-needed interfaces. You could then indeed tight-pack the remainder. Try using non-trickle ICE mode. This will increase the latency though

**Comment by suggestedfixes** [comment]
So you would suggest whitelisting only gateways and for example eth0 if device is on a LAN. Would this be configurable on the SDK level or this is more of a system level configuration, or both?

**Comment by disa6302** [comment]
@suggestedfixes , 

You can set your callback to whitelist interfaces [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/17fa3a7234944ee7d5d9ee8124ecfbc510ce0f98/samples/Common.c#L260):

**Comment by MushMal** [comment]
@suggestedfixes Yes, this would really be needed on a proper prod devices. @disa6302 do we have an example of actually using the filter that can help?

**Comment by disa6302** [comment]
@MushMal , 

I do not think so. But, this is a simple example of the callback: 

```
BOOL WhiteListInterface(UINT64 customData, PCHAR interface) {
    BOOL whiteList = TRUE;
     if(STRNCMP(interface, "eth0", ARRAY_SIZE("eth0") != 0) {
         whiteList = FALSE;
     }
     return whiteList;
}
```

This will lead to collecting all details related to `eth0` such as address, family and port.

**Comment by suggestedfixes** [comment]
Thanks! I will try it out!

**Comment by MushMal** [comment]
@disa6302 thanks for adding this info. We really need to add some samples utilizing it. I am also wondering how Windows will work with this filter.

@suggestedfixes could you please resolve this issue as we are going off of the main topic

**Comment by disa6302** [comment]
[Windows](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/17fa3a7234944ee7d5d9ee8124ecfbc510ce0f98/src/source/Ice/Network.c#L28) is taken care of as well.

**Comment by suggestedfixes** [comment]
@MushMal How difficult would it for us to customize packing multiple candidates? And would you recommend the packing approach?

**Comment by MushMal** [comment]
It's not really super hard but you are talking about a hybrid kind of mode between trickle and non-trickle. You could control the device side as you have the SDK but you won't control the other side if based on non-embedded SDK.

**Comment by suggestedfixes** [comment]
The other side is based on aws's javascript Signaling Client library, which is a wrapper around websockets

**Comment by MushMal** [comment]
I see. Yeah, I guess you could pack those too. You really need to modify the SDK code in both of those cases. Try to eliminate the non-used interfaces by filtering first. Then, try to see if you can simply do non-trickle ICE and if that works then you don't need to do anything. If not, you will have to write some heuristics logic in both clients to do packing based on the size vs time heuristics. Not sure how much help we can be in that case

**Comment by suggestedfixes** [comment]
Thanks! We can experiment with interface and ip white listing and resort to packing as a last resort.
