### ISSUE TITLE
[QUESTION] Session keeps streaming from master but there is no client viewing

### ISSUE THREAD

**Issue by jonescx** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#794]
Here are some logs from the file "2020-09-11 08-48-41 FT230X Basic UART #2.log"

`09-11 08:44:59.208: [ 947][W]webrtc_master: heartbeat. state:[9], sessions:[0]`
no viewer session 

`09-11 08:45:01.806: [ 947][D]lwsWssCallbackRoutine(): Client receive`
got viewer offer

`09-11 08:45:02.211: [ 947][D]doMasterMessageReceived(): Creating new streaming session for peer [echoshow353]
`
create session for echoshow353

`09-11 08:46:24.593: [ 947][W]webrtc_master: heartbeat. state:[9], sessions:[1]`
one session for echo show streaming

`09-11 08:59:16.876: [9237][D]freeSampleStreamingSession(): Freeing streaming session with peer id: 9ee73dfad1db4a4fbdf11b7368bc4cdc`
However, customer says there is no viewer after this point
Then the "writeFrame V" or "writeFrame A" keep outputing, until the system reboot

`09-11 11:31:42.664: U-Boot 2013.01 (Aug 10 2016 - 15:01:21)`
system reboot (log_server3.log line 16160)

Here are the descriptions from customer.
-- many retries have failed

- 09-11 08:59:16.876: [9237][D]freeSampleStreamingSession(): Freeing streaming session with peer id: 9ee73dfad1db4a4fbdf11b7368bc4cdc
 
- after this, the session count is at 2 even though no clients are streaming. Also, the camera logs show that frames continue to send for hours.

- Dropping signalling message from peer [0e403a4115bc4958bb3ffc936248361e] since maximum simultaneous streaming session of [2] is reached
 
- 09-11 08:59:40.741: [9237][W]doMasterMessageReceived(): Dropping signalling message from peerdoMasterMessdoMasterMessageR[9237][D]doMaste[9237][D]lwsWssCallbackRoutine(): Client is writmasterMessageRecmasterMessageReceived:---:54ms
 
- 09-11 11:10:35.250: skipped[35]:[9237][W]writeFrame A:[480],T:[84694900000]
 
- 09-11 11:10:35.322: skipped[19]:[9237][W]writeFrame V:[4800],T:[84696230000]
 
- Still in this state at 11:27:50.184 - drops all signaling messages since it thinks the session count is at 2, but there are still no viewers.

My question is if the webrtc sdk cannot detect the viewer doesn't no longer exist and let master keeps sending video/audio. Is there any message that master application can check if the viewer is still watching? For example, an active viewer would keep sending keep alive message to master, if master doesn't receive that keep alive message, then master can disconnect that connection by calling API. If there is some message we should regularly received in the doMasterMessageReceived(), then we can try do disconnect those "zombie" connections. 

UART uses local time stamp (UTC-4)
[2020-09-11 08-48-41 FT230X Basic UART #2.log.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5222216/2020-09-11.08-48-41.FT230X.Basic.UART.2.log.zip)

Log server uses UTC time stamp
[log_20200910_223023.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5222224/log_20200910_223023.zip)

**Comment by MushMal** [comment]
The peer connection state change should trigger the cleanup.

Take a look at how sample specifies it: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L32-L47

Ensure this API gets set in the peer connection like so: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L389

And, ensure that when setting the atomic to terminate the session cleanup actually does the cleanup.

We are not exposed to your code so you need to do your debugging. Please try to reproduce this issue on the stock master sample and if so we can look at the same code and make suggestions.

**Comment by sbarry157** [comment]
Here is example of this issue that is not using an echo show as the viewer. The viewer will abort and retry if it does not receive an sdp_answer within 10 seconds. There were 7 failures with an eventual success. And after the successful stream was stopped, master continued to stream and reported the number of sessions to be equal to 1.

12:44:25.651    success
12:44:14.648    failed
12:44:03.644    failed
12:43:53.641    failed
12:43:42.639    failed
12:43:31.635    failed
12:43:20.632    failed
12:43:08.631    failed

[CMAX-506-2020-09-14 12-21-40 FT230X Basic UART #2.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5229050/CMAX-506-2020-09-14.12-21-40.FT230X.Basic.UART.2.log)

**Comment by MushMal** [comment]
@jonescx @sbarry157 any update on this particular issue? Have you debugged this issue any further to understand why your master application doesn't respond properly to the state change callbacks?

**Comment by jonescx** [comment]
@MushMal We have updated the master code to the latest version of master stock and doing the network filtering now. We will check issues again after these updates.

**Comment by disa6302** [comment]
@jonescx , 

Any update?

**Comment by jonescx** [comment]
@disa6302 Sorry, no update yet.

**Comment by disa6302** [comment]
I am closing this for now. @jonescx , feel free to reopen or reach out if you have questions
