### ISSUE TITLE
[QUESTION] signalingSendMessageSync(): operation returned status code: 0x5d00002b

### ISSUE THREAD

**Issue by jonescx** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#795]
Here is a streaming fail case with these error messages. Is there any suggestion to improve it?

in UART log line 78311
09-11 11:42:54.877: [ 964][I]signalingClientSendMessageSync(): Signaling Client Sending Message Sync
09-11 11:42:54.878: [ 964][E]signalingSendMessageSync(): operation returned status code: 0x5d00002b
09-11 11:42:54.878: [ 964][E]respondWithAnswer(): operation returned status code: 0x5d00002b

in log_server4.log line 4724
[ 964][I]signalingClientSendMessageSync(): Signaling Client Sending Message Sync
[ 964][E]signalingSendMessageSync(): operation returned status code: 0x5d00002b
[ 964][E]respondWithAnswer(): operation returned status code: 0x5d00002b

UART log time (UTC-4)
[2020-09-11 08-48-41 FT230X Basic UART #2.log.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5222291/2020-09-11.08-48-41.FT230X.Basic.UART.2.log.zip)

log server time (UTC)
[log_20200910_223023.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5222292/log_20200910_223023.zip)

**Comment by MushMal** [comment]
0x5d00002b is a duplicate message status. This indicates that another send message is in progress, though I am not sure why exactly the sending is "stuck". Can you check whether you have a good network? This could happen on trickle ICE but normally this won't cause an error. Can you see if you can reproduce this on the stock master sample? You might need to be careful with the trickle ICE and sending messages. If you are responding in a message received thread then you need to perhaps serialize your sendSignalingMesasge API calls.

**Comment by sbarry157** [comment]
Here is example of this issue (same logs and sequence as mentioned in #794). The viewer will abort and retry if it does not receive an sdp_answer within 10 seconds. There were 7 failures with an eventual success. The first failure shows the error code 0x5d00002b.

12:44:25.651 success
12:44:14.648 failed
12:44:03.644 failed
12:43:53.641 failed
12:43:42.639 failed
12:43:31.635 failed
12:43:20.632 failed
12:43:08.631 failed

[CMAX-506-2020-09-14 12-21-40 FT230X Basic UART #2.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5229087/CMAX-506-2020-09-14.12-21-40.FT230X.Basic.UART.2.log)

**Comment by ycyang1229** [comment]
@sbarry157 Just curious. Did you have any ice candidate pair each streaming session? It means master does receive the remote ice candidate, handle it and make the relationship between local ice candidate and remote ice candidate. Btw, did you use single core chip as your platform? thanks.

**Comment by jonescx** [comment]
@ycyang1229 From @sbarry157 attached log, we can see the candidate pair is 0 in those fail cases.
`iceAgentCheckConnectionStateSetup(): ice candidate pair count 0`

The platform uses an ARM single core CPU.

**Comment by ycyang1229** [comment]
@jonescx I did check the log, but I am not sure the behavior since it is not the original pattern. Maybe you can confirm the sequence of related sdp. If it is not correct. you can try what I mentioned in this issue(https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/804). Thanks.

**Comment by ycyang1229** [comment]
Btw, I am not a member of this sdk team, so the suggestion from this sdk team is definitely your first choice. You can try what I mentioned if you want to do it, in case you waste your time to do it. Thanks.

**Comment by jonescx** [comment]
@ycyang1229 Thanks for your advice. We will check it out.

**Comment by MushMal** [comment]
This is a long thread including various questions. I am going to resolve this for now. Please cut separate issues with details
