### ISSUE TITLE
[QUESTION] typo?

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#799]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Sdp/Serialize.c#L33

    if (pSDPOrigin->userName[0] != '\0' && pSDPOrigin->sdpConnectionInformation.connectionAddress[0] != '\0' &&
        pSDPOrigin->sdpConnectionInformation.connectionAddress[0] != '\0' && pSDPOrigin->sdpConnectionInformation.connectionAddress[0] != '\0') {
        currentWriteSize = SNPRINTF(*ppOutputData, (*ppOutputData) == NULL ? 0 : *pBufferSize - *pTotalWritten,

Is it a typo?
thanks.

**Comment by ycyang1229** [comment]
I guess it should be like this.

    /** #BUG. */
    if (pSDPOrigin->userName[0] != '\0' && 
        pSDPOrigin->sdpConnectionInformation.networkType[0] != '\0' &&
        pSDPOrigin->sdpConnectionInformation.addressType[0] != '\0' && 
        pSDPOrigin->sdpConnectionInformation.connectionAddress[0] != '\0') {
        currentWriteSize = SNPRINTF(*ppOutputData, 
                                    (*ppOutputData) == NULL ? 0 : *pBufferSize - *pTotalWritten,
                                    SDP_ORIGIN_MARKER "%s %" PRIu64 " %" PRIu64 " %s %s %s" SDP_LINE_SEPARATOR,
                                    pSDPOrigin->userName,
                                    pSDPOrigin->sessionId,
                                    pSDPOrigin->sessionVersion,
                                    pSDPOrigin->sdpConnectionInformation.networkType,
                                    pSDPOrigin->sdpConnectionInformation.addressType,
                                    pSDPOrigin->sdpConnectionInformation.connectionAddress);

**Comment by MushMal** [comment]
Oh wow... Thanks for spotting it. Not sure how this got in but certainly need to be fixed to prevent a possible NULL deref crash.

@ycyang1229 do you want to provide a PR for this please?

**Comment by ycyang1229** [comment]
My repo is quite different from the master trunk now, so I prefer the team fix it if you think it is necessary. Maybe add code review when merging the code.

**Comment by MushMal** [comment]
No worries, just submitted a PR: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/800

**Comment by ycyang1229** [comment]
cool, thanks.

**Comment by MushMal** [comment]
fix is in
