### ISSUE TITLE
Validate input media

### ISSUE THREAD

**Issue by Sean-Der** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#80]
We should explore adding some basic input validation for H264/VP8/Opus. Full validation isn't needed, but just enough to assert that the bitstream looks ok.

Maybe this should be a debug only feature? On constrained devices this might be costly.

**Comment by Sean-Der** [comment]
We should also validating if the incoming PTS make sense. We had a user that was sending the same PTS over and over. It would be nice if we could send an error if we saw two Keyframes with the same PTS. (maybe just record last keyframe PTS?)

**Comment by disa6302** [comment]
This is a bigger story for integration. Will work on this in the future
