### ISSUE TITLE
[QUESTION] m=audio 0 or m=video 0 ?

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#802]
I assume my device only has the capability of streaming video, and tried to use video only in the sample code. 
I removed audio related code in the sample code in order to make it as a video-only device.

    CHK_STATUS(addSupportedCodec(pSampleStreamingSession->pPeerConnection, RTC_CODEC_OPUS));

    // Add a SendRecv Transceiver of type video
    audioTrack->kind = MEDIA_STREAM_TRACK_KIND_AUDIO;
    audioTrack->codec = RTC_CODEC_OPUS;
    STRCPY(audioTrack->streamId, "myKvsVideoStream");
    STRCPY(audioTrack->trackId, "myAudioTrack");
    CHK_STATUS(addTransceiver(pSampleStreamingSession->pPeerConnection, audioTrack, NULL, &pSampleStreamingSession->pAudioRtcRtpTransceiver));

    CHK_STATUS(transceiverOnBandwidthEstimation(pSampleStreamingSession->pAudioRtcRtpTransceiver, (UINT64) pSampleStreamingSession, sampleBandwidthEstimationHandler));

I got the following log by using the js sdk. Can this sdk reply to viewer with "m=audio 0 ..." or with "m=video 0 ..."? Did I make a mistake? Or I can not remove audio related code in the sample? thanks.

[2020-09-16T15:48:02.033Z] [INFO] Page loaded
[2020-09-16T15:48:51.218Z] [INFO] [VIEWER] Channel ARN:  arn:aws:kinesisvideo:us-west-2:021108525330:channel/tst123/1599494244396
[2020-09-16T15:48:51.388Z] [INFO] [VIEWER] Endpoints:  {
  "HTTPS": "https://r-4d150b47.kinesisvideo.us-west-2.amazonaws.com",
  "WSS": "wss://v-de467d09.kinesisvideo.us-west-2.amazonaws.com"
}
[2020-09-16T15:48:53.105Z] [INFO] [VIEWER] ICE servers:  [
  {
    "urls": "stun:stun.kinesisvideo.us-west-2.amazonaws.com:443"
  },
  {
    "urls": [
      "turn:52-27-201-74.t-490d1050.kinesisvideo.us-west-2.amazonaws.com:443?transport=udp",
      "turns:52-27-201-74.t-490d1050.kinesisvideo.us-west-2.amazonaws.com:443?transport=udp",
      "turns:52-27-201-74.t-490d1050.kinesisvideo.us-west-2.amazonaws.com:443?transport=tcp"
    ],
    "username": "1600271632:djE6YXJuOmF3czpraW5lc2lzdmlkZW86dXMtd2VzdC0yOjAyMTEwODUyNTMzMDpjaGFubmVsL3RzdDEyMy8xNTk5NDk0MjQ0Mzk2",
    "credential": "rtyJ5A2gQWIgLis48oZX4BWLl+Q0e73tn8XoszyYWr0="
  }
]
[2020-09-16T15:48:53.107Z] [INFO] [VIEWER] Starting viewer connection
[2020-09-16T15:48:53.846Z] [INFO] [VIEWER] Connected to signaling service
[2020-09-16T15:48:53.847Z] [INFO] [VIEWER] Creating SDP offer
[2020-09-16T15:48:53.866Z] [INFO] [VIEWER] Sending SDP offer {
  "type": "offer",
  "sdp": "v=0\r\no=- 8503335753432398307 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:UStq\r\na=ice-pwd:NzIk6lh88tDCquux1I5OAabt\r\na=ice-options:trickle\r\na=fingerprint:sha-256 25:95:F4:35:8A:87:E7:35:DC:67:F3:09:12:DA:34:FB:16:B4:2F:03:76:A4:EE:EE:02:73:6F:0C:05:FC:06:98\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:UStq\r\na=ice-pwd:NzIk6lh88tDCquux1I5OAabt\r\na=ice-options:trickle\r\na=fingerprint:sha-256 25:95:F4:35:8A:87:E7:35:DC:67:F3:09:12:DA:34:FB:16:B4:2F:03:76:A4:EE:EE:02:73:6F:0C:05:FC:06:98\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 transport-cc\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=102\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f\r\na=rtpmap:121 rtx/90000\r\na=fmtp:121 apt=127\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 goog-remb\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:107 rtx/90000\r\na=fmtp:107 apt=125\r\na=rtpmap:108 H264/90000\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:124 red/90000\r\na=rtpmap:120 rtx/90000\r\na=fmtp:120 apt=124\r\na=rtpmap:123 ulpfec/90000\r\n"
}
[2020-09-16T15:48:53.868Z] [INFO] [VIEWER] Generating ICE candidates
[2020-09-16T15:48:53.870Z] [INFO] [VIEWER] Generated ICE candidate
[2020-09-16T15:48:53.871Z] [INFO] [VIEWER] Sending ICE candidate
[2020-09-16T15:48:53.872Z] [INFO] [VIEWER] Generated ICE candidate
[2020-09-16T15:48:53.872Z] [INFO] [VIEWER] Sending ICE candidate
[2020-09-16T15:48:54.105Z] [INFO] [VIEWER] Generated ICE candidate
[2020-09-16T15:48:54.105Z] [INFO] [VIEWER] Sending ICE candidate
[2020-09-16T15:48:54.110Z] [INFO] [VIEWER] Generated ICE candidate
[2020-09-16T15:48:54.110Z] [INFO] [VIEWER] Sending ICE candidate
[2020-09-16T15:48:54.234Z] [INFO] [VIEWER] Generated ICE candidate
[2020-09-16T15:48:54.235Z] [INFO] [VIEWER] Sending ICE candidate
[2020-09-16T15:48:54.250Z] [INFO] [VIEWER] Generated ICE candidate
[2020-09-16T15:48:54.251Z] [INFO] [VIEWER] Sending ICE candidate
[2020-09-16T15:48:54.711Z] [INFO] [VIEWER] Generated ICE candidate
[2020-09-16T15:48:54.711Z] [INFO] [VIEWER] Sending ICE candidate
[2020-09-16T15:48:54.717Z] [INFO] [VIEWER] Generated ICE candidate
[2020-09-16T15:48:54.718Z] [INFO] [VIEWER] Sending ICE candidate
[2020-09-16T15:48:54.722Z] [INFO] [VIEWER] Generated ICE candidate
[2020-09-16T15:48:54.722Z] [INFO] [VIEWER] Sending ICE candidate
[2020-09-16T15:48:54.724Z] [INFO] [VIEWER] Generated ICE candidate
[2020-09-16T15:48:54.724Z] [INFO] [VIEWER] Sending ICE candidate
[2020-09-16T15:48:56.072Z] [INFO] [VIEWER] Received SDP answer {
  "type": "answer",
  "sdp": "v=0\r\no=- 993687334 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS myKvsVideoStream\r\nm=video 9 UDP/TLS/RTP/SAVPF 108 109\r\nc=IN IP4 127.0.0.1\r\na=msid:myKvsVideoStream myVideoTrackRTX\r\na=ssrc-group:FID 1370429126 502141743\r\na=ssrc:1370429126 cname:afNRUWxueEcKJbMa\r\na=ssrc:1370429126 msid:myKvsVideoStream myVideoTrack\r\na=ssrc:1370429126 mslabel:myKvsVideoStream\r\na=ssrc:1370429126 label:myVideoTrack\r\na=ssrc:502141743 cname:afNRUWxueEcKJbMa\r\na=ssrc:502141743 msid:myKvsVideoStream myVideoTrackRTX\r\na=ssrc:502141743 mslabel:myKvsVideoStreamRTX\r\na=ssrc:502141743 label:myVideoTrackRTX\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:jF6f\r\na=ice-pwd:4quOed//hnyPwM9ibNqa4lLe\r\na=ice-options:trickle\r\na=fingerprint:sha-256 76:9B:75:27:E0:E6:B5:8D:55:30:F3:1E:F8:AB:7A:DF:A3:43:5F:59:48:4E:F4:BB:81:7F:BC:79:12:E5:90:16\r\na=setup:active\r\na=mid:0\r\na=sendonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:108 H264/90000\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtcp-fb:108 nack\r\n"
}
[2020-09-16T15:48:56.077Z] [ERROR] InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.
[2020-09-16T15:48:56.325Z] [INFO] [VIEWER] Received ICE candidate
[2020-09-16T15:48:56.333Z] [ERROR] OperationError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate
[2020-09-16T15:49:33.644Z] [INFO] [VIEWER] All ICE candidates have been generated
[2020-09-16T15:58:56.326Z] [INFO] [VIEWER] Disconnected from signaling channel

**Comment by MushMal** [comment]
You should be able to remove the audio from the sample. Unfortunately, the issue you've posted is vague and is not actionable on our side. I am going to close this issue. Please cut a targeted question that we can help you with

**Comment by ycyang1229** [comment]
Does this sdk handle this situation for video-only? The order of m-lines in answer doesn't match order in offer.

**Comment by hassanctech** [comment]
It would work, what version of the SDK are you using?  This issue was fixed a month ago and I tested it by removing audio parts from the sample.

**Comment by ycyang1229** [comment]
My repo is detached from this commit. Would you mind giving me the commit fixing this problem? I did not add codec table and tranceiver of audio. Does this sdk reply to the viewer with "m=audio 0"? Or just ignore the "m=audio xxx" from offer.

*   commit e2fad0b46c5ae8ccfae5fd600c523c97f9cf8b3e (origin/viewer-mode, origin/master, origin/jetson-porting, origin/HEAD, master)
|\  Merge: 1d8a292a 2c7af1f3
| | Author: Divya Sampath Kumar <disa6302@colorado.edu>
| | Date:   Thu Aug 13 17:12:52 2020 -0700
| | 
| |     Merge pull request #697 from zhuker/datachannel-stats
| |     
| |     RTCDataChannelStats

**Comment by hassanctech** [comment]
Yep that would explain it -- this is where it is fixed:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/5f24664abb9f07d2ebd776a965ef7ff51f647746

Which is from Aug 19, it looks like you have a commit from Aug 13.

**Comment by ycyang1229** [comment]
Cool. It looks good. I will try it tmr in my timezone.  Thanks.

**Comment by ycyang1229** [comment]
I used the latest webrtc sdk on ubuntu, and webrtc test page on chrome. Did not add the codec table and transceiver of audio and made master sample as video-only. It did not work.  Safari works since it seems not to check "m=".  Not sure the team want to deep dive into this, or has the plan to do sdp negotiation.

**Comment by hassanctech** [comment]
Yes actually what you describe is a known issue -- it works in Safari because in the js sdk we offer to receive/send audio (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/examples/viewer.js#L131-L132) but Safari ignores those and actually doesn't send any m lines for media types that are not explicitly selected.  What I mean by this is when you select video-only in the master sample Chrome will send a sendrecv video m-line and a recvonly audio m-line however Safari will send a sendrecv video m-line and that's all.  This is why when you've commented out audio in the master sample

I've created a new bug for this:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/803

**Comment by ycyang1229** [comment]
Thanks for the detailed information. Look forward to its fix. Would you also consider the  scenario of audio-only?

**Comment by hassanctech** [comment]
Yes, the fix would make sure we match up a response m-line to all m-lines present in the answer, which we do now the only exception is when the master side doesn't have the matching capability in which case we don't currently "create" the capability if it's not in the local transceiver to send an m-line but the correct solution is to still send the response to match the answer with direction set to inactive.

**Comment by ycyang1229** [comment]
Cool. That will be nice. Thanks.
