### ISSUE TITLE
[BUG] Answer m-lines should match offer m-lines even when answerer doesn't support media type

### ISSUE THREAD

**Issue by hassanctech** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#803]
**Describe the bug**
The master sample right now adds audio/video transceivers.  If we modify it to only have video -- when replying to an offer which has recvonly audio, instead of sending an m-line it will send nothing.  

Need to modify the logic that determines the response to match m-lines in offer even when local transceivers might not have matching media.

**SDK version number**
eac3e1656aa01b3f3d730fb80272d062fd7cb538 (latest)

**Open source building**

**To Reproduce**
1. Modify master sample to have video only
2. Run test page (https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html) in Chrome and select audio and video
3. Start master, and then start viewer
4. See error about non-matching m-lines

**Expected behavior**
The answer (from the master side) should contain an m-line for audio but the direction can indicate it's not actually supported

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by disa6302** [comment]
The work has not been initiated yet.
