### ISSUE TITLE
[QUESTION] Does this sdk pend the emitting of ice candidate until sdp offer or answer is received? 

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#804]
Does this sdk pend the emitting of ice candidate until sdp offer or answer is received? The js sdk does, but I am not sure c sdk support this or not. Thanks. 

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/src/SignalingClient.ts#L283
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/src/SignalingClient.ts#L298

**Comment by MushMal** [comment]
The SDK is not the one responsible for it. In this case, it's the master and viewer sample applications. They use the signaling client to exchange the offer and answer and then prepare the peer connection which would then use the signaling client in the ICE agent state machinery to exchange the ICE candidates

**Comment by ycyang1229** [comment]
Thanks for the information. I wonder the specification of trickle ice defines the behavior of sdp offer/answer/ice candidate or not. 
After master receives the sdp offer. Does master need to hold all the local ice candidate until it sends the sdp answer? Or the master can send local ice candidate freely after receiving the sdp offfer?

**Comment by MushMal** [comment]
In trickle ice more the master will send the answer and will start sending the ice candidates as it discovers the

**Comment by ycyang1229** [comment]
I am using one single-core 240Mhz chip to run this sdk, and it works well at low bit rate/frame rate now. Device as a master, and js sdk as a viewer. Why I trying to confirm this behavior of trickle ice here. It is because of having the similar situation in this case(https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/795). When the sequence was not correct, I received the error message(0x5d00002b). And Lws looked like hanging there. I think lws should not hang there even the sequence is not correct. I have no clue why it hangs there, but I will deep dive into it later. Maybe you have some thought about it. Btw, does kvs backend only relays the sdp of offer/answer/ice candidate between master and viewer? I am trying to identify the behavior of trickle ice by going through the draft of trickle ice. But I did not find anything to specify it clearly. Would you mind pointing it out(which section in the draft) and helping me out of this specification hell. Thanks.

**Comment by ycyang1229** [comment]
Btw, does the team have the plan to do zero-copy/__packed...etc to speed up the process of packets?

**Comment by MushMal** [comment]
I think it's not the LWS that stuck in the first case. What happens is that while we gather the ICE candidates, the socket code gets blocked and times out 5 seconds later. This causes timeouts throughout which is expected. Recommend filtering all the interfaces which are "bad". For example, if your device has both wifi and ethernet, and the latter one is not plugged in, it will cause the timeout. Filtering those interfaces will help to resolve it.

Regarding the zero alloc/zero copy. I believe we have a work item to track this but no certain timeline yet.

**Comment by ycyang1229** [comment]
I only have one network interface, and I confirmed it only has two ice candidates(host/srflx) in the master when I disabled turn. I saw the lws did not send writable callback back to lws routine, so I guess it may hang there.  But you are right. I will check the socket code and confirm the behavior. Thanks for your advice. :)

**Comment by disa6302** [comment]
@ycyang1229 , 

Closing this issue for now. Feel free to reach out if you have any questions.
