### ISSUE TITLE
[BUG] dereference null pointer in executeGetTokenSignalingState

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#808]
Hi experts,

in `executeGetTokenSignalingState`,  we try to get new credential
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/StateMachine.c#L279
however, `pSignalingClient->pAwsCredentials` could be null if get credential fails.
e.g. I got null credential with the following log
```
[09-18 15:33:07][2020-08-18 07:33:07] [KVS]lwsIotCallbackRoutine(): Client connection failed. Connection error string: lws_ssl_client_connect1 failed
[09-18 15:33:08][2020-08-18 07:33:07] [KVS]lwsIotCallbackRoutine(): Client http closed
```
Then we will dereference null pointer https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Signaling/StateMachine.c#L282

Thank you!

**Comment by MushMal** [comment]
@staowyze thanks for reporting. We need to properly fix this.

**Comment by MushMal** [comment]
Done
