### ISSUE TITLE
[QUESTION] Is it a good idea to fail peer connection when DTLS fails?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#815]
In https://github.com/suggestedfixes/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/PeerConnection.c,

VOID onDtlsStateChange(UINT64 customData, RTC_DTLS_TRANSPORT_STATE newDtlsState)

We see that we map DTLS state is closed, we trigger RTC_PEER_CONNECTION_STATE_CLOSED.

Is it also ok if the DTLS session is failed, we also trigger RTC_PEER_CONNECTION_STATE_FAILED?

**Comment by suggestedfixes** [comment]
Looks like this is a hard question to answer. I will run some experiments I suppose.

**Comment by MushMal** [comment]
Resolving this for now. Please cut a new issue if you need further help. As is, we can't make any assumptions
