### ISSUE TITLE
Have released the integration guide with Alexa?

### ISSUE THREAD

**Issue by pai-da-xin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#820]
Hello,Experts,

Excuse me,Have released the integration guide with Alexa?Whether to push the reference lambda code on GitHub.

**Comment by suggestedfixes** [comment]
Pst. you can email @bdhandap or kinesis-video-support@amazon.com for a sample lambda implementation.

**Comment by pai-da-xin** [comment]
OK,Thank you for your reply.
