### ISSUE TITLE
[QUESTION] How do you close an existing data channel?

### ISSUE THREAD

**Issue by mdonahoe** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#823]
So I have this function in my master code
```
void onDataChannel(UINT64 customData, PRtcDataChannel pRtcDataChannel) {
  // set up message handler
  dataChannelOnMessage(pRtcDataChannel, (UINT64)customData, myHandlerFunc);
}
```

And everything is good. But how do I let the master `close` the datachannel so it stops handling messages from the client? Is that part of the data channel api?

**Comment by disa6302** [comment]
@mdonahoe , 

It should be, but not sure why we do not have it. Let me create a new ticket and tag this as a feature request. 
In the meantime, what you could probably do is, you can try to add No-op type of instruction to avoid handling incoming messages. Not sure what your use case is though.

**Comment by disa6302** [comment]
Feature still unimplemented.

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.

**Comment by Tad-CQ** [comment]
any updates?
