### ISSUE TITLE
[BUG] src/source/PeerConnection/PeerConnection.c has a bug to cause crash

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#827]
Line https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/8c1eaf09d8f27d13efdac3808b3d6b7cd554fa74/src/source/PeerConnection/PeerConnection.c#L342
has a bug.
The static cast to (PUINT64) causes the neighboring stack variable, "pTransceiver" to be overwritten.
When onFrameDroppedFunc() is called, damaged value of "pTransceiver" makes webrtc crash.

The following patch helps to fix the problem. I also notice that the same problem also happens in onFrameReadyFunc().  We are "lucky" that the overwritten there doesn't cause anything.  Please check if there are similar problems somewhere else.

diff --git a/src/source/PeerConnection/PeerConnection.c b/src/source/PeerConnection/PeerConnection.c
index 88d56df..38275ab 100644
--- a/src/source/PeerConnection/PeerConnection.c
+++ b/src/source/PeerConnection/PeerConnection.c
@@ -335,11 +335,13 @@ STATUS onFrameDroppedFunc(UINT64 customData, UINT16 startIndex, UINT16 endIndex,
 {
     UNUSED_PARAM(endIndex);
     STATUS retStatus = STATUS_SUCCESS;
+    UINT64 hashValue = 0;
     PRtpPacket pPacket = NULL;
     PKvsRtpTransceiver pTransceiver = (PKvsRtpTransceiver) customData;
     DLOGW("Frame with timestamp %ld is dropped!", timestamp);
     CHK(pTransceiver != NULL, STATUS_NULL_ARG);
-    retStatus = hashTableGet(pTransceiver->pJitterBuffer->pPkgBufferHashTable, startIndex, (PUINT64) &pPacket);
+    retStatus = hashTableGet(pTransceiver->pJitterBuffer->pPkgBufferHashTable, startIndex, &hashValue);
+    pPacket = (PRtpPacket) hashValue;
     if (retStatus == STATUS_SUCCESS || retStatus == STATUS_HASH_KEY_NOT_PRESENT) {
         retStatus = STATUS_SUCCESS;
     } else {

**Comment by MushMal** [comment]
Oh WOW! Cool. This will clearly happen on a 32 bit system! Thanks for spotting, it is hard to notice while doing a CR.

Do you want to push a quick PR for this please?

We will also inspect the codebase for other instances. @disa6302 - FYI

**Comment by shiv50084** [comment]
@MushMal 
My issue #770 also related to this. After changing suggested by @zwei333 .Its working fine.

**Comment by zwei333** [comment]
@MushMal I can wait for the fix.

**Comment by hassanctech** [comment]
Thanks I'm in the process of going through this and will put out a PR shortly

**Comment by hassanctech** [comment]
PR is out for this

**Comment by shiv50084** [comment]
@hassanctech 
Still issue reproducible in my embedded system
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L1011

after this line 1011 pSampleConfiguration i am getting NULL but before that its getting proper address

**Comment by hassanctech** [comment]
Not merged yet, I forgot to run clang-format that test failed, should be in soon though

**Comment by hassanctech** [comment]
Change has been merged.  @shiv50084 please try with the latest master.
