### ISSUE TITLE
[BUG] clang-format does not work properly.

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#831]
**Describe the bug**
Please specify the version of clang-format this sdk prefers or adjust the yaml.
You refer this pr to check the log.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/828

**Comment by ycyang1229** [comment]
@MushMal created one issue for tracking this. thanks.

**Comment by disa6302** [comment]
@ycyang1229 , 

The clang format with which this was tested on Mac and linux is 10.0.0.

**Comment by MushMal** [comment]
Closing this issue, please reopen with more information so we can pinpoint the issue
