### ISSUE TITLE
[FEATURE] Add a 32 bits system to the CI

### ISSUE THREAD

**Issue by lherman-cs** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#833]
**Is your feature request related to a problem? Please describe.**
Our SDK was designed to run on both 32 and 64 bits systems. But, our CI doesn't have any 32 bits system to check the SDK's integrity.

Unfortunately, TravisCI doesn't have 32 bits systems, https://docs.travis-ci.com/user/multi-cpu-architectures/.

Travis Open Issue:
https://github.com/travis-ci/travis-ci/issues/5770

**Describe the solution you'd like**
I think we should create/use a docker image which we run the binary through a 32 bit simulator.

**Comment by disa6302** [comment]
This item is being tracked internally.
