### ISSUE TITLE
[QUESTION] How to use sdk into another project

### ISSUE THREAD

**Issue by VRichardJP** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#836]
Hi,

I am trying to understand how to integrate the SDK into another CMake project.
Typically, how can I compile a sample application using the SDK but not within the SDK?

I have tried to create a project and add the SDK as subdirectory or ExternalProject but without success. I always end up facing some CMake configuration issue or missing headers. For instance the Sample.h header requires several headers that are not found in this repository.

Thank you for your help

**Comment by lherman-cs** [comment]
@VRichardJP we have a demo repository that shows how to use our SDK for targeted use cases, https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/webrtc-c/canary. In that repo, it shows how you can integrate the SDK in CMake.

**Comment by VRichardJP** [comment]
This was exactly what I was looking for
Thank you very much !
