### ISSUE TITLE
[QUESTION] Suggestions on Tweaking Timeouts on a Slow Network?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#849]
We are simulating scenarios where the viewer network bandwidth is slightly above the master video bitrate (1mbps).
When this happens, the success rate of a connection drops. In a simulated low bandwidth environment, the connection success rate is still pretty high. But with an actual slow network, the connection success rate is lower. So this leads us to think that the lower success rate is due to jitter and high latency of an actual network, leading to timeouts. So what would be some recommended parameters to start tweaking? Or some places where we can enable more logging on what timed out?

**Comment by suggestedfixes** [comment]
We also tried to map out the maximum bitrate that the camera can be set where we can make a successful connection.

Base bandwidth: 80Mbps
Variable bitrate until we can no longer make a connection/decode: 7000kbps, ~ 12 times smaller
Constant bitrate until we can no longer make a connection/decode: 3000kbps, ~ 27 times smaller

Assuming the following model is true:
N = C * B, where N = Network Bandwidth, B = camera bitrate, C = constant.
C_cbr = 27
C_vbr = 12

Those numbers seem a bit too big. Intuitively if we just stream one camera, C_cbr or C_vbr should be roughly 1 to 3 correct?

Then we have something as follows, are we roughly on track to estimate the max bitrate a customer can set to make sure a reliable connection?

Network Bandwidth   (Mbps) | Max CBR (kbps) | Max VBR (kbps)
-- | -- | --
5 | 185.1851852 | 416.6666667
10 | 370.3703704 | 833.3333333
15 | 555.5555556 | 1250
20 | 740.7407407 | 1666.666667
25 | 925.9259259 | 2083.333333
30 | 1111.111111 | 2500
35 | 1296.296296 | 2916.666667
40 | 1481.481481 | 3333.333333
45 | 1666.666667 | 3750
50 | 1851.851852 | 4166.666667
55 | 2037.037037 | 4583.333333
60 | 2222.222222 | 5000
65 | 2407.407407 | 5416.666667
70 | 2592.592593 | 5833.333333
75 | 2777.777778 | 6250
80 | 2962.962963 | 6666.666667

**Comment by MushMal** [comment]
Perhaps we should clarify what a success rate is? If we are talking about the rate at which both clients are able to START stream actual media then the bandwidth has nothing to do with it - latency and packet loss is.

**Comment by suggestedfixes** [comment]
The threshold for success rate is roughly 90% - 95%, as we are manually clicking. If we were to set 1.5 times of the bitrate estimated, then for sure is the success rate is very low.

**Comment by suggestedfixes** [comment]
You have a good point, "latency and packet loss" are better indicators.

**Comment by suggestedfixes** [comment]
There is an implicit relationship between low bandwidth network and latency and packet loss. So it might still be a valid table. It might be one of the cases where A correlates with B which correlates with C. And it's probably ok to run a linear regression model with A and C.

**Comment by MushMal** [comment]
I am still unsure what the ask is.

1) The required bandwidth is a product of the encoder settings - such as the resolution, the encoding parameters, quality, color space, etc..
2) The observed bandwidth is just that - what's the throughput. This should be greater or equal to the required bandwidth to have non-dropped frame experience.

The bandwidth has no bearing on the success rate of connection establishment. Perhaps, some packets get lost during ICE negotiation or something.

Could you perhaps rephrase what your ask is as I am a little confused.

**Comment by suggestedfixes** [comment]
1. The user has an option to set the remote camera's max bitrate to around 1Mbps
2. Bandwidth measured from user's browser, let's assume it's 15Mbps

- We found that at 15Mbps, the user has trouble making a successful connection.
- However, if we were to set the bitrate to 250kbps, the success rate is much higher.

- So we assume there is a constant factor that links the two, so we did more experiments
- At 80Mbps from our browser, we cranked up the camera bitrate until there's a point of failure, that's where we got the numbers.

**Comment by suggestedfixes** [comment]
Like you mentioned, latency and packet loss are more relevant. 
I'm trying to explain, there is a correlation between user's network bandwidth and user's "latency and packet loss"

That's why the original post was asking whether there are timeouts that are too strict?

**Comment by suggestedfixes** [comment]
"Perhaps, some packets get lost during ICE negotiation or something" this could be one of the factors.

**Comment by MushMal** [comment]
I am puzzled like you but this is one thing that we won't be able to help at all. You really need to debug your network to understand why an increased bandwidth results in some network configuration changes resulting in issues you've mentioned. I don't even know what those issues are - whether you have an issue with the signaling client connection, message delivery, ICE negotiation process or later with actual frame streaming.

As is, this is not actionable. I am going to close this for now. Please cut an issue when you debug into the scenario where there is an issue with KVS SDKs

**Comment by suggestedfixes** [comment]
@MushMal I believe it has to do with actual frame streaming. Grabbing log.

**Comment by MushMal** [comment]
Perfect. Please cut a new issue with the detailed statement of what's going on and the debug logs so we can focus on it
