### ISSUE TITLE
[QUESTION] pFrame->flag value remains the same for all frames

### ISSUE THREAD

**Issue by suraj-vantigodi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#854]
Hi,

In the viewer code, I need to perform image processing to detect emotions and hence I am planning to perform the task only on the keyframes and for this I need to know the frame type I,P or B.

My understanding was that pFrame->flags hods this value, the value should be different for I,P or B frames. However I've noticed that the value remains the same throughout the stream and is randomly assigned every time I run the Viewer. Can you please tell me how to get the frame type value from the viewer (I, P or B)?

Sample values for pFrame->flags

`Frame received. TrackId: 1, Size: 1329, Flags 3899268981

 Frame received. TrackId: 1, Size: 1096, Flags 3899268981
 Frame received. TrackId: 1, Size: 1117, Flags 3899268981
 Frame received. TrackId: 1, Size: 1258, Flags 3899268981
 Frame received. TrackId: 1, Size: 1070, Flags 3899268981
 Frame received. TrackId: 1, Size: 1155, Flags 3899268981
 Frame received. TrackId: 1, Size: 1259, Flags 3899268981
 Frame received. TrackId: 1, Size: 1233, Flags 3899268981
 Frame received. TrackId: 1, Size: 1286, Flags 3899268981
 Frame received. TrackId: 1, Size: 1307, Flags 3899268981
 Frame received. TrackId: 1, Size: 1138, Flags 3899268981
 Frame received. TrackId: 1, Size: 1093, Flags 3899268981
 Frame received. TrackId: 1, Size: 1093, Flags 3899268981
 Frame received. TrackId: 1, Size: 927, Flags 3899268981
 Frame received. TrackId: 1, Size: 1410, Flags 3899268981
 Frame received. TrackId: 1, Size: 1165, Flags 3899268981
 Frame received. TrackId: 1, Size: 1414, Flags 3899268981
 Frame received. TrackId: 1, Size: 1280, Flags 3899268981
 Frame received. TrackId: 1, Size: 1035, Flags 3899268981
 Frame received. TrackId: 1, Size: 1145, Flags 3899268981
 Frame received. TrackId: 1, Size: 1338, Flags 3899268981
 Frame received. TrackId: 1, Size: 847, Flags 3899268981
 Frame received. TrackId: 1, Size: 1431, Flags 3899268981
 Frame received. TrackId: 1, Size: 1316, Flags 3899268981
 Frame received. TrackId: 1, Size: 1220, Flags 3899268981
 Frame received. TrackId: 1, Size: 1175, Flags 3899268981
 Frame received. TrackId: 1, Size: 1072, Flags 3899268981
 Frame received. TrackId: 1, Size: 1350, Flags 3899268981
 Frame received. TrackId: 1, Size: 1264, Flags 3899268981
 Frame received. TrackId: 1, Size: 863, Flags 3899268981
 Frame received. TrackId: 1, Size: 1249, Flags 3899268981
 Frame received. TrackId: 1, Size: 1220, Flags 3899268981
 Frame received. TrackId: 1, Size: 1352, Flags 3899268981
 Frame received. TrackId: 1, Size: 1425, Flags 3899268981
 Frame received. TrackId: 1, Size: 1136, Flags 3899268981
 Frame received. TrackId: 1, Size: 1102, Flags 3899268981
 Frame received. TrackId: 1, Size: 1117, Flags 3899268981
 Frame received. TrackId: 1, Size: 989, Flags 3899268981
 Frame received. TrackId: 1, Size: 1228, Flags 3899268981
 Frame received. TrackId: 1, Size: 1276, Flags 3899268981
 Frame received. TrackId: 1, Size: 1441, Flags 3899268981
 Frame received. TrackId: 1, Size: 1487, Flags 3899268981
 Frame received. TrackId: 1, Size: 1011, Flags 3899268981
 Frame received. TrackId: 1, Size: 1252, Flags 3899268981
 Frame received. TrackId: 1, Size: 940, Flags 3899268981
 Frame received. TrackId: 1, Size: 925, Flags 3899268981
 Frame received. TrackId: 1, Size: 1570, Flags 3899268981
 Frame received. TrackId: 1, Size: 1272, Flags 3899268981
 Frame received. TrackId: 1, Size: 1266, Flags 3899268981
 Frame received. TrackId: 1, Size: 1145, Flags 3899268981
 Frame received. TrackId: 1, Size: 1127, Flags 3899268981
 Frame received. TrackId: 1, Size: 1081, Flags 3899268981
 Frame received. TrackId: 1, Size: 1197, Flags 3899268981
 Frame received. TrackId: 1, Size: 890, Flags 3899268981
 Frame received. TrackId: 1, Size: 1151, Flags 3899268981
 Frame received. TrackId: 1, Size: 1304, Flags 3899268981
 Frame received. TrackId: 1, Size: 1316, Flags 3899268981
 Frame received. TrackId: 1, Size: 1261, Flags 3899268981
 Frame received. TrackId: 1, Size: 1210, Flags 3899268981
 Frame received. TrackId: 1, Size: 1465, Flags 3899268981
 Frame received. TrackId: 1, Size: 1610, Flags 3899268981
 Frame received. TrackId: 1, Size: 1803, Flags 3899268981
 Frame received. TrackId: 1, Size: 1343, Flags 3899268981
 Frame received. TrackId: 1, Size: 1047, Flags 3899268981
 Frame received. TrackId: 1, Size: 1333, Flags 3899268981
 Frame received. TrackId: 1, Size: 1384, Flags 3899268981
 Frame received. TrackId: 1, Size: 1422, Flags 3899268981
 Frame received. TrackId: 1, Size: 1434, Flags 3899268981
 Frame received. TrackId: 1, Size: 1393, Flags 3899268981
 Frame received. TrackId: 1, Size: 1531, Flags 3899268981
 Frame received. TrackId: 1, Size: 1412, Flags 3899268981
 Frame received. TrackId: 1, Size: 1343, Flags 3899268981
 Frame received. TrackId: 1, Size: 1370, Flags 3899268981
 Frame received. TrackId: 1, Size: 1434, Flags 3899268981
 Frame received. TrackId: 1, Size: 1692, Flags 3899268981
 Frame received. TrackId: 1, Size: 6058, Flags 3899268981
 Frame received. TrackId: 1, Size: 2751, Flags 3899268981
 Frame received. TrackId: 1, Size: 1545, Flags 3899268981
 Frame received. TrackId: 1, Size: 1181, Flags 3899268981
 Frame received. TrackId: 1, Size: 1574, Flags 3899268981
 Frame received. TrackId: 1, Size: 1223, Flags 3899268981
 Frame received. TrackId: 1, Size: 1128, Flags 3899268981
 Frame received. TrackId: 1, Size: 951, Flags 3899268981
 Frame received. TrackId: 1, Size: 2171, Flags 3899268981
 Frame received. TrackId: 1, Size: 1168, Flags 3899268981
 Frame received. TrackId: 1, Size: 899, Flags 3899268981
 Frame received. TrackId: 1, Size: 1315, Flags 3899268981
 Frame received. TrackId: 1, Size: 1181, Flags 3899268981
 Frame received. TrackId: 1, Size: 1297, Flags 3899268981
 Frame received. TrackId: 1, Size: 1332, Flags 3899268981
 Frame received. TrackId: 1, Size: 728, Flags 3899268981
 Frame received. TrackId: 1, Size: 1269, Flags 3899268981
 Frame received. TrackId: 1, Size: 951, Flags 3899268981
 Frame received. TrackId: 1, Size: 1360, Flags 3899268981
 Frame received. TrackId: 1, Size: 1228, Flags 3899268981
 Frame received. TrackId: 1, Size: 781, Flags 3899268981
 Frame received. TrackId: 1, Size: 1278, Flags 3899268981
 Frame received. TrackId: 1, Size: 966, Flags 3899268981
 Frame received. TrackId: 1, Size: 1498, Flags 3899268981
 Frame received. TrackId: 1, Size: 1103, Flags 3899268981
 Frame received. TrackId: 1, Size: 1270, Flags 3899268981
 Frame received. TrackId: 1, Size: 1644, Flags 3899268981
 Frame received. TrackId: 1, Size: 1366, Flags 3899268981
 Frame received. TrackId: 1, Size: 1258, Flags 3899268981
 Frame received. TrackId: 1, Size: 1405, Flags 3899268981
 Frame received. TrackId: 1, Size: 1198, Flags 3899268981
 Frame received. TrackId: 1, Size: 1109, Flags 3899268981
 Frame received. TrackId: 1, Size: 1163, Flags 3899268981
 Frame received. TrackId: 1, Size: 1236, Flags 3899268981
 Frame received. TrackId: 1, Size: 1240, Flags 3899268981
 Frame received. TrackId: 1, Size: 1464, Flags 3899268981
 Frame received. TrackId: 1, Size: 1444, Flags 3899268981
 Frame received. TrackId: 1, Size: 1308, Flags 3899268981
 Frame received. TrackId: 1, Size: 1465, Flags 3899268981
 Frame received. TrackId: 1, Size: 2139, Flags 3899268981
 Frame received. TrackId: 1, Size: 1384, Flags 3899268981
 Frame received. TrackId: 1, Size: 1561, Flags 3899268981
 Frame received. TrackId: 1, Size: 1334, Flags 3899268981
 Frame received. TrackId: 1, Size: 1779, Flags 3899268981
 Frame received. TrackId: 1, Size: 2165, Flags 3899268981
 Frame received. TrackId: 1, Size: 1929, Flags 3899268981
 Frame received. TrackId: 1, Size: 1929, Flags 3899268981
 Frame received. TrackId: 1, Size: 1761, Flags 3899268981
 Frame received. TrackId: 1, Size: 1072, Flags 3899268981
 Frame received. TrackId: 1, Size: 1065, Flags 3899268981
 Frame received. TrackId: 1, Size: 1269, Flags 3899268981
 Frame received. TrackId: 1, Size: 1296, Flags 3899268981
 Frame received. TrackId: 1, Size: 1266, Flags 3899268981
 Frame received. TrackId: 1, Size: 1114, Flags 3899268981
 Frame received. TrackId: 1, Size: 995, Flags 3899268981
 Frame received. TrackId: 1, Size: 888, Flags 3899268981
 Frame received. TrackId: 1, Size: 1251, Flags 3899268981
 Frame received. TrackId: 1, Size: 1285, Flags 3899268981
 Frame received. TrackId: 1, Size: 1753, Flags 3899268981
 Frame received. TrackId: 1, Size: 1615, Flags 3899268981
 Frame received. TrackId: 1, Size: 1298, Flags 3899268981
 Frame received. TrackId: 1, Size: 1338, Flags 3899268981
 Frame received. TrackId: 1, Size: 1206, Flags 3899268981
 Frame received. TrackId: 1, Size: 1394, Flags 3899268981
 Frame received. TrackId: 1, Size: 1173, Flags 3899268981
 Frame received. TrackId: 1, Size: 1210, Flags 3899268981
 Frame received. TrackId: 1, Size: 407, Flags 3899268981
 Frame received. TrackId: 1, Size: 1285, Flags 3899268981
 Frame received. TrackId: 1, Size: 1013, Flags 3899268981
 Frame received. TrackId: 1, Size: 1458, Flags 3899268981
 Frame received. TrackId: 1, Size: 1002, Flags 3899268981
 Frame received. TrackId: 1, Size: 1436, Flags 3899268981
 Frame received. TrackId: 1, Size: 1066, Flags 3899268981
 Frame received. TrackId: 1, Size: 1152, Flags 3899268981
 Frame received. TrackId: 1, Size: 992, Flags 3899268981
 Frame received. TrackId: 1, Size: 1239, Flags 3899268981
 Frame received. TrackId: 1, Size: 1368, Flags 3899268981
 Frame received. TrackId: 1, Size: 939, Flags 3899268981
 Frame received. TrackId: 1, Size: 1031, Flags 3899268981
 Frame received. TrackId: 1, Size: 1188, Flags 3899268981
 Frame received. TrackId: 1, Size: 1261, Flags 3899268981
 Frame received. TrackId: 1, Size: 1258, Flags 3899268981
 Frame received. TrackId: 1, Size: 1414, Flags 3899268981
 Frame received. TrackId: 1, Size: 1151, Flags 3899268981
 Frame received. TrackId: 1, Size: 1444, Flags 3899268981
 Frame received. TrackId: 1, Size: 1273, Flags 3899268981
 Frame received. TrackId: 1, Size: 1040, Flags 3899268981
 Frame received. TrackId: 1, Size: 1102, Flags 3899268981
 Frame received. TrackId: 1, Size: 1254, Flags 3899268981
 Frame received. TrackId: 1, Size: 622, Flags 3899268981
 Frame received. TrackId: 1, Size: 1224, Flags 3899268981
 Frame received. TrackId: 1, Size: 1238, Flags 3899268981
 Frame received. TrackId: 1, Size: 1020, Flags 3899268981
 Frame received. TrackId: 1, Size: 1392, Flags 3899268981
 Frame received. TrackId: 1, Size: 1043, Flags 3899268981
 Frame received. TrackId: 1, Size: 1224, Flags 3899268981
 Frame received. TrackId: 1, Size: 1269, Flags 3899268981
 Frame received. TrackId: 1, Size: 1368, Flags 3899268981
 Frame received. TrackId: 1, Size: 1296, Flags 3899268981
 Frame received. TrackId: 1, Size: 1340, Flags 3899268981
 Frame received. TrackId: 1, Size: 1306, Flags 3899268981
 Frame received. TrackId: 1, Size: 1216, Flags 3899268981
 Frame received. TrackId: 1, Size: 1233, Flags 3899268981
 Frame received. TrackId: 1, Size: 1196, Flags 3899268981
 Frame received. TrackId: 1, Size: 1349, Flags 3899268981
 Frame received. TrackId: 1, Size: 1815, Flags 3899268981
 Frame received. TrackId: 1, Size: 1528, Flags 3899268981
 Frame received. TrackId: 1, Size: 1492, Flags 3899268981
 Frame received. TrackId: 1, Size: 1379, Flags 3899268981
 Frame received. TrackId: 1, Size: 1427, Flags 3899268981
 Frame received. TrackId: 1, Size: 1116, Flags 3899268981
 Frame received. TrackId: 1, Size: 1193, Flags 3899268981
 Frame received. TrackId: 1, Size: 1145, Flags 3899268981
 Frame received. TrackId: 1, Size: 1226, Flags 3899268981
 Frame received. TrackId: 1, Size: 1642, Flags 3899268981
 Frame received. TrackId: 1, Size: 1487, Flags 3899268981
 Frame received. TrackId: 1, Size: 1739, Flags 3899268981
 Frame received. TrackId: 1, Size: 1472, Flags 3899268981
 Frame received. TrackId: 1, Size: 1488, Flags 3899268981
 Frame received. TrackId: 1, Size: 1183, Flags 3899268981
 Frame received. TrackId: 1, Size: 1265, Flags 3899268981
 Frame received. TrackId: 1, Size: 1066, Flags 3899268981
 Frame received. TrackId: 1, Size: 1273, Flags 3899268981
 Frame received. TrackId: 1, Size: 1466, Flags 3899268981
 Frame received. TrackId: 1, Size: 1095, Flags 3899268981
 Frame received. TrackId: 1, Size: 1068, Flags 3899268981
 Frame received. TrackId: 1, Size: 1061, Flags 3899268981
 Frame received. TrackId: 1, Size: 951, Flags 3899268981
 Frame received. TrackId: 1, Size: 1088, Flags 3899268981
 Frame received. TrackId: 1, Size: 1187, Flags 3899268981
 Frame received. TrackId: 1, Size: 1204, Flags 3899268981
 Frame received. TrackId: 1, Size: 604, Flags 3899268981
 Frame received. TrackId: 1, Size: 1147, Flags 3899268981
 Frame received. TrackId: 1, Size: 1356, Flags 3899268981
 Frame received. TrackId: 1, Size: 1204, Flags 3899268981
 Frame received. TrackId: 1, Size: 1250, Flags 3899268981
 Frame received. TrackId: 1, Size: 1159, Flags 3899268981
 Frame received. TrackId: 1, Size: 1244, Flags 3899268981
 Frame received. TrackId: 1, Size: 1224, Flags 3899268981
 Frame received. TrackId: 1, Size: 1156, Flags 3899268981
 Frame received. TrackId: 1, Size: 1184, Flags 3899268981
 Frame received. TrackId: 1, Size: 1160, Flags 3899268981
 Frame received. TrackId: 1, Size: 1339, Flags 3899268981
 Frame received. TrackId: 1, Size: 1720, Flags 3899268981
 Frame received. TrackId: 1, Size: 1176, Flags 3899268981
 Frame received. TrackId: 1, Size: 1195, Flags 3899268981
 Frame received. TrackId: 1, Size: 1268, Flags 3899268981
 Frame received. TrackId: 1, Size: 1342, Flags 3899268981
 Frame received. TrackId: 1, Size: 1283, Flags 3899268981
 Frame received. TrackId: 1, Size: 1369, Flags 3899268981
 Frame received. TrackId: 1, Size: 1386, Flags 3899268981
 Frame received. TrackId: 1, Size: 1236, Flags 3899268981
 Frame received. TrackId: 1, Size: 1247, Flags 3899268981
 Frame received. TrackId: 1, Size: 1174, Flags 3899268981
 Frame received. TrackId: 1, Size: 1308, Flags 3899268981
 Frame received. TrackId: 1, Size: 1133, Flags 3899268981
 Frame received. TrackId: 1, Size: 1048, Flags 3899268981
 Frame received. TrackId: 1, Size: 1093, Flags 3899268981
 Frame received. TrackId: 1, Size: 910, Flags 3899268981
 Frame received. TrackId: 1, Size: 975, Flags 3899268981
 Frame received. TrackId: 1, Size: 1170, Flags 3899268981
 Frame received. TrackId: 1, Size: 1494, Flags 3899268981
 Frame received. TrackId: 1, Size: 1045, Flags 3899268981
 Frame received. TrackId: 1, Size: 1021, Flags 3899268981
 Frame received. TrackId: 1, Size: 1215, Flags 3899268981
 Frame received. TrackId: 1, Size: 1025, Flags 3899268981
 Frame received. TrackId: 1, Size: 951, Flags 3899268981
 Frame received. TrackId: 1, Size: 1022, Flags 3899268981
 Frame received. TrackId: 1, Size: 1139, Flags 3899268981
 Frame received. TrackId: 1, Size: 1325, Flags 3899268981
 Frame received. TrackId: 1, Size: 1084, Flags 3899268981
 Frame received. TrackId: 1, Size: 1018, Flags 3899268981
 Frame received. TrackId: 1, Size: 1219, Flags 3899268981
 Frame received. TrackId: 1, Size: 1088, Flags 3899268981
 Frame received. TrackId: 1, Size: 1193, Flags 3899268981
 Frame received. TrackId: 1, Size: 786, Flags 3899268981
 Frame received. TrackId: 1, Size: 1095, Flags 3899268981
 Frame received. TrackId: 1, Size: 1194, Flags 3899268981
 Frame received. TrackId: 1, Size: 1137, Flags 3899268981
 Frame received. TrackId: 1, Size: 1117, Flags 3899268981
 Frame received. TrackId: 1, Size: 1171, Flags 3899268981
 Frame received. TrackId: 1, Size: 1123, Flags 3899268981
 Frame received. TrackId: 1, Size: 1150, Flags 3899268981
 Frame received. TrackId: 1, Size: 995, Flags 3899268981
 Frame received. TrackId: 1, Size: 1694, Flags 3899268981
 Frame received. TrackId: 1, Size: 1056, Flags 3899268981
 Frame received. TrackId: 1, Size: 1054, Flags 3899268981
 Frame received. TrackId: 1, Size: 1060, Flags 3899268981
 Frame received. TrackId: 1, Size: 1023, Flags 3899268981
 Frame received. TrackId: 1, Size: 1092, Flags 3899268981
 Frame received. TrackId: 1, Size: 1064, Flags 3899268981
 Frame received. TrackId: 1, Size: 982, Flags 3899268981
 Frame received. TrackId: 1, Size: 1260, Flags 3899268981
 Frame received. TrackId: 1, Size: 1115, Flags 3899268981
 Frame received. TrackId: 1, Size: 1101, Flags 3899268981
 Frame received. TrackId: 1, Size: 1145, Flags 3899268981
 Frame received. TrackId: 1, Size: 1192, Flags 3899268981
 Frame received. TrackId: 1, Size: 1118, Flags 3899268981
 Frame received. TrackId: 1, Size: 1249, Flags 3899268981
 Frame received. TrackId: 1, Size: 964, Flags 3899268981
 Frame received. TrackId: 1, Size: 1260, Flags 3899268981
 Frame received. TrackId: 1, Size: 1505, Flags 3899268981
 Frame received. TrackId: 1, Size: 971, Flags 3899268981
 Frame received. TrackId: 1, Size: 1177, Flags 3899268981
 Frame received. TrackId: 1, Size: 1097, Flags 3899268981
 Frame received. TrackId: 1, Size: 1210, Flags 3899268981
 Frame received. TrackId: 1, Size: 850, Flags 3899268981
 Frame received. TrackId: 1, Size: 895, Flags 3899268981
 Frame received. TrackId: 1, Size: 1088, Flags 3899268981
 Frame received. TrackId: 1, Size: 1265, Flags 3899268981
 Frame received. TrackId: 1, Size: 1095, Flags 3899268981
 Frame received. TrackId: 1, Size: 1111, Flags 3899268981
 Frame received. TrackId: 1, Size: 1056, Flags 3899268981
 Frame received. TrackId: 1, Size: 1062, Flags 3899268981
 Frame received. TrackId: 1, Size: 1190, Flags 3899268981
 Frame received. TrackId: 1, Size: 1009, Flags 3899268981
 Frame received. TrackId: 1, Size: 1096, Flags 3899268981
 Frame received. TrackId: 1, Size: 1122, Flags 3899268981
`

**Comment by MushMal** [comment]
Unfortunately, this is not implemented: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/PeerConnection.c#L328

This is not a trivial task as the underlying stream is an elementary stream which is encoder specific. The flags need to be filled based on the integral understanding of the frames.

In your case, you could parse out the elementary stream and get the information. For example, if your underlying stream is in Annex-B format, you will need to skip the Annex-B start code and look into the NALu type.

Unfortunately, I don't have an ETA for the full solution.

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/855

Resolving this in favor of the feature request
