### ISSUE TITLE
[FEATURE] Transceiver onFrame callback frame flags should be set

### ISSUE THREAD

**Issue by MushMal** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#855]
**Is your feature request related to a problem? Please describe.**
Currently, the onFrame doesn't set the frame flags. 

**Describe the solution you'd like**
Frame flags set based on the elementary stream specific parsing. For example, for H264 Annex-B, we need to look into the NALu type byte following the Annex-B start code. This is assuming a non-multi-packet frame.

**Describe alternatives you've considered**
None that doesn't break the standards. If we define our own elementary stream - i.e. our own transceiver type then we can handle the frame flags easier.

**Additional context**

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.
