### ISSUE TITLE
[QUESTION] Transcription on the audio packets received through kinesis webrtc

### ISSUE THREAD

**Issue by suraj-vantigodi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#857]
Hi Team,

In my end application, I want to transcribe the audio using amazon transcribe service. Currently on streaming data transcribe supports only PCM encoding and webrtc supports only Opus encoding. 

So Should there be an intermediate layer where I convert the OPUS fragments into a mp3 or a wav file and send it to transcribe?
How can I do this?

In the **kvsWebrtcClientViewer**, I am getting the audio bytes but when I write them into opus files and try to decode, I get errors. I tried to decode these opus file using opusdec provided by [https://opus-codec.org/docs/opus-tools/opusdec.html](url)

`WARNING: Hole in data (4 bytes) found at approximate offset 160 bytes. Corrupted Ogg.
WARNING: Hole in data (156 bytes) found at approximate offset 160 bytes. Corrupted Ogg.
ERROR: No Ogg data found in file "sample-000.opus".
Input probably not Ogg.`

The audio bytes are written to pus files in the **sampleFrameHandler** method of Common.c file

`sprintf(fname_str, "../outputaudio/keyframe%d.opus", keyframe_counter);

    retStatus = writeFile(fname_str,FALSE,FALSE,pFrame->frameData,(UINT64)pFrame->size);`

Any help would be appreciated.

**Comment by MushMal** [comment]
While I am not familiar with the opusdec tool, try to use `retStatus = writeFile(fileName, TRUE, FALSE, data, size);` in order to produce a binary file.

**Comment by suraj-vantigodi** [comment]
@MushMal Can you tell me how the sample opus frames were generated?
These are the samples in **"./samples/opusSampleFrames/"** folder of the sdk.

**Comment by MushMal** [comment]
Hmm, that’s a good question. I am not sure I know actually. You could use some sort of audio source and use an opus decoder and a file sink to dump out the files using GStreamer. There must be some examples in the GStreamer forums

**Comment by disa6302** [comment]
@suraj-vantigodi , 

You can look into [this](https://gstreamer.freedesktop.org/documentation/opus/opusenc.html?gi-language=c) and see how you can modify the pipeline for the use case. Closing this issue. Feel free to reach out if you have any questions.

**Comment by suraj-vantigodi** [comment]
@disa6302 @MushMal  
I have an output file from aws transcribe which is in opus ogg format. I want to stream this audio back to the master from the viewer. what would be the ideal way to do that? I tried streaming the audio through the viewer but in the media player in the kvs console, I cant hear the audio but can only see the video.
What am I missing?
