### ISSUE TITLE
get env var AWS_SESSION_TOKEN

### ISSUE THREAD

**Issue by pai-da-xin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#863]
Hello,Dear experts,
I see in the code that the environment variable AWS_SESSION_TOKEN is used,How to set environment variable AWS_SESSION_TOKEN.
Thank you in advance.

**Comment by MushMal** [comment]
Not sure what you mean by this. Are you looking for an advise on how to set an env variable for your given platform? Something like

`export ENV_VAR=VALUE`

Resolving for now. Please reopen with detailed question/ask which is specific to KVS.
