### ISSUE TITLE
set the value of the env var AWS_SESSION_TOKEN

### ISSUE THREAD

**Issue by pai-da-xin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#864]
Hi,Dear experts,
I see in the [https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L605](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L605) that I get the environment variable SESSION_TOKEN_ENV_VAR, SESSION_TOKEN_ENV_VAR is equal to AWS_SESSION_TOKEN.
I want to know where the value of the environment variable AWS_SESSION_TOKEN is obtained. For example AWS_ ACCESS_ KEY_ ID and AWS_SECRET_ACCESS_KEY is available from the IAM console, Where does the value of the AWS_SESSION_TOKEN need to be obtained.

Thank you in advance.

**Comment by MushMal** [comment]
There are various ways. Try to read up on the auth from the AWS documentation following this link https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

I am resolving this as it’s not KVS specific issue
