### ISSUE TITLE
[FEATURE] Replace the shutdown sequence controlled by atomics interlocking with a semaphore

### ISSUE THREAD

**Issue by MushMal** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#873]
**Is your feature request related to a problem? Please describe.**
Currently, the codebase is handling intricate synchronization on a teardown path using atomics. We really need to use semaphores to streamline the code and avoid edge cases.

**Describe the solution you'd like**
PR #871 contains more details

**Describe alternatives you've considered**
This is the alternative to the existing code.

**Additional context**

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.
