### ISSUE TITLE
[BUG] CMake Error for not recognizing FILTER sub-command in SDK 1.3.0

### ISSUE THREAD

**Issue by ajjiang48** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#875]
Hi, Sir, 
I failed In the SDK v1.3.0 CMake with the below error, the Makefile is not generated and couldn't execute the following
make command.
(I do the ARM cross compile and my full CMake command with parameters is:
cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-unknown-linux-uclibcgnueabi )

CMake error:
////
CMake Error at CMakeLists.txt:233 (list):
  list does not recognize sub-command FILTER

I checked the line 233 in the CMakeList.txt file; found below lines and those scripts are not appeared in v1.2.0 SDK.
////
if (USE_OPENSSL)
  list(FILTER WEBRTC_CLIENT_SOURCE_FILES EXCLUDE REGEX ".*_mbedtls\\.c")
elseif (USE_MBEDTLS)
  list(FILTER WEBRTC_CLIENT_SOURCE_FILES EXCLUDE REGEX ".*_openssl\\.c")
endif()

is there any definition for "FILTER" missing in the script file? and how to fix this CMake problem?? 

Thanks,
A.J.

**Comment by lherman-cs** [comment]
@ajjiang48 I'm sorry for the trouble. Our CMakeLists seems to use a wrong minimum version requirement. FILTER subcommand was introduced in CMake 3.6.3. Could you please upgrade your CMake to at least 3.6.3? Thanks!

**Comment by disa6302** [comment]
Closing this because the PR is merged
