### ISSUE TITLE
Does PeerConnection.c handle trickle ICE properly?

### ISSUE THREAD

**Issue by yuma-m** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#889]
I use KVS WebRTC C SDK (Master) and Android SDK (Viewer).

The SDP offer from Android is below.

```text
v=0
o=- 3199963460847894932 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=msid-semantic: WMS KvsLocalMediaStream
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:TEwt
a=ice-pwd:idZJ7/7/BbQ4YI4mqiPST5cE
a=ice-options:trickle renomination
...
```

The SDP offer has the attribute `ice-options` and the value `trickle renomination`.

On the other hand, the C SDK handles `ice-options` in the lines below. It compares the value of `ice-options` with `“trickle”` (exact match, not forward match). As a result, `pKvsPeerConnection->canTrickleIce` is set to be `FALSE`.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/bdedb56788e794edf0e8aa526ed7a141502fedc4/src/source/PeerConnection/PeerConnection.c#L980-L982

Is this behavior correct?
Should `trickle renomination` be handled as `canTrickleIce = TRUE`?

**Comment by disa6302** [comment]
@yuma-m ,

You are probably right. It should not be an exact match. Though we do not support re-nomination, we should expect an offer with multiple attributes.

**Comment by disa6302** [comment]
Let me cut another ticket and tag it as a bug. 
Closing this issue. (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/890)

**Comment by yuma-m** [comment]
@disa6302 Thank you for ticketing the issue. I will follow that.
