### ISSUE TITLE
[BUG] Handle trickle ice attribute appropriately

### ISSUE THREAD

**Issue by disa6302** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#890]
**Describe the bug**
On receiving `ice-options` in the offer, we perform an exact match to `trickle` to enable the trickle ice. However, the `ice-options` can contain multiple attribute values and we should not perform an exact match but check if `trickle` value exists in the attribute value list.

**SDK version number**
Top of master

**To Reproduce**
1. Generate an offer with values: `ice-option`: `trickle renomination`

**Expected behavior**
Trickle gets enabled. But, trickle does not get enabled with current SDK

Created from #889

**Comment by disa6302** [comment]
@yuma-m , 

The change is in. Let me know if this fixes the issue for you. Closing this

**Comment by yuma-m** [comment]
Hi @disa6302 , thank you for fixing it quickly.
I confirmed `trickle renomination` is properly handled as `canTrickleIce = TRUE`.
