### ISSUE TITLE
timestamp with absolute Unix time (time_since_epoch 01/01/1970) will overflow timpstamp conversion in RTP.c

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#892]
Unix time is a very large number, and the time unit of 100ns inside of webrtc make the time number even larger.  Then in RTP.c when converting the 100ns timestamp unit into RTP timestamp, it overflows 
So, using absolute Unix time causes error
using relative time as timestamp is fine (time since boot)

**Comment by MushMal** [comment]
Can you give us exact info on where it overflows? 100ns is the default time unit measurement in the SDKs and it should not overflow, unless we for some reason add timestamps which we shouldn't/

**Comment by MushMal** [comment]
Removing BUG label - 100ns duration is by design

**Comment by zwei333** [comment]
Not questioning time unit of 100ns
Using unix time, currently reading is 1603475356403, unit is second
Converting to unit of 100ns, it is 16034753564030000000.
In https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/bdedb56788e794edf0e8aa526ed7a141502fedc4/src/source/PeerConnection/Rtp.c#L233
to convert time stamp into RTP's 90000 Hz, the above timestamp is multiplied by 90000 first.
The result overflows 64 bit unsigned int

**Comment by MushMal** [comment]
BUG: we should not be multiplying the value by clock rate.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/bdedb56788e794edf0e8aa526ed7a141502fedc4/src/source/PeerConnection/Rtp.h#L80

Needs to be properly fixed. Let me cut a new issue and resolve this one.

Issue #894 https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/894
