### ISSUE TITLE
Inconsistency in live video streaming

### ISSUE THREAD

**Issue by vickyskarthik** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#895]
I followed a AWS blog for controlling raspberrypi robot using AWS IOT and AWS Kinesis video stream - signaling channel to stream real time video from a Raspberrypi camera. The video is played in a website hosted through S3 bucket.  But I experience inconsistency in the video stream.  When the same webpage is browsed through different devices, the video is visible only in few systems while a black screen is most.  When I inspect the webpage it shows that the it reveals the packets from kinesis.

Kindly help me on how to solve this issue.
I have attached the images of both the screens one with live video and other with black screen.  

![IMG-20201021-WA0002](https://user-images.githubusercontent.com/46419602/97113346-c0b57d80-170f-11eb-80bb-839c90629551.jpg)
![IMG-20201021-WA0005](https://user-images.githubusercontent.com/46419602/97113348-c743f500-170f-11eb-838e-1ab08da42793.jpg)

**Comment by vickyskarthik** [comment]
@disa6302, I check again, I am able to see the video feed but my peer browsing in another system is unable to view the video for the same URL.  Herewith I have attached the device logs for your perusal.
[logs.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5445839/logs.txt)

**Comment by MushMal** [comment]
The logs don't capture anything useful. Try to capture VERBOSE level logs which could give you some idea if there are issues with your device streaming out.

**Comment by vickyskarthik** [comment]
@MushMal  @disa6302  I have attached the VERBOSe level log files for your reference. 
[logs.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5450584/logs.txt)

**Comment by MushMal** [comment]
@vickyskarthik again, your logs contain absolutely no useful information. At this stage, I would ask you to do some debugging of your own. Try to narrow the issue down. We won't be able to support you on a particular application/sample that's not part of the SDK itself. Try to reproduce something on the SDK itself so we can narrow things down. It's been multiple days and many back and forths with no traction.
