### ISSUE TITLE
[QUESTION] Windows 7 Chrome Decoding Problem

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#896]
First question, is KVS planning to support chrome for windows 7? Chrome isn't going to end the support for windows 7 either.
https://cloud.google.com/blog/products/chrome-enterprise/how-chrome-is-helping-enterprises-still-using-windows-7

Second question, the chrome  86.0.4240.111 (Official Build) (64-bit) with default webpage https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html and kvsWebRTCClientMaster seem to unable to decode on windows 7. Can someone spend some time verifying?

**Comment by suggestedfixes** [comment]
At first glance, chrome seems to settle down on a profile that the master does not support 
H264 (114, level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640015)
--



```

timestamp | 10/27/2020, 7:11:12 AM
-- | --
ssrc | 1247994073
isRemote | false
mediaType | video
kind | video
trackId | RTCMediaStreamTrack_receiver_12
transportId | RTCTransport_0_1
codecId | RTCCodec_1_Inbound_114
[codec] | H264 (114, level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640015)
firCount | 0
pliCount | 20
nackCount | 0
packetsReceived | 16336
[packetsReceived/s] | 126.37914007175515
bytesReceived | 3851847
[bytesReceived_in_bits/s] | 240938.82151965663
headerBytesReceived | 196032
[headerBytesReceived_in_bits/s] | 12132.397446888494
packetsLost | 0
lastPacketReceivedTimestamp | 2.53033e+06
framesReceived | 3056
framesPerSecond | 25
framesDecoded | 0
[framesDecoded/s] | 0
keyFramesDecoded | 13
framesDropped | 0
totalDecodeTime | 0
[totalDecodeTime/framesDecoded_in_ms] | 0
totalInterFrameDelay | 0
[totalInterFrameDelay/framesDecoded_in_ms] | 0
totalSquaredInterFrameDelay | 0
[interFrameDelayStDev_in_ms] | 0
decoderImplementation | NullVideoDecoder


```

**Comment by MushMal** [comment]
There are very few places in the code that we make platform specific adaptation - for example, how to handle sockets. Other than that there is no functional difference. The question whether Chrome WebRTC will support Windows 7 should be directed to the Chrome's implementation of the WebRTC.

The seconds question is more actionable. Could you please debug into the issue and try to extract what exactly fails with the decoding? Is this an h264 unsupported profile issue? 

We won't be able to reproduce every platform/software version issue so we would rely on the open-source community members to do some diagnostics and debugging and boil it down to the SDK behavior if there is an issue with the SDK specifically - in this case C WebRtc

**Comment by suggestedfixes** [comment]
It should be related to how SDPs were negotiated. If I randomly try adding transceivers of different directions on the browser side, for example 'sendrecv'. Eventually it will work.

**Comment by suggestedfixes** [comment]
But I don't understand SDP enough to diagnose it, so allow me to understand a bit of time of understanding SDP first.
The fast way to solve it is try to get someone on windows 7 to replicate it.

**Comment by suggestedfixes** [comment]
I think the first question is whether the SDK should support SDP generated under chrome with win7 and win7 version of the decoder. I think from the answer to the second question, the answer is as long as we provide SDPs and debug logs, we might be able to include accommodate more edge cases.

**Comment by suggestedfixes** [comment]
I think this patch fixes it:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/902
