### ISSUE TITLE
[QUESTION] Does KVS WebRTC support AAC audio codec?

### ISSUE THREAD

**Issue by Teresa7755** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#901]
Hi Team,
      Does KVS WebRTC support AAC audio codec? I couldn't find it in the source code.  If not, would you please add this feature?  It's important for us. We'd like to send the AAC audio frames from the Master so that Viewers get them from webrtc and save as MP4 file. 
Use case: 
Device as Master(sends video,audio and receives audio) and Android/iOS as Viewer(sends audio and receives video, audio)

Thanks.

**Comment by MushMal** [comment]
Sorry, this is the list of codecs we currently support: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/master/src/source/Rtp/Codecs

We welcome any contributions though.
