### ISSUE TITLE
[BUG] SDP setPayloadTypesForOffer may select an incompatible H264 protocol from the SDP offer

### ISSUE THREAD

**Issue by andyhoffy** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#902]
**Logging**

Sample offer/answer from testing that reproduces the issue:

[offer.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5459733/offer.log)
[answer.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5459737/answer.log)

**Describe the bug**

It appears that the SDP answer formulation process does not discriminate between different fmtp options when selecting an H264 fmtp value to put into the answer.

Specifically, the sole supported H264 protocol in the SDK is:
`RTC_CODEC_H264_PROFILE_42E01F_LEVEL_ASYMMETRY_ALLOWED_PACKETIZATION_MODE`

In Google Chrome, the correct advertised FMTP value to select looks something like:
```a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f```

In firefox, the default packetization-mode value is assumed (0) so the offer looks like:
```a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1```

In my testing, I found that the SDK is instead selecting whatever H264 fmtp line is last in the offer, which at times is incompatible with the stream being sent (e.g. packetization-mode=1, for example) which results in a breakdown of streaming.

Without a fix in place, I found that Google Chrome on Mac, Firefox on Linux and Mac, and Chromium on Linux would not process streams correctly, and communication would break down shortly after streaming begins, resulting often in a NACK shower.

With a fix in place, streaming seems to occur normally/as expected.

**SDK version number**

The issue was initially diagnosed and patched off of this commit point: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/4e21b6e7e3029db94d3e260352ef1f07c261c50a

**Open source building**

N/A

**To Reproduce**
1. Configure a master that is offering an H264 video stream (this may work using the gstreamer sample, but we used our own custom library.) Enable logging of the SDP offer/answer.
2. Attempt to connect to the master via a client that advertises a multitude of H264 options (e.g. Chrome on Mac).
3. Observe the SDP offer/answer. Note that the answer includes an fmtp value selection that matches the last H264 option in the offer, instead of one that accurately matches the supported `RTC_CODEC_H264_PROFILE_42E01F_LEVEL_ASYMMETRY_ALLOWED_PACKETIZATION_MODE` configuration.

Other side effects that may be obsevable: If/when the wrong selection is made (esp if packetization-mode=1) note that the stream may break down after even minor amounts of loss/corruption, and does not recover.

**Expected behavior**

The SDP answer should select an fmtp option that is know to be compatible with the `RTC_CODEC_H264_PROFILE_42E01F_LEVEL_ASYMMETRY_ALLOWED_PACKETIZATION_MODE` configuration, most notably with the characteristics:
`level-asymmetry-allowed=1`, `packetization-mode=0` (or missing, which implies 0), and `profile-level-id=42e01f`

Relevant spec stating that packetization-mode as optional (implied value 0):
https://tools.ietf.org/html/rfc6184#section-6.2

**Screenshots**

N/A, please see log section for samples.

**Desktop (please complete the following information):**
 - OS: Mac, Linux
 - Browser: Chrome, Chromium, Firefox
 - Version: (Various)

**Smartphone (please complete the following information):**
(UNTESTED)

**Additional context**

This may be one simple way to fix the issue, although this exact implementation strategy may not be ideal:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/compare/master...canvasco:fix/sdp_h264_mismatch

**Comment by andyhoffy** [comment]
FYI, not sure if this is of interest, but I added some parameterized tests on my branch that teased out a few additional cases to cover, if they would be of value. Captured some SDP offers from a few different browsers/platforms to use as test input.

**Comment by docee** [comment]
@andyhoffy There is no fmtp with packetization-mode=0 on Safari. So I think the judgment on packetization-mode can be eliminated.

```
"v=0
o=- 4476463512088233894 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=msid-semantic: WMS eac9584d-fa2c-4a0e-9058-679cc1f26024
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 125 104
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:/ewK
a=ice-pwd:aKGjExI+6jxloHUS/YAiBJ8l
a=ice-options:trickle
a=fingerprint:sha-256 4C:BF:6E:12:46:8E:78:5C:95:72:8A:DA:7D:43:37:8B:B1:0A:18:BB:14:2E:8C:91:DC:96:F7:F0:4A:3D:D9:96
a=setup:actpass
a=mid:0
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:eac9584d-fa2c-4a0e-9058-679cc1f26024 d80cd5e8-77bc-412b-b28b-1a49cb206a8d
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 red/90000
a=rtpmap:125 rtx/90000
a=fmtp:125 apt=127
a=rtpmap:104 ulpfec/90000
a=ssrc-group:FID 356870772 2134359896
a=ssrc:356870772 cname:Q0M8Ph7hjtImqJCS
a=ssrc:356870772 msid:eac9584d-fa2c-4a0e-9058-679cc1f26024 d80cd5e8-77bc-412b-b28b-1a49cb206a8d
a=ssrc:356870772 mslabel:eac9584d-fa2c-4a0e-9058-679cc1f26024
a=ssrc:356870772 label:d80cd5e8-77bc-412b-b28b-1a49cb206a8d
a=ssrc:2134359896 cname:Q0M8Ph7hjtImqJCS
a=ssrc:2134359896 msid:eac9584d-fa2c-4a0e-9058-679cc1f26024 d80cd5e8-77bc-412b-b28b-1a49cb206a8d
a=ssrc:2134359896 mslabel:eac9584d-fa2c-4a0e-9058-679cc1f26024
a=ssrc:2134359896 label:d80cd5e8-77bc-412b-b28b-1a49cb206a8d
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 102 0 8 105 13 110 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:/ewK
a=ice-pwd:aKGjExI+6jxloHUS/YAiBJ8l
a=ice-options:trickle
a=fingerprint:sha-256 4C:BF:6E:12:46:8E:78:5C:95:72:8A:DA:7D:43:37:8B:B1:0A:18:BB:14:2E:8C:91:DC:96:F7:F0:4A:3D:D9:96
a=setup:actpass
a=mid:1
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:eac9584d-fa2c-4a0e-9058-679cc1f26024 a0566073-3a10-493c-be50-e7a419130fe3
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:3171718753 cname:Q0M8Ph7hjtImqJCS
a=ssrc:3171718753 msid:eac9584d-fa2c-4a0e-9058-679cc1f26024 a0566073-3a10-493c-be50-e7a419130fe3
a=ssrc:3171718753 mslabel:eac9584d-fa2c-4a0e-9058-679cc1f26024
a=ssrc:3171718753 label:a0566073-3a10-493c-be50-e7a419130fe3
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:/ewK
a=ice-pwd:aKGjExI+6jxloHUS/YAiBJ8l
a=ice-options:trickle
a=fingerprint:sha-256 4C:BF:6E:12:46:8E:78:5C:95:72:8A:DA:7D:43:37:8B:B1:0A:18:BB:14:2E:8C:91:DC:96:F7:F0:4A:3D:D9:96
a=setup:actpass
a=mid:2
a=sctp-port:5000
a=max-message-size:262144

```

**Comment by andyhoffy** [comment]
@docee thanks for the note! I'm actually concerned that the library might not support packetization-mode=1, need to figure out if this is an issue for safari (and other browser) compatibility. 

As it stands, I'm concerned that selecting packetization-mode=1 is the breaking issue, but I haven't traced the nack-storm problems I experienced with mis-selection of protocol back to the mis-selection packetization-mode or the mis-selection of the profile-level-id. 

There appear to be conflicting requirements in competing proposed RFCs:

RFC 6184 (proposed) specifies that all implementations MUST support packetization-mode=0 https://tools.ietf.org/html/rfc6184#section-6.2 

However, that's simultaneously inconsistent with what the mozilla docs and RFC 7742 (proposed) suggest about packetization-mode: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/WebRTC_codecs and RFC 7742 https://tools.ietf.org/html/rfc7742#section-6.2

I may need to dig into the implementation a bit more and see whether or not mode 0, mode 1, or both are actually supported!

**Comment by andyhoffy** [comment]
Intersetingly, the code does seem to default to advertising packetization-mode=1 (specified in DEFAULT_H264_FMTP in SessionDescription.h)... 

It looks like support for two different payload types (24, 28) are required for mode 1 (over mode 0), so perhaps if RtpH264Payloader supports these types (if that's the right file) then it's safe (preferable?) to select packetization-mode=1 when available...

**Comment by andyhoffy** [comment]
Ok, I see good indications of FU-A and STAP-A packet types, so I agree, it probably makes sense to drop the packetization-mode check, and possibly change it to prefer packetization-mode=1 or default/none as available.

In fact, it looks like the payloader defaults to either sending single packets or sending FU-A encapsulated packets, depending on nalu length. So it seems that it MUST select packetization-mode=1 if there is a chance that H264 frames will exceed the MTU size.

**Comment by andyhoffy** [comment]
Ok, I haven't run my own smoke tests yet to confirm that packetization-mode=1 works, but I pushed a change that checks for packetization-mode=1 (instead of zero or missing) and included a safari/mac sample in the tests I added (that now passes.) :-)

**Comment by lherman-cs** [comment]
This issue has been fixed in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/966
