### ISSUE TITLE
[FEATURE] add API to set cache file apth

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#908]
We are using File Cache feature. (code implementation in src/source/Signaling/FileCache.c)
However, there is no API to set DEFAULT_CACHE_FILE_PATH.  It is hard coded to be the same directory as webrtc binary.
In our system, app binary is in read only folder so the cache file "./.SignalingCache_v0" doesn't work.

Please provide API to override the default cache file path.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zwei333** [comment]
Yes, being able to specify the path will be good enough.

**Comment by disa6302** [comment]
Change merged. Closing.
