### ISSUE TITLE
[FEATURE] Add continuous benchmark to CI

### ISSUE THREAD

**Issue by lherman-cs** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#909]
**Is your feature request related to a problem? Please describe.**
As of now, there's no performance feedback loop in our SDK. We should add a continuous benchmark to our CI so that we can monitor any performance regression within our SDK for every change.

**Describe the solution you'd like**
In https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/903, we use Google benchmark to run a series of benchmarks. I think we can run the benchmark in every CI by comparing the result with master.

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.
