### ISSUE TITLE
[BUG] video latency grows as streaming lasts long

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#910]
The stability of webrtc SDK is pretty good, so that streaming can run more than 24 hours uninterrupted.
However, the long streaming disclose a new problem:
When streaming first starts, the latency (from an object moves to the object moves in streamed video) is quite small, less than 0.5second.
But after 24 hours streaming, the latency grows to as large as 8 seconds.
Don't know why it happens.  Can you try to run SDK for extended time and see if the problem can be reproduced?

**Logging**
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

**Describe the bug**

**SDK version number**
Include the SDK version you are running. If it is a specific commit on master branch, include that

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by suggestedfixes** [comment]
If you are using GStreamer, there are drop on latency options on some of the elements (you might end up observing some video artifacts). Or you can dig into how the jitterbuffer works for this SDK.

**Comment by suggestedfixes** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/577e149ea846fef652237e3c7d3371dea50bd395/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L594

**Comment by MushMal** [comment]
@suggestedfixes Thanks for the suggestions. I don't have anything else to add to this as it's network/media pipeline configuration related issue.

**Comment by MushMal** [comment]
Any further progress on this issue? There can be a certain latency that's absorbed by the jitter buffer duration. Can you debug your network bandwidth? Can you dump out the metrics/stats periodically to see if this is network/packet loss issue?

Can you give more information on what the peers are? Are you using Chrome? Which version?

You might want to try different network topologies to eliminate the network in the first place.

**Comment by disa6302** [comment]
@zwei333 , 

Closing because of no response. Feel free to reopen/open a new issue if you have questions.
