### ISSUE TITLE
[QUESTION] Is there a way to filter out ipv6 local candidate or just 0000:0000:0000:0000:0000:0000:0000:0000?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#911]
Occasionally, getting this error, is it because of spuirous ipv6? or some other reaon?
```
Cannot find candidate pair with local candidate 0000:0000:0000:0000:0000:0000:0000:0000 and remote candidate 3.134.76.195. Dropping STUN binding success response
```

**Comment by MushMal** [comment]
Can you please provide verbose logs? I am not sure where does this come from. You can filter out entire network interface or disable IPv6 processing in the first place.

**Comment by suggestedfixes** [comment]
This is hard to reproduce. I'm already filtering out non-relevant interfaces. I understand there are ways to disable ipv6 at the system level. Is there an easy way to disable ipv6 from the SDK side?

**Comment by MushMal** [comment]
In our Travis.ci script we disable IPv6 using the following:

- sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

Not sure if we have a central location for disabling ipv6 in the SDK.

**Comment by lherman-cs** [comment]
@suggestedfixes we currently don't have a way to filter out ipv6. To help us debugging this issue, what's your OS? We have a separate code path for Windows vs unix based systems: 

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/8a64e7feeb0d42f2917b3660819424bcd41534fe/src/source/Ice/Network.c#L28-L124

**Comment by lherman-cs** [comment]
@suggestedfixes I can't reproduce this locally as my network interfaces don't give `0000:0000:0000:0000:0000:0000:0000:0000` local IP address. But, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/942 should filter out this IP address.
