### ISSUE TITLE
Unstable video connection

### ISSUE THREAD

**Issue by farmeng** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#912]
Videos can occasionally be viewed, but often it does not show up.

We have a backend "master" that feed video frames to kinesis and a mobile frontend that viewer videos. We use the video only mode. 

We are testing using the [kvs webrtc test page](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html). Our master resembles the sample kvsWebrtcClientMaster, and it works with the test page's viewer consistently. Our mobile frontend viewer works with the test page's master consistently. But our master does not work with our mobile frontend. Retrying with kvsWebrtcClientMaster with our iOS app shows the same problem.

Often, the connection was successful when we bring up the master for the first time during a day. The video lasted for a short time and froze. After that, we cannot get video anymore, neither restarting the master nor the mobile app helps. 

** Logging ** 
Oct 29 20:31:48 back launch[818]: [webcast-1] [WARN] [webcast]: Add video frame...
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:48 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] Videoframe (presentationTs: 116666655) popped from queue. size:  104854
Oct 29 20:31:49 back launch[818]: [webcast-1] [WARN] [webcast]: Add video frame...
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   deserializeStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   handleStunPacket(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   incomingDataHandler(): operation returned status code: 0x5700000e
Oct 29 20:31:49 back launch[818]: [webcast-1] 2020-10-29 20:31:49 ERROR   executeFailedIceAgentState(): IceAgent failed with 0x5a00000d

** Any design considerations/constraints **
Note our "master" sits on a readonly filesystem. Not sure if that's a concern.

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by disa6302** [comment]
@farmeng , 

The error indicates HMAC validation in the received STUN packet fails, which is strange.

You mentioned your master works with test page viewer and mobile frontend works with test page master. Can you explain how your mobile viewer is designed?

**Comment by farmeng** [comment]
Thank you for the tips! we'll get back to your question about the frontend. 

Not sure what is "stick master" and how to run it in the same setting as the viewer? Our master runs on ubuntu and the viewer runs in on iOS. If you have any suggestions on how we can reproduce the error on the same environment, please let me know. Thanks again!

**Comment by disa6302** [comment]
Sorry. My bad. I mean stock master sample. Run the master and the viewer samples without any changes, in the same network settings and your set up and see if it works fine.

**Comment by farmeng** [comment]
Thanks. We'll try. Do you know if the kinesis service, especially the
authentication/validation part, requires any network ports to open? Want to
make sure we are not blocking any messages.

**Comment by sb28103** [comment]
The frontend is based off the iOS SDK example. Using AWSStaticCredentialsProvider for testing.

**Comment by MushMal** [comment]
There is not much to go with in the logs. Looks more like an on-the-network corruption of some sort due to mismatch of the HMACs in the SDP.

Does this happen continuously? Can you narrow things down? Try to capture the packets (though, they will be encrypted and hard to understand). Try different network setups?

As is, this is not actionable due to missing repro and the logs are not useful.

**Comment by MushMal** [comment]
Closing as stale. Please don't hesitate to cut a new issue with detailed description and what debugging steps you might have taken. In this case, it seems like a network issue. If this is iOS SDK based issue then please cut an issue in that repository. NOTE: iOS SDK WebRTC implementation itself is not ours. We provide just the signaling for iOS.
