### ISSUE TITLE
[QUESTION] How to stream the output from transcribe, opus ogg file back to the master?

### ISSUE THREAD

**Issue by suraj-vantigodi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#917]
I have an output file from aws transcribe which is in opus ogg format. I want to stream this audio back to the master from the viewer. what would be the ideal way to do that? I tried streaming the audio through the viewer but in the media player in the kvs console, I cant hear the audio but can only see the video.
What am I missing?

**Comment by MushMal** [comment]
@suraj-vantigodi Are you are asking for a general solution architecture help or a concrete problem when your audio stream is not being received/played back by the console?

For the first, you might need to read up on the encoders and formats and webrtc in general and if you need more help you can reach out to your AWS technical account management team to get solution architecture help.

For the second, you need to be very specific. Try to narrow down your issue to the actual audio format. There are few formats that are supported - all listed in the readme. You need to follow the sample and replace the transceiver and stream your audio frames. Ensure that the codec you are streaming is compatible with the browsers webrtc implementation.

Please resolve this issue and cut another one that has enough low-level details and verbose logs for help.
