### ISSUE TITLE
[FEATURE] Recreate present project as a Gstreamer plugin

### ISSUE THREAD

**Issue by alvarozornoza** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#923]
**Is your feature request related to a problem? Please describe.**
Hello AWS team, when trying to use current code it is quite tedious to integrate with other processes.

**Describe the solution you'd like**
Release the present project as a Gstreamer plugin, the same way you did with https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp and kvssink-

**Describe alternatives you've considered**
I know that there exist gstreamer plugins like IpcPipeline which would allow user to interconnect several process. However, this is not possible in embedded platforms with low CPU capabilities like Nvidia Jetson or Raspberry Pi

**Additional context**
I am willing to help in case I can

**Comment by suggestedfixes** [comment]
I'm also a fellow user and happened to have done a bit of research in the past.
This might help a bit: https://gstreamer.freedesktop.org/documentation/webrtc/index.html?gi-language=c

**Comment by MushMal** [comment]
We are contemplating on packaging a master and/or viewer solution in a GStreamer package including signaling and potentially persistence. We are still investigating and we don't have an ETA yet.

Meanwhile, can you please provide some info as to what makes the integration hard with the existing SDK? Perhaps we can improve on it?

GStreamer elements provide a great power at the cost of manageability and flexibility. We could target a particular application/use case scenario whereas the SDK which acts as the low-layer can be integrated into a variety of different classes of applications on a different form-factors and platforms, some of which can not support GStreamer.

**Comment by alvarozornoza** [comment]
Thanks for your answers @suggestedfixes and @MushMal.

My usecase consists on performing several operations to a video and then both stream it and persist it using KVS (video streams and signaling)

We process the video first using Nvidia package called Deepstream (https://developer.nvidia.com/deepstream-sdk) (deeplearning inferences, and other stuff) which is indeed complex program itself with many dependencies and so on. I didn't try to merge both projects and adjust CMake dependencies but I guess it can be a nightmare.

In the case of kvssink (persistance), I just included it in the pipeline I have for deepstream, since it is a plugin itself, and it worked easily.

So persistance is working but for webrtc, let's say that I have two different process with two different Gstreamer pipelines which must be linked.

I thought about using ipcpipeline from gst-plugins-bad, but it implicates memory copies which are performed using CPU and it produces an overhead which is not admissible (embedded system with low CPU capabilities).

I know that many of this stuff might be completely out of your stuff, I just want to let you know that amazon-kinesis-video-streams-webrtc-sdk-c released as a gst plugin would be extremely helpful for the AWS robotics users community ;D

Thanks a lot!

**Comment by MushMal** [comment]
We hear you..

Could you please provide a little more info on your scenario as we are collecting feedback. I assume your device is continuously streaming to KVS for the persistence but once a viewer connects, it should also perform webrtc master functionality? How many viewers would you have in parallel at one time? What's the viewer average viewing duration? What's the density of the stream in kbps? More info you think could help us to categorize.

**Comment by alvarozornoza** [comment]
Our case of use is the autonomous mobile robots. We want our robots to record video sequences from the cameras (continuously). When an operator wants to tele-operate a robot, we want to use webrtc to offer low latency during the time the operator is tele-operating (on-demand). Don't know yet about bitstream/viewer duration, we are still testing and checking the technology and the limits of LTE networks.

**Comment by alvarozornoza** [comment]
Hello again @MushMal,

While kindly waiting for the feature I proposed, I am trying to integrate present SDK with others application (ROS and deepstream) similar to #859

My main program should be similar to kvsWebRTCClientMasterGstreamerSample.c so I will need Common.c and samples.h

This is my CMakeLists file now:

```
cmake_minimum_required(VERSION 3.5)
project(wb_video)

# Default to C++14
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
endif()

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic -O3 -march=native)
endif()

set(KINESIS_VIDEO_WEBRTC_CLIENT_SRC $ENV{HOME}/repo/aws/amazon-kinesis-video-streams-webrtc-sdk-c)
message(STATUS ${KINESIS_VIDEO_WEBRTC_CLIENT_SRC})

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)

# Gstreamer
find_package(PkgConfig)

pkg_check_modules(GST REQUIRED gstreamer-1.0>=1.4
        gstreamer-sdp-1.0>=1.4
        gstreamer-video-1.0>=1.4
        gstreamer-app-1.0>=1.4)
message(STATUS "Find Gstreamer include at ${GST_INCLUDE_DIRS}")
message(STATUS "Find Gstreamer libraries: ${GST_LIBRARIES}")

include_directories(
  include
  ${GST_INCLUDE_DIRS} 
  /opt/nvidia/deepstream/deepstream-5.0/sources/includes/
  /usr/local/include
  ${KINESIS_VIDEO_WEBRTC_CLIENT_SRC}/src/include
  ${KINESIS_VIDEO_WEBRTC_CLIENT_SRC}/open-source/include
)
ament_export_include_directories(include)

set(dependencies
  rclcpp
  std_msgs
)

link_directories(
  ${GST_LIBRARIES} 
  /opt/nvidia/deepstream/deepstream-5.0/lib
  ${KINESIS_VIDEO_WEBRTC_CLIENT_SRC}/open-source/lib
)


add_executable(wb_video src/Common.c src/wb_video_node.cc src/video.cc)
target_link_libraries(${PROJECT_NAME} ${GST_LIBRARIES} /usr/local/lib/libkvsWebrtcClient.so /usr/local/lib/libkvsWebrtcSignalingClient.so)
ament_target_dependencies(${PROJECT_NAME} ${dependencies})

install(TARGETS
  ${PROJECT_NAME}
  DESTINATION lib/${PROJECT_NAME}
)

install(DIRECTORY
  config
  launch
  DESTINATION share/${PROJECT_NAME}
)

ament_package()
```

Moreover this is my folder structure. Note present SDK is correctly installed in the indicated folder above and I run make install to have includes and binaries in /usr/local/

I am getting this error

```
CMakeFiles/wb_video.dir/src/Common.c.o: In function `lookForSslCert':
Common.c:(.text+0x228f): undefined reference to `traverseDirectory'
collect2: error: ld returned 1 exit status
CMakeFiles/wb_video.dir/build.make:181: recipe for target 'wb_video' failed
make[2]: *** [wb_video] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wb_video.dir/all' failed
make[1]: *** [CMakeFiles/wb_video.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

I guess I am failing when linking. In this [comment](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/859#issuecomment-706315681) @MushMal mentioned that, could please provide with instructions on how to link?

Best regards

**Comment by lherman-cs** [comment]
`traverseDirectory` is defined in our PIC layer, https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/Directory.c#L57. Please make sure that you link the binary with libkvspicState.a and libkvspicUtils.a

**Comment by MushMal** [comment]
@alvarozornoza could you please follow the CMake file system that we have in place. 

C++ SDK wraps the C SDK which wraps PIC. You will need to follow the CMake we have in place and build your own.

Please cut separate targeted issues for questions you might have. This issue is solely for a proposal of having the existing or a new GStreamer plugin integrating KVS C webrtc implementation.

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.

**Comment by sauravkumar-volt** [comment]
Hi,
when can we expect the GStreamer plugin for kvs webrtc.

**Comment by MushMal** [comment]
> Hi, when can we expect the GStreamer plugin for kvs webrtc.

Try this https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/gst/gst-kvs-plugin
