### ISSUE TITLE
Wondering compatibilities with official WebRTC

### ISSUE THREAD

**Issue by northteam** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#928]
Is webrtc part of this sdk compatible with official WebRTC (webrtc.org)?
I think only signaling process relies on Amazon Kinesis Video Stream service. Am I right?

**Comment by MushMal** [comment]
Yes, you are right. We are adhering to the spec.

TL&DR; not every rfc is implemented and we take one at a time
