### ISSUE TITLE
[BUG] Memory leak

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#931]
**Logging**
[normal.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5514297/normal.log)
[abnomal.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5514298/abnomal.log)

**Describe the bug**
Quit the program after connectig several times, it shows memory leak. The value is integer multiple of 12060. I add printf in **instrumentedAllocatorsMemCalloc** and **instrumentedAllocatorsMemFree**. In abnormal.txt, it allocated 12060 twice but released only once.

**Screenshots**
![image](https://user-images.githubusercontent.com/20633988/98618252-b6b09300-233b-11eb-9ac9-30475b154317.png)

**Comment by Nomidia** [comment]
[11-10-10-1080P-COM4.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5514492/11-10-10-1080P-COM4.log)

![image](https://user-images.githubusercontent.com/20633988/98621182-ab606600-2341-11eb-9649-863d8002f1a9.png)


![image](https://user-images.githubusercontent.com/20633988/98621192-aef3ed00-2341-11eb-9224-e73ba32f8123.png)

**Comment by disa6302** [comment]
@Nomidia , 

You are right. That is the location where memory leak occurs. Can you try the PR to see if the issue gets fixed?

**Comment by MushMal** [comment]
Fixed. Closing
