### ISSUE TITLE
[BUG] Logical error in freeSampleConfiguration

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#935]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/27b95a928c05810f901949fa02364acdb17b16e3/samples/Common.c#L834-L843

CHK should be before use.

**Comment by lherman-cs** [comment]
@Nomidia thanks for reporting this. This is definitely an error, the fix has been created here, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/936.
