### ISSUE TITLE
[QUESTION] Are SO_REUSEADDR and SO_REUSEPORT good to have during setsockopt() in Network.c?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#938]
I've been skimming through code.
Seems like the collision probability is so small (1/65535) when binding stun/turn ports there might be very little concern. Also seems like when we specify the port number of 0, the OS automatically allocates a free port, correct?

**Comment by MushMal** [comment]
Not sure about using the "reuse" API. Those really are geared towards a server-side application optimization and tight packing. Also, the support is not uniform.

Specifying port 0 instructs the OS to use the next available port.

Closing as answered but please reopen if you need more questions answered.
