### ISSUE TITLE
[BUILD] Building with mbedtls enabled breaks when using a non-default build tool (e.g. ninja.)

### ISSUE THREAD

**Issue by andyhoffy** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#943]
**Logging**
```
> cmake -G Ninja -DUSE_MBEDTLS=ON -DUSE_OPENSSL=OFF -DCMAKE_C_FLAGS="-fgnu89-inline" ..

...

[5/9] Performing configure step for 'project_libmbedtls'
-- The C compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python3: /usr/bin/python3.7 (found version "3.7.5") found components: Interpreter 
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS - Success
-- Configuring done
-- Generating done
-- Build files have been written to: <path_omitted>/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libmbedtls/build/src/project_libmbedtls-build
[6/9] Performing build step for 'project_libmbedtls'
FAILED: build/src/project_libmbedtls-stamp/project_libmbedtls-build 
cd <path_omitted>/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libmbedtls/build/src/project_libmbedtls-build && make -j4
make: *** No targets specified and no makefile found.  Stop.
ninja: build stopped: subcommand failed.
```

**Describe the bug**

After pulling latest branch and attempting to build using our default build system (ninja) I ran into a compilation failure. It seems to trace back to a manual override of cmake's build tool here:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/8a64e7feeb0d42f2917b3660819424bcd41534fe/CMake/Dependencies/libmbedtls-CMakeLists.txt#L33

It might be better to either not override (let the user specify multi-core building in their build system) or to detect the use of make and add flags in only that case?

**SDK version number**

Running from master or tag v1.4.0

**Open source building**

To reproduce:

```
> cmake -G Ninja -DUSE_MBEDTLS=ON -DUSE_OPENSSL=OFF -DCMAKE_C_FLAGS="-fgnu89-inline" ..
```

Using Ubuntu 18.04, ninja version 1.8.2, cmake version 3.18.4.

**To Reproduce**

(see "Open source building")

**Expected behavior**

Prior to this change, cmake configuration and compilation succeeded when using ninja as a build system.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by andyhoffy** [comment]
An agnostic way to build with paralellization may be to change this to:

```
diff --git a/CMake/Dependencies/libmbedtls-CMakeLists.txt b/CMake/Dependencies/libmbedtls-CMakeLists.txt
index 46dcd00f1..2a088a838 100644
--- a/CMake/Dependencies/libmbedtls-CMakeLists.txt
+++ b/CMake/Dependencies/libmbedtls-CMakeLists.txt
@@ -30,6 +30,6 @@ ExternalProject_Add(
     -DENABLE_TESTING=OFF
     -DENABLE_PROGRAMS=OFF
     -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
-  BUILD_COMMAND   make -j4
+  BUILD_COMMAND   ${CMAKE_COMMAND} --build . --parallel
   BUILD_ALWAYS    TRUE
   TEST_COMMAND    "")
```

**Comment by andyhoffy** [comment]
Suggested fix posted (above).

**Comment by MushMal** [comment]
I assume #945 fixes the build issue. I am renaming the issue and resolving. Please feel free to reopen.
