### ISSUE TITLE
[QUESTION] What message types are currently supported by the back-end server, and will it forward user-defined signaling message?

### ISSUE THREAD

**Issue by Teresa7755** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#947]
What message types are currently supported by the back-end server, and will it forward user-defined signaling message?

**Comment by MushMal** [comment]
@Teresa7755 the official answer is defined here: https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-websocket-apis.html

The 3 types of messages are Offer, Answer and ICE candidate.

I am going to close this issue as answered. Please don't hesitate to reopen if you have further questions
