### ISSUE TITLE
Set DEBUG_LOG_SDP but no local sdp printing

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#948]
After export DEBUG_LOG_SDP=TRUE, the local sdp is not printed. Because the sdp print log in setLocalDescription is ahead of createAnswer.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/98e36b7838c7c2c71433851e0417db2e1f7b91a7/samples/Common.c#L142-L148

**Comment by disa6302** [comment]
Oops. Let me fix this.
