### ISSUE TITLE
[QUESTION] Sample for streaming same video stream from master to multiple clients

### ISSUE THREAD

**Issue by HimanshuVerma18111989** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#951]
Hi Team,

Is there any sample which supports streaming same video stream from master to multiple clients? I am using kvsWebrtcClientMasterGstSample but looks like it only supports streaming to single client. When i try to open stream from other client, stream does not happen. Is there any other sample which supports this?

**Comment by disa6302** [comment]
@HimanshuVerma18111989 , 

Every master-viewer connection constitutes one peer connection. Can you explain your set up a little? 
Who are the viewers? Is it the embedded SDK or the browsers?

You can have a single master and multiple viewer configuration without any code changes. The signaling channel name must be appropriate.

What do you mean by "open stream from other client"?

**Comment by HimanshuVerma18111989** [comment]
Closing this question as i have found the answer.
