### ISSUE TITLE
[QUESTION] IceAgent failed with 0x5a000013

### ISSUE THREAD

**Issue by docee** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#967]
When IceAgent failed with `0x5a000013` appears, Alexa cannot play normally. What is the reason for this?

** Logging ** 
```
[main] 1605756903465 E src/conn/src/kvs_webrtc/kvs.c(126):[signaling-1] - IceAgentState executeFailedIceAgentState(): IceAgent failed with 0x5a000013
[main] 1605756904575 W src/conn/src/kvs_webrtc/kvs.c(124):[st_streaming] - IceAgent iceAgentShutdown(): TurnConnection shutdown did not complete within 1 seconds
```

**Comment by MushMal** [comment]
For any of the status codes you can check the public Include.h file. In this case it's 

`STATUS_ICE_FAILED_TO_NOMINATE_CANDIDATE_PAIR`

which is defined in

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L184


This is a higher-level status codes which means that after the candidate pair was selected it failed to finish the nomination stage. This is an indication that something had gone wrong with exchanging the messages - likely a bad network topology or something in that nature if I have to guess as you have not included any information that would make this issue actionable.

Please resolve this issue unless you have more details.
