### ISSUE TITLE
[QUESTION] Does sessionCleanupWait in Common.c have limited ability receiving incoming connections during sleep?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#971]
I'm trying to improve how the signaling client listens to incoming connections.
My question is when sessionCleanupWait goes to sleep and has yielded to other threads. Will incoming connections be ignored during this time until the sessionCleanupWait has woken up? So are there any other threads that are actively listening to connections and wake up the signaling client?

**Comment by MushMal** [comment]
Not sure if I understood the question. The session starts from the signaling service listening to the channel and receiving the offer from the viewer  (assuming we are talking about the master sample). So, if I understood it, the answer is the listener thread in signaling client is responsible for handling the message and calling the signaling client callback which is supplied by the sample. The signaling client automatically handles reconnects and error recovery but if the retries fail it will call error callback. The error handler in the sample signals the waking up of the sessionCleanupWait condition variable and the sample pulses the signaling client (frees and recreates) and reconnects. Does this answer your question?

**Comment by suggestedfixes** [comment]
Where is the listener thread for signaling client located, Signaling.c, lwsApiCalls.c? I'm experimenting with boosting the thread priority so that the poor device can handling incoming connections better.

**Comment by suggestedfixes** [comment]
Found one, "reconnectHandler"

**Comment by MushMal** [comment]
It’s called a listenerThread. The reconnectHandler is just that - handles the reconnects. You don’t need to boost the priority of the thread - it’s not doing much. You should profile it and see if there are other threads hogging the CPU. 

What’s the problem you are seeing anyway? Can you run debug logs and also check the cpu load?

**Comment by suggestedfixes** [comment]
For poor networks, the socket performance isn't very good and tends to ignore signaling messages.

**Comment by suggestedfixes** [comment]
Cpu load is around 9% idle.

**Comment by MushMal** [comment]
It might be platform specific perhaps. There isn’t anything that is actionable unfortunately

**Comment by suggestedfixes** [comment]
That's why it was a question. Thanks!
