### ISSUE TITLE
[QUESTION] How long is the latency for 1 master to N viewer video broadcast webrtc application ?

### ISSUE THREAD

**Issue by ajjiang48** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#975]
Hi,
We have done a simple experiment for 1 to 1 (1 master - webrtc test page and 1 viewer - our own ARM SoC platform running embedded Linux) video sending using webrtc (480p video streaming only from viewer to master, tried both STUN and TURN) and the latency is around 2 seconds (better using TRUN); we're interested in the latency on the same situation with more viewers. 

My question is:
1. is the underlay layer using IP multicast for webrtc video 1 to N (1 master, N viewers) or it's just 1 by 1 sending ? cause I think 1 by 1 sending affect the latency a lot.
2. How long is the latency for AWS webrtc video for 1 to 10 (10 is the maximum viewer per channel) case ? and how is the latency difference between each viewers ? , will the video displayed on each viewer synchronous ??

Thanks,
A.J.

**Comment by hassanctech** [comment]
At present the streams are unicast we do not support multicast.  ICE can only connect with a single peer, if a new peer wants to view the stream then a new ICE session must be created.

Have you tried to add more viewers to test whether you see high latency, might be a simple experiment?

Latency can be impacted by many things like your network, I would expect the latency to remain the same regardless of number of viewers.  If you observe something different then please provide details of your experiment, including WebRTC SDK version.

**Comment by disa6302** [comment]
Closing since this has gone stale. @ajjiang48 , if you have more questions, feel free to open a new issue.
