### ISSUE TITLE
How to use kvs webRTC to stream IP camera video[QUESTION]

### ISSUE THREAD

**Issue by nhanminhnhat1998** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#977]
I am trying to use webRTC to stream the footage from an IP camera to kvs. 

here is the gst pipeline that i base on the kvsWebrtcClientMasterGstSample

 pipeline = gst_parse_launch(
                "rtspsrc location=rtsp://{}:{}@192.168.1.5:554/axis-media/media.amp?camera=1 is-live=TRUE ! queue ! videoconvert ! "
                 "video/x-raw,width=1280,height=720,framerate=15/1 ! "
                 "x264enc bframes=0 speed-preset=veryfast bitrate=512 byte-stream=TRUE tune=zerolatency ! "
                 "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video",
                    &error);

please help me.

Thank you

**Comment by MushMal** [comment]
Not sure whether this is related to KVS at all. Perhaps you should get the pipeline working without any of the KVS assets first by using fakesink. There are also GStreamer forums that you can get some help. Also, there have been some answers in previous issues in KVS cpp sdk and c producer. Search the readme and the issues for some help with the pipeline

**Comment by nhanminhnhat1998** [comment]
yeah your right, if i just run the sample without changing anything I see this on kvs signalling channel 
![image](https://user-images.githubusercontent.com/21211975/100304502-02796280-2ff3-11eb-810d-213240ff4dd5.png)

I just learn about his webRTC, I am not sure how to create the correct gstreamer pipeline with IP camera as the source.

thank you for your help, I will look into GStreamer forums

**Comment by nhanminhnhat1998** [comment]
i found i solition here https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/521
