### ISSUE TITLE
recipe for target 'CMakeFiles/kvsWebrtcClientMaster.dir/all' failed

### ISSUE THREAD

**Issue by thasin96** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#978]
**Logging**
```
[ 85%] Linking C executable kvsWebrtcClientMaster
/home/thasin/Documents/kvs/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/lib/libwebsockets.a(unix-caps.c.o): In function `lws_plat_drop_app_privileges':
unix-caps.c:(.text+0x341): undefined reference to `cap_get_proc'
unix-caps.c:(.text+0x35d): undefined reference to `cap_set_flag'
unix-caps.c:(.text+0x365): undefined reference to `cap_set_proc'
unix-caps.c:(.text+0x385): undefined reference to `cap_free'
unix-caps.c:(.text+0x391): undefined reference to `cap_get_proc'
unix-caps.c:(.text+0x3aa): undefined reference to `cap_set_flag'
unix-caps.c:(.text+0x3b2): undefined reference to `cap_set_proc'
unix-caps.c:(.text+0x3d2): undefined reference to `cap_free'
../open-source/lib/libcrypto.a(threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x16): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
CMakeFiles/kvsWebrtcClientMaster.dir/build.make:121: recipe for target 'kvsWebrtcClientMaster' failed
make[2]: *** [kvsWebrtcClientMaster] Error 1
CMakeFiles/Makefile2:103: recipe for target 'CMakeFiles/kvsWebrtcClientMaster.dir/all' failed
make[1]: *** [CMakeFiles/kvsWebrtcClientMaster.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2

```

**Describe the bug**
While building the sdk, it throws cmake error.
**SDK version number**
Latest SDK

**To Reproduce**
1. clone the repository
2. sudo apt-get install libssl-dev libcurl4-openssl-dev liblog4cplus-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools
3. cmake .. -DBUILD_STATIC_LIBS=TRUE
4. make
5. See error

**Expected behavior**
It should build the application

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser  chrome

**Comment by MushMal** [comment]
Seems like you have an issue with some OpenSSL dependencies. Are you able to build the non-static build ok?

Re-setting the “bug” tag

**Comment by thasin96** [comment]
I will try and update you soon

**Comment by thasin96** [comment]
I am able to build the non-static build :+1:

**Comment by thasin96** [comment]
I am getting another issue with latest build.

ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002

After statring master, the log says, 

```
[KVS GStreamer Master] Signaling client connection to socket established
[KVS Gstreamer Master] Beginning streaming...check the stream over channel signal-name
```
But when viewer is started the above errror occurs. 

Comlpete Log:
```
[KVS GStreamer Master] Signaling client connection to socket established
[KVS Gstreamer Master] Beginning streaming...check the stream over channel signal-name
======================================================================rtspsrc location=rtsp://127.0.0.1:7001/e3e9a385-7fe0-3ba5-5482-a86cde7faf48 user-id=user user-pw=pass short-header=TRUE ! rtph264depay ! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video======================================================================2020-11-26 08:45:07 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
2020-11-26 08:45:07 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
2020-11-26 08:45:07 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x00000002
2020-11-26 08:45:07 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2020-11-26 08:45:07 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2020-11-26 08:45:07 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2020-11-26 08:45:07 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2020-11-26 08:45:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
2020-11-26 08:45:13 ERROR   iceAgentAddRemoteCandidate(): operation returned status code: 0x5a000005
```

Any thought about this issue? 

I am passing rtsp-url as stream-source. For that I have modified `kvsWebRTCClientMasterGstreamerSample.c`

**Comment by MushMal** [comment]
0x00000002 is the invalid argument error. Are you getting this error with the stock master sample with absolutely no modifications? Is there anything specific to your scenario? How can we reproduce this issue?

**Comment by thasin96** [comment]
i have modified the stock master sample application. Because, I want to use rtsp as source for master.  Do you want me to share the new modified application here?

**Comment by thasin96** [comment]
One more thing is, The same modification was working in older WebRTC sdk (~ 4 months ago build). The reason, I wanted to use new build is based on this suggestion https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/656

**Comment by MushMal** [comment]
No, please run the stock application and get the debug logs. If this reproduces then it would reproduce on the stock application.

**Comment by thasin96** [comment]
@MushMal - I actually need rtsp as my source. So, I have made modification according to that. The modification is in sendGstreamerAudioVideo function:

I have added/modified pipeline like below. 
```
sprintf(buffer, "rtspsrc location=%s user-id=%s user-pw=%s short-header=TRUE ! rtph264depay ! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! appsink sync=TRUE emit-signals=TRUE name=appsink-video", url, user, pass);

     pipeline = gst_parse_launch(
                                 buffer,
                                 &error);
```

I commented pipeline logic's switch block.

**Comment by MushMal** [comment]
We have a set of test suites targeting ice negotiation. These have been passing ok or otherwise we wouldn’t merge. Same with the samples. The media pipeline modification has no bearing on ice negotiations. This is why I would like to reproduce this on stock master sample. If this reproduced then we will look into it. If not, you will need to debug your modifications.

**Comment by thasin96** [comment]
@MushMal - I thik it's codec issue. After removing short-header=TRUE ! rtph264depay !  from pipeline i am able to get video on viewer js page. But still it throws the warning message `iceAgentAddRemoteCandidate`. 

I have a doubt, Once viewer is stopped and then start again i am not able to view video from master but able to send message. Is this designed as such?

**Comment by MushMal** [comment]
@thasin96 we really need more precise and reproducible scenario to be able to help.

* The format of the elementary stream has to match to the existing transceiver type. Make sure you have configured the pipeline like in the samples.
* Cut a separate issue with every detail for the re-connect issue. Include debug logs, detailed scenario info, run the scenario with stock sample and no modification, include the platform details, etc... 
* Search for the existing issues for answers.

I am closing this issue. Please don't hesitate to cut a new one or reopen.

**Comment by atyshka** [comment]
@MushMal Petition to reopen? This thread got a little off track but a solution to the original issue was never explained. I am also having the issue with ```undefined reference to `pthread_atfork' ``` when trying to build staticly, no issues with the non-static build. Using Ubuntu 18.04

**Comment by MushMal** [comment]
I would rather leave this as is and cut a new issue if there is any. Please ensure to include the details. If this is a build issue you have then please check the existing Travis CI runs to adapt for your needs as we have runs with static build.
