### ISSUE TITLE
use of amazon-kinesis-video-streams-webrtc-sdk-c for IoT devices

### ISSUE THREAD

**Issue by pankeshpatel** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#981]
As suggested by the author (@hassanctech ) that `amazon-kinesis-video-streams-webrtc-sdk-c` SDK is not supporting TCP candidates. 

Can you please suggest how this SDK is used on embedded devices such as NVIDIA Jetson Nano, Rpi??

In my current project, I would like to use this SDK for live streaming from a camera attached with NVIDIA Jetson and access the live video stream from my mobile iOS device. 

My understanding is that I need to run `amazon-kinesis-video-streams-webrtc-sdk-c` on an embedded device such as NVIDIA jetson Nano to stream video. And Second, I need to use  `amazon-kinesis-video-streams-webrtc-sdk-iOS` for my iOS App, Is that correct?

Second question -- how can I use `amazon-kinesis-video-streams-webrtc-sdk-c` on devices such as RPi, Jetson nano for streaming? Any resources/sample code you would like to suggest???

**Comment by MushMal** [comment]
Perhaps the comment is about the TURN server not supporting plain TCP. The SDK runs ICE negotiations where it probes different P2P candidates and TURN candidates. All P2P candidates are UDP based.

The embedded SDK (this project) supports embedded devices. There are samples that you can compile and run on these platforms. 

Could you perhaps target your question to what exact problem you are having?

**Comment by disa6302** [comment]
@pankeshpatel , 

Please open a new issue detailing what the exact issue is.
