### ISSUE TITLE
[QUESTION] Is it ok to have only one side of peer to have relay ice config?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#982]
I think the current device is having resource limitations, it might have trouble reliably getting turn ice config. Currently still testing with asyncIceConfig = FALSE.
We are tweaking kernel network parameters to decrease the odds of this failing.

Which allows one question to arise.
Is it ok to have the master side of the peer (device side) to configure only stun servers, and the viewer side of peer to have both stun and turn servers configured.

One particular edge case that I'm not uncertain about is whether if this configuration will work if the device is sitting behind a symmetric NAT with local stun candidate, but paired with a relay remote candidate from the viewer.

**Comment by MushMal** [comment]
Perhaps I am not understanding the questions. Could you please rephrase it?

* In a limited environment setting asyncIceConfig to FALSE is the right choice. For the master, it has almost no advantage as the session initialization happens later when the viewer connects and there is no advantage at all running ICE config in parallel. Please set this to false.
* If your master is set to not use TURN then any viewer attempting to connect to it will fail if there is no way to establish P2P connection.

**Comment by suggestedfixes** [comment]
If your master is set to not use TURN then any viewer attempting to connect to it will fail if there is no way to establish P2P connection.
- This is not true, the cases I'm certain about are host, server reflexsive and peer reflexsive case where the master side could use STUN servers to communicate with the other peer without TURN servers given sitting behind a non-symmetric NAT.
- The case I'm not certain about is when the viewer has a relay candidate, would it be able to pair with a master sitting behind a symmetric NAT without TURN.

**Comment by MushMal** [comment]
Perhaps you are confusing the functionality of the STUN server. All it does is pings back the public IP. The client then uses its public IP to punch through NAT. It's not always possible. In either case, if you disable TURN then that's it - you won't get relay at all and all your streaming will have to go through P2P which can use, as you said, the reflexive pairs. It's not always possible to go through NAT even with the reflexive pair info.

Hope this makes it clear.

**Comment by suggestedfixes** [comment]
What if the viewer tries to pair a relay candidate with a server reflexive candidate with a peer. Would this scenario work because there is at least a relay server?

**Comment by MushMal** [comment]
The rules are described in the RFCs. Each pair deals with their own ICE server negotiation. In case of JS, the negotiations are done by the Google's WebRTC implementation.

At the end of the day, if the P2P (with or without the reflexive candidates) is not possible then the TURN is used (unless it's disabled)

**Comment by suggestedfixes** [comment]
Long story short, there is a 4-way handshake going on.
In case of a stun server reflexive candidate pairing with relay candidate. If the stun candidate can talk to the relay candidate, chances are there will be a successful connection. What is unknown is how NAT maps an IP:port in the internal network to external IP:port, and once we have an external IP:port with relay, I think the odds will be very hight that it might be sticky with the relay with TCP.

**Comment by suggestedfixes** [comment]
Ice config credentials have a TTL of 300 seconds. If they were longer, it might be worthwhile to cache them to reduce the odds of fail to fetch ice configs.

**Comment by MushMal** [comment]
TCP is only used with TURN. P2P always uses UDP.

TURN server has a short allocation time. Once the DTLS channel gets established, it will auto-refresh and extend the life of the TURN connection

**Comment by suggestedfixes** [comment]
Let me summarize, there's no guarantee this will work. (local: camera/viewer, remote: browser)
```
   +-------------------------------+
    .|                               |
     | Local     Remote              |
     | +-----+    +----+   +default?  |
     | |Srflx|    |Relay|   +valid?    |
     | +-----+    +----+   +nominated?|
     |                    +State     |
     |                               |
     |                               |
     |          Candidate Pair       |
     +-------------------------------+
```

**Comment by suggestedfixes** [comment]
And I suppose there's no way to punch a hole through peer's relay because of credentials?

**Comment by MushMal** [comment]
The relay works like this

peer1 <=> relay <=> peer2

The relay is "transparent" - it can't even listen to the traffic as the traffic is DTLS encrypted. Each peer "thinks" it talks to the other.

**Comment by suggestedfixes** [comment]
So it isn't like this: peer1 <=> relay1 <=> relay2 <=> peer2.

**Comment by MushMal** [comment]
Logically, there is no difference between a single TURN server or multiple turn servers creating a tunnel. The stream is protected. At any rate, from the perspective of the peers, they communicate with each other transparently even though they use the TURN server address.

**Comment by suggestedfixes** [comment]
But to deviate from your diagram and my diagram a bit. Another illustration. Those three scenarios should work because there is a relay in the middle?
peer1 <=> host <=> relay2 <=> peer2.
peer1 <=> stun1 <=> relay2 <=> peer2.
peer1 <=> prflx <=> relay2 <=> peer2.

**Comment by MushMal** [comment]
You misunderstand the concept of the TURN and STUN. STUN is used to get the public IP address only. Peer will use this address as one of the candidates. Very similar to trying its local address. In either case, in this case the connection is udp based and will establish p2p, in some cases with NAT. This is what’s known as hole punching.

If that doesn’t work, the peers fall back to TURN which acts as a relay. This is what ICE server configuration is used for. It contains the urls and the credentials for the turn server to use.

**Comment by suggestedfixes** [comment]
From chrome debug: I do see those pairs:
 host, relay
 prflx, relay
 srflx,  relay

**Comment by suggestedfixes** [comment]
Also because those pairs have higher priority scores than relay, relay.

**Comment by suggestedfixes** [comment]
I suppose what you are trying to say is that there exists a case where at least a pair is (relay, relay).

**Comment by suggestedfixes** [comment]
For example, here is an example where the browser relay gets matched to a srflx remote candidate. 


Statistics RTCIceCandidatePair_3m9mAgyG_5WbBY84x
--
timestamp | 12/1/2020, 5:16:17 PM
transportId | RTCTransport_0_1
localCandidateId | RTCIceCandidate_3m9mAgyG
remoteCandidateId | RTCIceCandidate_5WbBY84x
state | succeeded
priority | 144151471053602814
nominated | true
writable | true
bytesSent | 68071
[bytesSent_in_bits/s] | 2800
bytesReceived | 7909243
[bytesReceived_in_bits/s] | 242240
totalRoundTripTime | 11.049
[totalRoundTripTime/responsesReceived_in_ms] | 0
requestsReceived | 4
requestsSent | 2
responsesReceived | 60
responsesSent | 4
consentRequestsSent | 61
currentRoundTripTime | 0.179
availableOutgoingBitrate | 300000
availableIncomingBitrate | 395981




Statistics RTCIceCandidate_3m9mAgyG
--
timestamp | 12/1/2020, 5:15:10 PM
transportId | RTCTransport_0_1
isRemote | false
networkType | unknown
ip | 3.134.76.195
port | 63934
protocol | udp
relayProtocol | udp
candidateType | relay
priority | 33562879
deleted | false


Statistics RTCIceCandidate_5WbBY84x
--
timestamp | 12/1/2020, 5:15:48 PM
transportId | RTCTransport_0_1
isRemote | true
ip | 172.218.223.215
port | 55077
protocol | udp
candidateType | srflx
priority | 1694498815
deleted | false

**Comment by MushMal** [comment]
Recommend reading the RFCs referenced in the codebase to understand the algorithm. The idea is to match the own and the peer IP address. Both can be translated via NAT. The permutation is used and if the binding succeeds then the connection is deemed viable. With the p2p candidates the SDK attempts to also bind the TURN candidates in case the p2p is not possible.

**Comment by disa6302** [comment]
Closing based on tag.
