### ISSUE TITLE
can't resolve symbol 'HMAC_CTX_new' (linux-mips32)

### ISSUE THREAD

**Issue by devxiaoyi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#99]
Hi, I cross-compiled the program and run on linux-mips32 platform , then I got `./kvsWebrtcClientMaster: can't resolve symbol 'HMAC_CTX_new'`. 
I search the code related to "HMAC_CTX_new" , only find `-DLWS_HAVE_HMAC_CTX_new=1` in libwebsockets-CMakeLists.txt . And google given little information.
May I kown the definition's effect ？ And how can I handle it ？
Best Regards and Merry Christmas ！

**Comment by devxiaoyi** [comment]
Perhaps It doesn't match my openssl library. I will try it .

**Comment by Nomidia** [comment]
Openssl1.1.0以上的用HMAC_CTX_new，老的是HMAC_CTX_init
vi libwebsockets-3.2.0/lib/tls/openssl/lws-genhash.c +98
![image](https://user-images.githubusercontent.com/20633988/71454904-c7145980-27cd-11ea-9e35-1aab23783c81.png)

**Comment by devxiaoyi** [comment]
thx !
