### ISSUE TITLE
[QUESTION] How to force TCP relay?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#991]
We have encountered a network topology situation where it's possible to make a connection within the same network.
However, it's almost impossible to view the office cameras from an external network even with a regular UDP relay. We were thinking, maybe if we force TCP turn, we might have a chance connecting. 

We found that although we have chosen TCP URLs from ice-config for both sides and forcing turn. 
Although having only TLS ice URL only Chrome still thinks the local candidate is using UDP. 
On the camera side (master, v1.3.0), it is also receiving UDP candidates and sending UDP candidates, although we specified to use the TCP relay URL.

The code is a bit clumsy because we know the third URI from each group is always TCP and this is for one-time experimentation.

Camera side code:
```
    if (pSampleConfiguration->useTurn) {
        // Set the URIs from the configuration
        CHK_STATUS(awaitGetIceConfigInfoCount(pSampleConfiguration->signalingClientHandle, &iceConfigCount));

        for (uriCount = 0, i = 0; i < maxTurnServer; i++) {
            CHK_STATUS(signalingClientGetIceConfigInfo(pSampleConfiguration->signalingClientHandle, i, &pIceConfigInfo));
            for (j = 0; j < pIceConfigInfo->uriCount; j++) {
                CHECK(uriCount < MAX_ICE_SERVERS_COUNT);
                if (STRSTR(pIceConfigInfo->uris[j], "transport=tcp") != NULL) {
                    STRNCPY(configuration.iceServers[uriCount + 1].urls, pIceConfigInfo->uris[j], MAX_ICE_CONFIG_URI_LEN);
                    STRNCPY(configuration.iceServers[uriCount + 1].credential, pIceConfigInfo->password, MAX_ICE_CONFIG_CREDENTIAL_LEN);
                    STRNCPY(configuration.iceServers[uriCount + 1].username, pIceConfigInfo->userName, MAX_ICE_CONFIG_USER_NAME_LEN);
                    DLOGD(">>> ice config: %s", pIceConfigInfo->uris[j]);
                    uriCount++;
                }
            }
        }
    }
    pSampleConfiguration->iceUriCount = uriCount + 1;
    CHK_STATUS(createPeerConnection(&configuration, ppRtcPeerConnection));
```
 
Browser side code:
```
    if (!formValues.natTraversalDisabled) {
          getIceServerConfigResponse.IceServerList.forEach(function(iceServer) {
              var uris = iceServer.Uris;
			  uris.shift();
			  uris.shift();
			  iceServers.push({
                  urls: uris,
                  username: iceServer.Username,
                  credential: iceServer.Password,
              });
			 }
          );
    }

    console.log('[VIEWER] ICE servers: ', iceServers);
```

**Comment by suggestedfixes** [comment]
Actually the issue we are seeing might not be related to relay server. It might be related to the signaling because we can send messages to the signaling channel, but the camera can't talk back.

**Comment by suggestedfixes** [comment]
But it will be nice to make TCP TLS working.

**Comment by suggestedfixes** [comment]
Double checked, we are getting back udp relay candidates back, but no pairing.

**Comment by suggestedfixes** [comment]
Chrome pretty much returning errors for tcp turn candidates, very high likelihood there is a turn configuration issue?
```
12/6/2020, 7:00:43 PM | icecandidateerrorurl: turns:3-21-52-195.t-c01cb9af.kinesisvideo.us-east-2.amazonaws.com:443?transport=tcp host_candidate: :0 error_text: TURN host lookup received error. error_code: 701
-- | --
12/6/2020, 7:00:43 PM | icecandidateerrorurl: turns:3-21-52-195.t-c01cb9af.kinesisvideo.us-east-2.amazonaws.com:443?transport=tcp host_candidate: :0 error_text: TURN host lookup received error. error_code: 701
```

**Comment by suggestedfixes** [comment]
After a bit of reading. Does the current SDK support ICE TCP?
https://tools.ietf.org/html/draft-ietf-mmusic-ice-tcp-08

**Comment by MushMal** [comment]
The SDK supports TCP protocol (secure TCP) for TURN. It will try to negotiate P2P and TURN if configured to do so.

It's not clear what your issue is. Likely a routing issue within your network. Not sure how to help - perhaps running some network testing without any of the KVS SDK stuff? Perhaps, you could state the issue properly? As I read through from the top of the issue I see you have a UDP connection issue related to the network topology, then, you have an issue with the signaling and then with TCP which I assume is the TURN?

**Comment by suggestedfixes** [comment]
We only did some browser-side test as the customer's network was not yet available. We will run discoverNatBehavior as soon as we can get a hold of the customer's environment.

Troubleshooting steps:
- Chrome from an external network.
- Unknown customer network topology (camera/master). Suspected symmetric NAT.
- looking at chrome://webrtc-internals.

Observations:
- Customer side only sent a host candidate. No srflx candidates received.
- Chrome side only collecting UPD turn candidates on the browser side.
- Chrome emitting errors on TLS TCP servers, so the chrome side cannot add TCP TLS candidates.

Speculations:
- customer's network blocked UDP, making ice handshakes difficult.
- suspected symmetric NAT.
- possibility that the current TCP TLS turn servers are not compatible with current version of chrome.

Nice to have:
- instructions on enabling TCP TLS, third server on each server group.
- double-check if the newest chrome is compatible with with TCP TLS.

**Comment by suggestedfixes** [comment]
Initial findings about stun:
AWS's stun server not compatible for this network scenario.
Compared with a public stun, where it returns a valid external IP.
![stun_error](https://user-images.githubusercontent.com/61390265/101378823-6bb96b00-3868-11eb-9b3e-6ca18fca4a93.PNG)
![stun_public](https://user-images.githubusercontent.com/61390265/101378830-6d832e80-3868-11eb-8da0-c21ec6c15bb5.PNG)

**Comment by suggestedfixes** [comment]
Will be manually grabbing TURN and try to enter the TURN credentials within 5 minutes.

**Comment by suggestedfixes** [comment]
TURN is working this morning. 
Question:
- do both sides have to use the same turn server?

**Comment by MushMal** [comment]
I am not familiar with the customers environment so I can't comment on it.

* We should indeed add more documentation and have easy ways to configure TURN/P2P and set priorities if the customer wants to prioritize things differently.
* The clients get a list of TURN servers from getIceServerConfiguration API call and submit these to the WebRTC PeerConnection object to be passed to the ICE agent for the negotiations. ICE would use one of the URLs. From the perspective of ICE - the TURN is the other peer. Each of the peers in participation - master/viewer can chose one of the TURN URLs.

**Comment by suggestedfixes** [comment]
Typically, getIceConfig returns 2 domains, each domain contains 3 versions of turn: udp plaintext, udp tls, and tcp tls).

What if the camera chooses the first domain and the browser chooses the second domain, would this setup work?

**Comment by MushMal** [comment]
As long as they use the TURN servers vended out by our backend.

Please resolve this if you have no further questions regarding TURN

**Comment by MushMal** [comment]
Any further action on this issue? If not, please resolve this

**Comment by idonahum1** [comment]
@suggestedfixes 
Can you please explain me how did you resolve this network issue? 
I have the same situation as you described. 
Customer network is very strict. It uses proxy and also blocks all udp transport. Only TCP allowed. It will be great if you can explain me how things worked out on your side
