### ISSUE TITLE
how to open more than 2 view with kvs webRTC using rtspsrc as video source 

### ISSUE THREAD

**Issue by nhanminhnhat1998** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#992]
Hello everyone,

I ran to an issue where my modified ./kvsWebrtcClientMasterGstSample only show with one viewer and if that viewer close it will lose the footage as well, even though the viewer still receives data

here is the part where I added to the script
`pipeline = gst_parse_launch(
                    "rtspsrc location=url do-retransmission=FALSE buffer-mode=synced latency=500 drop-on-latency=TRUE short-header=TRUE debug=TRUE !"
                    " queue ! rtph264depay aggregate-mode=zero-latency !"
                    "video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! "
                    "appsink sync=TRUE emit-signals=TRUE name=appsink-video max-buffers=0",
                    &error); `

here is the 1st time I run the code and view the stream
![image](https://user-images.githubusercontent.com/21211975/101275421-9e784a80-37f9-11eb-92a9-ef57b8f11322.png)

here is the 2nd time, when I try to reopen the stream
![image](https://user-images.githubusercontent.com/21211975/101275437-d41d3380-37f9-11eb-8b7e-4e7e2b362d0f.png)

## I am not sure if that is the gst problem or kvs?

thank you so much for your help

**Comment by MushMal** [comment]
It's hard to guess what's wrong with your code. Try the stock samples first. The master sample will support multiple viewers as long as they have different client ids.

For GStreamer related issues you can file an issue in GStreamer related forums or search for existing issues there.

You can also contact your AWS technical account management team that can assist you with your code.

**Comment by nhanminhnhat1998** [comment]
cool, thank you for your suggestions
