### ISSUE TITLE
[Question] Service roles are not working when trying to connect to signaling channel.

### ISSUE THREAD

**Issue by HimanshuVerma18111989** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#998]
Hi Team,

When i use IAM user, i am able to connect to signaling channel but when i use service roles to connect to signaling channel, my code is unable to connect to signaling channel and failing with "Invalid credentials error". Do you know how to use service roles with C library?

**Comment by MushMal** [comment]
Removing "bug" tag as there are no identified bugs.

SDK operates with credential providers. There are few defined currently. Static, file and IoT based are the examples of what we provide out-of-the-box. If you need custom credential provider then you need to build your own.

If this is a general question about how IAM roles and service roles work, please contact AWS technical account management team for more info.

If you need help integrating with the existing credential providers please cut a separate issue with detailed question.

Please resolve this issue.

**Comment by juanitosvq** [comment]
Hey @MushMal so just to confirm, if we wanted our EC2 instance to act as master using the IAM role linked to it, there is nothing in the current implementation to do that, is that correct?
